### ISSUE TITLE
Define "set-like behavior"

### ISSUE THREAD

**Issue by gabrielgrant** [json-api/json-api#100]
The text following the example of removing a comment from a photo states "to-many relationships have set-like behavior in JSON API"

I don't see this "set-like behavior" mentioned anywhere in [the JSON Patch RFC](http://tools.ietf.org/html/rfc6902), so it should be explicitly defined.

It seems there are four salient points:
1. Sets are represented as JSON Arrays
2. The order of that array should be explicitly ignored
3. `add` operations should use only the [end-of-the-array reference ("-")](http://tools.ietf.org/html/rfc6902#section-4.1) as their target
4. References should be by ID rather than array index (see #99)

Does this sound good? If so, I can go ahead and submit a patch for this.

**Comment by steveklabnik** [comment]
@wycats?

​I will say this was originally written against the later drafts of JSON PATCH, so maybe that behavior was defined and then removed?

**Comment by steveklabnik** [comment]
Adding to 1.0.

**Comment by wycats** [comment]
@gabrielgrant everything you said above is correct. A PR for it would be most welcome.

**Comment by dgeb** [comment]
I believe this is all covered by #237, but please send a PR if anything has been missed.
