### ISSUE TITLE
What to return if a collection is empty?

### ISSUE THREAD

**Issue by gabrielgrant** [json-api/json-api#101]
What should be returned when an empty collection is queried?

a hash with an empty array?

example 1

```
GET /photos

HTTP/1.1 200 OK
Content-Type: application/json

{
  "photos": []
}
```

example 2

```
GET /photos

HTTP/1.1 200 OK
Content-Type: application/json

{
  "photos": [],
  "meta": {
    "client-ids": true
  }
}
```

or an empty hash?

example 3:

```
HTTP/1.1 200 OK
Content-Type: application/json

{}
```

example 4:

```
HTTP/1.1 200 OK
Content-Type: application/json

{
  "meta": {
    "client-ids": true
  }
}
```

I think a hash with an empty array is probably less likely to cause surprises and would be happy to provide a patch if you agree.

**Comment by steveklabnik** [comment]
I'm about to get on a plane and don't have time to properly review the relevant part of the spec, but will come back to it later tonight.

My understanding at current would be that it's example 1, as per the spec right now. Why would it not be?

**Comment by gabrielgrant** [comment]
sorry, just updated the issue to number my examples sanely -- i assume you were referring to the first example 1 (not the second one that is now example 3)?

like i said, my assumption is that example 1 & 2 are correct, but thought it should be spelled out explicitly. Right now the spec covers the cases of "singular resources" and says when "the length of an array at a resource key is _greater than one_, the value represents a list of documents." But it doesn't specify anything for the case when a resource collection is empty.

sorry if I'm being too pedantic... but that's kind of what specs are all about, right? :)

**Comment by steveklabnik** [comment]
Specs are about being pedantic, but there's also a level of explicitness vs. implicitness.

I don't think that this should belong in the spec proper, but I wouldn't mind it being in the examples. (and i meant 1)

**Comment by gabrielgrant** [comment]
also: have a good flight!

**Comment by gabrielgrant** [comment]
woops, deleted my actual comment :P 

Yes, I agree: at a certain point, overly-explicit documents just become basically unreadable. [RFC 6902](http://tools.ietf.org/html/rfc6902#appendix-A) has an appendix of specific examples to keep the core spec more lean. Are you alright with me adding one of those to JSON API?

**Comment by steveklabnik** [comment]
Yes, I wanted to do it myself, but if you're willing, please do.

**Comment by ahx** [comment]
When using the full-url style in the links object, what would you return for an empty relation? 
I think to just omit the attribute might be problematic, so we should return `null` instead, right?

Example 1: A Post _with_ an Author and Comments:

```
{
  "posts": [{
    "id": "1",
    "title": "Rails is Omakase",
    "links": {
      "author": "http://example.com/people/1",
      "comments": "http://example.com/comments/5,12,17,20"
    }
  }]
}
```

Example 2: A Post _without_ an Author or Comments:

```
{
  "posts": [{
    "id": "1",
    "title": "Rails is Omakase",
    "links": {
      "author": null,
      "comments": null
    }
  }]
}
```

**Comment by steveklabnik** [comment]
Especially now that we have single responses with no arrays, we should explicitly mention this in the spec.

**Comment by dgeb** [comment]
Here's my take on these various issues:

A request for a collection can still return an empty array:

```
GET /photos

HTTP/1.1 200 OK
Content-Type: application/json

{
  "photos": []
}
```

A request that for a single resource can return a 404 (with or without an error object):

```
GET /photos/1

HTTP/1.1 404 Not found
```

A request for multiple individual resources can also return a 404 along with error objects that enumerate the missing resources.

Has-one relationships that are blank should be `null`, as in @ahx's example 2 above:

```
{
  "posts": [{
    "id": "1",
    "title": "Rails is Omakase",
    "links": {
      "author": null,
      "comments": null
    }
  }]
}
```

@steveklabnik do you agree with all the above? If so, I agree that some of these points could be better spelled out in the spec, especially the point about `null` values.

**Comment by steveklabnik** [comment]
I agree that all these are reasonable, yes.

**Comment by diosney** [comment]
Just as a sidenote, I've been using for a while @dgeb approaches for cases 1 (200 with empty array on collections) and 2 (404 on single resources) and so far is working for me very smoothly.

**Comment by dgeb** [comment]
@steveklabnik I'll send a PR to clarify `null` relationships

@diosney nice! :+1:

**Comment by dgeb** [comment]
I missed something when I copied that example from @ahx. I did mean that has-many relationships should be represented by an empty array and only has-one relationships should be represented by `null`.

This is corrected:

```
{
  "posts": [{
    "id": "1",
    "title": "Rails is Omakase",
    "links": {
      "author": null,
      "comments": []
    }
  }]
}
```

**Comment by dgeb** [comment]
I believe this is all clarified in the spec as of #341 (RC2)
