### ISSUE TITLE
2 different relationships to same resource

### ISSUE THREAD

**Issue by yp28** [json-api/json-api#1014]
Hi all,

We're implementing the JSON API specification in one of our new API's, and came across a problem we could not find a solution or recommendation for.

One of the resources in our API, has two different relationships to the same resource type. For example:
- Order[ShippingAddress] => Address
- Order[InvoiceAddress] => Address

Now, when getting a single result of the Order resource, including both invoice and shipping address, it's hard to distinguish which is which.

Is there anyone who has come across this problem, and how did you fix it?

**Comment by ethanresnick** [comment]
The solution is to use [resource identifier objects]() in each relationship object to indicate which included resource is which. Doing this is actually required by the "full linkage" requirement so that clients aren't confused:

> Compound documents require "full linkage", meaning that every included resource MUST be identified by at least one resource identifier object in the same document...

The payload, then, would look something like this:

``` js
{
  "data": {
    "type": "order",
    "id": "1",
    "attributes": { /* ... */ },
    "relationships": {
      "shippingAddress": {
        "data": { "type": "addresses", "id": "5" }
        // optionally add links here too
      },
      "invoiceAddress": {
        "data": { "type": "addresses", "id": "3" }
        // optionally add links here too
      }
    }
  },
  "included": [{
    // because of its type and id, this must be the shippingAddress.
    "type": "addresses",
    "id": "5",
    "attributes": { /* .... */ },
    "relationships": { /* ... */}
  }, {
    // because of its type and id, this must be the invoviceAddress.
    "type": "addresses",
    "id": "3",
    "attributes": { /* .... */ },
    "relationships": { /* ... */}
  }]
}
```

**Comment by yp28** [comment]
Thanks for your quick reply!
