### ISSUE TITLE
Clarify filter syntax recommendation

### ISSUE THREAD

**Issue by lukasoppermann** [json-api/json-api#1028]
Hey, 

reading the [Filtering](http://jsonapi.org/recommendations/#filtering) section on the recommendations page, I stumbled upon this part:

> It's recommended that servers that wish to support filtering of a resource collection based upon associations do so by allowing query parameters that combine filter with the association name.

The recommended syntax is:

> ?filter[post]=1

However I am not sure if the recommendation is ONLY when filtering based on relationships or if this syntax is also recommended, when filtering based on data/parameters.

E.g. if I want to show only items that have a status of `published=1` where published is an entry in the items database.

> ?filter[published]=1

Thanks for clarifying.

**Comment by arunbakt** [comment]
Hello,
 I am looking for an answer for this as well.  I see the katharsis implementation follows a model described in their docs. Is that the recommended way?
http://katharsis.io/docs

Thank you!

**Comment by beauby** [comment]
The [spec](http://jsonapi.org/format/#fetching-filtering) only imposes that, for filtering purposes, the `filter` query parameter should be used. It imposes no restriction whatsoever on what the value for the `filter` parameter can be, nor to what kind of filtering the server should do.
@lukasoppermann: long story short, your `?filter[published]=1` is totally valid.
