### ISSUE TITLE
Response for filtered request without result

### ISSUE THREAD

**Issue by lukasoppermann** [json-api/json-api#1030]
The specs and the recommendations do not mention anything about responses to filtered requests specifically. I would think that they are exactly the same as the responses for a normal `GET` request to an endpoint requesting a collection of resources.

Is this correct? I would like to see a sentence added stating this, as it would make it easier and more specific. This should be possible to be added to `1.0` imo as it does not change behaviour but rather clarifies indirectly implied behaviour.

Why is this good? I think that the less additional thinking you have to do, when reading specs, the better, so a statement about how to deal with this would be very good.

**Comment by jelhan** [comment]
I'm sorry that no one replied to your issue yet in such a long time. I'm currently going through the list of open issues to clean them up a little bit and came across yours.

What kind of clarification would you like to see? I'm not sure which potential difference a reader may expect depending if the requested collection is filtered or not. Would be great if you could elaborate a little bit what potential confusion should be avoided.

**Comment by freddrake** [comment]
The response to a filtered request will still include a collection as primary data, but the top-level ``links.self`` will include the additional query parameter.

Implementations are free to include additional information in the top-level ``meta`` structure if appropriate.

**Comment by jelhan** [comment]
@freddrake Thanks for your quick response. Do you think it is enough to clarify it for filter, sort and pagination in the [_Document Structure: Top Level_](https://jsonapi.org/format/#document-top-level) section, which specifies the `self` link? Or do you think we should add a clarification note to the filter, sort and pagination sections as well?

Pull request highly welcome!

**Comment by freddrake** [comment]
@jelhan: I think this is already sufficiently covered by the existing specification:

- [JSON:API 1.0: Top Level](https://jsonapi.org/format/1.0/#document-top-level)
- [JSON:API 1.1: Top Level](https://jsonapi.org/format/1.1/#document-top-level)

This section specifies that the **self** entry in a **links** object is present, it gives the link for the "current response document", which requires that *any* query arguments provided should be included in the value (and not just the filter, page and sort parameters).  This is distinctly different from links given in resources or relationships.

Nothing more is needed.

**Comment by jelhan** [comment]
@freddrake Thanks for your response. I think adding a note to the top-level links chapter may still be valuable to avoid confusion. If you have a few minutes, it would be great if you could review #1604.
