### ISSUE TITLE
How to deal with requests to create/update relationships while the related resources do not exist?

### ISSUE THREAD

**Issue by RussellLuo** [json-api/json-api#1033]
According to the [spec](http://jsonapi.org/format/), there may be a request to create an article with an author relationship:

```
POST /articles HTTP/1.1
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "data": {
    "type": "articles",
    "attributes": {
      "title": "JSON API paints my bikeshed!"
    },
    "relationships": {
      "author": {
        "data": { "type": "people", "id": "9" }
      }
    }
  }
}
```

Or a request to update the existing author relationship:

```
PATCH /articles/1/relationships/author HTTP/1.1
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "data": { "type": "people", "id": "12" }
}
```

If the related author (`/people/9` or `/people/12`) does not exist, how to deal with the above requests:
1. Respond errors for the missing author?
2. Always create/update the relationship regardless of the missing author?

**Comment by dgeb** [comment]
You should return a 404 here. See http://jsonapi.org/format/#crud-updating-responses-404

> A server MUST return 404 Not Found when processing a request that references a related resource that does not exist.
