### ISSUE TITLE
Specification should have a changelog

### ISSUE THREAD

**Issue by jfinkels** [json-api/json-api#1037]
I asked this question on the discussion forum but got no response: http://discuss.jsonapi.org/t/is-there-an-easy-way-to-see-the-differences-between-versions-1-0-and-1-1/353

Is there an easy way of seeing the differences between version 1.0 and 1.1 of the specification? Ideally, each new version of the specification would have a change log.

**Comment by ethanresnick** [comment]
Yes, we'll add a changelog. For now, the only new feature in 1.1 is the introduction of [@-Members](http://jsonapi.org/format/upcoming/#document-member-names-at-members). We fixed some errata too.

**Comment by lode** [comment]
Is there any update on this? Is there a changelog somewhere? Is `@-Members` still the only change?

**Comment by ethanresnick** [comment]
@lode The changelog is on the jsonapi.org homepage. I'm gonna close this.

**Comment by michaelkrupp** [comment]
@ethanresnick Your response is not very helpful. Mind providing a link to the actual changelog?

**Comment by ethanresnick** [comment]
@michaelkrupp https://jsonapi.org/#update-history

**Comment by shadowhand** [comment]
For anyone stumbling here, the link has changed to https://jsonapi.org/about/#update-history.
