### ISSUE TITLE
Are collections required to be ordered?

### ISSUE THREAD

**Issue by gabrielgrant** [json-api/json-api#104]
The patch in #91, by using a patch path including a zero-based index into the returned results from a GET, seems to formalize the notion that collections are ordered.

Are collections required to be ordered? Even if so, not referencing the record by ID seems to be begging for race conditions. What if a new document is inserted earlier in the collection between a GET request and it's corresponding PATCH?

At the bottom of "Updating a Document (PATCH)" > "To-Many Relationships" it is made explicit that "to-many relationships have set-like behavior in JSON API to limit the damage that can be caused by concurrent modifications." It seems collections should behave the same way, but instead collections are repeatedly referred to as "arrays" or "lists" (implying order) in the "singular resources" and "resource collections" sections.

Mind clarifying?

**Comment by guillec** [comment]
This falls in the same arena as our discussion on #99 . 
The difficulty of JSON Patch / Pointers not defining sets and how we want to handle that.

**Comment by steveklabnik** [comment]
Yes, I think we need to figure out exactly what's the deal between JSON PATCH and this.

/cc @wycats

**Comment by dgeb** [comment]
See #176 for a related discussion on JSON Pointers and PATCH. We definitely need to clarify this area in the spec.

**Comment by steveklabnik** [comment]
Adding to 1.0.

**Comment by wycats** [comment]
As I said in #100, I intentionally meant for collections to have set-like behavior, and (clumsily) tried to extend JSON PATCH with set-like semantics. Let's formalize that extension in JSON API and try to get it accepted by JSON PATCH (or at least in the popular JSON PATCH libraries, if possible).

@dgeb mind taking a whack at it? #100 describes the salient details, but it's 10 months old and I suspect @gabrielgrant may not be available to do the work now. (@gabrielgrant correct me if I'm wrong :smile:)

**Comment by dgeb** [comment]
Closed via #237, which discusses [URLs in general](http://jsonapi.org/format/#urls) as well as [PATCH URLs](http://jsonapi.org/format/#patch-urls).
