### ISSUE TITLE
id fields conflict with pretty much every other system

### ISSUE THREAD

**Issue by bpappin** [json-api/json-api#1040]
The documentation specifies that a resource must contain two fields; called "id" and "type".

However this conflicts with pretty much every other system that has to read the data, and prevents reuse and automatic mapping of JSON data to local schema.

The term "id" should be reserved for the local datastore, and the ID of transmitted data should be a distinct field.

For a use case, I want to transmit Widget `{id:"123abc", type:"widget"}` from the server datastore. 
On the client I want to receive the Widget, but my local ID is also called "id", so what I want it to see is Widget `{remote_id:"123abc", type:"widget"}` because my local Widget object already has an "id" attribute (e.g. Widget `{id:"555", remote_id:"123abc", type:"widget"}`).

This will be true of just about any system that stores a local copy of data, including webapps.

I am going to attempt to workaround this oversight by modifying the client to map the incoming JSON "id" field to "remote_id" in the local record, but the point is that I shouldn't have to, seeing at its a problem encountered often. 

If the spec allows for the fact that a transmitted ID is not locally authoritative, the mapping and conversion is usually much easier, and the human readable data much clearer as to the role a particular id field plays, which AFAIK, is one of the points of the spec in the first place.

**Comment by jamesplease** [comment]
@bpappin , are you unable to use the remote ID as the local ID? I haven't yet worked on a system that uses different IDs for local and remote resources. I tend to treat my local version as a representation of what's on the server, and in this system, using the same ID makes sense.

**Comment by bpappin** [comment]
You really want your data portable, so it needs to be ID agnostic, for the same reason you never use integer IDs in distributed data; conflicts arise easily and can go undetected, creating difficult to find bugs or worse.

In general, the ID only make sense within the context that the data is stored. Sometimes you can fudge or force things to match up, but it is generally considered poor practice.

In the case that made this apparent most recently and caused this issue to be created, we are storing data on mobile devices using various tools. The local IDs are integer based and only valid within the context of the local data. The remote IDs are properly encoded as digested strings. Obviously the two are incompatible, even if they have a 1-1 relationship (which is not exactly true, but reasonable for this description).
So, now we have ambiguity about what the term ID even means.
Semantics aside, If you are using a ORM library combined with a network serializer, this can become problematic, because they both want to use the same property.

Of course there are ways to work around that problem, but the very fact that we have the problem is a smell that should be considered.

**Comment by beauby** [comment]
I think your problem comes from the fact that you are expecting the transmitted JSON to be somewhat "directly usable" for local storage, whereas the spec is mostly about how the data is transmitted, not how it is stored at either end.

**Comment by bf4** [comment]
> id fields conflict with pretty much every other system

I can confirm that I have not had any trouble with resources requiring a value 'id' to be a unique identifier for the resource. Nor am I aware of any systems that prohibit a field named 'id'.

**Comment by bpappin** [comment]
I've had a long discussion about this with others, and it appears I am in the minority.

@beauby is correct, I want incoming data to be deserialized directly into useable objects for local storage. Doing away with translation code is pretty much the holy grail of remote data.
However the reasonable argument against that is that most serialization systems have a way to map data to fields, so the local data and remote data could have the same name and different field names.

For instance, if I'm using Gson and Cube ORM on android, i can do:

``` java
@Table(name="myfoo")
public class Foo {
   @Id
  private long id;

  @SerializedName("id")
  @Column(name="remote_id")
  private String remoteId;
}
```

Each system uses a different annotation set to map values.
Practical and workable as long as we don't get annotation name clashes.

However, I think here is an important distinction between an object's storage id and its portable permanent id (which should always be strings).

**Comment by bpappin** [comment]
I am going to close this issue.

Having now had extensive discussion with peers, I think I'm simply going to have to lump it.
Most people either don't understand what I'm talking about, or don't see the same issues I do :)
