### ISSUE TITLE
Relationships for favoriting, friending, etc

### ISSUE THREAD

**Issue by zmorris** [json-api/json-api#1042]
Hi I have implemented most of the json-api spec but am really struggling with non-resource relationships like favorites (where a favorite is not a resource, instead it is more like a pivot between a user and a resource):

http://jsonapi.org/format/#fetching-relationships

For example, say a user favorites an article on the site.  My first instinct was to have an endpoint for listing favorites like:

```
GET /me/favorites/100
{
  "data": [
    {
      "type": "articles",
      "id": 100,
      "attributes": {
        "title": "my article",
        "created_at": "2016-04-25T22:40:10Z",
        "updated_at": "2016-04-25T22:40:12Z"
      }
    }
  ]
}
```

The problem with this is that the `created_at` attribute corresponds to the date the article was written, instead of the date the user favorited the article and created a row in the `user_favorites` pivot table.  This makes organizing favorites difficult on the client.  I thought perhaps I should add the favorite data to the article's relationships:

```
GET /me/favorites/100
{
  "data": [
    {
      "type": "articles",
      "id": 100,
      "attributes": {
        "title": "my article",
        "created_at": "2016-04-25T22:40:10Z",
        "updated_at": "2016-04-25T22:40:12Z"
      },
      "relationships": {
        "data": [
          {
            "type": "favorites",
            "id": 101
          }
        ]
      }
    }
  ]
}
```

But this starts to get complicated because now I need `?include=favorites` and the favorite id doesn't correspond to the id in the URL.  I thought about adding meta data:

```
GET /me/favorites/100
{
  "data": [
    {
      "type": "articles",
      "id": 100,
      "attributes": {
        "title": "my article",
        "created_at": "2016-04-25T22:40:10Z",
        "updated_at": "2016-04-25T22:40:12Z"
      },
      "meta": {
        "favorite": {
          "created_at": "2016-05-01T01:02:03Z",
          "updated_at": "2016-05-01T01:02:03Z"
        }
      }
    }
  ]
}
```

But this feels like I'm making up my own spec.  So I decided to expose the pivot table row as a first class resource.  Now the response is:

```
GET /me/favorites/100
{
  "data": [
    {
      "type": "favorites",
      "id": 100,
      "attributes": {
        "created_at": "2016-04-25T22:40:10Z",
        "updated_at": "2016-04-25T22:40:12Z"
      },
      "relationships": {
        "data": [
          {
            "type": "articles",
            "id": 101
          }
        ]
      }
    }
  ]
}
```

I don't know how conceptually correct this is, or if it will work for all the other relationships like friendships, categories, etc etc etc.

I tried several other approaches like exposing only a `/me/relationships/favorites/100` endpoint with no `/me/favorites/100` but that feels strange somehow.

I've been spinning on this for too long and feel like I'm missing something fundamental.  I think the crux of the matter is that a favorite is more than just a has-one or has-many relationship like an article's author or comments (because it has a timestamp associated with it).  Does that make it a first class resource?  Or something altogether different?

Thanks for any help you can provide.

**Comment by dgeb** [comment]
If you want to track attributes on a relationship, then the relationship itself should be promoted to a resource, as you did in your last example with the `favorites` type.

The only thing you're missing in your example is the name of the `articles` relationship:

```
GET /me/favorites/100
{
  "data": [
    {
      "type": "favorites",
      "id": 100,
      "attributes": {
        "created_at": "2016-04-25T22:40:10Z",
        "updated_at": "2016-04-25T22:40:12Z"
      },
      "relationships": {
        "articles": {
          "data": [
            {
              "type": "articles",
              "id": 101
            }
          ]
        }
      }
    }
  ]
}
```

No big deal, but these discussions are better suited for http://discuss.jsonapi.org/
