### ISSUE TITLE
Singleton resource fetching/updating via json api

### ISSUE THREAD

**Issue by senid231** [json-api/json-api#1046]
related to #203 (but issue is very old)

How should we get access to singular resource for fetching and updating?

For example we have with authorization via token in headers.
So in context of each request we know who is making it.
We need to have resource that allows user to fetch and change his information.

I think restful interface for singleton resource should looks like:
`GET /user_detail` should return

``` json
{
  "data": {
    "type": "user_details",
    "attributes": {
      "first_name": "John",
      "last_name": "Doe"
    }
  }
}
```

`PATCH user_detail` with body

``` json
{
  "data": {
    "type": "user_details",
    "attributes": {
      "first_name": "Bill"
    }
  }
```

should change first_name and return 200.

`POST /user_detail` and `DELETE /user_detail` should not be permitted.

But spec says that:

> Updating Resources
> 
> A resource can be updated by sending a PATCH request to the URL that represents the resource.
> 
> The URL for a resource can be obtained in the self link of the resource object. Alternatively, when a GET request returns a single resource object as primary data, the same request URL can be used for updates.
> 
> The PATCH request MUST include a single resource object as primary data. The resource object MUST contain type and id members.

What do you think about that?

**Comment by bintoro** [comment]
Just use a static ID such as `0` or `"user_details"`, for instance.

**Comment by Fivell** [comment]
@bintoro , isn't it ugly?

**Comment by dgeb** [comment]
@Fivell you are required to include an `id` with resources, but it does not have to be ugly or completely arbitrary. 

You surely track an `id` for individual users internally, which you could choose to expose through your API. The server could perform an authorization step to ensure that the `id` matches that of the logged in user.

If you prefer not to expose that internal `id`, you could alternatively expose the `id` that is meaningful to the user, such as their user name or something generic like `me`.

This architecture has benefits if you choose to allow for a new class of users (e.g. "admins") to update other users' details at the same endpoint.

**Comment by Fivell** [comment]
@dgeb ,thanks for clarification,  understood your point.

**Comment by beauby** [comment]
This issue seems resolved. Can we close it?

**Comment by iirving** [comment]
I'd like to make the case for the singular resource,
as per issue [#203](https://github.com/json-api/json-api/issues/203l) which implied support for a singular resource, it still feels like there use cases for it, and supplying it with pseudo id which will be overriding on the backend seems like a hack.

**Comment by beauby** [comment]
@iirving I understand what you mean, although
1. `id`s identify resources as in objects represented by your API, they are not necessarily related to any DB field.
2. You may want to cache requests, in which case, having something that identifies the user in the request is definitely a good thing.

**Comment by iirving** [comment]
@beauby those are 2 seem reasonable points for including an id in the api.  

I guess I missed when singleton resources were dropped in the final spec.  

I think this needs to be explicitly stated in the spec document, with some of the alternatives for handling that @dgeb mentioned above and the benefits you mentioned, to avoid confusion.  Once that is done I'm happy to close this issue.
