### ISSUE TITLE
What does creating a document with links look like?

### ISSUE THREAD

**Issue by gabrielgrant** [json-api/json-api#105]
In "Updating" > "Creating a Document" the example document doesn't have any links.

When creating a document with links in the URL style, I'm assuming the top-level "links" template is still required, yes?

Example 1

```
POST /photos
Content-Type: application/json
Accept: application/json

{
  "links": {
    "photos.comments": "http://example.com/comments/{posts.comments}"
  },
  "photos": [{
    "title": "Ember Hamster",
    "src": "http://example.com/images/productivity.png",
    "links": {
      "comments": [ "1", "5", "12", "17" ]
    }
  }]
}
```

Or is it valid to just include the ID(s) and assume the server knows what type of object you're referencing?

Example 2

```
POST /photos
Content-Type: application/json
Accept: application/json

{
  "photos": [{
    "title": "Ember Hamster",
    "src": "http://example.com/images/productivity.png",
    "links": {
      "comments": [ "1", "5", "12", "17" ]
    }
  }]
}
```

I'm pretty sure the client should have to be explicit about what it is linking to, despite there not being any way to explicitly communicate whether a server supports ID-based JSON, URL-based JSON or both.

As with #101 it's possible that this is implicit, but I think at least having one of these examples in an appendix makes sense.

**Comment by steveklabnik** [comment]
If you want the links to be something specific, then you'd include them, but if you don't, then you don't.

That said, an example with including them would make sense.

**Comment by drgomesp** [comment]
I'm also not sure about how to implement the object creation from the links point of view.

What would be the best option?

```
POST /categories
Content-Type: application/json
Accept: application/json

{
  "category": [{
    "name": "My category",
    "links": {
      "products": [ "1", "5", "12", "17" ]
    }
  }]
}
```

Versus

```
POST /categories
Content-Type: application/json
Accept: application/json

{
  "category": [{
    "name": "My category",
    "products": [ 
        "1", "5", "12", "17" 
    ]
  }]
}
```

?

**Comment by dgeb** [comment]
It's possible to create a resource together with relationships. For example:

```
POST /categories
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "data": {
    "type": "category",
    "name": "My category",
    "links": {
      "products": { "type": "products", "ids": ["1", "5", "12", "17"] }
    }
  }
}
```
