### ISSUE TITLE
Mismatch between 409 Conflict responses in creating and updating resources

### ISSUE THREAD

**Issue by jfinkels** [json-api/json-api#1051]
The [responses section for creating resources](http://jsonapi.org/format/1.1/#crud-creating-responses-409) currently states,

> A server **MUST** return `409 Conflict` when processing a `POST` request in
> which the resource object's `type` is not among the type(s) that constitute the
> collection represented by the endpoint.

However the [responses section for updating resources](http://jsonapi.org/format/upcoming/#crud-updating-responses-409) states,

> A server **MUST** return `409 Conflict` when processing a `PATCH` request in
> which the resource object's `type` and `id` do not match the server's endpoint.

Suppose I have an "employee" type and a "manager" subtype, and suppose I wish to be able to create and update manager resources via the endpoint for all employees. Is the specification indicating here that a request like

``` http

POST /employee HTTP/1.1
Host: example.com
Content-Type: application/vnd.api+json

{"type": "manager"}
```

should succeed but a subsequent request to update the created object (assuming it has ID 1) like

``` http

PATCH /employee/1 HTTP/1.1
Host: example.com
Content-Type: application/vnd.api+json

{
    "type": "manager",
    "id": "1",
    "data": {}
}
```

should fail with a `409 Conflict` because the type "manager" does not match the "employee" type that appears in the endpoint URL? If this is true, I am surprised that these two request methods have different type requirements. If this is false, the responses section on updating resources should be modified to match that of creating resources.

**Comment by ethanresnick** [comment]
I think it'd be fair here to update the PATCH text  to say something like:

> A server MUST return 409 Conflict when processing a PATCH request in
> which the resource object's type and id is not **among the resource(s) that 
> are modifiable at the endpoint.

Ping @dgeb

**Comment by dgeb** [comment]
There are a couple things to unpack here.

URLs are opaque to the base spec, even though we do make [recommendations](http://jsonapi.org/recommendations/). None of these requirements has anything to do with the URL itself, but rather the resources represented at those endpoints. Therefore, if the `self` link for the new manager was `/abc`, that might be bad API design, but would not be in conflict with the spec.

Also, endpoints that represent a collection (e.g. `/employee`) vs. an individual resource (e.g. `/employee/1`) are completely different and account for the different rules. The PATCH rule is written to align with:

> A resource can be updated by sending a PATCH request to the URL that represents the resource.  

There is only one resource represented at that one endpoint and it has a single `id` and `type`.

**Comment by jfinkels** [comment]
Okay, so you're saying there are multiple possible implementations that satisfy the requirement, some of which are better designed than others. I guess my question concerns the quoted text.

> A resource can be updated by sending a PATCH request to the URL that represents the resource.

I understand that each endpoint like `/employee/1` represents a single resource, but isn't it possible that each resource can be viewed from multiple endpoints, for example, from `/employee/1` and `/manager/1` in this case?

**Comment by dgeb** [comment]
> I understand that each endpoint like /employee/1 represents a single resource, but isn't it possible that each resource can be viewed from multiple endpoints, for example, from /employee/1 and /manager/1 in this case?

As long as the resource returned from those endpoints with GET includes a `type` that matches the `type` you're sending with PATCH, the spec is satisfied.

**Comment by jfinkels** [comment]
Right, of course. You have resolved my confusion here, thanks.

**Comment by BhuvaneshwariB** [comment]
How can we validate type in POST call? Please help.
