### ISSUE TITLE
Question: Sorting by a related property

### ISSUE THREAD

**Issue by TheHandsomeCoder** [json-api/json-api#1054]
I'm currently implementing an adapter that will allow BreezeJS to talk to a JSON-API.

Going through their docs they have the facility to sort by the [related property on a resource](http://breeze.github.io/doc-js/query-examples.html#RelatedPropertyOrdering).

Is this supported by JSON-API in it's spec or would this fall under the implementation specific banner?

Cheers

Scott

**Comment by dgeb** [comment]
See http://jsonapi.org/format/#fetching-sorting

> Note: It is recommended that dot-separated (U+002E FULL-STOP, “.”) sort fields be used to request sorting based upon relationship attributes. For example, a sort field of author.name could be used to request that the primary data be sorted based upon the name attribute of the author relationship.
