### ISSUE TITLE
Questions for updating the GOintegro HATEOAS lib (+ Symfony bundle)

### ISSUE THREAD

**Issue by skqr** [json-api/json-api#1057]
Hi, guys.

I'm the author of [a HATEOAS lib](https://github.com/skqr/hateoas) for PHP / Symfony. I made it for the 0.8 spec, and never updated to 1.0.

I'm trying to do that now, but I'm a bit concerned about a couple of things in the spec.

Given the following example (omitting the irrelevant `attributes` and `links` content)

``` json
{
  "type": "articles",
  "id": "1",
  "attributes": {},
  "links": {},
  "relationships": {
    "author": {
      "links": {
        "self": "http://example.com/articles/1/relationships/author",
        "related": "http://example.com/articles/1/author"
      },
      "data": { "type": "people", "id": "9" }
    },
    "comments": {
      "links": {
        "self": "http://example.com/articles/1/relationships/comments",
        "related": "http://example.com/articles/1/comments"
      },
      "data": [
        { "type": "comments", "id": "5" },
        { "type": "comments", "id": "12" }
      ]
    }
  }
}
```
1. What is the purpose of the "related" link? I know it's optional, but appears to be entirely redundant, since AFaiK points to the same resource document as the "self" link of the same relationship resource object.
2. Why did the "data" section for a resource object representing a to-many relationship change from an object with the resource type of the list (e.g. `"data": {"type": "comments"}) to a list with the type and Id of each related resource object? Looks pretty when it's two items, but what should I do for three thousand?

(The very first thing I added to JSON-API when implementing it was to make pagination required for all primary resources. You could still get a 413 response if you included a to-many relationship which was above the set maximum, but that implied a deliberate choice by the user, and they still could get the relationship by using it's relationship link.)

I'm also a bit baffled by how might I handle resource polymorphism. This is a more general question, which goes beyond the update.

Say that I want to link a resource of type A against a list of resources of several different subtypes of B, say C, D, and E.

So far, I had been creating a wrapper resource, so that A linked to a list of B, but then each B had a relationship of the same name against either C, D, or E.

Is there a better way?

Thanks in advance!

**Comment by nubs** [comment]
> What is the purpose of the "related" link? I know it's optional, but appears to be entirely redundant, since AFaiK points to the same resource document as the "self" link of the same relationship resource object.

The "self" link is for the relationship itself.  That URL can be used for associating new comments with the article, removing comments from the article, etc. without actually updating the comment entity's attributes.

The "related" link is for the entities that are part of the relationship.  That URL can be used to access the entities themselves and make changes to them or create new ones.

> Why did the "data" section for a resource object representing a to-many relationship change from an object with the resource type of the list (e.g. `"data": {"type": "comments"}) to a list with the type and Id of each related resource object? Looks pretty when it's two items, but what should I do for three thousand?

Pagination within relationships is supported by the spec.  It's allowed to have next/prev links within the comments relationship.  The data for the relationship would just be the first page.  This is hinted at in [this section](http://jsonapi.org/format/#document-resource-object-relationships)

**Comment by skqr** [comment]
Thanks for the quick response!

I didn't really understand what you meant on the "self" vs "related" point; could you please elaborate? I'm a little worried because I can find nothing explicit in the spec about it.

I can already make changes to the related entities without the "related" link. If I want to create a new comment, I just POST to `/comments` and include the Id of the blog post I'm commenting on as a to-one relationship on the "relationships" section.

If I want to edit a comment, I just use its "self" link, on its own resource object.

That covers the two use cases you mentioned, without ever needing a "related" link.

I'm really confused about it.

About the to-many relationships "data" section, it seems that when reading the sepc you should already know that "meta" means I'm able to paginate in order to figure out how to deal with a very common scenario (?)

I've seen the "pagination in relationship objects" mentioned in issue threads, but, it kind of sounds to me like somebody might have jumped the gun in declaring the spec as is a 1.0 version, at least in regards to it not specifying either of the solutions you describe.

**Comment by nubs** [comment]
There are definitely many cases where you do not need a related link.  Cases where you may want to support that are where you need to change the relationship.  For example, say your article resource had tags.  You may want to disassociate a tag from an article without deleting the tag itself.  That could be implemented by sending a DELETE request to the self url for that relationship.  For example: `DELETE http://example.com/articles/1/relationships/tags/foo`.

For pagination, I'm not sure what you mean about "meta".  The pagination links can go in the relationship itself:

``` json
{
  "data": {
    "type": "article",
    "id": "1",
    "attributes": {},
    "relationships": {
      "comments": {
        "data": [
          {"type": "comment", "id": "1"},
          {"type": "comment", "id": "2"},
          {"type": "comment", "id": "3"},
          {"type": "comment", "id": "4"},
          {"type": "comment", "id": "5"}
        ],
        "links": {
          "self": "http://example.com/articles/1/relationships/comments",
          "related": "http://example.com/articles/1/comments",
          "next": "http://example.com/articles/1/relationships/comments?page[offset]=5"
        }
      }
    }
  }
}
```

Making a request to the next link would return you something like this:

``` json
{
  "data": [
    {"type": "comment", "id": "6"},
    {"type": "comment", "id": "7"},
    {"type": "comment", "id": "8"},
    {"type": "comment", "id": "9"},
    {"type": "comment", "id": "10"}
  ],
  "links": {
    "self": "http://example.com/articles/1/relationships/comments",
    "related": "http://example.com/articles/1/comments",
    "prev": "http://example.com/articles/1/relationships/comments",
    "next": "http://example.com/articles/1/relationships/comments?page[offset]=10"
  }
}
```

**Comment by dgeb** [comment]
@nubs thanks for fielding @skqr's questions 👍 

@skqr please reopen if any questions are left unanswered or check out http://discuss.jsonapi.org/ for general usage questions / discussions.
