### ISSUE TITLE
"Examples" should be renamed "Example Implementations"

### ISSUE THREAD

**Issue by gabrielgrant** [json-api/json-api#106]
With the new "Examples" appendix, having a top level link called "Examples" is confusing (I expected to find the request/response examples behind that link)

"Examples" should be renamed "Example Implementations" (or just "implementations")

**Comment by steveklabnik** [comment]
Nope, it should have both.

**Comment by gabrielgrant** [comment]
Ah, that makes more sense -- sorry for the confusion. I'm tied up right now, but I'll send a new (correct) pull request shortly.

**Comment by steveklabnik** [comment]
No worries!
