### ISSUE TITLE
Unclear how to represent link-like relationships

### ISSUE THREAD

**Issue by bf4** [json-api/json-api#1064]
We want to return some initialization data for the current user the represents their current context, and links to available 'tabs' so that we can prepare our js app (react) for rendering.  

e.g.

for the domain where there are `networks` of hospitals (`facilities`), and each hospital has `departments`, and we want to return
- the current user id and 'nickname'
- the primary entity name, e.g. the network name for a user that manages facilities in that network
- a list of entities that the user has access to. Each entity represents a tab/page and a link that returns the data required to build that tab.

``` http
GET /user/current HTTP/1.1
Accept: application/vnd.api+json
Content-Type: application/vnd.api+json; charset=utf-8

{
  "data": {
    "id": "5",
    "type": "users",
    "attributes": {
      "nickname": "Ivan Danger McCarthy",
      "primary_entity": { "title": "Corporal Healing, LLC", "type": "networks"},
      "entities": [
         { "type": "facilities", "title": "Facility", "data-link": "https://api.example.com/compliance/facilities" },
         { "type": "departments", "title": "Department", "data-link": "https://api.example.com/compliance/departments" },
       ]
    }
  }
}
```

So, we would then have a page that is something like

``` plain
<Corporal Healing, LLC>        Account: Ivan Danger McCarthy

        ___[Facility]______[Departments]_____
        |______________________________________|
```

And the js app (react) knows to render the tabs `Facility` and `Department`, and that when the user clicks the `Facility` tab, to hit `https://api.example.com/compliance/facilities` and render using that data.

Obviously, the example isn't JSON API compliant, it just represents how we're thinking about it, but we can't quite figure out how it would look in JSON API.

We think it would be best represent our resource object 'users', along with 'relationships' to the entities they manage, something like

``` json
{
  "data": {
    "id": "5",
    "type": "users",
    "attributes": {
      "nickname": "Ivan Danger McCarthy"
    },
    "relationships": {
       "networks": { "meta": { "title": "Corporal Healing, LLC" } },
       "facility": {
          "links": {
            "self": "https://api.example.com/compliance/facilities"
          },
          "meta": { "title": "Facility" }
       },
       "department": {
          "links": {
            "self": "https://api.example.com/compliance/departments"
          },
          "meta": { "title": "Department" }
        }
      }
  }
}
```

But that doesn't seem quite right.  Part of the problem is that the relationships are resource-like in that they have an associated resource e.g. `type: facilities` and attributes like `title: 'Facility'` but and the data for them can be represented by a url, but they are more of an index page, and thus don't really have an associated id, so it doesn't seem to make sense to use `data`.  

We could use some help figuring this out.

One related question that's come up, is what's the difference between a `related` and `self` link in a relationship. e.g. from http://jsonapi.org/recommendations/#including-links

``` http
GET /comments HTTP/1.1

{
  "data": [{
      "relationships": {
        "author": {
          "links": {
            "self": "/comments/1/relationships/author",
            "related": "/comments/1/author"
          }
        }
      }
  }]
}
```

What's the difference in response from hitting `/comments/1/relationships/author` vs. `/comments/1/author`?

Possibly related
- https://github.com/json-api/json-api/issues/666
- https://github.com/json-api/json-api/pull/632
- https://github.com/json-api/json-api/pull/920

**Comment by belohlavek** [comment]
I just started implementing the spec and I agree that it's unclear how to correctly handle relationships.

For example:

> A server **MUST** respond to `PATCH` requests to a URL from a to-one relationship link.
> The `PATCH` request **MUST** include a top-level member named data containing one of:
> - a resource identifier object corresponding to the new related resource.
> - `null`, to remove the relationship.

...and...

> A server **MUST** respond to `PATCH`, `POST`, and `DELETE` requests to a URL from a to-many relationship link as described below.
> For all request types, the body **MUST** contain a data member whose value is an empty array or an array of resource identifier objects.

Source: [Updating relationships](http://jsonapi.org/format/#crud-updating-relationships)

So you use `PATCH`to create _some_ relationships and `POST` to create others. I think that's a bit counter intuitive. Also I don't understand why the docs define all operations under "updating" when we could refer to all CRUD operations on relationships :sweat_smile: 

Also, there's what @bf4 mentioned:

> What's the difference in response from hitting `/comments/1/relationships/author` vs. `/comments/1/author`?

I couldn't find an answer to that from reading [Fetching relationships](http://jsonapi.org/format/#fetching-relationships)

The [recommendations](http://jsonapi.org/recommendations/#urls-relationships) mention `/relationships/` as being just that, a recommendation, and the other being "related resources", but I still don't understand what's the difference and what the response should be for each case.

All in all, I'm not saying that it's wrong or bad in any way. I (a newcomer) am unable to understand it easily :cry: 

Maybe @dgeb and @ethanresnick could spare some time to show us the light?

**Comment by bf4** [comment]
fwiw, what I ended up doing was the create a notional `entity` attribute and `entity_query` relationship. I chose `self` links since they seem to mean the link to that entity, not to how that entity relates to the current one

``` json

{
  "data": {
    "id": "5",
    "type": "users",
    "attributes": {
      "nickname": "Ivan Danger McCarthy",
      "entity": {
        "type": "networks",
        "title": "Corporal Healing, LLC"
      }
    },
    "relationships": {
      "facilities": {
        "links": {
          "self": "https://api.example.com/compliance/facilities"
        },
        "data": {
          "id": "facilities_compliance_query",
          "type": "entity_queries",
          "title": "Facility"
        }
      },
      "departments": {
        "links": {
          "self": "https://api.example.com/compliance/departments"
        },
        "data": {
          "id": "departments_compliance_query",
          "type": "entity_queries",
          "title": "Department"
        }
      }
    }
  }
}
```

**Comment by dgeb** [comment]
@bf4 

> what's the difference between a related and self link in a relationship
> 
> What's the difference in response from hitting /comments/1/relationships/author vs. /comments/1/author?

A `self` link for a relationship is called the "relationship URL" and should return the relationship's linkage data - i.e. the resource identifier object(s) associated with the relationship. Requests can also be sent to the relationship URL to modify the relationship.

A `related` link for a relationship is called the "related resource URL" and should return the resource(s) currently in the relationship.

Given that, you should use `related` in your links (e.g. `"https://api.example.com/compliance/facilities"`) to return full resource objects.

@belohlavek 

> So you use PATCH to create some relationships and POST to create others. I think that's a bit counter intuitive.

Use PATCH to _update_ (i.e. completely replace) the values of relationships. To-many and to-one relationships can be PATCHED.

Use POST / DELETE to partially adjust the membership of to-many relationships.

**Comment by bf4** [comment]
@dgeb Thanks. Gotcha. 

`self: /comments/1/relationships/author` returns something like `{ id: 5, type: authors }`

while 

`related:  "/comments/1/author"` returns something like `{ id: 5, type: authors, attributes: { name: 'Frank', title: 'Good Vibes Technician' } }`

?

Also, since writing I decided to write the response document using relationships `data` instead of `meta`.

``` json
{
  "data": {
    "id": "5",
    "type": "users",
    "attributes": {
      "name": "Ivan Danger McCarthy",
      "entity": {
        "type": "networks",
        "title": "Corporal Healing, LLC"
      }
    },
    "relationships": {
      "facilities": {
        "links": {
          "related": "http://api.example.com/compliance/facilities"
        },
        "data": {
          "id": "facilities_compliance_query",
          "type": "entity_queries",
          "title": "Facilities"
        }
      },
      "departments": {
        "links": {
          "related": "http://api.example.com/compliance/departments"
        },
        "data": {
          "id": "departments_compliance_query",
          "type": "entity_queries",
          "title": "Departments"
        }
      }
    }
  }
}
```

I've been threatening lately to write an intro to getting to know JSON API's core concepts and how to think like JSON API. :)

**Comment by abuiles** [comment]
@bf4 is `title` an attribute on the `entity_query`?  if you are using data on the relationship, then is should be a resource linkage which only includes `type` and `id`.  Then if you want to sideload the resource, it should be in the `included` array. 

Check the following https://api.ember-101.com/loans?include=friend where the "`friend` is linked in the relationship object, but the `resource` full data is in the `included` array.

**Comment by bf4** [comment]
@abuiles Thanks for taking a look.  Do you think it makes sense to have an `included` member by default? Or maybe I should return to using the relationships meta `"meta": { "title": "Department" }`? 

I'm trying to remember why I thought putting the `title` in there was valid, but probably was just me getting tired

Back to the drawing board

http://jsonapi.org/format/#document-resource-object-linkage

**Comment by bf4** [comment]
I think it had to do with how I defined an entity as an attribute whose value is a JSON object with keys type and title

``` json
"entity": {
        "type": "networks",
        "title": "Corporal Healing, LLC"
      }
```

And then defining the relationship object type as `entity_queries`. And then oopsed

**Comment by jelhan** [comment]
@bf4 If I get it right, your questions have been resolved, haven't they? Do you mind closing this issue in that case?

**Comment by bf4** [comment]
I suppose I'm not expecting further discussion
