### ISSUE TITLE
How to represent nested relationships of the same type objects?

### ISSUE THREAD

**Issue by ericntd** [json-api/json-api#1065]
I have an object type **Category**. Each category can have multiple child categories.

How do I express a list of categories together with their child and grandchild categories? Should they children go under **relationship** or **included**? How about the grand children?

**Comment by ericntd** [comment]
@kamikat could you please lend me some of your wisdom here?

**Comment by kamikat** [comment]
That's not a problem with json-api but your model. Typically, we use a single object of type `categories` with a `parent` relationship.

Read JSON API specification for more details on `relationship` and `included` objects.

**Comment by ericntd** [comment]
I'm not saying this is a problem with any one. I'm just trying to use Retrofit to parse JSON response from my webservice to objects in my Android app. My server guy and me want to use JSON API but we are confused. We don't know how to achieve our goal. The documentation on json-api website is not obvious enough for us to follow

**Comment by nubs** [comment]
A sample response could look something like this:

``` json
{
  "data": {
    "type": "category",
    "id": "123",
    "attributes": {
      "name": "foo"
    },
    "relationships": {
      "children": {
        "data": [
          {
            "type": "category",
            "id": "124"
          },
          {
            "type": "category",
            "id": "125"
          }
        ]
      }
    }
  },
  "included": [
    {
      "type": "category",
      "id": "124",
      "attributes": {
        "name": "bar"
      },
      "links": {
        "self": "https://example.com/categories/124"
      }
    },
    {
      "type": "category",
      "id": "125",
      "attributes": {
        "name": "baz"
      },
      "links": {
        "self": "https://example.com/categories/125"
      }
    }
  ]
}
```

**Comment by ericntd** [comment]
Thanks @nubs, while it does make sense, it hasn't answered my question fully:
1) How to deal with the grandchild categories?
2) Is the **included** part parseable (i.e. all `included` follow certain standards) by libraries such as this [one](https://github.com/kamikat/moshi-jsonapi)?

**Comment by nubs** [comment]
> 1) How to deal with the grandchild categories?

The included resources can have relationships defined on them, so you could add the "children" relationship to them as well and add the referenced documents to the compound document.

> 2) Is the included part parseable (i.e. all included follow certain standards) by libraries such as this one?

The included part is parseable, although I can't answer for how it is handled by a given library - you can definitely give it a go.  The type+id pair in the resource identifier should match at most one resource in the compound document.  See this note in the specification:

> Note: In a single document, you can think of the type and id as a composite key that uniquely references resource objects in another part of the document.

**Comment by ericntd** [comment]
Thanks @nubs , indeed the response you gave is aligns with the library I'm using. That is the standard I'm after.
As for the grandchild objects, I'll deal with them separately. I'm happy with the Category objects and their children
