### ISSUE TITLE
Can "links" be omitted on creation?

### ISSUE THREAD

**Issue by gabrielgrant** [json-api/json-api#107]
For example, if a blog post has no comments, should the POST data be fully explicit:

Example 1

```
{
  "links": {
    "posts.comments": "http://example.com/comments/{posts.comments}"
  },
  "posts": [{
    "id": "1",
    "title": "Rails is Omakase",
    "links": {
      "comments": []
    }
  }]
}
```

or can the link info be omitted:

Example 2

```
{
  "posts": [{
    "id": "1",
    "title": "Rails is Omakase"
  }]
}
```

**Comment by gabrielgrant** [comment]
I'm inclined to say that empty sets of links should have to be included, but it isn't clear to me whether there is a way to specify an empty set if full links are being specified inline 

```
{
  "posts": [{
    "id": "1",
    "title": "Rails is Omakase",
    "links": {
      "comments": "http://example.com/comments/1,2,3,4"
    }
  },
  {
    "id": "2",
    "title": "Rails is Omakase: Update",
    "links": {
      "comments": "http://example.com/comments/-"   <-- What should this be? an empty string?
    }
  }]
}
```

**Comment by steveklabnik** [comment]
Links are optional, so they're not needed. If you were using PUT, then you'd need to figure them all out and include them yourself, but if you have no comments, no reason to include links.
