### ISSUE TITLE
Relationship deletion clearification

### ISSUE THREAD

**Issue by emil-nasso** [json-api/json-api#1070]
I'm trying to get my head around how to delete a relationship.

According to the documentation you can update a relationship in a similar fashion to how you update attributes on a resource: http://jsonapi.org/format/#crud-updating-resource-relationships

``` http
PATCH /articles/1 HTTP/1.1
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "data": {
    "type": "articles",
    "id": "1",
    "relationships": {
      "author": {
        "data": { "type": "people", "id": "1" }
      }
    }
  }
}
```

Later in the documentation, information on how to delete a relationship can be found, by replacing the relationship with an empty relationship with a PATCH to the relationship url: http://jsonapi.org/format/#crud-updating-to-one-relationships

``` http
PATCH /articles/1/relationships/author HTTP/1.1
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "data": null
}
```

With these two pieces of information, is it a correct conclusion to draw that it should be possible to clear a relationship by patching the resource, like this?

``` http
PATCH /articles/1 HTTP/1.1
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "data": {
    "type": "articles",
    "id": "1",
    "relationships": {
      "author": {
        "data": null
      }
    }
  }
}
```

**Comment by ballPointPenguin** [comment]
good question

**Comment by dgeb** [comment]
>  is it a correct conclusion to draw that it should be possible to clear a relationship by patching the resource, like this?

Yes, that's correct. Clearing a to-one relationship is done by patching its `data` with a `null` value. This can be done via the relationship URL or the resource URL.
