### ISSUE TITLE
Neither `links` nor `included` allows me to easily match information with "resource identifier objects" inside `relationships`

### ISSUE THREAD

**Issue by h8rry** [json-api/json-api#1072]
Please look at the following JSON response (taken from documentation). This `article` has relationships with `author` and `comments`. In this case, the `article` has 2 `comments`.

The "relationship object” has a "resource linkage", which has an array of "resource identifier objects".

My problem is that "resource identifier objects" (unlike "resource objects") only contains `type` and `id`, but not other information. There are 2 ways JSON-API currently recommends to get more information out of `relationships`:
1. use `links` and make requests - but this will increase # of requests
2. include information inside `included` - but this requires me to loop through the `included` array constantly if I want to match information with  "resource identifier objects" inside `relationships`

Am I missing something here? 

``` js
{
  "data": [{
    "type": "articles",
    "id": "1",
    "attributes": {
      "title": "JSON API paints my bikeshed!"
    },
    "links": {
      "self": "http://example.com/articles/1"
    },
    "relationships": {
      "author": {
        "links": {
          "self": "http://example.com/articles/1/relationships/author",
          "related": "http://example.com/articles/1/author"
        },
        "data": { "type": "people", "id": "9" }
      },
      "comments": {
        "links": {
          "self": "http://example.com/articles/1/relationships/comments",
          "related": "http://example.com/articles/1/comments"
        },
        "data": [
          { "type": "comments", "id": "5" },
          { "type": "comments", "id": "12" }
        ]
      }
    }
  }],
  "included": [{
    "type": "people",
    "id": "9",
    "attributes": {
      "first-name": "Dan",
      "last-name": "Gebhardt",
      "twitter": "dgeb"
    },
    "links": {
      "self": "http://example.com/people/9"
    }
  }, {
    "type": "comments",
    "id": "5",
    "attributes": {
      "body": "First!"
    },
    "relationships": {
      "author": {
        "data": { "type": "people", "id": "2" }
      }
    },
    "links": {
      "self": "http://example.com/comments/5"
    }
  }, {
    "type": "comments",
    "id": "12",
    "attributes": {
      "body": "I like XML better"
    },
    "relationships": {
      "author": {
        "data": { "type": "people", "id": "9" }
      }
    },
    "links": {
      "self": "http://example.com/comments/12"
    }
  }]
}
```

**Comment by dgeb** [comment]
> include information inside included - but this requires me to loop through the included array constantly if I want to match information with "resource identifier objects" inside relationships

"Included" records may appear as primary or included data, so it is recommended that you translate data from JSON:API's normalized form to a hash that provides easier lookups across both data sets. (Note that a hash form could not be used for `data` because it needs to convey order, which is why its contents are an array).
