### ISSUE TITLE
Asymmetrical collections

### ISSUE THREAD

**Issue by tgriesser** [json-api/json-api#109]
Somewhat related to #20

I'm looking into building a json-api integration for backbone on the client and [bookshelf.js](http://bookshelfjs.org), on the server, and I'm trying to understand how to handle fetching items that are the same type, but are possibly requested with different attributes:

Consider this example:

``` js
posts.fetch({
  jsonApi: true,
  withRelated: [
    'author', 'comments', 'comments.author:id,first_name'
  ]
})
```

Where this request would generate a json-api response on the server of something like:

``` json
{
  "author": [{
    "id": 1,
    "first_name": "Example",
    "last_name": "Author",
    "email": "author@example.com"
   }, {
    "id": 2,
    "first_name": "Joe"
   }, {
    "id": 3,
    "first_name": "Bob"
   }, {
    "id": 10,
    "first_name": "Test",
    "last_name": "User",
    "email": "user@example.com"
  }],
  "post": [{
    "id": "1",
    "title": "Article title",
    "links": {
      "author": "10",
      "comment": [ "1", "2" ]
    }
   }, {
    "id": "2",
    "title": "Article 2",
    "links": {
      "author": "1",
      "comment": [ "3" ]
    }
  }],
  "comment": [{
    "id": "1",
    "message": "lorem ipsum",
    "links": {
      "author": "1"
    }
  }, {
    "id": "2",
    "message": "lorem ipsum",
    "links": {
      "author": "3"
    }
  }, {
    "id": "3",
    "message": "lorem ipsum",
    "links": {
      "author": "10"
    }
  }]
}
```

The fact that the `author` collection has varying attributes values feels a bit odd - does this seem like it'd be the right way to do it? Or should there be a separate `comment.author` property which contains a full collection with the simple values requested to display alongside the comments.

I also noticed that the `author` key links to the `people` key in the site's examples, is this linking something that should be handled by the application logic and potentially described in the `meta` property?

**Comment by steveklabnik** [comment]
Can you explain how this is not a dup of #20?

**Comment by tgriesser** [comment]
As I read it, #20 was asking about how to handle the requests (`exclude_all`, `include_all`, fetching more information `self`), and whether these would be handled/provided by the spec.

This is more about the response once you have partial attributes, but also have objects with full attributes of the same resource type in that request, should these two be mixed together into the same collection with varying attributes, or should they be split out into separate properties at the top level.

I could join this in on #20 if that'd be easier, it just seemed like a separate question.

**Comment by steveklabnik** [comment]
Gotcha. Thanks, that makes total sense.

I don't think that having different attributes for different objects is strange; a document story may expose data like this, for example.

If you want them to always have the same attributes, have your server always return the same attributes for every `author`.
