### ISSUE TITLE
Use "articles" for the CRUD examples

### ISSUE THREAD

**Issue by brainwipe** [json-api/json-api#1090]
The specification uses `articles`, `author` and `relationship` for the [GET requests](http://jsonapi.org/format/#fetching) and then swaps to `photos` for the [CRUD actions](http://jsonapi.org/format/#crud).

Perhaps the specification might be easier to understand if it used `articles` as an example throughout. Or is it just me?

**Comment by jelhan** [comment]
Thanks a lot for opening this issue. I fully agree that this does not help with readability. But if you don't mind I would like to track that in #941. Going to close as a duplicate.
