### ISSUE TITLE
Is links: {} valid?

### ISSUE THREAD

**Issue by richmolj** [json-api/json-api#1095]
This response currently validates against the schema:

``` json
"relationships": {
  "posts": {
    "links": {} 
  }
}
```

The [documentation on links](http://jsonapi.org/format/#document-links) is a little unclear here - is the above actually valid, or should one of `self`/`href`/`meta` be present?

**Comment by dgeb** [comment]
I don't see any issue, in the spec or conceptually, with `links` being an empty object.

**Comment by richmolj** [comment]
👍 thanks for the clarification!
