### ISSUE TITLE
Additional fields parameter

### ISSUE THREAD

**Issue by malejpavouk** [json-api/json-api#1099]
Hi,

we have maybe found a small missing piece in the 1.0 specification. Currently the spec supports sparse fields - you can limit which fields to include.

Our API currently works also in an opposite way - we have fields, which are very expensive to request, hence our APIs have additional-fields param, using which you specify these fields (and which we are missing in JSON API).

We can't make these fields related resources, as there are many of these fields (it would be expensive to maintain these as separate resources) and also it usually does not make sense to require these fields separately.

Is there any construct in current JSON API spec, which would allow this? If not, is there any recommendation, how shall we proceed? Is the additional-fields parameter acceptable?

Thanks

**Comment by beauby** [comment]
As long as the query parameter name (here `additional-fields`, which is ok) complies with [the rules on implementation-specific query parameters](http://jsonapi.org/format/#query-parameters), you are good.
There is a discussion somewhere about adding something in the spec about relative limiting of fields, I cannot remember where at the moment.

**Comment by malejpavouk** [comment]
Ok, thanks for response, I will try to look it up :-)
