### ISSUE TITLE
Shouldn't the JSON-API spec be versioned?

### ISSUE THREAD

**Issue by devinus** [json-api/json-api#110]
E.g. JSON-API v. 0.1

**Comment by steveklabnik** [comment]
Media types generally are not versioned.

That said, once we have something that's a little further along, there will be drafts, and each draft will get a name.

**Comment by devinus** [comment]
@steveklabnik Sorry, I meant the spec itself. It may give us context when discussing changes made to the spec.

E.g. we used "url" in 0.1, but we use "href" now in 0.9.

**Comment by steveklabnik** [comment]
You can do that by referencing commits.
