### ISSUE TITLE
Compound document example doesn't contain all related entities in incl-payload

### ISSUE THREAD

**Issue by wuarmin** [json-api/json-api#1101]
Is there a reason, why the ressource(type: people, id: 2) is not included in the included-payload at the compound-document example? Some people may think, that there is a restriction for deep relations.

``` json
{
  "data": [{
    "type": "articles",
    "id": "1",
    "attributes": {
      "title": "JSON API paints my bikeshed!"
    },
    "links": {
      "self": "http://example.com/articles/1"
    },
    "relationships": {
      "author": {
        "links": {
          "self": "http://example.com/articles/1/relationships/author",
          "related": "http://example.com/articles/1/author"
        },
        "data": { "type": "people", "id": "9" }
      },
      "comments": {
        "links": {
          "self": "http://example.com/articles/1/relationships/comments",
          "related": "http://example.com/articles/1/comments"
        },
        "data": [
          { "type": "comments", "id": "5" },
          { "type": "comments", "id": "12" }
        ]
      }
    }
  }],
  "included": [{
    "type": "people",
    "id": "9",
    "attributes": {
      "first-name": "Dan",
      "last-name": "Gebhardt",
      "twitter": "dgeb"
    },
    "links": {
      "self": "http://example.com/people/9"
    }
  }, {
    "type": "comments",
    "id": "5",
    "attributes": {
      "body": "First!"
    },
    "relationships": {
      "author": {
        "data": { "type": "people", "id": "2" }
      }
    },
    "links": {
      "self": "http://example.com/comments/5"
    }
  }, {
    "type": "comments",
    "id": "12",
    "attributes": {
      "body": "I like XML better"
    },
    "relationships": {
      "author": {
        "data": { "type": "people", "id": "9" }
      }
    },
    "links": {
      "self": "http://example.com/comments/12"
    }
  }]
}
```

**Comment by beauby** [comment]
It does not appear because it was not requested. I think, on the contrary, that this example helps showing that the "included" resources are decided on a per-relationship basis, rather than per-type.

**Comment by ethanresnick** [comment]
What @beauby said. To get {people, 2}, you'd have to request `http://example.com/articles?include=author,comments,comments.author`.

However, I think your issue highlights that it's not very clear what the request URI is for that example response. The only indication of the request URI is the top-level `self` link, which is currently `http://example.com/articles`, whereas it should probably be `http://example.com/articles?include=comments,author`. So, I'd accept a PR that fixes that self link (and adjusts the other top level links accordingly) and, optionally, lists the request URI more prominently.

**Comment by beauby** [comment]
This issue seems resolved. Can it be closed?

**Comment by wuarmin** [comment]
Yes, your explanations were helpful. 
Thanks
