### ISSUE TITLE
Clarification request: creating resources

### ISSUE THREAD

**Issue by beauby** [json-api/json-api#1104]
In the [Creating Resources](http://jsonapi.org/format/#crud-creating) section, it is stated:

> The request MUST include a single resource object as primary data. 

It is not said anything about other potentially valid top level members (like `jsonapi`, `included`, `links`, none of which would make sense _a priori_ in a client-issued payload, and `meta`, which could).

**Comment by ethanresnick** [comment]
`jsonapi`, `included`, and `links` don't currently have a meaning in client issued payloads. However, at least `included` and `links` are likely to acquire a meaning in the future (for sideposting and extension negotiation respectively). At the moment, we don't explicitly prohibit those members from appearing in request documents (i.e., client issued payloads), but maybe we should...

**Comment by beauby** [comment]
I'm curious what would be a possible meaning of top level `links` in a client-issued payload?

**Comment by ethanresnick** [comment]
One possible meaning is being explored in #957 (see https://github.com/json-api/json-api/pull/957/commits/9b8235d246fb44b5b87025b8b0c85c1eab1f8b8c). Note, though, that the final meaning is _very_ likely to be different in some details than what's proposed there.

**Comment by beauby** [comment]
Ok, fair enough. Closing this then.
