### ISSUE TITLE
Consider making `href` required

### ISSUE THREAD

**Issue by ethanresnick** [json-api/json-api#1105]
The link object at the moment doesn't have any required keys... but `href` probably should be required. See #1103

**Comment by brainwipe** [comment]
I'm quite surprised that it's not required. I agree with this wholeheartedly!

**Comment by mgold** [comment]
See also #1095.

**Comment by beauby** [comment]
@mgold I don't think #1095 is related to this. Could you be more specific?

**Comment by mgold** [comment]
Ah! #1095 is asking whether a **links**, plural, object can be empty. A relevant question to this issue is where a single **link** object can be empty. My bad!

**Comment by jelhan** [comment]
The `href` member is required in latest release candidate for v1.1:

> A link object MUST contain the following member:
>
> -    href: a string whose value is a URI-reference [RFC3986 Section 4.1] pointing to the link’s target.

https://jsonapi.org/format/1.1/#auto-id--link-objects

Thanks a lot for this proposal. It seems as if it was picked up for v1.1 without leaving a comment here. I think this issue cam be closed.
