### ISSUE TITLE
Errors in request object

### ISSUE THREAD

**Issue by mgold** [json-api/json-api#1113]
This is a nitpicky edge case, but the discussion of errors centers entirely on how the _server_ should handle and format errors. A _request_ that includes an `errors` field is, yes absurd, but also not disallowed by the spec.

Would it be appropriate to add something like this?

> If the server receives a request containing an `errors` field, it **MUST** respond with `400 Bad Request`.

**Comment by jelhan** [comment]
I don't think a request with `errors` is allowed by latest specification.

A document must only contain primary data or errors. It must not contain both.

The specification enforces primary data to be included in all request. At least if I haven't missed something.

> 9.1  Creating Resources
>
> A resource can be created by sending a POST request to a URL that represents a collection of resources. The request MUST include a single resource object as primary data.

> 9.2 Updating Resources
>
> A resource can be updated by sending a PATCH request to the URL that represents the resource.
>
> (...)
>
> The PATCH request MUST include a single resource object as primary data.

> 9.3.1 Updating To-One Relationships
> 
> (...)
>
> The PATCH request MUST include a top-level member named data

> 9.3.2 Updating To-Many Relationships
>
> A server MUST respond to PATCH, POST, and DELETE requests to a URL from a to-many relationship link as described below.
>
> For all request types, the body MUST contain a data member whose value is an empty array or an array of resource identifier objects.

All the citation is based on latest release candidate for v1.1.

**Comment by jelhan** [comment]
I'm going to close this issue. Please speak up if I missed an important point.
