### ISSUE TITLE
Document Sparse Fieldsets and nested objects (e.g. Django's JSONField / Postgres' jsonb)

### ISSUE THREAD

**Issue by arielpontes** [json-api/json-api#1116]
Consider the Dog model from Django's documentation:

```python
class Dog(models.Model):
    name = models.CharField(max_length=200)
    data = JSONField()
```
And this dog instance:
```
>>> Dog.objects.create(name='Rufus', data={
...     'breed': 'labrador',
...     'owner': {
...         'name': 'Bob',
...         'other_pets': [{
...             'name': 'Fishy',
...         }],
...     },
... })
```
Let's say its id is 1. If I want to retrieve this resource but only include the name of the owner, excluding the `other_pets` attribute, is there anything specified or recommended syntax? Should I use a dot-separated path like the one used for accessing relationships? Like this:
```
GET /dogs/1?fields[dogs]=name,data.breed,data.owner.name
```
Django's ORM for example borrows the `__` (double underscore) syntax from relationship access in order to access the date in JSONFields.

**Comment by beauby** [comment]
You could model your `Dog` API resource to have an `owner_name` attribute and an `owner_pets` relationship instead.

**Comment by jelhan** [comment]
It seems that @beauby's comment has answered the question. I'm going to close this issue.
