### ISSUE TITLE
Should relationships include data or not?

### ISSUE THREAD

**Issue by arielpontes** [json-api/json-api#1117]
In the [Fetching Resources](http://jsonapi.org/format/#fetching-resources) section, there is an example (the second-to-last) of a resource that has a to-one relationship being fetched. In the response, the related object is not included by default. Instead, a link is provided to retrieve the related resource. Here's the example:
```
HTTP/1.1 200 OK
Content-Type: application/vnd.api+json

{
  "links": {
    "self": "http://example.com/articles/1"
  },
  "data": {
    "type": "articles",
    "id": "1",
    "attributes": {
      "title": "JSON API paints my bikeshed!"
    },
    "relationships": {
      "author": {
        "links": {
          "related": "http://example.com/articles/1/author"
        }
      }
    }
  }
}
```
However, according to the section [Inclusion of Related Resources](http://jsonapi.org/format/#fetching-includes), I can also "return resources related to the primary data by default", which I assume would look like the first example in the [Resource Objects section](http://jsonapi.org/format/#document-resource-objects):
```
// ...
{
  "type": "articles",
  "id": "1",
  "attributes": {
    "title": "Rails is Omakase"
  },
  "relationships": {
    "author": {
      "links": {
        "self": "/articles/1/relationships/author",
        "related": "/articles/1/author"
      },
      "data": { "type": "people", "id": "9" }
    }
  }
}
// ...
```
(Note the `data` key inside the relationship object)

But what if I want to offer both responses? Is it possible? How would each endpoint look like? I know I can add the `include` parameter to the querystring but then I'd be fetching actual resources, not only resource identifiers. Is this intentionally left open for each implementation or would I be breaking the standard if I offer both endpoints? I think this is a bit confusing in the documentation and could be clarified.

**Comment by lgebhardt** [comment]
> I can also "return resources related to the primary data by default", which I assume would look like the first example in the Resource Objects section

I read it as the response would also include the Person resource for the Author with id=9 in the `included` section of the response document. In other words your response example is missing the `included` section.

``` json
{
  "data": [{
  "type": "articles",
  "id": "1",
  "attributes": {
    "title": "Rails is Omakase"
  },
  "relationships": {
    "author": {
      "links": {
        "self": "/articles/1/relationships/author",
        "related": "/articles/1/author"
      },
      "data": { "type": "people", "id": "9" }
    }
  }
}],
  "included": [{
    "type": "people",
    "id": "9",
    "attributes": {
      "first-name": "Dan",
      "last-name": "Gebhardt",
      "twitter": "dgeb"
    },
    "links": {
      "self": "http://example.com/people/9"
    }
  }]
}
```

**Comment by lgebhardt** [comment]
The above would be like a default include. However the spec adds:

> If an endpoint supports the include parameter and a client supplies it, the server MUST NOT include unrequested resource objects in the included section of the compound document.

So if you have the default include you would need to not include the author if the request specified `include=comments` for example.

**Comment by arielpontes** [comment]
Thanks for the clarification @lgebhardt, indeed I had interpreted the "included by default" differently. I still don't understand, however, how to specify whether I want:
1. **only a link** or
2. **a link** + **a list of resource identifiers**

Is it totally up for me to decide what I return in my implementation? Or am I missing something?

**Comment by lgebhardt** [comment]
I interpret it as being up to you. If you return any included resources you also need to provide the list of resource identifiers to connect the primary resources to the included ones (see the note about full linkage):

> Note: Because compound documents require full linkage (except when relationship linkage is excluded by sparse fieldsets), intermediate resources in a multi-part path must be returned along with the leaf nodes. For example, a response to a request for comments.author should include comments as well as the author of each of those comments.

I don't see  a requirement around your two choices if no related resources (includes) are returned. I also don't see a way for the client to specify to your server whether to include the resource identifiers, so it looks to me to be a server design choice. In my implementation I chose to not include the identifiers if the related resources were not requested, but I can see inclusion as equally valid in some cases. The reasoning for this choice was sometimes there may be a large number of related resources and without a way to paginate the resource identifiers the responses could be too large.

**Comment by bernhard-gatzhammer** [comment]
I discovered the same issue. For certain use cases it can be helpful to only obtain related resource identifiers, without their full representation. Maybe it could be a solution that a server offers a dedicated query parameter similar to"included", but just for adding the related resource IDs. 

E.g.,
```
GET /articles?includeIds=author

{
  "data": [
  {
    "type": "articles",
    "id": "1",
    "attributes": {
      "title": "Rails is Omakase"
    },
    "relationships": {
      "author": {
        "links": {
          "self": "/articles/1/relationships/author",
          "related": "/articles/1/author"
        },
        "data": { "type": "people", "id": "9" }
      }
    }
  }]
}
```

**Comment by bradjones1** [comment]
Found this issue while doing some issue archaeology. I think this issue can be closed with the following conclusions, if I can be bold and suggest:

> Should relationships include data or not?

This is up to the server implementation. The spec does not _require_ a `data` attribute, just at least one of `data`, `links`, and/or `meta`. Drupal, for example, includes both `links` and `data` by default, regardless of linkage with includes.

> Is it totally up for me to decide what I return in my implementation? Or am I missing something?

I concur with https://github.com/json-api/json-api/issues/1117#issuecomment-260380419:

> ...it looks to me to be a server design choice. In my implementation I chose to not include the identifiers if the related resources were not requested, but I can see inclusion as equally valid in some cases.

**Comment by jelhan** [comment]
> For certain use cases it can be helpful to only obtain related resource identifiers, without their full representation. Maybe it could be a solution that a server offers a dedicated query parameter similar to"included", but just for adding the related resource IDs.

You could use an extension, which is part of v1.1 to do so. An extension is allowed to register an [extension-specific query parameter](https://jsonapi.org/format/1.1/#extension-query-parameters). It is also allowed to "impose additional processing rules or further restrictions". If there is interested in creating such an extensions, I would recommend to create a dedicated issues for it.

As pointed out by @bradjones1 the original question has been answered. Also no need to clarify specification has been identified. Going to close this issue.
