### ISSUE TITLE
How to handle endpoints that don’t return a resource object(s) as its primary data

### ISSUE THREAD

**Issue by andrewmtoy** [json-api/json-api#1118]
Hi everyone,
I am writing an api that exposes an Elastic Search api and was hoping to format the response using the JSON API Spec.

Currently the api looks like this:
------
#### Historical percentiles

* Example:
`/historical_percentiles?field=someField&start_time=1478810146&end_time=1478810158&bin_interval=second`

Returns the percentiles for a field over a range of time.

* Parameters:
    * __start_time__ (required) Unix epoch time
    * __end_time__ (required) Unix epoch time
    * __field__ (required)
    * __bin_interval__ (required) Elastic Search compatible interval string
    * __filters__ (optional)

```JSON
{
  "meta": {
    "time_to": "2016-11-05T01:34:31.597836+00:00",
    "time_from": "2016-10-08T01:37:51.597836+00:00",
    "bins": [
      {
        "5.0": 361.5706796497282,
        "25.0": 729.7459890881007,
        "1.0": 327.0,
        "95.0": 5520.63477722484,
        "75.0": 2844.4385814706948,
        "date": "2016-10-08T00:00:00.000Z",
        "99.0": 8380.986835876729,
        "50.0": 1617.47585721036
      },
      {
        "5.0": 365.73289647286674,
        "25.0": 779.2334616130121,
        "1.0": 328.0,
        "95.0": 5440.772302540405,
        "75.0": 2795.7787375257903,
        "date": "2016-10-09T00:00:00.000Z",
        "99.0": 8345.435844243311,
        "50.0": 1819.0584232227932
      }
    ]
  }
}
```

Ideally, I would like to wrap the payload in the data property, but JSON API spec requires that data returns a resource or resources, which must have an id and type.
The only performant way (that I can think of) to have an id for this payload would be to base64 encode the endpoint with query params.

`/historical_percentiles/base64encodedEndpointWithQueryParams`

```JSON
{
  "data": {
    "id": "base64encodedEndpointWithQueryParams",
    "type": "historical_percentiles",
    "time_to": "2016-11-05T01:34:31.597836+00:00",
    "time_from": "2016-10-08T01:37:51.597836+00:00",
    "bins": [
      {
        "5.0": 361.5706796497282,
        "25.0": 729.7459890881007,
        "1.0": 327.0,
        "95.0": 5520.63477722484,
        "75.0": 2844.4385814706948,
        "date": "2016-10-08T00:00:00.000Z",
        "99.0": 8380.986835876729,
        "50.0": 1617.47585721036
      },
      {
        "5.0": 365.73289647286674,
        "25.0": 779.2334616130121,
        "1.0": 328.0,
        "95.0": 5440.772302540405,
        "75.0": 2795.7787375257903,
        "date": "2016-10-09T00:00:00.000Z",
        "99.0": 8345.435844243311,
        "50.0": 1819.0584232227932
      }
    ]
  }
}
```

I don't like this method for a number of reasons: 
1.  the id could take up more space than the actual data being returned eg. (user enters many filters and one bin is returned)
2.  the documents are stored for a finite period of time; the user would not be able to retrieve the same resource again after some period of time by using the id and type.
3.  added complexity and redunancy of having to handle query params and base64 encoded id
4.  frequency of use, I doubt the consumers of this api would ever use the id to retrieve data

Because of these reasons, I've put it in meta for now.  My reasoning is the api is returning data about stored data, which technically is meta data of the resource.

Is there a better way to handle this that is JSON API compliant?
Should I handle this use case separately and add it to our version of the JSON API spec?

Thanks for reading,
Andrew Toy

**Comment by rpkilby** [comment]
A couple thoughts:

Do you really need to use a json-api endpoint here? As long as this exception is documented, I don't see any reason to try and force this to comply with the spec.

That said, I don't think there's really a problem with using a resource-based approach. For example:

``` http
POST /historical_percentiles HTTP/1.1
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "data": {
    "type": "historical percentile",
    "attributes": {
      "field": "someField",
      "time_to": "2016-11-05T01:34:31.597836+00:00",
      "time_from": "2016-10-08T01:37:51.597836+00:00"
    }
  }
}
```

Response:

``` http
HTTP/1.1 200 OK
Content-Type: application/vnd.api+json

{
  "data": {
    "type": "historical percentile",
    "attributes": {
      "field": "someField",
      "time_to": "2016-11-05T01:34:31.597836+00:00",
      "time_from": "2016-10-08T01:37:51.597836+00:00",
      "bins": [
        ...
      ]
    }
  }
}
```

As far as I can tell:
- There doesn't seem to be anything that requires you to return an ID. The only discussion on resource creation and IDs seems to be about client-generated IDs.
- There isn't anything in the spec that requires the object to be persisted. 
- It's perfectly acceptable to return other response codes. 200 might be appropriate here, since the request was successful, you're returning data, yet nothing is persisted.

**Comment by beauby** [comment]
@rpkilby The spec states

> A resource object MUST contain at least the following top-level members:
> - id
> - type

(with the only exception being resource-creation payloads).

**Comment by rpkilby** [comment]
Whoops - was just scanning the resource creation section. Regardless, you could always just return a randomly generated uuid.

**Comment by beauby** [comment]
This endpoint does not need to be a jsonapi endpoint to be honest. You could go with a simple json endpoint.

**Comment by andrewmtoy** [comment]
Cool, thanks the feedback.  I really appreciate it.

**Comment by andrewmtoy** [comment]
I was really hoping that JSON API could serve as the spec for any and all json responses.  If anybody else has any thoughts it would be much appreciated.

**Comment by andrewmtoy** [comment]
Our team has been using the meta property to return aggregated data for a few months now.  We've decided to change direction and add an additional section to our fork of the JSON API Spec.

When we finalize on it, I'll put it here.

Here are some related discussions that also have no resolution:
http://discuss.jsonapi.org/t/extension-for-chart-graph-data/408
http://discuss.jsonapi.org/t/representing-non-resourceful-aggregated-data/431/7 

I believe that this is an important and common use case to resolve.  Please let me know if you have any other ideas.

**Comment by bf4** [comment]
related https://github.com/json-api/json-api/issues/1131

**Comment by ethanresnick** [comment]
I'm gonna close this; I think the discourse discussions and #1131 cover this well.
