### ISSUE TITLE
Implementing <select>-like semantics with url templates

### ISSUE THREAD

**Issue by renato-zannon** [json-api/json-api#112]
Using HTML forms for searching, it's common to use the <select> tag for filters that have a fixed set of options. For example:

``` html
<form method="get" action="/search">
  <label>Contract state:
    <select name="state">
      <option value="in-force">In force</option>
      <option value="overdue">Overdue</option>
      <option value="closed">Closed</option>
    </select>
  </label>

  <label>Involving:
    <select name="involving" multiple="true">
      <option value="1">Github</option>
      <option value="2">Google</option>
      <option value="3">Facebook</option>
    </select>
  </label>
</form>
```

When using URL Templates, how would I convey the information of the possible options? For the first example, it could be described on the profile, but what if the options are dynamic, as in the second example?

**Comment by dgeb** [comment]
URI templates are no longer supported in the spec.
