### ISSUE TITLE
Dealing with relationships that own data.

### ISSUE THREAD

**Issue by zachdaniel** [json-api/json-api#1123]
We have some join tables that have fields on them (currently only one) that represents some contextual piece of data.  An example we can use is a `favorite_food_list`.  The `favorite_food_list` has many `foods`, *but* the join table between those two, call it "`favorite_food_list_foods`, also retains what order it is on that particular `favorite_food_list`, so the join table has columns like `favorite_food_list_id`, `food_id` and `position`. 

Currently, we have `position` as a field on `foods` that is always `nil`, with the exception of the request where you ask for a single `favorite_food_list` and `include?=foods`.  In that case, the position field is populated from the join table.  This limits us in a few ways (can't tell you the position of a `food` on multiple `favorite_food_lists` at the same time), not to mention its obviously suboptimal for the client to have to know that this request and this request only populates that field.
I was not able to find any recommendations or parts of the spec that address this case, but if they exist I'm more than happy to be redirected there.

What is the best way to represent these kind of data points w/ our JSON API?    
Thank you!

**Comment by utf4** [comment]
When you are having relationships with their own attributes then the best way is to consider those relationships as separate resources. In your example you will have 3 `jsonapi` resources. 

1. favorite_food_list
2. favorite_food_list_foods ( with its own column id in db table)
3. foods

'favorite_food_list' will have relation with `favorite_food_list_foods` and `favorite_food_list_foods` with `foods`.

I know it is little different than database concept but this is the exact way to handle this scenario in jsonapi.org 1.0 standard.

**Comment by beauby** [comment]
Note that you can add a `meta` member on resource identifier objects inside relationship linkage data.
```json
{
  "data": {
    "type": "foo",
    "id": "bar",
    "relationships": {
      "baz": {
        "data": [{ "type": "baz", "id": "1", "meta": { "rank": 5 }, ...]
      }
    }
  }
}
```

**Comment by zachdaniel** [comment]
@beauby This seems like a good option, thanks.
