### ISSUE TITLE
Allow DELETE that doesn't delete?

### ISSUE THREAD

**Issue by scottgonzalez** [json-api/json-api#1138]
We have resources that don't actually get deleted, instead they get a disabled status and can later be re-activated. Would it be valid to allow a DELETE request and respond with a 200 providing `meta` data that indicates the resource has been disabled?

**Comment by jamesplease** [comment]
One idea would be to consider the `enabled` (or `disabled`) state of the resource to be a regular old attribute. Then you could use PATCH to modify the value.

**Comment by scottgonzalez** [comment]
That's what we currently have, but we were wondering about the validity of allowing DELETEs. Conceptually users do think of this as a delete. This type of behavior has been baked into OSes forever, with concepts like Trash and Recycle Bin. I know the WordPress API also has similar functionality, where the first DELETE just moves a post to the trash and then a second DELETE actually deletes the post. However, we realize this is really stretching the meaning of a DELETE request. At least our DELETE requests would be idempotent since there aren't two stages of deletion, but it does seem wrong to allow a DELETE and then a successful GET on the same resource without an intermediary POST.

**Comment by jamesplease** [comment]
I agree with you. If, after DELETE, the user can still request the resource, then it would not be a DELETE if you adhere to JSON API. A system I've seen involves doing this soft-delete that you're describing, but filtering out disabled requests from future GETs (and other operations). This way, consumers of the API cannot tell that it's been soft-deleted, but an engineer can recover the data later if necessary. In this case, I think a regular DELETE is correct.

With that said, I'm in favor of bending the rules when it solves a business need. From my interpretation of JSON API, there's no way to do what you've described without considering enabled/disabled to be an attribute. However, you could just author your own extension to the spec (even though JSON API doesn't officially support extensions), and remain consistent with this extension, to allow exactly what you're describing. You run the risk of being incompatible with a future version of JSON API, but I think it's worth it.

**Comment by nubs** [comment]
> A system I've seen involves doing this soft-delete that you're describing, but filtering out disabled requests from future GETs (and other operations). This way, consumers of the API cannot tell that it's been soft-deleted, but an engineer can recover the data later if necessary. In this case, I think a regular DELETE is correct.

Another option going down that same path is allowing the user to recreate the record by sending a POST with any unique keys matching the deleted record although that can't be done in all cases.

**Comment by Tav0** [comment]
This seems more as deactivate a resource, thus wouldn't this be considered as MODIFY?

**Comment by dgeb** [comment]
Here's what the [HTTP spec says about DELETE](https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html):

> The DELETE method requests that the origin server delete the resource identified by the Request-URI. This method MAY be overridden by human intervention (or other means) on the origin server. The client cannot be guaranteed that the operation has been carried out, even if the status code returned from the origin server indicates that the action has been completed successfully. However, the server SHOULD NOT indicate success unless, at the time the response is given, it intends to delete the resource or move it to an inaccessible location.

So it's fine to use DELETE to modify the underlying resource, but it SHOULD NOT remain accessible at the same location. Note that "SHOULD NOT" is different from "MUST NOT", so you have some wiggle room to allow a GET to the same endpoint. However, the strong recommendation would be to allow access to the modified resource at a different endpoint (the API equivalent of a recycle bin ♻️).

**Comment by jamesplease** [comment]
@scottgonzalez do you think this issue has been adequately resolved? If so, should we close this issue?

**Comment by scottgonzalez** [comment]
Yeah, we're about to disable DELETE requests on these resources.
