### ISSUE TITLE
Normalized include question

### ISSUE THREAD

**Issue by LaurentGoderre** [json-api/json-api#1144]
I am wondering about the include syntax for the specification, since the type and id are required why the include section would does not have a syntax like:

```json
"included": {
    "author": {
        "1": { ...},
        "76": { ... }
    },
    "comment": {
        "355": { ... },
        "578": { ... }
    }
}
```

This way you can access the data with `included[type][id]`.

I read https://github.com/json-api/json-api/issues/1072#issuecomment-237821346 and it seems peculiar that the consumer of the API would need to proprocess the data before using it. Am I missing something?

**Comment by dgeb** [comment]
The aspect that's often overlooked here is that, if an included resources is present in `data` as a primary resource, then it must not be duplicated in `included`. Furthermore, primary resources can be ordered, so collections are presented as arrays, which can't be accessed with a type/id hash lookup. If the spec allowed duplication of resources in a document, then we very well may have adopted the strategy you've proposed for `included`.

FYI, we are considering an option to allow clients to request a more directly browsable format. More details coming soon.

**Comment by LaurentGoderre** [comment]
Thanks for the explanation! Makes sense.

**Comment by olosegres** [comment]
There is a client js&php libs to specification, that provide the way you want to work with data in included:
https://github.com/olosegres/jsona-js
https://github.com/olosegres/jsona-php

**Comment by LaurentGoderre** [comment]
Nice! Thanks!
