### ISSUE TITLE
Post with included attribute

### ISSUE THREAD

**Issue by tomcat90** [json-api/json-api#1146]
I have an endpoint with a has_many relationship. For this case let's say Object Foo needs many Bars. The way the backend is structured I need to create the Foo and multiple Bars all at once and link them together via a transaction. If the Foo or any bar fails to be created then it should roll back and send an error back. Would I accomplish this by Posting to /foo with the attributes for Foo and then in that body also post "included" with the attributes for each Bar? The only documents I can find only mention "included" in the Get response and not the POST. Thanks!

**Comment by mwpastore** [comment]
Unfortunately, there's no standard way of including related object attributes in a request, and no standard way of wrapping multiple dependent operations in a single "transaction." The recommended solution is to create the Foo, then create the Bars, and either associate the Bars to the Foo when you create them or do so in a third step (i.e. `PATCH` or `POST /foos/:foo_id/relationships/bars`). If any step of this fails, you'll need to manually "roll back" the other steps by deleting resources and/or dissociating (disassociating?) them. It's admittedly painful.

There are several proposals/work-arounds out there to either include related object attributes in a request or encapsulate multiple operations in a single request, but to the best of my knowledge, none of them have been accepted as a new standard, and all of them are very much implementation-specific.

**Comment by beauby** [comment]
Ref #1089.

**Comment by squiddle** [comment]
You could model the construction of the target object as requiring a construction process (factory pattern). So you create a resource for the construction process itself, patch it with all the data needed and finally trigger the construction with a final patch.

example

so you start by 

    POST /foo-constructions

and add the details as PATCHes on the returned foo-construction

    PATCH /foo-construction
    foo-data
    bar-data[1]
    ....

and finally

    PATCH /foo-construction/{id}
    constructed = true

by setting constructed to true the transaction starts, and you can return from the construction a document with relationships to all the constructed things.

This uses no extensions to json api, but is not discoverable or intuitive.

**Comment by olosegres** [comment]
Without violating the standard you may use UUID and send body this relationships and data in included, with ids, that contains generated UUIDs.

If you work with JavaScript, it may be conveniently to use [jsona](https://github.com/olosegres/jsona) for create correct json from data, that you want to send.

**Comment by ethanresnick** [comment]
Closing in favor of #1197
