### ISSUE TITLE
PATCH syntax proposal

### ISSUE THREAD

**Issue by kikito** [json-api/json-api#115]
Hi there,

I confess I was a bit surprised when I first read the PATCH syntax:

```
PATCH /photos/1
Content-Type: application/json-patch+json

[
  { "op": "replace", "path": "/photos/0/src", "value": "http://example.com/hamster.png" }
]
```
- JSON API defines 3 reserved attributes, but yet `"op"`, `"path"` and `"value"` are ... "special".
- Also, the path syntax "/path/to/resource/field" seems unnecessary (The path to the resource in question is already defined on the request main path.

I propose the following:
- For field replacements, just use the conventional "form-like" syntax:
  
  PATCH /photos/1
  Content-Type: application/json-patch+json
  
  { "src": "http://example.com/hamster.png", "title": "A new title" }

This is aligned with what we see in the rest of the verbs, and its (I think) what most people will expect. It doesn't use any special attributes, and doesn't use the "path/to/resource/field" syntax.
- For collection operations (add+delete) I would suggest adding two special attributes, concentrated on list operations only. I would use `"+"` and `"-"` (`"add"` and `"remove"` would also be fine, but are a bit less cool):
  
  PATCH /photos/1
  Content-Type: application/json-patch+json
  
  { "comments": {"+": [21, 30], "-": [5]} }

So the previous request would add comments 21 and 30 to the post, and remove comment #5.

I think arrays could be made optional when there is only one element `{ "comments": {"+": 30}` would be the same as `{ "comments": {"+": [30]}`.

A PATCH that does everything together would look like this:

```
PATCH /photos/1
Content-Type: application/json-patch+json

{ "src": "http://example.com/hamster.png",
  "title": "A new title",
  "comments": {"+": [21, 30], "-": 5}
}
```

**Comment by guillec** [comment]
Quick question, 
are you confusing the HTTP Patch method with the JSON Patch RFC http://tools.ietf.org/html/rfc6902 ? 

thanks

**Comment by steveklabnik** [comment]
Yup, I think you are.

I want to relax JSON API to be 'any diff media type, preferring JSON PATCH' but haven't discussed it with everyone yet.

**Comment by kikito** [comment]
The first example code from my OP is comes straight from jsonapi.org (section "Updating a Document (PATCH)"). I didn't know that PATCH actually specifies op, value, replace, etc. That's ... _creative_. Thanks for your help.

> I want to relax JSON API to be 'any diff media type, preferring JSON PATCH' but haven't discussed it with everyone yet.

Nice!

**Comment by jokeyrhyme** [comment]
related to #167
