### ISSUE TITLE
Feedback request (another php implementation)

### ISSUE THREAD

**Issue by f3ath** [json-api/json-api#1150]
Hi there. I am making a php7 library to build JSON API requests strictly according to the specification. While it is still a work in progress, I consider the internal API stable enough. Please [take a look](https://github.com/json-api-php/json-api). I would appreciate your critics a lot. Here is [the discussion thread](https://github.com/json-api-php/json-api/issues/4) where I explained my motivation a little bit more.

**Comment by jamesplease** [comment]
That seems pretty cool, @f3ath . I'm not sure if this issue tracker is a good place to talk about implementations, though -- I'm thinking this issue should probably be closed to keep this issue tracker clean. There are lots of other conversations going on here about improving the spec itself. What do you think?
