### ISSUE TITLE
Clarification on ids in attributes

### ISSUE THREAD

**Issue by paulfalgout** [json-api/json-api#1157]
I've read through https://github.com/json-api/json-api/pull/588 and https://github.com/json-api/json-api/issues/799

For the most part I get the argument why `type` shouldn't be included in the attributes, but I'm not sure I completely understand `id`.

If my "id" attribute on a model was some other value like "uuid" would this be recommended against?:
```json
{
  "type": "articles",
  "id": "1",
  "attributes": {
    "uuid": "1",
    "title": "Rails is Omakase"
  }
}
```

Similarly it seems like a lot of data implementations of models expect a json attributes object that includes the id.  For backbonejs for instance you may need the data to be:
```js
new MyBackboneModel({
  "uuid": "1",
  "title": "Rails is Omakase"
});
// but for some other model it may need to be
new MyBackboneModel({
  "id": "1",
  "foo": "bar"
});
```
So I understand not wanting _different_ `id` values in the `attributes` from the root.. but I'm not sure I understand why `id` shouldn't exist in the `attributes` if it is the same `id`

Not that this is hard:
```js
Backbone.Collection.extend({
  parse(response) {
    return _.map(response.data, data => {
      data.attribute.uuid = data.id;
      return data.attributes;
    });
  }
});
```

But I'd much rather be able to everywhere:
```js
Backbone.Collection.extend({
  parse(response) {
    return _.map(response.data, 'attributes');
  }
});
```

**Comment by paulfalgout** [comment]
Just saw the link to http://discuss.jsonapi.org/  Once my post gets accepted, I'll link to it here and close this.

**Comment by dgeb** [comment]
@paulfalgout I just approved your post over at the forum (thanks for posting there btw). Please give that post a new title and then link to it from here.

**Comment by paulfalgout** [comment]
http://discuss.jsonapi.org/t/clarification-on-ids-in-attributes/967

**Comment by paulfalgout** [comment]
@jmeas if you've got a minute mind looking over this conversation?  I feel like I can get a clear answer from you and it looks like you've had some experience.
