### ISSUE TITLE
`self` link inconsistency

### ISSUE THREAD

**Issue by tadast** [json-api/json-api#1159]
The spec says that [a link can be either a string or an object](http://jsonapi.org/format/#document-links).

However the schema enforces that [`self` links must be strings](https://github.com/json-api/json-api/blob/509ee949c621cee5683c959d4268386e1a592b83/schema#L158-L162).

(It is also a bit odd that the properties and descriptions in `definitions/links` seems to be [relationship-specific](https://github.com/json-api/json-api/blob/509ee949c621cee5683c959d4268386e1a592b83/schema#L154-L168), but this definition is referenced from [resource](https://github.com/json-api/json-api/blob/509ee949c621cee5683c959d4268386e1a592b83/schema#L144-L146) and [top level](https://github.com/json-api/json-api/blob/509ee949c621cee5683c959d4268386e1a592b83/schema#L38-L43) link objects.)

I was wondering if the `self` links are an exception and must be strings intentionally, or is it a bug in the schema? If it's the latter I'd be happy to open a PR to fix the schema.

Sample use case: on a project I'm working on we prefer links as objects v.s. links. We have a convention to pass extra meta data for each link e.g. request header, http verb (GET/PUT/POST) and so on. However the schema validations fail if a resource `self`link is an object, even though there doesn't seem to be anything in the documentation that makes `self` links exceptional.

**Comment by steveklabnik** [comment]
I think it's a bug in the schema; that is, we work on the spec, and we tried to make the schema fit it, but there may be an error. It's been a while, but it might be

> Validation will not yield false negatives, but could yield false positives for the sake of flexibility.

This is from the FAQ. http://jsonapi.org/faq/#is-there-a-json-schema-describing-json-api

I wonder if these is one of those issues...

**Comment by tadast** [comment]
Hi @steveklabnik, thanks for a quick response :)

It does seem like a false-negative, because if I understand correctly what you're saying the spec is the source of truth and the schema should actually pass where a `self` link is an object. 

If my interpretation of your answer above is not correct let me know. I'll try to fix the schema and open a PR in the meantime.
