### ISSUE TITLE
Create with Multiple Relationships

### ISSUE THREAD

**Issue by jamesarosen** [json-api/json-api#1162]
In http://jsonapi.org/format/#crud-creating, the spec says,

> If a relationship is provided in the relationships member of the resource object, its value MUST be a relationship object with a data member. The value of this key represents the linkage the new resource is to have.

The use of "the linkage" suggests that there can be only one relationship of a particular type.

So while
```json
{
  "relationships": {
    "tags": {
      "data": [
        { "type": "tag", "id": 12345 },
        { "type": "tag", "id": 67890 }
      ]
    }
  }
}
```
is specifically allowed in fetching, it doesn't _seem_ to be for creating.

### Suggestions:

 * include a link to the [relationships object docs](http://jsonapi.org/format/#document-resource-object-relationships) in this section
 * state that any structure allowed in fetching is allowed in creating, so long as each _resource linkage_ contains at minimum, `{ id, type }`.
 * change "the linkage" to "the linkage(s)"

**Comment by dgeb** [comment]
@jamesarosen The intention is that "the linkage" represents linkage between the primary resource and any number of related resources (as appropriate for the relationship). This is spelled out in further detail here: http://jsonapi.org/format/#document-resource-object-linkage. This section states that "linkage" can be represented by an array of resource identifier objects or a single resource identifier object, but I'm open to trying to make this more clear if necessary.

**Comment by jamesarosen** [comment]
Perhaps just linking to linkage would be sufficient. That would imply that "anything that goes for resource linkages applies here."

**Comment by dgeb** [comment]
Yes, that's a great suggestion 💯

**Comment by dgeb** [comment]
I'll leave this open until we add that link
