### ISSUE TITLE
Proposal to always wrap relationship IDs in an array

### ISSUE THREAD

**Issue by andrewsardone** [json-api/json-api#117]
I'd like to propose a change to how the `"links"` object's values are represented.

Currently the [ID-based JSON API](https://github.com/json-api/json-api/blob/gh-pages/format/index.md#id-based-json-api) specifies that the `"links"` object represents related documents, linking to those related documents by their ID. A [to-one relationship](https://github.com/json-api/json-api/blob/4f494182c5fe66f29f62aa13d2bc1e08b68a2b0c/format/index.md#to-one-relationships) is a single string or number value, whereas a [to-many relationship](https://github.com/json-api/json-api/blob/4f494182c5fe66f29f62aa13d2bc1e08b68a2b0c/format/index.md#to-many-relationships) is a JSON array value of IDs:

``` json
{
  "posts": [{
    "id": "1",
    "title": "Rails is Omakase",
    "links": {
      "author": "9",
      "comments": [ "5", "12", "17", "20" ]
    }
  }]
}
```

With the [URL-Based JSON API](https://github.com/json-api/json-api/blob/4f494182c5fe66f29f62aa13d2bc1e08b68a2b0c/format/index.md#url-based-json-api), relationships can be expressed with string values representing URLs, or [URL template shorthands](https://github.com/json-api/json-api/blob/gh-pages/format/index.md#url-template-shorthands) to reduce duplication and/or bridge between an ID-based JSON API:

``` json
{
  "posts": [{
    "id": "1",
    "title": "Rails is Omakase",
    "links": {
      "author": "http://example.com/people/1",
      "comments": "http://example.com/comments/5,12,17,20"
    }
  }]
}
```

``` json
{
  "links": {
    "posts.comments": "http://example.com/comments/{posts.comments}"
  },
  "posts": [{
    "id": "1",
    "title": "Rails is Omakase",
    "links": {
      "comments": [ "1", "2", "3", "4" ]
    }
  }]
}
```

This is very slick, but it can also create ambiguity. Within a `"links"` object, a string value can be:
1. A single ID for a to-one relationship, e.g., `{ "links" : { "author": "1" } }`
2. A URL to a to-one relationship, e.g., `{ "links": { "author": "http://example.com/people/1" } }`
3. A URL to a to-many relationship, e.g., `{ "links": { "comments": "http://example.com/comments/5,12,17,20" } }`.

I propose the following:
1. If a `"links"` relationship is pointing to an ID, it needs to be wrapped in an array, even for to-one relationships. `{ "links" : { "author": ["1"] } }`
2. If a `"links"` relationship is pointing to a URL, it is a string value. `{ "links": { "author": "http://example.com/people/1" } }` `{ "links": { "comments": "http://example.com/comments/5,12,17,20" } }`

This means clients don't need to guess or rely on out-of-band information to determine how `"links"` are resolved, but can determine so by the JSON type of the value.

**Comment by rkh** [comment]
This assumes that one-to-many relations can always be resolved by a single API call. I mean, it seems to me that the spec assumes the same, but does not explicitly state so.

**Comment by dgeb** [comment]
@andrewsardone - thanks for pointing out a possible way to resolve this ambiguity. We ended up going with a more declarative approach in 8d3adde90161ec4118f8ec5b0c758d807dfc4100 .

A document's URL must now be specified within `"links"` with a nested object containing an `"href"` attribute. For example:

```
{ "links": { "author": {"href": "http://example.com/people/1"} } }
```

The preferred place to specify URLs is at the top level `"links"` object with a URL template.
