### ISSUE TITLE
Updating relationships: DELETE only supported for to-many relationships?

### ISSUE THREAD

**Issue by adam-lynch** [json-api/json-api#1173]
The "Updating Relationships" specification section goes like this:

> ### Updating Relationships
>
> ...
>
> #### Updating To-One Relationships
>
> ... 
> (no mention of `DELETE`)
> ...
>
> #### Updating To-Many Relationships
>
> ...
>
> If the client makes a `DELETE` request to a URL from a
[relationship link][relationships] the server **MUST** delete the specified
members from the relationship or return a `403 Forbidden` response. If all of
the specified resources are able to be removed from, or are already missing
from, the relationship then the server **MUST** return a successful response.

> Note: As described above for `POST` requests, this approach helps avoid
pointless race conditions between multiple clients making the same changes.

>Relationship members are specified in the same way as in the `POST` request.

>In the following example, comments with IDs of `12` and `13` are removed
from the list of comments for the article with ID `1`:

>```http
>DELETE /articles/1/relationships/comments HTTP/1.1
>Content-Type: application/vnd.api+json
>Accept: application/vnd.api+json
>
>{
>  "data": [
>    { "type": "comments", "id": "12" },
>    { "type": "comments", "id": "13" }
>  ]
>}
>```

> Note: RFC 7231 specifies that a DELETE request may include a body, but
that a server may reject the request. This spec defines the semantics of a
server, and we are defining its semantics for JSON API.

---

Even though `DELETE` is described in a general way ("If the client makes a `DELETE` request to a URL from a [relationship link][relationships]"), since it is only described within the "Updating To-Many Relationships" section, I assume that `DELETE /articles/1/relationships/thing` (for example) is only support if it's a to-many relationship. Therefore, the only way to delete the relation is to `PATCH /articles/1/relationships/thing` with `data: null` to effectively do the same thing for a one-to-one relationship.

I would just like if someone could clarify that please.

**Comment by adam-lynch** [comment]
Never mind, what I said is correct. I glanced over some bits too quickly:

> #### Updating To-One Relationships
>A server **MUST** respond to `PATCH` requests to a URL from a to-one relationship link as described below.
>...
> #### Updating To-Many Relationships
>A server **MUST** respond to `PATCH`, `POST`, and `DELETE` requests to a URL _**from a to-many relationship link**_ as described below.
>...

**Comment by maurei** [comment]
made a new issue regarding this: https://github.com/json-api/json-api/issues/1296
