### ISSUE TITLE
Link hints

### ISSUE THREAD

**Issue by andrewsardone** [json-api/json-api#118]
Are there any plans to help clients determine whether or not certain types of requests can be made on links? For example, with something similar to [HTTP Link Hints](https://tools.ietf.org/html/draft-nottingham-link-hint-00), a document;s `"links"` could declare supported methods that clients could learn.

For example, if a `posts` document's `author` and `comments` _can not_ be deleted or edited in anyway (perhaps due to limited permissions), the document's `"links"` could include:

``` json
{
  "posts": [{
    "id": "1",
    "title": "Rails is Omakase",
    "links": {
      "author": {
        "href": "http://example.com/people/1",
        "hints": {
          "allow": ["GET"]
        }
      },
      "comments": {
        "href": "http://example.com/comments/5,12,17,20",
        "hints": {
          "allow": ["GET"]
        }
      }
    }
  }]
}
```

This may be beyond JSON API's “build a data-store of information” goal and more in the HATEOAS-camp. I was just curious — I hadn't come across anything similar in the spec or issues.

**Comment by steveklabnik** [comment]
This is one of the jobs of a link relation.

**Comment by rkh** [comment]
> This is one of the jobs of a link relation.

Is this a yes or a no? Note that json-home implements these exact links.

**Comment by jcallaha** [comment]
Would the idea be that there might be different methods available for different documents even within the same type?  (e.g. the ability to PUT or DELETE a `post` that the client has authenticated as the author?)

Otherwise I would think this more sensible to be in a profile or json-home document, or at least the top-level `links` object to keep from resending the same GET hint for a URI that results in 200 `comments`.

**Comment by rkh** [comment]
> Would the idea be that there might be different methods available for different documents even within the same type? (e.g. the ability to PUT or DELETE a post that the client has authenticated as the author?)

It can be used that way, yes. From draft-nottingham-link-hint:

> [T]he information in a link hint is specific to the link it is attached to.  This means that if a representation is specific to a particular user, the hints on links in that representation are also specific to that user.

Note that you won't have to use hints on all links (or at all) and a client can feel free to not interpret them.

It is nice that json-home implements them, though there is no clear way, except for using the templates from json-home to _parse_ the links given in JSON API.

From RFC 6570:

> Some URI Templates can be used in reverse for the purpose of variable matching: comparing the template to a fully formed URI in order to extract the variable parts from that URI and assign them to the named variables. Variable matching only works well if the template expressions are delimited by the beginning or end of the URI or by characters that cannot be part of the expansion, such as reserved characters surrounding a simple string expression. In general, regular expression languages are better suited for variable matching.

Compare #126 and #159.

**Comment by steveklabnik** [comment]
Yes, when you define what your relations are in your profile, you should define what HTTP methods you intend to use. We don't need them repeated in the body. This is how @mikekelly did HAL.

**Comment by andrewsardone** [comment]
> when you define what your relations are in your profile, you should define what HTTP methods you intend to use. We don't need them repeated in the body

This makes sense when defining some broad schema – users can always read, create, and edit `comments` (`GET`, `POST`, `PATCH`) but never delete – but unless I'm missing something this seems cumbersome when defining business rules around the verbs.

Can these profiles be unique to each individual request? How else would one express the scenario when, say, deletion of comments is only allowed for ones the user has created?

**Comment by steveklabnik** [comment]
> Can these profiles be unique to each individual request?

yes, it's a parameter to the type or a header. I think this adds extra complexity, though.

> How else would one express the scenario when, say, deletion of comments is only allowed for ones the user has created?

You would put that sentence in your profile.

**Comment by andrewsardone** [comment]
What's the reasoning behind requiring a profile?

I see that it's potential feature creep, but shoving this into a profile potentially means people will be routinely solving the same problem.
