### ISSUE TITLE
Non Canonical URIs

### ISSUE THREAD

**Issue by ghost** [json-api/json-api#1189]
I have been reading the spec to implement it on a PHP project I work on, yet I noticed that the URIs for relationships aren't canonical.

`GET /articles/1/relationships/comments HTTP/1.1`

would get the related comments.

`GET /articles/1/relationships HTTP/1.1`

What happens here? This is a perfectly valid URI and should have a valid response.

---

A more canonical way to do it would be just have the relationship directly off the resource.

`GET /articles/1/comments HTTP/1.1`

This is more correct in a canonical form, and there is nothing saying it shouldn't be done this way.

**Comment by dgeb** [comment]
Please see the URL design recommendations here: http://jsonapi.org/recommendations/#urls-relationships

A URL such as `/articles/1/comments` is recommended for accessing _related resources_, as opposed to `/articles/1/relationships/comments`, which accesses the _relationship_ data (i.e. resource identities in the relationship). 

Currently, `GET /articles/1/relationships` is unspecified as an endpoint. In other words, feel free to provide a response of your choosing here, but don't expect standard clients to understand what to expect there.

**Comment by ghost** [comment]
Closing this issue like this makes me assume you're not open to any discussion on improving the spec which I feel is bad form.

Maybe the spec should aim to include people to improve by actually defining what should happen at levels of a url pattern?

HTTP is about resources at endpoints, and I don't see how `/articles/1/relationships/comments` can be considered a resource, or collection? It is merely data that forms a part of a separate resource. That data is provided in the main resource anyway, so why does it need it's own uri that doesn't follow HTTP standards?

I'm not aiming to be an arse here, but rather to help improve the spec and the understanding of how HTTP resource specifications should be worded and written.

**Comment by dgeb** [comment]
Believe me, there's no intention to exclude you or anyone else. I simply closed this issue because I answered the questions you posed.

If you have a proposal to make, please do so in a new issue. If you want to discuss nuances and build up to a proposal, please do so at http://discuss.jsonapi.org/
