### ISSUE TITLE
Should numeric values be sent as strings?

### ISSUE THREAD

**Issue by jezmck** [json-api/json-api#1200]
From the homepage example:
```{
  ...
  "data": [{
    "type": "articles",
    "id": "1",
    ...
```

Why is it not `... "id": 1, ...`?

ref: https://spacetelescope.github.io/understanding-json-schema/reference/numeric.html

**Comment by adam-lynch** [comment]
They're allowing for alphanumeric IDs as well but I don't think it has to be a string if yours are IDs. I'll be returning ints.

**Comment by steveklabnik** [comment]
http://jsonapi.org/format/#document-resource-objects

> Every resource object MUST contain an id member and a type member. The values of the id and type members MUST be strings.

So it's not about numeric values, it's about IDs. And yes, @adam-lynch , they must be strings.

We try to keep the issue tracker for spec work only, for questions, please post on http://discuss.jsonapi.org/ in the future, thanks!

**Comment by adam-lynch** [comment]
Ugh 😄

**Comment by ethanresnick** [comment]
Note: fields other than type and id can hold numbers or whatever you want. It's just that we wanted the fields for resource identification to always have a consistent type.

**Comment by jezmck** [comment]
Then this is a poor example, can it be updated? 

Include some integers and use non-numeric IDs.

**Comment by ethanresnick** [comment]
> Then this is a poor example, can it be updated?

Feel free to submit a PR. Honestly, though, I think it's probably *good* that the example shows a numeric id, because it helps communicate that, even with numeric ids, a string must be used. If the id were alphanumeric, that might give more people the mistaken impression that integers can be used for simple numeric ids.

**Comment by jezmck** [comment]
It's missing any numbers formatted as numbers, hence the initial confusion.

**Comment by ethanresnick** [comment]
Gotcha. I agree, an example to fix that would be good. Again, PR welcome!
