### ISSUE TITLE
POST array validation on create

### ISSUE THREAD

**Issue by vdmgolub** [json-api/json-api#121]
I got some issues implementing POST create action with [rails-api](https://github.com/rails-api/rails-api) and [strong_parameters](https://github.com/rails/strong_parameters). It appears that strong_parameters can't validate array in the request body and there is no simple way to find workaround:

Given request body:

``` json
{
  "photos": [{
    "title": "Ember Hamster",
    "src": "http://example.com/images/productivity.png"
  }]
}
```

Strong_parameters tries to validate it:

``` ruby
photos_hash = params.require(:photos) # returns Array, but should be  ActionController::Parameters
photos_hash.permit(:title, :src) # raises ActionController::ParameterMissing exception
```

Here is discussion [thread](https://github.com/rails/strong_parameters/issues/140#issuecomment-18084213).

I believe implementation details are out of scope of this documentation. But can you suggest a way of processing such array?

**Comment by steveklabnik** [comment]
Wouldn't you just iterate? Ie, `params[:photos].each....`?

**Comment by vdmgolub** [comment]
Your example skips `require[:photos]` usage, but you're right, it's okay to iterate here. I've come up with similar solution:

``` ruby
def create
  photos = []

  photo_params.each do |p|
    photo = Photo.new(p)
    photos << photo if photo.save
  end

  render json: photos, status: 201
end
```

It's a bit tricky in `photo_params`:

``` ruby
def photo_params
  params.require(:photos).map do |p|
     ActionController::Parameters.new(p.to_hash).permit(:title, :src)
   end
end
```

However I have a question: what if during bulk create not all objects are saved successfully? It means that the response will have json of saved data plus errors?

**Comment by steveklabnik** [comment]
> what if during bulk create not all objects are saved successfully? It means that the response will have json of saved data plus errors?

This is entirely dependent on your controller code.

**Comment by vdmgolub** [comment]
I understand that it depends on my implementation, but I would like to know if JSON-API has any rules for that. There is a discussion about error response format here, but as far as I know there is no any decision yet to make a standard. Do you have any plans for JSON-API to include errors description?

**Comment by steveklabnik** [comment]
The discussion is specifically discussing the plans.
