### ISSUE TITLE
implement menu like structure

### ISSUE THREAD

**Issue by Gibheer** [json-api/json-api#122]
Hi,

how would a menu like structure in every document look like? I'm building an API which answers in json-api and html, but should both contain the same content.

```
{
  "links": {
    "posts": "/posts",
    "tags": "/tags"
  },
  "posts": {[
    // some posts here
  ]}
}
```

Would that be the way to go or should "links" reside in a meta block?

**Comment by steveklabnik** [comment]
This example is fine.
