### ISSUE TITLE
json-schema.org schema lacks a version

### ISSUE THREAD

**Issue by n2ygk** [json-api/json-api#1220]
There's no {json:api} version in the json-schema.org [schema](https://github.com/json-api/json-api/blob/gh-pages/schema) file.

**Comment by bf4** [comment]
@n2ygk Not sure what you mean.  Whether the schema describe 1.0 or 1.1?

Also, you reference json-schema.org  but link to https://github.com/json-api/json-api/blob/gh-pages/schema  which do you mean?

FWIW, linking to comment that the JSON SCHEMA is not authoritative https://github.com/json-api/json-api/pull/440#issuecomment-151013219

**Comment by n2ygk** [comment]
@bf4 There's no metadata in the schema at https://github.com/json-api/json-api/blob/gh-pages/schema which identifies the version of jsonapi it describes.  My reference to json-schema.org is simply that the jsonapi schema is written using the json-schema.org standard schema notation.  Might want to have a top-level 'id' key that references the jsonapi version.

**Comment by bf4** [comment]
> 
I look forward to your PR :)
>

**Comment by n2ygk** [comment]
@bf4 PR submitted, but I note there seems to be at least one other, https://github.com/json-api/json-api/pull/1079, that tried to do the same, except it doesn't set a version.

**Comment by lorenzleutgeb** [comment]
I noticed the same. Exposing a JSON Schema without referring what JSON API version it relates to is quite dangerous IMO.

**Comment by Relequestual** [comment]
Vote to close in favour of https://github.com/json-api/json-api/issues/1522

**Comment by dgeb** [comment]
Sounds good, we'll pick up the discussion in #1522.
