### ISSUE TITLE
Requests with `include` should always return `included`

### ISSUE THREAD

**Issue by noetix** [json-api/json-api#1230]
When requesting results with included data, the response should always have the `included` top-level key. The response structure should not change depending on the data sourced to generate the response.

e.g. `GET /todos?include=comments`

The expectation is that the response should have a list of todo items under `data` and any included data under `included`, but depending on whether there comments or not will determine whether `included` as a top-level key exists or not.

As a client trying to use this data I have to first check that the array exists then try find my result.

**Comment by beauby** [comment]
The idea is that you would use come kind of client library to take care of that on the client side. If you do not want to commit to a full-fledged client library because you feel your use-case is too simple for that, you can simply define a helper function that does the checking for you.

**Comment by noetix** [comment]
I do use a client library to facilitate these requests and I could have posted this issue there. However, aside from the fact that the client library author would turn to the spec for guidance -- to which he would receive none -- the issue is about returning a consistent message format.

When my request has specifically asked for included data to be returned, I expect that the `included` top-level member to be there regardless of whether there are any results. Exactly the same as `data` -- we don't optionally include that depending on result set.

**Comment by seanrkerr** [comment]
👍

**Comment by ethanresnick** [comment]
I would be open to a PR mandating that, if the `include` parameter is in use, `included` must be present in the response document (even if empty). Please feel free to submit.

**Comment by ethanresnick** [comment]
I’ve merged #1236 to address this. If anyone objects, we can discuss further.
