### ISSUE TITLE
Inconsistency on fetching relationships

### ISSUE THREAD

**Issue by darrensony** [json-api/json-api#1234]
In the specification under "Fetching Data", it states that fetching relationships MUST support

```
GET /articles/1/author HTTP/1.1
Accept: application/vnd.api+json
```

Immediately after, under "Fetching Resources", it states MUST support

```
GET /articles/1/relationships/author HTTP/1.1
Accept: application/vnd.api+json
```

However there is no guidance as to what, if anything, is different about these two calls, or when one would be used as opposed to the other.

**Comment by mwpastore** [comment]
The first request returns the author as the primary resource. [example payload](http://jsonapi.org/format/#fetching-resources-responses-200)

The second request returns the relationship data (i.e. the linkage) from the article to the author. [example payload](http://jsonapi.org/format/#fetching-relationships-responses-200)

**Comment by darrensony** [comment]
So just for clarity, using the data from http://jsonapi.org/format/#document-compound-documents

GET /articles/1/author

Returns either the same data as .included[0] (the primary resource, same as /people/9),
```
{
  "data":  {
    "type": "people",
    "id": "9",
    "attributes": {
      "first-name": "Dan",
      "last-name": "Gebhardt",
      "twitter": "dgeb"
    },
    "links": {
      "self": "http://example.com/people/9"
    }
}
```

Or the primary resource in the context of the article (links.self == request URL) but still the same data as .included[0],
```
{
  "data":  {
    "type": "people",
    "id": "9",
    "attributes": {
      "first-name": "Dan",
      "last-name": "Gebhardt",
      "twitter": "dgeb"
    },
    "links": {
      "self": "http://example.com/articles/1/author"
    }
}
```

Or is there no equivalence at all between them, i.e.

```
GET /articles/1/author   
  (is not the same as)
GET /authors/1
  (when /authors/1 is the author of /articles/1)
```

and 

```
GET /articles/1/relationships/author
   ~~> .links.related ~~> GET
  (is not the same as)
GET /articles/1/relationships/author
  ~~> GET /.data.type/.data.id
```

Thanks
Darren

**Comment by mwpastore** [comment]
A resource's serializer generally doesn't have any information about the context in which it's being serialized (at least not in the serializers I've worked with), so it should always generate the same payload (or relevant portion thereof), whether it's included or gotten at through a related link, self link, or type and ID.

**Comment by darrensony** [comment]
ok thanks
