### ISSUE TITLE
Create a Globals item shorthand to reduce size of the JSON API Outputs

### ISSUE THREAD

**Issue by grantkemp** [json-api/json-api#1238]
I really love the work that JSON API spec is doing. Its something I have wanted for a long time. 

One of the use cases is that it needs to work well for mobile clients and is a bit long winded with repeating things like hostname with every element.  This could be an optional flag that could be layered on existing JSon API = ?Shorthandnotation=true

We could use a shorthand method to reduce the overall size of the overall api and make it faster to download and parse on mobile. 

Eg: 
Instead of:
```
  "links": {
    "self": "http://example.com/articles",
    "next": "http://example.com/articles?page[offset]=2",
    "last": "http://example.com/articles?page[offset]=10"
  },

```
we could have 
```
"globals": { 
"~hn": "http://example.com"
},
 "links": {
    "self": "~hn/articles",
    "next": "~hn/articles?page[offset]=2",
    "last": "~hn/articles?page[offset]=10"
  },
```
@sirclickalot also has a good suggestion about potentially even pushing protocol out to make it even more generic. 

**Enhanced shortcode**
You could also potentially even create custom shorthands for longer elements eg articles : 
`~arto : http://example.com/articles`
and make it even smaller to return the api result 
```
"globals": { 
"~hn": "http://example.com",
"~arto": "http://example.com/articles"
},
"links": {
    "self": "~arto",
    "next": "~arto?page[offset]=2",
    "last": "~arto?page[offset]=10"
  },
```

**Comment by jaredcnance** [comment]
Nothing in the spec says you can't use relative urls, e.g /articles

**Comment by grantkemp** [comment]
Maybe the style above can support APi's with multiple domains then- albeit this seems like an edgecase.  
 Didn't realise that about the Relative urls- you guys should make it clearer!

Thanks for the great work
