### ISSUE TITLE
No self link for people ?

### ISSUE THREAD

**Issue by mkimont** [json-api/json-api#1241]
Hi Guys,
Does  http://jsonapi.org/format/#document-compound-documents missing self link ?
`"data": { "type": "people", "id": "2" }`

Shouldn't be: 

```
"data": { "type": "people", "id": "2" }'
"links": {
      "self": "http://example.com/comments/5"
```

Is that even possible to have in include relationship with item with relationship ? 
Never try that ..

**Comment by dgeb** [comment]
There is not a strict requirement that `self` links be included with each resource. However, I'd be open to a PR that made the resources in the `data` and `included` sections in that example more consistent.
