### ISSUE TITLE
gRPC Proto + GraphQL Schema Standard

### ISSUE THREAD

**Issue by disturbing** [json-api/json-api#1242]
I'm about to build a schema for protobuf by following json-api. The way this is formatted, it's really going to make grpc uber flexible for building apis quickly.

Has anyone done this before? If not, how could we go about getting a standard proto file and graphql schema here and potentially in the 1.1 release.

**Comment by dgeb** [comment]
Sounds interesting. It would be good to get this discussion started over at http://discuss.jsonapi.org/
