### ISSUE TITLE
Forbid filtering and sorting by specific attributes.

### ISSUE THREAD

**Issue by firedigger** [json-api/json-api#1246]
Greetings.
We are using json-api library in a commercial application and we expose many fields. Some of the fields are not indexed and we would not like them to be used in filtering and sorting queries. I have not found support for such a use case in the library so I have come up with my own possible implementation through custom attributes.
I created a new Attribute class "NotFilterable" with no additional data.
There is a virtual method responsible for filtering in IQueryableExtensions.cs
```
public static IQueryable<TSource> Filter<TSource>(this IQueryable<TSource> source, RelatedAttrFilterQuery filterQuery)
```
Inside it I added a check for the attribute for the property used for filtering:
```
var notFilterableAttribute = (NotFilterableAttribute[])property.GetCustomAttributes(typeof(NotFilterableAttribute), false);
```
```

            if (notFilterableAttribute.Any())
            {
                Console.WriteLine("This field can't be filtered"); //for debug
                return source;
            }
```
As the filterable fields are not going to change dynamically, having a check in the code with attributes is a clean solution without any overhead. The same code should be added to the method for filtering related objects.
If you were willing to accept this design, I would gladly submit a pull request.

**Comment by jaredcnance** [comment]
@firedigger this sounds like a library issue. Specifically, this looks like [JsonApiDotNetCore](https://github.com/json-api-dotnet/JsonApiDotNetCore). Would you mind opening this issue in that repo? But take a look at this issue first: https://github.com/json-api-dotnet/JsonApiDotNetCore/issues/105

**Comment by dgeb** [comment]
Thanks for replying @jaredcnance 👍
