### ISSUE TITLE
recent updates to FAQ have broken formatting on the web page

### ISSUE THREAD

**Issue by kevmoo** [json-api/json-api#125]
Talking about commit ad3ab29590db84c73f7572e798366d2727444c47

FYI @steveklabnik 

Things look good here: https://github.com/json-api/json-api/blob/gh-pages/faq/index.md

But not how they are rendered on the web page: http://jsonapi.org/faq/

![screen shot 2013-08-30 at 2 57 11 pm](https://f.cloud.github.com/assets/17034/1060960/51369956-11bf-11e3-9590-5bc6e0794324.png)

**Comment by steveklabnik** [comment]
Bummer. I wonder if the paragraphs need to be indented with the bullets...

**Comment by kevmoo** [comment]
Perhaps? No clue what library is being used on the web page.

t'would be nice if it was identical to what GitHub uses

**Comment by steveklabnik** [comment]
@brixen I think you did that part, right? Any idea what's up here?

**Comment by brixen** [comment]
Just FYI, there's a Rake task `preview:browser` that is pretty handy.

**Comment by steveklabnik** [comment]
Ahhh awesome :+1:
