### ISSUE TITLE
Consider specifying an index route

### ISSUE THREAD

**Issue by gr0uch** [json-api/json-api#126]
There is currently no specification describing what the root path of an API might look like. An analogue might be the homepage of a website, it typically contains links to top-level resources. 

An example might look just like the top-level `links` object on a resource:

``` js
{
  "meta": {
    "name": "Blog JSON API"
  },
  "links": {
    "posts": {
      "href": "http://api.foo.com/posts/{posts.id}",
      "type": "post"
    },
    "authors": {
      "href": "http://api.foo.com/authors/{authors.id}",
      "type": "person"
    }
  }
}
```

This would enable resource discovery, as well as a generic JSON API explorer/admin interface, as mentioned in issue #13.

**Comment by rkh** [comment]
Wondering about the same.

Here is something you can do with the current format:

``` json
{
  "homes": [{
    "name": "Blog JSON API"
  }],
  "links": {
    "posts": {
      "href": "http://api.foo.com/posts/{posts.id}",
      "type": "post"
    },
    "authors": {
      "href": "http://api.foo.com/authors/{authors.id}",
      "type": "person"
    }
  }
}
```

**Comment by jcallaha** [comment]
What about JSON-HOME?  http://tools.ietf.org/html/draft-nottingham-json-home-03 - the latest draft is only a day old, so its fresh!

**Comment by rkh** [comment]
While JSON Home is nice and definitely usable with JSON API, playing with the two I found that they don't integrate very smoothly, since JSON Home actually implements RFC 5988, so there is no direct mapping from relations in there to links in JSON API. But maybe this isn't actually a problem at all.

**Comment by jokeyrhyme** [comment]
Have you guys seen this?
http://www.restdoc.org/
It's a specification for resource discovery via the OPTIONS method. Could apply here...

**Comment by steveklabnik** [comment]
The root path looks like any other JSON API response, we don't need a special one.
