### ISSUE TITLE
Difference between relationship and related

### ISSUE THREAD

**Issue by foo123** [json-api/json-api#1265]
Hello I have a requirement for subscribers and fields, each subscriber can have many fields (one to many relation). However it is not clear to me what is the difference between the following urls, do they serve different purposes and if so what? 

1. `/subscriber/1/fields`
2. `subscriber/1/relationships/fields`

I am new to JSON API and maybe I missed sth so excuse my ignorance on this.

**Comment by kjellmorten** [comment]
You're not the first to wonder about this.

1. `/subscriber/1/fields` would return the actual field [resource objects](http://jsonapi.org/format/#document-resource-objects) – with `attributes` and `relationships`.
2. `/subscriber/1/relationships/fields` would return the relationships – the [resource linkage](http://jsonapi.org/format/#document-resource-object-linkage) – objects with `id` and `type` that defines a relationships between subscribers and fields in your case.

So to get all field data for a subscriber, you would use url 1.
To e.g. delete a relationship from a subscriber to a field, you would use url 2.

Hope this makes it clearer.

**Comment by foo123** [comment]
Thanks it is clear. 

My test project does not support orphan fields (without subscriber) so no `POST/DELETE/PATCH` to second url (`/subscriber/1/relationships/fields`) it returns a `403 forbidden` header, per the` json-api` specification. So all is good.

 I dont know if I should close this or leave it open for future reference. I'll leave it up to you.

**Comment by kjellmorten** [comment]
Good to hear!

I suggest we close this, but you have to do it – I don't have that permission. :)

**Comment by dgeb** [comment]
Glad this is all clear. Thanks!
