### ISSUE TITLE
Key naming convention

### ISSUE THREAD

**Issue by gr0uch** [json-api/json-api#127]
Should there be any specification on what keys can be named? It is possible for an API to have keys that are named like:

``` js
{
  "posts": [{
    "id": 1,
    "title_of_post": "Hi Steve",
    "postBody": "JSON API!!",
    "PostTimestamp": 1378670268521
  }]
}
```

Obviously this is quite shitty naming. Should the spec disallow that, or is it up to the API maintainer to keep key naming conventions in sync?

I would like to propose that keys should be underscored. 

**Other considerations**
- This would remove any confusion that may arise from keys similarly named to the reserved keys, i.e. `iD`, `Id`, `ID`.
- Key names in non-latin languages don't have to follow this convention.

**Comment by steveklabnik** [comment]
I think this is up to the API, it's too low-level of a concern. I'm giving it a close, but if someone has a really convincing argument, I'm open to hearing it.

**Comment by sinetris** [comment]
JSON is an acronym for "JavaScript Object Notation" so I think the JavaScript style would be preferable.
I agree with @steveklabnik that it should remain a choice of the API designer.
Maybe we can suggest the JavaScript style as a best practice.
@steveklabnik what do you think?
