### ISSUE TITLE
Array vs Single Object

### ISSUE THREAD

**Issue by naturalwarren** [json-api/json-api#1275]
I recently ran into an API that returns an object if a single item is sent back for a field, and an array if multiple items are returned for the field. After searching around a bit I ran into #268 but haven't been able to concretely see if this behavior is part of the 1.0 spec.

Does the spec make the recommendation contained in #268 or is an array supposed to always be returned?

**Comment by ethanresnick** [comment]
#268, based on a quick skim, refers to the fact that the top-level `data` key holds an array when the response represents a "zero to many" items response, and a single object or null when the request can logically only match zero or one resources. That is how the current spec works:

> Primary data MUST be either:
>
> - a single resource object, a single resource identifier object, or null, for requests that target single resources
> - an array of resource objects, an array of resource identifier objects, or an empty array ([]), for requests that target resource collections


That's different from whether a field within a resource object can sometimes hold an array and sometimes hold a single value. The spec says nothing about that, so it's up to each API, though using a consistent type is likely preferable.
