### ISSUE TITLE
Change RFC2119 wording to be consistent with RFC8174

### ISSUE THREAD

**Issue by cmeeren** [json-api/json-api#1277]
See [RFC8174](https://tools.ietf.org/html/rfc8174), which contains a clarification/update of the RFC2119 wording that should ideally be used instead of the old one.

**Comment by ethanresnick** [comment]
PR welcome.

**Comment by cmeeren** [comment]
Am I right in assuming I should only edit `_format/1.1/index.md`, not `_format/1.0/index.md`?

**Comment by ethanresnick** [comment]
> Am I right in assuming I should only edit _format/1.1/index.md, not _format/1.0/index.md?

Yes, that's probably better. Idk if we've been completely strict about leaving 1.0 exactly as-is, but it's a good idea.
