### ISSUE TITLE
Question: what is the rule for multiple words attrs when we put them into query params?

### ISSUE THREAD

**Issue by yarigpopov** [json-api/json-api#1280]
When I look at the specification (http://jsonapi.org/format/#fetching) all examples are consist only one word. Because of that I can't understand what is a JSON API complaint way of listing them in the request? Namely, what is right?:

1)  GET /api/v1/nice-resource?awesomeAttribute_id=5
1)  GET /api/v1/nice-resource?awesome_attribute_id=5

**Comment by beauby** [comment]
There are recommendations [here](http://jsonapi.org/recommendations/#naming). I believe there were some talks about changing those recommendations though.

**Comment by yarigpopov** [comment]
@beauby thanks for the answer. But I checked the link and still couldn't find how to transform *multiworded* names when we put them into query params

**Comment by bravo-kernel** [comment]
@chilicoder IMO this depends on the inflection chosen by the API developers. I mostly spot kebab-case in the wild which would lead to `awesome-attribute` and `very-awesome-attribute`.

**Comment by yarigpopov** [comment]
This sounds like JSON API doesn't have opinion about this question, right?

**Comment by ethanresnick** [comment]
> This sounds like JSON API doesn't have opinion about this question, right?

The spec has no official rule. The current recommendation is kebab case (`awesome-attribute`) but I think that will eventually change to camel case (`awesomeAttribute`). I would therefore lean towards camel case, but it doesn't really matter.
