### ISSUE TITLE
Schema Support

### ISSUE THREAD

**Issue by remmeier** [json-api/json-api#1281]
Based on the discussions of deficiencies compared to GraphQL in https://github.com/json-api/json-api/issues/1272 I'm openeing this ticket to discuss the schema support.

This issue has also be raised in the Drupal implementation (https://www.drupal.org/project/jsonapi/issues/2822768) or the Crnk implementation (http://www.crnk.io/releases/stable/documentation/#_meta_module) among likely various others. Goal would be to have a standardized way to specify resources, which in turn would opened up many new possiblities:

- generic UIs to explore JSON API endpoints
- generation of client and server stubs in various programming languages to ease development
- more automated testing
- automation within user interfaces
- ...

what could the specification cover:

- definition of a primitive type system (dates, urls, boolean, string, etc.)
- definition of array types
- definition of complex types composed of attributes having a type
- definition of documents, resources, meta, links, relationship types basedon complex types.
- definition of custom types composed of any other type (primitve, array, complex, etc.)
- set of validation constraints (minimum length, regex pattern, not empty, etc.) that can be attache   to types

the schema could be implemented with two formats:

- a low-level schema definition following the JSON:API specification 
- a more lightweight/human-readable schema definition in a custom DSL similar to GraphQL and others that can be translated to the JSON:API-conform specification.

The former target automated processing/discovery, while the later is targered towards developers.

how could an implementation look like:

- JSON:API-conform schema resources could be make available JSON:API endpoint next to application-specific resources. This would be signaled to clients as profile (#1268)
- the schema definitions can be stored in one or more files with a given file suffix
- a reference implementation is provided to translate a DSL-based schema to a JSON:API-based schema.
- an (extensible) reference implementation translates JSON:API-based schema to client stubs for varous languages.
- reference implementations are made available as command line tools distributed as platform-independent docker images
- (later) a language service would provide syntax highlighting/code completing for IDEs
- the compliance test suite (https://github.com/json-api/json-api/issues/1209) would contribute a schema definition of its own together with pairs of requests/responses to check both client and server implementations.

sources of inspiration for the DSL and JSON:API-based schema:

- graphql
- JSON Schema
- openapi/swagger
- protobuf/gRPC
- https://github.com/crnk-project/crnk-framework/tree/master/crnk-meta/src/main/java/io/crnk/meta/model ( for the JSON:API-base schema, but simpler at various places)

for the first or implementations I could potentially contribute quite a substantial part based on existing crnk code base if that is desired (in an independent/new github repository). I would also have time to work on the topic since it is quite important in my area and we want to avoid home-grown things.

could be targeted for a JSON:API 1.2 release.

**Comment by remmeier** [comment]
note that while in #1272 it was mentioned that the lack of filtering standard and operations API as major issue and this one more as lower-priority. One can equally argue for this issue here as it opens up many new tooling possibilities, in particular the lack of generation of client stubs is something that has been brought up a number of times.

**Comment by handrews** [comment]
Hi folks- note that the next version of JSON Schema (informally "draft-08", formally probably "draft-handrews-json-schema-02") is adding support for modular vocabularies.  This will make it much easier to tailor JSON Schema usage to different goals and environments.

The current validation and hyper-schema specs are essentially vocabularies already.  We also plan to have a code generation vocabulary.  @philsturgeon and I have been coordinating with OpenAPI on this topic.

Draft-08 should be out by the end of September.  I'm not sure how long after that it will take to propose a code generation vocabulary, but there is a lot of interest in it, and an opportunity to influence its direction.

**Comment by remmeier** [comment]
is the 02 draft already out somewhere in a non-source/xml version?

- maybe things could get started with example how it would look like.
- from there see how it could be mapped to a JSON:API resource(s) to make it queryble
- and whether there are any objections/reasons to go for another toolstack. But if there is an alignment with OpenAPI then should be perfectly suitable for JSON:API as well.

**Comment by philsturgeon** [comment]
> from there see how it could be mapped to a JSON:API resource(s) to make it queryble

If I understand you correctly, mapping a JSON:API and JSON Schema resource is handled through HTTP, so `/users/fred` would have `Link: <http://example.com/schemas/user.json#>; rel=”describedby”` on it. 

A lot of this and more is explained on an article I wrote about [using JSON Schema for client-side validation](https://blog.apisyouwonthate.com/the-many-amazing-uses-of-json-schema-client-side-validation-c78a11fbde45), which is certainly something JSON:API users would like to do.

**Comment by handrews** [comment]
@remmeier I am actively working on draft-handrews-*-02 a.k.a. draft-08 right now.  If I had it in a form people could read I wouldn't be estimating a completion date of late September!  You can track progress with the [draft-08 milestone](https://github.com/json-schema-org/json-schema-spec/milestone/6).

If anyone here is interested in working on the code generation vocabulary, then I'd be happy to connect them with others who are interested and help get that off the ground.  But a lot of things related to vocabularies are still in flux.

**Comment by philsturgeon** [comment]
Btw there is plenty enough in JSON Schema draft 07 to be useful to JSON:API. The [core vocabulary](http://json-schema.org/latest/json-schema-core.html) alone would be a very close equivilent of GraphQL types or protobuf, and would be an easy add to JSON:API.

[Validation](http://json-schema.org/latest/json-schema-validation.html) is another very useful vocabulary, which adds functionality beyond that of GraphQL types or protobuf. The only criticisms of JSON Schema validation that I've heard are by @wycats which mentioned it was "heavy" (it can validate all sorts of things) and limited (it does not have the ability to create custom validations). 

The latter is an interesting point, as it would make code generation rather difficult to cover. Right now code generators for server-side code and client-side code can implement checks for specific validation keywords that cover the vast majority of requirements, and doing so is not that tough. If any conceviable custom validation could be created through this same vocabulary, the code would probably be a bit tougher to implement. Either way, I'd be really excited to discuss elsewhere, through an issue on the JSON Schema repo, or wherever else. 

Let's not get too distracted by code generation either way, that's really not the most important aspect of having a schema in JSON:API. :)

**Comment by handrews** [comment]
> it does not have the ability to create custom validations

It does not yet have a formal ability to do this within the JSON Schema document, but many implementations support custom keywords (off the top of my head, at least one in JavaScript and one in Python, and I think the Erlang one was working on it?  Or was that the Elixir one?  Can't rememeber).

But this is exactly what draft-08 is addressing, so that is a short-term limitation.

@philsturgeon is correct that JSON Schema draft-07 (or even draft-06, which is more widely implemented simply because draft-07 is still quite new and implementations are catching up) has more than enough to be useful.  Including informal extensibility.

**Comment by remmeier** [comment]
> Let's not get too distracted by code generation either way, that's really not the most
> important aspect of having a schema in JSON:API. :)

we make use of that in basically every project as it helps to quickly track down minor, avoidable issues when frontend and backend teams work together. 

@handrews : in terms of generation it would be interesting to not only generate the plain interfaces, 
but something one may call expression objects. http://www.querydsl.com/ and https://www.jooq.org/ are to prominent examples. We make use of it as well in the JSON:API context.
An example is given in https://github.com/crnk-project/crnk-example/blob/master/crnk-example-frontend/src/app/movie/movie.editor.component.html and https://github.com/crnk-project/crnk-example/blob/master/crnk-example-frontend/src/app/movie/movie.editor.component.ts with `this.movie = new QMovie(new BeanBinding(movie), null);` and  `[expression]="movie.attributes.year"` as generated in https://github.com/crnk-project/crnk-example/blob/master/crnk-example-frontend/src/resources/movie.ts with `QMovie`. In the end it can allow the type-safe construction of attribute paths, filter parameters, sort parameters, inclusions, etc. and when bound to a concrete instance can also give the value of the attribute path for that instance. Around 50% of our frontend use cases work with those expression objects rather then the plain resource interfaces, allowing to quickly discover many issues.

if there is a first conclusion about the JSON schema with JSON:API I'm happy help to get the generators running (and deprecate our current non-standard code base).

**Comment by philsturgeon** [comment]
Hey there! I was waiting for [this article](https://blog.apisyouwonthate.com/common-hypermedia-patterns-with-json-hyper-schema-17c78cf884ff) to help us all get on the same page about JSON Schema, and how it might fit in with JSON:API. It's important to have an idea of where JSON Hyper-Schema would fit in with as there is definite crossover.

Using JSON:API links as a switch and the most basic level of hypermedia controls, then having JSON Hyper-Schema there to supply considerably more metadata on top (such as submissionSchemas so you know what to put in the payload programatically) makes this a really powerful combination. Imagine it as Siren actions, but taken out of the payload and put into metadata. 

Now @remmeier, don't get me wrong, I love code generation (using it heavily for SDKs and moving into server generation too). JSON Schema getting code/UI generation vocabularies further down the line will make it an even more useful and flexible tool, but that is feature discussion for JSON Schema. Basically, it's coming, and discussing how it should work would be a job done best on the [JSON Schema slack](https://join.slack.com/t/json-schema/shared_invite/enQtMjk1NDcyNDI2NTAwLTcyYmYwMjdmMmUxNzZjYzIxNGU2YjdkNzdlOGZiNjIwNDI2M2Y3NmRkYjA4YmMwODMwYjgyOTFlNWZjZjAyNjg) or on the JSON Schema GitHub perhaps. 

I think there is a lot of power in JSON Schema in the Core, Validation and HyperSchema vocabularies at this point, as they cover a lot of the requirements, would essentially give the same base functionality as GraphQL Types, and add a lot more too. 

As you say, if we can get some consensus on JSON Schema as an approach, we can start to look as specifics like how to integrate what and where, how to word recommendations, etc. I'd be happy to draft up that proposal, as WeWork is now using both JSON:API and JSON Schema. 😎

**Comment by jugaadi** [comment]
Any updates on this issue?

**Comment by philsturgeon** [comment]
Not yet, but @dgeb and I will be chatting about this when he's back from vacation.

**Comment by remmeier** [comment]
if there is any help required, you can let me know. in Crnk we started generating Asciidoc document from the underlying schema and test cases (http://www.crnk.io/releases/v3.0/ and http://www.crnk.io/releases/v3.0/documentation/#_documentation_with_asciidoc). So be nice to see if functionality like this is not limited to Crnk but works with any kind of JSON:API schema/model.

**Comment by jbmolle** [comment]
Hi,
Any update on this issue?
I've seen that Json Schema Draft 08 milestone is done, am I right?

**Comment by philsturgeon** [comment]
Hey @jbmolle, draft 08 (will actually be called something else because folks had opinions about the versioning scheme) is in review so its a few weeks from being released. 

I had some great chats with @dgeb and @gabesullice about this, and we bounced around some potentially solutions. 

The last I heard about it was May 28th. 

> we should discuss more in discord, but we really need to sort out the 1.1 release and provide a target for 1.2 PRs like this

@dgeb @gabesullice how did that discord conversation go? 

I am avoiding pasting in any of the solutions we suggested because there were a few different ones and I don't wanna bias the discussion. @gabesullice perhaps you could provide whichever one you settled on?

**Comment by jugaadi** [comment]
Any updates on this issue?

**Comment by philsturgeon** [comment]
It's entirely in the hands of the JSON:API folks now, but I've bumped them for updates!

**Comment by gabesullice** [comment]
Hi all!

Thanks for your continued interest/enthusiasm for this! I'm just as excited about schema support as you all :D I think it'll open up a whole new world for JSON:API and reinvigorate the community.

That's why @dgeb and I have been working together at a fast pace to get JSON:API v1.1 sorted out. Lots of detail can be found in @dgeb's update here: https://github.com/json-api/json-api/issues/1403#issuecomment-518263298

To sum that up, finalizing 1.1 is our highest priority. We're working very hard to get that finished ASAP. Once that's done, I plan to focus on schema support and finally land it as either a profile enabled by 1.1 or as part of the base spec.

---

In an entirely experimental project, I've already been experimenting with how JSON-Schema and JSON:API can be married to support new tooling for JSON:API. If you'd like to satisfy your curiosity, you can check that out here: https://explore.jsonapi.dev. Nothing about it should be considered official or stable ;)

**Comment by wimleers** [comment]
https://explore.jsonapi.dev/ is so cool! 🤩

**Comment by jugaadi** [comment]
Latest updates:
1. [JSON Schema released v2019-09](http://json-schema.org/specification.html) i.e draft-08
2. [OpenAPI and JSON Schema incompatibility issues are being ironed out](https://github.com/OAI/OpenAPI-Specification/pull/1977)

Thanks @handrews  and @philsturgeon  for the incredible work.

**Comment by jugaadi** [comment]
Initial thoughts on using OpenAPI for defining JSON:API. Just like JSON:API is all about shared conventions, we can adopt certain conventions while describing our APIs.

1. Introduce a new [data type format](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#data-types): "jsonapi:id" to support json:api **id**. This can be used inside the schema objects to refer an ID.
2. The schema object associated with the response must be a [reference object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#referenceObject).
3. We can reuse [Link maps](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#response-object) to define 
    1. Links:
        1. Key = self, related or pagination links.
        2. Value = [Link Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#link-object). The operationID can point to the relevant [operation object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#operationObject).
     2. Relationships.
        1. Key = relationship field name.
        2. Value = relationship link in the form of a [Link Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#link-object). The operationID can point to the relevant [operation object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#operationObject). 
        3. The above *relationship link* operation object must have the tags:"jsonapi:relationship" and must also specify the related resource link in its links object.

Based on the above assumptions, we can create JSON:API by computing the following:

1. Each response contains a schema reference object associated with [content](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#mediaTypeObject) key = "application/vnd.api+json". This represents a JSON:API resource where its name represents the **type**.
2. Any property within the above resource which has type= "string" and format = "jsonapi:id" represents the **id**.
3. Intersection of Link Map keysets and Properties keysets represents the **relationships**.
4. Rest of the properties are **attributes**.

PS: 
1. Meta has not been considered.
2. This can be vastly improved with the help of our community. We can even consider extending the specification with our own keywords.

**Comment by dgeb** [comment]
#1447 is a minimalist PR that opens the door for compatibility with description documents via the `describedby` link relation.

**Comment by bradjones1** [comment]
#1447 was merged in January 2020. https://github.com/json-api/json-api/pull/1447#event-2931746260

**Comment by dgeb** [comment]
> #1447 was merged in January 2020

@bradjones1 right, thanks for the reminder. It's time to allow more fine-grained discussion (if needed) in separate issues at this point.
