### ISSUE TITLE
Brackets in requests for filter parameters

### ISSUE THREAD

**Issue by remmeier** [json-api/json-api#1282]
There is currently an issue with Apache Tomcat not allowing [ and ] anymore without beeing properly escaped:

https://bz.apache.org/bugzilla/show_bug.cgi?id=62273

based on RFC that browser vendors do not seem to follow. Is there something to do in the JSON API area? like moving away from brackets? since escaping those would be a bit cumbersome to use when directly typing urls into a browser.

**Comment by ethanresnick** [comment]
I don't think there's anything we can do anything about the use of `[` and `]` in the `?fields` parameter, as that wouldn't be backwards compatible. In theory we could introduce an alternate syntax, but that might be tricky too — as you note, there are competing standards for URL escaping rules (RFC 3986 and the WHATWG Url standard), and the whole thing is a bit of a minefield. 

In the meantime, it looks like maybe this has been fixed on the Tomcat side?

**Comment by ethanresnick** [comment]
I've opened #1302 as a place to discuss this further/beyond the apache tomcat context.
