### ISSUE TITLE
How to present empty relationship?

### ISSUE THREAD

**Issue by coolbeet** [json-api/json-api#1284]
```
{
  "type": "articles",
  "id": "1",
  "attributes": {
    "title": "Rails is Omakase"
  },
  "relationships": {
    "comments": {
        "data": []
      }
  }
}
```
This `article` doesn't have `comments`, what is the correct way to present a empty relationship?

`"data": []` or `"data": null` or no `"relationships"` at all?

Thanks!

**Comment by rpkilby** [comment]
Per the [relationships](http://jsonapi.org/format/#document-resource-object-relationships) section, a relationship's `data` must be represented by [resource linkage](http://jsonapi.org/format/#document-resource-object-linkage). For empty to-many relationships, resource linkage should be an empty array.

Hope that helps.

Edit: Note that a relationship object doesn't necessarily need `data`. It just needs to contain at least one of the `links`, `data`, or `meta` objects.

**Comment by coolbeet** [comment]
@rpkilby Make sense, thanks a lot!
