### ISSUE TITLE
Problem patching polymorphic linked relationships

### ISSUE THREAD

**Issue by andrewsardone** [json-api/json-api#129]
Using [Active Record's polymorphic association](http://guides.rubyonrails.org/association_basics.html#polymorphic-associations) example, let's say your app has the following model relationships:

``` ruby
class Picture < ActiveRecord::Base
  belongs_to :imageable, polymorphic: true
end

class Employee < ActiveRecord::Base
  has_many :pictures, as: :imageable
end

class Product < ActiveRecord::Base
  has_many :pictures, as: :imageable
end
```

A `GET` request to `/employees/1` might return:

``` json
{
  "links": {
    "employees.pictures": "http://api.example.com/pictures/{employees.pictures}"
  },
  "employees": [{
    "id": "1",
    "name": "Johnny Appleseed",
    "links": {
        "pictures": [ "3", "4" ]
    }
  }]
}
```

A `GET` request to one of the pictures (`/pictures/3`) might return:

``` json
{
  "links": {
    "pictures.imageable": "http://api.example.com/imageable/{pictures.imageable}"
  }, 
  "pictures": [{
      "id": "3", 
      "name": "Johnny Appleseed.jpg",
      "links": {
        "imageable": "1"
      }
  }]
}
```

The **problem** here is that the `"imageable"` **link's ID is ambiguous** – we don't know if it's linking to an employee or product resource.

Now, if we're just going to retrieve the `"imageable"` relationship, we don't _really_ need to know whether it's an employee or product. If we really did care, our link could be more specific:

``` json
{
  "links": {
    "pictures.imageable": "http://api.example.com/employees/{pictures.imageable}"
  }
}
```

The real problem arises when trying to update the picture's `"imageable"` link.

A `PATCH` request to change the picture's `"imageable"` link is impossible with just the ID:

```
PATCH /pictures/3

[
  { "op": "replace", "path": "/pictures/0/links/imageable", "value": "28" }
]
```

We don't know what type the `"28"` ID belongs to, that is, is it an employee or a product? Right now, document IDs are not globally unique, but [scoped to the document's type](https://github.com/json-api/json-api/blob/9453e1045d96eb94d0f4f52916f6d3c166ba71a3/format/index.md#ids-1). 

How can we describe polymorphic link relationships? It doesn't look like relying solely on IDs is sufficient – we're missing any notion of the resource's type. Using GUIDs is one option (at leat a poor man's GUID of `:id-:type`), but this would require larger changes for implementers' backend.

**Comment by steveklabnik** [comment]
It seems like this is a problem with the ID style but not the hypermedia style; the URL _is_ a GUID.

**Comment by andrewsardone** [comment]
I think there are some problems with the hypermedia style, too. The above examples use full URL links – they just fallback to the array-of-IDs to help segment the example.

For the polymorphic to-one relationship, is the suggestion that the picture document should look like:

``` json
{
  "pictures": [{
      "id": "3", 
      "name": "Johnny Appleseed.jpg",
      "links": {
        "imageable": "http://api.example.com/employees/1"
      }
  }]
}
```

…and updating the picture's `"imageable"` should replace the entire URL?

```
PATCH /pictures/3

[
  { "op": "replace", "path": "/pictures/0/links/imageable", "value": "http://api.example.com/products/28" }
]
```

Let's say an employee has a to-many relationship of `"images"` that's a collection of photograph and painting resources:

``` json
{
  "employees": [{
    "id": "1",
    "name": "Johnny Appleseed",
    "links": {
        "images": "https://api.example.com/images/1,4,7,8"
    }
  }]
}
```

Those comma separated IDs could clash – their uniqueness only applies within their specific type (photographs and paintings).

Even if we use a more abstract URL, it's unclear to me how we'd add & remove resources from the `"images"` relationship:

``` json
{
  "employees": [{
    "id": "1",
    "name": "Johnny Appleseed",
    "links": {
        "images": "https://api.example.com/employees/1/images"
    }
  }]
}
```

What sort of `PATCH` requests with `application/json-patch+json` bodies could manipulate `/employees/0/images`? Are we limited to `PUT` requests to `https://api.example.com/employees/1/images`? What about deletion?

**Comment by rkh** [comment]
Assuming #164, you could simply add a type attribute to the link.

**Comment by steveklabnik** [comment]
This issue is no longer relevant with the current version of the spec.
