### ISSUE TITLE
Unclear wording in pagination of relationships

### ISSUE THREAD

**Issue by jamesarosen** [json-api/json-api#1291]
Under [Relationships](http://jsonapi.org/format/#document-resource-object-relationships), the spec says,

> Any pagination links in a relationship object MUST paginate the relationship data, not the related resources.

But the spec doesn't make clear the distinction between a page of "relationship data" and a page of "related resources."

One possible interpretation is that the "second page" should be a link to the same primary document, but with a different `relationships` collection. But it seems wasteful to reload and reserialize the primary document for each page.

**Comment by ethanresnick** [comment]
This has [come up before](https://github.com/json-api/json-api/issues/509#issuecomment-86795865), but the spec's wording is a still confusing/in need of examples.

Basically, "relationship data" is referring to the resource identifier objects in the relationship's `data` key, whereas "related resources" refers to the set of resources that those identifier objects pick out.

A set of resource identifier objects is returned from a "relationship endpoint", like `GET /articles/1/relationships/comments`. The idea is simply that you can paginate the data that would be returned at that endpoint, like `GET /articles/1/relationships/comments?page[offset]=40`.

Then, in the relationship object of article 1, you use that pagination link, like so:

```
GET /articles/1

{
  "data": {
    "type": "articles",
    "id": "1",
    "attributes": { /* ... */ },
    "relationships": { 
       "comments": { 
          "links": { "next": "/articles/1/relationships/comments?page[offset]=40" },
          "data": [/* first 40 resource identifier objects */]
       }
    }
  }
}
```
