### ISSUE TITLE
Are relationships with only data valid?

### ISSUE THREAD

**Issue by jamesarosen** [json-api/json-api#1292]
The [ember-cli-mirage 0.4 upgrade guide](http://www.ember-cli-mirage.com/docs/v0.4.x/upgrading/#03x--04-upgrade-guide) says this:

> In 0.3.x, Mirage’s JSONAPISerializer included all related foreign keys whenever serializing a model or collection, even if those relationships were not being included in the payload. This actually goes against JSON:API’s design. Foreign keys in the payload are known as Resource Linkage and are intended to be used by API clients to link together all resources in a JSON:API compound document.

The [Relationships](http://jsonapi.org/format/#document-resource-object-relationships) section of the `{json:api}` spec says,

> A “relationship object” MUST contain at least one of the following: [links, data, meta]

where `data` is a [Resource Linkage](http://jsonapi.org/format/#document-resource-object-linkage). That section states,

> Resource linkage in a compound document allows a client to link together all of the included resource objects without having to GET any URLs via links.

So it seems like the _intent_ of a linkage is a performance optimization to prevent extra GETs.

But the only normative content in the Resource Linkage section is

> Resource linkage MUST be represented as one of the following:
> null for empty to-one relationships.
> an empty array ([]) for empty to-many relationships.
> a single resource identifier object for non-empty to-one relationships
> an array of resource identifier objects for non-empty to-many relationships.

And the [Resource Identifier Objects](http://jsonapi.org/format/#document-resource-identifier-objects) section only says,

> A “resource identifier object” MUST contain type and id members.

So the spec seems to allow
```json
{
  "data": {
    "type": "blog",
    "id": "b12345",
    "relationships": {
      "author": {
        "data": { "type": "person", "id": "p67890" }
      }
    }
  }
}
```

There is, of course, a philosophical argument against this practice: the document is no longer hypermedia. The document neither provides the full details for `{ "type": "person", "id": "person67890" }`, nor tells the client how to get them. The client would have to be programmed to know that the URL for that is, e.g. `/people/p67890`.

**Comment by ethanresnick** [comment]
You're correct both that the spec allows this and that it requires clients to know how to construct the relevant urls if they want the full resources. If a server wants to support hypermedia, it can and should include the links

**Comment by samselikoff** [comment]
Thanks @ethanresnick.

@jamesarosen I wrote a blog post after some discussions with @dgeb about all this here: http://www.ember-cli-mirage.com/blog/2018/02/01/changing-mirages-default-linkage-data-behavior/. I believe Ethan is correct.
