### ISSUE TITLE
Profile Registration

### ISSUE THREAD

**Issue by gabesullice** [json-api/json-api#1295]
First, congratulations @ethanresnick and @dgeb for merging #1268! 🎉

I'm incredibly excited for v1.1 to be released and to (hopefully) be one of the first adopters :)

I see that the registration concept was removed from #1195. Are there plans to reincorporate that?

Should we proceed on the assumption that our profile URIs will typically have our own domain or the jsonapi.org domain?

Personally, I'd love to contribute the profiles we generate back the JSON API community. I think a profile registered with a jsonapi.org domain would make them more discoverable.

To give a few concrete examples of the profiles I'd like to register:

- a filtering syntax
- a pagination syntax
- handling CRUD on relationships that can target a resource object more than once
- handling access restrictions on individual resource objects in a collection
- a way to represent RFC8288 link objects (with `rel` and other link-params under the `meta` key)
- a home document format and standard API entry point
- a JSON API compliant implementation of resource versioning using [RFC5829](https://tools.ietf.org/html/rfc5829)

**Comment by ethanresnick** [comment]
Thanks @gabesullice! 

And yes, I would very much like to bring back the concept of optional-but-strongly-encouraged registration that was in #1195/#1196. If @dgeb doesn't have any objections to that, I'll update #1196 to bring that stuff back (including the registration template).

**Comment by ethanresnick** [comment]
@gabesullice See #1311! 🎉

**Comment by gabesullice** [comment]
🎊🎊🎊🎊🎊🎊

Thanks for the mention @ethanresnick!
