### ISSUE TITLE
Clarify encoding of square brackets in query param names

### ISSUE THREAD

**Issue by ethanresnick** [json-api/json-api#1302]
JSON:API requires the use of square brackets in `?fields[TYPE]` query parameter names. But we don't say in any normative text whether these square bracket should be percent-encoded. 

We strongly imply that they should be, though, through non-normative notes like:

> Note: The above example URI shows unencoded `[` and `]` characters simply for readability. In practice, these characters must be percent-encoded, per the requirements in RFC 3986.

The idea implicit in these notes seems to be that "the syntax for URLs is defined by RFC 3986 so, if that RFC requires encoding, then of course these characters must be encoded".

The issue, which I didn't realize at the time, is that there are actually two competing standards around the format of URLs; the other is the WHATWG Url spec, which browsers follow.

Per the WHATWG Url spec, browsers do _not_ percent-encode `[` and `]` in query strings by default.

Therefore, in an ideal world, I think we'd define field parameter names with encoded square brackets (i.e., `fields%5BTYPE%5D`) and those with un-encoded square brackets as equivalent aliases for one another, and would require servers to support both.

In practice, I'm pretty sure we can — and, for clarity, I think we should — turn our current notes into a *normative MUST* requiring that servers support the percent-encoded form. Since HTTP's specification incorporates RFC 3986 as its normative definition of a URL, and we've always said that JSON:API should be read to comply with HTTP, and because we have the existing notes we do referencing RFC 3986, I don't think this MUST would be a breaking change.

Further, I think we should add a **SHOULD** that servers support the unencoded versions — since this is what browsers will send by default — and that these unencoded parameter names should be treated as identical to the percent-encoded variants.

**Comment by dgeb** [comment]
@ethanresnick I agree with this analysis. The spec could use the clarifying statements you suggest 👍

**Comment by ethanresnick** [comment]
Closed by #1308
