### ISSUE TITLE
Using "application" vs "client"

### ISSUE THREAD

**Issue by kocsismate** [json-api/json-api#1317]
Hi,

When reading the Profiles section in the new docs (specifically the https://jsonapi.org/format/upcoming/#profiles-processing subsection), I spotted that "application" is consistently written instead of "client". For example:
> Each profile MAY define its own rules for how applications should proceed when encountering unrecognized values.

Wouldn't using "client" make more sense? Or did you want to emphasize that the subsection applies to clients which process the documents automatically?

**Comment by ethanresnick** [comment]
The idea is to emphasize that it may be the server, not the client, that's encountering the profile. E.g. if the client submits a profiled document in a `PATCH`, the server is the recipient.

**Comment by ethanresnick** [comment]
Also, just as a heads up, note that the rules in that section are likely to be revised slightly by #1306

**Comment by kocsismate** [comment]
First, thanks for the notification :)

Ah, I see your point. I didn't imagine before that profiles can be used for CRUD actions. :O But probably I just missed some details in the docs.

And I have a bonus question: do you want to add any new features into the 1.1 version besides @ fields and profiles? I am asking this because I am working on the JSON:API 1.1 support in my client and server implementations, so I am curious about the timeframe when the new version is finalized.

**Comment by kocsismate** [comment]
PS: Another thing that I've just noticed in the "Profiles" section: "JSON:API" is used in more places instead of "JSON API". Will you change the other occurences too to the new format? I like it much more :)

**Comment by ethanresnick** [comment]
>  do you want to add any new features into the 1.1 version besides @ fields and profiles? 

No, those will be the only new features, and the goal is to release soon, once implementers have had time to test. Definitely before the end of the year.

> PS: Another thing that I've just noticed in the "Profiles" section: "JSON:API" is used in more places instead of "JSON API". Will you change the other occurences too to the new format? I like it much more :)

I think JSON:API is what we settled on, right @dgeb? If so, we'd gladly accept a PR that changed it across the board.

**Comment by kocsismate** [comment]
Yes, this is what I also remember. I'll try to come up with a PR in the following days :)
