### ISSUE TITLE
'Included' section array leads to less than ideal front-end handling

### ISSUE THREAD

**Issue by buckmaxwell** [json-api/json-api#1319]
I am wondering why the included section is an array of objects rather than an object with the keys being the type of object? It seems that if the included section was an object rather than an array, font-end handling would be much easier.

ie, rather than having to filter for an array to find an object with a certain type and id, you could just invoke included['SOME_TYPE']['some_id'].

What were the reasons behind this decision?

**Comment by buckmaxwell** [comment]
It seems a search through an array could be avoided by having the included section like so,
```js
"included" : {
 "MY_TYPE":{
   "MY_ID": {} // your object
 }
}
```
or
```js
"included" : {
 "MYTYPE_MYID":{} // your object
}
```

**Comment by kocsismate** [comment]
This idea has already been proposed/discussed multiple times, see one conversation at the following link: https://github.com/json-api/json-api/issues/1170 :)

> I'm sure I've explained this in the past, but am having trouble finding my explanation, so here it goes...

I believe @dgeb was searching for the following explanation in the quoted comment of him: https://discuss.jsonapi.org/t/why-is-included-an-array/76/3

**Comment by ethanresnick** [comment]
Closing in favor of #1170.

**Comment by buckmaxwell** [comment]
Thanks, was looking for this
