### ISSUE TITLE
Sort dot notation forces implementors to write two different patterns

### ISSUE THREAD

**Issue by krainboltgreene** [json-api/json-api#1322]
> Note: It is recommended that dot-separated (U+002E FULL-STOP, “.”) sort fields be used to request sorting based upon relationship attributes. For example, a sort field of author.name could be used to request that the primary data be sorted based upon the name attribute of the author relationship.

I suggest we just make this enforced, as it unnecessarily requires client/server implementors to write two pieces:

  - no dot notation
  - dot notation

Considering sparse fieldset is dictionary based and include is dot notation (effectively a dictionary), I see no compelling reason why sort shouldn't also follow this style.

**Comment by ethanresnick** [comment]
Changing the spec to require the behavior you're describing would be a breaking change, which we can't do at this point. Consider that many existing uses/implementations of the sort parameter don't just use comma-separated field names, e.g., [`?sort=distanceFrom(lat,lng)`](https://github.com/json-api/json-api/issues/1266).

All that said, this would be a *perfect* thing to write a [profile](https://jsonapi.org/format/upcoming/#profiles) for. If you do that, please let us know, and we'll find a way to get it included in the upcoming profile registry, even though the [registration process is still being discussed](https://github.com/json-api/json-api/pull/1311).

**Comment by krainboltgreene** [comment]
> Consider that many existing uses/implementations of the sort parameter don't just use comma-separated field names, e.g., ?sort=distanceFrom(lat,lng)

Holy crap, that makes this even more difficult.

> All that said, this would be a perfect thing to write a profile for.

So profiles are basically schema documentation for value types? I can get on board with that.

**Comment by ethanresnick** [comment]
> So profiles are basically schema documentation for value types? 

They can be that, but they can add additional semantics as well. Take a look at the example cursor pagination profile in #1311.

**Comment by ethanresnick** [comment]
Closing for now, as this seems to have been addressed.
