### ISSUE TITLE
Why the SQL anti-pattern?

### ISSUE THREAD

**Issue by FAQinghere** [json-api/json-api#134]
Just curious, but why use the id technique, which is SQL anti-pattern?

Obviously a child normally has a reference to its parent id if a database is normalized.

ex. 
We have a thousand posts with an average of 50 comments each. We fetch the thousand posts. Then we want to load one particular post with all details. That would be two SQL commands returning data directly without post-processing other than the JSON serialization.

Get the list of posts:
`SELECT * FROM posts;`

Get the details of a particular post:
 `SELECT * FROM comments WHERE post_id = 2;`

It's simple, efficient, and conventional.

But using this API, we would have to choose one of several ugly hacks.

We could run another SQL command per post before sending the initial list of posts:
`for (post in posts) { 
SELECT id FROM comments WHERE post_id = post.id;
}`
Ouch, that's no good. Alternatively we could fetch them in a batch, and then process them in memory to attach the comment ids to each post. That's no good. Or, we could duplicate the data, storing an array of ids on each post. Again, ugly.

Of course all of those actions would require at least one extra database hit (and that's assuming we're doing all the parsing in memory on the server, prior to serialization). 1. Get the posts, 2. Get the ids, 3. Get the comments for a particular post when requested. We could cut this down to two if we side load all of the comments from the start (again, fetching them in a batch and parsing them in memory). But that's clearly not scalable.

In reality, we could use SQL to fetch everything at once, but that takes some serious SQL acrobatics and, again, it's very inefficient.

So again, why force the anti-pattern? I have to be missing (probably obvious) something here. The only benefit I could see is being able to show the comment count on posts before fulling loading comments. But then, just storing a comment count on the post would be a vastly more efficient denormalization. What am I missing?

**Comment by steveklabnik** [comment]
Closing based on the fact that this isn't a bug. :)

Anyway, the ID style is a transitional path towards the URL style. It's in no way a requirement, it's an option. The goal is to ease people who haven't drank the proper kool-aid into it.

We can absolutely keep discussing this here if you'd like, I just like to keep issues open for bugs, not questions.

**Comment by beauby** [comment]
Not sure what the state of the spec was back when this was opened, but for future reference, version 1.0 of the spec allows for specifying only a `link` for a resource, thus avoiding the multiple queries to fetch the related ids in a `has_many` relationship.
