### ISSUE TITLE
Add an editor(s) section to the profile template

### ISSUE THREAD

**Issue by gabesullice** [json-api/json-api#1346]
I just submitted a profile for registration and this came up:

I was able to choose `drupal` as the namespace of the profile in order to not portray myself as the sole creator of the profile, but the `author_name` and `author_email` items defeat that distinction. I did technically _author_ it, but the ideas all came from a collaborative effort.

I think a good solution would be to substitute an "Editor(s)" section for the author section.

This would also mean that more than one person could be responsible for making changes, which would be a nice relief for authors and could increase the velocity of corrections/additions.

**Comment by ethanresnick** [comment]
This sounds good to me. Can you make a PR?

**Comment by ethanresnick** [comment]
Addressed by #1349
