### ISSUE TITLE
First sentence of index.md is confusing

### ISSUE THREAD

**Issue by whatcould** [json-api/json-api#135]
I was confused trying to read the first sentence of `index.md`. I'd submit a pull request if I understood what it was trying to say; maybe I can just explain the problem in grammatical terms.

The first sentence lacks an object:

> "JSON API" is a JSON-based read/write hypermedia-type designed to support a smart client who wishes to build a data-store of information.

"JSON API" is a hypermedia-type ____. A hypermedia-type _what_? A hypermedia-type API? I'm not sure what that means, but at least it makes grammatical sense. Or, is it a hypermedia **type** (no hyphen), 'type' being the subject?

It also uses "who" instead of "what" when describing a non-human thing; using "who" for the client is a little confusing when the "client" you're talking about is generally a client-side web application, the pronoun for which should be "that". But then it's also a little weird that your rich client is _wishing_ to do something. And now that I look at it, "data-store of information" seems redundant, or vague. Isn't every data store a data store of information?

Anyway, if I understood what you were trying to say, I'd try to rewrite it, but I'm not sure I understand what the spec is about.

**Comment by brixen** [comment]
@whatcould I believe "hypermedia-type" in the sentence you refer to means this:

> "Hypermedia Types are MIME media types that contain native hyper-linking semantics that induce application flow. For example, HTML is a hypermedia type; XML is not."

-- Mike Amundsen (2010)

From http://amundsen.com/hypermedia/

**Comment by whatcould** [comment]
Ah. So the object is "type", ok. I see Amunsen is using, inconsistently, 'media-type' and at times 'media type'. The hyphenated version seems wrong grammatically, and is not used elsewhere on the internet (eg http://www.iana.org/assignments/media-types). If anything it's a hypermedia-media type!

**Comment by steveklabnik** [comment]
Yes, it really should be a 'hypermedia media type.'

**Comment by whatcould** [comment]
That's great, the sentence reads more clearly now.

I still don't really understand what a hypermedia media type is, so as a developer I'm not sure why I care about it. But maybe, since it's a page for the spec, it's ok that it's written for spec-readers. The intro on the Github README ("**a standard for APIs that use JSON**") actually explains what it is in lay-developer language.
