### ISSUE TITLE
Profiles: Consider allowing servers to opt-out of recognizing aliases

### ISSUE THREAD

**Issue by dgeb** [json-api/json-api#1362]
In order to allow incremental adoption of profiles in v1.1, I'd like to consider allowing servers to signal that they do not support certain features, while still specifying that they SHOULD support them. For instance, it seems reasonable to me that a server could respond with a 422 error if a document is sent that includes aliases for keywords in a profile. We could create an official URL for this error so that it would be easily distinguished from other 422 errors.

I wanted to raise this as an issue for discussion prior to opening a PR.

**Comment by wimleers** [comment]
I don't think I fully understand what you're referring to.

Are you referring to the case  where the server supports the profile that the aliased keyword is for, but the server does not support resolving aliases?

**Comment by dgeb** [comment]
> Are you referring to the case where the server supports the profile that the aliased keyword is for, but the server does not support resolving aliases?

Yes. 

My thinking is that the primary use case for aliases is to avoid conflicts between semantically conflicting, yet functionally compatible, profiles. More often than not, servers will support only non-conflicting profiles that do not require aliases. For these servers, there's little benefit to supporting some random and unnecessary alias sent by the client.

While it may be ideal if servers can always support aliases and be maximally forgiving, I think it's unlikely to be the reality. It seems realistic to give servers a way to avoid extra processing and clearly communicate to the client why they don't allow it.

**Comment by gabesullice** [comment]
+1, aliases are the most demanding requirement of v1.1 (re: implementation complexity)

**Comment by gabesullice** [comment]
Superseded by #1412
