### ISSUE TITLE
Convert to C# class

### ISSUE THREAD

**Issue by stesvis** [json-api/json-api#1363]
Is there any way to convert a json:api string to a c# class?
With "regular" json, we can use a convert tool like this: http://json2csharp.com/

But that is not really helpful with json:api...

Any help?

**Comment by wimleers** [comment]
See 
https://jsonapi.org/implementations/, which lists 
https://github.com/l8nite/JsonApiNet.

**Comment by stesvis** [comment]
Thanks.
You still have to define the destination C# class first tho?

I was wondering if there was any tool that takes the json:api string and creates the class structure for you.

**Comment by michaelsw95** [comment]
This is a requirement I had also. This can be done in C# using a [dynamic](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/types/using-type-dynamic) class. Using [newtonsoft](https://www.newtonsoft.com/json) you can deserialize into a dynamic like this:

```csharp
dynamic person = JsonConvert.DeserializeObject("{ 'Name': 'John Doe', 'Age': 22 }");
```

You can then access the  `person` object to get its values:

```csharp
string name = person.Name;
int age = person.Age;
```

**Comment by remmeier** [comment]
in general for such things it would be great to have https://github.com/json-api/json-api/issues/1281. This so there is a common denominator across all JSON:API implementations that then allow to do things like the code generatio mentioned here without being looked into one particular implementation.

**Comment by jelhan** [comment]
I think the specification repository itself is the wrong place for these kind of questions. The [JSON:API discussion forum](http://discuss.jsonapi.org/) or the [json-api tag on StackOverflow](https://stackoverflow.com/tags/json-api/info) are better fits in my perspective.

The question seems to be resolved also with @MichaelHancock's comment.

I'm going to close this issue. Please speak up if I missed something important.
