### ISSUE TITLE
A missing `people:2` on the example on the main page?

### ISSUE THREAD

**Issue by zerkms** [json-api/json-api#1366]
The example on the main page at https://jsonapi.org/ is missing the entity `people` `id=2`.

Is it deliberate or a genuine issue?

**Comment by gabesullice** [comment]
I think it's deliberate. JSON:API does not require that anything be included unless an `include` parameter is present. Looking at the `self` link, there are none. So, it seems only the "first level" is included by default.

Way to keep JSON:API honest!
