### ISSUE TITLE
Plurality of compound documents

### ISSUE THREAD

**Issue by farski** [json-api/json-api#137]
In the Compound Documents section of ID-Based JSON API, the example shows a set of posts that references a single author, which is compounded as `people` (plural).

Under URL-Based JSON API, again the example shows a set of posts that references a single author, but the compound document is under the `author` key. This seems to be the only example I can find of a key being singular. I get that the link has a definition for `posts.author`, which is correct and makes sense, but I'm unclear why in the document the key is also singular, especially since, as far as I can tell, it could contain multiple authors. Would the key change in that case?

**Comment by steveklabnik** [comment]
We've unified the two styles now, so there should be no inconsistency.
