### ISSUE TITLE
Unclear `Accept` header client documentation

### ISSUE THREAD

**Issue by TrevorHinesley** [json-api/json-api#1382]
I might be nitpicking here, but the wording seems intentional so I think it's worth a discussion for clarification. In [this section](https://jsonapi.org/format/#content-negotiation-clients), the language in the second sentence is as follows:

```
Clients that include the JSON:API media type in their Accept header MUST specify the media
type there at least once without any media type parameters.
```

The `at least once` piece is a bit confusing to me.

Does this mean:

1. The client is allowed to specify the JSON:API media type more than once in their Accept header, but *at least* one instance of the media type must be without media type parameters (meaning one or more other instances *can* have media type parameters)?

OR

2. The client is allowed to specify the JSON:API media type more than once in their Accept header, but *all* instances of the media type must be without media type parameters?

**Comment by gabesullice** [comment]
@TrevorHinesley, I'm fairly certain that it's #1. Would you mind submitting a PR to that effect?

My reasoning is that we need to be able to support profile negotiation in version 1.1, which require the use of media type parameters.

**Comment by TrevorHinesley** [comment]
@gabesullice done! Let me know if the wording is sufficient or still lacks clarity.

**Comment by Dormilich** [comment]
Is the quality parameter `q` in an Accept header considered a disallowed parameter?

E.g. If I specify different profiles/extensions (version 1.1), then none of that would be used as the preferred MIME type (with the maximum importance) has no parameters.

**Comment by freddrake** [comment]
The `q` parameter in an Accept header should not be considered part of the media type, though it is encoded as if it were.

**Comment by freddrake** [comment]
@gabesullice: I believe all the questions posed here have been answered, but specification 1.1 has moved on and includes a detailed discussion of the interpretation of media type parameters in the **Accept** header.

This issue seems outdated, and should be closed.

**Comment by gabesullice** [comment]
Thanks for the ping @freddrake! Agreed that this issue is out of date.
