### ISSUE TITLE
How to parse this kind of JSON Request.?

### ISSUE THREAD

**Issue by udhaya28** [json-api/json-api#1386]
Hi  I have json format like this. How can split this header using Jackson api.

-H "content-type: application/vnd.api+json"
-H "X-Transaction-MsgId: 8723423ed-0d21-2df-csfwe-asfsdf3345"
-H "X-Transaction-DataId: asds323-c7ca-23423-asdfsa3-sfsdf5sd323"
-H "X-Transaction-DateTimeCreated: 24-04-2019"
{  
   "company":{  
      "data":[  
         { 
..............
         }
}

**Comment by gabesullice** [comment]
I think you've posted this to the wrong issue queue.
