### ISSUE TITLE
Ambiguous use of MAY when describing resource objects

### ISSUE THREAD

**Issue by Herriau** [json-api/json-api#1388]
The 1.0 spec states:

> In addition, a resource object MAY contain any of these top-level members:
>
> - `attributes`: an [attributes object](https://jsonapi.org/format/#document-resource-object-attributes) representing some of the resource’s data.
> - `relationships`: a [relationships object](https://jsonapi.org/format/#document-resource-object-relationships) describing relationships between the resource and other JSON:API resources.
> - `links`: a [links object](https://jsonapi.org/format/#document-links) containing links related to the resource.
> - `meta`: a [meta object](https://jsonapi.org/format/#document-meta) containing non-standard meta-information about a resource that can not be represented as an attribute or relationship.

In regards to `relationships` (resp. `attributes`), it's not clear whether a given resource object MAY or MAY NOT contain these members because:
- Its resource type is such that it doesn't have relationships (resp. attributes).
- Its resource type has relationships (resp. attributes) but the server may decide to omit sending a [relationships object](https://jsonapi.org/format/#document-resource-object-relationships) (resp. [attributes object](https://jsonapi.org/format/#document-resource-object-attributes)) altogether for whatever reason.

I was under the impression that if a given resource type has one or more relationship(s) (resp. attribute(s)) then a [resource object](https://jsonapi.org/format/#document-resource-objects) for a resource of that type MUST contain a [relationships object](https://jsonapi.org/format/#document-resource-object-relationships) (resp. [attributes object](https://jsonapi.org/format/#document-resource-object-attributes)), and said relationship(s) (resp. attribute(s)) MUST be represented within the [relationships object](https://jsonapi.org/format/#document-resource-object-relationships) (resp. [attributes object](https://jsonapi.org/format/#document-resource-object-attributes)) — in the particular case of relationships either in the form of a [links object](https://jsonapi.org/format/#document-links) or [resource linkage](https://jsonapi.org/format/#document-resource-object-linkage) or possibly a [meta object](https://jsonapi.org/format/#document-meta) — and said relationship(s) (resp. attribute(s)) certainly MUST NOT be omitted from the response, unless the request explicitly asks for a sparse fieldset that does not contain said relationship(s) (resp. attribute(s)).

I looked everywhere throughout the spec to validate whether my assumptions were correct, but nowhere did I found a compelling answer to my question. I think this needs to be explicitly called out as the ambiguity has apparently led some people to believe (and perhaps rightfully so?) that attributes and relationships can be freely omitted from [resource objects](https://jsonapi.org/format/#document-resource-objects) for whatever reason regardless of whether the request supplied a sparse fieldset.

**Comment by gabesullice** [comment]
@Herriau, I'm having a hard time parsing your post. but I'll try to provide some clarity regardless, but I may be missing the mark.

I think your impression is incorrect. It _is_ acceptable for a server to omit fields even when no sparse fieldset is requested. It's not a common practice, but it's a valid one. This can be used to omit fields that might be uncommonly used, but expensive to compute. In that way, those expensive fields would only need to be computed if they're explicitly requested via a sparse fieldset.

IOW, at the extreme, _sparse_ fieldset is a bit of a misnomer. It's valid for a JSON:API server to return _no_ fields by default and require that _every_ field be explicitly requested (à la GraphQL) to prevent overfetching.

**Comment by Herriau** [comment]
@gabesullice If the spec is that loose and the server isn't required to return all relationships then it sounds like a client can't reliably discover how resources are linked together purely from looking at a JSONAPI document. 

> This can be used to omit fields that might be uncommonly used, but expensive to compute

I would think that a relationship that's uncommonly used and expensive to compute would still be represented within the [relationships object](https://jsonapi.org/format/#document-resource-object-relationships) at the very least in the form of a [links object](https://jsonapi.org/format/#document-links).

**Comment by jelhan** [comment]
> If the spec is that loose and the server isn't required to return all relationships then it sounds like a client can't reliably discover how resources are linked together purely from looking at a JSONAPI document.

I think such a discovery is out of scope for the specification.

It may be guaranteed by an implementation through responding with all existing fields by default - or through an Open API document. A discovery mechanism may be even added at spec level using an extension. But it isn't something base spec provides out of the box.

> I would think that a relationship that's uncommonly used and expensive to compute would still be represented within the [relationships object](https://jsonapi.org/format/#document-resource-object-relationships) at the very least in the form of a [links object](https://jsonapi.org/format/#document-links).

Yes. That would be my recommendation as well. But it does not solve the problem for attributes, which are uncommonly used and expensive to calculate.

**Comment by jelhan** [comment]
I think the original question has been resolved. By reading through through the issue again, I noticed that the specification also address that topic explicitly in the [sparse fieldsets](https://jsonapi.org/format/#fetching-sparse-fieldsets) section:

> If a client does not specify the set of [fields](https://jsonapi.org/format/#document-resource-object-fields) for a given resource type, the server MAY send all fields, a subset of fields, or no fields for that resource type.
