### ISSUE TITLE
Remove the `profile` query parameter

### ISSUE THREAD

**Issue by gabesullice** [json-api/json-api#1391]
I'm sitting down to get a general overview of how I can approach an implementation of JSON:API v1.1. There are a few things that have already stood out to me as burdensome or superfluous. One of them is the `profile` query parameter.

The `profile` query parameter seems to exist solely as a means for a client to force a server to either honor a profile or reject the request. This seems like a necessary feature, but I'm not sure it really needs to be implemented via a query parameter.

The need for this mechanism appears to be driven by two other requirements in the spec:

1. A client has a responsibility to send the JSON:API media type without any parameters at least once
2. A client is only allowed to use the `Accept` header to _request_ not _require_ a profile to be applied

The second requirement feels like it only exists because for the first.

It's unclear to me why the first requirement can't be removed in version 1.1 so as to allow a client to require a profile via the `Accept` header.

I suppose that the downside of this approach would be that the `Accept` header may grow enormously in size if there are quite a few optional profiles.

Is there some compromise that can be reached here that would allow a server implementation to _only_ inspect the header and not have to inspect the header _and_ the query string?

Am I missing a key use case for the `profile` query parameter or an unfixable problem with using the `Accept` header to require a profile?

cc: @ethanresnick

**Comment by gabesullice** [comment]
> Is there some compromise that can be reached here that would allow a server implementation to only inspect the header and not have to inspect the header and the query string?

I'm thinking that perhaps a `+ (PLUS SIGN)` could be prepended to the profile URI in the profile media type parameter to make it a required profile.

**Comment by jelhan** [comment]
I think the `profile` query parameter has been removed in latest v1.1 release candidate in favor of `Accept` header as proposed by you:

> A client MAY use the profile media type parameter in an Accept header to request that the server apply one or more profiles to the response document.

I quickly scanned through the document to verify that a `profile` query parameter is not mentioned anywhere anymore. All seems good.

I think this issue could be closed.
