### ISSUE TITLE
An addition to the curated list on your website

### ISSUE THREAD

**Issue by thogerb** [json-api/json-api#1399]
Hi, great project! 

Not sure where to contribute this, so I am choosing the easy route here: Thought you might want to include this python package to your curated list: https://github.com/django-json-api/django-rest-framework-json-api

It is a very nice python implementation wrapping Django APIs. I am using it and it seems to have some tracktion.

**Comment by jelhan** [comment]
Thanks a lot for your suggestion. The library has been added to the list in the meantime. I think this issue could be closed.
