### ISSUE TITLE
Document differences/trade-offs between JSON API and other similar specifications

### ISSUE THREAD

**Issue by timbunce** [json-api/json-api#14]
For example:
- [HAL](http://stateless.co/hal_specification.html)
- [JSON-LD](http://json-ld.org)
- [Collection+JSON](http://amundsen.com/media-types/collection/)
- [Siren](https://github.com/kevinswiber/siren)

**Comment by wycats** [comment]
This is very important, and a dup of #1. Thanks so much for providing a list of similar specifications for the FAQ section about this.
