### ISSUE TITLE
Changelog between versions of the Spec

### ISSUE THREAD

**Issue by ylynfatt** [json-api/json-api#1400]
Does a changelog currently exist for changes between v1.0 and v1.1 (and v.1.2) of the JSON:Api Spec? It would be good to have a general idea of significant changes to the spec as each new version is released.

**Comment by lode** [comment]
See the 'Update history' at the bottom of the homepage: https://jsonapi.org/#update-history

**Comment by ylynfatt** [comment]
@lode thanks. Much appreciated.
