### ISSUE TITLE
roadmap/contributions

### ISSUE THREAD

**Issue by remmeier** [json-api/json-api#1402]
Hi, 

https://jsonapi.org/ it mentions that version 1.1 is to be released by end of January. Is there an update to it? Sometimes there is quite substantial activity here, then everything falls back to sleep a bit... I do not consider that an issue mostly. Because it is a simple spec with simple patterns that does not need continuous attention. Nevertheless some topics like filtering, nested filtering, nested inclusions, bulk update/side-loading and modelling would be really good to see being ironed out to make the various implementations work better together and fill the gaps to GraphQL and continue to give all the benefits of restful APIs that have been lost along the way with GraphQL. For all of this the 1.1 release with the profiles would provide the basic building block.

Maybe a schedule could be setup? Designate a lead for each topic to drive the topic forward? have one, two public review periods where people can provide input and then come to a conclusion and release the particular profile? I could also make time for one or the other topic.

**Comment by dgeb** [comment]
Hi @remmeier - Thanks for reaching out with your questions and insights. I've just opened an issue (#1403) that provides some perspective on the general lack of progress in finalizing v1.1. I'm starting with a request for community feedback, which I hope to follow soon with some action. And I appreciate your suggestions for how we might manage that progress. 👍

**Comment by jelhan** [comment]
Please also have a look at #1578 for the latest state of v1.1.

**Comment by jelhan** [comment]
I'm going to close this one as an update on roadmap has been shared in https://github.com/json-api/json-api/issues/1578#issuecomment-907854591. Not saying that there isn't a need for another update. But I think we can use #1578 to track that.
