### ISSUE TITLE
Client-side caching with URL-based representations

### ISSUE THREAD

**Issue by samwgoldman** [json-api/json-api#141]
Consider this resource:

``` javascript
{
  "projects": [{
    "id": 1,
    "href": "http://example.com/projects/1",
    "name": "Example Project",
    "links": {
      "tasks": "http://example.com/projects/1/tasks"
    }
  }],
  "tasks": [{
    "id": 1,
    "href": "http://example.com/tasks/1",
    "name": "Task 1",
    "links": {
      "project": "http://example.com/projects/1"
    }
  }, {
    "href": "http://example.com/tasks/2",
    "id": 2,
    "name": "Task 2",
    "links": {
      "project": "http://example.com/projects/1"
    }
  }]
}
```

A project's tasks are at a path `project/:project_id/tasks`, but the tasks themselves have paths like `tasks/:task_id`. In this resource, we side-load the project's tasks to minimize roundtrips to the API.

However, the client has no way of knowing from this representation that it already has the appropriate tasks. We might rectify this situation if we link to a project's tasks by ID. For example:

``` javascript
{
  "links": {
    "projects.tasks": "http://example.com/projects/{projects.id}/tasks"
  }
  "projects": [{
    "id": 1,
    "href": "http://example.com/projects/1",
    "name": "Example Project",
    "links": {
      "tasks": [1, 2]
    }
  }],
  "tasks": [{
    "id": 1,
    "href": "http://example.com/tasks/1",
    "name": "Task 1",
    "links": {
      "project": "http://example.com/projects/1"
    }
  }, {
    "id": 2,
    "href": "http://example.com/tasks/2",
    "name": "Task 2",
    "links": {
      "project": "http://example.com/projects/1"
    }
  }]
}
```

Here we have moved the `projects.tasks` link from the project links object to the top-level links object. Now the client can match the `projects.links.tasks` IDs against the IDs of the side-loaded tasks. I have doubts about this approach, particularly because it muddies the concept of identity. We use hrefs to identify resources, except when we don't (for caching).

Even if that were OK on it's own, it opens up another issue. In either of the above representations, for a given task, the client can determine that we have already loaded its associated project by comparing hrefs. However, now we're using IDs as cache keys for project->tasks and hrefs as cache keys for task->project. That's not nice.

I've tried to dump my brain here. I don't have any specific recommendation, but I'm curious what others think. Anyone have an alternate representation for this?

**Comment by samwgoldman** [comment]
Perhaps it is possible to use IDs consistently as cache keys if we move the tasks->project link into the top-level links object.

``` javascript
{
  "links": {
    "projects.tasks": "http://example.com/projects/{projects.id}/tasks",
    "tasks.project": "http://example.com/projects/{tasks.project}"
  }
  "projects": [{
    "id": 1,
    "href": "http://example.com/projects/1",
    "name": "Example Project",
    "links": {
      "tasks": [1, 2]
    }
  }],
  "tasks": [{
    "id": 1,
    "href": "http://example.com/tasks/1",
    "name": "Task 1",
    "links": {
      "project": 1
    }
  }, {
    "id": 2,
    "href": "http://example.com/tasks/2",
    "name": "Task 2",
    "links": {
      "project": 1
    }
  }]
}
```

I think the consequence of this design is that all document-level links objects must be ID-based.

I think we need to specify how URI templates are expanded. In `projects.tasks` I want to expand `{projects.id}` with the `id` property from the project document itself, whereas in `tasks.project` I want to expand `{tasks.project}` with the `project` property from the task's links object. Maybe `{tasks.links.project}` would be more appropriate in the `tasks.project` link?

**Comment by gr0uch** [comment]
Including all IDs in a to-many relationship in the payload may not be feasible, particularly when it may be thousands of IDs long.

That said, I think that your top-level links should either:
- include a link to tasks by id: `http://example.com/tasks/{tasks.id}`
- make the project's tasks link to the tasks collection: `http://example.com/tasks/{projects.tasks}`

In the current state of your example above, the client doesn't know how to retrieve a partial collection of tasks, so including the tasks IDs in the links doesn't help the client get only the tasks that are not loaded.

**Comment by samwgoldman** [comment]
> Including all IDs in a to-many relationship in the payload may not be feasible, particularly when it may be thousands of IDs long.

Yes, this would be a problem with collections that have very many members. One would probably not want to side-load/cache in this case anyway.

> That said, I think that your top-level links should either:
> - include a link to tasks by id: http://example.com/tasks/{tasks.id}
> - make the project's tasks link to the tasks collection: http://example.com/tasks/{projects.tasks}

Do you think you could show me what these would look like? What would the top-level links object's keys be for these? How would the client know where to look?

> In the current state of your example above, the client doesn't know how to retrieve a partial collection of tasks, so including the tasks IDs in the links doesn't help the client get only the tasks that are not loaded.

I think I understand what you mean, but let me check my assumption. If I modify the last example above so that Task 1 was side-loaded but Task 2 was not, the client wouldn't know how to request Task 2. That's true. I think it would be OK for the client to request all of `projects.tasks` in that case.

**Comment by gr0uch** [comment]
> Do you think you could show me what these would look like? What would the top-level links object's keys be for these? How would the client know where to look?

I think the second case is more straightforward and an example of this is in the docs: 

``` js
{
  "links": {
    "projects.tasks": "http://example.com/tasks/{projects.tasks}"
  },
  "projects": [{
    "id": 1,
    "links": {
      "tasks": [1, 2, 3]
    }
  }]
}
```

This would tell the client to go fetch `http://example.com/tasks/1,2,3`. 

Or you could keep your example as is and include this key to your links (I'm not sure if this is correct or valid):

```
"tasks": "http://example.com/tasks/{tasks.id}"
```

> I think I understand what you mean, but let me check my assumption. If I modify the last example above so that Task 1 was side-loaded but Task 2 was not, the client wouldn't know how to request Task 2.

Correct. There's a tradeoff to be made between including a list of IDs or having to retrieve related resources over and over. For example, if projects 1, 2, 3... and so on all had task 1 related to them, you'd retrieve task 1 repeatedly (unless you included IDs of course).

**Comment by samwgoldman** [comment]
So far we have discussed a number of different representations that a server could produce, and how a client could use those representations to make requests for linked resources.

I'd like to direct this discussion back to the original topic: how can we represent resources so that the client _doesn't_  need to make requests for linked resources? Ember is cited as an exemplar client implementation. Ember Data uses a client-side "store" to cache already seen documents and reduce the number of requests. How does this store work, both with URL-based and ID-based representations? What are the cache keys? In my original question, I showed how URI-based "has many" association links make this unclear. This is still unresolved.

**Comment by rkh** [comment]
This is related to #163.

**Comment by dgeb** [comment]
Please review the updated [resource relationships](http://jsonapi.org/format/#document-structure-resource-relationships) section of the spec. Specifically focus on relationship URLs (for obtaining link objects) and related resource URLs (for obtaining related resource objects). You should be able to fetch from either (and they may be paginated), to retrieve and cache what is needed.
