### ISSUE TITLE
Please clarify URL recommendations

### ISSUE THREAD

**Issue by maurei** [json-api/json-api#1431]
I am confused with respect to json:api's recommendations for URLs. The recommendation mentions that the **type values** and  **member names** (of `relationships` and `attributes`) should ripple through to URLs:

>It is recommended that the URL for a collection of resources be formed from the resource type. 
...
>It is recommended that a related resource URL be formed by appending the name of the relationship to the resource’s URL.

In turn, there are explicit recommendations for **member names**: use camelCase (#1297).  For **type values** there are no explicit recommendations, but for consistency to me it makes sense to use the same convention here, because else you could end up having an API response that contains both kebab-case and camelCase. The idea of consistency between type vales and member names is supported by the spec:
> The values of type members **MUST** adhere to the same constraints as member names.

So my reading is that if we choose to adhere to the extra camelCase constraint, it should also apply to type values.

So far all of this seems to suggest that urls should be camelCased too (i.e. `/myModels/1/relationships/toOneRelationship`). However, the [async processing](https://jsonapi.org/recommendations/#asynchronous-processing) example does not seem to follow the outline above because `queue-jobs` is in kebab-case in both the type value and the URL.  

What does this imply? Does it imply that type values can remain in kebab-case but member names should be pascalCase? This would mean we end up having kebab-case and pascalCase in both the api output and URL, which is not desirable? Or is it simply an example that choose to not follow the recommendations and in which kebab-case is used everywhere?

I'm trying to figure out what to do with my URLs. I understand these are just recommendations and I am free to do as I like, but I'm working on a json:api implementation ([JsonApiDotNetCore](https://github.com/json-api-dotnet/JsonApiDotNetCore)) and I want to stay as close as possible to the specs and recommendations. Basically, the questions posed by @antonkomarev  in https://github.com/json-api/json-api/issues/1255 at the bottem are pretty much the open questions I have too

**Comment by maurei** [comment]
Personal stance:  I vote for having camelCase **everywhere**. 

Two main arguments: (1) consistency is key and (2) readability/crawlability is not as important

**1. Consistency is key**
I think json:api should aim at maximizing consistency, which is an argument in favour of having camelCased urls:
* *query parameter part of url*: having kebab-case when filtering on attributes and relationships (`?filter[first-name]=x`) while these member names in the document body are camelCase ( `attributes: { "firstName": "x" ...`) is not consistent. Thus, go for camelCase in query parameters too
* *path part of url*:  Then it follows that relationship member names are camelCase in the body document as well as in the query parameters, so having them kebab-cased in the path part of the url would be inconsistent. So, prefer `.../relationships/toOneRelationship?include=toManyRelationship` over `.../relationships/to-one-relationship?include=toManyRelationship` for consistency.
* Since a part of the url path is camelCased, all of it should be camelCased: `myModels/relationships/toOneRelationship?include=toManyRelationship`.

**2. Readability/crawlability is not as important**
* Some people would argue that kebab-case simply looks nicer and is easier to read for humans. I agree with them. But that's the thing with API urls: humans will never have to look at them, except when writing the code that will do the reading for them
* [In this stackoverflow post](https://stackoverflow.com/questions/10302179/hyphen-underscore-or-camelcase-as-word-delimiter-in-uris) it is argued that for "public/external" webpages, kebab-case allows for better crawlability, and to keep it simple it is best to just stick with that for "private/internal" webpages too. But here we're designing urls to be used for an entirely different content type which wont be crawled by search engines. Hence I argue this is not as important and certainly does not outweigh the benefits (easy parsability) of having a strong correlation between urls and the document body

**Comment by antonkomarev** [comment]
Personally I'm using `camelCase` for everything except resource types. Types in my APIs have `UpperCase`.

**Comment by maurei** [comment]
So your routes look like `/myModel/1/relationships/toOneRelationship` but the payload contains `{ "type": "MyModel"}`?

What is the motivation for having uppercase in the document body?

**Comment by antonkomarev** [comment]
`/articles/1/relationships/exampleRelationship`

`/articles?filter[exampleRelationship][type]=UpperCaseResourceType`

Don't think about `articles` in URI as about `Article` type. URI could be like this:
`/someRandomName?filter[exampleRelationship][type]=UpperCaseResourceType`
Or even like this:
`/fsdkfjdskflsdklf?filter[exampleRelationship][type]=UpperCaseResourceType`
But it could return `Article` resources.

**Comment by maurei** [comment]
> Don't think about articles in URI as about Article type

So if I'm understanding correctly, you're not adhering to the following part of the recommendations?
> It is recommended that the URL for a collection of resources be formed from the resource type.

**Comment by antonkomarev** [comment]
There are cases when one endpoint could return different resource types, then you cannot strictly follow this rule. I'm always trying to follow this concept to make API developer friendly, but sometimes it's impossible.

I highly recommend you to read this set of articles: https://blog.michaelhibay.com/2017/03/29/development-guidelines-for-hypermedia-apis/

**Comment by freddrake** [comment]
The specification does not place any normative constraints on the URL-space itself, only how the URLs returned in the various `links` structures should behave.

This is good, since it avoids misleading API consumers into thinking URLs can be constructed by clients.

It would be better if this separation were more clear (in fact, I thought were was something about this, but I can't find it now). The presence of recommendations about URL structure in the Recommendations page is... unfortunate.

**Comment by dsbos** [comment]
> misleading API consumers into thinking URLs can be constructed by clients.

Don't clients _need_ to be able to construct URLs from resource identifier objects?

If a response contains a resource identifier object (e.g., under `relationships`), which has a `type` member and an `id` member which together uniquely identify an entity, how is the client supposed to make a request to get the data for that entity without constructing a URL?  

The example URL paths in the JSON:API spec imply that the client can take a type and an ID and construct a URL with a path having a segment corresponding to the type followed by a segment equal to the ID, and then make a request to that URL to get the identified entity as the primary data.

There doesn't seem to be any requirement that entities referred by a resource identifier object in a response need to show up (as resource objects) in that same response.  (They _can_ appear, if the `include` parameter requests them, but that's optional.) (Every resource object in `included` has to be referred to by a resource identifier object, but there's no requirement that every resource identifier object has to refer to a resource object (in the same response document.) 

If clients can't construct those URLs, then how can they use resource identifier objects that don't have a corresponding resource object in `included`?

**Comment by freddrake** [comment]
> Don't clients need to be able to construct URLs from resource identifier objects?

Actually, no.  Your example of a relationship can provide the URLs required in the `links` object, and arguably should, especailly if the relevant resources are not included in the response.

**Comment by dsbos** [comment]
> Your example of a relationship can provide the URLs required in the `links` object,

If a relationship listed, say, 10 resource identifier objects, then how would the 10 corresponding URLs be listed within the relationship's `links` object? How would the correspondence between each object's `type`/`id` combination and its URL be represented?

Or are you referring to `links` objects _in the resource identifier objects_?  (I don't think I've seen any such `links` members in the spec's examples, and the Resource Identifier Objects section doesn't _seem_ to allow them. (It specifies some members that resource identifier objects "must" and "may" have, although it doesn't explicitly specify that they _can't_ have other members.))

**Comment by freddrake** [comment]
> If a relationship listed, say, 10 resource identifier objects, then how would the 10 corresponding URLs be listed within the relationship's `links` object?

The relationship would include a `related` link that points to a collection of the 10 related resources; performing a `GET` on that would yield the 10 resources.  Those would include the resource identification and could be aligned with the references from the relationship.

As an implementer, I'd be inclined to return the `related` link and not the resource identifiers if the resources are not being included in the original response, to avoid any confusion about what's needed.
