### ISSUE TITLE
JSON API Plugin not working

### ISSUE THREAD

**Issue by obadaKraishan** [json-api/json-api#1433]
JSON-API plugin: This plugin has been closed as of August 7, 2019 and is not available for download. This closure is temporary, pending a full review.

Is there any alternative?

**Comment by ahx** [comment]
What do you mean with “JSON-API plugin”? Are you referring to a client/server implementation?

**Comment by obadaKraishan** [comment]
Wordpress plugin

**Comment by wimleers** [comment]
URL?

**Comment by jelhan** [comment]
This issue does not seem to be related to the JSON:API specification. I recommend to ask these question to the maintainers of that Wordpress plugin.
