### ISSUE TITLE
Links object in error

### ISSUE THREAD

**Issue by JaZo** [json-api/json-api#1444]
The spec is ambiguous about whether an error links object MUST contain an `about` member or not. Someone has asked [the exact same question on the forum](https://discuss.jsonapi.org/t/errors-and-links/1227), but unfortunately it is still unanswered. I hope we can clarify this in some way.

**Comment by bbrala** [comment]
Thanks :)

**Comment by jelhan** [comment]
This has been clarified in v1.1:

>  `links`: a links object that **MAY** contain the following members:
> 
>  -   `about`: a link that leads to further details about this particular occurrence of the problem. When derefenced, this URI SHOULD return a human-readable description of the error.
>  -   `type`: a link that identifies the type of error that this particular error is an instance of. This URI SHOULD be dereferencable to a human-readable explanation of the general error.

Do you see further need to clarify it?

**Comment by freddrake** [comment]
I think this can be closed because of PR #1525.

**Comment by dgeb** [comment]
Thanks @jelhan and @freddrake 👍
