### ISSUE TITLE
Do Sparse Fieldsets apply to include relationships?

### ISSUE THREAD

**Issue by multimeric** [json-api/json-api#1450]
The spec defines sparse fieldsets in terms of `fields`:
>  A client MAY request that an endpoint return only specific fields in the response on a per-type basis by including a fields[TYPE] query parameter.

`fields` are defined as:
> A resource object’s attributes and its relationships

However, in the example request for sparse fieldsets, we have:
```
GET /articles?include=author&fields[articles]=title,body&fields[people]=name HTTP/1.1
```
Note that the `fields[articles]` does *not* include the `author` relationship, even though relationships are fields. According to the spec as it stands, the relationship between article and author should *not* be included in the response to this request, which seems like an unlikely request to make.

***

Thus, we need clarification:
* Do we actually mean sparse fieldsets only refer to *attributes*, or
* Is this example poor, and we should have included the relationship in the fields, making it: 
```
                                                         ↓↓↓↓↓ (this is new)
GET /articles?include=author&fields[articles]=title,body,author&fields[people]=name HTTP/1.1
```

**Comment by Doqnach** [comment]
the way I read it is that the `include=author` means that the response might include the `author` object in the `included` array, even if the relationship is not even present because of the sparse fieldset. You then have absolutely no way to link them to each other though, so that might be a confusing implementation choice...

**Comment by multimeric** [comment]
Yes, that's also how I interpret it. I don't doubt that both resources would be *included*, the question is whether the relationship between them is displayed.

**Comment by gabesullice** [comment]
Sparse fieldsets _do_ apply to relationship fields, even when the relationship field is also a member of the `include` query parameter.

Note this statement under [the compound documents section](https://jsonapi.org/format/#document-compound-documents):

> The only exception to the full linkage requirement is when relationship fields that would otherwise contain linkage data are excluded via sparse fieldsets.

"Full linkage" here refers to the client's ability to associate resource identifier objects in a relationship object with a resource object in the `included` member.

**Comment by gabesullice** [comment]
> Thus, we need clarification:
> 
> * Do we actually mean sparse fieldsets only refer to attributes, or
> * Is this example poor, and we should have included the relationship in the fields, making it:

I would be open to a PR that either:

- Changes the example URL, OR
- Adds a clarifying note
