### ISSUE TITLE
Specification for meta-only response after resource creation

### ISSUE THREAD

**Issue by 8-3** [json-api/json-api#1466]
When **updating** resources or relationships JSON:API 1.1 defines as possible response the [following](https://jsonapi.org/format/1.1/#crud-updating-responses-200):

> A server MUST return a 200 OK status code if an update is successful, the client’s current fields remain up to date, and the server responds only with top-level meta data. In this case the server MUST NOT include a representation of the updated resource(s).

This allows to respond with `meta` only. For updates of relationships we find the [same definition](https://jsonapi.org/format/1.1/#crud-updating-relationship-responses-200). However when **creating** resources there is no standardized way to response with `meta` only.

1. [201](https://jsonapi.org/format/1.1/#crud-creating-responses-201) requires me to send back the resource.
> The response MUST also include a document that contains the primary resource created.
2. [204](https://jsonapi.org/format/1.1/#crud-updating-responses-204) does not allow me to include `meta`
> the server MUST return either a 201 Created status code and response document (as described above) or a 204 No Content status code with no response document.

As 200 is not defined as response status code for resource creation yet I propose to define it similar to the update responses for resources and relationships cited above.

Beside making the create specification more consistent with resource updates and relationship updates this allows (just as an example use case) to send back success messages after a resource creation in the appropriate language without the need to include the created resource in the response.

**Comment by jelhan** [comment]
This has been addressed by v1.1: 

> A server MAY return a 201 Created response with a document that contains no primary data if the requested resource has been created successfully and the server does not change the resource in any way (for example, by assigning an id or createdAt attribute). Other top-level members, such as [meta](https://jsonapi.org/format/#document-meta), could be included in the response document.
