### ISSUE TITLE
Problem with included structure

### ISSUE THREAD

**Issue by gvpmahesh** [json-api/json-api#1476]
The current structure is 
```
included: [{'id': 'foo', ..}, {}]
```

Instead of
```
included: {
'foo': {
.....
}  

}
```

While in the first structure you are forced to loop over all the items in the included to find the object you are interested in, which takes O(n) time.

But in the second structure, you can accomplish the search with O(1), I just want to understand the rationale behind this, because I feel it's overhead for the consumers of API

**Comment by thomaxxl** [comment]
1. Multiple included items of different types may have the same id.
2. The O is negligible for web api array lengths on modern hardware. I.e. all jsonapi use cases.

**Comment by gvpmahesh** [comment]
Thanks @thomaxxl for your clarification. I did not think of duplicate ids problems.

**Comment by gvpmahesh** [comment]
Closing this, as this is clarified
