### ISSUE TITLE
Question, Compound documents without relationship in primary resources

### ISSUE THREAD

**Issue by ben-zhong** [json-api/json-api#1480]
Hi, we have an api to return a compound document. I wonder if it is valid according to JSON:API

GET http://api/services?include=client

Response:
```
{
    "data": [
        {
            "id": 3,
            "type": "services",
            "attributes": {
                "attr1": "value1",
                ...
                "attrn": 0
            }
        },
       {
            "id": 4,
            "type": "services",
            "attributes": {
                "attr1": "value1",
                ...
                "attrn": 0
            }
        }
    ],
    "included": [
        {
            "id": 333,
            "type": "client_services",
            "attributes": {
                ...
            },
            "relationships": {
                "services": {
                    "data": {
                        "id": 3,
                        "type": "services"
                    }
                },
                "clients": {
                    "data": {
                        "id": 12,
                        "type": "clients"
                    }
                }
            }
        },
        {
            "id": 334,
            "type": "client_services",
            "attributes": {
                ...
                }
            },
            "relationships": {
                "services": {
                    "data": {
                        "id": 4,
                        "type": "services"
                    }
                },
                "clients": {
                    "data": {
                        "id": 12,
                        "type": "clients"
                    }
                }
            }
        },
        {
            "id": 12,
            "type": "clients",
            "attributes": {
                "name": "A Client"
            }
        }
    ]
}
```
According to Json:API document:
>Compound documents require “full linkage”, meaning that every included resource MUST be identified by at least one resource identifier object in the same document. These resource identifier objects could either be primary data or represent resource linkage contained within primary or included resources.

While there is no relationship in the primary resources (services objects), the client_services object does have relationships of services and client objects. 
Is the response consider to be "full linkage"? Are the above API and response valid?

Thanks!

**Comment by danleyden** [comment]
I'm not 100% sure about the validity, however from a purely practical point of view a number of client libraries and more simplistic parsers will likely struggle with this.

A typical method for parsing might look something like:
```
for primaryObject in data {
  for relation in primaryObject.relationships {
    parse from included where includedItem.type == relation.type
      && includedItem.id == relation.id
  }
}
```

In this methodology, your clients objects would never actually get parsed...

I would suggest altering the API's format to have the services object either have a relationship direct with clients or to the client_services object. The first option would be easier for other developers to consumer, but may be harder for you to implement in your API

**Comment by Doqnach** [comment]
I think you have the relationships backwards. The items in `data` should have the relationships, and then if the client requests the includes those items will be added under `included` (with their own relationships of course where applicable).

**Comment by jelhan** [comment]
This requirement has been reworded in v1.1:

> Every included resource object MUST be identified via a chain of relationships originating in a document’s primary data. This means that compound documents require “full linkage” and that no resource object can be included without a direct or indirect relationship to the document’s primary data.

@ben-zhong Do you think that new wording would have answered your question? Or do you see additional need for clarifying it in the specification?
