### ISSUE TITLE
Many to many POST Body relationships problem 

### ISSUE THREAD

**Issue by rcholody** [json-api/json-api#1485]
I have got problem with POST request with many to many relationship.
I have STI  Beneficiary, model type Author that is connected to Book.

**beneficiary.rb**
```ruby
class Beneficiary < ApplicationRecord
  belongs_to :company_address, class_name: ‘CompanyAddress’, optional: true
  has_one :billing_information
  enum type: [‘Agency’, ‘Author’, ‘Heir’]
  self.inheritance_column = :type
end
```
**author.rb**
```ruby
class Author < Beneficiary
  has_many :author_books
  has_many :books, through: :author_books
end
```
**author_resource.rb**
```ruby
class AuthorResource < BeneficiaryResource
  many_to_many :books, resource: BookResource, through: :author_books

end
```
**book.rb:**
```ruby
class Book < ApplicationRecord
  has_many :author_books
  has_many :authors, class_name: ‘Author’, through: :author_books
end
```

**book_resource..rb**

```ruby
class BookResource < ApplicationResource
  attribute :title, :string

  many_to_many :authors, resource: AuthorResource, through: :author_books
end
```

**author_book.rb**

```ruby
class AuthorBook < ApplicationRecord
  belongs_to :author
  belongs_to :book
end
```
I want to create Book that will be connected to Author.

I am trying to achieve proper POST request with this structure: https://discuss.jsonapi.org/t/representing-many-to-many-pivot-data/445 
Unfortunately I always getting errors about unknown attribute 'authors' etc. 

Example body from POST request to localhost:3000/api/v1/books?debug=true

```JSON
{
    "data": {
        "type": "books",
        "attributes": {
            "title": "Fake Book",
            "authors": {
                "relationships": {
                    "author": {
                        "author": "authorbooks",
                        "id": "3"
                    }
                }
            }
        }
    },
    "included": [
        {
            "type": "author",
            "id": "3"
        }
    ]
}
```

Error:

          data.attributes.authors is an unknown attribute

I can't find any similar example there  
 https://jsonapi.org/format/#crud-updating-to-many-relationships

Am I built proper implementation of many to many?

Do you see any path to solve this problem? Or maybe do you know any example of request with models in many_to_many relationship in JSON-API?

**Comment by Doqnach** [comment]
The `relationships` should be on the same level as `type` and `attributes`, not nested within. That example given there (#383) was not implemented.

**Comment by rcholody** [comment]
Thanks for you answer. It push me to correct direction and I solve this problem with that Body request:
```JSON
{
    "data": {
        "type": "books",
        "attributes": {
            "title": "Title Test"
        },
        "relationships": {
            "authors": {
                "data": {
                    "type": "authorbooks",
                    "temp-id": "hashhash"
                }
            }
        }
    },
    "included": [
        {
            "type": "author_books",
            "temp-id": "hashhash",
            "attributes": {
                "author_id": "3"
            }
        }
    ]
}
```
