### ISSUE TITLE
Content-Type and Accept header should be application/vnd.api+json

### ISSUE THREAD

**Issue by rkh** [json-api/json-api#149]
Right now all the examples use application/json.

**Comment by rkh** [comment]
Has been fixed.

**Comment by sergiogarciadev** [comment]
I know that is an old issue and a closed one, but in someway I disagree.

[RCF-4627 - Section 6. IANA Considerations](http://tools.ietf.org/html/rfc4627#section-6) denotes [application/json](http://www.iana.org/assignments/media-types/application/json) as the correct media type for json, so I my opition this should be a option to use.

Additionally, the vendor notation could be an option to version the API (or something else, but an option not a requirement), as shown in [Internet Media Type Naming](http://en.wikipedia.org/wiki/Internet_media_type#Naming), as used by the [GitHub API](https://developer.github.com/v3/media/).

Also, every developer who consumes an REST API previously learned to use the original media type.

**Comment by steveklabnik** [comment]
>  as the correct media type for json, so I my opition this should be a option to use.

Right, but JSON-API is _more_ than just JSON. We're following the rules for IANA, and in fact, are registered with them: http://www.iana.org/assignments/media-types/media-types.xhtml
