### ISSUE TITLE
"MUST return 204" clauses are difficult to implement, conflicts with ?include, and won't break anyone if violated anyway

### ISSUE THREAD

**Issue by cmeeren** [json-api/json-api#1494]
I'm the author of [Felicity](https://github.com/cmeeren/Felicity), a relatively new JSON:API framework (as well as the deprecated [FSharp.JsonApi](https://github.com/cmeeren/FSharp.JsonApi/) library). As such I'm interested in every minute detail of the spec.

The "MUST return 204" clauses strike me as particularly cumbersome. I'm talking about the following (paraphrased):
* Must return 204 to PATCH resource requests if only the requested fields were modified as specified in the request
* Must return 204 to POST/DELETE to-many relationship requests if the relationship was modified as specified in the request

On its own, these are hard enough. I can't think of a foolproof way a framework can detect these conditions in all cases. If the framework is based on user code being immutable (as Felicity is), then it's possible to build the resource for both the original input entity and the updated entity, and compare the resources, verifying that 1) all fields not in the request are identical between the two, and 2) the fields specified in the request have exactly the specified values. Then 204 can be returned.

This becomes more difficult when updating relationships, which may be lazily loaded. Extra DB round-trips may occur.

And it becomes even more complicated if `?include` is used. First of all, the spec doesn't say what should happen if the response matches the request, but the request specifies `?include`. In that case, 204 can't be returned anyway, and the response must contain the resource being modified as well as any included resources.

Another matter for included resources: What if a modification to a resource also modifies another resource? For example, modifying an `orderline` also modifies the parent `order`. What if the `orderline` is modified as specified in the request, warranting 204 as per the spec, but the parent `order` is also modified? The spec says nothing about how this impacts the choice of 204 vs. 200, or how any `?include` present in the request factors into this.

Based on all of the above, and after talking to our front-end devs, it is my fairly strong opinion that it's much simpler both to implement and to consume the API if the 204 clauses are completely ignored. This is what Felicity does, and I currently have no intention of changing that. While it is technically a violation of the JSON:API spec, it will never break any clients, because even partially conforming clients (e.g. homegrown or ad-hoc clients) are prepared to handle normal 200 responses, whereas only more strictly conforming clients are prepared to handle 204 responses.

The only cost is slightly more data transferred over the wire, but given the complexity in checking whether the response should be 200 or 204 (particularly if it incurs extra DB roundtrips for relationships), it may still be more effective in some cases to just ignore it altogether. (And given the verbosity of JSON:API due to the resource and relationship links, over-the-wire efficiency was never a core reason for our choosing JSON:API. If counting bytes, one will always be much better off with optimized custom formats.)

This is mostly an FYI from a guy who has developed both a library and a framework for JSON:API. You may take this as hopefully useful input for future JSON:API versions. But feel free to discuss, of course.

**Comment by cmeeren** [comment]
In the 1.1 spec, this is seemingly no longer an issue:

### Update resource requests

> If an update is successful and the server doesn’t change the targeted resource in ways other than those specified by the request, the server **MUST** return either a 200 OK status code and response document (as described above) or a 204 No Content status code with no response document.


### Update relationship requests

> If an update is successful and the server doesn’t change the targeted relationship in ways other than those specified by the request, the server **MUST** return either a 200 OK status code and response document (as described above) or a 204 No Content status code with no response document.

**Comment by jelhan** [comment]
It has been addressed as part of  #1638. Missed updating this issue. Thanks for taking care of it!
