### ISSUE TITLE
Question about members of error objects

### ISSUE THREAD

**Issue by freddrake** [json-api/json-api#1496]
The error object, as defined in both 1.0 and the draft 1.1 specifications, MAY contain many members, but there are none that MUST be provided.  It seems insane that a service would return a completely empty error, but is it valid?

I'd like a statement in the specification that clarified that at least one member must be provided, even if it's the **meta** member with non-standard content.

**Comment by dgeb** [comment]
@freddrake Thanks for raising this point.

Your proposal seems reasonable, and would be consistent with other areas of the spec that require at least one member (e.g. https://jsonapi.org/format/#document-top-level).

Do you want to pursue a PR to bring this into 1.1?

**Comment by freddrake** [comment]
I'll have to think about how to write that, but will see what I can come up with.

What I'd like to avoid is having something like

~~~~~~ json
{"errors": [
   {"meta": {},
    "source": {}
    }
 ]}
~~~~~~

being allowed.  There needs to be be *some* information content somewhere.

Looking at the 1.0 spec, it looks like the about link is required if links is included.  For 1.1, it looks like both about and type are required, if links is included.  Is that the intent?  (Smells like a compatibility issue for type to be required.)

**Comment by freddrake** [comment]
@dgeb: Any response to my question about the type link in the previous comment?

**Comment by gabesullice** [comment]
`status` seems like the most reasonable one to me. It's likely going to be readily available info on the server side and it will encode some of the conversational context into the response document.

**Comment by freddrake** [comment]
@dgeb: My question about requirements of `links` members in the error object from Sep 9 have gone without response for two months.  I understand we're all busy, but I'd like to understand requirements in order to propose wording that's helpful.

@gabesullice: Are you suggesting that `status` become required, specifically?  Even if that's done in 1.1 only, doesn't that impose a forward compatibility conundrum?

**Comment by dgeb** [comment]
@freddrake My proposal would be to change:

> An error object MAY have the following members:

To:

> An error object MUST contain at least one of the following members:

We really can't specify the contents of `meta` so if an implementation wants to keep it empty, it would be bizarre, but not really in the domain of this spec.

> Looking at the 1.0 spec, it looks like the about link is required if links is included. For 1.1, it looks like both about and type are required, if links is included. Is that the intent? (Smells like a compatibility issue for type to be required.)

Good catch, I think this should change from:

> a links object containing the following members:

To: 

> a links object that MUST contain at least one of the following members:

**Comment by lode** [comment]
What about other kind of links in error objects?

With 'An error object MUST contain at least one of the following members:' refering to `about` and `type` it sounds, more than the previous sentence did, that no other links are allowed. Is that correct?

E.g. see https://discuss.jsonapi.org/t/error-action-link/1489
