### ISSUE TITLE
JSON:API Object in requests?

### ISSUE THREAD

**Issue by freddrake** [json-api/json-api#1498]
The specification (both 1.0 and draft 1.1) describe cases where the server might want to return a "jsonapi" top-level member, but there is nothing about how a server should handle such a member found in a request.

Should a client include a JSON:API Object with a request to indicate what specification version(s) it supports?

**Comment by gabesullice** [comment]
As a server implementer, I think I would be happy if more clients implemented it. The advantage is that I'd have some insight into the capabilities of its clients and could perhaps upgrade/deprecated things sooner/later with that information. That said, the spec itself is perfectly okay with clients and server omitting it. It's purely an available enhancement.
