### ISSUE TITLE
Specification should state whether the "default" fields for a type is required to be complete

### ISSUE THREAD

**Issue by freddrake** [json-api/json-api#1499]
This has been discussed in the forum a few times, and the specification seems to be silent on this (at least in my reading).

It would be great if the specification explicitly stated whether the default set of fields returned for a type was required to include all available fields for the type.

Explicit is better than implicit.

**Comment by gabesullice** [comment]
The advantage of leaving it unspecified is that servers can choose to return _no_ fields unless a `fields` query parameter is present. This is advantageous because a server can inspect its request log to identify which fields are depended upon and which could be safely removed. IOW, every field must be explicitly requested.

Perhaps a note like this would help?

> Note: It is valid for a server to include no fields in its response _unless_ the client explicitly requests them. This can reduce response sizes and help with server evolution—at the expense of discoverability and concision.

FWIW, even if we wanted to add a requirement about default fields, it would be an incompatible change that would require a new major version of the spec.

**Comment by freddrake** [comment]
I think a comment like that would be helpful.  Specifying that the server can return a subset of the available fields when the client doesn't specify fields[type], and that an any subset is acceptable, would be best.  That would cover both the case of needing to know what clients are using, and avoiding delivering expensive fields if not requested.

**Comment by gabesullice** [comment]
Care to open a PR? :)

I think we can make the change in 1.0 and 1.1.

**Comment by freddrake** [comment]
While working on this, it strikes me that the spec is also not specific regarding whether setting fields[type] to an empty string is allowed, in which case the client would be expecting no fields for each resource of the type.

Regarding the mechanics of making the change: Should I edit just one of 1.0, 1.1, and upcoming, or all of them?  I didn't see anything about that in CONTRIBUTING.md.

**Comment by gabesullice** [comment]
> it strikes me that the spec is also not specific regarding whether setting fields[type] to an empty string is allowed, in which case the client would be expecting no fields for each resource of the type.

Correct.

> Should I edit just one of 1.0, 1.1, and upcoming, or all of them?

1.0 and 1.1. Upcoming is simply a redirect file.

**Comment by freddrake** [comment]
Resolved with the merge of #1500.

**Comment by gabesullice** [comment]
🙌
