### ISSUE TITLE
Are links always to json-api documents?

### ISSUE THREAD

**Issue by rkh** [json-api/json-api#150]
Do links listed in the links section have to implement JSON API themselves?

**Comment by diosney** [comment]
I don't think that JSON+API restricts itself in that way and that this functionality is perfectly valid but I can be mistaken so it will be great that @steveklabnik cames into our aid.

I see natural and desirable that an API can return a JSON+API document that links to other related resources through `links`, and that those links can guide you to an image, video, or even another vendor JSON media type (preferible not a JSON+API competitor :D).

Then in your client app you can check for the media type returned by the server and see is what your are expecting so you can process it accordingly.

**Comment by steveklabnik** [comment]
Links can point anywhere, including to a non-JSON API document.

I'm guessing that in the common case, you _will_ want them to, but it's not strictly required.
