### ISSUE TITLE
How to model user friendships?

### ISSUE THREAD

**Issue by timothyfisherdev** [json-api/json-api#1501]
I'm trying to model a user friendship system with the JSON API. Put simply, a user can send another user a friend request and the user can accept or decline the request.

The only resource evident here is `users` and it has a self-referencing to-many relationship back to `users`. So I could make a `POST` request to `/api/users/{user}/relationships/users`, where `{user}` is the person sending the friend request. This initially works great as I can create a pivot table record from this and set the status to `pending` on the server. However, there's also a couple of problems I run into:

- **First:** According to the spec I have to allow multiple resources to be in the to-many `POST` request in a single request since the data key has to be an array. This would be bulk friend requesting:

```
// POST to api/users/1/relationships/users
{
  "data": [
    { "type": "users", "id": "2" },
    { "type": "users", "id": "3" }, 
  ]
}
```

What if I wanted to only allow one user per request? Could I change the last segment of the URI to be singular `api/users/{user}/relationships/user` or would that go against the spec? Or should this be something I restrict on the server and only take the first item of the object that comes through?

- **Second:** There's the issue of updating the status of the friendship. Where the person who updates it has to be the recipient of the request. So my initial thought is a `PATCH` request to the same URI but where `{user}` is the recipient's ID. But, looking more closely it looks like `PATCH` is only to be used for full replacements in to-many relationships. So I was thinking of just making another `POST` request to the same URI where `{user}` is again the recipient's ID. Going with the example from above user 2 is accepting the request from user 1:

```
// POST to /api/users/2/relationships/users
{
  "data": [
    { "type": "users", "id": "1", "meta": { "action": "accept" } }
  ]
}
```

Overall does it seem like I'm on the right track or am I missing something?

**Comment by Doqnach** [comment]
> Primary data MUST be either:
> 
> * a single resource object, a single resource identifier object, or null, for requests that target single resources
> * an array of resource objects, an array of resource identifier objects, or an empty array ([]), for requests that target resource collections

So there is no harm into using a singular `data` object?

**Comment by timothyfisherdev** [comment]
The part of the spec I was going off was this:

> Updating To-Many Relationships
> 
> A server MUST respond to PATCH, POST, and DELETE requests to a URL from a to-many relationship link as described below.
> 
> For all request types, the body MUST contain a data member whose value is an empty array or an array of resource identifier objects.
> 
> If a client makes a PATCH request to a URL from a to-many relationship link, the server MUST either completely replace every member of the relationship, return an appropriate error response if some resources can not be found or accessed, or return a 403 Forbidden response if complete replacement is not allowed by the server.

**Comment by Doqnach** [comment]
I think using the relationship link with a meta object containing details on the operation is not a great choice. I would rather expect the 'friend request' to go into some queue with some unique identifier, and the recipient user being able to call some other endpoint with that unique identifier to accept.

I think your server-side may demand an array-size of 1 without going against the spec?

Also: `// POST to /api/users/2/relationships/users` I would probably go with `// POST to /api/users/2/relationships/friendships` since 'friendships' actually describes what the relationship is. 'users' is not very descriptive here.

**Comment by freddrake** [comment]
This is really an application question rather than a question about JSON:API itself.

@gabesullice: This issue should be closed.

**Comment by dgeb** [comment]
In this specific case, I would consider modeling the "friendship" as a resource unto itself. This resource might have attributes such as status, timestamps, etc. and relationships to each user. 

In general, please post issues about application-specific spec usage at https://discuss.jsonapi.org. We try to reserve the GitHub repo for discussion about the spec itself.
