### ISSUE TITLE
top-level links for collection question

### ISSUE THREAD

**Issue by freddrake** [json-api/json-api#1502]
I want to be sure I understand how top-level links should be generated for a request for a collection.

My current understanding:
* the **self** link *should not* include query parameters related to pagination, filtering, sorting, sparse field sets, or compound documents.
* the pagination links *should* include generated parameters for pagination, and pass along parameters for filtering, sorting, sparse field sets and compound documents as received.

Does this correspond with the intent of the specification authors?  Or is the client responsible for mixing in parameters related to any of those aspects for pagination links?

**Comment by dgeb** [comment]
The `self` link at the top-level should include whatever params are needed to return an identical result. Top-level `self` should be considered a link to the current document. So if the current document contains a collection that is filtered or paginated, those params should be included in the `self` link.

Similarly, paginated links (`next`, `prev`, etc.) should step through the _current_ collection and thus should also include whatever params are present on `self`.

**Comment by freddrake** [comment]
Thanks, @dgeb!  This is very helpful.

Was this covered in the specification in some way that I missed, or will clarifications be added (at least for 1.1)?

**Comment by dgeb** [comment]
Glad to help! I'll reopen so we can review / discuss if clarification is needed in the spec.

**Comment by freddrake** [comment]
Reviewing the 1.0 spec, the description of the top-level self link here:

> https://jsonapi.org/format/#document-links

does not spell out that the link refers specifically to the *document*, and should be constructed to reproduce the current rendering.  The [Top Level](https://jsonapi.org/format/#document-top-level) section does indicate the self link is for the generated response; perhaps that should be considered sufficient, though this portion of the spec doesn't include the exact term "self link", which does yield the other description of the top-level self link.

Perhaps the difficulty is that the top-level self link is described in two places?

**Comment by freddrake** [comment]
Two months and no response to my analysis?

@dgeb, when you reopened for discussion, I was hoping not to be talking to myself.

**Comment by dgeb** [comment]
@freddrake in 1.1 isn't the top-level `self` link only specifically described in https://jsonapi.org/format/1.1/#document-top-level ? That looks pretty accurate and sufficient imo.

I'm not clear how it contradicts any of the general language about `links` contained in https://jsonapi.org/format/1.1/#document-links

**Comment by freddrake** [comment]
@dgeb: I don't think there's a contradiction.  The problem I was trying to point out is that it's fairly difficult to be sure how these things need to be handled in an implementation.  To some degree, that's inherent in interpreting a specification, but... JSON:API isn't exactly a complicated spec.

Part of the difficulty may be mine rather than a fault in the specification.  I want to think of resources, collections, and relationships as being "equal citizens", but the specification doesn't actually suggest that at all.

**Comment by jelhan** [comment]
I just reviewed v1.1 and it seems to be clear to me.

- The meaning of top-level `self` link is defined in [_Top Level_](https://jsonapi.org/format/1.1/#document-top-level) chapter. It explicitly states that it must be "the link that generated the current response document". I think the additional clarification for profiles and extensions makes that even more clear.
  > self: the link that generated the current response document. If a document has extensions or profiles applied to it, this link SHOULD be represented by a link object with the type target attribute specifying the JSON:API media type with all applicable parameters.
- The [_Links_](https://jsonapi.org/format/1.1/#document-links) chapter points back to the different places, in which a links object may be used.
  > A link’s context is the top-level object, resource object, or relationship object in which it appears.

**Comment by jelhan** [comment]
Let's maybe better wait until #1604 lands. Reopening for now.

**Comment by jelhan** [comment]
#1604 has been merged.
