### ISSUE TITLE
Add examples for instance-as-list-of-one case

### ISSUE THREAD

**Issue by kevinburke** [json-api/json-api#151]
The statement:

> Singular resources are represented as JSON objects. However, they are still wrapped inside an array - this simplifies processing, as you can know that a resource key will always be a list.

Contains a lot of wisdom but it's not obvious at first glance. Some examples would be handy here, to sell people that this is a good idea, if they're on the fence on implementing this

**Comment by dgeb** [comment]
As of #237, there is now a [distinction between singular and plural resource representations](http://jsonapi.org/format/#document-structure-resource-representations).

This still carries the advantage of using a common "resource type" as the key, regardless of whether it is singular or plural. However, as described in #237, it also has the following advantages:

> This allows for symmetrical representations in request and response documents, as well as PUT/POST requests and PATCH operations. It also simplifies implementations which do not support batch operations (i.e. they can allow an object and not an array).
