### ISSUE TITLE
geo-json API extention for 1.1?

### ISSUE THREAD

**Issue by auvipy** [json-api/json-api#1518]

**Comment by jelhan** [comment]
I'm sorry for the late feedback on this proposal. It would be great if you could elaborate which kind of support you are missing from the specification. Is it preventing you from using GEO JSON as attribute values?

**Comment by auvipy** [comment]
I actually don't how how to use geojson as part of json:api schema, any example would be great. for instance https://github.com/openwisp/django-rest-framework-gis this library provide GIS REST API for django gis module, & this https://github.com/django-json-api/django-rest-framework-json-api provide JSON:API 1.0 specs. is there built in specs for handling geojson data with json:api 1.1 specs?

**Comment by jelhan** [comment]
I don't have much experience with GeoJSON to be honest. I had a brief look into [RFC 7946](https://datatracker.ietf.org/doc/html/rfc7946) if anything stands out, which may prevent a GeoJSON object to be used as attributes value. I haven't noticed anything.

The GeoJSON RFC [includes an example](https://datatracker.ietf.org/doc/html/rfc7946#section-1.5). That example seems to be a valid attribute value in a JSON:API document. It may look like this:

```json5
{
  "data": {
    "type": "geometrical-shape",
    "id": "4050aa98-55e0-46d5-9fc1-16dde56faf53",
    "attributes": {
      "shape":
        // the GeoJSON object given as example in the RFC
        // used as value of "shape" attribute
        {
          "type": "FeatureCollection",
          "features": [
            {
              "type": "Feature",
              "geometry": {
                "type": "Point",
                "coordinates": [102, 0.5]
              },
              "properties": {
                "prop0": "value0"
              }
            },
            {
              "type": "Feature",
              "geometry": {
                "type": "LineString",
                "coordinates": [
                  [102, 0],
                  [103, 1],
                  [104, 0],
                  [105, 1]
                ]
              },
              "properties": {
                "prop0": "value0",
                "prop1": 0
              }
            },
            {
              "type": "Feature",
              "geometry": {
                "type": "Polygon",
                "coordinates": [
                  [
                    [100, 0],
                    [101, 0],
                    [101, 1],
                    [100, 1],
                    [100, 0]
                  ]
                ]
              },
              "properties": {
                "prop0": "value0",
                "prop1": {
                  "this": "that"
                }
              }
            }
          ]
        }
    }
  }
}
```

**Comment by auvipy** [comment]
thanks a lot!

**Comment by jelhan** [comment]
I'm glad that I was able to help. Going to close the issue as the question seems to be resolved. Please speak up if I missed something.
