### ISSUE TITLE
Specification does not link to a specific definition of "URL"

### ISSUE THREAD

**Issue by freddrake** [json-api/json-api#1519]
This leaves it ambiguous whether relative URLs should be considered acceptable in the various places they're used within `links` structures.

**Comment by dgeb** [comment]
In v1.1, we do specify that `href` for link objects should be "a string whose value is a URI-reference [RFC3986 Section 4.1] pointing to the link’s target". See https://jsonapi.org/format/1.1/#auto-id--link-objects

Does that remove the ambiguity sufficiently?

**Comment by freddrake** [comment]
Thanks, @dgeb!  Yes, that's good enough for me.
