### ISSUE TITLE
How should related link from empty to-one relationship respond?

### ISSUE THREAD

**Issue by freddrake** [json-api/json-api#1520]
For a resource with an empty to-one relationship to another resource, the serialization of the of the relationship can include ``data: null``, but how should the ``related`` link for the relationship be handled?

Both version 1.0 and the current 1.1 draft of the spec state:

> Additionally, a related resource link MUST NOT change because its relationship’s content changes.

When a mutable to-one relationship is empty, should the ``related`` simply be omitted from the response?  If the client has previously retrieved the resource when the relationship is non-empty and already has the ``related`` link, they might still attempt to load the resource; should the service respond to a request for an empty ``related`` link with a 404 response containing an error object?

**Comment by freddrake** [comment]
I had hoped this question would be reasonably straightforward; the behavior of the link for such a relationship seems very relevant to the specification, given the cited constraint.

**Comment by prathe** [comment]
@freddrake Your related links should be contextual. Consumers who already have the link will be able to know about the resources which the relationship points to when it changes. For example the related link for John beloved one should be more like `/people?filter=beloved.name eq "John"` and not `/people/Claudia`. Both today returns [Claudia] and Claudia. But tomorrow a consumer may not notice John have no more beloved one if he has the `/people/Claudia` URL.

You can use your existing collection endpoint for this.

**Comment by freddrake** [comment]
@prathe: Thank you for responding!

Unfortunately, I'm not sure I understand any better.

Your example link suggests a search of a collection, resulting in a response with a list of results as the primary data.  Since my original question is specifically about to-one relationships, I don't think that actually makes sense.

The specification suggests (though does not mandate) related links having a form that combines the URL path of the source resource and the relationship's field name:

> /people/{id}/beloved

When the relationship is non-empty, I expect returning a 307 Temporary Redirect or 308 Permanent Redirect from that URL is appropriate (depending on whether the relationship itself is mutable), where the target of the redirect is the resource at the "other end" of the relationship.

However, if the relationship is empty, there's no appropriate destination for a redirect.  Returning a 404 Not Found doesn't seem entirely wrong, but it seems strange to use that for something that could come & go.

**Comment by prathe** [comment]
@freddrake Ok I see that you are using a contextual URL and understand your reasoning. Sorry for that.

Regarding the way to do it, isn't the documentation already [talking about it](https://jsonapi.org/format/#fetching-resources)?

Let me paste only the parts that refers to it:

> ## Fetching Resources
>
> A server MUST support fetching resource data for every URL provided as:
>
> ...
>
> * a related link as part of a relationship-level links object
>
> ...
>
> And the following request fetches an article’s author:
>
> ```
> GET /articles/1/author HTTP/1.1
> Accept: application/vnd.api+json
> ```
>
> ...
>
> A server MUST respond to a successful request to fetch an individual resource with a resource object or null provided as the response document’s primary data.
>
> null is only an appropriate response when the requested URL is one that might correspond to a single resource, but doesn’t currently.
>
> If the above article’s author is missing, then a GET request to that related resource would return:
>
> ```
> HTTP/1.1 200 OK
> Content-Type: application/vnd.api+json
>
> {
>   "links": {
>     "self": "http://example.com/articles/1/author"
>   },
>   "data": null
> }
> ```

So redirecting or returning 404 may not be optimal.

You are right, I should not have returned an array of one for a to-one, but using the authors resource URL to return the contextual author would certainly makes sense.

**Comment by freddrake** [comment]
@prathe: Thank you for pointing that out!  I'd not understood that correctly at all.

This makes a lot of sense.
