### ISSUE TITLE
Missing step in definition of `relationships`

### ISSUE THREAD

**Issue by chrylis** [json-api/json-api#1521]
In both 1.0 and the draft 1.1, the *Relationships* section says:

> The value of the `relationships` key **MUST** be an object (a “relationships object”).

So far, so good; there should be an object listing some relationships. However, the spec then goes on to define the contents of _a relationship_ (not relationships) object, without specifying the relation between the two levels in the hierarchy.

In particular, the spec should define the allowable "relationships object". Presumably the keys are the name of the relationship. Are the values of mixed cardinality? A single "relationship object"? What is the allowable way to handle to-many relationships?

The example document provided, under `relationships.tags`, has a single-valued "relationship object" where the resource linkage is multi-valued, but a "link object" is not permitted to have multi-valued hrefs or equivalent, so is there really an asymmetry built into the spec such that "relationship as link" may only be single-valued but "relationship as data" may be multi-valued?

**Comment by freddrake** [comment]
More clarity could certainly be added in sentence following the one you quote:

> Members of the relationships object (“relationships”) represent references from the resource object in which it’s defined to other resource objects.

There is a note pointing to the [Fields](https://jsonapi.org/format/1.1/#document-resource-object-fields) and [Member Names](https://jsonapi.org/format/1.1/#document-member-names) sections, which are helpful in clarifying the naming of properties in the *relationships object*.

An explicit statement that the value of each property in the *relationships object* is a *relationship object* would probably be sufficient.  Would this have helped?

The first example in [Compound Documents](https://jsonapi.org/format/1.1/#document-compound-documents) shows a to-many relationship for the `comments` field.

**Comment by jelhan** [comment]
Thanks a lot for reporting. This is addressed in #1608.

**Comment by dgeb** [comment]
Closed via #1608. Thanks @jelhan!
