### ISSUE TITLE
Custom Middleware

### ISSUE THREAD

**Issue by PawelTomkow** [json-api/json-api#1537]
Hello,

Is it possible to add custom middleware (handling errors, prefer then filters) or create abstract for it? Also possible to add sub-middleware or change pipline of .net core request. 
MS pattern: https://docs.microsoft.com/en-gb/aspnet/core/fundamentals/middleware/?view=aspnetcore-5.0

BR,
Pawel

**Comment by Doqnach** [comment]
Hey Pawel,

This repository is for the specification, and not any specific implementation.

Please check https://jsonapi.org/implementations/#client-libraries-net for a specific implementation you are using (or want to use). The documentation of their respective project should provide you this information, or at the very least you can ask your questions at their project instead.

Good luck!
