### ISSUE TITLE
Content-Type is overridden by json object

### ISSUE THREAD

**Issue by alucardu** [json-api/json-api#1538]
I have a Axios interceptor to change the data of a POST request:

```
export default function ({ $axios }) {
  $axios.interceptors.request.use((req) => {
    console.log('req: ', req)
    req.data = {
      data: {
        type: 'user',
        attributes: {
          vendor: 'Facebook',
          code: '**'
        }
      }
    }
    return req
  })

  $axios.setHeader('Accept', 'application/vnd.api+json', [
    'post'
  ])
  $axios.setHeader('Content-Type', 'application/vnd.api+json', [
    'post'
  ])
}
```

But using this `req.data` changes to content-type to `application/json;charset=UTF-8` causing the back end to return a `415 (Unsupported Media Type).` 

What's the correct way of formatting a json-api object?

**Comment by freddrake** [comment]
Isn't this a question for the Axios project?

**Comment by alucardu** [comment]
I think the issue is that:

    req.data = {
      data: {
        type: 'user',
        attributes: {
          vendor: 'Facebook',
          code: '**'
        }
      }
    }
    
is an json object, forcing the content-type to change. So I'm wondering if there's a correct way to format or change this data object so the content-type header doesn't get changed.

**Comment by freddrake** [comment]
That still sounds like a question about how Axios should be used.

Looking at what our front-end developer is doing, it looks like Axios get / post / etc methods take a configuration object as an additional argument (2nd arg for get, 3rd for post, patch), and that should allow you to specify headers:

~~~~~~~ js
resp = axios.post('/link/goes/here', jsonapi_payload, {
    headers: { 'Content-Type': 'application/vnd.api+json' }
});
~~~~~~~

I'm not an Axios expert, but it looks like something like that should work.

**Comment by alucardu** [comment]
Looks like you're correct and this is an Axios issue: https://github.com/axios/axios/issues/340. My apologies.

**Comment by dgeb** [comment]
No worries, @alucardu. Looks like that Axios issue you found has a decent resolution so I'm going to close this now.
