### ISSUE TITLE
Why are "linked" documents represented as arrays?

### ISSUE THREAD

**Issue by jcallaha** [json-api/json-api#154]
I understand why the "primary document" is represented as an array, but why are the related documents under "linked" also represented as an array instead of an object with the keys being the "id" attribute of the related documents?

It strikes me unlike the primary document which is likely to be iterated over, the "linked" documents are only iterated over in the context of the fields in the primary document.

For example, take a "group" which has several relationships to "people" (members, admins, pendingMembers, etc)

```
GET /groups/1?include=members,admins
```

``` json
{
  "groups": [ {"id":1,...,"links":{"members": [1,2,3,...,100],"banned":[86,42],"admins":[13013]} } ],
  "linked": { "people": [ {"id":1, ... }, {"id":2,...}, ...] }
}
```

The spec already requires that every document MUST have an "id" and that in the case of the compound documents that no record be duplicated per document type, yet at this point if the client wants to access attributes of the members of the group (which are in the primary document by their "id") it would have to iterate over the "people" array and match the "id" field against the members array.  It might as well just build its own object / hash using the key -- why not save the client the extra step?

**Comment by mattupstate** [comment]
Every document SHOULD have an "id" attribute now. However, I'm curious what the case would be if the document does not have an "id".

**Comment by dgeb** [comment]
@mattupstate You're correct - there is no longer a MUST requirement for ids, so this suggestion isn't feasible any more.

@jcallaha Thanks for raising this - feel free to jump into the related discussion re: arrays vs objects in #176
