### ISSUE TITLE
Update MUST 409 clause should be OR rather than AND

### ISSUE THREAD

**Issue by Relequestual** [json-api/json-api#1549]
> A server MUST return 409 Conflict when processing a PATCH request in which the resource object’s type **and** id do not match the server’s endpoint.
https://jsonapi.org/format/1.1/#crud-updating-responses-409

This should read...

> A server MUST return 409 Conflict when processing a PATCH request in which the resource object’s type **or** id do not match the server’s endpoint.

Otherwise, the implication reads as only if both are true must you return a 409, whereas I expect the intent is if either are true, you must return a 409.

**Comment by jelhan** [comment]
Thanks a lot for reporting. I implemented your proposed solution in  #1621.

**Comment by jonatanlr98** [comment]
PATCH /articles/1 HTTP/1.1 Content-Type: application/vnd.api+json Accept: application/vnd.api+json { "data": { "type": "articles", "id": "1", "relationships": { "tags": { "data": [ { "type": "tags", "id": "2" }, { "type": "tags", "id": "3" } ] } } } }

**Comment by jonatanlr98** [comment]
PATCH /articles/1 HTTP/1.1 Content-Type: application/vnd.api+json Accept: application/vnd.api+json { "data": { "type": "articles", "id": "1", "relationships": { "tags": { "data": [ { "type": "tags", "id": "2" }, { "type": "tags", "id": "3" } ] } } } }
