### ISSUE TITLE
A new Ruby implementation of the JSON:API specification!

### ISSUE THREAD

**Issue by joshdemoss** [json-api/json-api#1550]
Hi, a new implementation of the JSON:API spec, called [easy-jsonapi](https://github.com/Curatess/easy-jsonapi), was just released. It is a rack-based, lightweight middleware, parser, and response validator with comprehensive error checking that can be used on any rack app (plain ruby, rails, sinatra). Here is a link to the [repo](https://github.com/Curatess/easy-jsonapi) for more information.

**Comment by joshdemoss** [comment]
Is there something that I can do to expedite recognizing this gem as a Ruby implementation? Please let me know. I am happy to help!

**Comment by jelhan** [comment]
Hello Joschua,

Thanks a lot for working on an implementation of JSON:API specification!

The normal procedure to update the list of implementations on https://jsonapi.org/implementations/ is opening a merge request. You can find the list of implementations in `implementations/index.md` file in this repository. There is a tone of example merge requests, which add new implementations. The newest one, which got merged, is this one: #1586 

Best
Jeldrik

**Comment by jelhan** [comment]
Closing this issue as stale. If implementation is still actively developed, please create a PR adding it to implementation page.
