### ISSUE TITLE
question about link "type" member

### ISSUE THREAD

**Issue by freddrake** [json-api/json-api#1552]
In JSON:API 1.1, the link object grows a lot of optional members.  For example, `hreflang` can specify a number of languages that a resource is available in, and allows the client & server to use the content negotiation to determine which variant will be delivered.

Unfortunately, the `type` member (referring to Content-Type) supports only a single value.  This is also a field where general recommendations for REST APIs suggest content negotiation be applied, so it seems that allowing a list of media types here would be appropriate.

Is there a reason this was not done?

**Comment by freddrake** [comment]
I understand the maintainers are busy, and maintaining the JSON:API specification is unlikely a primary goal, but the dearth of responses to presumably simple questions leads me to believe JSON:API (as a specification; not particular implementations) is approaching abandonware.

**Comment by gabesullice** [comment]
> Is there a reason this was not done?

Yes, we tried to be as consistent when ongoing link standardization efforts as we could while remaining backward-compatible with version 1. Specifically, `type` as a single value member is consistent with [web linking standards](https://datatracker.ietf.org/doc/html/rfc8288#section-3.4.1) and with [contemporary work](https://datatracker.ietf.org/doc/html/draft-ietf-httpapi-linkset-03#section-4.2.4.1) in the IETF.
