### ISSUE TITLE
Spec constraints entities attributes

### ISSUE THREAD

**Issue by Relequestual** [json-api/json-api#1553]
I'm creating an updated JSON Schema for the 1.0 spec, and re-read this section of the spec, which is similar / the same in v1.1 in relation to `attributes`...

> Complex data structures involving JSON objects and arrays are allowed as attribute values. However, any object that constitutes or is contained in an attribute **MUST NOT contain a `relationships` or `links` member, as those members are reserved by this specification for future use.**

Bluntly, this is wrong. It's unreasonable to place constraints on the attributes of entities that you have no control over.

Say, for example, my system represents patient data, and those patients have relationships which I express in an object under a `relationships` key. According to the spec, that entity can't be legally represented in the JSON:API spec format.

> reserved by this specification for future use

Making use of or applying semantics to specific attributes in data you have no control over, is asking for trouble.

Could someone please explain to me the motivation behind this specific section and language, please?

**Comment by jelhan** [comment]
It was added as #653 without further explaining or discussing that limitation. I fully agree that the specification should be agnostic about the value of an attribute.

**Comment by jelhan** [comment]
The constraints has been removed in #1630. v1.1 will be agnostic about attribute values and do not put any limitations on them. 🎉
