### ISSUE TITLE
JSON Schema for JSON:API v1.0 is incomplete or broken

### ISSUE THREAD

**Issue by Relequestual** [json-api/json-api#1554]
Hi all. I promised to work on this, so here goes!

The `schema` file in the root of this repo is a little lacking and in some cases inaccurate.
I feel like what makes the most sense here is to make a draft PR and then talk about the changes I've made and why.

I've not fully tested it, but it should be more than enough to get discussions going!

PR to follow!

**Comment by Relequestual** [comment]
PR created.
I'll look to fully explain it next week!
Please ping me on Twitter if for some reason that hasn't happened!

**Comment by bradjones1** [comment]
https://github.com/json-api/json-api/pull/1600 is a continuation of the work initiated on #1555. It includes test fixtures, as well.

To assist with discovery/SEO for those who are tripped up by this, I ran into this issue validating json:api objects against the schema, and ajv reported `unknown format` for `uuid`, `uri-reference`, and `date`, some of which are only present in `json-schema` [> Drafts 6](https://json-schema.org/understanding-json-schema/reference/string.html#built-in-formats). The schema format for the shipped/public json:api schema is Draft 6.

**Comment by auvipy** [comment]
And for v1.1 i believe the latest should be used > Drafts 7
