### ISSUE TITLE
included vs relationships

### ISSUE THREAD

**Issue by paul-uz** [json-api/json-api#1558]
The documentation, not-surprisingly, is terrrible at given a clear description and example.

I am confused over the usage of `included` and `relationships`

Should I use the `include=foo` query parameter to say what if all of a resources `foo` relationships should be show in the `relationships` object? Or are they added to `included`?

Or do I use both?

**Comment by jelhan** [comment]
I think for this kind of questions are better asked in [discussion forum](https://discuss.jsonapi.org/). To summarize quickly:

`include` query parameter allows a client to request, which related resources should be included. See [inclusion of related resources](https://jsonapi.org/format/1.1/#fetching-includes) for details.

Every included resources must be referenced directly or indirectly by primary data. Therefore [resource linkage](https://jsonapi.org/format/1.1/#document-resource-object-linkage) must be used in a [compound document](https://jsonapi.org/format/1.1/#document-compound-documents).

The server is free to provide resource linkage even if the related resources are not included. The server is free to include related resources unless client provides `include` query parameter.
