### ISSUE TITLE
Multiple URI templates per resource type

### ISSUE THREAD

**Issue by rkh** [json-api/json-api#156]
How do I use multiple URI templates per resource type?

Image you are building the API for a CI system to be used with GitHub. You might implement two different endpoints for fetching infos about a repository: `/repos/{repositories.id}` and `/repos/{repositories.owner_name}/{repositories.name}`.

However, the links section only allows to list one URI template per type (and URI templates do not support unions of different patterns.

**Comment by rkh** [comment]
Any input on this?

**Comment by wycats** [comment]
@rkh are you still trying to use JSON API or did you move on?

**Comment by wycats** [comment]
One approach here would be to allow an array of templates for a resource, with the first one considered canonical (or preferred). @rkh does that satisfy your requirements?

**Comment by rkh** [comment]
> One approach here would be to allow an array of templates for a resource, with the first one considered canonical (or preferred). @rkh does that satisfy your requirements?

It would.

> @rkh are you still trying to use JSON API or did you move on?

I have an incomplete json-api implementation for travis, but I have not put a lot of work into it lately.

**Comment by ethanresnick** [comment]
Hey guys, I know this is an old issue, but some of the same questions seem to be coming up in #276 so I wanted to revisit it. @rkh, could you clarify why you wanted to communicate both of those endpoints to the client in the first place? I.e. it makes sense to me that both endpoints might exist (and both could be documented) but wouldn't it be sufficient for _the json api client_ to know about just one?

**Comment by lgebhardt** [comment]
One reason I can see is that the url could be too long if a large set of ids were returned, especially if the ids are UUIDs. The 2000 character limit would be chewed up very quickly (62 related records would do it), so providing an alternate url template would make sense. I don't think that was the original issue here, but it is something I have been thinking about recently. Of course it would make sense to avoid long lists of ids to begin with, so you could probably just get away without the id based one.

**Comment by rkh** [comment]
Assuming you can have URI templates that need additional user input to be
fully expanded, we would like to be able to allow using for instance a slug
or an id in a generic client to look up a repository. We could only supply
the ID based payloads, since this is how you probably navigate links once
you did the initial slug to id resolution. Not sure I'm making sense here,
but my goal is to get rid of hard-coded links in our CLI, and as it is we
will have to add other means of communication URI templates to support
different, slug based entry points into the API.

This also seems hard to automate. I have been playing with the idea of
generating links from the URL patterns we use. However, both Sinatra's and
Rails' URL pattern syntax is more powerful than URI templates, supporting
unions and optional sections. I have gotten
https://github.com/rkh/mustermann to generate URI templates from arbitrary
URL patterns for a lot of different pattern types, but it has to map
certain patterns onto multiple templates.

**Comment by dgeb** [comment]
As of #341 (RC2), explicit URI template support has been removed from the spec.
