### ISSUE TITLE
What does the spec say about a response with only a true/false value?

### ISSUE THREAD

**Issue by XO39** [json-api/json-api#1568]
We are redesigning one of our APIs that has a lot of requests to check only for true or false, we chose the JSON:API specs for the this api, we couldn't find anything in the specs about (true/false)-only values!

Our API looks like this:

```
/space/isVacant  ------> response is true or false
/connection/isActive --> response is true or false
/wheather/isRaining ---> response is true or false
```

The response usually is like this:
```json
{"isVacant": true}
{"isActive": false}
{"isRaining": true}
```
According to the specs: 
> A JSON object MUST be at the root of every JSON:API request and response containing data. This object defines a document’s “top level”.
>
> A document MUST contain at least one of the following top-level members:
>
> data: the document’s “primary data”
errors: an array of error objects
meta: a meta object that contains non-standard meta-information.

And:

> Primary data MUST be either:
>
> a single resource object, a single resource identifier object, or null, for requests that target single resources
an array of resource objects, an array of resource identifier objects, or an empty array ([]), for requests that target resource collections

And:

> “Resource objects” appear in a JSON:API document to represent resources.
> 
> A resource object MUST contain at least the following top-level members:
> 
> - id
> - type

But almost all of the resource don't have id, they are identified by URL only!

What should the response look like? Is any of the following conform to the specs?:

The first:

```js
{
  "meta": {
    "isValid": true // or false
  },
  "data": []
}
```

The second:
```js
{
  "data": {
    "isValid": true // or false
    // And what about the id and type?
  }
}
```

The third:
```js
// When true
{
  "data": {
    "isValid": true
    // Again, what about the id and type?
  }
}

// When false
{
  "error": {
    "isValid": false
    // And again, what about the id and type?
  }
}
```

Any ideas?

Thanks!

**Comment by ozgg** [comment]
I have similar situation and I think the following structure (which I use) conforms the specification:

```json
{
  "meta": {
      "isVacant": true
  }
}
```

**Comment by jelhan** [comment]
I'm not fully sure if I understand the use case. It seems as if you are requesting a single attribute of a resource. E.g. your example `/space/isVacant` endpoint, seems to return the `isVacant` attribute of a `space` resource. Why aren't you using [Sparse Fieldsets](https://jsonapi.org/format/#fetching-sparse-fieldsets) instead?

Assuming you have a `space` resource with many attributes, you could request a sparse fieldset only including the `isVacant` attribute like this:

```http
GET /space?fields[space]=isVacant
Content-Type: application/vnd.api+json

{
  "data": {
    "type": "space",
    "id": "ced63b22-0a7b-47a1-8280-9712b94ba904",
    "attributes": {
      "isVacant": true
    }
  }
}
```

Doing so also a consumer to request multiple attributes in a single request:

```http
GET /connection?fields[connection]=isActive,isStable
Content-Type: application/vnd.api+json

{
  "data": {
    "type": "connection",
    "id": "94d2c807-f3e2-4c58-82d0-3ee1023f6a24",
    "attributes": {
      "isActive": true,
      "isStable": false
    }
  }
}
```

> But almost all of the resource don't have id, they are identified by URL only!

If a resource is identified by its URL, you could use that (or an UUID v5 derived from the URL) as the `id` value.
