### ISSUE TITLE
JSON-LD Context

### ISSUE THREAD

**Issue by davidbarratt** [json-api/json-api#1572]
I was wondering if you would be willing to provide a JSON-LD context for JSON API?

I took a stab at writing one, it seems to work well in either direction:
https://gist.github.com/davidbarratt/893d7a17a39acbb9644c05f3376a5a31

**Comment by jelhan** [comment]
Hello David,

Thanks a lot for opening this issue and even providing a first draft!

To be honest I'm not fully sure if I understand the use case. Why would one use this LD context? A request or response should be identified as JSON:API by the `application/vnd.api+json` media type presented in `Content-Type` header. Would appreciate if you could help me to understand this better.

Best Jeldrik

**Comment by jelhan** [comment]
Closing this issue due to missing feedback. Feel free to reopen or comment if you have any new input.
