### ISSUE TITLE
Relations with arguments

### ISSUE THREAD

**Issue by rkh** [json-api/json-api#158]
Are relations with arguments supported? The spec doesn't say anything about it and it feels a bit like cheating, but would something like this be valid:

``` json
{
  "repositories": [{
    "id": 1,
    "name": "json-api",
    "links": {
      "branch": "https://api.travis-ci.org/repos/1/branches/{branches.name}",
      "branches": "https://api.travis-ci.org/repos/1/branches"
    }
  }]
}
```

Or this:

``` json
{
  "links": {
    "repositories.branch": "https://api.travis-ci.org/repos/{repositories.id}/branches/{branches.name}",
    "repositories.branches": "https://api.travis-ci.org/repos/{repositories.id}/branches"
  },
  "repositories": [{
    "id": 1,
    "name": "json-api",
  }]
}
```

Are both of these valid JSON API replies with general purpose clients being able to resolve both the branches and the branch link? Is the plural/singular usage correct here?

**Comment by rkh** [comment]
The plural/singular naming in this case is a hack to circumvent #156.

**Comment by rkh** [comment]
Another question relating this: If arguments are supported, how do you name arguments that do not correspond to a field in any of the documents? Simply not use a prefix?

For instance, a list of caches in our API can be filtered with the `match` parameter. This is important for allowing batch operations to be performed on these (like, for all branches, delete all caches for JRuby).

``` json
{
  "links": {
    "repositories.caches": "https://api.travis-ci.org/repos/{repositories.id}/caches{?match}",
    "branches.caches": "https://api.travis-ci.org/repos/{repositories.id}/caches/{branches.name}{?match}"
  }
}
```

**Comment by dgeb** [comment]
I don't see that relations with arguments are explicitly covered by the spec, but both of your original proposals look like the right way to approach this. 

I would make one minor change: the paths in the top level `"links"` should be absolute and not relative. Therefore, I'd change `{branches.name}` to `{repositories.branches.name}`, like so:

``` json
{
  "links": {
    "repositories.branch": "https://api.travis-ci.org/repos/{repositories.id}/branches/{repositories.branches.name}",
    "repositories.branches": "https://api.travis-ci.org/repos/{repositories.id}/branches"
  },
  "repositories": [{
    "id": "1",
    "name": "json-api",
  }]
}
```

Similarly, I don't see an issue with declaring an arbitrary expression like `{?match}` as long as it doesn't interfere with reserved parameters like `fields` or valid paths in the primary or related documents. Of course, the client won't be able to resolve the expression automatically, but that doesn't mean it should be disallowed. It is still a valid URI template after all.

The spec should probably be more explicit about all these issues: declaring arbitrary links, absolute vs. relative paths, and arbitrary expressions in URI templates.

**Comment by BRMatt** [comment]
:+1: It's not always practical to return the ids of all linked resources so this would be a great workaround.

**Comment by steveklabnik** [comment]
By "arguments" do you mean "URI templates?"

**Comment by rkh** [comment]
I mean URI templates with variables that can not be automatically interfered and need to be handed in when expanding the template.

**Comment by dgeb** [comment]
As of #341 (RC2), URI templates are no longer supported. We are considering a post-1.0 optional concept of "templates" that could include templates for whole resources, not just links.
