### ISSUE TITLE
Clarification of PATCH response

### ISSUE THREAD

**Issue by wmike1987** [json-api/json-api#1581]
> A server MUST return a 200 OK status code if an update is successful, the client’s current fields remain up to date, and the server responds only with top-level meta data. In this case the server MUST NOT include a representation of the updated resource(s).

I'm confused by this wording. In particular...

> the client's current fields remain up to date

So like... if the fields they sent to be updated were in fact updated and nothing else was updated?

> And the server responds only with top-level meta data

Confused by this one... I get the server may respond with meta data, but huh? How does this play a role in the... what?

I'm then further confused by how the following paragraph relates to the above-described situation.
> 204 No Content
If an update is successful and the server doesn’t update any fields besides those provided, the server MUST return either a 200 OK status code and response document (as described above) or a 204 No Content status code with no response document.

I understand this paragraph: If _only_ what we specified was successfully updated, return 200 and return the new representation of the entity. Or return a 204 with no document. But how exactly does it relate to the part I'm having trouble understanding?

**Comment by auvipy** [comment]
it is based on version 1.1 spec?

**Comment by wmike1987** [comment]
This language is present in both the 1.0 spec and the 1.1 spec.

**Comment by jelhan** [comment]
I propose to resolve that confusion by removing the last sentence in #1540. Do you think that would help?

**Comment by jelhan** [comment]
This has been clarified in v1.1.
