### ISSUE TITLE
@-members question: treatment in objects nested under attributes?

### ISSUE THREAD

**Issue by freddrake** [json-api/json-api#1584]
Version 1.1 of the specification is clear about the treatment of @-members contained in the JSON:API-defined objects of a document, but it's unclear how they should be handled in objects nested under `attributes` (which are not JSON:API-defined, but are defined entirely by the types of the application.

For example, in this document:

~~~~~~ json
{"data": {
   "type": "person",
   "id": "42",
   "attributes": {
     "@at-thing": "ignore this",
     "address": {
       "@comment": "Would be nice to live here!",
       "street": ["123 Main St.", "Suite 24"],
       "city": "Someplace Warm",
       "state": "CA",
       "postcode": "90120"
   },
   "links": {
     "self": "/api/people/42"
   }
 },
 "links": {
   "self": "/api/people/42?include[person]=address"
 }
}
~~~~~~

the `@at-thing` member should clearly be ignored, but should `@comment` be dropped as non-JSON:API data, or should it be passed along to the application as part of the `address` field?

**Comment by lode** [comment]
Just chiming in here maybe without a clear answer.

What do you mean with 'should clearly be ignored'? As I understand at-members can be added so some consumer of the jsonapi document can use them. Without anyone using them, we can just as well not document their usage.

I would say that middleware that doesn't want to consume the at-members should ignore it where ever it is, but do pass it to a deeper layer which might decide to do something with that data.

But maybe that is a too much simplified way of seeing it? I don't know you use-case.

**Comment by freddrake** [comment]
I'd certainly agree that middleware should ignore-but-pass.

What I'm working on right now is input validation (intended for the server side), which has no need for anything other than the JSON:API content.  For every object defined by the JSON:API specification, I'm pulling out the @-members, validating the rest, and then adding the @-members back in (with those machinations applied because of how the lower-level validation library works).

But the specification is unclear regarding how @-members should be treated down inside the values in `attributes`.

**Comment by jelhan** [comment]
That's a great question. I think it comes down to how the spec treats values of attributes. Should it be agnostic about the value - even if it's an object or an array? Or should it enforce constraints on them?

I would strongly argue that the spec should leave the value of an attribute alone. But sadly it does not:

> Complex data structures involving JSON objects and arrays are allowed as attribute values. However, any object that constitutes or is contained in an attribute MUST NOT contain a relationships or links member, as those members are reserved by this specification for future use.

But I'm still not sure if that means that all constraints for member names should be enforced on objects used as attribute values. @-Members seem to be just a special case.

Wondering if depending on the interpretation adding @-Members may have been a breaking change. 😳

See #1553 for proposal to drop constraints on attribute values entirely.

**Comment by jelhan** [comment]
Related #1367

**Comment by bradjones1** [comment]
I think this could be removed from the 1.1 milestone in preference of https://github.com/json-api/json-api/issues/1367 (specifically, cleaning up the language around what profiles may be able to do in the future with @-member restriction) and possibly adding https://github.com/json-api/json-api/issues/1553 to the 1.1 milestone to drop constraints on attribute values.

**Comment by jelhan** [comment]
I added it to v1.1 milestone because of:

> Wondering if depending on the interpretation adding @-Members may have been a breaking change. 😳

**Comment by dgeb** [comment]
I am closing this with the same [comment](https://github.com/json-api/json-api/issues/1367#issuecomment-1160653576) from #1367:

> Upon reading and re-reading these issues and the current v1.1 section on @ members, it now is clear to me that @ members are fully in the domain of [implementation semantics](https://jsonapi.org/format/1.1/#semantics) rather than specification semantics. As such, their usage can be governed by profiles, but not the base spec or extensions.

Because @ members everywhere are the domain of implementation semantics, the spec can not have an opinion on their usage any more than it can regarding the contents of `meta` objects.
