### ISSUE TITLE
Extraneous 'not' in "Creating, Updating and Deleting Resources" section

### ISSUE THREAD

**Issue by pmcgaley** [json-api/json-api#1587]
Both 1.0 and 1.1 say:

> There are some cases, such as when POSTing to an endpoint representing heterogeneous data, when the `type` could not be inferred from the endpoint.

The point of that paragraph is that even though the type _could_ be inferred, it is nonetheless always required. Therefore the 'not' is incorrect there - it should say "when the `type` could be inferred".

**Comment by cmeeren** [comment]
I find it makes perfect sense as it is. Perhaps it could be joined with the previous sentence and start with "but"; that would clarify the reading I am seeing.

**Comment by cmeeren** [comment]
I find it makes perfect sense as it is. Perhaps it could be joined with the previous sentence and start with "because"; that would clarify the reading I am seeing.

**Comment by pmcgaley** [comment]
I can see your point. I guess it works both ways. Thanks.
