### ISSUE TITLE
Does not implement Web Linking

### ISSUE THREAD

**Issue by rkh** [json-api/json-api#159]
JSON API currently does not implement [Web Linking](http://tools.ietf.org/html/rfc5988). More specific, it does not implement relations according to the RFC.

Judging from a Twitter discussion on Sunday, this might be intentional rather than by accident.

RFC 5988 divides into two kinds of relations types: Registered and extension types. I think the main reason this was not used is because extension types are supposed to be URIs (which are not meant to be dereferenced).

However:

> Note that while extension relation types are required to be URIs, a serialisation of links can specify that they are expressed in another form, as long as they can be converted to URIs.
## Why is this bad?
- The server cannot rely on general purpose clients inferring semantics from well defined, [registered relation types](http://www.iana.org/assignments/link-relations/link-relations.xhtml), like "next". A side effect of this is that a "profile" meta attribute had to be added, which could have otherwise been just a link.
- It is not possible to properly use extension types, making integration with other API standards, like [json-home](http://tools.ietf.org/html/draft-nottingham-json-home-03) a bit more problematic.
### Not fixing this

``` json
{
  "posts": [{
    "id": "1",
    "title": "Rails is Omakase",
    "links": {
      "author": "http://example.com/people/17",
      "comments": "http://example.com/comments/1"
    }
  }]
}
```

You could assume the standpoint that generic implementations of pagination and integration with json-home are not worth it, or not feasible and that a mapping from relation types to JSON API links should happen in the documentation, if at all.
### Fully implementing it

This would probably be the most radical approach and break compatibility with existing implementations.

An example of what this would look like:

``` json
{
  "posts": [{
    "id": "1",
    "title": "Rails is Omakase",
    "links": {
      "author": "http://example.com/people/17",
      "http://example.com/rel/comments": "http://example.com/comments/1"
    }
  }]
}
```

Or with a well defined shorthand (inspired by HAL):

``` json
{
  "links": {
    "curies": {
      "ex": "http://example.com/rel/{rel}",
      "acme": "http://docs.acme.com/relations/{rel}",
    }
  },
  "posts": [{
    "id": "1",
    "title": "Rails is Omakase",
    "links": {
      "author": "http://example.com/people/17",
      "ex:comments": "http://example.com/comments/1"
    }
  }]
}
```

To simplify this, the `:` prefix could be defined as `://{host}/relations/{rel}` implicitly:

``` json
{
  "posts": [{
    "id": "1",
    "title": "Rails is Omakase",
    "links": {
      "author": "http://example.com/people/17",
      ":comments": "http://example.com/comments/1"
    }
  }]
}
```

Even if it wouldn't break compatibility, I'm not sure I would like this approach (and I really mean not sure, not that I don't).
### Making the `rel` attribute part of the spec

Simple, and makes it opt-in.

``` json
{
  "posts": [{
    "id": "1",
    "title": "Rails is Omakase",
    "links": {
      "author": {
        "href": "http://example.com/people/17",
        "rel": "author"
      },
      "comments": {
        "href": "http://example.com/comments/1",
        "rel": "http://example.com/comments/1"
      }
    }
  }]
}
```

This again would work with curies and would also allow choosing to set a relation type on a per link basis:

``` json
{
  "posts": [{
    "id": "1",
    "title": "Rails is Omakase",
    "links": {
      "author": {
        "href": "http://example.com/people/17",
        "rel": "author"
      },
      "comments": "http://example.com/comments/1"
    }
  }]
}
```

I think to be able to use this, it would need to be part of the spec, even though just adding the rel attribute might not violate the current spec. But without it being part of the spec, there would be little to no incentive for library/framework developers to implement this feature.

What I don't like about this approach is that in all the examples I can think of the relation type and the relation name would pretty much be identical (as author is above).
### The implicit `rel` attribute

``` json
{
  "posts": [{
    "id": "1",
    "title": "Rails is Omakase",
    "links": {
      "author": "http://example.com/people/17",
      "comments": "http://example.com/comments/1"
    }
  }]
}
```

This would basically be a hybrid of the above:
- Allow defining curies in the links section.
- Allow adding `rel` attribute explicitly to links.
- If `rel` is not explicitly set and the relation name corresponds to a known relation type, assume the `rel` attribute equals the relation name.
- **Optional:** If the relation name does not correspond to any known relation type, and the `rel` attribute is not explicitly set, assume `://{host}/relations/{rel}` (thus all links would conform with RFC 5988).

The only real downside I can see is that people might accidentally use a relation type that doesn't fit ("Oh, I called it author, even though it doesn't refer to the context's author. Didn't know that was implied"). I feel like that's an acceptable tradeoff if this logic is part of the spec.
## Conclusion

If you think any of this is valid and this issue reaches some consensus, I'd be more than willing to submit a pull request.

**Comment by rkh** [comment]
Any implementation should also assume that the `href` attribute inside a document has the `self` relation type and that documents are the context for link relations.

**Comment by dgeb** [comment]
> - Allow adding rel attribute explicitly to links.
> - If rel is not explicitly set and the relation name corresponds to a known relation type, assume the rel attribute equals the relation name.

I think this approach makes a lot of sense.

On a related note: I've been trying to come up with an approach for using `rel` attributes with related documents in a compound document. For instance, how to paginate a related document type like `comments` when requesting them along with `posts` ?

**Comment by rkh** [comment]
> On a related note: I've been trying to come up with an approach for using rel attributes with related documents in a compound document. For instance, how to paginate a related document type like comments when requesting them along with posts ?

Yes, thinking about exactly this issue (we might include the first 25 builds if you ask for them in a repository payload) made me open #163.

Maybe define a `comments.next` link on the post?

**Comment by rkh** [comment]
Though, thinking about it, it won't be clear that the rel attribute would define the relation between the document that is the list of all the comments and that link rather than the post and that link.

**Comment by steveklabnik** [comment]
Adding for 1.0.

**Comment by rkh** [comment]
What's the status on this?

**Comment by rkh** [comment]
We decided against json-api for now, so this is on longer urgent from our standpoint.

**Comment by kjwierenga** [comment]
I'm curious to know what you decided to use instead of json-api... Care to elaborate?

**Comment by rkh** [comment]
Not finalised, but we are just rolling our own™, with the goal of having it json-ld compatible in the future.

JSON-API seems not to solve (or even address) the issues we're facing while trying to move towards a more consistent API.

We have a somewhat fragmented API in three different scenarios (travis-ci.com, travis-ci.org and Travis Enterprise), which we are going to unify in a single code base. This API will also be used by internal applications.

Main problems we're having with JSON-API:
- Progress seems to be slow (this is not meant to put any blame on anyone, I'm an OSS maintainer myself and can feel your pain). Issues that have been agreed on needing to be addressed are not. We don't feel like waiting for 1.0 anymore.
- Client still needs implicit or explicit knowledge about the API endpoints, given that these differ for us between Enterprise and our normal platform, this is an issue we would like to address. We are addressing it now, but this involves writing our own ember-data adapter, which is not what you'd expect with ember.js being one of the main if not the JSON-API use case.
- JSON-API does not address the concept of multiple representations of the same resource (ie, partially loaded content, attributes only available to certain auth levels). I know this doesn't mean we can't implement these, but if JSON-API does not allow for generic clients, I don't see the value in it.
- JSON-API does not implement proper weblinking and schemas. Our for the entry-point to our API we decided to go with JSON-HOME, which does implement proper weblinking and schema, the same is true for JSON-LD.
- For most endpoints we have two or three corresponding uri-templates (resolve by internal ID, GitHub ID, some name). This is currently not possible to communicate to the client via JSON-API.
- I personally prefer the JSON-LD meta annotations over the JSON-API structure. I think it works better for clients not aware of JSON-API, hypermedia and so on.
- Smaller issues: Lack of built in pagination support, lack of collections having relations, relations with arguments, link generation assumes resources can be identified by a single attribute only, I dislike the linking/unlinking API, a lot of attributes (can the multi-id API be used) cannot be communicated via the API in a canonical way, no standardised error format, etc

These are all the things I would be looking for in a standard.

We want to be a good web citizen with proper hypermedia etc but JSON-API does not seem to get us closer to that goal.

**Comment by dgeb** [comment]
@rkh I am sorry to hear that, although your decision isn't final, you're leaning away from implementing JSON API. I really appreciate the questions and issues you've raised over the last year and your list of problems above, which I will fully consider and review with @wycats and @steveklabnik.

While working for a client together in December, @wycats and I spent several evenings trying to add rigor and simplicity to the spec. We came close but have not yet released the work as a PR. I fully appreciate that you and others have been waiting a long time for 1.0, and I'm sorry for the delays and gaps in communication.

You can review the WIP [in my branch](https://github.com/dgeb/json-api/blob/v1rc2/format/index.md). We've extracted some large chunks of the spec, such as bulk updating and patch support, as optional extensions. I think you'll find many improvements, especially in the thoroughness of link definitions. I'll finish this up and move it to a proper PR by the end of the week to allow for comments and review by everyone interested in the spec.

Just to address one of your points above: although I don't want to speak too much for @wycats, he has expressed the need for JSON API to return as the default spec supported by ember-data (which was its original driving force after all). 

I'll review the rest of your points in detail and see how they coincide with our WIP. Hopefully, we can address enough of your concerns before reaching 1.0.

**Comment by ahacking** [comment]
@rkh, @dgeb as per my previous proposals and conclusions, I think the spec needs to adopt JSON-LD for describing link relations and resource structure. A lot of bike shedding would die away and a simpler yet more powerful spec would result, and one that has broader applicability and interoperability.

**Comment by rkh** [comment]
@ahacking link? :)

**Comment by ahacking** [comment]
@rkh sure, here's a bunch of comments:
- https://github.com/json-api/json-api/issues/310#issuecomment-63249053
- https://github.com/json-api/json-api/issues/310#issuecomment-63303023
- https://github.com/json-api/json-api/issues/310#issuecomment-63812207
- https://github.com/json-api/json-api/issues/310#issuecomment-63826841
- https://github.com/json-api/json-api/issues/311#issuecomment-63395159

I also suggested looking at odata for inspiration as well since its an OASIS standard there is some overlap with json-api:
- https://github.com/json-api/json-api/issues/324#issuecomment-65218199

**Comment by steveklabnik** [comment]
I still feel terrible this issue has been open so long. I believe, after all the stuff that's gone on, this is addressed to the degree it's going to be, and therefore, I'm going to give it a close. Thanks!
