### ISSUE TITLE
1.1 is inconsistent and/or contains erroneous breaking change

### ISSUE THREAD

**Issue by cmeeren** [json-api/json-api#1599]
I assume the parts quoted below are poorly phrased and not an intended breaking change.

In the resource ID section, the 1.1. spec says:

> A “resource identifier object” MUST contain a `type` member. It MUST also contain an `id` member, except when it represents a new resource to be created on the server. In this case, a `lid` member MUST be included that identifies the new resource.

And in the resource creation section:

> A server MAY accept a client-generated ID along with a request to create a resource. An ID MUST be specified with an `id` key

I interpret the first quote to mean that for resource creation, the `lid` key MUST be present, period. In 1.0, this was not the case. The 1.1 spec requiring this is therefore a breaking change, since any API that moves from 1.0 compliance to 1.1 compliance must fail if `lid` is not present. This is not backwards compatible.

Furthermore, the client-generated ID case is confusing. The first snippet seems to require it to be supplied in `lid` instead of `id`.

Some clarification/rephrasing is probably in order.

**Comment by dgeb** [comment]
There is a difference between identification of resource objects vs. resource identifier objects.

Identifying resource objects is covered in [this section](https://jsonapi.org/format/1.1/#document-resource-object-identification). The introductory paragraph clarifies that `lid` is optional:

> As noted above, every resource object MUST contain a type member. Every resource object MUST also contain an id member, except when the resource object originates at the client and represents a new resource to be created on the server. If id is omitted due to this exception, a lid member MAY be included to uniquely identify the resource by type locally within the document. The value of the lid member MUST be identical for every representation of the resource in the document, including resource identifier objects.

The section you reference covers resource identifier objects, not full resource objects. These identifier objects include `type` and either `id` or `lid` to reference a resource, say in a relationship. `lid` might be used for instance to reference an object that has yet to be created on the server that exists elsewhere in the request document.

> Some clarification/rephrasing is probably in order.

I don't doubt this may be true and will re-read these sections with a critical eye. Thanks for your feedback. 

Please close this issue if I've addressed your concern.

**Comment by cmeeren** [comment]
Thank you, I was indeed mistaken regarding resource identifier objects vs. resource objects - sorry about that!
