### ISSUE TITLE
Partial loading

### ISSUE THREAD

**Issue by rkh** [json-api/json-api#160]
I propose making the following logic part of the spec:

If a document is not retrieved from the URI listed in the `href` attribute (or implied by `id`), the client should assume that additional attributes and relationships of this document can be retrieved by dereferencing said URI.

This allows embedding a relevant subset of a document automatically (without the client having to specify `fields` or the server having to support and arbitrary list of `fields`). The same would apply for a collection of resources, say the index for blog posts only containing the summary by default.

**Comment by cdeszaq** [comment]
:+1:  We use this same concept to fill in "summary" information about related resources. It's very useful to be able to have a clear summary representation of a resource, especially for very large resources.

**Comment by steveklabnik** [comment]
The standard way of doing this kind of thing is to have a rel=self. It's a super useful pattern, for sure, but since it's already a thing elsewhere, I'm not sure it explicitly needs to be called out here.
