### ISSUE TITLE
Clarify exception to full linkage requirement and server-initiated sparse fieldsets

### ISSUE THREAD

**Issue by bradjones1** [json-api/json-api#1614]
I'm running into what I think is an unresolved area of ambiguity as it relates to json:api's spec constraints around:

* Full linkage in compound documents, and
* Server-initiated sparse fieldsets.

Full linkage between a response's primary data and included documents is required in all cases, except:

> ...when relationship fields that would otherwise contain linkage data are excluded via [sparse fieldsets](https://jsonapi.org/format/#fetching-sparse-fieldsets).

In the sparse fieldsets section, we learn servers may respond by applying its own sparse fielset rule, in the absence of one being sent in the request query string:

> If a client does not specify the set of [fields](https://jsonapi.org/format/#document-resource-object-fields) for a given resource type, the server MAY send all fields, a subset of fields, or no fields for that resource type.

Does this mean, then, that the server may forego full linkage if it has opted to respond with a subset of fields?

If not, I think we need to add some sort of requirement stating that the obligation to send full linkage cannot be foregone by server-initiated sparse fielsets. (My invented term, but I think we need to call it something for purposes of this discussion.)

**Comment by bradjones1** [comment]
Wondering if it matters at all if there isn't necessarily a full linkage to be had? Let's imagine:

* Primary data document A references user B with a resource linkage.
* Included data document C references user B with a resource linkage.
* User B is not included in the response.

I'm including document C in a server-initiated, unsolicited manner because I anticipate the client would want to know about it, but they do not have a tree of direct linkages to traverse in my data model.

**Comment by jelhan** [comment]
Full linkage requires that every resource in `included` must be related either directly or indirectly with the primary resource. All that linkage information must be included in the JSON:API document itself. An interim resource must not be skipped. This has been clarified in v1.1:

> Every included resource object MUST be identified via a chain of relationships originating in a document’s primary data. This means that compound documents require “full linkage” and that no resource object can be included without a direct or indirect relationship to the document’s primary data.

The only exception are sparse fieldsets:

> The only exception to the full linkage requirement is when relationship fields that would otherwise contain linkage data are excluded via sparse fieldsets.

Spare fieldsets are discussed in the specification as a feature a client can request:

> A client MAY request that an endpoint return only specific fields in the response on a per-type basis by including a fields[TYPE] query parameter.

The specification allows a server to include only a subset of fields by default. But this is not referred to as sparse fieldsets in the specification.

> If a client does not specify the set of fields for a given resource type, the server MAY send all fields, a subset of fields, or no fields for that resource type.

I see that it would be helpful to clarify in full linkage requirement that the only exception is if a client requested a spare fieldset.

**Comment by jelhan** [comment]
I created #1615 to clarify this point. Do you think the clarifications already landed in v1.1 together with #1615 would prevent further confusion?

**Comment by bradjones1** [comment]
> I see that it would be helpful to clarify in full linkage requirement that the only exception is if a client requested a spare fieldset.

> I created https://github.com/json-api/json-api/pull/1615 to clarify this point. Do you think the clarifications already landed in v1.1 together with https://github.com/json-api/json-api/pull/1615 would prevent further confusion?

I think that's helpful and I'd love to see that addition in the spec.

I'll have to think about the best way to handle this in my case, as I am sending related documents but they do not necessarily have a direct chain of relationship in my object model, but the included data I want to send is still pertinent and "related." Just not in a direct sense.

I'm trying hard to make my implementation spec-compliant, even though it's not a public API. For the moment I've included a "computed" field that gets populated on demand with a relationship identifier so as to maintain compliance with the spec, but I don't love it.

**Comment by jelhan** [comment]
> I'll have to think about the best way to handle this in my case, as I am sending related documents but they do not necessarily have a direct chain of relationship in my object model, but the included data I want to send is still pertinent and "related." Just not in a direct sense.

If it is not related but a client may very likely need it anyways, HTTP2 server push may be another option.

**Comment by bradjones1** [comment]
Thanks... I ended up creating a "computed field" that is only present/request-able on the route in question, so as to stay spec-compliant. I'll have to read up on the reasoning why full linkage is a hard-and-fast requirement. In theory I guess I could implement some sort of extension/profile for my use case but then clients wouldn't know about it if they are just vanilla json:api implementations. I think the PR is solid and would address the core of the question. Thanks for the help.

**Comment by jonatanlr98** [comment]
links": { "related": { "href": "http://example.com/articles/1/comments", "meta": { "count": 10 } } }

**Comment by jonatanlr98** [comment]
links": { "related": { "href": "http://example.com/articles/1/comments", "meta": { "count": 10 } } }

**Comment by jonatanlr98** [comment]
GET /articles?include=author&fields[articles]=title,body&fields[people]=name HTTP/1.1 Accept: application/vnd.api+json
