### ISSUE TITLE
Traversing relationships in URI templates

### ISSUE THREAD

**Issue by rkh** [json-api/json-api#162]
In the given examples, `posts.author` represents the author id (or whatever is given in the author field in the posts document).

Especially given that there is a solution for #158, how would I specify other fields from the author document in a template relating to a post? `posts.author.name`?

**Comment by dgeb** [comment]
I believe that the paths in URI template expressions in the top level `"links"` should be absolute, while paths in URI template expressions in `"links"` for a particular document should be relative to that document.

Therefore, I'd use `posts.author.name` at the top level, `author.name` from within a particular `post`, and simply `name` from within an `author` document.

**Comment by dgeb** [comment]
As of #341 (RC2), explicit URI template support has been removed from the spec.
