### ISSUE TITLE
Collection Relations

### ISSUE THREAD

**Issue by rkh** [json-api/json-api#163]
Are relations a collection (but not the documents in the collection on its own have) supposed to simply go into the meta tag? If so, could we make this part of the spec?

**Comment by rkh** [comment]
Also, how would that work for embedded collections? But then again, a collection is defined by entity type at the moment, it would be impossible to have two kinds of collections for the same type (unless you give them different names).  #141 is a subset of this issue, though this also affects for instance pagination.

An example would be embedding the first five comments in a post document.

**Comment by steveklabnik** [comment]
If I'm reading this right, it's "Can I have more than one relation per link", yes?

**Comment by rkh** [comment]
No, can a collection have relations. ie, here's a collection of post, can it have a "next" relationship to another collection of posts, even thought the posts on its own would not have such a relation, or do we need an intermediate "page" resource? How does this work for embedded collections?

**Comment by steveklabnik** [comment]
I believe this is irrelevant now with the latest version of the spec.
