### ISSUE TITLE
Can normal links include meta data, too?

### ISSUE THREAD

**Issue by rkh** [json-api/json-api#164]
According to the examples in the spec, top level links (using templates) can include meta data:

``` json
{
  "links": {
    "posts.author": {
      "href": "http://example.com/people/{posts.author}",
      "type": "people"
    }
  }
}
```

Can links in the document include this, too?

``` json
{
  "posts": [{
    "links": {
      "author": {
        "href": "http://example.com/people/dhh",
        "type": "people"
      }
    }
  }]
}
```

**Comment by dgeb** [comment]
:+1: I think this makes sense and should be explicitly called out in the spec.

**Comment by BRMatt** [comment]
It would also help avoid this caveat mentioned in the spec:

> NOTE: The linkage between the key under "links" ("author" in this example) and the associated document type ("people" in this example) is hardcoded into the client. The client must also hardcode how to relate that reference to a url.

**Comment by dbettin** [comment]
+1 on this request. This is the only thing making us diverge from the spec. We love to see this land.

**Comment by bencates** [comment]
+1.  I'd also like to propose the following variations:

``` json
{
  "posts": [{
    "links": {
      "author": {"id": "dhh", "type": "person"},
      "commenters": [
        {"id": "wycats", "type": "person"},
        {"id": "37signals", "type": "company"}
      ]
    }
  }]
} 
```

**Comment by steveklabnik** [comment]
Adding to 1.0.

**Comment by dgeb** [comment]
Meta data in links is now explicitly allowed via #237. See the [resource relationships](http://jsonapi.org/format/#document-structure-resource-relationships) section.
