### ISSUE TITLE
Not able to upload files from postman to durpal dev portal.

### ISSUE THREAD

**Issue by simantstha** [json-api/json-api#1643]
![image](https://user-images.githubusercontent.com/30699044/181593281-76386ce9-af49-4b39-8570-7f0a643b3b4f.png)
Selected file with binary. I get 403 forbidden errors.

**Comment by jelhan** [comment]
Hello @simantstha,
This repository is about the JSON:API specification itself. Questions about specific implementations like Drupal should be asked at other places. E.g. StackOverflow or a Drupal community chat.
I'm closing this issue as off topic.
Best Jeldrik
