### ISSUE TITLE
Using a resource identifier object to create a resource

### ISSUE THREAD

**Issue by jelhan** [json-api/json-api#1645]
Reading the spec another time, I noticed this statement:

> A “resource identifier object” MUST contain a type member. It MUST also contain an id member, except when it represents a new resource to be created on the server. In this case, a lid member MUST be included that identifies the new resource.

In which case could a resource identifier object be used to create a resource?

If I haven't missed anything, base specification only supports one way to create resources described in _9.1 Creating Resources_. And that one requires resource objects.

> A resource can be created by sending a POST request to a URL that represents a collection of resources. The request MUST include a single resource object as primary data. The resource object MUST contain at least a type member.

This was introduced in #1244. Adding it to v1.1 milestone as we may want to revisit before releasing stable version.

**Comment by dgeb** [comment]
> In which case could a resource identifier object be used to create a resource?

The resource identifier object isn't being used to create a resource. It is used to reference a resource to be created in the same request. For instance, say that a resource is POSTed as described in 9.1. If that same resource wants to reference itself from within a relationship, but the server is supplying the `id`, then the client must supply an `lid` in both the resource and in the resource identifier that represents the relationship.

For instance:

```
 POST /people HTTP/1.1
 Content-Type: application/vnd.api+json"
 Accept: application/vnd.api+json

 {
   "data": {
     "lid": "a",
     "type": "person",
     "attributes": {
       "firstName": "John",
       "lastName": "Doe"
     },
     "relationships": {
       "bestFriend": {
         "data": {
           "lid": "a",
           "type": "person"
         }
       }
     }
   }
 }
 ```

**Comment by jelhan** [comment]
Thanks a lot for that detailed explanation. Makes totally sense. Missed that use case.
