### ISSUE TITLE
Optional relationships member

### ISSUE THREAD

**Issue by mark-hartmann** [json-api/json-api#1653]
I have a question regarding the relationship member of a resource object, but could not find an answer in the specification. 

Is it possible according to the specification that resources of the same type can or cannot have a relationship? If it's known in advance that certain resources can definitely not have some relationship, would the following representation be acceptable, or do resources of the same type always have to display all relationships, even if it's linked resource would almost always null/not found?

For this example, it is assumed that the type `foo` has a relation `bar`, which is only relevant for a limited set of resources:

```json
[
  {
    "id": "id1",
    "type": "foo",
    "attributes": {
      "someAttribute": false
    },
    "links": {
      "self": "/foo/id1"
    }
  },
  {
    "id": "id2",
    "type": "foo",
    "attributes": {
      "someAttribute": false
    },
    "links": {
      "self": "/foo/id2"
    },
    "relationships": {
      "bar": {
        "links": {
          "related": "/foo/id2/bar",
          "self": "/foo/id2/relationships/bar"
        }
      }
    }
  }
]
```

**Comment by lode** [comment]
To be friendly to our clients, I've always included empty relationships with `null` data. E.g.:

```json
{
	//...
	"relationships": {
		"bar": {
			"data": null
		}
	}
}
```

This also makes explicit to the client that the server understood the request but that the relationship is not set.

I'm not fully sure about what the spec allows or not, as the server is allowed to add fields when it sees fit, but unclear whether that decision can be mixed on list requests. But when the client requests the relationship explicitly (`?fields[foo]=bar`) you will need to add it (optionally with `null` data).

**Comment by dgeb** [comment]
> But when the client requests the relationship explicitly (?fields[foo]=bar) you will need to add it (optionally with null data).

Thanks @lode. I agree that this is one scenario regarding field inclusion in which the spec is explicit. 

Other scenarios are not specified, so it is technically allowed to include fields for some resources but not others of the same `type` when `fields` for that `type` are not specifically requested.
