### ISSUE TITLE
Can a creation request respond with a different entity type?

### ISSUE THREAD

**Issue by cmeeren** [json-api/json-api#1654]
The 1.0 spec says that

> A resource can be created by sending a POST request to a URL that represents a collection of resources. The request MUST include a single [resource object](https://jsonapi.org/format/#document-resource-objects) as primary data. The [resource object](https://jsonapi.org/format/#document-resource-objects) MUST contain at least a type member.

And:

> The response **MUST** also include a document that contains the primary resource created.

IN particular, it does not say that the created resource must have the same `type` as the one in the request. In other words, it seems that, according to the spec, it is allowed for the server to respond with a different `type` than the one in the request. I can't immediately think of any valid use-cases, but I'm just wondering if this is indeed allowed.

**Comment by jelhan** [comment]
I think this has been clarified in v1.1:

> If the requested resource has been created successfully and the server changes the resource in any way (for example, by assigning an id), the server MUST return a 201 Created response and a document that contains _the resource_ as primary data.

A resource is identified by `type` and `id` (or `lid`). If `type` changes, it's not the same resource.

**Comment by cmeeren** [comment]
> If `type` changes, it's not the same resource.

It doesn't really make sense to speak of "the same resource" in this case: The resource doesn't exist before it is created; furthermore, the client can create resources by only supplying a `type`, which is not sufficient to identify a resource anyway (`id` is needed, to).

But in your terms: As I read it, the spec does not state that the created resource has to be the "same" resource as the one in the request. I am still wondering if that is correctly interpreted.

**Comment by jelhan** [comment]
> As I read it, the spec does not state that the created resource has to be the "same" resource as the one in the request.

I'm reading it differently. Wording used in v1.1 states that response "contains the resource as primary data". It's not just some resource. But _the resource_, which has been created.

Wording used in v1.0 is more confusing to me. But it's also talking about "the primary resource created". Again not some resource but the resource created in the request.

I think that's also the intent. Would be very confusing if a server may create any resource as a result of a request to create a resource. The client asks about creating a specific resource. That resource may be specified more detailed or not. But it's always about a specific resource.

What is the use case for creating a different resource than requested by the client?

**Comment by cmeeren** [comment]
> Wording used in v1.1 states that response "contains the resource as primary data". It's not just some resource. But _the resource_, which has been created.

That could simply mean that the server must return "the resource that was created", whichever resource type that happens to be. As I read it, it does not mandate that the resource type be the same as the one in the request.

> I think that's also the intent.

I would like to believe it is.

> Would be very confusing if a server may create any resource as a result of a request to create a resource.

I agree, though it would of course be documented in the API specification. In any case, as an implementer of a JSON:API server framework, I would like to make sure.

>  That resource may be specified more detailed or not.

Yes, and as I see it, JSON:API does not mandate that the resource is created with exactly the field values that the client supplied. For example, a phone number could be canonically formatted in the response where it was not in the request, or there may be other reasons why the server returns a different value than what the client requests. I am wondering if this extends to `type`.

> What is the use case for creating a different resource than requested by the client?

As I said, I can't immediately think of any good use-cases. (Admittedly, I haven't tried very hard to think of any.) That does not mean there aren't any.

**Comment by jelhan** [comment]
If I understand correctly, you are concerned that specification is not clear enough, which resource must be returned on successful creation. To be honest it's seems to be quite clear to me. Let me put the sentences together, which makes it clear in my reading.

> A resource can be created by sending a POST request to a URL that represents a collection of resources. The request MUST include a single resource object as primary data.
> 
> If _the requested resource_ has been created successfully (...) the server MUST return a document that contains _the resource_ as primary data.

Maybe the second sentence in first paragraph could be improved. Currently it does not state explicitly that the resource object in the request must represent the resource, which should be created. But for me it's quite clear from context.

For response it explicitly states that it's "requested resource". I have no idea how this could be further clarified.

Do you have any proposal how the current wording could be improved to avoid this confusion.

> > I think that's also the intent.
> 
> I would like to believe it is.

@dgeb please speak up if my assumption on intent is wrong.

**Comment by cmeeren** [comment]
Thank you for highlighting relevant parts of the specification. I agree that it seems quite clear now.
