### ISSUE TITLE
Vector logo?

### ISSUE THREAD

**Issue by bradjones1** [json-api/json-api#1655]
Is there a vector version of the JSON:API logo? (e.g., an SVG?) I thought it would be fun to get some stickers made to celebrate 1.1?

**Comment by jelhan** [comment]
There is a Sketch file for the logo available: https://github.com/json-api/json-api/blob/gh-pages/design/jsonapi.sketch

I don't have Sketch myself. But I think it is the latest version, which was used to generate the logo PNG used at the website. You could find that one here: https://github.com/json-api/json-api/blob/gh-pages/images/jsonapi.png

**Comment by dgeb** [comment]
@bradjones1 let me know if you don't have sketch and need an svg generated. And thanks for the thought re: stickers - great idea!

**Comment by bradjones1** [comment]
@dgeb I do not have sketch and my 5-minute search for a way to convert came up empty, seems like it's not really 1:1 and proprietary nonetheless. Yes, a SVG would be great. DrupalCon Europe is in late September and I would love to be a bit of a "json:api ambassador," and be able to share with people that 1.1 is tagged.

**Comment by dgeb** [comment]
> DrupalCon Europe is in late September and I would love to be a bit of a "json:api ambassador," and be able to share with people that 1.1 is tagged.

Love it, that sounds great!

I'll dig up my old version of sketch and get that svg to you soon.

**Comment by dgeb** [comment]
@bradjones1 I've just updated the sketch document and added an [svg of the logo](https://github.com/json-api/json-api/blob/gh-pages/design/jsonapi.svg) in #1661. Let me know if you need anything else :)

**Comment by bradjones1** [comment]
@dgeb How many backend guys does it take to make a vector logo? The SVG had the right data in it but the crop/viewport/whatever it's called in SVG was incorrect. I did some manual editing to get it closer to usable out of the box. https://github.com/json-api/json-api/pull/1662
