### ISSUE TITLE
Caching for non-canonical URLs

### ISSUE THREAD

**Issue by rkh** [json-api/json-api#166]
Give a URL-based JSON API for a CI system where one repository has many jobs.

Imagine the following API endpoints:
- **/repos/{repos.id}** - returns the payload for a single repository
- **/repos/{repos.id}/last_build** - returns the payload for the last build on a repository
- **/builds/{builds.id}** - returns the payload for a given build

It is builds that encapsulate the actual state (failing/passing aka red/green).

Now an example payload could look like this:

``` json
{
  "repos": [{
    "id": 9000,
    "slug": "rails/rails",
    "links": { "last_build": "/builds/42" }
  }]
}
```

The issue with the above example is that checking for updates would involve reloading the repository and then loading the last build again. So instead we could do the following:

``` json
{
  "links": { "repos.last_build": "/repos/{repos.id}/last_build" },
  "repos": [{ "id": 9000,  "slug": "rails/rails" }]
}
```

I really like that. However, if someone want to embed the last build, there is no way for a client to identify the embedded build as such:

``` json
{
  "links": { "repos.last_build": "/repos/{repos.id}/last_build" },
  "repos": [{ "id": 9000,  "slug": "rails/rails" }],
  "linked": {
    "builds": [{
      "href": "/builds/42",
      "state": "passed"
    }]
  }
}
```

I don't see how the client could figure out that the included build is the last build for the repository.

How do I solve this?

**Comment by dgeb** [comment]
So, you're looking to retrieve the current `last_build` for each repo from the `linked` data, but also provide an `href` which could be polled later to check for a new `last_build`?

The documented method to link the primary document to linked documents is by specifying the linked id in the primary document, so it can be matched up with the `linked` document.

You could combine this approach with specifying `repos.last_build` in the top-level `links`, like so:

``` json
{
  "links": {
    "repos.last_build": {
      "href": "/repos/{repos.id}/last_build",
      "type": "builds"
    } 
  },
  "repos": [{ "id": 9000,  
              "slug": "rails/rails",
              "links": {"last_build": "42"} }],
  "linked": {
    "builds": [{
      "id": "42",
      "href": "/builds/42",
      "state": "passed"
    }]
  }
}
```

I think this solves both problems, but this combination of canonical and non-canonical links with the same path is not explicitly addressed in the spec.

**Comment by steveklabnik** [comment]
Yes, you should use `rel=canonical` if you want to indicate that one of them is. It's already standard, so it's outside of the scope of definition here.

**Comment by BRMatt** [comment]
> Yes, you should use rel=canonical if you want to indicate that one of them is. It's already standard, so it's outside of the scope of definition here.

@steveklabnik To clarify, do you mean there should be a `rel` attribute in link objects? I can't see a reference to this in the current spec.

**Comment by rkh** [comment]
See #159.

**Comment by BRMatt** [comment]
@rkh thanks
