### ISSUE TITLE
query parameters json schema

### ISSUE THREAD

**Issue by mathematikoi** [json-api/json-api#1664]
Hi, I'm wondering if there is any provided json schema definition for the [query parameters](https://jsonapi.org/format/#query-parameters)

**Comment by freddrake** [comment]
Query parameters are not JSON; why would there be a corresponding JSON Schema?

**Comment by mathematikoi** [comment]
i see, i'm wondering if there should be any validation of the query parameters values, and if so, a json schema can be used to define them for jsonapi compliance.

**Comment by mathematikoi** [comment]
i get your point, since the query parameters are not even sent in json format then we can't use a json schema for it (not the same as request/response body, which are in fact sent in json format).
