### ISSUE TITLE
How to Represent DDD Value Objects using Json Api

### ISSUE THREAD

**Issue by lawrenceong001** [json-api/json-api#1665]
We are in the process of adopting the use of Json API for our services. At this time, the use of relationships seem to match very well with entities, since the value of the information is in the link. However, when we try to use relationships for value objects, we run into issues:

When the value object is a string-representable value (i.e. 'text', '9.99'), we can set the id to it and it seems to be fine (with certain caveats for basic type conversion). When the value object is a compound item (i.e. amount: {currency: 'usd', value: '4.44'}), we can't really set this into a string without having to write all sorts of translations to tackle them. this [section](https://jsonapi.org/format/1.1/#document-resource-object-identification) requires that the value of the id be string. 

are there any advice on how we can achieve this type of representation?

**Comment by lode** [comment]
In this specific example (amount with currency and value), I would say you should not use relationships, but just an attribute. The amount is more a value object than an entity; there is no id. E.g.:

```json
{
	"type": "Product",
	"id": "42",
	"attributes": {
		"amount": {
			"currency": "usd",
			"value": "4.44",
		}
	}
```
