### ISSUE TITLE
Is there any way to include not related models into a model for JsonApiFramework 2.8.0?

### ISSUE THREAD

**Issue by tylerton** [json-api/json-api#1668]
Hello team,

When I was using JsonApiFramework 2.1.0, I was able to include not related models to a model without defining any relationship in JsonApiWriter or Mapping. I just simply pass an empty string as its relationship name.

For example, food and vehicle are not related to each other. When I want to include vehicles with food, I just call
`.IncludeMany(food, String.Empty, vehicles)`

However, when I update from 2.1.0 to 2.8.0, it complains about the relationship name. It requires a valid one. However, I don't want to define a fake relationship name because those models are not really related. I just want to get everything in one API call.

Could you please tell me if we have any way to do that?

Thank you very much.

**Comment by dgeb** [comment]
Hi @tylerton - This repo is for the json:api specification. The JsonApiFramework repo is [here](https://github.com/scott-mcdonald/JsonApiFramework). Please try opening a new issue over there. Good luck!

**Comment by jelhan** [comment]
Let me quickly add the position of the spec itself on including resources, which aren't related to primary data:

> Every included resource object MUST be identified via a chain of relationships originating in a document’s primary data. This means that compound documents require “full linkage” and that no resource object can be included without a direct or indirect relationship to the document’s primary data.

Your implementation is free to ignore that requirement. But you should be aware that it violates the specification. This might be also the reason for which the library you are using has dropped support for it.

I would recommend using parallel requests to fetch independent resources.
