### ISSUE TITLE
specification for PATCH "remove" operation for attribute

### ISSUE THREAD

**Issue by jokeyrhyme** [json-api/json-api#167]
In the "Updating a Document (PATCH)" section...

> For attributes, only the replace operation is supported at the current time.

How should other attribute operations look in PATCH requests? Could we just follow the RFC mentioned in #115 for now? Is the JSON API specification likely to be extended in accordance with that RFC?

Cheers!

**Comment by steveklabnik** [comment]
Yes, you just use RFC 6902.

**Comment by steveklabnik** [comment]
Sorry, I was confused about your issue. I am not 100% sure why we have that restriction in the spec, as @wycats added that part. We should be more explicit about this.

**Comment by steveklabnik** [comment]
I'd like this clarified and/or removed for 1.0.

**Comment by wycats** [comment]
The reason is that "removing" an attribute is a bit of a weird operation to support in a backend-agnostic way.

You can always replace the attribute with `null`, and removing an attribute is really backend-specific. A backend could choose to implement "replace with null" as a removal, but for example, there is no way to "remove" an attribute from a SQL database, which has a fixed schema.

**Comment by steveklabnik** [comment]
So, doesn't that mean it varies per backend? Is that a good reason to restrict removal wholesale?

I guess what I'm saying is, we're worried about interface. The details of the backend implementation don't really matter, right?

**Comment by wycats** [comment]
In general, having an operation that varies by backend means that a client library has no way to know if the operation will actually work when applied to a specific backend.

I would be open to reconsidering here if someone could give me an example of a case where a document-style backend truly needed to distinguish between "replace with null" and "remove". We would then need to think about what to recommend to SQL-style backends when receiving a "remove" operation (because if there **is** an important difference, a SQL-style backend cannot encode the information that a removal request is intending to communicate).

**Comment by steveklabnik** [comment]
Seems fair.

**Comment by jokeyrhyme** [comment]
It seems like a shame to avoid saying _anything_ about a particular feature just because SQL backends are going to behave differently to NoSQL backends.

How about a compromise? We specify:
- clients should use the `PATCH` RFC, and are free to submit "replace with null" and "remove" requests
- servers should implement both these requests, but are free to implement them both the same way (e.g. SQL backend treats "remove" as "replace with null")
- clients should take care to not make any assumptions about backend behaviour, and that in this case either "replace with null" or "remove" could be performed

In JavaScript, the absence of a property is just as "falsey" as if it were defined to be `null`. In many JSON-consuming clients, it shouldn't be too difficult to cover both cases. Exactly what the backend did will usually not matter, and won't be difficult to work around in either case.

I tried to design a REST API years ago, but found so little guidance on the subject (outside of what the HTTP methods mean semantically). This is why I'm passionate about JSON API filling as many of the gaps around HTTP and REST as possible. Leaving something out of the specification is just as serious a matter as including something.

**Comment by wycats** [comment]
I guess my feeling is that if we tell clients that they aren't allowed to distinguish between "replace with null" and "remove", why should they issue different requests? Surely it's to express **some kind** of intent, which can't be reliably honored.

I know this is a little subtle, and I think your compromise is mostly acceptable, but I'm curious about your thoughts on my thoughts :wink:

**Comment by jokeyrhyme** [comment]
> if we tell clients that they aren't allowed to distinguish between "replace with null" and "remove", why should they issue different requests?

Good point. I think in this particular case, it's probably not going to be an issue for the clients. However, it does smell a bit funny.

Regarding the eternal conflict between SQL and NoSQL:
- if we don't specify anything, then everyone using JSON API will come up with all sorts of different incompatible solutions
- if we specify something strictly SQL-backend-compatible, then the NoSQL folks will implement NoSQL-specific behaviour in all sorts of different incompatible ways
- if we specify something allowing the full flexibility of NoSQL, then the SQL folks will have to say "we implement JSON API except for these parts"

Hmmm. That last option could be a way forward for conflicts like this. What if we had different levels for the JSON API specification? For the most part, SQL capabilities are a subset of the Document-store capabilities. There could be an appendix or something that specifies what parts are missing if your backend is SQL.

I'm pretty torn. Forking the specification has its own issues. I wouldn't suggest it just to solve this one issue, but it might be an interesting solution to hold in reserve should we encounter other back-end specific inconsistencies.
