### ISSUE TITLE
1.1 seems to contain a breaking change - 'lid' now required for resource creation?

### ISSUE THREAD

**Issue by cmeeren** [json-api/json-api#1674]
The 1.1. spec, section 7.3, states:

> A “resource identifier object” **MUST** contain a `type` member. It **MUST** also contain an `id` member, except when it represents a new resource to be created on the server. In this case, a `lid` member **MUST** be included that identifies the new resource.

I can't immediately see a way to interpret this other than `lid` being required for all resource creation requests. This is, of course, a breaking change from 1.0, where only `type` was required (and `id` was optional). So either I'm missing something, or the spec could be improved. Could you clarify this?

**Comment by jelhan** [comment]
The quote is about _Resource Identifier Objects_. Resource identifier objects were required to have `type` and `id` already in v1.0:

>  5.3 Resource Identifier Objects
>
> [...]
>
> A “resource identifier object” MUST contain `type` and `id` members.

A resource identifier object is not used for creating a resource. It is used to identify resources. It requires either `id` or `lid` in addition to `type` to identify a resource.

A resource object, which is used to create a resource, is allowed to have neither `id` nor `lid` member also in v1.1:

> 7.2 Resource Objects
>
> [...]
> 
> 7.2.1 Identification
>
> As noted above, every [resource object](https://jsonapi.org/format/#document-resource-objects) MUST contain a type member. Every resource object MUST also contain an id member, except when the resource object originates at the client and represents a new resource to be created on the server. If id is omitted due to this exception, a lid member MAY be included to uniquely identify the resource by type locally within the document. The value of the lid member MUST be identical for every representation of the resource in the document, including [resource identifier objects](https://jsonapi.org/format/#document-resource-identifier-objects).

**Comment by cmeeren** [comment]
My bad. Thanks for clarifying!
