### ISSUE TITLE
Why the square bracket syntax for query params?

### ISSUE THREAD

**Issue by dwjohnston** [json-api/json-api#1679]
The documentation here: https://jsonapi.org/format/#query-parameters-families

gives something of an explanation: 

>In practice, however, parameters like page[offset] and page[limit] are usually defined and processed together, and it’s convenient to refer to them collectively. Therefore, JSON:API introduces the concept of a query parameter family.
>
>A “query parameter family” is the set of all query parameters whose name starts with a “base name”, followed by zero or more instances of empty square brackets (i.e. []) or square-bracketed legal [member names](https://jsonapi.org/format/#document-member-names). The family is referred to by its base name.

So basically for grouping, sure. 

Problem is, these query params need to be percent encoded, which makes for unreadable URLs. 

Why not just use a camel casing convention, eg `pageNumber`, `pageSize`, `filterFoo`, `filterBar`?

**Comment by lindyhopchris** [comment]
Definitely prefer the grouping. It definitely helps in server implementations, i.e. handle the `filter` group as filters, rather than having to go through all the query params and see if they are of format `filter*` to know they are filters.

**Comment by jelhan** [comment]
> Why not just use a camel casing convention, eg `pageNumber`, `pageSize`, `filterFoo`, `filterBar`?

First of all it would be a breaking change. And we don't want to introduce breaking changes as that would make implementations incompatible.

Using camel case might also introduce collisions with [implementation-specific query parameters](https://jsonapi.org/format/#query-parameters-custom). `pageNumber` would be valid implementation-specific query parameter as it contains at least one non a-z character.

Isn't the percent encoding nearly always handled by the tools you use to make a network request anyways? In which scenario is this causing a noticeable additional complexity for implementations?

**Comment by gabesullice** [comment]
As @jelhan says, we can't change this.

For background, the "why" might boil down to a historical accident. JSON:API came out of the Ruby/Ember world. The Ruby [query string builder](https://devdocs.io/rails~6.0/hash#method-i-to_query) implements hierarchical values with square brackets. PHP does [the same thing](https://www.php.net/manual/en/function.http-build-query.php#example-3932). I suspect many other languages have implemented something similar for cross-compatibility reasons.

I'm not sure which language you're working in @dwjohnston, but I'll bet your language has a library for handling this already :)

Related discussion on [StackOverflow](https://stackoverflow.com/questions/30261513/is-there-a-spec-for-nested-urlencoded-params).

**Comment by dwjohnston** [comment]
@gabesullice  I'm using JavaScript. 

It did occur to me that perhaps something would do the square bracket notation automatically - I looked at JavaScript's [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) like: 

```javascript 
new URLSearchParams({page: {number: 1}}).toString(); 
//'page=%5Bobject+Object%5D'
```

But it doesn't auto-squarify things for us.

**Comment by lindyhopchris** [comment]
@dwjohnston take a look at something like [qs](https://www.npmjs.com/package/qs) - you can use `qs.stringify()` to convert an object to a query string.

**Comment by jelhan** [comment]
> @gabesullice I'm using JavaScript.
> 
> It did occur to me that perhaps something would do the square bracket notation automatically - I looked at JavaScript's [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) like:
> 
> ```js
> new URLSearchParams({page: {number: 1}}).toString(); 
> //'page=%5Bobject+Object%5D'
> ```
> 
> But it doesn't auto-squarify things for us.

@dwjohnston That's not how `URLSearchParams` is meant to work. `URLSearchParams` takes an optional key-value pair as an argument. But that keys should be the name of the query parameter and the value should be the value of the query parameter. It than takes care of encoding the brackets as needed:

```js
new URLSearchParams({ 'page[number]': '1', 'page[size]': '25' }).toString();
// "page%5Bnumber%5D=1&page%5Bsize%5D=25" 
```

**Comment by jelhan** [comment]
I'm closing this issue. I feel it has been answered. Please feel free to comment anyways if an aspect has not been covered yet.
