### ISSUE TITLE
How does one document a JSON:API

### ISSUE THREAD

**Issue by Floppy012** [json-api/json-api#1685]
We're thinking about using the JSON:API spec for our REST-API (using [Laravel JSON:API](https://laraveljsonapi.io/)). However after reading through both documentations (JSON:API and Laravel JSON:API) there is no mention of how to document such an API.

When not using JSON:API I can simply create an OpenAPI spec file that documents the API. However, OpenAPI spec files only work for the surface of a JSON:API documenting the requests I can make and the responses I get. It doesn't document the actual Schemas, Attributes and Relations. At least not in a way that is easy to understand for someone who tries to implement the API.

OpenAPI has the advantage of letting me generate a client that I can use to access the API. Generating a client from an OpenAPI spec file of a JSON:API doesn't really help since I would still have to deal with relations myself.

The only solution I see is by creating a human readable documentation (for example in Markdown) that explains what Schemas there are, what attributes and relations they have. So that API users can implement a client for themselves. Which does work but feels like a huge leap backwards compared to a traditional API where I can just publish the OpenAPI file and have users generate their clients (or even provide them myself).

Even for our own usage it's kind of annoying basically having to define the API twice (backend and frontend) just to be able to connect the frontend to the backend.

**Comment by lindyhopchris** [comment]
As the creator of Laravel JSON:API, I'm interested to see what people say here.

FYI there is an intention for Laravel JSON:API to produce Open API specs. The only thing that's blocking it really is available time on open source work. Plus I find it difficult to prioritise, because the personal projects I use Laravel JSON:API don't (at the moment) need OpenAPI spec files.

There's a rather lengthy discussion about it here, in case you haven't seen it: https://github.com/laravel-json-api/laravel/issues/19

**Comment by Floppy012** [comment]
> There's a rather lengthy discussion about it here, in case you haven't seen it: https://github.com/laravel-json-api/laravel/issues/19

I have seen that issue and tried it out with the example project of Laravel JSON:API. It generates an OpenAPI spec file as expected, which does work but gets cumbersome really quickly.

Generating a client from that, currently doesn't work really well as the response bodies are incomplete (for example: `included` is missing. I know, it's still in development). But even if it were complete I would have to extract data from the `included` array using `relationships` data.

<details>
<summary>Example</summary>

```typescript

const postResponse = await PostsService.postsShow(1, ['author']);  // the array represents the "include" query parameter

const author = postsResponse.included
    .filter((i) => i.type === postResponse.relationships.author.data.type)
    .find((i) => i.id === postResponse.relationships.author.data.id)
```
</details>

I know there are tools like [json-api-merge](https://www.npmjs.com/package/json-api-merge). But they would only return me an untyped (`any`-object).

### Our current solution

Currently we use Laravel-Data to work with data in regards to our API. We have a laravel package that generates an OpenAPI spec file using information from our controllers, attributes and the DTO class structures.

We then generate a Typescript client from that OpenAPI spec file and use that to interact with our backend. One of the major benefits is, that if a backend dev changes something in regards to the API, we immediately see where we have to adjust code in our frontend due to TypeScript or SAST throwing errors at us.

**Comment by jelhan** [comment]
Two patterns are available to document your JSON:API as already mentioned in this thread:

1. Human readable documentation focused on existing a) entry points to the API, b) available resource objects and the attributes and relationships of those, and 3) implementation-specific semantics (e.g. filtering strategy, supported side-loading of related resources etc.).
2. Machine readable documentation using OpenAPI specification.

An API could provide only one of them, both or even none. The documentation could be written by hand or generated automatically. Existing tooling highly depends on the tech stack chosen by the project. This is nothing to be solved by the JSON:API specification itself in my opinion.

**Comment by jelhan** [comment]
I'm going to close this issue. Feel free continuing the topic in the [discussion forum](https://discuss.jsonapi.org/).
