### ISSUE TITLE
Clarity on n-nested document links in compound documents

### ISSUE THREAD

**Issue by lettertwo** [json-api/json-api#170]
Given the following (abbreviated) example of a compound document taken from the spec:

``` json
{
  "links": {
    "posts.author": {
      "href": "http://example.com/people/{posts.author}",
      "type": "people"
    },
    "posts.comments": {
      "href": "http://example.com/comments/{posts.comments}",
      "type": "comments"
    }
  },
  "posts": [{
    "id": "1",
    "title": "Rails is Omakase",
    "links": {
      "author": "9",
      "comments": [ "1" ]
    }
  }],
  "linked": {
    "people": [{
      "id": "9",
      "name": "@d2h"
    }],
    "comments": [{
      "id": "1",
      "body": "Mmmmmakase"
    }]
  }
}
```

It is clear how the links between the `linked` documents and the primary `posts` document are determined.

However, the spec doesn't appear to address what a compound document might look like when relationships are nested further (i.e., `linked` documents themselves have `links`).

For example (the difference between this example and the one above is that the included comment document also has a link to a comment 'author'):

``` json
{
  "links": {
    "posts.author": {
      "href": "http://example.com/people/{posts.author}",
      "type": "people"
    },
    "posts.comments": {
      "href": "http://example.com/comments/{posts.comments}",
      "type": "comments"
    },
    "comments.author": {
      "href": "http://example.com/people/{comments.author}",
      "type": "people"
    }
  },
  "posts": [{
    "id": "1",
    "title": "Rails is Omakase",
    "links": {
      "author": "9",
      "comments": [ "1" ]
    }
  }],
  "linked": {
    "people": [{
      "id": "9",
      "name": "@d2h"
    }],
    "comments": [{
      "id": "1",
      "body": "Mmmmmakase",
      "links": {
        "author": "9"
      }
    }]
  }
}
```

Is this is an accurate understanding of the spec? Can non-primary (`linked`) documents have their own mappings in the top-level `links`?  Are those mappings always relative to the primary document (i.e. `posts.comments.author`), or are they relative to the document resource (i.e. `comments.author`, as above)?

**Comment by steveklabnik** [comment]
This is a good question. Unsure. I would say that I would write exactly what you did (`comments.author`), but we should be explicit about this.

**Comment by lettertwo** [comment]
:+1: to being explicit—I think the common-sense solution may be what we've just agreed on, though I may have a short-sighted view of how easily a client could handle this type of scenario. It strikes me as possible that following n-nested relationships on the client side might end up being nebulous, but at the moment it seems like this approach is both straightforward and robust enough to support even very complicated and deeply nested relational structures.

**Comment by steveklabnik** [comment]
Adding to 1.0.

**Comment by steveklabnik** [comment]
This very old issue is basically not relevant today, I believe. The spec has changed in the meantime. Thanks!
