### ISSUE TITLE
PrimaryResourceType not to be null at this point

### ISSUE THREAD

**Issue by sasa-vasiljevic** [json-api/json-api#1704]
I implemented basic sample using JSONAPI. However when I try to invoke GET command I get following error:
`System.InvalidOperationException: Expected IJsonApiRequest.PrimaryResourceType not to be null at this point.`
What am I missing?

**Comment by jelhan** [comment]
This question seems to be about a specific library implementing the JSON:API specification. This repository is for the development of the specification itself. Please open a ticket with the library you are using or ask on StackOverflow for support.
