### ISSUE TITLE
Extend Spec To Allow Creation of Multiple Resources in One API Call

### ISSUE THREAD

**Issue by AlexanderKaran** [json-api/json-api#1711]
The current spec allows for resource creation via an object on the `data` key: https://jsonapi.org/format/#crud-creating

We should extend the spec to allow an array of objects to be passed.

```
POST /photos HTTP/1.1
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "data": [
    {
      "type": "photos",
      "attributes": {
        "title": "Ember Hamster",
        "src": "http://example.com/images/productivity.png"
      },
      "relationships": {
        "photographer": {
          "data": { "type": "people", "id": "9" }
        }
      }
    },
    {
      "type": "photos",
      "attributes": {
        "title": "Another Photo",
        "src": "http://example.com/images/another-photo.png"
      },
      "relationships": {
        "photographer": {
          "data": { "type": "people", "id": "10" }
        }
      }
    }
  ]
}
```

I would happily do the work and updates if this kind of extension is allowed. Wanted to ask first rather than just put a PR in.

**Comment by jelhan** [comment]
I'm aware of two extensions allowing to create multiple resources in a single request:

1. [Atomic Operations](https://jsonapi.org/ext/atomic)
2. [Bulk Create](https://github.com/jelhan/json-api-bulk-create-extension)

Adding support to base specification itself has been discussed at multiple places already. #1625 is a good starting point. Going to close this one as duplicate.
