### ISSUE TITLE
Profiles should be allowed to define query parameters 

### ISSUE THREAD

**Issue by jelhan** [json-api/json-api#1718]
Profiles are currently explicitly forbidden to define query parameters:

> A profile MUST NOT define any query parameters.

Implementations are explicitly allowed to define query parameters:

> Implementations MAY support custom query parameters. However, the names of these query parameters MUST come from a family whose base name is a legal member name and also contains at least one non a-z character (i.e., outside U+0061 to U+007A).
> 
> It is RECOMMENDED that a capital letter (e.g. camelCasing) be used to satisfy the above requirement.

This mismatch between capabilities of implementations and profiles conflicts with the general intent of profiles to standardize implementation semantics.

> Profiles provide a means to share a particular usage of the specification among implementations.
>
> Profiles can specify implementation semantics, but cannot alter, add to, or remove specification semantics.

Profiles should be allowed to define query parameters as long as they comply to the same rules as [implementation-specific query parameters](https://jsonapi.org/format/#query-parameters-custom).

I noticed this problem in the following discussion: https://discuss.jsonapi.org/t/dynamic-constraints-a-proposal-for-a-general-specification/1744

**Comment by cmeeren** [comment]
Would be great if this could be changed and backported to 1.1. The limitation simply doesn't make any sense.

**Comment by dgeb** [comment]
The profiles should have been allowed to explicitly define custom query parameters:

> A profile MUST NOT define any query parameters _except custom query parameters_.

Note that in this way profiles can be customized while not coming into contact with 'future' query parameters, which we may or may not introduce.

**Comment by cmeeren** [comment]
Actually, on closer look, the current spec does not prohibit custom query parameters. It says:

> A profile MUST NOT alter or remove processing rules that have been defined by this specification or by an [extension](https://jsonapi.org/format/#extensions). However, a profile **MAY** define processing rules for query parameters whose processing rules have been reserved for implementors to define at their discretion.

Note the last sentence, which explicitly allows query parameters reserved for implementors.

Also, I think the first sentence covers the previous problematic paragraph ("A profile MUST NOT define any query parameters."), so I suggest just removing that paragraph.

**Comment by jelhan** [comment]
> The profiles should have been allowed to explicitly define custom query parameters:
> 
> > A profile MUST NOT define any query parameters _except custom query parameters_.

Agree. But would use the term "implementation-specific query parameters" instead as that one is used in the specification already.

> > a profile **MAY** define processing rules for query parameters whose processing rules have been reserved for implementors to define at their discretion.
> 
> Note the last sentence, which explicitly allows query parameters reserved for implementors.

This is about defining processing rules for query parameters defined by the specification. For example a filter profile defining processing rules for the `filter` query parameter family. It's not about defining additional query parameters.

**Comment by cmeeren** [comment]
Thanks for the clarification. I agree with this phrasing then:

> A profile MUST NOT define any query parameters except implementation-specific query parameters.
