### ISSUE TITLE
Why have "linked" object?

### ISSUE THREAD

**Issue by graza** [json-api/json-api#172]
As I was reading through the spec, I was puzzled as to why there was a need for a primary document and to have linked documents had to be in a "linked" object.  It seemed to me that flattening the document would simplify its access without losing any information since the resource names should be unique.

I dug through different issues and found this by @wycats on issue https://github.com/json-api/json-api/issues/8#issuecomment-17450174 so now I understand the reasoning - that something like this:

```
GET /people/me
```

We can distinguish which document relates to the specific resource path requested versus other documents that may be included in the response.  I have to ask though, is that something that the JSON API spec should be concerned with?  It's a very specific route that is application specific.

The spec as it stands doesn't mandate a single document be returned as the primary.  In fact by choosing under issue #8 to always return an array, the design is able to return multiple "primary" documents.  So I would expect to receive many "people" documents in response to the following request:

```
GET /people
```

The fact that it's "me" that's being returned as a given person document in the response above could be determined in other ways (e.g. an is_me flag on the relevant document) without having to impact the purity of the JSON API specification.

**Comment by dgeb** [comment]
The rationale behind `linked` is explained in commit 5a7b7a2e0e3d14852afc0f5597ef41061db060a8 and issue #74

**Comment by graza** [comment]
@dgeb thanks for those pointers.  I hadn't seen them.  I think that #74 is the same kind of rationale as given in #8.  

And here the question remains:  Isn't that application specific stuff?  The commit refers to pagination, but that also seems application specific as it is said to be in the `meta` top-level object.  At the same time, I do recognise cases where using `linked` is necessary.  But is it a **MUST** level requirement?

I suppose my thinking around this started from the fact that I found these pages through a reference from Ember.js where the REST API is invoked only when the local store doesn't have a particular entity, or it needs to send a change back to the server.  In that case, it's keyed by the `id`.

In the case of creation, where the server is returning the `id` the `linked` object doesn't help anyway.

**Comment by steveklabnik** [comment]
I literally had this conversation in a meeting while this issue was being opened. We should maybe consider adding this information to the FAQ.
