### ISSUE TITLE
JSONRenderer does not extract includes from PolymorphicModelSerializer properly

### ISSUE THREAD

**Issue by dmuseychuk-invgate** [json-api/json-api#1720]
When using `PolymorphicModelSerializer` with `JSONRenderer`, the `extract_included` method is retrieving the base polymorphic serializer instead of the specific serializer corresponding to the object instance. This results in the `includes` not being processed correctly, as the base polymorphic serializer is not equipped to handle the specifics of each derived instance.

It appears that the issue can be resolved by modifying the `render` method to correctly identify and use the appropriate serializer based on the object instance during the rendering process. This adjustment should enable `includes` to function as expected with polymorphic serializers.

```
if serializer is not None:
    # Extract root meta for any type of serializer
    json_api_meta.update(self.extract_root_meta(serializer, serializer_data))
    if getattr(serializer, "many", False):
        ...
    else:
        if isinstance(serializer, PolymorphicModelSerializer):
            resource_instance = serializer.instance
            serializer_class = serializer.get_polymorphic_serializer_for_instance(resource_instance)
            serializer = serializer_class(resource_instance, context=serializer.context)

            fields = utils.get_serializer_fields(serializer)
            ...
```

**Comment by jelhan** [comment]
This repository is about the JSON:API specification itself. Your issue seems to be related to a specific implementation of it. Please move your bug report to the GitHub project of the (python?) library you are using.
