### ISSUE TITLE
Version 1.1 is incomplete about where extension members are allowed.

### ISSUE THREAD

**Issue by FranzDeschler** [json-api/json-api#1733]
In version 1.1 of the JSON:API specification, extension members are only explicitly mentioned in sections 7.1 and 7.2.2.2.
So it seems that extension members are only allowed in the top level document, relationships, and relationship links.

But is this true?
The example code in section 5.4.1 shows an extension member in a resource object.
So it seems that those members are also allowed in resource objects, but section 7.2 doesn´t explicitly mentions extension members.
The same applies for links. Or are extension members only allowed in relationship links?

Maybe there are even more sections that may allow extension members but don´t explicitly state that.
In my view, the specification is incomplete about this and should be updated accordingly.

**Comment by jelhan** [comment]
An extension may define new members anywhere in the document. But an extension must not lessen or remove any processing rules. This requires explicitly mentioning members defined by an applied extension in some cases.

Let me illustrate using this paragraph of [7.1 Top Level](https://jsonapi.org/format/#document-top-level) as an example:

> A document MUST contain at least one of the following top-level members:
> 
> - `data`: the document’s “primary data”.
> - `errors`: an array of error objects.
> - `meta`: a meta object that contains non-standard meta-information.
> - a member defined by an applied extension.

Explicitly listing members defined by an applied extension here allows having a JSON:API documents without any of `data`, `errors`, or `meta` as member but only an extension defined member. The [Atomic Operations extension](https://jsonapi.org/ext/atomic/) relies on that heavily.

I hope this explanation resolved the confusion. I'm going to close this for now. If I missed something or you have follow-up questions, please don't hesitate replying here. I will reopen in that case.
