### ISSUE TITLE
v1.1 docs mix location of "links" for GET vs POST

### ISSUE THREAD

**Issue by Epigene** [json-api/json-api#1745]
Hello,

In current v1.1 docs (2024-05-29), the location of "links" differs for GET responses and POST. I wonder whether this is by design and whether POST response could just reuse #show structure.

Section 8.1.1.1 shows this as an example response for a single resource's GET ("links" are toplevel)
```json
HTTP/1.1 200 OK
Content-Type: application/vnd.api+json

{
  "links": {
    "self": "http://example.com/articles/1"
  },
  "data": {
    "type": "articles",
    "id": "1",
    "attributes": {
      "title": "JSON:API paints my bikeshed!"
    },
    "relationships": {
      "author": {
        "links": {
          "related": "http://example.com/articles/1/author"
        }
      }
    }
  }
}
```

Whereas section 9.1.2.1 shows this POST response example ("links" are in "data"):
```json
HTTP/1.1 201 Created
Location: http://example.com/photos/550e8400-e29b-41d4-a716-446655440000
Content-Type: application/vnd.api+json

{
  "data": {
    "type": "photos",
    "id": "550e8400-e29b-41d4-a716-446655440000",
    "attributes": {
      "title": "Ember Hamster",
      "src": "http://example.com/images/productivity.png"
    },
    "links": {
      "self": "http://example.com/photos/550e8400-e29b-41d4-a716-446655440000"
    }
  }
}
```

**Comment by jelhan** [comment]
Hello,

both is valid. The `links` member can be at multiple places in the document:

> A link’s context is the top-level object, resource object, or relationship object in which it appears.
>
> https://jsonapi.org/format/#document-links

The first example includes a `self` link in the top-level object:

> The top-level links object MAY contain the following members:
>
> -  `self`: the link that generated the current response document.
>
> https://jsonapi.org/format/#document-top-level

The second example includes a `self` link in a resource context:

> The optional links member within each resource object contains links related to the resource.
>
> If present, this links object MAY contain a `self` link that identifies the resource represented by the resource object.
>
> https://jsonapi.org/format/#document-resource-object-links

Best
