### ISSUE TITLE
Updating a to-many relationship in the URL-based approach

### ISSUE THREAD

**Issue by fancyremarker** [json-api/json-api#175]
It's not clear to me from the spec how a to-many relationship should be updated in the URL-based approach. Consider the following example from the spec:

``` json
{
  "posts": [{
    "id": "1",
    "links": {
      "comments": "http://example.com/comments/5,12,17,20"
    }
  }]
}
```

Say I want to remove the comment with ID 5 from this post's comments. According to the spec, I should issue a `PATCH` request with a `remove` operation, a la:

```
PATCH /posts/1

[
  { "op": "remove", "path": "/posts/0/links/comments/5" }
]
```

But in this case, this operation doesn't represent a valid JSON Patch operation on the original document. Perhaps the crux of the problem is that at one point the spec states:

> While to-many relationships are represented as a JSON array in a GET response, they are updated as if they were a set.

But in the case of the URL-based approach, the to-many relationship is represented as a string, not an array.

One potential answer is that instead of representing editable to-many relationships in the form `"http://example.com/comments/5,12,17,20"`, one should always use an opaque URL of the form `"http://example.com/posts/1/comments"`, and then issuing a `remove` operation on the array elements of this resource.

Alternatively, the spec could allow for listing to-many references as an array of URLs, a la:

``` json
{
  "posts": [{
    "id": "1",
    "links": {
      "comments": [
        "http://example.com/comments/5",
        "http://example.com/comments/12",
        "http://example.com/comments/17",
        "http://example.com/comments/20"
      ]
    }
  }]
}
```

And then issuing a `remove` operation:

```
PATCH /posts/1

[
  { "op": "remove", "path": "/posts/0/links/comments/http:~1~1example.com~1comments~15" }
]
```

Which of these two options seems more in line with the spec's intention? I'd prefer not to use the "URL shorthand" approach described in the spec, even though it provides another solution.

**Comment by guillec** [comment]
@fancyremarker as you know from #176 the the JSON Patch path is being discussed but just wanted to suggest an idea.

If you want to remove comment with id 5 

<pre>
{
  "posts": [{
    "id": "1",
    "links": {
      "comments": "http://example.com/comments/5,12,17,20"
    }
  }]
}
</pre>

Why not replace the comments value?

<pre>
PATCH /posts/1
[
  { "op": "replace", "path": "/posts/0/links/comments", "value": "http://example.com/comments/12,17,20" }
]
</pre>

**Comment by fancyremarker** [comment]
@guillec That's a good suggestion, and robust against confused client intent. However, it requires that the client know the current exact state of the related collection, and if (for example) an item is added to to the collection by a second client in between when the first client GETs the resource and PATCHes their change, they will have inadvertently removed the second client's item.

**Comment by steveklabnik** [comment]
Adding to 1.0.

**Comment by m-breen** [comment]
We have had the same issue, specially because the to-many urls we had were getting really big...
We therefore used the "opaque URL" approach as suggested by @guillec

**Comment by dgeb** [comment]
> We have had the same issue, specially because the to-many urls we had were getting really big...

As of #341 (RC2), the spec no longer requires the use of URLs for multiple individual resources.

To-many relationships can be updated as described in the base spec: http://jsonapi.org/format/#crud-updating-to-many-relationships

Or with the Patch extension: http://jsonapi.org/extensions/patch/#patch-updating-to-many-relationships

I'm pretty sure these two sections cover all the issues mentioned here, but please reopen if necessary.
