### ISSUE TITLE
Proposal: Remove limitation against the coexistence of "data" and "errors" top-level members

### ISSUE THREAD

**Issue by NrdyN8** [json-api/json-api#1763]
## Issue:
The current version of the JSON:API spec has an explicit rule disallowing the `error` top-level member and the `data` top-level member from coexisting.

I am failing to see the logical reasoning behind an explicit rule stating they should not coexist. If a request is received, is processable, but results in some errors handling portions of the data then a response with the `data` member and the `errors` member should be returned. 

### Situation: 
- A public facing API for a blogging platform.
- A user DOES have permission to update the body of their article
- A user DOES NOT have permission to update the title of their article
- A 3rd party application has a bug in their editor that submits all data when auto-saving

Original data: 
```JSON
{
    "id": 1,
    "title": "Article",
    "body": "Lorem Ipsum...",
    "author": 1,
}
```

The user sees an edit screen where the title and the body are editable. The user proceeds to assume they can update the title and proceeds to do so.

Request submitted:
```JSON
PUT /articles/1 HTTP/1.1

{
    "title": "Article 1",
    "body": "Dolor sit amet..."
    "author": 1
}
```
In this instance the expected behavior would be for the body of the article to be updated, but the title to not be. To properly notify the end user an error should be returned stating they have insufficient permissions to update the title.

Example response:
```JSON
HTTP/1.1 207 Multi-Status

{
    "data": {
        "id": 1,
        "attributes": {
            "title": "Article",
            "body": "Dolor sit amet...",
            "author": 1
        }
    },
    "errors": [
        {
            "code": 422,
            "title": "Insufficient permissions",
            "body": "Insufficient permissions to edit the title"
        }
    ]
}
```

## Proposal
I would like to propose removing this limitation in the spec and adding a note in the `Errors` section stating that if a request returns `data` and `errors` then it **SHOULD** utilize the 207 HTTP code.

This would allow the JSON:API spec to be more flexible to different use cases while minimizing issues with older implementations of the spec.

---

### PS
I do understand this is a poor example but was the best off the top of my head without getting into the weeds explaining my specific situation. If there is a strong conviction to not have the two members coexist; I understand. I am just at a loss for why an explicit rule is set against something seemingly minor and I am unsure of a clean way to implement this under the existing spec.

**Comment by lode** [comment]
> In this instance the expected behavior would be for the body of the article to be updated, but the title to not be.

I disagree. I much prefer the API to tell me my request is not processable. Otherwise there is the risk that the title and body are out of sync.

---

For me the main reason the have either and not both is that it makes it easier to detect which kind of response I got, and communicate that to end-users. For the same reason I can't get a http status code of both 200 and 400. And if you really need that kind of workflow you can always send updates per field and see which one succeeds and which one fails.

**Comment by jelhan** [comment]
> I am failing to see the logical reasoning behind an explicit rule stating they should not coexist. If a request is received, is processable, but results in some errors handling portions of the data then a response with the `data` member and the `errors` member should be returned.

Forbidding both `error` and `data` in the same document is a consequence of the meaning of error within the specification. An error means that the request was not processed.

What you are looking for is a way to communicate that a request was processed but may have not been sd expected by the client. This could be described as a warning. There is a proposal to support such warnings in addition: #1592.

Are you good with closing this one as a duplicate of #1592?

**Comment by NrdyN8** [comment]
> And if you really need that kind of workflow you can always send updates per field and see which one succeeds and which one fails.

The problem with this is some frameworks, such as Laravel, do not offer a clean way to define a large amount of endpoints and separate the `PUT` and `PATCH` requests. I acknowledge this is an issue with the framework. I just created this proposal just to suggest increasing the flexibility of the JSON:API spec.

---

>What you are looking for is a way to communicate that a request was processed but may have not been sd expected by the client. This could be described as a warning. There is a proposal to support such warnings in addition: https://github.com/json-api/json-api/issues/1592.


For my example above, it could be described as a warning. Another example would be a request to sync objects. If the main object could sync but the child objects could not sync, and I do not wish to include the child objects in the request, it would be incorrect to say the entire request failed because some child objects didn't sync. I will confess this could be solved with notifications via web sockets or long polling.

>Are you good with closing this one as a duplicate of https://github.com/json-api/json-api/issues/1592?

I wouldn't say this is a duplicate because adding another top level member could be resolved by using an extension.

---

Would a valid compromise be to change:
> "The members `data` and `errors` **MUST NOT** coexist in the same document."

To:
> "It is **NOT RECOMMENDED** for the members `data` and `errors` to coexist in the same document."

Then in the Errors section have a disclaimer similar to:
> "While it is **NOT RECOMMENDED** for the members `data` and `errors` to coexist in the same document. If they must coexist in a response then you **SHOULD**/**MUST** utilize a 207 HTTP response code"

This way the spec maintains that the two shouldn't be included together, but in niche circumstances it can be allowed. Therefore increasing the flexibility of the spec?

**Comment by jelhan** [comment]
I don't see a way to move forward in that direction. The `error` is meant for describing why s request was not processed. You are asking for a wax to communicate additional information how the request was processed. You can either use `meta` member for that or an extension-defined member.

Please note that JSON:API is designed for having request either processed successfully or fail entirely. Partial processing may not violate the specification in all cases. But it goes against it's intent.

Some examples you gave indicate that there might be more mismatches between your implementation and the spec. E.g. `PUT` is not supported by the spec.

For implementing a JSON:API in Laravel, I can recommend the [Laravel JSON:API](https://laraveljsonapi.io/) library. It abstracts away a lot of the complexity.

**Comment by NrdyN8** [comment]
Alright. Sounds good. Thank you all for taking the time to respond.
