### ISSUE TITLE
Accept header syntax for multiple extensions

### ISSUE THREAD

**Issue by bkoelman** [json-api/json-api#1768]
What is the syntax for a JSON:API `Accept` HTTP header with multiple extensions? I can't find it in the spec.

Here are some possibilities for a client that wants to use both the `https://my-ext1` and `https://my-ext2` extensions:

1. `Accept: application/vnd.api+json; ext="https://my-ext1 https://my-ext2"`
2. `Accept: application/vnd.api+json; ext="https://my-ext1, https://my-ext2"`
3. `Accept: application/vnd.api+json; ext="https://my-ext1; https://my-ext2"`
4. `Accept: application/vnd.api+json; ext="https://my-ext1"; "https://my-ext2"`
5. `Accept: application/vnd.api+json; ext="https://my-ext1"; ext="https://my-ext2"`

**Comment by jelhan** [comment]
This is defined by HTTP specification.

> Each parameter is usually delimited by an immediately preceding semicolon.

See [RFC 9110: 5.6.6. Parameters](https://httpwg.org/specs/rfc9110.html#rfc.section.5.6.6) for more details.

The correct representation would be:

```
Accept: application/vnd.api+json;ext="https://my-ext1";ext="https://my-ext2"
```

**Comment by bkoelman** [comment]
Thanks!

**Comment by bkoelman** [comment]
The [JSON:API spec](https://jsonapi.org/format/#media-type-parameter-rules) leads me to believe it's 1 instead of 5:
> The values of the `ext` and `profile` parameters **MUST** equal a space-separated (U+0020 SPACE, “ “) list of extension or profile URIs, respectively.

@jelhan Do you agree this overrules the RFC?

**Comment by jelhan** [comment]
> The [JSON:API spec](https://jsonapi.org/format/#media-type-parameter-rules) leads me to believe it's 1 instead of 5:
> 
> > The values of the `ext` and `profile` parameters **MUST** equal a space-separated (U+0020 SPACE, “ “) list of extension or profile URIs, respectively.
> 
> @jelhan Do you agree this overrules the RFC?

Sorry. You are right. The `ext` parameter should only exist once. Listing all extensions as a space separated list. The HTTP RFC is only relevant if having multiple parameters (`ext` and `profile`).
