### ISSUE TITLE
Media Type parameter spec lacks example of multiple values

### ISSUE THREAD

**Issue by Roanmh** [json-api/json-api#1770]
[We noticed](https://github.com/jokiefer/drf-json-api-atomic-operations/issues/2) a minor point of confusion around the Media Type parameter formatting for extensions/profiles:

The examples in [section 5.4.1](https://jsonapi.org/format/#extension-rules) show a space between the `;` and `ext`, but the examples in the [atomic operations extension spec](https://jsonapi.org/ext/atomic/) all exclude this space. Are both options valid?

[Section 5.4](https://jsonapi.org/format/#media-type-parameter-rules) talks about spaces in the extension, but doesn't not provide an example of the space separated list of URI (and where the quotes mentioned in the Note belong), so it is hard to interpret the correct syntax, especially for multiple values of a parameter.

I suspect that the post `;` space is optional but that a correct example of the a parameter with multiple values would be `ext="http://uri.ex/1 http://uri.ex/2".

**Comment by Roanmh** [comment]
possible duplicate of #1768 ?

**Comment by jelhan** [comment]
> possible duplicate of #1768 ?

Yes. But as the question came up twice, let's keep this one open and add an example in the spec. Maybe even an example in addition shown an `Accept` header listing JSON API mime type two times with a different set of profiles. A PR is welcome.

**Comment by jelhan** [comment]
@Roanmh I created #1773 to add an example. Would appreciate your review if you have time.
