### ISSUE TITLE
proposal to make it easier to access properties  

### ISSUE THREAD

**Issue by adardesign** [json-api/json-api#188]
In the example's provided, it is very  inefficient to access properties by a `id` unless you loop the entire `array`, rather then having a array, have a  object as a `hash` which makes it so easy to access the property  as easy as `data.productData.FPRRIG6`   vs  when there are an array you would need to use something like `getProductData("id")` which would need to loop through the entire array till it finds that property.. 

Rather the data should like this:

```
{
  "productData": {
    "FPRRIG6": {
      "id": "FPRRIG6",
      "shortTitle": "w/18-55mm VR Lens, Refurbished by Nikon",
      "show": true
    },
    "FPRRIG5": {
      "id": "FPRRIG5",
      "shortTitle": "18-55mm VR Lens, Refurbished by Nikon"
      "show": true
    },
    "FPRRIG4": {
      "id": "FPRRIG4",
      "shortTitle": "w/18mm-55mm & 55-200 NIKKOR DX Lenses",
      "show": true
    },
    "FPVMBM3": {
      "id": "FPVMBM3",
      "shortTitle": "Digital SLR Camera w/18mm-55mm",
      "show": true
    }
  }
}

```

**Comment by dgeb** [comment]
As discussed in #181 and #182, there is no MUST level requirement that resource `id`s be included in documents. In edge cases that do not include an `id`, it would be impossible to use the format you mentioned here.

JSON API documents are structured to be an efficient transport format, and not necessarily an ideal storage or access format. The expectation is that clients request just the data they need, and have a deserialization process that transforms the entire payload into a usable form for storage and rapid access. JSON API's usage of arrays instead of sets works well for these patterns.

**Comment by adardesign** [comment]
I hear you, but still, if data is going to be consumed by a app that will use the above mentioned proposed schema, then it should be populated in this way to begin with.. and not require post receiving deserialization  processing ... This way the data is in a much linear way... and having such examples in your examples will advocate and introduce this very efficient data structure.    

I see no issue to have it this way **when ID's are used**. and it is still a efficient transport format

**Comment by samwgoldman** [comment]
While it is appealing to use IDs as keys as you've suggested, it's not a slam dunk. In addition to the lack of a required `id` to act as a key, JSON objects don't have an inherent order. It's a common use case to request sorted data from the server, which an object-based serialization would complicate.

**Comment by dgeb** [comment]
@samwgoldman - yes, that's a good point.

@adardesign - because this proposal is incompatible with both sorted results and edge cases in which IDs are not used, I don't see how it could be incorporated in the spec.

@steveklabnik @wycats - any objections to closing this?

**Comment by steveklabnik** [comment]
Yes, I don't see how this can work.

**Comment by steveklabnik** [comment]
(If anything, I'd say that it doesn't matter that you can't access one efficiently from the JSON directly, because the whole idea is that it's loaded in some kind of store. Once it is, that store can support retrieving by ID efficiently)
