### ISSUE TITLE
How set specific top level `links` URL template

### ISSUE THREAD

**Issue by diosney** [json-api/json-api#192]
In the docs is this example, first at **URL Template Shorthands** section:

```
{
  "links": {
    "posts.comments": "http://example.com/posts/{posts.id}/comments"
  },
  "posts": [{
    "id": "1",
    "title": "Rails is Omakase"
  }, {
    "id": "2",
    "title": "The Parley Letter"
  }]
}
```

So, I have this output in my API that imitates that structure:

**GET:** http://192.168.56.3:3000/api/interfaces/ethernets/52f43f4248e5ab55082f8804

```
{
    "links": {
    "ethernets": "http://192.168.56.3:3000/api/interfaces/ethernets/{ethernets.id}",
    "ethernets.addresses": "http://192.168.56.3:3000/api/interfaces/ethernets/{ethernets.id}/addresses"
    },
    "ethernets": [
    {
        "name": "eth1",
        "mac": "08:00:27:18:27:3e",
        "mtu": 1500,
        "status": {
            "operational": "UP",
            "admin": "UP"
        },
        "id": "52f43f4248e5ab55082f8804"
    }
    ]
}
```

This is okey until this.

Now, what I need is to define a top level `links` relationship when I request for `addresses` inclusion that matches that structure, since I'm not sending the `addresses` `id` in an attribute below `ethernets`.

So, the output will be like this one (I put a **XXX** mark to the place I need to fill):

**GET:** http://192.168.56.3:3000/api/interfaces/ethernets/52f43f4248e5ab55082f8804?include=addresses

```
{
    "links": {
    "ethernets": "http://192.168.56.3:3000/api/interfaces/ethernets/{ethernets.id}",
    "ethernets.addresses": {
        "href": "XXX",
        "type": "addresses"
    }
    },
    "ethernets": [
    {
        "name": "eth1",
        "mac": "08:00:27:18:27:3e",
        "mtu": 1500,
        "status": {
            "operational": "UP",
            "admin": "UP"
        },
        "id": "52f43f4248e5ab55082f8804"
    }
    ],
    "linked": {
    "addresses": [
        {
            "address": "192.168.56.3/24",
            "scope": "global",
            "interface": "eth1",
            "broadcast": "192.168.56.255",
            "id": "52f43f4248e5ab55082f8805"
        },
        {
            "address": "fe80::a00:27ff:fe18:273e/64",
            "scope": "link",
            "interface": "eth1",
            "id": "52f43f4248e5ab55082f8806"
        }
    ]
    }
}
```

Something like this would be valid?:

```
 "links": {
    ...
    "ethernets.addresses": {
        "href": "http://192.168.56.3:3000/api/interfaces/addresses/{linked.addresses.id}",
        "type": "addresses"
    }
    }
```

I think there would be no reason to be invalid due the fact that all below `linked` fit itself in the standard, **BUT** since `addresses` are one level below `linked` attribute, maybe is some custom case it don't will fit into JSON API.

If this is not valid then, how can I specify the URL template for the related `addresses` taking into account that I won't be sending the ids along its related `ethernets` but in a separate `linked` object?

**Comment by dgeb** [comment]
The paths used in URL templates should be relative to the primary resource and should not include `linked`.

To ensure that the client knows to traverse the related `address` resources and extract each `id`, you probably want to go with this href in your top level links:

```
"links": {
   ...
   "ethernets.addresses": {
       "href": "http://192.168.56.3:3000/api/interfaces/addresses/{ethernets.addresses.id}",
       "type": "addresses"
   }
}
```

If you choose to include an array of address ids within each `ethernet` document, you could alternatively specify the href to expand that array:

```
"links": {
   ...
   "ethernets.addresses": {
       "href": "http://192.168.56.3:3000/api/interfaces/addresses/{ethernets.addresses}",
       "type": "addresses"
   }
}
```

**Comment by diosney** [comment]
That seems good to me but notice that I won't be sending the `addresses` inside `ethernets`:

```
 "ethernets": [
    {
    "name": "eth1",
    "mac": "08:00:27:18:27:3e",
    "mtu": 1500,
    "status": {
        "operational": "UP",
        "admin": "UP"
    },
    "id": "52f43f4248e5ab55082f8804"
    }
    ]
```

Do your primary example code fit in this use case?

**Comment by dgeb** [comment]
That was my intention. I only included the second example to illustrate how it could be simplified.

I'm beginning to have my doubts about this though, since there is no clear path from an `ethernet` document to its associated addresses. There is only so much work we can expect from a client to translate `ethernets.addresses` into an array of ids. It seems much preferable for the server to do this work by including an array of ids for each `ethernet` document.

**Comment by diosney** [comment]
I agree with that, this will be a lot of more work for the clients.

It should be nice having (finish to read the stament before make any judgement) an exception to the rule that says that when an attribute can't be found in a primary resource then it should look for it in the `linked` tree, but that will be also overkill and for make things simple and nice then no exception deserves to come into the standard.

The thing I was avoiding all this time is to add the `addresses` `ids` array below `ethernets` since I really don't want to allow a request like:

**GET**: http://192.168.56.3:3000/api/interfaces/addresses/ID_1,ID_2,ID_3

but:

**GET**: http://192.168.56.3:3000/api/interfaces/addresses/ID_1
**GET**: http://192.168.56.3:3000/api/interfaces/addresses/ID_2
**GET**: http://192.168.56.3:3000/api/interfaces/addresses/ID_3

and the standard explicitelly tells that the `ids` array should be exploded to fill the URL template to  build the final URL.

Maybe @steveklabnik can take a look into this and help is to clarify this situation?

**Comment by diosney** [comment]
Now with the unification of id and URL styles, it seems that another way to specify to-many relationships was landed:

> As another alternative, a to-many relationship MAY be represented as an array of "link" objects that contain one or more of the attributes: "id", "href", and "type".

```
{
  "posts": [{
    "id": "1",
    "title": "Rails is Omakase",
    "links": {
      "comments": [
        {
          "href": "http://example.com/comments/5",
          "id": "5",
          "type": "comments"
        },
        {
          "href": "http://example.com/comments/12",
          "id": "12",
          "type": "comments"
        }
      ]
    }
  }]
}
```
