### ISSUE TITLE
Profiles

### ISSUE THREAD

**Issue by MajorBreakfast** [json-api/json-api#195]
I really like the many ideas behind json-api. Implementing it fully is currently near impossible, though. There are so many things that are supported. (So many SHOULDs or MAYs) I'm proposing to introduce some kind of profiles to ensure compatibility between APIs and data frameworks.
- Common profile:
  - GET
    - No compound documents (only multiple docs of same type)
    - Simple templates (only for defining the type) `"links": { "posts.author": { "type": "people" }}`
    - Type determines the URL
  - POST only contains one document
  - PUT only for updating the document the URL specifies, not for document creation (because you'd need the id for that)
  - DELETE
- Errors extension https://github.com/json-api/json-api/issues/7
- URL templates profile extension
- Query profile extension
- Multi-Type extension (posts.author is of type people or cats)
- Sort profile extension
- Paging profile extension
- Compound documents GET extension
- Bulk POST/PUT profile extension
- ClientIds profile extension
- JSON Patch extension
- Revisions profile extension
- And other extensions...

What do you think? I'm proposing this because both API implementors and client side data framework authors need a starting point. These are just some rough ideas. Furthermore it makes it possible to categorize discussions and we can also create a compatibility graph between the profiles. For example the error handling becomes more complex if you allow for bulk POST requests.

Every SHOULD in the spec is a thing that...
- an API theoretically implements and thus has to be supported by the client side data framework
- a client side data framework expects and consequently has to be implemented by the API

The idea is that both the client side data framework and the API can be told to stay within a certain subset and everything just works. And I'm really for many MUSTs in these profiles because it's the only way to ensure compatibility.

**Comment by steveklabnik** [comment]
Sorry, I'm not really 100% sure what exactly you're asking here. SHOULDs do not 'have' to be supported. That's why they're SHOULDs.

**Comment by MajorBreakfast** [comment]
I'm asking for a subsets that are clearly defined an labeled as such.

**Comment by steveklabnik** [comment]
Profiles will be built, but that's outside the scope of the specification proper.
