### ISSUE TITLE
Proposal: Allow updates by sending the whole record

### ISSUE THREAD

**Issue by fivetanley** [json-api/json-api#201]
Right now in the current format, I can see that doing PATCH updates is the preferred way to do updates. There does not appear to be an alternative means of updating. After talking with @steveklabnik a few weeks ago, I've finally gotten around to opening this issue. I'm willing to submit a PR if others think this is a good idea.

Basically, I would like to allow updates by sending the whole record. What I mean is, instead of sending a PATCH request, you would send a payload like the following to `/posts/1`:

``` json
{
  "title": "Rails is SO Omakase",
  "published": "2014-02-18"
}
```

At Instructure, we're currently sending updates as an array so it's consistent with our GET requests. So, to update a blog using our API, we use the following format:

``` json
{
  "posts": [
    {
      "id": 1,
      "title": "Rails is SO Omakase"
    }
  ]
}
```

We send it as an array not only for consistent, but so that endpoint can process multiple records in the future. I'm not proposing this instead of the previous payload, but it does feel nice that both updates and GETs are consistent.

I'm not sure I can argue this from a spec perspective, but for people using Rails and Ember Data, sending the whole record for an update means that many existing endpoints don't have to change. You don't have to implement a new adapter for Ember Data, and you don't have to change your existing Rails endpoints to understand PATCH. I've worked in a few Rails apps now and it seems to be a common pattern to accept a `params[:blog]` or just use `params` to feed accepted attributes into `update_attributes` or some similar updating mechanism.

I know JSONAPI isn't just for Rails and Ember Data-based apps, but I've worked with a few REST APIs that allow updating by sending the full document. It seems to be a common idiom in the web API community.

Some questions:
- How would we handle update associations via "links" hash?

**Comment by steveklabnik** [comment]
@wycats had some thoughts about this.

**Comment by wycats** [comment]
My biggest concern is that most of the endpoints you're talking about actually have "PUT as PATCH" semantics and totally ad hoc semantics for updating relationships. "The whole record" really doesn't work sanely if you want to add a record to a has many, and people mostly just solve it totally ad hoc without even thinking about the semantics they expose.

Maybe the solution is a simple PATCH gem for Rails: `model.patch(params[:post])`

**Comment by fivetanley** [comment]
I agree. Thanks.

**Comment by wycats** [comment]
I would for serious be ok with PUT for attributes only if we could hold the line on relationships and insist on PATCH for those.

**Comment by fivetanley** [comment]
I'll open a pull request allowing for PUT for attributes only and then re-close this issue.

**Comment by dgeb** [comment]
I believe `PUT /photos/1` should be equivalent to `PATCH /photos/1` with `"op": "replace"`. Neither option is currently spelled out in the spec - only the updating of individual attributes and relationships via PATCH.

This ties into a larger conversation re: an overarching schema for updating records in #176 and #193. When every request is considered to be operating against a single JSON document (i.e. schema), POST and PUT can be cleanly mapped to PATCH equivalents.

I'll consolidate my thoughts in a gist or PR soon...

**Comment by dgeb** [comment]
However, I don't think it's appropriate to send an array payload with a request to `PUT /photos/1`.

**Comment by wycats** [comment]
I intentionally left out `replace` with relationships from the original draft because the semantics (especially with has-many) are somewhat hairy, and will totally fail under concurrent usage.

As I've said before, I'm totally in favor of replacing attributes, but I have some serious concerns about a `PUT` or `replace` that clobbers entire relationships.

**Comment by steveklabnik** [comment]
Adding this to the 1.0 milestone, as per the discussion in TryGhost/Ghost#2362.

**Comment by wycats** [comment]
I think we should also support `POST`ing to has-many relationships to create a new record and link it to a relationship at the same time.

**Comment by steveklabnik** [comment]
Seems legit.

**Comment by dgeb** [comment]
Bulk updates are now covered by the [Bulk extension](http://jsonapi.org/extensions/bulk/#updating-multiple-resources).

Furthermore, [PUT updates can cover attributes and relationships](http://jsonapi.org/format/#crud-updating).

More specific relationship updates [can be requested at relationship URLs](http://jsonapi.org/format/#crud-updating-relationships).
