### ISSUE TITLE
How express in json-api singleton resources?

### ISSUE THREAD

**Issue by diosney** [json-api/json-api#203]
For instance, I want to provide access to some system information at:

**GET** /system/info

That information could be:
- hostname
- domain
- nameservers

and the like.

Until now I've only seen resource-oriented responses, how to return such resouce in a response with full json-api compliance? Maybe creating some resource like _info_?

**Comment by steveklabnik** [comment]
I'm not really sure what you're asking, to be honest. :/

**Comment by diosney** [comment]
Fair enough.

I want to know whether is this json-api compliant (or at least how to achieve that):

**GET** /system/info

```
{
  "info": [{
   "hostname": "router",
   "domain": "localhost",
   "nameservers": ["192.168.56.2", "192.168.56.3"]
 }]
```

   }

**Remarks:**
- `info` is a singleton resource, I mean, that URL will always lead to only one resource.
- as such, it doesn't need an `id` since it will be always `it`.
- is `info` a json-api compliant resource name?

Thanks

**Comment by steveklabnik** [comment]
Yes! That's perfectly fine. We now don't require `id`, and the only restriction we place on keys is that `id`, `meta`, `links`, and `linked`.
