### ISSUE TITLE
Suggesting values to clients

### ISSUE THREAD

**Issue by guillec** [json-api/json-api#206]
If you have pre-defined values for an attribute what is the best way to tell that to the client? In meta? Not here, in a profile? Any other way? 

Example:

```
#Posts "status" can only be "Posted", "Draft" or "New".
{
  "meta": {
    "status": ["Posted","Draft","New"]
  },

  "posts": [{
    "status": "Draft"
  }]
}
```

Thanks!

**Comment by steveklabnik** [comment]
This is a good question, of which there aren't a lot of answers at the moment.

**Comment by mrec** [comment]
What's the specific use case for needing to tell the client?

json-api is pretty silent so far regarding the best way to communicate errors, but if you took the view that there's no need to tell the client this unless they're trying to set an invalid one, then returning error json that lists the valid values seems a good first step.

If you're wanting something more ambitious, like the ability to build CRUD UI generically based solely on information obtained via the API, then that feels out of scope for this project. I'd probably return the url of a schema document (http://www.q-lang.io/ or equivalent) in meta.

**Comment by guillec** [comment]
The specific use case is that I have a attribute called "status" that can only be "new", "active", "closed". I already return the error message with the correct values but I would like to avoid that by providing the accepted values to start with. Biggest reason is, these values could change in the future, I don't want to break the clients if the do.

**Comment by bartvandendriessche** [comment]
What about a top level `enums` attribute, something like:

``` json
{
  "enums":{
    "posts.comments.status": [ "new", "active", "closed" ]
  }
  "links": {
    "posts.author": {
      "href": "http://example.com/people/{posts.author}",
      "type": "people"
    },
    "posts.comments": {
      "href": "http://example.com/comments/{posts.comments}",
      "type": "comments"
    }
  },
  "posts": [{
    "id": "1",
    "title": "Rails is Omakase",
    "links": {
      "author": "9",
      "comments": [ "1", "2", "3" ]
    }}, {
    "id": "2",
    "title": "The Parley Letter",
    "links": {
      "author": "9",
      "comments": [ "4", "5" ]
   }}, {
    "id": "1",
    "title": "Dependency Injection is Not a Virtue",
    "links": {
      "author": "9",
      "comments": [ "6" ]
    }
  }],
  "linked": {
    "people": [{
      "id": "9",
      "name": "@d2h"
    }],
    "comments": [{
      "id": "1",
      "body": "Mmmmmakase",
      "status": "active"
    }, {
      "id": "2",
      "body": "I prefer unagi",
      "status": "active"
    }, {
      "id": "3",
      "body": "What's Omakase?",
      "status": "active"
    }, {
      "id": "4",
      "body": "Parley is a discussion, especially one between enemies",
      "status": "active"
    }, {
      "id": "5",
      "body": "The parsley letter",
      "status": "active"
    }, {
      "id": "6",
      "body": "Dependency Injection is Not a Vice",
      "status": "new"
    }]
  }
}
```

**Comment by ahacking** [comment]
JSON schema.

Please don't pollute API requests and responses with this stuff.  Soon you will want i18n language mapping too and pattern matching for constraining other fields and field label names. We don't need documentation going across the wire on every request.

Also consider that clients should also send valid full resource representations when not using PATCH and therefore should also include that schema detail on PUT.

What is your semantically barren client supposed to do on create/post in order to get these schema details? I guess you will need a /edit hanging off each endpoint to get a JSON template...

This is what JSON schema is for, it describes JSON structures, value types ranges and constraints. You can reference it using API discovery link headers if you need to.

**Comment by bartvandendriessche** [comment]
You're right, JSON Schema would make most sense.

It would be nice to see this as a recommendation in the spec somewhere.

**Comment by tkellen** [comment]
I'd be open a PR suggesting the combined usage of meta and json schema if anyone in this thread would be willing to create one. For now, I'm going to give this a close due to inactivity.
