### ISSUE TITLE
Clarification re sparse fieldsets

### ISSUE THREAD

**Issue by mrec** [json-api/json-api#207]
In the absence of a `fields` parameter, **MUST** an endpoint return the same fields for a given document regardless of the URL by which that document was requested? Or **MAY** it vary them based on other criteria?

Here's the specific use case that's turning out ugly. Each document has a few small metadata fields (name, description etc) and one or two big non-textual body fields. Expected usage is exactly what you'd imagine: a "list" request that fetches metadata fields for all documents to populate picker UI, and a "detail" request that fetches the body field for a single picked one. 

There are obvious practical reasons why you might not want to return body fields in a list response, even if requested. There may be also be good reasons not to include metadata fields in a detail response, e.g. helping intermediate caches by omitting textual data that would need to vary by user language.

Now, the only tool json-api seems to offer to achieve this is `fields`, which isn't ideal:
- `fields` feels like, and is presented as, a moderately advanced optional feature. This isn't an advanced use case.
- It's more granular than is required. We don't need arbitrary client-specified sets of fields, we just need a couple of predefined sets, presented to clients as "views". 
- It would require clients to know and explicitly list all fields for each view type, which doesn't play well with extensible document schemas and is a long way from the kind of  [Pit of Success](http://blog.codinghorror.com/falling-into-the-pit-of-success/) we strive for in API design.
- Querystring parameters like `fields`, and _especially_ querystring parameters carrying multiple comma-separated values, generate textual variation which has no semantic significance but is pretty much guaranteed to reduce the effectiveness of any cache layer.

So if, for example, an API didn't support `fields`, returned a list view by default and supported a detail view (e.g. as `/things/123?view=detail` or `/things/123/detail`) **only** when a single id was specified, would that be considered conforming?

**Comment by steveklabnik** [comment]
Servers MAY always do whatever they want, as long as it doesn't contradict the spec. If there is open space, they are free to do as they wish.

**Comment by outcassed** [comment]
Lately I'm using JSON-API as a guide when growing my API and a common pattern that I use is this list/detail split where requests that return many results default to a list view that omits larger fields (like hunks of Markdown or HTML, etc).

I'm trying to think of a nice way to request fields that are omitted by default.  ("include_fields=?")

**Comment by dgeb** [comment]
Do `fields` meet your needs? http://jsonapi.org/format/#fetching-sparse-fieldsets

**Comment by outcassed** [comment]
I'm doing something similar to the person who opened the issue where I have documented "views" that are the sets of fields and nested objects that are returned (typically "list" and "full") so it might be best for me to work outside of JSON-API and just offer a way to change that view "view=detail" .. rather than have developers specify the long list of fields that they are already getting.

If I had to do it all over again, maybe I'd scratch the view idea and go with include+fields.  I think that it's fantastic that this project addresses the design decisions that we all have to make over and over again and my "views" are effectively predefined lists of fields/includes.

anyway - mostly just sharing what I ran into because I saw that the issue was raised

**Comment by pnsantos** [comment]
Just to add a sidenote, the Prefer header (http://tools.ietf.org/html/rfc7240) can be used to specify different "views" of a representation (it purpose is for exactly the types of scenarios @caseyf mentioned where you define a set of representation fields and give that group a name).

Don't know if it's worth mentioning :-)

**Comment by mrec** [comment]
@pnsantos - that's interesting and not something I'd seen before, but I ended up avoiding headers for API parameters. They make it much less pleasant to experiment in a browser, and I think caches have a nasty tendency to throw up their hands and run away if they see anything even slightly unusual about a request.

Also, the RFC states:

> The Prefer request header field is used to indicate that particular
> server behaviors are preferred by the client but are not required for
> successful completion of the request.

List versus body doesn't feel like a nice-to-have preference to me; if you want a list view then a body view really isn't going to cut it, and _vice versa_.

**Comment by ahacking** [comment]
@pnsantos thanks for that sidenote, I think the RFC is very relevant here, even if it coarse grained (is minimal vs full representation only). It also has other relevance such as async and time bounded requests.

@mrec You can use browser extensions like Advanced Rest Client which is intended for developers to manage request types, set headers and view decoded JSON. 

I would like to see the concept of attribute sets when specifying what fields to include and perhaps a complement for excluding fields; ie `-fieldname` or `-fieldset` and state rules that the field specification is applied left to right and have a reserved fieldset 'all'.  
There is always going to be the clashing with resource property names problem so some escape rule will be needed when using set names.
