### ISSUE TITLE
Wrap single links inside arrays

### ISSUE THREAD

**Issue by sebgie** [json-api/json-api#210]
I wonder if it would be sensible to wrap single links to ressources into an array and use the plural form for the ressource type? According to the description of singular ressources I will get back the plural form anyway.

> Documents that represent singular resources are wrapped inside an array and keyed by the plural form of the resource type.

The plural form would seem consistent with the expected result to me. Additionally there wouldn't be the need to distinguish between single links and link collections when processing the response.

Example:

```
{
  "posts": [{
    "id": "1",
    "title": "Rails is Omakase",
    "links": {
      "authors": ["9"],
      "comments": [ "5", "12", "17", "20" ]
    }
  }]
}
```

**Comment by paddycarver** [comment]
I was just about to open this issue.

From the current spec:

> The link to each related resource MUST be one of the following:
> - a string or number - to represent a single ID.
> - an array of strings or numbers - to represent multiple IDs.
> - a "link" object that contains one or more of the attributes: "id", "ids", "href" and "type". Note that "id" and "ids" should never be present together.
> - an array of "link" objects

If, like we did with returned resources (See #8), we just return arrays, the parsing logic for this is cut in half with no loss to expressive power.

Is there any reason we'd always return arrays for resources but not for links?

**Comment by BigAB** [comment]
Is it bad form to just add a :thumbsup: comment?

I too think it would be a good idea, does it warrant more discussion or should someone create a pull request and open the discussion there?

**Comment by samwgoldman** [comment]
Some previous discussion: https://github.com/json-api/json-api/issues/142

I feel like this was resolved somewhere else, and I'd like to point there when these issues come up instead.

**Comment by steveklabnik** [comment]
Adding a :+1: is just fine.

**Comment by dgeb** [comment]
Closing due to #341, which expands the definition of a relationship - see http://jsonapi.org/format/#document-structure-resource-relationships
