### ISSUE TITLE
Clarification: Can the href of a "link" object be interpreted as a url template?

### ISSUE THREAD

**Issue by butsjoh** [json-api/json-api#213]
The spec provides use with a toplevel links object to define url template for expanding the relationship and it is clear to me how it should be used. If i would not use toplevel links todo this and want to define a url template on the "link" object of a association would that be allowed? The spec does not say anything about that, but to me it would make sense. I will make it clear with the following examples:

example with toplevel links: everything fine like the spec is saying

``` json
{
  "links": {
    "posts.comments": "http://example.com/comments/{posts.comments}"
  },
  "posts": [{
    "id": "1",
    "title": "Rails is Omakase",
    "links": {
      "comments": [ "1", "2", "3", "4" ]
    }
  }]
}
```

example of not using toplevel links: is it allowed to express href as url template?

``` json
{
  "posts": [{
    "id": "1",
    "title": "Rails is Omakase",
    "links": {
      "comments": {
         // url template allowed?
        "href": "http://example.com/comments/{posts.comments}",
        "ids": [ "5", "12", "17", "20" ],
        "type": "comments"
      }
    }
  }]
}
```

**Comment by dgeb** [comment]
:+1: I agree that this is consistent and should be allowed.

**Comment by butsjoh** [comment]
@dgeb Thnx for replying. Do you think it still makes sense that the url template param should still be {posts.comments} or could it be nicer to express this as either one of the following: 
- singular: {post.comments}
- reference to links section {post.links.comments}
- referring to yourself {self.comments}

For toplevel url templates the documentation is clear on that:

> For each document that the path points to, act as if it specified a relationship formed by expanding the URL template with the non-URL value actually specified.

**Comment by gr0uch** [comment]
It would only complicate a client implementation of JSON API, since then it would have to look for the URL template in two places (probably the resource-level `links` should have priority then).

**Comment by dgeb** [comment]
@daliwali the distinction here is that type and therefore href _may_ vary per link, which couldn't be captured at the top-level. I imagine this will be the exception rather than the rule for most APIs.

@butsjoh good question re: relative vs absolute url template paths ... let me research and think this over.

**Comment by koemeet** [comment]
Is the following not more easy to understand? The links should only refer to the relation right, so with the right url or a list with the corresponding ids. The top level links are only used for templating then.

``` json
{
  "links": {
     // top level template
      "posts.comments": {
         "href": "http://example.com/posts/{id}/comments"
      }
  },
  "posts": [{
    "id": "1",
    "title": "Rails is Omakase",
    "links": {
      "comments": {
        "href": "http://example.com/posts/1/comments"
      }
    }
  }]
}
```

**Comment by dgeb** [comment]
After working through a number of different scenarios while trying to flesh out a more rigorous spec, I have re-thought my position on this. I now think the spec will remain easier to implement and understand if we allow URL templates only in the top-level `links` object. I find the relative vs. absolute path issue difficult to reason about and I no longer see this feature as absolutely critical for specifying URLs for polymorphic relationships. Sorry for the initial support and then flip flop.

**Comment by dgeb** [comment]
URI templates are no longer supported in the spec. Furthermore, `href` has been replaced by `self` links. See http://jsonapi.org/format/#document-structure-resource-urls
