### ISSUE TITLE
Proposal: Support 'increment' operation for PATCH

### ISSUE THREAD

**Issue by sebgie** [json-api/json-api#214]
> For attributes, only the replace operation is supported at the current time.

I would like to propose the support of `increment` operations for `PATCH` as well. One use case that comes to my mind would be a view counter for page views. The use of `replace` is not feasible because it would lead to overwriting views if two or more people would visit a page at the same time.

```
GET /views/1

HTTP/1.1 200 OK
Content-Type: application/vnd.api+json

{
  "views": [{
    "id": "1",
    "count": 20,
  }]
}
```

```
PATCH /views/1
Content-Type: application/json-patch+json

[
  { "op": "increment", "path": "/views/0/count", "value": 1 }
]
```

**Comment by guillec** [comment]
@sebgie not sure if this is the correct place to suggest a new 'op' as the patch functionality is based on RFC 6902.

**Comment by sebgie** [comment]
@guillec you are right, I was under the assumption that PATCH would allow 'increment' operations. 

As it is now I think the only thing I could do is something like this:
`POST /views/1/increment`

Do you have any suggestions how to rephrase the proposal to achieve what I would like to do?

**Comment by guillec** [comment]
Hey @sebgie I feel like this has to be handled by your app logic maybe by doing some kind of locking on the record. This scenario is no different than if two users pull the record of the same user and change then name of that user to be different.

**Comment by ahacking** [comment]
@sebgie, you could implement value coercion in your add and replace operators without breaking RFC 6902.

For example:

```
{ "op": "replace", "path": "/a/b/c", "value": " +=3" }
{ "op": "replace", "path": "/a/b/d", "value": "-=1" }
```

Since JSON is pretty agnostic/spartan in the value domain (is doesn't have a date type) this is arguably in the spirit of its laxness given string/value coercion is a fundamental requirement in practice.

**Comment by dgeb** [comment]
I agree with others that this is beyond the scope of JSON API.

A custom implementation, such as @ahacking's suggestion, should work well.

**Comment by LB-Digital** [comment]
https://github.com/dharmafly/jsonpatch.js/pull/39
