### ISSUE TITLE
Fetching Recursive Data

### ISSUE THREAD

**Issue by lgebhardt** [json-api/json-api#215]
If we have data that is recursive how do we want to specify this in the `include` parameter? For example in a system that tracks comments for a post and each comment can have one or more comments in reply, creating a deeply nested tree of comments. Does JSON-API have an opinion on how to fetch the comment tree?

As it is now I assume `include=comments` gets the top level, `include=comments.comments` gets the first and second level comments. Should there be a way to get the whole comment tree? Maybe `include=comments*`?

**Comment by hpoom** [comment]
Have the same issue. Want to get nested tree with includes. Also would like to know if includes should use the resource type or the key in the top level resource. (I assume key).

So for example if we have:

``` javascript
{
    "books": {
        "id": "16",
        "href": "/books/16",
        "name": "Some book",
        "links": {
            "authors": ["78","36"]
        }
    },
    "links": {
        "books.authors": {
            "href": "/authors/{books.authors}",
            "type": "person"
        }
    }
}
```

Do we `include=person` or `include=authors`. As I said I assume authors.

If we then have.

``` javascript
{
    "employee": {
        "id": "94",
        "href": "/employee/94",
        "name": "Joe Bloggs",
        "links": {
            "manager": ["78"],
            "team": ["127","182","193"]
        }
    },
    "links": {
        "employee.manager": {
            "href": "/employee/{employee.manager}",
            "type": "employee"
        },
        "employee.team": {
            "href": "/employee/{employee.team}",
            "type": "employee"
        }
    }
}
```

I can I assume `include=manager` and that should include a linked block with my manager. Now I want to get my managers manager. I would want to do `include=manager,manager.manager`

**Comment by ahacking** [comment]
If you modeled relationships for all ancestors and all descendants you wouldn't have any issues with recursion.  You could even filter them with query parameters as required.

**Comment by hesalx** [comment]
You can just expose into the `linked` all the resources that ever appear in a queried tree, hm? 
It's clearly said [there](http://jsonapi.org/format/#document-structure-compound-documents) that `linked` object contains `resource objects`, and [there](http://jsonapi.org/format/#document-structure-resource-object-attributes) it's said that `links` (as long as `id`, `type` and `href`) are absoutely legal parts of a `resource object`.
So it should be absolutely OK to link linked resources to other linked resources. With this it's not an issue to build a real tree in your client, I think.

**Comment by hhware** [comment]
One way to do it: allow to specify depth up and down the hierarchy. E.g.

```
/comments/123?include=comments&parent_depth=1&child_depth=2
```

will return comment `123` with its immediate parent, children and grandchildren.

But it might be worthwhile to standardize it in the spec.

**Comment by mrhwick** [comment]
Any update on adding this to the spec? The proposal here seems effective.

**Comment by mrhwick** [comment]
#940 Appears to solve this problem effectively.

**Comment by jelhan** [comment]
Let's consolidate the discussion about a potential extension at one place. Closing this one in favor of #940
