### ISSUE TITLE
Question: How to express/support nested JSON objects?

### ISSUE THREAD

**Issue by butsjoh** [json-api/json-api#216]
Not really sure if this should be questioned regarding the scope of json api, but we are struggling to find a proper way. It think it is somehow related to this issue on the ember data issue tracker: https://github.com/emberjs/data/issues/53. The discussion is about how ember data would be able to extract/define certain parts of a json payload as other model types then the main resource.

The current json api spec has the "links" key to describe relationships of a resource document, but in json api there is nothing really a way to express the concept of "embedded records". According to @wycats:

> ... there are really fundamentally two kinds of embedded records
> - Embedded records that are included with the primary record purely for efficiency. Otherwise, they have their own IDs and can be saved separately.
> - Embedded records that are conceptually a part of the primary record. They may not have their own IDs and may not be saved separately.

That's the research i have done related to the issue we are trying to resolve, now i will try to explain with an example. We have a very abstract api that allows use to define dynamic **properties** for a document of certain **resource_type**. Each of these properties has a meaningful name and also a **kind** which defines how the **value** should be interpreted.

The following example is a json api representation without doing anything special with properties. We define a document of rescoure type "foobar_with_addresses_and_places" which has the properties: name (string), my_addresses (collection of address types) and places (another collection of address types but with different meaning because of the the name places). 

``` json
{
   "resources":[
      {
         "id":1,
         "resource_type":"foobar_with_addresses_and_places",
         "properties":{
            "name":{
               "kind":"string",
               "value":"Foobar"
            },
            "addresses":{
               "kind":"collection",
               "value_type":"address",
               "values":[
                  {
                     "id":1,
                     "street":"Antwerpsesteenweg 5",
                     "city":"Antwerpen",
                     "country":{
                        "code":"BE",
                        "name":"Belgium"
                     },
                     "href":"http://myapi.com/addresses/1"
                  },
                  {
                     "id":2,
                     "street":"Mechelsesteenweg 25",
                     "city":"Mechelen",
                     "country":{
                        "code":"BE",
                        "name":"Belgium"
                     },
                     "href":"http://myapi.com/addresses/2"
                  }
               ]
            },
            "places":{
               "kind":"collection",
               "value_type":"address",
               "values":[
                  {
                     "id":3,
                     "street":"Tisseltsesteenweg 5",
                     "city":"Tisselt",
                     "country":{
                        "code":"BE",
                        "name":"Belgium"
                     },
                     "href":"http://myapi.com/addresses/3"
                  },
                  {
                     "id":4,
                     "street":"Liersesteenweg 25",
                     "city":"Lier",
                     "country":{
                        "code":"BE",
                        "name":"Belgium"
                     },
                     "href":"http://myapi.com/addresses/4"
                  }
               ]
            }
         },
         "links":{}
      }
   ],
   "linked":{},
   "meta":{}
}
```

The above output to me seems not to be really nice and could be expressed (according to my believe:)) in many other ways. Below is just one of them that would makes the most sense to us. It uses the "link" object definition of the spec to define nested collections in a conform way.

``` json
{
   "resources":[
      {
         "id":1,
         "resource_type":"foobar_with_addresses_and_places",
         "properties":{
            "name":"Foobar", // not caring about the kind in this case anymore
            "my_addresses":{ 
               "ids":[1,2],
               "href":"http://myapi.com/addresses/{id}",
               "type":"addresses"
            },
            "places":{
               "ids":[3,4],
               "href":"http://myapi.com/addresses/{id}",
               "type":"addresses"
            }
         },
         "links":{

         }
      }
   ],
   "linked":{ // maybe this is not the correct section to but them, maybe another name would be better?
      "addresses":[
         {
            "id":1,
            "street":"Antwerpsesteenweg 5",
            "city":"Antwerpen",
            "country":{
               "code":"BE",
               "name":"Belgium"
            },
            "href":"http://myapi.com/addresses/1"
         },
         {
            "id":2,
            "street":"Mechelsesteenweg 25",
            "city":"Mechelen",
            "country":{
               "code":"BE",
               "name":"Belgium"
            },
            "href":"http://myapi.com/addresses/2"
         },
         {
            "id":3,
            "street":"Tisseltsesteenweg 5",
            "city":"Tisselt",
            "country":{
               "code":"BE",
               "name":"Belgium"
            },
            "href":"http://myapi.com/addresses/3"
         },
         {
            "id":4,
            "street":"Liersesteenweg 25",
            "city":"Lier",
            "country":{
               "code":"BE",
               "name":"Belgium"
            },
            "href":"http://myapi.com/addresses/4"
         }
      ]
   },
   "meta":{

   }
}
```

I can understand that this is really a specific use case and that the spec cannot really cater to this abstractness. But since ember data is going to support some kind of way to define nested objects the json api sepc could come with a recommendation. Any feedback on this is welcome :)

**Comment by ephrin** [comment]
+1
Hmm. Seems all resources must be self-described by resource presentation?

**Comment by tkellen** [comment]
This is now covered under the [attributes](http://jsonapi.org/format/#document-resource-object-attributes) section of the specification. If this is not sufficient clarification, please create a thread @ http://discuss.jsonapi.org
