### ISSUE TITLE
Linked with link back to root resource

### ISSUE THREAD

**Issue by joshdholtz** [json-api/json-api#217]
What is the correct way to handle this scenario?

I have a `shoe` that links to a `sock`. The linked `sock` the links back to the `shoe`.

I looked through the spec but I didn't see a case like this. Since the `sock` has the `shoe` in the links, does the `shoe` object need to be duplicated in the links?

``` javascript
{
  "shoes" : [
    {
      "id" : 1,
      "links" : {
        "sock" : 1
      }
    }
  ],
  "linked" : {
    "socks" : [
      {
        "id" : 1,
        "links" : {
          "shoe" : 1
        }
      }
    ]
  }
}
```

**Comment by dgeb** [comment]
Your example is consistent with the spec, which states:

> if a primary document is linked to another primary or related document, it should not be duplicated within the "linked" object.
