### ISSUE TITLE
Requesting sorting

### ISSUE THREAD

**Issue by indirect** [json-api/json-api#22]
Crap. I lied. Sorry. I was reading #8, specifically the bits about determining the canonical request object in the response (which is especially thorny since responses could include associations of the same object type). @paddyforan suggested that the response always be an array, but the canonical object always be the first object in an array. This brings up another question -- can clients request a sorting criteria? Sometimes sorting the objects is fast (or free) for the server, and so it might make sense for the client to request a particular sorting order or criteria. Worth adding a canonical example?

**Comment by SphtKr** [comment]
Interested in the answer to this as well. Sorting seems to be one of those things that invokes MVC religious arguments ("sorting is a view concern not a model concern!") but as you mention, with the client-server separation sometimes it's stupid to try and only sort on the client--the paged data use case is a classic example: can't sort on the client if we don't have all the rows! Just as a reference point, OData includes a way to sort returned records (I don't really love OData, it's just something I'm familiar with).

Incidentally, I don't see an issue yet for pagination (save maybe #1), though it's mentioned on the specification page.

**Comment by paddycarver** [comment]
I'd vote that we allow sorting through query parameters, personally. I haven't come across a better way to specify sorting yet, though if anyone has any ideas, I'd love to hear them.

As for the canonical object being first in the array, I can't think of a good example where you'd want to return a canonical object (a request where you simultaneously don't know the ID of the canonical object _and_ you're expecting multiple objects of the same type to be returned) and _also_ want to sort, but I suppose I could be missing something. I think that's a conversation to be carried on in #8, though.

**Comment by steveklabnik** [comment]
This is something you'd put in your profile.

**Comment by indirect** [comment]
Since sorting seems like a very common concern, maybe there could be an example of what this would look like in a profile? I'm guessing it would simply be a paragraph explaining that arrays are sorted by X and can be sorted by Y or Z if such is requested via a parameter named e.g. "sort". Right?

**Comment by steveklabnik** [comment]
Yes.
