### ISSUE TITLE
Updating Multiple Resources

### ISSUE THREAD

**Issue by csexton** [json-api/json-api#221]
Trying to work out the best way to implement the update action in my app, and wasn't clear on the best way to do this.

So the format says we should "Update URLs are determined the same way as `GET` URLs." And it also shows examples of performing those `GET`s with multiple IDs like `http://example.com/comments/1,2,3,4`

Should I do the same thing with an update action, and simply map the IDs in the URL to the JSON in the `PUT` body?

---

So the request might be:

`PUT http://example.com/comments/1,2,3`

With this body (map ID to the position in the array)

``` json
{
  "comments": [
    {
      "id": "1",
      "body": "Mmmmmakase"
    }, {
      "id": "2",
      "body": "I prefer unagi"
    }, {
      "id": "3",
      "body": "What's Omakase?"
    }
]}
```

---

The other option is to include the ID in the body of the JSON and ignore any IDs in the URL.

So the request might be:

`PUT http://example.com/comments`

``` json
{
  "comments": [
    {
      "id": "1",
      "body": "Mmmmmakase"
    }, {
      "id": "2",
      "body": "I prefer unagi"
    }, {
      "id": "3",
      "body": "What's Omakase?"
    }
]}
```

Is there a recommended approach while doing the full update with `PUT`?

**Comment by gr0uch** [comment]
PUT is intended for replacing or creating, I think PATCH is the preferred method for updating. Although it is not explicitly stated in the specification, I believe a bulk PATCH request may be allowed:

```
PATCH http://api.example.com/balls/5,7,11
```

``` json
[
  { "path": "/balls/0/color", "op": "replace", "value": "blue" },
  { "path": "/balls/1/color", "op": "replace", "value": "green" },
  { "path": "/balls/2/color", "op": "replace", "value": "red" }
]
```

In this case, the index in the path corresponds to the order that the IDs appear, since doing a GET on the route would return entities in that order. This is all speculative on my part and it's not clear how bulk updates should be handled.

**Comment by csexton** [comment]
@daliwali in this case I was using PUT to mean replace. 

This was my attempt to be as JSON APIy as I can with the time I have 😁 so instead of fully implementing the preferred PATCH format I was hoping to fit this into a rails app in a reasonable way.

**Comment by dgeb** [comment]
Bulk updates are now covered by both the [Bulk extension](http://jsonapi.org/extensions/bulk/#updating-multiple-resources) and the [Patch extension](http://jsonapi.org/extensions/patch/).

**Comment by KerryJones** [comment]
Extensions are now removed?

**Comment by fredngo** [comment]
Yes, what should we do now for bulk apis?
