### ISSUE TITLE
Needs moar RFC 2119

### ISSUE THREAD

**Issue by steveklabnik** [json-api/json-api#226]
> The top-level of a JSON response will contain the primary document(s) keyed by the plural form of the primary resource type.

'will' doesn't work here. Should this be a `SHOULD` or a `MUST`? In other words, is this response valid:

```
{
  "meta": {
    "last": "/events?limit=10&offset=0",
    "next": null,
    "href": "/events?limit=10&offset=0",
    "limit": 10,
    "offset": 0,
    "previous": null,
    "total": 0,
    "first": "/events?limit=10&offset=0"
  },
  "links": {}
}
```

There's no `events' key.

**Comment by jasonwebster** [comment]
`MUST` makes the most sense to me. No problem with requiring an empty array on the resource's key.

**Comment by dgeb** [comment]
This ambiguity has been removed with #341.
