### ISSUE TITLE
Meta data for individual documents

### ISSUE THREAD

**Issue by jrhe** [json-api/json-api#231]
It would be nice to be able to provide meta data for individual documents.

A supposed use case is as follows. I may be modelling things badly.

So my app uses elasticsearch which produces JSON payloads. In a previous version of the app using Cappuccino we just spat the whole thing out and made sure that we didn't index any fields which shouldn't be returned. We are now rewriting the app in Ember.js as its generally much better. Along with this we are re-modeling the API to follow json-api and make it (mostly) compatible with ember-data.

The JSON payload from elasticsearch looks like this:

``` json
{
  "took" : 108,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 6039391,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "my_river",
      "_type" : "page",
      "_id" : "4175484",
      "_score" : 1.0, "_source" : {"title":"File:Mb-vt29b.jpg","...":"...  "}
    } ,
    "..."
   ]
  }
}
```

The best way I can think to represent this using json-api + meta document keys is:

``` json
{
  "meta" : {
    "took" : 108,
    "timed_out" : false,
    "shards" : {
      "total" : 5,
      "successful" : 5,
      "failed" : 0
    },
    "total" : 6039391,
    "max_score" : 1.0
  },
  "hits" : [ {
    "meta" : {
      "index" : "my_river",
      "type" : "page",
      "score" : 1.0
      },
      "id" : "4175484",
      "title":"File:Mb-vt29b.jpg",
      "...": "..."
    } ,
    "..."
   ]
}
```

It seems more natural than having a seperate resource for a search hit and then a document linked to that, especially considering the meta data in this case is transient.

This might end up adding too much overhead but I thought I'd try making it conform as much as possible first.

I may be barking up the wrong tree, in which case any feedback is appreciated.

**Comment by dgeb** [comment]
As of #341, [`meta` is now allowed in more places](http://jsonapi.org/format/#document-structure-meta):

> As discussed above, the document MAY be extended to include meta-information as "meta" members in several locations: at the top-level, within resource objects, and within link objects.
> 
> All "meta" members MUST have an object as a value, the contents of which can be used for custom extensions.
