### ISSUE TITLE
There's no spec

### ISSUE THREAD

**Issue by jnicklas** [json-api/json-api#233]
Forgive the slightly provocative title, but at the moment, it's entirely unclear which parts of the website are normative and which aren't.

Let me give an example. From the FAQ:

> ### How to discover resource possible actions?
> 
> You should use the OPTIONS HTTP method to discover what can be done with a particular resource. The semantics of the methods returned by OPTIONS is defined by the JSON API standard.

This is _only_ specified in the FAQ. Nowhere else. Is this normative? Is this a SHOULD or a MUST for the server? Note it says "you should", so it could very well be mandatory for the server to respond to OPTIONS, but the spec makes no mention of this either way.

There should be one single document which is the only source of truth for what is and isn't  in the spec. Maybe it's intended to be this page: http://jsonapi.org/format/, but if it is, then it's not very clearly labelled.

IMO the spec should be available on a separate page, with no website chrome around it. One single page which clearly describes everything that's normative.

**Comment by steveklabnik** [comment]
The spec is on the 'format' page. That's the only part that really matters. Everything else is just gravy.

I'm having a hard time not seeing why this isn't clear, which makes sense, since I'm so close to it. ;) I'd be open to a pull request that clarified this.

**Comment by jnicklas** [comment]
The thing is, it doesn't _say_ anywhere that the spec is on the format page. What about the format page makes it stand out as "the spec"? Nothing.

For a good example, compare the STOMP spec: http://stomp.github.io The homepage has an introduction with a bit of background and stuff, and clear, unambiguous links to the different versions of the spec. On the actual spec page there's hardly any chrome, just the navigation links at the top and the header is "STOMP Protocol Specification, Version 1.2". There's absolutely no doubt what is and isn't part of the spec. I don't need to guess.

**Comment by steveklabnik** [comment]
Gotcha. Makes sense. I only closed this because it's not really a bug in the spec, I'm gonna give this some more thought and change this this week.
