### ISSUE TITLE
Hash instead of array

### ISSUE THREAD

**Issue by jonas-jasas** [json-api/json-api#24]
Why not to use hash instead of array?

``` json
{
  "posts": {
    "1": {"title": "Rails is Omakase"},
    "2": {"title": "The Parley Letter"}
  }
}
```

instead of this:

``` json
{
  "posts": [{
    "id": "1",
    "title": "Rails is Omakase"
  }, {
    "id": "2",
    "title": "The Parley Letter"
  }]
}
```

**Comment by GavinJoyce** [comment]
Some context from HN : https://news.ycombinator.com/item?id=5654116

**Comment by lukfugl** [comment]
I understand the momentum of the existing tools for keeping it array based, so I don't expect it to change. That said, I think alexkcd made some good points in the HN thread that could also provide some assistance around the "primary document among others of the same type" problem being discussed in issue #8. So there may be more motivation for reconsidering...

**Comment by mahmoudimus** [comment]
@lukfugl - One of the main reasons that a list is used is because of order. Using a hash indicates that the response is not necessarily ordered. This is subtle, but very important.

**Comment by paddycarver** [comment]
Beyond order, I'd argue for performance. Array operations and hash operations have wildly differing performance characteristics. If people are interested (or think I'm wrong--I may be) I'll write and run some quick benchmarks to illustrate my point.

**Comment by steveklabnik** [comment]
Ultimately, there are pros and cons to each side, and we made a choice towards arrays. There's nothing super bad about hashes, but this really boils down to a bikeshed.

**Comment by wycats** [comment]
In particular, looping over an Array is much faster than looping over an Object in JavaScript. Since a main use-case we have in mind is for a smart client to load the objects into a local store, it's easy for the loading code to index by ID, which will then produce fast lookup by ID later, but fast load initially.
