### ISSUE TITLE
Specifying Callback URL's

### ISSUE THREAD

**Issue by tgroshon** [json-api/json-api#247]
Callback URL's could be addressed more directly.  It is not clear, from my reading of the spec, where it is appropriate to place a Callback URL when one is necessary such as when a **POST** request is made on a service and data is expected to be asynchronously sent to a specified location when ready.

Possible solutions:
- `callback` in Top-level `links`
- `callback` embedded in the resource itself
- `callback` as a URL parameter: e.g. `http://example.com/resource?callback=<url>`

The current spec is not clear on which approach is preferable, and this seems like a legitimate use case.

Any thoughts on this?

**Comment by steveklabnik** [comment]
I'm not sure what benefit we get for calling out callbacks specifically.

**Comment by tgroshon** [comment]
I suppose that's part of my question.  Callbacks tend to have a specific purpose of notifying the caller about some change in state of a resource.  Does the spec care about them?  I supposed since the spec cared to define `href` to mean a specific thing in a resource, that it might also care about callbacks.

If there are no opinions about it, or I am the only one unclear about it, then I suppose that is answer enough and I will just do whatever I like :)

**Comment by steveklabnik** [comment]
That sounds good to me. Give some things a shot, and see if it's something that actually needs support in the spec.

**Comment by tgroshon** [comment]
Will do!
