### ISSUE TITLE
Clarify top level "links" key.

### ISSUE THREAD

**Issue by ethanresnick** [json-api/json-api#250]
If I understand correctly, there are two ways to specify a key–value pair in the top-level `links` section: 
- `"path": "url-template"`, and 
- `"path": {"type": "type", "href": "url-template"}`.

But the URL Templates section, in describing the behavior of the `links` section, only describes the first case. Specifically, it says: "The value of each key is interpreted as a URL template." But, to accommodate the second case, it should read (something like): "For each key, if its value is a string, then its value is interpreted as a url template; if its value is an object, its value's `href` property is interpreted as a url template."

**Comment by dgeb** [comment]
@ethanresnick Good catch! Your understanding is correct. If you're up for it, a PR to clarify these two distinct possible representations would be appreciated.

**Comment by ethanresnick** [comment]
I'm closing this, as I've already submitted the relevant PR.
