### ISSUE TITLE
Per item type in a to-many relationship

### ISSUE THREAD

**Issue by denisnazarov** [json-api/json-api#252]
```
 {
    "id": "1",
    "title": "Rails is Omakase",
    "links": {
      "comments": {
        "href": "http://example.com/comments/5,12,17,20",
        "ids": [ "5", "12", "17", "20" ],
        "type": "comments"
      }
    }
  }
```

What is the correct way to specify an individual type per item in a to-many relationship? The example in the docs has one type for all comments.

Is it:

```
"contacts":[
  {
    "id": "5",
    "type": "email"
  },
  {
    "id": "6",
    "type": "phone"
  }
]
```

**Comment by ahacking** [comment]
Polymorphic types is a point of consternation. You could have type collections at each level or specific levels of your type hierarchy and endpoints for each type which for all intents would make them appear as completely independent resource types, or you may just use the base abstract type for your endpoint.

However in some contexts as you show, you want to use the abstract type and in other cases you may want a more specific type scope. So which collection should you use?

The type specified in the links section should be the collection you would find the resource in regardless of its specific type.

I avoided these kind of issues by using URLs for my links and UUIDs and therefore do not need typed collections to segregate id spaces. The question of what collection a resource is in is never asked.

I also have large collections for a few resource types with a high number of links out and couldn't afford the overhead of explicit ids when linking from a has many. A URL with the parent key works wonders.

You may want to consider link cardinality when designing your API and choice of linking scheme. Similarly the choice of ID has a major impact on how clients can serialize object graphs. Uuids have many advantages at multiple levels of your stack if you have the luxury of that choice just go with them.

**Comment by dgeb** [comment]
As of #341, JSON API now supports heterogenous collections.
