### ISSUE TITLE
Resource Creation Formatting

### ISSUE THREAD

**Issue by thomasdashney** [json-api/json-api#254]
Currently, the documentation is a little bit sketchy on how to create just one resource.. I would expect that there are potentially two ways to create a resource, like so:

"photo": {
  "title": "Ember Hamster",
  "src": "http://example.com/images/productivity.png"
}
or

"photos": [{
  "title": "Ember Hamster",
  "src": "http://example.com/images/productivity.png"
}]
I'm wondering because Ember data implements the former, while some implementations of the json api implement the latter, and the example listed in the JSON-API format doesn't implement either. Clarification much appreciated!!

**Comment by dgeb** [comment]
The former is now covered in the [base spec](http://jsonapi.org/format/#crud-creating) and the latter is covered in the [bulk extension](http://jsonapi.org/extensions/bulk/#creating-multiple-resources).
