### ISSUE TITLE
304 response code for PUT where resource unchanged?

### ISSUE THREAD

**Issue by thomasdashney** [json-api/json-api#255]
I noticed that 204 (No Content) seems like a strange response for when a resource is attempted to be updated (with no change). There is still content there, it just hasn't changed. For this reason, I think it might be necessary to consider 304 (Not Modified) as an alternative.

**Comment by steveklabnik** [comment]
`304` is a 'redirect', but `204` is a 'successful.' 204 is absolutely correct here.

Compare:

304:

> "If the client has performed a conditional GET request and access is allowed, but the document has not been modified, the server SHOULD respond with this status code. The 304 response MUST NOT contain a message-body, and thus is always terminated by the first empty line after the header fields. "

to:

204:

> "The server has fulfilled the request but does not need to return an entity-body, and might want to return updated metainformation. The response MAY include new or updated metainformation in the form of entity-headers, which if present SHOULD be associated with the requested variant. "

No conditional GET has been requested, so 304 is not appropriate.

**Comment by thomasdashney** [comment]
Makes sense! Thanks for clarifying.
