### ISSUE TITLE
PATCH definition is not RFC compliant

### ISSUE THREAD

**Issue by seletskiy** [json-api/json-api#26]
Sorry if I'm duplicating existing question.

What I talking about is the reference on the page http://jsonapi.org/write/#toc_updating-a-document-code-patch-code to JSON Patch draft document. Link on JSON Patch is leading to outdated version of document.

If you look at latest version (http://tools.ietf.org/html/rfc6902#section-4) of proposal, you will see major change in format:

```
{ "add": "foo", "path": "/a/b/c" } # outdated version
{ "op": "add", "path": "/a/b/c", "value": "foo" } # latest version
```

Should it be updated? I could make PR if needed.

**Comment by lukfugl** [comment]
Agree it should be updated; a PR would be excellent (speaking as an involved bystander, not the project owner). If you don't get to it tonight I can make one tomorrow.
