### ISSUE TITLE
Add table of contents to format (specification) document.

### ISSUE THREAD

**Issue by jgornick** [json-api/json-api#265]
When viewing the format documentation at http://jsonapi.org/format/, it would be nice if there was a table of contents to quickly navigate the document.

**Comment by steveklabnik** [comment]
:+1:

**Comment by jgornick** [comment]
Maybe this could be auto-generated using: https://github.com/dafi/jekyll-toc-generator

**Comment by steveklabnik** [comment]
GitHub pages can't use plugins. I think we have to use JS :/

**Comment by dgeb** [comment]
The Format page has gotten a lot leaner now that large sections have been moved to [Extensions](http://jsonapi.org/extensions/) and [Recommendations](http://jsonapi.org/recommendations/).

However, I think a TOC would still be nice.

**Comment by tkellen** [comment]
This will be addressed in #531
