### ISSUE TITLE
Define how to handle resource objects with a compound key.

### ISSUE THREAD

**Issue by jgornick** [json-api/json-api#266]
Currently, resource objects are identified via the resource ID (`id`) attribute:

> Each resource object SHOULD contain a unique identifier, or ID, when available. IDs MAY be assigned by the server or by the client, as described below, and SHOULD be unique for a resource when scoped by its type. An ID SHOULD be represented by an "id" key and its value MUST be a string which SHOULD only contain alphanumeric characters, dashes and underscores.

I'm running into an issue when building an API where a resource is uniquely identified by more than one attribute (e.g. http://en.wikipedia.org/wiki/Compound_key).

For example, let's say we have a `groups` resource type and a `users` resource type. In this scenario, `groups` are unique but `users` are unique based on the the `group` identifier and `user` identifier. 

It's also worth noting that a `user` in a different `group` is a unique resource and does not point back to a common `user` resource.

This scenario could be expressed with the following resource URLs and responses:

```
GET /groups/foo/users/jgornick

{
    "links": [
        "users.self": {
            "href": "/groups/{users.group}/users/{users.id}",
            "type": "users"
        },
        "users.group": {
            "href": "/groups/{users.group}",
            "type": "groups"
        }
    ],    
    "users": {
        "id": "jgornick",
        "links": {
            "group": "foo"
        }
    }
}

GET /groups/bar/users/jgornick

{
    "links": [
        "users.self": {
            "href": "/groups/{users.group}/users/{users.id}",
            "type": "users"
        },
        "users.group": {
            "href": "/groups/{users.group}",
            "type": "groups"
        }
    ],    
    "users": {
        "id": "jgornick",
        "links": {
            "group": "bar"
        }
    }
}
```

Notice that both the `foo` and `bar` group have a user identified as `jgornick`. The URL resource is unique for the type, however, the `users` resource object is not `... unique for a resource when scoped by its type.`. Because a `user` is not unique for it's type, I would not be able to build a resource URL like `/users/jgornick`

I'm looking for some insight on how to handle this type of "compound key" resource type scenario.

Thanks!

**Comment by dgeb** [comment]
A resource must be uniquely identified by its `id` and `type` members, both of which must be strings.

If type/id pairs are not unique in your application, I'd recommend concatenating IDs on the server to make them so.
