### ISSUE TITLE
Update filtering to define strict matching in collections (arrays) and to-many relationships.

### ISSUE THREAD

**Issue by jgornick** [json-api/json-api#267]
The current "Filtering" spec says:

> This specification only supports filtering based upon strict matching.

This is great, however, it doesn't mention anything about filtering on collections (arrays) or to-many relationships.

To take the existing example of filtering on "author", let's assume that there are multiple "authors" for a single post:

```
{
    "id": "1",
    "title": "Rails is Omakase",
    "links": {
      "authors": ["17", "19", "21"]
    },
    "tags": ["foo", "bar"]
}
```

To filter posts on the to-many relationship of authors by value "19", I would expect the request to be: 

```
GET /posts?authors=19
```

When a filter condition is provided for a collection (array) or to-many relationship, I would expect it to filter posts where the value of 19 is IN the authors collection.

Another example would be to filter posts by a tag:

```
GET /posts?tags=bar
```

I would expect the results to include posts that had the value of "bar" in the tags array.

Thoughts?

**Comment by dgeb** [comment]
Filtering rules are now opaque to the base spec, which only reserves the `filter` query parameter and leaves the rest implementations. See http://jsonapi.org/format/#fetching-filtering

However, we could consider expanding the [filtering recommendations](http://jsonapi.org/recommendations/).

**Comment by steveklabnik** [comment]
This is effectively as far as we're going to do at this moment, now that the spec has changed and we have some recommendations. Thanks!
