### ISSUE TITLE
Clarification on PUT request without `id`

### ISSUE THREAD

**Issue by ashishtilara** [json-api/json-api#269]
From http://jsonapi.org/format/#crud-updating-multiple-resources:

The request **MUST** include a top-level collection of resource objects that each contain an "id" member.

Should the following example add a new record?

```
PUT /articles
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "articles": {
    "title": "To TDD or Not"
  }
}
```

**Comment by lucas-clemente** [comment]
I propose clarifying the spec so that `id` is always required in PUTs, including for updating a single resource. This makes de-serialization in server implementations much easier and seems more consistent in general.

**Comment by ethanresnick** [comment]
The spec is already completely clear imo: an id is required, you can't `PUT` to the url for the whole collection, and this request should simply return an error. Probably a 400 Bad Request.

**Comment by dgeb** [comment]
As others have said, this should probably result in a 400 or 422. [The spec is already clear about the requirement for an `id` in resource representations (and the few exceptions allowed).](http://jsonapi.org/format/#document-structure-resource-object-ids)
