### ISSUE TITLE
Clarification on 'Accept' for Creating a Resource with PATCH

### ISSUE THREAD

**Issue by lgebhardt** [json-api/json-api#270]
Is there a reason that the example in Creating a Resource with PATCH contains the `Accept: application/json` instead of `Accept: application/vnd.api+json`?

Also, should `Accept: application/vnd.api+json` be required for all requests like the Content-Type header is required for any requests that contain content?

**Comment by dgeb** [comment]
Content type usage is now more clear in the [Patch extension](http://jsonapi.org/extensions/patch/).
