### ISSUE TITLE
No guidance for use with json-schema

### ISSUE THREAD

**Issue by HelloGrayson** [json-api/json-api#271]
I'm guessing that jsonapi should have a position on whether json-schema should or could be used alongside of. 

Thoughts?

Why - I'm working on a multi-language SOA where there is a benefit in knowing what makes up a given "type".

**Comment by steveklabnik** [comment]
JSON-Schema can never totally describe JSON API, but that doesn't mean it's not helpful at times.

**Comment by HelloGrayson** [comment]
@steveklabnik I'm not talking about using json-schema to describe json-api. I'm talking about guidelines for those who want to use json-schema WITH json-api. Make sense?

**Comment by xiaohanyu** [comment]
+1 for this

**Comment by eneuhauser** [comment]
**Updated:** Moved this to a [pull request](https://github.com/json-api/json-api/pull/440)

I am currently documenting my API that is trying to conform to JSON API using RAML and JSON-Schema. Unfortunately, I am new to JSON API, RAML, and JSON-Schema. I've been following JSON API for some time and just now had an opportunity to start exploring it. I am even newer to RAML and JSON-Schema, but find it a very powerful way to express an API.

As I built out my API, I found it useful to express JSON API in JSON Schema notation. I'm sure I may have misrepresented some things, but I believe [this schema](https://github.com/eneuhauser/json-api/blob/schema/schema) expresses JSON API very concisely and would be a good intro to someone new to JSON API.

Additionally, I feel seeing it in JSON Schema helps solidify some concepts. One question I had while writing the schema is if an `error` response could have a `links` block?

**Comment by kjwierenga** [comment]
Although json-schema can never describe JSON API exhaustively there is merit in having a json-schema that covers as much of the spec as possible. I'm currently using an updated version of @eneuhauser schema to validate JSON API responses using rspec

In `spec/rails_helper.rb`

```
  config.include JSON::SchemaMatchers
  config.json_schemas[:json_api] = 'spec/schema/json-api-schema.json'
```

In my spec:

```
      expect(response.body).to match_json_schema(:json_api)
```

The logical place to host this schema would be at `http://jsonapi.org/schema`. Is there an intention to host this schema within the json-api project?

**Comment by tkellen** [comment]
Closing in favor of the PR. I'm working on house-cleaning so we can focus on stuff like this!
