### ISSUE TITLE
Discuss: Why is property `linked`.<type> an array instead of an object keyed by id?

### ISSUE THREAD

**Issue by geertbrit** [json-api/json-api#274]
Currently `linked` has the following format: 

```
"linked": {
    "people": [{
      "id": "9",
      "name": "@d2h"
    }],
    "comments": [{
      "id": "1",
      "body": "Mmmmmakase"
    }, {
      "id": "2",
      "body": "I prefer unagi"
    }]
}    
```

To me, although I'm pretty new to json-api, it would seem to make more sense to have the arrays be objects mapped by key instead. E.g.: 

```
"linked": {
    "people": {
      "9" : {
        "id": "9",
        "name": "@d2h"
      }
    },
    "comments": {
      "1": { 
        "id": "1",
        "body": "Mmmmmakase"
      }, 
      "2" : {
        "id": "2",
        "body": "I prefer unagi"
      }
    }
}    
```

This allows for: 
- quick lookup by id which will almost always be needed on the client
- trivial dupe checking. 

I don't see any disadvantages. i.e.: relying on sort order for this seems to be weird.

Has this been discussed before? If so, what's the reason it is as it is?

**Comment by wvteijlingen** [comment]
I would say that the current way of wrapping them in arrays is better because it mirrors the way primary resources are returned.

This makes it easier to reuse mapping logic in client libraries.

**Comment by geertbrit** [comment]
@wvteijlingen : ah yes, that probably makes sense. Ok no biggie, it's a oneliner with lodash anyway ;). Cheers.

**Comment by ahacking** [comment]
The thing to remember is results should preserve the order and JavaScript object keys do not have a defined ordering, so on that basis it can never be a viable option.
