### ISSUE TITLE
Design Simplification

### ISSUE THREAD

**Issue by ethanresnick** [json-api/json-api#275]
I've been following this spec for a while, and have been trying to contribute actively more recently. I've also written what I think is the most-complete [server-side JS implementation](https://github.com/ethanresnick/json-api) of the spec.

My overwhelming feeling, which others have also expressed, is that the design is too complicated. This is becoming even clearer to me now that I'm trying to contribute to a [JSON API adapter](https://github.com/kurko/ember-json-api) that could work on the client side. 

So I'd like to propose a design simplification, namely: throwing out the `{"ids": ["x", "y", "z"], "href": "", "type":""}` and `{"id": ["x", "y", "z"], "href": "", "type":""}` representations of resource collections and single resources, respectively. 

The `"id"`/`"ids"` key can be replaced with just a string or array of strings for the id/ids, while the `"type"` and `"href"` info can be handled in the top-level `"links"` tag. If the response has more than one resource, this actually saves data (as the `"type"` and `"href"` info don't have to be repeated in each resource) and, if the response only has one resource, it only costs a tiny bit more data. (And that extra data could be minimized if, as I suggested in [#238](https://github.com/json-api/json-api/issues/238#issuecomment-51873324), clients could request all the API's relationship url templates at once.)

As far as I can tell, having this `"type"`/`"url"` info on each resource's relationships may have [made](https://github.com/json-api/json-api/issues/129) [more sense](https://github.com/json-api/json-api/issues/164) when this spec aimed to support polymorphic relationships, but now I'm not sure there's much point. The only functionality that would be lost by removing these resource/collection representations is the option for a resource/collection to define a unique url that differs from its url template. To me, the value of such custom urls seems dubious, especially in a spec that's all about using conventions to simplify things. And, this makes the work for clients harder, as then the client can't use a generic `buildUrl` function that just depends on the resource's type and id(s); instead it must deal with the individual resources in the response.

[Also, as an aside, I'm still strongly in favor of [removing the resource-level "links" object](https://github.com/json-api/json-api/issues/238), which would immediately make client-side implementation easier (more of the [RESTAdapter](emberjs.com/api/data/classes/DS.RESTAdapter.html) logic could be used) and would solve the "linking in embedded objects" problem. This wouldn't make response documents less informative, either, as the top-level "links" object could easily pick up the slack of identifying which attributes are relationships, with very little extra over-the-wire overhead (or even data savings).]

**Comment by wvteijlingen** [comment]
I've been writing a client framework in Swift that aims to support all jsonapi features. In the process I also ran into some things that I think could be simplified. Right now we have, as far as I can tell, two ways of representing links.

Using a simple id:

``` json
{
  "id": "1",
  "title": "Rails is Omakase",
  "links": {
    "author": "17"
  }
}
```

Using an id/type/href combination:

``` json
{
  "id": "1",
  "title": "Rails is Omakase",
  "links": {
    "author": {
      "href": "http://example.com/people/17",
      "id": "17",
      "type": "people"
    }
  }
}
```

Supporting both these styles increate complexity in parsing code and I think it would be better to pick one of these.

> The "id"/"ids" key can be replaced with just a string or array of strings for the id/ids, while the "type" and "href" info can be handled in the top-level "links" tag.

My interpretation is that this is already possible. Whatever is in the top level links tag takes should be merged with the data in the resource specified link, where the resource specific link takes precedence.

> The only functionality that would be lost by removing these resource/collection representations is the option for a resource/collection to define a unique url that differs from its url template.

While it might not be needed most of the time, I think having this feature makes the spec a little more flexible. I propose we keep this option where possible.

I think the simplest way is to always use the id/type/href combination, both in the resource as in the top level links. Individual parts of this trio can be left out in the resource in favor of the data in the top level. links. This also allows resources to override the data in the top level link. It creates a consistent style, supports templating to reduce data, and support individual overrides of these templates.

This would then be the only way of linking resources:

``` json
{
  "posts": [{
    "id": "1",
    "links": {
      "author": {
        "id": "17",
      }
    },
    "id": "2",
    "links": {
      "author": {
        "id": "18",
        "type": "some-custom-type"
      }
    },
    "id": "3",
    "links": {
      "author": {
        "href": "http://example.com/custom-href",
        "id": "19",
        "type": "another-custom-type"
      }
    }
  }],
  "links": {
    "posts.author": {
      "href": "http://example.com/people/{posts.author}",
      "type": "people"
    }
  }
}
```

**Comment by ethanresnick** [comment]
@wvteijlingen I like that you're trying to unify things while preserving all the expressive power of the current format. If we went with your approach, I'd also suggest replacing the `"id"`/`"ids"` key in the object representation with a `"refs"` key, so that clients don't need to check a different key name for hasMany and belongsTo relationships (though they can still distinguish between them based on whether the value is an array). 

I'm just still not sold that the ability to specify a custom type or url for related resource(s) needs to be preserved. Maybe others who've built apis using the spec could chime in on whether these are features they're using? I know @dbettin mentioned needing this way back in #164, but I'd be curious to know his precise use case. My guess is that it had to do with polymorphism, as in #129, which we've decided in an anti-pattern. As for specifying custom urls that deviate from the template, it's pretty hard for me to imagine how an API would need this; I know it's not something I've needed in my APIs thus far.

Curious what @dgeb and @steveklabnik think

**Comment by wvteijlingen** [comment]
Good suggestions on using `refs` instead of `id`/`ids`. Clients can indeed still distinguish on string/array and null/empty array for empty relationships. This does require that the `refs` are always included though as you noted in https://github.com/json-api/json-api/issues/268. I'm in favor of always including the linked ids anyway. It makes hooking up things much easier client side.

I think the type is useful if the name of the relationship is not be the same as the linked resource type. For example: a post can have a link named `author` which links to a resource of type `users`. Because the type is included here, the client knows that the resource must be found under `/users/{id}` instead of `/authors/{id}`. Without the type, this must be be explicitly configured client side.

I'm partially with you on custom URLs and types that deviate from the template. Most APIs will not need this and thus only include the `refs` in the resource link section. However, the only increase in client complexity will be the logic to merge the top level link with the resource specific link. I think this is a small compromise for a lot of extra flexibility.

**Comment by ethanresnick** [comment]
Hey! So it seems like all the issues raised here have been taken up in #276, so I'm going to close this issue.
