### ISSUE TITLE
Add support for heterogeneous linked data collection

### ISSUE THREAD

**Issue by ahacking** [json-api/json-api#278]
This issue follows some brief discussion in #276, and proposes that the `linked` key ought to accept a heterogeneous collection, just as the `data` key currently does.

The motivation for this proposal is to:
- support identical processing rules for both `data` and `linked` collections
- allow ordering on attributes which may span resource types, eg `updatedAt`
- reduce server side collation overhead, specifically having the server sort resources into typed collections is not friendly to large result sets or streaming.

The above proposal does not intend to address streaming, if there is a desire to solve the streaming/fire-house type problem then additional consideration should also be given to the rule regarding only including a resource once.  That particular rule introduces an unavoidable requirement that a server must perform additional processing or book-keeping to prevent multiple instances of a resource being serialised.  This means servers must solve the [Hamiltonian path problem](http://en.wikipedia.org/wiki/Hamiltonian_path_problem) in order to emit a valid JSON API response, see also [Hamiltonian Path](http://en.wikipedia.org/wiki/Hamiltonian_path).  This is an NP-Complete problem and not easy to solve given an arbitrary graph of interconnected resources.  The partitioning of resources into`data` and `linked` collections also introduces the need to defer or double process results to first emit the match set, and then emit the linked set.  If one NEVER emits linked data, this entire problem reduces to a simpler book keeping exercise, but still requires keeping history as time goes by. If the duplicate resource rule is relaxed, no book keeping history is required and streaming results of any size/length over and arbitrary time period is possible and if partitioning linked data from the match set is removed, linked data can also be serialized.  It is hard to reason that repeating a resource could actually cause trouble in practice, also given a long enough running process this could actually be used to refresh resources and be beneficial. Simple optimisation techniques _could_ be used (eg a small history window) to avoid repetition in small clusters of interconnected resources, but by no means provide a hard guarantee.

**Comment by dgeb** [comment]
I feel that this is consistent with the `data` key for the primary resource. If that is allowed in the spec, then I believe this should be.

I suppose the larger question, as we talk about simplification, is whether both should be allowed in the spec for 1.0. Support for heterogeneous collections is more implicit than explicit currently. If the spec explicitly allows heterogeneous collections, then that leaks into complexities with polymorphic relationships, which [I've explored unsuccessfully](https://github.com/json-api/json-api/issues/276#issuecomment-56960142).

> The above proposal does not intend to address streaming, if there is a desire to solve the streaming/fire-house type problem then additional consideration should also be given to the rule regarding only including a resource once.

These are good points. The duplicate resource rule currently uses **SHOULD NOT** instead of **MUST NOT**, so I think it's probably relaxed enough (although **SHOULD NOT** _should_ be emphasized in the spec - that was an oversight). Here's how the spec reads now:

>  This approach ensures that a single canonical representation of each document is returned with each response, even when the same document is referenced multiple times (in this example, the author of the three posts). Along these lines, if a primary document is linked to another primary or linked document, it should not be duplicated within the "linked" object.

**Comment by dgeb** [comment]
> I suppose the larger question, as we talk about simplification, is whether both should be allowed in the spec for 1.0.

I've been thinking about this for the past few days: I still support allowing the use of `data` for primary resources and, for consistency's sake, allowing `linked` to contain a heterogenous collection.

This will allow the spec to implicitly support polymorphism in what I've come to see as the only sane way: any resource types that may be mixed in a heterogenous collection must share an ID space. Implementations may choose to use UUIDs or perhaps a shared ID scheme and generator across types.

By requiring a unique ID space for any types that may be mixed, we remove the need to specify both ID and type when modifying polymorphic relationships.

I think this approach allows for flexibility without overcomplication. I'll review with @steveklabnik and @wycats soon.

**Comment by dgeb** [comment]
As of #341, the `linked` data collection is now heterogenous. Thanks for the suggestion, @ahacking!
