### ISSUE TITLE
Clarification of updating to-many relationships

### ISSUE THREAD

**Issue by opsb** [json-api/json-api#280]
Currently I understand it that if you update a to-many relationship at it's link url you can only update a to-many relationship is to replace all of the elements with a post e.g.

```
POST /articles/1/links/comments
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "comments": ["1", "2"]
}
```

I believe orbit.js uses a different semantic though, it appears to use POST to _append_ items to the relationship. From an implementation point of view this makes a lot of sense as it means you don't need to retrieve the existing contents of the relationship to add new items.

It would seem to make sense to support both scenarios with PUT/POST i.e.

```
PUT replaces items in a to-many relationship
POST appends item to a to-many relationship
```

I believe this is different to how the spec currently works but I may be misreading it...

**Comment by dgeb** [comment]
@opsb Please see my recent PR #279 which tries to clarify updates to relationships. Here's what it boils down to:

PUT **MAY** be supported to replace to-one and to-many relationships. However, full _replacement_ of relationships is not often appropriate or desired. In those cases, POST and DELETE may be used to add and remove members from the relationship.

**Comment by opsb** [comment]
@dgeb it was that PR which prompted my question, the semantics for to-one were clear but I wasn't sure about the to-many, thanks for clearing it up!

**Comment by dgeb** [comment]
@opsb ok, great - please comment over on the PR if there's anything that could be clarified further in the revised text!

**Comment by opsb** [comment]
@dgeb next week i'm planning on looking at helping out with integrating orbit.js and jsonapi-resources. I think my first step though will be to try and distill the jsonapi spec into a more concrete form i.e. list all of the url structures along with the verb and request/response payloads. I'll concentrate on the interactions I need but maybe it can be expanded later. Have you given any consideration to some kind of tabular format that might serve this purpose?

**Comment by dgeb** [comment]
> next week i'm planning on looking at helping out with integrating orbit.js and jsonapi-resources

That's awesome - thanks in advance :+1: 

> I think my first step though will be to try and distill the jsonapi spec into a more concrete form

This dovetails with the discussion we've been having across several issues about the need to establish  some standard attributes in profiles that control the major options across JSON API. This should pave the way for cleaner implementers. Development of the JSONAPISource in orbit.js and jsonapi-resources should help us iterate on the profile options.
