### ISSUE TITLE
licensing?

### ISSUE THREAD

**Issue by steveklabnik** [json-api/json-api#283]
Obviously CC0 or something like it, but we should maybe be explicit about this.

**Comment by krainboltgreene** [comment]
I think the Creative Commons brand is great for this, since it's a specification.

Though perhaps just straight up Public Domain?

**Comment by steveklabnik** [comment]
CC0 covers jurisdictions where Public Domain doesn't exist.

**Comment by krainboltgreene** [comment]
:+1:
