### ISSUE TITLE
Updating individual resource and attribute

### ISSUE THREAD

**Issue by alexbyk** [json-api/json-api#284]
Hi. I've read a suggested API and don't see a difference between upd. individual res and upd attributes.
http://jsonapi.org/format/#crud-updating-attributes
http://jsonapi.org/format/#crud-updating

``` json
PUT /articles/1
{
  "articles": {
    "id": "1",
    "foo": "bar"
  }
}
```

Does the whole replacement (like MongoDB save() or update() does) makes sense according to this API?

**Comment by dgeb** [comment]
Perhaps the organization of the [Updating Resources](http://jsonapi.org/format/#crud-updating) section could be clearer:
- The first sections describe updating [individual resources](http://jsonapi.org/format/#crud-updating-individual-resources) vs. [multiple resources](http://jsonapi.org/format/#crud-updating-multiple-resources).
- The next sections describe updating [attributes](http://jsonapi.org/format/#crud-updating-attributes) and [relationships](http://jsonapi.org/format/#crud-updating-relationships). 

The concepts for updating attributes and relationships may apply to either individual or multiple resources. There is no discrepancy between the sections. 

There is no concept of "whole replacement" in the spec. This can effectively be achieved by PUTing a complete resource representation (as retrieved via GET).
