### ISSUE TITLE
Any library implementing it?

### ISSUE THREAD

**Issue by alexbyk** [json-api/json-api#286]
Hi. Does actually any client library implementing this API exists? I tried restangular, with some modifications it works, but maybe somone can suggest more suitable opensource solution?

If it doesn't, lets disscuss that.

**Comment by steveklabnik** [comment]
We have a list of implementations here: http://jsonapi.org/examples/

They may not conform to the latest version of the spec, but if they don't, bugs should be filed with their repos, not here.
