### ISSUE TITLE
q: nested attrs without links?

### ISSUE THREAD

**Issue by alexbyk** [json-api/json-api#289]
Hello. I have a collection in mongoDB with sizes as array and prices as subdocuments of subdocuments

```
{
  products => {
    id: 'myId'
    sizes: ['m','l'],
    prices: {
      min: {uah: 100, usd: 8},
      max: {uah: 200, usd: 16}
    }

  }
}
```

How should I represent it according to the specification? Is json above ok? Could a 'sizes' field be an array? Could a 'prices' field be a nested object without links?

**Comment by dgeb** [comment]
Attribute values can be of any type, including arrays and objects.

However, you should create separate resource types for these objects if you want to reference them with ids, create links to other resources from within them, or offer the ability to partially edit their data.

I don't see these particular resources crossing those boundaries, so I think you're fine as is.

**Comment by alexbyk** [comment]
thanks dgeb. I think it'll be usefull to describe in documentation. Because I couldn't find any example of that situation and it is a little bit confusing especially those who use no-sql dbs.

**Comment by dgeb** [comment]
@alexbyk good call - I'll reopen this issue as a reminder to clarify in the spec.

**Comment by ahacking** [comment]
This also touches on #238 as I have products with fields and some of those fields do reference other resources. Eg brand colours and supercedes and also some product fields link to external resources like product safety datasheets . All product fields are modeled as an array of embedded objects very similar to what @alexbyk has done. They are most certainly not resources that stand on their own.

**Comment by ethanresnick** [comment]
I'm pretty sure this can be closed now, since the spec has an explicit section on complex attributes
