### ISSUE TITLE
Meta-information for multiple resources

### ISSUE THREAD

**Issue by GavinJoyce** [json-api/json-api#29]
The `meta` key is currently defined as **meta-information about a resource, such as pagination**.

This seems limiting in cases where we want to return meta information about multiple resources. A couple of possibilities:
1. Extend the definition of meta to possibly include meta-information about multiple resources
2. Allow meta elements per resource

I've implemented `2` in [RestPack](https://github.com/RestPack/restpack-serializer), compound documents include resource prefixed meta elements such as `artists_meta`, `albums_meta` and `songs_meta`:

http://restpack-serializer-sample.herokuapp.com/albums.json?artist_ids=2,3&includes=artists,songs

@wycats also mentioned the possibility of 'meta everywhere' on the HN thread:

https://news.ycombinator.com/item?id=5655327

**Comment by lukfugl** [comment]
It feels like a combination of the two might be appropriate. It feels like there should be at most one `meta` in any object (including the root object), and that `meta` has members for each sibling _in that object_ that is described. Then subobjects may include a `meta` member as well to describe _their_ members.

As an example of a situation where you might want a `meta` in an object other than the root, consider a threaded discussion where a post side-loads the first page of its replies (I'm modeling "posts" and "replies" separately just to avoid the "primary document" issue of #8):

```
{
  "meta": {
    "posts": {
      "includes": ["author", "replies"]
    }
    "replies": {
      "includes": ["author"]
    }
  },
  "posts": [{
    "id": 1,
    "body": "cheese is delicious",
    "author": 1,
    "replies": [1, 2, 4],
    "meta": {
      "replies": {
        "page": 1,
        "page_size": 3,
        "count": 5,
        "page_count": 2,
        "previous_page": null,
        "next_page": 2
      }
    }
  }, {
    "id": 2,
    "body": "I dislike politics"
    "author": 2,
    "replies": [3, 5],
  }],
  "replies": [
    { "id": 1, "author": 2, "body": "except for limburger" },
    { "id": 2, "author": 3, "body": "but I'm lactose intolerant" },
    { "id": 3, "author": 1, "body": "make cheese, not politics" },
    { "id": 4, "author": 4, "body": "american cheese is the best" },
    { "id": 5, "author": 4, "body": "american politics are the best" }
  ],
  "authors": [
    { "id": 1, "name": "George Washington" },
    { "id": 2, "name": "Teddy Roosevelt" },
    { "id": 3, "name": "John F. Kennedy" },
    { "id": 4, "name": "Jim McCarthy" }
  ]
}
```

**Comment by steveklabnik** [comment]
`meta` is intended to be meta information for the document, not attached to a particular value in the response.If you want certain data to be included, just include it in the part under the actual key itself.
