### ISSUE TITLE
Empty responses?

### ISSUE THREAD

**Issue by alexbyk** [json-api/json-api#298]
Hello. The specs says nothing about empty results.
What status should i return when querying
1) A whole collection `/products/`, when the collection exists but contains no items (an empty db table) - `{ products: [] }`?
2) A filtering collection when no items are found `/products/?brand=222`, when brand exists but has no products yet `{products: [], links: { brands: [{id: 222, name: 'awesome'}]}`?
3) The same, but when not only there are no items but also there are no actual brand with that brandId? The same empty result or smthng else?
4) When querying singe resource by id `/product/222`, when there are no items with id 222 -  `{products: []}` or `{ products: null }`?
5) When querying not existing type `/dfswqsdof`?

What status codes should I use for that cases? 204 no content?

**Comment by ahacking** [comment]
Normal HTTP semantics and conventions should apply, json-api does not subvert http. When querying collections it is normal to return an empty result setbas no items matched the query. When trying to GET a resource that doesn't exist, that is a 404 error.

**Comment by alexbyk** [comment]
"Normal HTTP semantics and conventions" - everybody can understand that different way. Right now i use 200,[] for collections that are empty, and 404 for getting individual resources, that don't exist.

But without exact explanation and examples I don't feel confident about that. That's why I opened this issue and provided ambiguous cases.

**Comment by ahacking** [comment]
I don't think you will find the authors of json-api want to overstate what a server should do given HTTP has RFC status.  If servers don't adhere to HTTP semantics then it gets kind of hard to base anything like json-api on top of it.  There are cases (mostly create/update related) where json-api provides some additional clarity.

If you think there is something extra that needs to be said that is generally applicable to all implementations a PR would be welcome.

**Comment by dgeb** [comment]
> Right now i use 200,[] for collections that are empty, and 404 for getting individual resources, that don't exist.

@alexbyk sounds correct. So to go through your examples:

1) `{ products: [] }` is correct
2) `{ products: [] }` is appropriate. No `linked` collection should be returned because there are no primary resources and therefore no related resources.
3) 404 - because the filter points to an unknown item
4) 404 - requested item doesn't exist
5) 404 - type doesn't exist so there's no endpoint to reach

Please let me know if you have questions / differences of opinion on any of these.

> If you think there is something extra that needs to be said that is generally applicable to all implementations a PR would be welcome.

Well said @ahacking

**Comment by alexbyk** [comment]
thanks for your answers )
