### ISSUE TITLE
How to apply this to a pure relationship resource?

### ISSUE THREAD

**Issue by x1a0** [json-api/json-api#302]
For example I have a table stores user's "liked" items. It's a m-to-n relationship. Then I need to expose APIs so client side can get user's likes, as well as adding, deleting, checking, etc.
- How to design the path? should it be like `/likes/:uid/items/:item_id`, or just `/likes/:item_id` and get uid from session for instance.
- The table doesn't have an ID field as it's only simple relationship - 2 fields: `uid` and `item_id`. But ID seems to be important in JsonAPI, is it?

**Comment by hesalx** [comment]
Dedicated resource's ID is not necessary is some cases.
Besides, `/likes/:uid/items/:item_id` looks wrong. `/likes/:whatever_id` should behave like `/likes/:like_id`.
To retrieve user's likes you may want to use `/users/:user_id/likes` or just `/likes` with the defaults of the current user as well.
Your `like` has `user_id` and `item_id`. It's good. In an opposite to `/user/:user_id/likes` you can have `/item/:item_id/likes`.
JSON API restrict ID [to be unique only for a resource object](http://jsonapi.org/format/#document-structure-resource-object-ids), not the whole resource collection. I hope I understood it right, but it's pretty logical as you will see. 
It's obvious that one item can be liked by a single user only once. It's just liked by the user or not. So in this case `user_id` is a unique identifier for a resource `/item/:item_id/likes`. And so you can use `user_id` to determine the exact like of an item, the like on the item by the user. The resource of it would be `/item/:item_id/likes/:user_id`.
And if you have a resource you can do CRUD things with it.
`POST /item/:item_id/likes/:user_id` — The user with ID `:user_id` liked the item with ID `:item_id`
`GET /item/:item_id/likes/:user_id` — Does the user with ID `:user_id` liked the item with ID `:item_id`? (204 No Content / 404 Not Found)
`DELETE /item/:item_id/likes/:user_id` — Remove the like from the item with ID `:item_id` made by the user with ID `:user_id`.
`PUT` has no practical use there.

Have to say that the form `/users/:user_id/likes/:item_id` will have exactly the same usage if you have only one resource type which can be liked. If you have many kinds of them I suppose you to use `/resource/:resource_id/likes/:user_id` with any resources you want to be allowed to be liked.

**Comment by ahacking** [comment]
IMO many to many is one of the most difficult things to implement and done naively can have horrible performance or memory overhead.  I've made comments on other issues w.r.t. passing id's on the many side when you have moderate to high cardinality relationships, (eg users and friends), the id's can really blow out.

As I posted previously:

> I have resources with references to 15,000 items through a many-to-many relationship. Many-to-many is tough, especially when the cardinality gets large. I can't adhere to json-api because it either wants me to list id's explicitly in links, or says I should comma separate them in a href. Well no, that makes the initial response massive and the related query massive too, not to mention inefficient for a server to implement the query. I prefer to use a href that passes the related model id as a query parameter. Its much more succinct to say:
> 
> /api/foos?bar_id=a1210292-025a-44a9-a1b0-14d9e711f6a3
> than
> 
>    /api/foos/134aab44-9e1a-4570-bd57-51db6b2f6a85,.... x15 thousand of them
> 
> Or naively issue 15 thousand GET requests.
> 
> Since I use UUIDs which are 36 bytes \* 15,000 this makes the request URL approx 540KB in size with the comma separators, and it results in a far less concise DB query. My approach has a url length of ~54 bytes and a very efficient db query which is also easy to apply offset and limit for paged results. Since there are various implementation limits for url lengths (as low as ~2000 bytes) the explicit id approach requires one to issue many batches or switch to a POST for 540KB of ids. With a "multi GET" what if one of those 15,000 items gets removed or has the "visible/shared bit" changed? What should the GET response be? Should the whole response fail or should the server just silently drop the invisible ones? I would rather just avoid this kind of problem that json-api leads me into.
> 
> Now whilst the above sounds bad, its just the start.... we have to remember that for all 15 thousand of those results, they also have inverse links back to the original resource collection (since its a many-to-many relationship), so each resource could be carrying 540KB worth of ids assuming balanced many-many cardinalities. This means we end up shipping back 8325000000 link ids, totalling 8GB for that one inverse relation plus the original 540KB when using explicit ids. My non conformant json-api approach ships 15000 urls (791K) plus the initial link url of 54 bytes which is much more palatable. Remember I am only trying to get 15001 resources and only the knowledge of what they may link to, we haven't included other relationships, or even the resource attributes, just a single many-to-many relationship from a single resource with a link cardinality of 15,000 related items.

I have just made a [radical proposal at the end of #276](https://github.com/json-api/json-api/issues/276#issuecomment-61397312) which would if it garners support, both simplify json-api whilst improving its applicability and avoid making any statements about what attributes identify a resource or how resource urls should be structured.  Many concerns would evaporate and basically be solved by utilising link templates more earnestly.  This would allow resources to be identified in any way that makes sense for your implementation. In this proposal "likes" could be identified without complication using generic json-api libraries. At least all of the following url forms would be possible:
-  foreign key from either side:
  - `/item/:item_id/liked_by/:user_id` 
  - `/users/:user_id/likes/:item_id`
- as a "like" resource:
  - using both keys:
    - `/likes/:user_id/:item_id`
    - `/likes/:item_id/:user_id`
  - using a surrogate key:
    - `/likes/:uuid`
  - using a composite key:
    - `/likes/:user_id+:item_id`
    - `/likes/:item_id+:user_id`
  - as params:
    - `likes?user=:user_id`
    - `likes?item=:item_id`
    - `likes?user=:user_id&item=:item_id`
- or something else I haven't thought of.

**Comment by steveklabnik** [comment]
We don't make requirements on URL structure, but we do have reccomendations now: http://jsonapi.org/recommendations/#urls

 We only require strings for IDs, so UUIDs are just fine.
