### ISSUE TITLE
Integration with "Problem Details for HTTP APIs" (aka JSON Error Objects)

### ISSUE THREAD

**Issue by dzrw** [json-api/json-api#307]
> This document defines a "problem detail" as a way to carry machine-
>    readable details of errors in a HTTP response, to avoid the need to
>    invent new error response formats for HTTP APIs.
> 
> ...
> 
> The data model for problem details is a JSON [RFC7159] object; when
>    formatted as a JSON document, it uses the "application/problem+json"
>    media type.

See: https://tools.ietf.org/html/draft-ietf-appsawg-http-problem-00

At least be aware of this effort -- it would be nice to have alignment on representing errors.

**Comment by ahacking** [comment]
Yes it and the Nottingham draft (https://datatracker.ietf.org/doc/draft-nottingham-http-problem/) has been considered in #208 and #234 and #281.

It doesn't actually solve the problem that needs to be solved, so I have to beg to differ, and say **no** it would be hurtful to have alignment with such a spec which seems to be conceived in a vacuum. A single problem description is just not useful, you cannot identify and return validation problems for multiple fields which may be present on an arbitrary object graph with it.

Please close.

**Comment by dzrw** [comment]
Thanks, I'll close after reading the links.

**Comment by ahacking** [comment]
One other thing I forgot to mention is that switching content-types is kind of nasty as well when the application has asked for the json-api content type it gets back a foreign content type.

**Comment by dzrw** [comment]
> switching content-types

Of course, I would have expected an embedding, not a reuse of the content type.  But that's neither here nor there.

**Comment by ahacking** [comment]
We do expressly allow for foreign content types in the spec for those who feel compelled to do so. See the errors section:

"Implementors MAY choose to use an alternative media type for errors."

I must say though, I can only see this kind of MAY actually hurting interoperability and ensuring more pain for implementers.

**Comment by asbjornu** [comment]
@ahacking:

> A single problem description is just not useful, you cannot identify and return validation problems for multiple fields which may be present on an arbitrary object graph with it.

The format can be extended with any property you may want, so if you're able to express what you want in regular JSON, you can do so with `application/problem+json` as well. The value of having a standard-based format with custom extensions, will in time **increase** interoperability, not hurt it.

> I must say though, I can only see this kind of MAY actually hurting interoperability and ensuring more pain for implementers.

I'd imagine you'd only return `Content-Type: application/problem+json` if the request contains `Accept: application/problem+json`, so I don't understand the "hurting interoperability" argument.

**Comment by ethanresnick** [comment]
> I'd imagine you'd only return `Content-Type: application/problem+json` if the request contains `Accept: application/problem+json`, so I don't understand the "hurting interoperability" argument.

Yup, and JSON:API totally allows you to do this today; nothing in it prevents users from applying standard HTTP content negotiation. (That said, any generic JSON:API client is probably already going to support the JSON:API error format, so adding support for problem+json errors, and perhaps defining a mapping between the two, is likely just to be extra work.)
