### ISSUE TITLE
Consider support for the WebDAV SEARCH verb (RFC 5323)

### ISSUE THREAD

**Issue by dzrw** [json-api/json-api#308]
The GET verb is traditionally used for fetching a resource, a collection of resources, and a subset of a collection of resources where the constraints are typically expressed by query parameters. 

Unfortunately, when queries become complex (as in https://github.com/json-api/json-api/issues/204#issuecomment-37792372), the tendency is to invent new syntax for query parameters, or to abuse the POST verb.

[RFC 5323](http://tools.ietf.org/html/rfc5323#section-2) defines a SEARCH verb to handle this case.

> The client invokes the SEARCH method to initiate a server-side
>    search.  The body of the request defines the query.
> ...
> The SEARCH method plays the role of transport mechanism for the query
>    and the result set.  It does not define the semantics of the query.
>    The type of the query defines the semantics.
> ...
> SEARCH is a safe method; it does not have any significance other than
>    executing a query and returning a query result (see [RFC2616],
>    Section 9.1.1).

Here we have an **idempotent** complex query operator that unfortunately lacks (a) attention, and (b) a JSON representation.

In the olden days, we were limited to GET and POST by the predominant web servers.  A JSON API spec could throw off those constraints.

**Comment by dzrw** [comment]
(I'm not suggesting that that spec is anything great... it's actually kind of a mess.  The valuable part, however, is the idea that we could have a standardized idempotent complex query verb for requesting subsets of a collection of resources.)

**Comment by gr0uch** [comment]
So, what you are suggesting is a JSON request body for initiating SEARCH requests?

What came to mind was the [MongoDB query syntax](http://docs.mongodb.org/manual/tutorial/query-documents/), though this is too specific to a particular data store. Are there any other existing standards?

**Comment by dzrw** [comment]
> So, what you are suggesting is a JSON request body for initiating SEARCH requests?

Right, for example `curl -X "SEARCH" --data '{"weight":1}' http://example.com/friends`.

> What came to mind was the MongoDB query syntax, though this is probably too specific to a particular data store.

Actually, database constraints are a pretty good place to start.  They've got fields, limits, and inequalities.  We'd need to add on syntax for plucking properties from a nested object (possibly within an array).

The MongoDB queries operate on collections of documents which is what a JSON-API endpoint returns anyway - a collection of resource documents.  It might work just fine.

**Comment by ahacking** [comment]
I have had my own concerns with the current query parameter approach in json-api. I wasn't particularly fond of having filtering terms mixed in with fieldsets/includes, and sorting as there are too many top level keywords which could clash with domain attributes/keys.

I would prefer to at least have clear separation of the query terms, fieldsets and sorting under separate keys.

Taking this a step further with a search object could be a nice approach for building complex query languagues but it makes referencing things via a url impossible. ie it is nice to be able to use a url that finds all related comments to a post, eg: `/comments?post=:id` or  non query based`/posts/:id/comments`. This is important as you either want to include those urls in responses or be able to build urls to related resources using link templates.

So I don't believe it could be viable as the only way to search for things, and adding it to the spec would  impose an unnecessary burden on server implementations which would not be useful for most.

Given that urls are what drives the web and that you certainly couldn't bookmark a query url that required a search object in its payload, it doesn't seem to align with the REST architectural pattern.

**Comment by dzrw** [comment]
> Taking this a step further with a search object could be a nice approach for building complex query languagues but it makes referencing things via a url impossible. ie it is nice to be able to use a url that finds all related comments to a post, eg: /comments?post=:id or non query based/posts/:id/comments. This is important as you either want to include those urls in responses or be able to build urls to related resources using link templates.

Please don't misunderstand - I'm not suggesting that simple queries of the form `GET /comments/posts/:id` or `GET /comments?post=:id` be abandoned in favor of another solution.  

Rather, I'd encourage the authors to consider using a custom verb and a simple JSON search object instead of building a bespoke query language out of query parameters.  The former is something that is easy for browsers to work with, but the later will require client framework support.

Regarding link templates: They could be expanded to support an optional request body.  Consider that a robust search operation would likely be rendered as a combination of HTML form elements rather than a single hyperlink.  Currently, this common use-case is thrown into the kitchen sink that is POST.

> Given that urls are what drives the web and that you certainly couldn't bookmark a query url that required a search object in its payload...

Bookmarks are an affordance for human users, but an API spec is for consumption by machines.  As such, I would consider "suitability for bookmarks" to be out-of-scope unless I've misunderstood the purpose of this spec (again - not dismissing the role of query parameters and the GET verb in, for example, emails).

**Comment by kevin-brown** [comment]
My thoughts on this can be summed up by something @ahacking mentioned.

> So I don't believe it could be viable as the only way to search for things, and adding it to the spec would impose an unnecessary burden on server implementations which would not be useful for most.

While I believe adding a `SEARCH` functionality for APIs could be very useful, I do not think the JSON API specification is the place where that should be enforced.

I'm a fan of the JSON API specification right now as it avoids digging into a lot of the special cases and tries to cater to the most common cases.

**Comment by dzrw** [comment]
@kevin-brown There is a straight-forward mechanical translation between the current specification for query parameters (fieldsets, includes, etc.) and an equivalent JSON request object -- in fact, I would be extremely surprised if existing client and server libraries didn't already generate a suitable intermediate AST for handling these queries.  It would be helpful from an interoperability standpoint if the specification stated that compatible implementations MAY implement this equivalent operation using the SEARCH verb with search object payload.

That said, generating a filtered subset of a collection is a common operation and manipulating JSON objects is the bread-and-butter of a JSON-based API, so I'm bit wary of a spec that delegates query to a custom DSL embedded in query parameters.

Consider: If URLs are supposed to identify resources, and verbs identify common operations on resources (as per Fielding), then what is the meaning of a PUT operation on a URL with such a JSON-API query string?  (Nonsense, most likely.)

My personal opinion is that it's strange and broken to embed complex projection, filtering, and sorting operations in a URL if the goal is to produce a machine-navigable REST-styled protocol.  Though as I mentioned earlier, I think concessions must be made for simple queries given the limitations of, for example, email clients.

**Comment by ahacking** [comment]
@politician I am not speaking for json-api current, but performing a PUT on a URL with query parameters would be equivalent to updating whatever the GET of same URL would return.

So, if those parameters scoped/filtered a result set which is a resource as far as HTTP is concerned, (eg using filters and `fieldsets` / `includes`),  then a PUT would simply replace that resource representation.  It would be a genuine way to update many "sub-resources" in a single request.

According to HTTbis (now RFC 7231):

>   HTTP does not define exactly how a PUT method affects the state of an
>   origin server beyond what can be expressed by the intent of the user
>   agent request and the semantics of the origin server response.  **It
>   does not define what a resource might be, in any sense of that word,
>   beyond the interface provided via HTTP.  It does not define how
>   resource state is "stored", nor how such storage might change as a
>   result of a change in resource state, nor how the origin server
>   translates resource state into representations.**  Generally speaking,
>   all implementation details behind the resource interface are
>   intentionally hidden by the server.

And:

>   **A PUT request applied to the target resource can have side effects on
>   other resources.**  For example, an article might have a URI for
>   identifying "the current version" (a resource) that is separate from
>   the URIs identifying each particular version (different resources
>   that at one point shared the same state as the current version
>   resource).  A successful PUT request on "the current version" URI
>   might therefore create a new version resource in addition to changing
>   the state of the target resource, and might also cause links to be
>   added between the related resources.

There is nothing strange or wrong with performing a PUT on a resource with a query string.

I have a [proposal at the end of #276](https://github.com/json-api/json-api/issues/276#issuecomment-61397312) which would allow resources to be identified by whatever the server supports and at the same time reduce the surface area of json-api by avoiding prescribing resource structure and resource identification.  Performing a PUT with query string would certainly be permissible, my current API does just that to allow both GET and PUT of a set of related resources identified by a foreign key, eg "/comments?post=:post_id"

**Comment by ahacking** [comment]
@politician I didn't comment on one of you previous statements:

> Regarding link templates: They could be expanded to support an optional request body. Consider that a robust search operation would likely be rendered as a combination of HTML form elements rather than a single hyperlink. Currently, this common use-case is thrown into the kitchen sink that is POST.

Link templates wouldn't support this, but my proposal for link transforms certainly would as the intent is to allow for not just constructing a url, but a request which could include headers and payload. It would allow for request signing and whatever future requirements are needed.  Presently the only transform being suggested is one that generates a request url based on RFC 6570 (ie basically what json-api currently does).

My approach to specs is to say as little as possible but say enough so that a FULLY CONFORMANT general implementation is not only straight forward, it in itself will cater for all aspects of the spec without having a sea of MAYs in the spec. MAYs are generally evil and often result in poor interoperability as each implementation chooses a different subset. I see link transforms as a way out of the MAY dilemma that json-api currently has because it has made statements and choices about resource structure and resource identification. The outcome is we take nothing away and everyone can represent resources however they please and identify them however they want, so there is no friction or compromise yet we can all use common implementations that are fully conforming to all aspects of the spec rather than cherry picking the bits we need because json-api currently says too much.  The intent is for JSON-API to be applicable for many more use-cases it currently cannot cope with whilst having a smaller surface area.

**Comment by dzrw** [comment]
> I am not speaking for json-api current, but performing a PUT on a URL with query parameters would be equivalent to updating whatever the GET of same URL would return.
> 
> So, if those parameters scoped/filtered a result set which is a resource as far as HTTP is concerned, (eg using filters and fieldsets / includes), then a PUT would simply replace that resource representation. It would be a genuine way to update many "sub-resources" in a single request.

(I think we might be in violent agreement.  Do you consider the query string to be part of the identity of a resource? I don't, so take the following with a grain of salt...)

It would be incorrect to say that PUT on a collection resource would merely update the subset of the items identified by the query string - instead, it would replace the collection because PUT is defined as an idempotent operation (http://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.1.2).  The bulk update interpretation you've articulated is more aligned with the role of PATCH - I would expect that presenting a PATCH request to a collection resource would merge the collections (insert, update, delete) - no query string necessary.

> It does not define what a resource might be, in any sense of that word, beyond the interface provided via HTTP. It does not define how resource state is "stored", nor how such storage might change as a result of a change in resource state, nor how the origin server translates resource state into representations. 

In the common special case where a resource identifies a collection there are well-understood broadly-applicable operators for working with lists of items (take, map, filter, sort, etc).  It seems like a reasonable idea to standardize access to such resources so that these projection, filtering, or sorting operations can be performed by either the client or the server.

> ... my proposal for link transforms ... is to allow for not just constructing a url, but a request which could include headers and payload. It would allow for request signing and whatever future requirements are needed.

Your link transforms proposal in #276 is more robust than RFC 6570, but I'd like to play with a JavaScript library which implements it.  **Is such a library available?**

> MAYs are generally evil and often result in poor interoperability as each implementation chooses a different subset.
> ...
> The intent is for JSON-API to be applicable for many more use-cases it currently cannot cope with whilst having a smaller surface area.

I'm supportive of this argument, as well as of the idea that providing a set of composable tools tends to produce better outcomes than a monolith.

**Comment by ahacking** [comment]
@politician ...

> (I think we might be in violent agreement. Do you consider the query string to be part of the identity of a resource? I don't, so take the following with a grain of salt...)

I do because it returns a representation  of a resource. The query params are scoping something on the server. That's why if I only requested people whos name start with 'M' and a status code I should be able to update the status of those resources by sending back what the server returned with the modified status codes using the same URL. It is idempotent and fully conforming with HTTP. Now there is a chance new sub resources could have been created or modified starting with 'M' between the GET and the PUT which would destroy sub-resources and this can be protected against in the normal way with HTTP headers.

We perceive attributes in json as part of a resource endpoint but I say that's just a mental construct and no different to a GET on what we call a 'collection endpoint' which just happens to contain sub resources. We can certainly be as coarse or fine grained as the server supports, anything returned from GET is a resource representation and if PUT is supported for that resource it must follow HTTP semantics.

Access controls are another scoping/sub-setting mechanism and also can remove aspects of a resource from the awareness of the client and those clients should be able to update what they are allowed to based on the representation they receive. Passing an api key either in the request params or a header conveys the scoping.

> Your link transforms proposal in #276 is more robust than RFC 6570, but I'd like to play with a JavaScript library which implements it. Is such a library available?

It is just a proposal at this stage and I would like some broad consensus and to work through all the pesky the details for a PR to the spec first.

There hasn't been much feedback or interest at this stage. I would like json api maintainers to seriously consider my proposal and I am certainly open to working with everyone so I'd like to give it a chance to either sink or swim before packing up and developing a rival specification. :p

**Comment by tkellen** [comment]
I appreciate the exploration here guys. This could definitely be considered for an extension in a post 1.1 world (when we have proper support for extensions). You can see our current roadmap here: http://discuss.jsonapi.org/t/json-api-weekly-meeting-june-22nd-2015/23

Even though I am giving this a close now, please understand that we're closer than ever to considering stuff like this! I've made a note in a master issue (#794) to re-visit this when we're ready.
