### ISSUE TITLE
Proposal: broken nested linked resources without referential links

### ISSUE THREAD

**Issue by kurko** [json-api/json-api#314]
According to the spec, `linked` resources don't include `links`. Thus, the basic semantic format for compound documents is this:

```
{
  "posts": [{
    "id": "1",
    "title": "Rails is Omakase",
    "links": {
      "comments": ["9"],
    }
  }],
  "linked": {
    "comments": [{
      "id": "9",
      "text": "lolwat"
    }]
  }
}
```

When using `include`, such as `GET /posts?include=comments.author`, the reference between comments and author would be broken.

```
{
  "posts": [{
    "id": "1",
    "title": "Rails is Omakase",
    "links": {
      "comments": ["9"],
    }
  }],
  "linked": {
    "comments": [{
      "id": "9",
      "text": "lolwat"
    }],
    "authors": [{
      "id": "10",
      "author": "Wally"
    }]
  }
}
```

How would you know that `authors` belong to `comments`?
### Proposal

I propose enforcing `links` presence in every described resource.

**Comment by hesalx** [comment]
Funny, I was always sure of the opposite.

http://jsonapi.org/format/#document-structure-resource-objects

> Resource objects have the same internal structure, regardless of whether they represent primary or linked resources.

http://jsonapi.org/format/#document-structure-resource-object-attributes

> There are four reserved keys in resource objects:
> - "id"
> - "type"
> - "href"
> - "links"

`linked` resources are equal in rights with their top-level siblings.
There are just lack of examples with `links` inside `linked`.

**Comment by kurko** [comment]
You're right. Silly me.

Thanks a lot!
