### ISSUE TITLE
Requirement to use camelCase

### ISSUE THREAD

**Issue by Niklas9** [json-api/json-api#323]
I would like to consider forcing the use of camelCase naming in this standard.
As it's JSON as in JavaScript Object Notation and it might be one of the only thing that's consistent in JavaScript - example - it is Array.prototype.forEach and not Array.prototype.for_each.

(I doubt this hasn't been discussed here before, but I couldn't find anything about it.)

**Comment by kevin-brown** [comment]
I don't think this should be enforced by the specification.

This isn't something that should vary greatly between languages, and I can't understand why it would necessarily make a difference if snake_case or camelCase (or another variation) is being used. APIs aren't only consumed by JavaScript clients, and I can see valid arguments for enforcing other casing styles ([`ember-json-api`](https://github.com/kurko/ember-json-api) uses dashes, [`drf-json-api`](https://github.com/kevin-brown/drf-json-api) uses underscores, [the rails implementation](https://github.com/rails-api/active_model_serializers) might also), and those are just a few examples of the implementations that currently exist for JSON API.

**Comment by wvteijlingen** [comment]
The fact that there are now already three different implementations indicates to me the need to specify a preferred style. I think we could use a SHOULD for this, so we can at least add a recommendation, but still allow API authors to deviate.

I personally use underscores, but either style is fine by me.

**Comment by vslinko** [comment]
:+1: for SHOULD

**Comment by wvteijlingen** [comment]
Any other opinions on a preferred style? If not I would like to add this to the spec as:

> Each attribute **SHOULD** be formatted using `underscore_case`.

**Comment by vslinko** [comment]
:+1: for `camelCase`

**Comment by vslinko** [comment]
Because most API clients is JavaScript applications which is `camelCased`.

**Comment by gr0uch** [comment]
I don't think the spec should be at all concerned with naming, and the co-author also disagrees with enforcing naming standards in issue #127.

**Comment by wvteijlingen** [comment]
I agree that the spec shouldn't strictly define the naming scheme. But why shouldn't the spec make at least a recommendation using 'should'? It provides a base on which authors of generic client libraries can build. It still allows you to deviate if you want to.

**Comment by timbunce** [comment]
If the spec makes a recommendation using 'should' then some 'authors of generic client libraries' are more likely to only support the recommended style, perhaps out of personal preference and/or natural laziness, and the 'should' in the spec will be used to defend that position. Then people wanting to provide an API to a large system that uses the other style are less likely to choose JSON-API.

In my view:
- The way multi-word key names are composed should be outside the scope of the JSON-API spec. It's just a name.
- Adoption of JSON-API will almost inevitably be hindered by recommending one style over another.
- There are more important issues to discuss and resolve.

**Comment by dgeb** [comment]
We've gone with a ["recommendation" for dasherized](http://jsonapi.org/recommendations/#naming). This is not a part of the base spec and of course won't be enforced. In #341, we originally made this a requirement of the spec, but there was a lot of pushback and it was moved. Ultimately, names and URLs are opaque to the spec.

**Comment by garrettmac** [comment]
Thought I was worth sharing  [Google JSON Style Guide](https://google.github.io/styleguide/jsoncstyleguide.xml?showone=Property_Name_Format#Property_Name_Format), where:

> * Property names must be camel-cased, ascii strings.

This should be reason enough to adapt camelCase so I created a PR https://github.com/json-api/json-api/pull/1247
