### ISSUE TITLE
requesting multiple resources with commas vs semicolons

### ISSUE THREAD

**Issue by tkellen** [json-api/json-api#330]
To my mind, a GET for resources with a comma delimited list of primary keys (e.g. `/resource/1,2,3`) should return the resources in the order specified. Perhaps an unsorted representation would be `/resource/1;2;3`?

Thoughts?

**Comment by wvteijlingen** [comment]
I don't see any upside to supporting both ways. Sorting can be specified using the `sort` parameter.

**Comment by bintoro** [comment]
Semicolons are sometimes substituted for ampersands as query string parameter delimiters, so I'm not a fan of overloading them with potentially conflicting meanings.

**Comment by dgeb** [comment]
The concept of a URL that addresses multiple individual resources is no longer present in the spec.

See https://github.com/json-api/json-api/issues/335#issuecomment-74960071
