### ISSUE TITLE
Status Codes for simple GET requests

### ISSUE THREAD

**Issue by amcaplan** [json-api/json-api#331]
I realize that status codes are usually pretty much "check [the official spec](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html)," but given that certain cases tend to engender discourse, I'm thinking that "your anti-bikeshedding weapon" should give certain basic guidelines on proper status codes for GET requests.

The particular example where I'm currently feeling some pain is a case where a collection resource is being requested with particular filters that yield an empty collection, e.g. `/posts/487/comments` or `/comments?post=487` or `/posts/487/comments?page=10` (in cases where post 487 exists).  I've seen some [rather](https://groups.google.com/forum/#!topic/api-craft/wngl_ZKONyk) [lively](http://programmers.stackexchange.com/questions/203492/when-to-use-http-status-code-404-in-an-api) [debate](http://programmers.stackexchange.com/questions/199742/restful-api-design-what-should-i-return-if-there-are-no-rows) and [strong opinion](https://www.brightpearl.com/developer/latest/concept/empty-list-response-code.html) out there on whether these should return a 200, 204, or 404, and have been engaged in some (friendly) bikeshedding about this issue.

I am inclined to support 200 for the described situations based on my interpretation of the HTTP spec, but regardless, I think it would make sense to address the issue not as a specific question but as part of generally specifying common cases of GET request status codes.  We don't need to copy the HTTP spec, but I think specifying the most common situations and questionable cases would be very helpful.

**Comment by tkellen** [comment]
![http request flowchart](https://raw.githubusercontent.com/wiki/basho/webmachine/images/http-headers-status-v3.png)

**Comment by amcaplan** [comment]
@tkellen I need a poster of this. Now. :clap:

**Comment by jokeyrhyme** [comment]
The current specification declares:

> The response document for a 200 OK MUST include a representation of the updated resource(s) as if a GET request was made to the request URL.
> But this is for read-write requests and not specifically for read-only requests.

One could interpret this to mean that HTTP 200 indicates that the body can be parsed as a JSON API response document. So _if_ a `GET /posts` request (when no posts exist) returns a 200, then the body should be something like `{ "posts": [] }.

HTTP 204 should only be used when the body is left empty, and HTTP 404 doesn't really need a body either in terms of the JSON API specification.

Until there's more guidance about GETs on empty collections, I think I'll stick to 200.

**Comment by ethanresnick** [comment]
@dgeb I think this can be closed! It seems to be covered in the spec by the text that says:

> A server MUST respond to a successful request to fetch a resource collection with an array of resource objects or an empty array ([]) as the response document's primary data.

That said, if we wanted to make it slightly more explicit, we could change the following sentence in the "Top Level" section from:

> A logical collection of resources (e.g., the target of a to-many relationship) MUST be represented as an array, even if it only contains one item.

to 

> A logical collection of resources (e.g., the target of a to-many relationship) MUST be represented as an array, even if it only contains one item **or is empty**.

**Comment by tkellen** [comment]
:+1: I believe you're right @ethanresnick.  Would you mind opening a PR that references closing this issue with that tweak?

**Comment by ethanresnick** [comment]
@tkellen Done!
