### ISSUE TITLE
Support filtering for a null value

### ISSUE THREAD

**Issue by SphtKr** [json-api/json-api#334]
In the current [filtering](http://jsonapi.org/format/#fetching-filtering) or future (#293?) filtering mechanism, can we designate a way to query for a null value? This may have implications for how various implementing languages treat NULL vs. undefined or whatever, but the scope of what I'm discussing here is that if a resource can return `key: null` in JSON, I should be able to filter as `?key=null` _somehow_ and retrieve those objects.

Use cases:
- A post without an author
- Distinguish between `summary === null` vs. `summary === ''`

I'm agnostic as to how, and I'm not even sure I have a good idea to suggest (`?author=%00`? probably not...).

It might be worth mentioning that this could affect #267 as well...i.e. should specifying a filter value of null on a to-many relationship designate zero related objects?

**Comment by SphtKr** [comment]
In particular, [here](https://github.com/SphtKr/JSONAPI.NET/pull/16#issuecomment-70813410) we have to decide whether we will support querying for null values of a string field, or support querying for empty string values. It's not really possible to support both, so we have to choose one in our library implementation...which will annoy half of our users either way.

**Comment by dgeb** [comment]
Filtering rules are now opaque to the base spec, which only reserves the `filter` query parameter and leaves the rest implementations. See http://jsonapi.org/format/#fetching-filtering

However, we could consider expanding the [filtering recommendations](http://jsonapi.org/recommendations/). 

I think `null` as filter value seems fine.

**Comment by tkellen** [comment]
@SphtKr Like @dgeb I am open to considering this as a non-normative recommendation. Please open a PR for this if you'd like to see this happen!

**Comment by henrymazza** [comment]
The params parsers today for a url like `/api/v2/sales?filter[date]=` generates a params hash like `{“filter”=>{“date”=>”"}}`. But if we lose the equal sign ( `/api/v2/sales?filter[date]`) it generates a hash like `{“filter”=>{“date”=>nil}}`, which the filter ignores (`SELECT "sales".* FROM “sales” WHERE 1=0 …`).

Perhaps this behavior can be derived from here. Or it’s a bad idea. Anyway, who you recommend to do this?
