### ISSUE TITLE
ambiguity for /resource/id,id,id

### ISSUE THREAD

**Issue by tkellen** [json-api/json-api#335]
If you request `/resource/id` and it isn't present, a 404 response is expected. In the case of a request `/resource/id,id,id` where one of the IDs is not present, should the collection be returned without the missing item, or should the whole resource be a 404?

**Comment by gr0uch** [comment]
To keep error handling as simple as possible I think returning a 404 with a message stating which ID could not be found would probably be the best way. There is no 2xx HTTP status code that would fit this situation. It may also be a defensive strategy against clients that assume that 2xx status means everything went OK.

**Comment by dgeb** [comment]
The concept of a URL that addresses multiple individual resources is no longer present in the spec. It was incompatible with heterogenous collections and could realistically hit URL length limits.

Of course, an implementation could still request multiple individual resources via a `filter` request - e.g. `/posts?filter[id]=1,2,3`. However, such a request would only return matches, not a 404 for any non-matches.
