### ISSUE TITLE
ambiguity for updating related data

### ISSUE THREAD

**Issue by tkellen** [json-api/json-api#337]
The spec indicates that relationships can be updated via an optional links key in the payload. 

e.g.

``` js
{
  "articles": {
    "title": "Rails is a Melting Pot",
    "links": {
      "author": "1"
    }
  }
}
```

What do you do in the case of a client that sends this?

``` js
{
  "articles": {
    "title": "Rails is a Melting Pot",
    "author_id": "2",
    "links": {
      "author": "1"
    }
  }
}
```

**Comment by gr0uch** [comment]
Ignore `author_id`, that key should have nothing to do with the spec?

**Comment by tkellen** [comment]
Resolved by a clarifying MUST in an upcoming PR: 
https://github.com/dgeb/json-api/blob/v1rc2/format/index.md#resource-attributes-
