### ISSUE TITLE
RestKit support

### ISSUE THREAD

**Issue by SPopenko** [json-api/json-api#338]
Hi guys,
Does anybody has experience to support json-api standard with RestKit mapping especially if project uses CoreData. Any recommendations or best practice?

Thanks.

**Comment by stevenharman** [comment]
@SPopenko, you might have better luck, and a higher-bandwidth conversation, over in one of the [support channels](http://jsonapi.org/about/#channels)?

**Comment by steveklabnik** [comment]
This tracker, as @stevenharman notes, is just for the spec itself. I would love to have any client, including RestKit, support JSON API, but it's not really releavnt here, so I'm going to give it a close. Thanks!
