### ISSUE TITLE
ambiguity with null relations and the top level linked key

### ISSUE THREAD

**Issue by tkellen** [json-api/json-api#339]
if a relation in the links key for the current draft of the spec is null, should there be an associated empty collection in the top level `linked` key?

**Comment by gr0uch** [comment]
This is indeed ambiguous, but I would be in favor of omitting an empty collection in the `linked` object because it does not add any information.

**Comment by dgeb** [comment]
I agree with @daliwali. I don't think an empty array associated with `linked` adds value to a response.
