### ISSUE TITLE
Specify how to encode IDs with commas (possibly other characters?) in URL

### ISSUE THREAD

**Issue by SphtKr** [json-api/json-api#340]
This is a dupe of #69. If we would rather reopen that one I'm fine with that, but this still hasn't been answered.

The spec states:

> The URL for multiple individual resources SHOULD be formed by appending a comma-separated list of resource IDs to the collection URL.
> 
> For example, the photos with IDs of "1", "2" and "3" will collectively have the URL:
> 
>    /photos/1,2,3

But, if an ID _has a comma as part of the value_, e.g. `DOE,JOHN` or `45.6,-93.51`, it will be treated as two separate IDs by a spec-compliant service. **There is no way to communicate to a server that one of these IDs is a single ID and not two IDs.** 

Percent-encoding the comma (e.g. `DOE%2CJOHN`) is not sufficient, because the HTTP server is required to decode `%2C` to `,` before passing the value to the application layer. The only valid percent-encoding solution would be to _double_ percent-encode the value, such as `DOE%252CJOHN` But this would have to be specified either in this spec or possibly in RFC6570, though I don't see it there (really the multiple-ID in the URL part of the spec isn't covered by RFC6570 anyway I don't think, so that's probably not applicable).

Additionally, simply assuming that double-percent encoding is the answer has larger implications. This would mean that at the application layer, _the entire string of IDs passed to the URL would always have to be percent-decoded_--so then you have a problem if an ID contains a `%` character, because it would attempt to decode the value...and so on.

Some history, #69 was superceded by #190, which attempted to limit the characters valid in an ID...but that was superceeded by #209, which chose _not_ to limit the characters allowed in an ID. So this question is back to square one.

**Comment by dgeb** [comment]
The spec no longer requires URLs for multiple individual resources. Furthermore, the contents of both URLs and IDs are opaque to the spec (IDs must now simply be strings).
