### ISSUE TITLE
Is a relationship a "field"?

### ISSUE THREAD

**Issue by jfinkels** [json-api/json-api#342]
The [Sparse Fieldsets](http://jsonapi.org/format/#fetching-sparse-fieldsets) section of the documentation is not clear about what constitutes a "field". Is a linked relationship a field? In the section [Resource Attributes](http://jsonapi.org/format/#document-structure-resource-object-attributes), the term "attribute" is used for any key in a resource other than the four reserved ones. Maybe "field" should be changed to "attribute"?

**Comment by steveklabnik** [comment]
You may want to check out https://github.com/json-api/json-api/pull/341

**Comment by jfinkels** [comment]
I'll take a look at the changes there, thanks.

**Comment by steveklabnik** [comment]
(I didn't check to see if it answers your question, but if it doesn't, raising it over there seems a good idea :) )

**Comment by dgeb** [comment]
@jfinkels the intention is that a "field" can be either an attribute or relationship. We should either define "field" or just say "attribute or relationship".

**Comment by jfinkels** [comment]
This is has been fixed, as it now says "The value of the parameter refers to an attribute name or a relationship name."
