### ISSUE TITLE
Media type versioning

### ISSUE THREAD

**Issue by gr0uch** [json-api/json-api#345]
The spec seems to have changed rapidly and drastically over the course of a few months, 2 things we don't want in an API. The changes are breaking and backwards incompatible.

I noticed the addition of parameters in the spec for the media type, so why not include version as well? It could look like:

```
Content-Type: application/vnd.api+json; version=1.0.0-rc.2
```

The server could respond with semver:

```
Content-Type: application/vnd.api+json; version=^1.0.0-rc.2
```

If no version is specified, it should just assume the latest version. Thoughts?

**Comment by steveklabnik** [comment]
We do not plan on ever introducing backwards incompatible changes after 1.0.

**Comment by gr0uch** [comment]
:+1:
