### ISSUE TITLE
Are embedded objects allowed for fields?

### ISSUE THREAD

**Issue by counterleft** [json-api/json-api#347]
Hey @dgeb and friends,

Given #341, and

> Any other member in a resource object represents an "attribute", which may contain any valid JSON value.

what is the spec's stand on embedded json objects as attributes? For example, we have the models, "product", "product-option" and "price". A product has options and options have prices. A couch is a product. The black leather and brown fabric are the options. Each option is priced in USD and CAD. A price will never stand on its own; it always belongs to an option. An option always belongs to a product; an option isn't shared with other products.

Should the options and prices be modeled with `links` and `linked` or can they be embedded into the representation of the primary resource (`data`) since their lifecycle is tied to that resource?

The two different approaches shown here: https://gist.github.com/winterchord/58391f01dd0bc87944ac

**Comment by csantero** [comment]
We support embedded json object attributes in [jsonapi.net](https://github.com/SphtKr/JSONAPI.NET). I feel like that approach makes more sense than coming up with surrogate ids for these objects and then extracting them into `links`.

**Comment by dgeb** [comment]
I believe that objects are fine as attributes as long as they are wholly dependent upon the parent resource. This means that requests can never address the object directly, but can only modify it through the parent resource. Furthermore, wholly dependent objects should not be shared across resources.

If you feel tempted to add `type` and `id` fields to your object attributes, then they are probably resources themselves.

Last but not least: if you are in doubt, just create separate resources.
