### ISSUE TITLE
request clarification: conflict with sparse fieldsets and required fields

### ISSUE THREAD

**Issue by jasonkarns** [json-api/json-api#349]
Presently, to respect Sparse Fieldsets a server _MUST NOT_ return fields other than those listed in the `fields` query param. This is at odds with the requirement that a resource object _MUST_ contain both `id` and `type` fields.

I'm assuming that a resource requested with `fields=name` will still include `id` and `type` along with `name`.

So is the client required to always explicitly request the `id` and `type` fields (if specifying fields)? Or are `id` and `type` just assumed to be included?

**Comment by dgeb** [comment]
> Or are id and type just assumed to be included?

Yes, I think that has to be true. Thanks for picking up on this conflict. We should correct the Sparse Fieldsets section.

**Comment by jasonkarns** [comment]
> Yes, I think that has to be true.

I figured as much. Otherwise it would have been a rather odd requirement on the client. The example given didn't help clarify, since it explicitly requested `id` and `type` anyway.

**Comment by jfinkels** [comment]
So the server should ignore a request to include `id` and `type`, and always include them anyway? For example,

```
GET /articles/1?fields[articles]=id
```

Will return

```
{"data": {"type": "articles", "id": "1"}
```

**Comment by dgeb** [comment]
@jfinkels I believe so. The requirement to include `id` and `type` with each resource is pretty absolute.

**Comment by jfinkels** [comment]
Should the self link always be included as well?

I think an example in this section would be very helpful.

**Comment by dgeb** [comment]
Clarification provided via b7fe0e06c8a0e8e3fb6929470323f3cb70785c8b

> Should the self link always be included as well?

The `self` link isn't a MUST requirement.
