### ISSUE TITLE
Changelog of Major Revisions

### ISSUE THREAD

**Issue by fny** [json-api/json-api#352]
Just noticed that the root key was changed from a pluralized resource name to `data`. At first I thought I was going crazy. It would be very nice to have a list of the major revisions to the spec.

**Comment by steveklabnik** [comment]
We had https://github.com/json-api/json-api/pull/341 as a huge discussion about all these changes.

We will be updating http://jsonapi.org/#update-history with any changes that happen post 1.0, which are expected to be entirely additive, and very, very few. but pre 1.0 it's very difficult to maintain one, so we haven't.
