### ISSUE TITLE
The term "rel" is being used in a different way than the HTML spec

### ISSUE THREAD

**Issue by reinh** [json-api/json-api#36]
In the [HTML4 spec](http://www.w3.org/TR/html4/struct/links.html#adef-href) and [HTML5.1 draft](http://www.w3.org/html/wg/drafts/html/master/single-page.html#attr-hyperlink-href) the `rel` attribute is used to specify the "role" of a link. In the current JSON-API spec, however, it is used to specify the links themselves. I think this mixing of metaphors may be confusing to some people (myself included).

I would suggest instead using `refs`, which maps to HTML's use of the `href` attribute, or `links` as used by HAL.

This would also preserve `rel` for more idiomatic uses, for example an "extended" reference specification:

``` javascript
{
  refs: [{
    rel: 'next',
    ref: 'http://example.com/pages/2'
  }]
}
```

**Comment by steveklabnik** [comment]
By breaking up the keys this way, you don't add a whole lot, but you do make it a lot harder to access.

The current way:

``` ruby
rels["next"]
```

this way:

``` ruby
refs.first{|k, v| k == "next"}["ref"]
```

That said, we picked `rels` because we did, no reason. `refs` would be just fine, but they're always composed of a relation and a link, so I don't think `ref`s is 'mixing metaphors' exactly.

**Comment by reinh** [comment]
@steveklabnik The example is completely contrived. Please throw it out if it's getting in the way of discussing what I think is important: choosing a good name for the attribute that contains the links/references.

To use HTML terms, they are "links" that are composed of a "rel" (the type of link) and a "ref" (the link target). Perhaps "links" is the most appropriate term?

**Comment by benhamill** [comment]
Maybe a better example:

``` js
{
  'links': [
    'next': 'http://example.com/pages/2'
  ]
}
```

I'm pretty impartial. Just trying to aid discussion.

**Comment by steveklabnik** [comment]
Sure, I was just trying to answer both parts. If you just want to focus on the second part, that's cool, I just didn't want to ignore part of what you're saying :)

**Comment by lausobo** [comment]
`links` fits the principle of least astonishment if it's being used in other standars while still being correct.

**Comment by reinh** [comment]
@luisobo It's also used by [HAL](http://stateless.co/hal_specification.html), an alternative JSON hypermedia format specification.

**Comment by reinh** [comment]
@benhamill Yep, that's what I'm thinking. The key/value pairs are "rel"/"ref" pairs in HTML parlance and the whole thing is a collection of "links". Seems to suit.

**Comment by lausobo** [comment]
@reinh also [JSON schema](http://json-schema.org/latest/json-schema-hypermedia.html#anchor6) and [Collection+JSON](http://amundsen.com/media-types/collection/)

**Comment by reinh** [comment]
@luisobo Seems good.

**Comment by daetal-us** [comment]
I agree with @luisobo

**Comment by lukfugl** [comment]
:+1: `links`

**Comment by steveklabnik** [comment]
Discussed this with @wycats last night, "rels" was mostly chosen to pick something. Being consistent with HAL and CJ is a Good Thing. Changed.
