### ISSUE TITLE
Rename resource attribute `id` 

### ISSUE THREAD

**Issue by hhware** [json-api/json-api#362]
The application behind the API may be implemented using object attribute naming conventions and other considerations which may be in conflict with conventions of JSON API. Specific example can be found in #361, so I am not repeating it here.

If no solution to the general problem described in #361 can be attained for one reason or another, I would like to propose to at least change the name of the mandatory API resource attribute `id` to something else. The best candidate I can think of is `identifier`. It does not seem to compromise on anything: one word, no artificial prefixes, the meaning is exactly what is expected. I believe that 2 vs 10 characters is not a crucial argument for a format designed primarily for machines. 

Less suitable options I can think of are `key` and `handle`.

**Comment by mattecapu** [comment]
`response.data.identifier` is a bit too verbose to me

**Comment by dgeb** [comment]
I'm closing because this issue was opened to address possible conflicts, rather than the suitability of the key `id`. We can not prevent conflicts when reserving keys, and should always choose the most suitable key rather than one that is obscure in an attempt to avoid conflicts.

**Comment by hhware** [comment]
> should always choose the most suitable key rather than one that is obscure

@dgeb I cannot agree more. However, IMHO, `identifier` cannot possibly be obscure or any less suitable than `id` because the latter is just an abbreviation of the former, i.e. they are semantically identical. The only "problem" which I see with `identifier` is that it is 400% longer than `id`.

@bintoro [considered](https://github.com/json-api/json-api/issues/313#issuecomment-75827005) `@id` as a possible option. I think it is a great option becase, in addition to being visually distinctive,  `@id` is unlikely to clash with variable or DB column name, so it would be easy to distinguish internal `id` from external `@id` in documentation and in communication between humans. And it is mere 50% longer!

The same applies to `@type`, `@links` and `@meta`.
