### ISSUE TITLE
Allow JSON-LD

### ISSUE THREAD

**Issue by ethanresnick** [json-api/json-api#369]
Currently, the spec says "The top level of a document **MUST NOT** contain any additional members." I'd suggest an exception to allow `@context` and any other members that authors would need to support JSON-LD. 

[More radical](https://github.com/json-api/json-api/issues/159#issuecomment-70868301) proposals to bake JSON-LD ideas into the spec may not have gained support, but there's no reason the spec should _explicitly prevent_ authors from adding JSON-LD annotations should they desire. Hopefully that's relatively uncontroversial!

**Comment by bintoro** [comment]
I've wondered about this as well. Not so much w.r.t. JSON-LD, but more generally, a custom extension might want to place some stuff on the top level, and I think it should be allowed. Or, at least, let's reserve an extra free-for-all member.

**Comment by gr0uch** [comment]
+1 to allowing custom properties on the top level.

**Comment by dgeb** [comment]
> The top level of a document MUST NOT contain any additional members.

The reasoning behind this is to future proof the spec. After 1.0, we can't break backward compatibility and will make only additive changes. If the spec allowed any other members at the top level, then JSON API would be prohibited from making additive changes to the top level.

With that said, it's probably very safe to include a member such as `@context` at the top level, but the onus is on you to maintain compatibility with JSON API if for some crazy reason the same member was reserved in the spec at the top level.

> a custom extension might want to place some stuff on the top level, and I think it should be allowed.

Extensions can make changes to the base spec as needed - they are not purely additive to the base spec. Changes will of course only affect clients and servers that negotiate for the extensions.

**Comment by bintoro** [comment]
> Extensions can make changes to the base spec as needed - they are not purely additive to the base spec.

Gotcha. It's been kinda unclear what extensions may and may not do. Up until now, `Content-Type` negotiation has not been mandatory, implying that extensions mustn't break compatibility with the base spec. This is partly resolved with PR #353. If we add to this a clause stating that servers must only provide extended/incompatible services to clients who explicitly indicate support for them, then it becomes safe for extensions to do whatever they want. (This, in turn, implies that clients MUST specify an extension in `Content-Type` or `Accept` if they want to use its features.)

**Comment by ethanresnick** [comment]
@dgeb Re...

>  If the spec allowed any other members at the top level, then JSON API would be prohibited from making additive changes to the top level. With that said, it's probably very safe to include a member such as @context at the top level, but the onus is on you to maintain compatibility with JSON API if for some crazy reason the same member was reserved in the spec at the top level.

I get the principal behind reserving the top level for future extensions, and I support it for the general case. I'm just suggesting that, for JSON-LD in particular, JSON-API 1.0 should make an explicit commitment to being compatible with that standard by reserving the JSON-LD properties for their JSON-LD uses. That way, authors don't have to worry about the possibility (however remote) that using JSON-LD will cause them problems later on. This onus shouldn't be on them, and I see no reason why JSON-API shouldn't be willing to make this guarantee of interoperability with other standards.

**Comment by dgeb** [comment]
@ethanresnick Perhaps we could reserve only keys beginning with an alphanumeric character at the top level. This would allow JSON-LD or other extensions to co-exist with JSON API (which is pretty clearly sticking to alphanumeric reserved keys).

**Comment by kjwierenga** [comment]
:+1: on this

**Comment by ethanresnick** [comment]
@dgeb That sounds like a perfect solution! It's easy, and more generic than the special exception I was proposing for JSON-LD. Should I create a PR?

**Comment by dgeb** [comment]
@ethanresnick a PR would be great - thanks in advance!

**Comment by dgeb** [comment]
Closed via #378 - Thanks for writing that up @ethanresnick :+1:
