### ISSUE TITLE
Filter recommendation of a range

### ISSUE THREAD

**Issue by moleculezz** [json-api/json-api#372]
Hi,

What would be a nice recommended way for a filter that includes a range?

For integer values I can see something like a dash as the separator.

``` http
GET /comments?filter[post]=1-10
```

But for a date. Doesn't quite work if you use the following.

``` http
GET /comments?filter[date]=2015-01-01-2015-01-02
```

**Comment by gr0uch** [comment]
I think that the spec will remain agnostic about filtering strategies in the foreseeable future.

**Comment by ahacking** [comment]
You may want to look at odata v4 for inspiration. It has a full query syntax from memory.

**Comment by moleculezz** [comment]
@daliwali Well there is a recommended section that specifies some filters. Hence the title of this issue "Recommendation". I was just wondering if anyone could recommend something.

@ahacking I looked at odata. It's very broad. But it did give me some ideas. Thanks.

**Comment by tkellen** [comment]
I wouldn't use a dash as your separator for dates, a comma, or a pipe, or basically any character that isn't a part of the date string itself would be preferable.

**Comment by moleculezz** [comment]
@tkellen Yeah a comma is already used in the recommendation section to specify a list. So that's out of the question. A pipe would work. I just don't see it clearly representing a range.

This would fit most use cases. But I feel it's a bit too much.

``` http
GET /comments?filter[date][ge]=2015-01-01&filter[date][le]=2015-01-02
```

I think I will use a pipe anyway.

``` http
GET /comments?filter[date]=2015-01-01|2015-01-02
```

**Comment by tkellen** [comment]
Actually, it would make a lot of sense to use `..` or `...`, since those are range operators in a bunch of programming languages.

**Comment by moleculezz** [comment]
@tkellen Yes indeed. I like that better.

``` http
GET /comments?filter[date]=2015-01-01..2015-01-02
```

**Comment by dgeb** [comment]
That seems like a good recommendation. 

I'm going to close this now because I don't think we want the spec to provide recommendations for filtering strategies on this granularity. Once we add ranges, then we slip into the territory of defining gt, gte, lt, lte and so on, and perhaps even number and time / date formats. This level of detail is beyond the scope of the spec (even its recommendations section) for now.
