### ISSUE TITLE
Examples with relations in "Creating Resources" section

### ISSUE THREAD

**Issue by bobholt** [json-api/json-api#375]
Creating resources with relations needs to be done just like in updating, with a links object under data informing the relations (instead of foreign keys).

The [Creating Resources](http://jsonapi.org/format/#crud-creating) section doesn't mention this or show any examples including links, making this an easy oversight for an implementer.

**Comment by dgeb** [comment]
I agree that the examples should be expanded to be clear about this :+1:

**Comment by ColtonProvias** [comment]
Agreed with @bobholt.  It should mirror the syntax used for updating relationships and be under a links section to create consistency within the specification.

**Comment by ethanresnick** [comment]
@dgeb @steveklabnik @tkellen This can be closed now that #480's been merged.
