### ISSUE TITLE
Rename top-level 'links' & clarify what a link is

### ISSUE THREAD

**Issue by bintoro** [json-api/json-api#380]
In JSON API, _links objects_ are containers for relationships (on resources) and hyperlinks (at the top level). This idea probably comes from HAL, where relationships **are** hyperlinks. In JSON API, relationships are expressed in many formats and are clearly a separate concept. There's no similarity whatsoever between the top-level `links` member and resource-level `links` members.

In addition, the language of the spec strongly implies that _linked resources_ have to do with those in a _compound document_ specifically. (**EDIT:** For latest example, see PR #396 whose intention makes sense but the wording of which is in direct contradiction with the name and definition of `links`.)

So, we're overloading the word "link" with no fewer than **three** distinct meanings. Ideally, it would refer to one concept only.

Solution 1:
-   `links` at the document level to host document-wide hyperlinks
-   `rel`, `relations`, `related`, ... at the resource level to host relationships
-   _related resources_ when talking about related resources
-   _relationship object_ instead of _link object_ etc.
-   _included resources_ when talking about compound documents

Solution 2:
-   `hrefs` at the document level to host document-wide hyperlinks
-   `rel`, `relations`, `related`, ... at the resource level to host relationships
-   _related resources_ when talking about related resources
-   _relationship object_ instead of _link object_ etc.
-   _linked resources_ when talking about compound documents

Solution 3:
-   `hrefs` at the document level to host document-wide hyperlinks
-   `links` at the resource level to host relationships (same as today)
-   _linked resources_ when talking about related resources
-   _link object_ same as today
-   _included resources_ when talking about compound documents

If we choose to use the word "link" in the general "relationship" meaning (option 3), then it's possible to relate the terms like this: if _relationship_ refers to an association between types of resources, then a _link_ would be its realization between concrete resources.
- `posts.comment` = a relationship (a more abstract thing)
- `links.comment` on a `posts` resource = a link (pointing to a specific comment resource).

This would agree nicely with the existing term "link object".

**Comment by bintoro** [comment]
Can be resolved by defining "links" as a collective term for "relationships" and "hyperlinks". Moving this to the meta issue.

**Comment by dgeb** [comment]
> There's no similarity whatsoever between the top-level links member and resource-level links members.

This is simply false. The top-level links member contains links (`self` and relative) for the primary data. A resource's links object contains links (`self` and relative) for a resource's data. Just because there is not complete overlap between possible membership doesn't mean that there is "no similarity whatsoever" between them.

The spec disambiguates differences between possible members in the links objects at each level.

**Comment by bintoro** [comment]
@dgeb, what about the main point of this issue, i.e. the double meaning of "linked resources"? The title is partly out of date, since I reopened & repurposed this issue as a place to figure out what "link" means in general.

**Comment by dgeb** [comment]
> the double meaning of "linked resources"

We're going to rename top-level `linked` as `included`. Is that sufficient?

**Comment by bintoro** [comment]
@dgeb, here's the crux of it:

Right now, depending on where you look, "linked resources" can mean either "included resources" or "related resources".

If the term should mean "included resources", then it doesn't really align with `links` and "link object" because both describe _all_ relationships, whether or not they are included.

If, on the other hand, it's supposed to mean "related resources", then most occurrences of "linked resources" in the spec are now using the wrong meaning.

If this is a non-issue, fine. I'm just pointing out a contradiction in key concepts of the spec that I think the project owners should at least be aware of.

Since `linked` has now been changed to `included`, the easiest way to fix this would be to eliminate all occurrences of "linked resources" when talking about compound documents. This corresponds to "Solution 3" above and is my preferred approach too. "Linked resources" and "related resources" will become synonymous.

**Comment by dgeb** [comment]
@bintoro please review https://github.com/tkellen/json-api/commit/bffd4c597723cf7ca542052550b1cc50c8755955 (now merged) and let me know if you see any remaining contradictions.

**Comment by bintoro** [comment]
@dgeb Looking good! Seems like only one occurrence left with the "included" meaning. I can submit a PR for it, but before I do, am I correct that both "linked resource" and "related resource" will live on as interchangeable terms, or should they be unified?

**Comment by dgeb** [comment]
@bintoro great - glad we're almost there! A PR that covers the one occurrence would be appreciated.

And a separate PR that merges linked and related resource into just "related" would be appreciated as well.

Thanks for pushing for consistency :+1:
