### ISSUE TITLE
URL Templates

### ISSUE THREAD

**Issue by catesandrew** [json-api/json-api#382]
Probably an easy answer, but have been wondering what happened to the url templates in rc2. They were in the top level `links` object? I can't seem to find the answer.

> -A top-level `"links"` object **MAY** be used to specify URL templates that can
> be used to formulate URLs for resources according to their type.

Example A:

``` json
 {
   "links": {
    "posts.comments": "http://example.com/comments/1/posts/{posts.id}"
  },
  "posts": [{
    "id": "1",
    "title": "Rails is Omakase"
  }, {
    "id": "2",
    "title": "The Parley Letter"
  }]
 }
```

 Looks like rc2 removed them. So what's the best advice for handling collection
 of objects with linked resources? The url templates would help reduce
 verbosity. I know that `href` was removed in favor of `resource` and that
 multiple id GET (/posts/1,2,3) were dropped, but below are some old examples
 of url templates off top of my head. They were useful from having to repeat
 the same links object information over and over again for each resource
 in a returned collection.

Example B:

``` json
{
  "links": {
    "posts.comments": {
      "href": "http://example.com/comments/{posts.comments}",
      "type": "comments"
    },
    "posts.author": {
      "href": "http://example.com/people/{posts.author}",
      "type": "people"
    }
  },
  "posts": [
    {
      "id": "1",
      "title": "Rails in Omakase",
      "links": {
        "comments": [ "1", "2" ],
        "author": "9"
      }
    }, {
      "id": "2",
      "title": "The Parley Letter",
      "links": {
        "comments": [ "3" ],
        "author": "9"
      }
    }
  ],
  "linked": {
    "comments": [
      {
        "id": "1",
        "body": "Mmmmmakase"
      }, {
        "id": "2",
        "body": "I prefer unagi"
      }, {
        "id": "3",
        "body": "What's Omakase?"
      }
    ],
    "people": [ {
        "id": "9",
        "name": "@d2h"
      }
    ]
  }
}
```

Example C:

``` json
{
  "sessions": {
    "id": "1",
    "label": "c",
    "timeout": 10000,
    "links": {
      "href": "/sessions/1",
      "users": {
        "href": "/users/3,2",
        "ids": [ "3", "2" ],
        "type": "users"
      },
      "comments": {
        "href": "/comments/1,2,3",
        "ids": [ "1", "2", "3" ],
        "type": "comments"
      }
    }
  },
  "links": {
    "sessions.users": {
      "href": "/users/{sessions.users.ids}",
      "type": "users"
    },
    "sessions.comments": {
      "href": "/comments/{sessions.comments.ids}",
      "type": "comments"
    }
  }
}
```

**Comment by bintoro** [comment]
AFAIK templates were removed because they don't work well with heterogeneous collections. Since a collection may contain resources of varying types, it's not generally feasible to key the link templates by relationship name.

**EDIT:** I first posted an example of a possible format for type-based link templates, but the reason this isn't in the spec is likely the fact that there's now a focus on _related resource URLs_ instead of canonical resource URLs (which I think is a good thing, although ideally we would accommodate both).

**Comment by tkellen** [comment]
> They were useful from having to repeat the same links object information over and over again for each resource in a returned collection.

In addition to what @bintoro said, repeated text is highly compressible, making this concern largely irrelevant.

**Comment by catesandrew** [comment]
Closing the issue. Thanks @bintoro and @tkellen.
