### ISSUE TITLE
Clarifying total for pagination links.

### ISSUE THREAD

**Issue by ColtonProvias** [json-api/json-api#384]
The documentation lists that `"first"`, `"last"`, `"prev"`, and `"next"` must be used for pagination.

For systems that use an offset/limit scheme, maybe a `"total"` or `"count"` key MAY be included in the `"meta"` key for the resource being paginated.  This way it can prevent requests with an offset outside of the range capable of being returned.

**Comment by steveklabnik** [comment]
The spec currently allows for both, see the "Note" section under pagination. Maybe we can make this more clear somehow?

**Comment by tkellen** [comment]
Please feel free to open a PR to add a non-normative note if you still feel this is necessary!
