### ISSUE TITLE
id always as a string?

### ISSUE THREAD

**Issue by lausobo** [json-api/json-api#39]
Most of the examples use integers to represent ids. ids should be opaque, a token that we use to check for equality and we don't need an order relation between ids.

Integers smell like auto-increment ids but that won't always be the implementation server-side. Seems like strings are a more flexible and sane way of encoding any type used server-side as the primary key.

Client-side generated ids are often uuids, which are most commonly represented as strings. Also, ids will be part of URL and used in URL templates. With strings we won't need to convert the ids back and forth between two types.

I think that strings are more suitable for the job. Thoughts?

Related: note some inconsistencies between the type of different ids in this example:

``` json
{
  "posts": {
    "id": "1",
    "title": "Rails is Omakase",
    "rels": {
      "author": 9
    }
  },
  "people": [{
    "id": "9",
    "name": "@d2h"
  }]
}
```

**Comment by steveklabnik** [comment]
One of the goals is to provide a transition from the 'id style' to the 'URL style.' 
—

**Comment by reinh** [comment]
It seems like the spec could easily allow compliant implementations to use _either_ strings or integers for IDs. If you must pick one, use strings as they're the most versatile.

**Comment by ghost** [comment]
If the goal is to move people to the URL style, why not just allow for the URL style. I realise there are many implementations using ids, but it seems to me that the goal of this project is to present a standard rather than cater for the implementations that aren't yet using the standard.

**Comment by sumkincpp** [comment]
:+1: for token ids as it is more common way

in addition, google reader is using token ids in json, e.g

```
...
"id": "tag:google.com,2005:reader/item/ed3325b1ddb79fb5",
...
```

**Comment by reinh** [comment]
@gevious The goal is both to present a standard and to offer a transitional path towards that standard. ID style helps provide that transitional path.

**Comment by wycats** [comment]
I'm in favor of Strings-only as IDs. It's trivial for a server to convert numeric IDs into Strings, and you will need String IDs when the ID comes from the URL anyway.

**Comment by steveklabnik** [comment]
:+1:
