### ISSUE TITLE
Minor: Filtering header link on Recommendations page not generating fragment

### ISSUE THREAD

**Issue by ColtonProvias** [json-api/json-api#390]
The header link in question: http://jsonapi.org/recommendations/#filtering

Generated HTML:

``` html
<h2>Recommendations for Filtering <a href="filtering" id="filtering" class="headerlink"></a></h2>
```

Expected HTML (includes fragment):

``` html
<h2>Recommendations for Filtering <a href="#filtering" id="filtering" class="headerlink"></a></h2>
```

**Comment by ethanresnick** [comment]
@steveklabnik @dgeb @tkellen Likewise, this has been closed by https://github.com/json-api/json-api/commit/4b8333cb696614d5e0d149acb42356dae2c2f907

**Comment by dgeb** [comment]
Looks good - thanks @ColtonProvias and @ethanresnick!
