### ISSUE TITLE
Nested Objects without globally unique ID

### ISSUE THREAD

**Issue by lasssim** [json-api/json-api#393]
We are not quite sure how we should handle associations where the nested resource doesn't have a globally unique id.

This example demonstrates the issue:

We have a User model that has many Settings. A Setting has a unique id within the user, but another user could have the same setting-ids.

```
users = [
  {
    id: 123,
    settings: [
      {
        id: "settingA",
        value: true
      }
    ]
  }

  { 
    id: 234,
    settings: [
      { 
        id: "settingA",
        value: false
      } 
    ] 
  } 
]
```

When we create a JSON-API response it wouldn't be clear which Setting belongs to which User.

```
{
  data: [
    {
      id: 123,
      type: "users",
      links: {
        settings: {
          type: "settings",
          ids: ["settingA"]
        }
      }
    },
    {
      id: 234,
      type: "user",
      links: {
        settings: {
          type: "settings"
          ids: ["settingA"]
        }
      }
    }
  ],
  linked: [
    {
      id: "settingA",
      type: "settings",
      value: true
    },
    {
      id: "settingA",
      type: "settings",
      value: false
    }
  ]
}
```

We didn't find any documentation or open issue for this topic. Our proposed solutions would be:
- We could use temporary unique IDs within one request for each Setting. But this would not work with the restfulness of our API. Eg. updating a Setting through its restful URL wouldn't work with the artificial ID.
  - One way to generate such a temporary ID is to create a compound key. Eg. "user-123.settingA".
- We could just embed the settings array as it is in the user. This would work for this simple example. If the data for the association is handled in a different service or database it could be more complicated or unwanted if the association should lazy loaded. 
- We could replace the string ID in the links section with an hash.
  - **Example 1** uses an hash as ID. The ID of the Setting objects in the linked section is also replaced by an hash. So the query is somehow conform to the query by string. The drawback is that the objects in the linked section lose the original ID format.
  - **Example 2** also uses an hash as ID. The query in the linked section works different than in Example 1. All attributes of the hash in the links section are used to match the objects attributes to find the associated object in the linked section. This solution makes the most sense from out point of view.

It would be great if you could give us feedback.
##### Hash ID Example 1

```
{
  data: [
    {
      id: 123,
      type: "users",
      links: {
        settings: {
          type: "settings",
          ids: [ { id: "settingA", user_id: 123 } ]
        }
      }
    },
    {
      id: 234,
      type: "user",
      links: {
        settings: {
          type: "settings"
          ids: [ { id: "settingA", user_id: 234 } ]
        }
      }
    }
  ],
  linked: [
    {
      id: { id: "settingA", user_id: 123 },
      type: "settings",
      value: true
    },
    {
      id: { id: "settingA", user_id: 123 },
      type: "settings",
      value: false
    }
  ]
}
```
##### Hash ID Example 2

```
{
  data: [
    {
      id: 123,
      type: "users",
      links: {
        settings: {
          type: "settings",
          ids: [ { id: "settingA", user_id: 123 } ]
        }
      }
    },
    {
      id: 234,
      type: "user",
      links: {
        settings: {
          type: "settings"
          ids: [ { id: "settingA", user_id: 234 } ]
        }
      }
    }
  ],
  linked: [
    {
      id: "settingA",
      type: "settings",
      user_id: 123,
      value: true
    },
    {
      id: "settingA",
      type: "settings",
      user_id: 234,
      value: false
    }
  ]
}
```

**Comment by steveklabnik** [comment]
In what case do you have two different `setting`s, but with the same ID?

**Comment by lasssim** [comment]
we have a legacy system where we have a nested settings structure for users as described above. the first code block shows the structure within our database.

**Comment by lasssim** [comment]
sorry for being so unresponsive.

with the latest changes of the spec our dilemma has improved a lot. but another related topic popped up:

is it allowed to reference an object without its ID but with other attributes, that define it uniquely?

```
 {
   "data": {
     "type": "some_object",
     "id": "1",
     "links": {
       "application": {
         "linkage": { "type": "applications", "version": "3.4.5", "key": "com.example.myapp" }
       }
     }
   },
   "included": [
     {
       "type":    "applications",
       "version": "3.4.5",
       "key":     "com.example.myapp"
     }
   ]
 }
```

in our case, the client doesn't know the ID of the application, only its version and key. the combination of version and key is uniqe.

**Comment by ethanresnick** [comment]
@lister That isn't allowed, but why not just add an `id` member to each `applications` object, where the value of that member is some guaranteed-to-be-unique combination of the `key` and `version` members. So you might have:

```
"included": [
     {
       "id": "com.example.myapp+3.4.5"
       "type":    "applications",
       "version": "3.4.5",
       "key":     "com.example.myapp"
     }
   ]
```

This `"id"` key could be added in the serialization layer, and shouldn't require touching your database or any other code. Then, you could reference that member in your linkage objects.

**Comment by lasssim** [comment]
ic, thx for clarification
