### ISSUE TITLE
Clarifying linked resource interlinking

### ISSUE THREAD

**Issue by dkubb** [json-api/json-api#394]
I have a few cases where my data links to a resource which is loaded in the linked section. Some of them have relationships between each other and I was wondering if it was compliant with the spec to do something like this:

``` json
{  
  ...

  "linked": [  
    {  
      "type": "people",
      "id": "1",
      "first-name": "Jon",
      "last-name": "Doe",
      "links": {  
        "self": "http://example.com/people/1",
        "employer": {  
          "type": "people",
          "id": 2
        }
      }
    },
    {  
      "type": "people",
      "id": "2",
      "first-name": "Jane",
      "last-name": "Doe",
      "links": {  
        "self": "http://example.com/people/2",
        "employees": {  
          "type": "people",
          "ids": [1]
        }
      }
    }
  ]
}
```

None of the examples of `linked` show the resources linking to each other.

**Comment by steveklabnik** [comment]
It's totally allowed, but we might want to add a non-nonmative example.

**Comment by tkellen** [comment]
Yes, you can do this! If you'd like to see this as an example, please open a PR for our examples page.
