### ISSUE TITLE
Allow DELETE requests to remove a to-one relationship

### ISSUE THREAD

**Issue by jfinkels** [json-api/json-api#397]
In the section _[Updating To-One Relationships](http://jsonapi.org/format/#crud-updating-to-one-relationships)_, a to-one relationship is removed by using a `PUT` request with the request body `{"data": null}`. This makes sense, but might it also make sense to allow a `DELETE`request to the relationship URL? The _[Updating To-Many Relationships](http://jsonapi.org/format/#crud-updating-to-many-relationships)_ section allows `DELETE` requests to remove members of a to-many relationship.

**Comment by bintoro** [comment]
This is because the spec reserves DELETE for removing items from logical collections. For collections, you have POST/DELETE symmetry, while logically singular entities are always manipulated via PUT.

**Comment by bintoro** [comment]
@jfinkels, is this issue ripe for closing?

Btw, it's perfectly fine if a server wants to additionally support DELETE in the to-one case. It's allowed for sure, just not required.

**Comment by jfinkels** [comment]
That's fine, but I think this should at least be documented...

**Comment by bintoro** [comment]
@jfinkels Do you think [this recent FAQ entry](http://jsonapi.org/faq/#wheres-put) adequately addresses this issue, or did you have a more explicit explanation in mind?

**Comment by jfinkels** [comment]
That's fine, thanks!
