### ISSUE TITLE
allow PUT

### ISSUE THREAD

**Issue by steveklabnik** [json-api/json-api#4]
```
> On creation, if I accept the pain of generating an ID on the client and can construct the URI using the template, why can't I use PUT instead of POST?

Good point. That seems fine.
```

https://news.ycombinator.com/item?id=5655592

**Comment by lausobo** [comment]
:+1: for idempotency

**Comment by b** [comment]
And a 201 and a Location header MUST be returned, per HTTP/1.1. Thanks.

**Comment by lausobo** [comment]
@b yep.

Note that, by allowing PUT, creation and update of a resource will be available via the same verb and URL

`PUT /post/asda-asdasd-asdasd-asdasdasd` could either create a post of replace an existing post (assuming that the semantics of the service allow both operations). In that particular case it should only return a 201 it the requests resulted the creation of the post but not if it was an update.

**Comment by b** [comment]
Right, just like HTTP/1.1 says.

**Comment by lausobo** [comment]
:relieved:
