### ISSUE TITLE
Improve jsonapi.org by bit more descriptive abstract

### ISSUE THREAD

**Issue by cowtowncoder** [json-api/json-api#40]
When reading the abstract for the first time, I was not quite sure what the project was about: what are the goals for example. Abstract makes more sense once you learn the basics.
So it would be good to cover bit more of the basics first; otherwise it is easy to get "wtf?" reaction. :)

Description of API styles would also benefit from links to more authoritative sources, since it is not clear whether two styles are widely considered to be canonical JSON API interfaces (which seems to be the implication), or just examples of commonly seen ways.
To me latter seems more likely explanation, but text as is would suggest former.

**Comment by steveklabnik** [comment]
Hm. Yay github emails. I thought I responded and now there's nothing here.

I agree. :+1:.

**Comment by steveklabnik** [comment]
I've moved stuff around, so this should be more clear. We can still improve, of course, but I'd consider this fixed for now.

**Comment by cowtowncoder** [comment]
I agree, looks better now. Thanks!
