### ISSUE TITLE
Improvements related to ordering

### ISSUE THREAD

**Issue by hhware** [json-api/json-api#416]
~~IMHO, not enough attention is given in the spec to the way of specifying of order of results in the response, especially given that the specification of sorting in the request is quite detailed. I believe it is just assumed that the way to specify order of results is to order elements in the top-level `data`, but AFAIK it is not mentioned explicitly anywhere. The only reference to ordering I was able to find is in the Recommendations: "because order is significant" . I suggest to mention this explicitly in the base spec.~~ (Extracted into #473)

Also, it has been repeatedly argued that streaming of data is one of viable use cases for JSON API. For example: [Partitioning into types also introduces another layer of sorting on the server. When dealing with large result sets this increases latency as you can't send the response until you have fully processed the entire response](https://github.com/json-api/json-api/issues/365#issuecomment-75858660). Howerver, if we extend this reasoning to requesting data in sorted form, streaming may become impossible if the sorting cannot be delegated to the data source (e.g., when the sorting rules are too complex to be implemented in SQL, or when the data source is not database but some other application which does not support sorting) -- the server-side application will have to fully process the entire response before starting to send it out.

I propose to modify the spec in two ways: 
- allow an OPTIONAL member of top-level `links`, called `order`, to override the order of elements in the top-level `data`,
- specify that if the member `links.order` is provided, then the order of elements in it overrides the ordering of elements of top-level `data`, otherwise ordering of elements in top-level `data` is used.

Definition of `links.order` can be made identical to definition of relationship linkage of type `data`:

``` http
{
  "data": [{
    "type": "articles",
    "id": "12",
    "attribute1": "value121",
    "attribute2": "value122"
  },{
    "type": "comments",
    "id": "34",
    "attribute3": "value343",
    "attribute4": "value344"
  },{
    "type": "comments",
    "id": "56",
    "attribute3": "value563",
    "attribute4": "value564"
  },{
    "type": "articles",
    "id": "78",
    "attribute1": "value781",
    "attribute2": "value782"
  }],
  "links": {
    "order": [{
      "type": "articles",
      "id": "12"
    },{
      "type": "articles",
      "id": "78",
    },{
      "type": "comments",
      "id": "56"
    },{
      "type": "comments",
      "id": "34"
    }]
  }
}
```

This way, the server-side application can start to stream data, determining order of elements of top-level `data` on the go, and then return the computed order in the top-level `links` in the end of transmission.

Any chance to still consider this before the spec hits 1.0?
I would be glad to promptly provide a PR for three proposed changes.

**Comment by ColtonProvias** [comment]
I see the `links` section as a relationship collection rather than metadata of the request returned.  I feel like ordering is something that should be included in the `meta` section instead as not every resource collection returned needs to be explicitly ordered.

**Comment by hhware** [comment]
Actually, this proposal can be made more consistent in the spirit of #447, if we view the elements of top-level `data` as elements related to the response object itself, in the same way as links of a given resource represent elements related to that resource.

Specifically,
- allow for an OPTIONAL member `links.data.linkage`, formatted similar to relationship linkage in #447,
- specify that if `links.data.linkage` is provided, then the order of elements in it overrides the ordering of elements in top-level `data`, otherwise elements in top-level `data` should be considered ordered as listed in it.

``` json
{
  "data": [
    {
      "type": "articles",
      "id": "12",
      "attribute1": "value121",
      "attribute2": "value122"
    },{
      "type": "comments",
      "id": "34",
      "attribute3": "value343",
      "attribute4": "value344"
    }
  ],
  "links": {
    "data": {
      "linkage": [
        {"type": "comments", "id": "34"},
        {"type": "articles", "id": "12"}
      ]
    }
  }
}
```

**Comment by hhware** [comment]
Sorry, the first paragraph in the previous comment should read as:

Actually, this proposal can be made more consistent in the spirit of #447, if we view the elements of top-level `data` as elements related to the response object itself, in the same way as links of a given resource represent elements related to that resource.

**Comment by ethanresnick** [comment]
I'm going to close this issue, since it's obviously too late for such a change to the base spec now. However, I'll reference this issue from #794, which lists possible extensions, in order to keep it on the map.
