### ISSUE TITLE
PATCH-related clarifications

### ISSUE THREAD

**Issue by bobholt** [json-api/json-api#419]
For consideration pre-1.0:

Commit 01ce3454602e394b078303b8853d725b7981c472 changes all references of `PUT` to `PATCH`. :+1: for RFC 5789 compliance, but it opens a couple of questions:
1. There is no longer explicit support for full-replacement updates via the `PUT` method. Devs familiar with `PUT` but not `PATCH` may find it strange that it isn't mentioned at all.
   - Suggestion: specify that servers **MAY** support the `PUT` method, but it **MUST** only be used for full-replacement updates.
2. RFC 5789 says ["If the Request-URI does not point to an existing resource, the server MAY create a new resource, depending on the patch document type (whether it can logically modify a null resource) and permissions, etc."](http://tools.ietf.org/html/rfc5789#section-2). The json-api spec does not currently offer guidance on this.
   - Suggestion: explicitly say whether or not this is allowable under json-api. If there is no strong guidance deemed necessary, then a best-practice suggestion could be added to Recommendations.

**Comment by bintoro** [comment]
The spec now says nothing about PUT. This means that servers are free to support resource creation and replacement via PUT. No need to even declare an extension, since it poses no conflict (yet).

**Comment by bobholt** [comment]
@bintoro Sure, that makes sense to those of us who have been immersed in the spec for a while, but I'm thinking of Random Serverdev, who sees this for the first time. 

Documentation is more useful when it errs on the side of being explicit rather than making newcomers have to figure something out based on a lack of evidence. I picture someone coming here, not seeing a reference to `PUT` and going like this:

 _scroll_ _scroll_... _scroll_... <ctrl-F> PUT 

"Huh?"

I'm for saving lots of people that time.

**Comment by bintoro** [comment]
@bobholt, fair point. I suppose we could say something like "JSON API does not currently define functionality for PUT, but may do so in the future".

Stating that "servers MAY support the PUT method, but it MUST only be used for full-replacement updates" is not rigorous enough. Implementations would get the details differently, and many would inevitably end up non-compliant once we have an official PUT spec.

With this in mind, I should qualify my previous comment. It's of course prudent to declare a custom extension to avoid a possible incompatibility down the line if/when PUT appears in the base spec.

**Comment by dgeb** [comment]
If the spec says that:

> servers MAY support the PUT method, but it MUST only be used for full-replacement updates.

Then the spec is taking on the role of defining "full-replacement", which we've found to be a rabbit hole with respect to relationships. In short, this would re-introduce all the complexity and uncertainty in place before the PUT / PATCH swap.

I'd prefer for PUT to simply be beyond the scope of the spec. Implementations can interpret PUT's meaning all on their own if they want.

I think this would make a great entry on the FAQ page. @bobholt @bintoro do you think that's sufficient?

**Comment by bobholt** [comment]
That's sufficient for me, @dgeb.

**Comment by bintoro** [comment]
> I'd prefer for PUT to simply be beyond the scope of the spec.

Forever? If someone writes up the details in a well-defined way? I'm surprised to hear that.

The FAQ is definitely the right place to address this, but if there's even a remote chance that a sanctioned PUT spec might land in JSON API in the future, then the FAQ entry should explicitly leave the door open. That way, implementors would know that if they provide PUT capability without declaring an extension, it may one day conflict with the spec.

Alternatively, the FAQ could state that JSON API will _never_ define functionality for PUT, but that's a pretty bold move.

**Comment by dgeb** [comment]
> Forever? If someone writes up the details in a well-defined way? I'm surprised to hear that.

Forever is a very long time. There's no need to speak in absolute terms in the FAQ, and the spec itself won't be absolute either. I'm looking forward to one of our children or grandchildren finally solving PUT here :stuck_out_tongue_winking_eye:

**Comment by dgeb** [comment]
I'll leave this open until we get that FAQ added ... no need before 1.0 obviously.

**Comment by bobholt** [comment]
@dgeb Thoughts on point number 2 (Resource creation via PATCH)?

**Comment by dgeb** [comment]
@bobholt Sorry ... I did skip right over point 2.

It's possible that we should be more explicit describing PATCH support in the base spec. Still not sure that we need this before 1.0, but it would probably be nice. 

@steveklabnik thoughts?

**Comment by steveklabnik** [comment]
Milestoning because I need to review this.

**Comment by dgeb** [comment]
Removing 1.0 milestone after discussing with @steveklabnik last night.

**Comment by ethanresnick** [comment]
About @bobholt's second point...I think resource creation via PATCH is an interesting case. It seems like it could have two applications:
1. Allowing api clients to create new json-api collections. E.g. `PATCH /whatevers`, where `"whatevers"` is a type that currently doesn't exist. I'm not sure how useful this is, but it also seems like the kind of thing that we might as well let a server implement if it wants.
2. Allowing clients to create json-api resources that don't exist. E.g. `PATCH /collection-name/client-generated-id`. This seems like a bad idea, because the client won't be able to differentiate between whether a new resource was created or whether there was already a resource with `client-generated-id` that the server simply updated. Besides, we already have a good procedure via POST that handles this possible conflict with a 409. So I'm inclined to disallow this.

But I don't think this needs to be resolved pre 1.0.

**Comment by JustinLivi** [comment]
> @bintoro Sure, that makes sense to those of us who have been immersed in the spec for a while, but I'm thinking of Random Serverdev, who sees this for the first time...
> 
> ... I picture someone coming here, not seeing a reference to PUT and going like this:
> 
> scroll scroll... scroll... PUT

Random Serverdev here, just +1 on getting this resolved. Literally had this reaction.

**Comment by ethanresnick** [comment]
@JustinLivi To clarify, which part of this issue are you saying needs to be resolved? Are you saying the FAQ should be clearer on why we don't support PUT, or are you concerned about the "creating over PATCH" case?

**Comment by JustinLivi** [comment]
Ah sorry for the vagueness.

> the FAQ should be clearer on why we don't support PUT

I spent some time going through the spec searching for PUT and ended up at this issue searching for the reasoning behind it. My experience with REST has been to always use PUT, so I was surprised when I saw no mention of it.

**Comment by jelhan** [comment]
I'm going to close this issue.

The FAQ entry has been added some time ago: https://jsonapi.org/faq/#wheres-put

If a `PATCH` request to a resource, which does not exist, should create the resource, has been clarified in the specification:

> A server MUST return 404 Not Found when processing a request to modify a resource that does not exist.
