### ISSUE TITLE
Data object?

### ISSUE THREAD

**Issue by bintoro** [json-api/json-api#422]
In _Updating Resources_:

> The URL for a resource can be obtained:
> - from the `self` link in the resource object
> - for a _data object_, the original URL that was used to `GET` the document

What does "data object" mean in this context?

**EDIT:** I presume it simply means a resource object appearing alone as primary data.

**Comment by dgeb** [comment]
> I presume it simply means a resource object appearing alone as primary data.

That is correct and I agree this could be worded more clearly.

Perhaps: "for a single resource object returned as primary data, the original URL that was used to GET the document".
