### ISSUE TITLE
Primary keys that aren't id and composite primary key support?

### ISSUE THREAD

**Issue by garysweaver** [json-api/json-api#43]
While Rails "restful routes" (quotes != sarcasm, just mean that is what they are called) use the single id convention in paths, is it really ok to make the assumption that everything using this media type will pass a composite key this way vs. a different route to get the resource? i.e. in it gives the example:

> In the above example, a GET request to /posts/1/comments returns a document containing the four specified comments.

Examples of requests, etc. similarly show a single integer as the id, e.g. `"id": "1"`, and it is referred to as a singular entity named "id".

So, how would a composite key work?

Also, I read:

> Each document in the list MAY contain an id key.
> 
> IDs
> 
> The "id" key in a document represents a unique identifier for the document, scoped to the document's type. It can be used with URL templates to fetch related records, as described below.
> 
> Attributes
> 
> Other than the "rels" and "id" keys, every key in a document represents an attribute. An attribute's value may be any JSON value.

Rails has historically allowed `set_primary_key=` and later `self.primary_key=` to set an alternate primary key (or keys as an array (iirc) in the case of https://github.com/drnic/composite_primary_keys).

In the case where the id is not id and/or perhaps id is not the id but is still a valid field, how should that be handled? Or must the primary key (singular only) be sent as "id"?

Mostly just curious, because we have both composite keys and non-standard id column names.

**Comment by lukfugl** [comment]
What about using the `meta` section to describe the primary key for a given collection? We could reserve a `primary_key` attribute within the `meta` of a collection to contain a list of one or more [JSON-Pointers][http://tools.ietf.org/html/rfc6901] to identify the attribute(s) contributing to the primary key. If absent, it is assumed to be `["/id"]`. Then any language that talks about the `id` attribute specifically should instead talk about the primary key generically.

For example:

```
{
  "meta": {
    "page_views": {
      "primary_key": ["/request_id"]
    }
  },
  "page_views": [{
    "request_id": "abc",
    "url": "http://jsonapi.org/history",
    "timestamp": "2013-05-07T04:23:06Z"
  }, {
    "request_id": "xyz",
    "url": "http://jsonapi.org/faq",
    "timestamp": "2013-05-07T04:39:17Z"
  }]
}
```

and for a composite primary key:

```
{
  "meta": {
    "enrollments": {
      "primary_key": ["/rels/user", "/rels/course"]
    }
  },
  "memberships": [{
    "rels": {
      "user": "1",
      "course": "1",
    },
    "role": "teacher"
  }, {
    "rels": {
      "user": "2",
      "course": "1",
    },
    "role": "student"
  }]
}
```

**Comment by lukfugl** [comment]
Sorry, mixed up my example halfway through. The `"memberships"` collection was intended to be `"enrollments"`.

**Comment by steveklabnik** [comment]
The 'ID style' is meant for people coming from the more traditional Rails world. It's not as low-level as "my primary key", it's something that's unique.

If you're using the "URL style", then this is even less than a problem.

Exposing low-level database concepts like "composite primary key" is a bad thing to expose through your API.

**Comment by garysweaver** [comment]
> Exposing low-level database concepts like "composite primary key" is a bad thing to expose through your API.

Constructing a single string value as `id` using the two or more values with a delimiter like `-` and doing `.split('-')` on it in the controller to support composite key lookup is not the end of the world, so that's fine.
