### ISSUE TITLE
Is it really a media type and how are requests identified as the format defined by the spec?

### ISSUE THREAD

**Issue by garysweaver** [json-api/json-api#44]
> A media type for APIs that serve JSON.

This is using the application/json media type (mime type), so is it really a media type?

In http://jsonapi.org/write/ it states:

> Creating a Document
> 
> A JSON API document is created by making a POST request to the URL that represents a collection of documents that the new document should belong to.
> 
> In general, this is a collection scoped to the type of document.
> 
> The request MUST contain a Content-Type header whose value is application/json. It MUST also include application/json as the only or highest quality factor.

So, if the incoming request is not defining it as the format defined by this request, what is in the request body, url, or headers that identifies the format of the request that the server should expect?

Also, what about versioning of the spec and how that is relayed?

**Comment by mateomurphy** [comment]
See #6

**Comment by steveklabnik** [comment]
Yes, #1 is answered in #6.

We will talk about versioning once we have something reasonably 'final.'

**Comment by garysweaver** [comment]
Sounds good to me. Thanks!
