### ISSUE TITLE
Can sparse fieldset support be made optional?

### ISSUE THREAD

**Issue by taion** [json-api/json-api#451]
As written right now, I read the sparse fieldset section to imply that all servers are required to support sparse fieldsets, because they "**MUST NOT** include additional fields in the response" when a client specifies restricted fields.

Is it possible to treat this more like sorting, pagination, and filtering, where support for sparse fieldsets is optional, but either should be done in a certain way, or has certain reserved query parameters? As written, it's the only query parameter that all servers are required to support - the rest are all optional.

**Comment by dgeb** [comment]
Sorting, pagination, and filtering all have varying degrees of applicability and difficulty in implementation for different applications.

However, sparse fieldsets should be very straightforward to implement and can provide a benefit by greatly reducing payload size. This is something that we want clients to be able to rely upon.

**Comment by taion** [comment]
Interesting - from my perspective, I've actually used sorting and filtering much more broadly, but that might just be because I'm mostly working on my own APIs.

For example, if I'm building a somewhat minimal API from scratch for internal use, I can often already have a pretty good idea ahead of time of what fields I will care about, and I don't particularly care about payload size, but I often want a bit of flexibility on the front end to specify which rows to display rather than which columns.

In some sense, filtering and sorting are also pretty easy, though. They're nearly trivial if your collection is backed by a database and you are using an ORM, but in general filtering and sorting on arrays of objects is not difficult in any language - `Array.prototype.filter` and `Array.prototype.sort` are pretty straightforward, no?

As one other point, if I'm not misreading the GitHub API docs, as a basic example, many of them support operations along the lines of filtering and sorting, but not restricting fields, e.g.: https://developer.github.com/v3/repos/#list-user-repositories

**Comment by taion** [comment]
I don't have any more points to make here. Please close this issue if you don't think this change is called for.

**Comment by dgeb** [comment]
I wanted to give others a chance to chime in, but since no one else has I'm going to close. Thanks for raising this @taion.

**Comment by taion** [comment]
Thanks for considering this issue. I still think this might lead to a number of implementations that are "mostly" consistent with JSON API in that they will implement the correct format for messages, but may not necessarily implement this feature, but I guess I have to add support for this on my API now. (:
