### ISSUE TITLE
Clarify Linkage Objects

### ISSUE THREAD

**Issue by lsylvester** [json-api/json-api#459]
The spec currently stats that a resource linkage object is `an object containing "type" and "id" members`.

Does this imply that it cannot have any members other than "type" and "id"?

I think that it could be useful to contain additional data in the linkage that could be used in invalidate cached object on the client, like a "version"  member. This "version" member could either be in the root of the linkage object, or in a "meta" member, which could correspond to the "meta" on the resource itself. Something like

``` json
"linkage": {"id": 1, "type": "authors", "meta": {"version": "1"}}
```

Would this be something that is prohibited by the spec as it stands?

Would embedding information about a resource in the linkage object be considered an appropriate way to invalidate cached objects on the client, or should this be one through other means?

**Comment by bintoro** [comment]
Under section _Document Structure_:

> Unless otherwise noted, objects defined by this specification MUST NOT contain any additional members. Client and server implementations MUST ignore object members not recognized by this specification.

The thinking here is that applications that want to use custom members can declare a proprietary extension defining what those custom members are. An extension is allowed to overrule even a MUST clause in the base spec.

**Comment by hhware** [comment]
@lsylvester This topic is being discussed in #415, it was moved post 1.0.

**Comment by lsylvester** [comment]
Thanks
