### ISSUE TITLE
JSON API spec is not versioned

### ISSUE THREAD

**Issue by b** [json-api/json-api#46]
The JSON API spec itself needs version information. When one of those mythical changes for which the current spec needs "flexibility", the version would be changed.

**Comment by lukfugl** [comment]
:+1:

**Comment by steveklabnik** [comment]
Yes, when we have something that's reasonably "final" we can talk about this.

**Comment by b** [comment]
When the design is done the work to add any version information and behavior to the design will happen?

**Comment by steveklabnik** [comment]
The version information is currently there:

> This document is a work in progress and will likely change over the next month as implementation work progresses. Implementors should be aware that this specification is not stable.

I'm not comfortable with adding anything further than this at this time. This is a draft, a request for feedback. Things get official version numbers when they're actually final in some form.

**Comment by b** [comment]
Think you're misunderstanding. A JSON API speaker needs a way to signal which version of the protocol it supports, regardless of what the current version number on the spec is. The mechanism needs to be part of the spec, even if the current document doesn't have a version.

**Comment by steveklabnik** [comment]
Yes, I did misunderstand, thank you.

My inclination is that most media types do not present an internal version, because the commitment to backwards compatibility is so great. That said, no official decision has been made about this, so I'll re-open it until we discuss it formally.

**Comment by b** [comment]
Version information can be expressed and negotiated in numerous ways, media type being one. I'm not pushing a specific mechanism, only urging strongly that there be one, and soon. Versioning of APIs and versioning of resources are also missing or underspecified, but are being handled in other issues.

**Comment by steveklabnik** [comment]
After a discussion with @wycats, we plan on doing the usual media-type thing: never remove, only add. Therefore we don't need explicit versioning after we declare it stable, as it will _always_ be backwards compatible.

I've updated #1 to add things around versioning your entire API.
