### ISSUE TITLE
Plural and Sigular in URL template

### ISSUE THREAD

**Issue by edas** [json-api/json-api#47]
Some examples use the singular in the URI template, but link to the plural form in the json keys. I may be un-usable for a robot, especially if the API is not using English.
It also seems an un-needed requirements as in the hypermedia model, you don't have to "understand" the URLs (the server will provide them).

Expected : Use plural or singular, but the key and the name in the URL template should us the same value

``` json
{
  "rels": {
    "posts.comments": "http://example.com/posts/{*post*.id}/comments"
  },
  "*post*s": [{
    "id": "1",
    "title": "Rails is Omakase"
  }, {
    "id": "2",
    "title": "The Parley Letter"
  }]
}
```

**Comment by wycats** [comment]
Agreed. If there are discrepancies they are almost certainly bugs. Can you submit a PR to fix it?
