### ISSUE TITLE
Clarification on rejection of a full replacement request

### ISSUE THREAD

**Issue by hhware** [json-api/json-api#475]
The spec contains the following clause:

> A server **MAY** reject an attempt to do a full replacement of a to-many relationship.

and then further elaborates on the issue. I am wondering, is there a reason why a similar clause is missing for full updates of isolated resources or resources with to-one relationships? Are they so much less dangerous? Why not have a note on all kinds of full replacements?

**Comment by tkellen** [comment]
I do think they are less dangerous--changes to a to-one relationship are always full replacements. I'm going to give this a close, but if you feel strongly that this needs further discussion, please feel free to re-open it.
