### ISSUE TITLE
Rename "related"

### ISSUE THREAD

**Issue by hhware** [json-api/json-api#478]
I am not positive that my feeling of English is adequate here, but I think `related` in `links` is somewhat confusing because the meaning of the word "related" is too broad: it may be perceived as something generally related, as opposed to the object being referred to by the relationship. So I suggest to replace it with `referred` (`refers` or `reference` might also work).

Before:

``` json
{
  "type": "articles",
  "id": "1",
  "title": "Rails is Omakase",
  "links": {
    "self": "http://example.com/articles/1",
    "author": {
      "self": "http://example.com/articles/1/links/author",
      "related": "http://example.com/articles/1/author",
      "linkage": { "type": "people", "id": "9" }
    }
  }
}
```

After:

``` json
{
  "type": "articles",
  "id": "1",
  "title": "Rails is Omakase",
  "links": {
    "self": "http://example.com/articles/1",
    "author": {
      "self": "http://example.com/articles/1/links/author",
      "referred": "http://example.com/articles/1/author",
      "linkage": { "type": "people", "id": "9" }
    }
  }
}
```
#477 can be viewed as a further improvement in this area.

**Comment by bintoro** [comment]
The origin of `related` is in the term "related resource URL". The key was adopted in place of the generic `resource` so that later on we can accommodate the static "target" URL you asked about in #477.

The apparent problem with generic words like `referred` is that it gives no indication about whether you have the relationship-bound URL or the ID-bound "target" URL. It sounds like it could be either. For me it's not necessarily a deal-breaker, as it's impossible for the key to be fully self-explanatory anyway, but it's something to keep in mind.

**Comment by hhware** [comment]
> The apparent problem with generic words like `referred` is that it gives no indication about whether you have the relationship-bound URL or the ID-bound "target" URL. 

@bintoro, IMHO, `related` has exactly the same problem, relationship-bound URL vs ID-bound URL. Any word which points at the object being referred to has this problem. IMHO, `incumbents` and `referenced` has it to a smaller degree than `related` and `referred`, but all of them have it. I actually like `incumbents` the best...

I think it would be even better to allow the `canonical`/`target` URLs. The purpose is that they will, by contrast, make it clear what other URLs mean. Even if is an additive change, having this contrast in 1.0 could be useful:

``` json
{
  "type": "articles",
  "id": "1",
  "title": "Rails is Omakase",
  "links": {
    "self": "http://example.com/articles/1",
    "author": {
      "self": "http://example.com/articles/1/links/proofreader",
      "incumbents": "http://example.com/articles/1/proofreader",
      "linkage": { "type": "people", "id": "11", "target": "http://example.com/people/11" }
    }
  }
}
```

> Or, you know, we could just assume that implementors read the spec :smirk:

Yes, they should, but many implementors of limited-scope clients will not do it very thoroughly. So the best keywords are still very valuable...

> it's impossible for the key to be fully self-explanatory anyway

It would have been possible if more than one word were allowed in a key

**Comment by dgeb** [comment]
Renaming keys is a hair-splitting exercise that we need to move beyond unless there is a fundamental problem.
