### ISSUE TITLE
Changing type, id with PATCH?

### ISSUE THREAD

**Issue by ethanresnick** [json-api/json-api#481]
Right now, the spec says that `PATCH`ing a resource requires providing a (type, id) pair in the request's primary resource object. It doesn't say, though, whether those values could differ from the resource's existing (type, id).

For example, imagine that you have resources of types `teachers` and `administrators`, and a request to `GET /people` returns a collection with resources of both types. Now, if `GET /people/1` returns a `teachers` resource, it might be useful to be able to change the resource's type like so:

```
PATCH /people/1

{
  "data": {
    "type": "administrators",
    "id": "1"
  }
}
```

Should this behavior be allowed? And what about changing the id of an existing resource (which I find harder to justify)?

I'm not sure if this needs to be clarified pre-1.0 or if it's ok for the spec to leave this undefined, but I wanted to at least open an issue for it.

**Comment by bintoro** [comment]
The question was briefly touched [in this conversation](https://github.com/json-api/json-api/pull/418#issuecomment-77572676).

Whatever the final decision here, if type and ID are allowed to be changed, then it means the URL becomes the single source of truth, and it would be logical to treat the members optional on PATCH.

**Comment by hhware** [comment]
IMHO, `id` might need to be updated, for instance, if it is client-generated, and ability to update `type` could be a useful shortcut for conversion between polymorphic types. However, if they are allowed, I believe the spec should detail the process of switching of URLs of resources after such updates...

**Comment by dgeb** [comment]
If the ID is client-generated, then it should either be accepted or rejected on POST. It should not be possible to change the ID with PATCH. The type/ID pair must uniquely identify a resource - otherwise, none of the bulk update / delete options would be valid.

**Comment by ethanresnick** [comment]
@dgeb Can we leave this open to discuss, post 1.0, the possibility of/semantics around `PATCH`ing `type`. Also, if `id` isn't changeable—which I agree makes sense—the spec should probably make that explicit!

**Comment by dgeb** [comment]
@ethanresnick I just don't see how `type` or `id` can be mutable, but I will reopen this as a reminder to clarify this in the spec.

**Comment by hhware** [comment]
A related question: why does it have to be mandatory to supply `id`/`type` in `PATCH` requests if they are immutable and specified in the URL anyway? For consistency with Bulk extension?

**Comment by SFEley** [comment]
:+1: on @hhware's comment. If bulk operations are an extension, then the additional semantics required to support them should be in that extension, _not_ in the core.

**Comment by dgeb** [comment]
> why does it have to be mandatory to supply id/type in PATCH requests if they are immutable and specified in the URL anyway? For consistency with Bulk extension?

Why? This requirement is for consistency _in general_. We have a hard requirement that `type` and `id` are always required in resource objects, which simplifies processing for implementations.

**Comment by ethanresnick** [comment]
I still think it would be desirable to have this capability, to handle the motivating example I gave when opening the issue (which has happened to me in real life!). However, I understand what @dgeb's saying about our resource identification rules appearing to preclude mutating `type`/`id`. 

But I think there's a clever way around this. According to the `PATCH` spec, a `PATCH` request "affects the resource identified by the Request-URI, and it also **MAY have side effects on other resources; i.e., new resources may be created, or existing ones modified, by the application of a PATCH.**" (Emphasis added.)

Now, if the user is `PATCH`ing at the parent endpoint (e.g. `/people/1`), that's a different resource in the HTTP sense then the child endpoint (e.g. `/administrators/1`)—even though both point to the same _JSON API resource_ (i.e. HTTP entity). So, a PATCH on `people/1` that changes the `type` could be read as:
1. Updating the HTTP resource at `/people/1`, which it clearly does. This resource remains accessible from an HTTP point of view; its `type` key just has a different value.
2. Deleting the HTTP resource at `/teachers/1` and creating an HTTP resource at `/administrators/1`, both of which are allowed as PATCH side affects under HTTP.

So now, we have a patch document that, _from an HTTP point of view_, is perfectly valid, and we can make up whatever JSON API semantics we want for it. So we just clarify that, in the process of doing (1), the PATCH is deleting the JSON API resource identified by (teachers, 1) and creating an equivalent JSON API resource identified by (administrators, 1).

If people agree with this conceptually, I can work up a PR.

**Comment by dgeb** [comment]
The uniqueness contract for `type` and `id` should be binding. This is very important in a distributed system (which describes every implementation of JSON API). Imagine an offline client that attempts to reconcile its version of a resource with one that's changed its `type` or `id`. I'm pretty certain that we don't want to open this Pandora's box by allowing it in the spec.

**Comment by joananeves** [comment]
> So now, we have a patch document that, from an HTTP point of view, is perfectly valid, and we can make up whatever JSON API semantics we want for it. So we just clarify that, in the process of doing (1), the PATCH is deleting the JSON API resource identified by (teachers, 1) and creating an equivalent JSON API resource identified by (administrators, 1).
> 
> If people agree with this conceptually, I can work up a PR.

@ethanresnick It would be great if we had a 'Changing Polymorphic Type' or something like that in [Patch Operations](http://jsonapi.org/extensions/jsonpatch/#patch-operations)

**Comment by dgeb** [comment]
It's impossible to broadcast a change to a `type` / `id` pair without establishing a different unique key with which to identify the resource, and this spec has none.

I'd suggest that if you want to change a polymorphic type without changing the resource, then the change should actually be made to an attribute other than `type`. For example, `category`, `classification`, etc.

**Comment by ethanresnick** [comment]
> Imagine an offline client that attempts to reconcile its version of a resource with one that's changed its type or id... It's impossible to broadcast a change to a type / id pair without establishing a different unique key with which to identify the resource, and this spec has none.

We could have the old resource's URI `303 See Other` to the new URI. So, when the client tries to request the new version of the resource it has a local copy of, that server can respond with the new resource. The new and the old resource may be incommensurate because they have different types, but that's no more true than if they had different `catergory`s or `classification`s.

Moreover, if changing type really does make them incommensurate, the server can signal that by responding with 404 or 410...which is a case that this hypothetical client had to handle anyway, since a resource can, of course, disappear.

> I'd suggest that if you want to change a polymorphic type without changing the resource, then the change should actually be made to an attribute other than type.

This approach has issues too, namely that clients can no longer determine the schema in use just by looking at `type`, and instead of following JSON API, every API has to make up their own convention for signaling subtypes.
&nbsp;

There's clearly a real use case for changing a resource's type when the types are polymorphic/hierarchical. I think we should either define a standard key, like `subtype` to handle this, or we should go with an HTTP-responsible approach that technically deletes the old resource and leaves a redirect. But I don't think we should say to people that they should make up their own conventions here.

**Comment by tkellen** [comment]
The issue that won't die. These are all good points @ethanresnick.

**Comment by ethanresnick** [comment]
Thanks @tkellen, and props to you and @dgeb for closing a bunch of other longstanding issues today! Looking forward to 1.0!

**Comment by dgeb** [comment]
These points are related to friction between the URI vs type/id being the source of identity for a resource in a given API. Since type/id are always required, and self links are not, this spec appears to have chosen type/id for identity. Consider that resource identifier objects contain only type/id.

I would expect a 30X response if a URI has changed for a resource - for instance, if a URI template has changed.

However, I wouldn't expect a server to keep a type/id history for a particular resource, and thereby serve up a 30X response to indicate such a change.

> There's clearly a real use case for changing a resource's type when the types are polymorphic/hierarchical.

If a resource can change from one type to another, then I believe that "type" should be represented in another implementation-specific way in an API. Let's take the example of "teachers" and "administrators". There are several alternative approaches:
- Teacher resources and administrator resources both link to people resources. When the teacher or administrator goes away, the related person remains.
- People resources are associated with one or more roles - teachers, administrators, or even both.
- Teachers and administrators are truly separate resources. One doesn't need to be able to morph into another. When Mr Teacher becomes Mr Principal, there's no need for continuity.

**Comment by dgeb** [comment]
As much as I'd like to, I won't close this a third time unilaterally, but I would like to un-milestone it if possible. Do those pushing for changes believe anything needs to be decided pre-1.0?

**Comment by ethanresnick** [comment]
> Do those pushing for changes believe anything needs to be decided pre-1.0?

I'm not sure. If we don't decide anything, what would that mean? That the response to an attempt to change type/id is just unspecified?

**Comment by ethanresnick** [comment]
> However, I wouldn't expect a server to keep a type/id history for a particular resource, and thereby serve up a 30X response to indicate such a change.

I agree that this could be an implementation burden, and we should take that into account when choosing what to do. I don't think it would conflict with even JSON API's identification semantics, though, since 303's target is explicitly a _different_ conceptual resource, whereas 301/302 are meant for the same conceptual resource now living at a different URI.

**Comment by ethanresnick** [comment]
@dgeb Re the alternate approaches... Teachers and administrators was actually a pretty bad example, since you're right that someone can be both a teacher and an administrator at the same time. So let me give the real example from my API, and then look at the alternatives in that light.

My api has a `"people"` and `"presenters"` type. It's a strict hierarchy, i.e. being a presenter implies being a person. A presenter is simply a person who's previously presented at one of the events in the system, so once a person becomes a presenter, they never shift back. Also, being a presenter implies having a few extra fields that standard `people` don't have.

To the alternatives:

> [Presenter] resources [could] link to people resources. When the [presenter] goes away, the related person remains.

I like this alternative. It gives the client all the schema information in a standard way (i.e. because `"presenters"` get a dedicated type, the client can know about its additional fields) and it makes the system more extensible. For example, if I added another sub-type of person down the line, and a single person could be both that new sub-type and a presenter at the same time (which would put us back more into the teacher/administrator category), then this approach could easily accommodate that. But I think this approach has a few downsides too:
1. If the subtypes are implemented with a discriminator key (i.e. for single-table/single-collection inheritance) on the base people table/collection, then serializing the document or table row with the discriminator key to look like a separate resource with its own fields and a relationship to the underlying base-type resource requires implementing an additional serialization algorithm. (This is as opposed to just using the discriminator key, if any, to set the resource object's `type` and calling it a day.) 
2. The point in (1) applies to complicating `include` logic too, which is already complicated enough, imo. (Also, it could affect routing.)
3. By putting the underlying `people` resource in a relationship, rather than listing its fields inline, it becomes much harder (impossible?) to implement validation constraints specific to the `presenters` subtype. For example, suppose any person in the system _may_ have a github account, but a presenter _must_ have a github account. How do I ensure that the related person object's github account field is never empty, since that person resource can be updated independently?
4. This is a smaller issue, but putting the underlying person off in a relationship also makes it harder for the client to leverage the additional information that the sub-type has, if applicable. For example, consider the `attendees` relationship on an event model. Under this approach, that relationship would likely hold a homogeneous collection of `people` objects. In theory, it could hold `people` or `presenters`, but the server would be disinclined to include `presenters` because, for each presenter, the client would need to `?include` and reference the underlying person. However, the client might benefit from knowing that a particular attendee also happens to be a presenter (e.g. it could list them higher on an attendees list). And, in the approach where being a presenter just triggers a different `type` value, the server would be much more inclined to make the `attendees` collection hold `people` or `presenters`, since that wouldn't require anything extra on the client (as both types have the same minimum set of inline fields).

> People resources are associated with one or more roles - teachers, administrators, or even both.

This made sense for the "teachers" and "administrators" example, since a person could be both at once, but I don't think it applies to the "people" presenters example above.

> Teachers and administrators are truly separate resources. One doesn't need to be able to morph into another. When Mr Teacher becomes Mr Principal, there's no need for continuity.

This just seems bizarre. Many of the fields on the underlying resource (e.g. home phone number) should stay in sync, and they wouldn't if the resources are truly detached.
&nbsp;

Overall, I think the first alternative you proposed is a contender, though it brings some of its own implementation difficulties such that I'm not sure it ends up being simpler than the 303-style solutions, assuming those actually are or can be made to be semantically valid/have the right distributed system guarantees.

I also think there might be a solution that gets the best of all worlds by formalizing a `subtype` key or similar, but defining the meaning of such a key is probably impossible pre 1.0. That said, we might just want to reserve the key now (i.e. say no attribute or relationship can have that name) and then figure out what to do with it post 1.0?

**Comment by dgeb** [comment]
@ethanresnick thanks for the specific example.

I'd recommend keeping both people and presenters the same type: `people`. You say that a presenter can not go back to being a plain person, but I would allow this scenario just in case (mistakes get made).

There are three nuanced ways this could be modeled:
- People resources could have a flag - `presenter` - that affects validation rules for certain fields. 
- People resources could have a to-one relationship - `presenter` - in which the unique presenter fields are maintained on the presenter resource.
- People resources could have a to-many relationship - `roles`. This could be a polymorphic collection of roles, one of which could be a `presenter`. The `presenter` resource could again contain the unique presenter fields for an individual person in that role.

I'd guess you want to avoid the first approach because it requires the presence of presenter fields directly on people resources (and many would not be appropriate for general people). Therefore, I'd favor moving those unique fields to another `presenter` resource and using the second or third approach above. Either would allow a person to become a presenter (and to reverse that change as well). Furthermore, you'd never change the central identity of a person, which seems important in this application.

**Comment by dgeb** [comment]
> If we don't decide anything, what would that mean? That the response to an attempt to change type/id is just unspecified?

I believe the spec specifically disallows this currently:

> A server MUST return 409 Conflict when processing a PATCH request in which the resource's type and id do not match the server's endpoint.

**Comment by tkellen** [comment]
So, I re-opened this because the 303 status code seemed perfect for handling the use-case that @ethanresnick is describing, but @dgeb just pointed out that we can only rely on this if we normatively enforce self links on all resource objects. I'd forgotten that nuance because my implementation provides them and I wouldn't ever consider omitting them.

Since we're definitely not going to normatively require the hypermedia aspects of the specification, I feel like there is no path forward for us to support this. We could try some clever wording about servers who support this functionality must also provide self links but I'm pretty much certain the result would be a mess and a burden for implementors.

**Comment by tkellen** [comment]
I think we should close this and pursue a discussion about the possibility of adding subtypes post 1.0. @ethanresnick does that work for you?

**Comment by ethanresnick** [comment]
@dgeb The more I think about this, the more I see where you're coming from. I really wanted to maximize client convenience, which was driving my original proposal, and I was just hoping we could figure out the identity stuff somehow with redirects. But I think you and @tkellen are right that, as long as we have `type` and `id` as a first-class identity mechanism, URI-based approaches to referencing/identifying resources will be inadequate.

It's a little sad, since even my favorite of your options (the second one) seems less usable for clients that don't care about resource identity or would be willing to identify a resource by its URI. (I say it's less usable since the client has to `include` the relationship if it wants to make use of these extra fields, and since its a bit unintuitive to have these extra attributes in a relationship). That said, everything involves tradeoffs, and this one isn't too bad.

I think I'm ultimately going to go either with your second option or with a fourth option, namely: listing the presenter fields in a `presenter-info` attribute. The value of that attribute would be allowed to be either false (for normal people) or an object for presenters. This would support the extra data without an `include` and without polluting the schema for the `people` type. The downside is that I wouldn't be able to add any presenter-specific relationships, since we haven't yet figured out if/how to do relationships from complex attributes. I'll have to think about whether that's a worthwhile tradeoff...

Anyway, yes, I think we can close this now. 

@tkellen As far as adding subtypes goes, I think talking about that more post 1.0 would be good. For 1.0, all I'd say is that we might want to disallow `subtype` as an attribute or relationship name so that, if we do add it later, it can be used in `?fields` etc. without risking conflicts. Otherwise, I think we're good on this for now.

**Comment by dgeb** [comment]
@ethanresnick I definitely understand your perspective here as well and the challenges to model your resources as cleanly as possible. There are some good points to revisit after 1.0, such as relationships inside complex attributes. These kinds of challenging use cases will hopefully help improve the spec post-1.0.
