### ISSUE TITLE
Client library conformance tracking issue

### ISSUE THREAD

**Issue by steveklabnik** [json-api/json-api#484]
I'm making this issue to track client library progress towards implementing RC3.

**Comment by bobholt** [comment]
This is a diff between RC2 and RC3 if that's helpful to anyone else: https://gist.github.com/bobholt/1a5e9103be5fa85a53da (specifically between af5dfcc50ac3838601cf3f26a8e89a5778529c89 and a75f88d00634ff6dbb205f4e3625599a2c27a99c)

**Comment by tkellen** [comment]
Closing as we are now 1.0.
