### ISSUE TITLE
Sort parameter use of literal plus symbol ("+")

### ISSUE THREAD

**Issue by realityendshere** [json-api/json-api#486]
If I am not mistaken, many web servers see the plus symbol ("+") as a substitute for a white space or ("%20") when sent as a query param in the URL.

In the JSON API spec, the format for sending sorting criteria to a collection endpoint is:

```
GET /people?sort=+age,+name
```

However, my Rails API code sees `params[:sort]= age, name` (with blank spaces before `age` and `name`). In hunting around on Google, it seems this is not limited to Rails; it is expected behavior for query params --- +'s are intended to be shorthand for spaces.

Which raises the question: when the spec says to use `GET /people?sort=+age,+name`, should the +'s be literal and the server should compensate for the +'s or resulting white spaces? Or are the +'s expected to be URL encoded like `GET /people?sort=%2bage,%2bname`?

**Comment by tkellen** [comment]
/ref https://github.com/endpoints/endpoints/blob/42f3e2583e260bc34a0b86ebe1034db9df6b8f11/modules/adapter-bookshelf/lib/process_sort.js#L3-L7

**Comment by tkellen** [comment]
resolved in 8c63a72b42869835271df63800d980ad4989e005
