### ISSUE TITLE
SHOULD vs MUST for Location header in 201 response to POST

### ISSUE THREAD

**Issue by taion** [json-api/json-api#487]
The RFC only states that 201 responses to POST requests **SHOULD** include the URL of the created resource in the `Location` header. Is there a meaningful benefit to upgrading this to a **MUST** for JSON API?

If I'm not mistaken, this is the only hypermedia-related **MUST** item in the base spec, and it can be a little tricky to implement in a generic way when using certain microframeworks (e.g. with Flask, without hackery, the routes for `/items` and `/items/:id` are different endpoints that don't necessarily know about each other).

On the other hand, laziness and marginal inconvenience are not very good reasons for not implementing a **SHOULD**.

**Comment by dgeb** [comment]
It's a reasonable question - marking for 1.0 review.

I tend to prefer SHOULD here as well, since MUST isn't appropriate for POSTs in the bulk extension now that we are no longer supporting the concept of URLs for multiple individual resources.

**Comment by bintoro** [comment]
I don't care about `Location`, but I would find it very strange if a server didn't communicate the URL of a newly created resource. I think `self` should be required on all resources in 201 responses.

> it can be a little tricky to implement in a generic way when using certain microframeworks 

I use Flask too and don't understand this at all. How could the server _not_ know where a resource it just created can be accessed at?

**Comment by taion** [comment]
@bintoro 

Of course the server should know, but if you follow something like the [Flask-RESTful quickstart](https://flask-restful.readthedocs.org/en/0.3.2/quickstart.html#full-example), you end up with the methods for creating and retrieving on different endpoints that don't explicitly know about each other, so you'd have to hardcode the `Todo` endpoint in the `TodoList` resource or something.

I think a well-behaved create method absolutely SHOULD include the `Location` header; just a question of whether this should be mandatory.

**Comment by bintoro** [comment]
@taion Okay, but seriously, who implements an actual application like the Flask-RESTful quickstart example? To me it seems elementary that the `TodoList` class should know that it represents a collection of `Todo` items, and the `Todo` class should be aware of its canonical endpoint. From there it becomes trivial.

Doing this would only add a few lines of code to the example, so the question is: what's the real-life benefit of not requiring the resultant URL to be present?

I agree that SHOULD is appropriate for `Location`. The right place to enforce the requirement is `self`.

**Comment by taion** [comment]
I dunno, it seems pretty reasonable to me. If I don't need to do any HATEOAS stuff, what do I get out of linking my `TodoList` view to my `Todo` view? Idiomatic project structure for a REST API in Flask calls for separating out your resources from your URL rule setup, so it'd be weird to have to specify the name of the endpoint for your `Todo` resource both in the `TodoList` resource so you can link to a created item, and when you set up your URL rules. Of course this is not insurmountable, but it's not particularly natural to work this way either. And using a single resource with two URL rules for the same end point for both list operations and instance operations breaks the automatic supported method type detection in `MethodView` as well.

None of these are show-stoppers (and you can attach two views to the same endpoint with different URL rules just by conditioning on the matched URL rule), but it's a little messy to do this with Flask `MethodView`s, or with APIs that are fairly thin wrappers around `MethodView`s (like Flask-RESTful).

---

As for the point at hand, I think the `Location` header is a better location than `self` - the former is part of the HTTP RFC, so it's more idiomatic and more likely to be broadly understood. I don't think it would make sense to have a SHOULD for the location header but a MUST for the `self` link.

**Comment by bintoro** [comment]
> Idiomatic project structure for a REST API in Flask calls for separating out your resources from your URL rule setup, so it'd be weird to have to specify the name of the endpoint for your `Todo` resource [...]

It's fairly trivial to write a router component that sets up the URL-to-resource mapping while allowing resources to look up their own location. No need to hardcode anything anywhere.

> As for the point at hand, I think the `Location` header is a better location than `self` - the former is part of the HTTP RFC, so it's more idiomatic and more likely to be broadly understood.

The thinking here is that `Location` is not guaranteed to be compatible with bulk operations, whereas `self` always works. Specifying a MUST for the latter would give a signal to client implementors that that's the one to rely on.

**Comment by tkellen** [comment]
Agreed as well. I've just pushed a commit implementing this.

**Comment by ethanresnick** [comment]
@tkellen I think your commit here accidentally replaced the wrong MUST! This was about removing the MUST for the `Location` header, not the one for the `201`.

**Comment by tkellen** [comment]
Blast! Would you mind dropping a PR to adjust? I'm in the middle of several things here--will be happy to merge.
