### ISSUE TITLE
Add a "Why use PATCH instead of PUT?" section to the FAQ

### ISSUE THREAD

**Issue by kellysutton** [json-api/json-api#488]
After skimming over the RC3 docs, I could see this being a common question. I'll work on an answer and submit a PR.

**Comment by mtvx** [comment]
Ended up here looking for answer to that exact question.

Could you also include why not to follow the JSON patch specification http://tools.ietf.org/html/rfc6902?

For example, the RFC spec supports adding/removing/deleting elements in attribute array or object. With JSON API you have to always submit the whole array/object, in which case versioning the resources becomes essential?

**Comment by bintoro** [comment]
There's a pending PR (#457) that somewhat overlaps with this. I'm open to adding a mention of PATCH there, or I can limit the entry to just "Can I use method X to do Y".

> Could you also include why not to follow the JSON patch specification

JSON Patch is not compatible with the base JSON API document structure, but there's an official [extension](http://jsonapi.org/extensions/jsonpatch/) for it.
