### ISSUE TITLE
Can the top level "data" key and resource object "id", "type" members be considered final?

### ISSUE THREAD

**Issue by yellow5** [json-api/json-api#489]
Many steps have been taken recently toward version 1.0.0 of the JSON-API spec. Kudos to all for your hard work!

At the start of the year, I started introducing JSON-API at my day job as the proposed standard to follow for building out internal JSON micro-resources. Currently they use RC1 format.

With RC2 (#341), some changes took place, including:
1. Top-level key name "data" instead of "pluralized_resource"
2. Top-level resource members "id" and "type" (particularly the latter)

First off, I have no hard feelings! :) When I started implementing it, the standard was described as a WIP; I recommended following the standard with the understanding that the spec could change.

Okay, back to the issue...

More recently, RC3 (#483) was merged in. It says:

> Only very small and very well-justified changes will be accepted after this.

Is it safe to say that the changes previously mentioned (top-level key "data", top-level resource members "id", "type") will remain unchanged?

Thanks in advance for any insight that you can provide!

**Comment by dgeb** [comment]
Yes - this is safe to say! We are stabilizing everything for 1.0 and I consider these key names to be locked down now.

I regret any trouble the last six months of churn have caused to your implementation.
