### ISSUE TITLE
Should resource ID match resource endpoint URL?

### ISSUE THREAD

**Issue by jfinkels** [json-api/json-api#490]
Does JSON API make any recommendations about a resource endpoint having an ID that matches the endpoint URL? For example, if I have a person resource with a primary key 'id' and a `name` attribute guaranteed to be unique, MAY my resource be accessible at `/people/somename`? SHOULD it?

**Comment by steveklabnik** [comment]
The only thing we have related to URL design is a recommendation: http://jsonapi.org/recommendations/#urls

The spec places no requirements on the structure of your URLs.

**Comment by steveklabnik** [comment]
(closing this since it's not a bug, but we can still keep talking about your case if you'd like)

**Comment by jfinkels** [comment]
That answers my question: the specification makes no recommendations of the style about which I asked. Thanks.
