### ISSUE TITLE
Example URLs for relationships

### ISSUE THREAD

**Issue by hhware** [json-api/json-api#491]
I think it would make it more straightforward if suggested relationship URLs in the examples are changed in the  following manner:

``` json
{
  "type": "articles",
  "id": "1",
  "title": "Rails is Omakase",
  "links": {
    "self": "http://example.com/articles/1",
    "authors": {
      "self": "http://example.com/articles/1/authors/self",
      "related": "http://example.com/articles/1/authors/related",
      "linkage": [
        { "type": "people", "id": "9" }
      ]
    }
  }
}
```

It looks more consistent, and it also easier to extend. For example:

``` json
{
  "type": "articles",
  "id": "1",
  "title": "Rails is Omakase",
  "links": {
    "self": "http://example.com/articles/1",
    "authors": {
      "self": "http://example.com/articles/1/authors/self",
      "related": "http://example.com/articles/1/authors/related",
      "target": "http://example.com/articles/1/authors/target/snapshot_12345",
      "linkage": [
        { "type": "people", "id": "9", "target": "http://example.com/people/9" }
      ]
    }
  }
}
```

FYI, related issues: #471, #477

**Comment by bintoro** [comment]
I'm sorry but I don't think this makes a whole lot of sense.

Nested URLs of the form `/foo-resource/<id>/bar-resource` look good and are quite standard. They are completely self-explanatory. What value does it add to append a redundant `related` segment, the meaning of which must be obtained from the API documentation?

Importantly, if the related resource URL is put behind `related`, then requesting all articles by the guy who authored article 1 would look like this:

```
http://example.com/articles/1/author/related/articles/related
```

IMO that's confusing and super ugly.

There's no 1:1 correspondence between URLs and the internal structure of resource objects anyway, so I find the consistency argument dubious.

**Comment by tkellen** [comment]
I agree with @bintoro. I don't see the value of this addition. If you wish, you could achieve your desired consistency by dot-notating your relations rather than slash separating them.

e.g.
`GET /articles/1/author.articles`
