### ISSUE TITLE
Constraint on types in Bulk POST

### ISSUE THREAD

**Issue by ethanresnick** [json-api/json-api#492]
Currently, the bulk extension just says that every resource I POST must contain a `"type"` member, but it doesn't constrain those types at all, or say how the server should respond to bizarre types.

For example, this should pretty obviously not be allowed:

```
POST /photos
{
  "data": [{"type": "people", "name": "New Person!"}]
}
```

That implies a basic restriction like "The `"type"` value provided for each resource must be among types that constitute the collection represented by the URI that you're `POST`ing to."

But, beyond that basic restriction, I'm wondering if there should be more guidance. E.g., perhaps the server MAY reject the request if all the `"type"`s don't match? Etc.

**Comment by dgeb** [comment]
I think a 422 (Unprocessable entity) would be appropriate. I'm not sure we need to provide guidance for every single error condition, but this might be a good one to include.

**Comment by ethanresnick** [comment]
Yup. And, if we do provide guidance here, presumably it should match the guidance we give for the non-bulk equivalent of this error. For that, we currently require a 409:

> A server MUST return 409 Conflict when processing a POST request in which the resource's `type` does not match the server's endpoint.

**Comment by tkellen** [comment]
This seems good @ethanresnick, would you mind opening a PR?

**Comment by ethanresnick** [comment]
I opened [a PR](https://github.com/json-api/json-api/pull/545) that starts work on this!
