### ISSUE TITLE
How to implement embedded resources

### ISSUE THREAD

**Issue by willemdewit** [json-api/json-api#495]
We are implementing an alternative to our XML API based on JSON API, I have the following (simplified) situation with embedded records due to our Document Oriented Storage:

It is important to notice that a File can be in more models than just a Student.

``` xml
<student id="2" name="Harry" some-other-types="etc">
  <files>
    <file id="test1.jpg" last-modified="2015/03/01" />
    <file id="test2.jpg" last-modified="2015/03/02" />
  </files>
</student>
```

I'm struggling how to translate this to a JSON API Resource object, the linkage via URL is easy:

``` json
{
  "id": 2,
  "name": "Harry",
  "some-other-types": "etc",
  "links": {
    "files": {
      "self": "http://example.com/students/2/links/files"
    }
  }
}
```

But how can I somehow embed the data in the result document?
Is this a good solution?

``` json
{
  "data": [{
    "type": "student",
    "id": 2,
    "name": "Harry",
    "some-other-types": "etc",
    "links": {
      "files": {
        "linkage": [{
          "id": "student/2/test1.jpg",
          "type": "file"
        }, {
          "id": "student/2/test2.jpg",
          "type": "file"
        }]
      }
    }
  }],
  "included": [{
    "type": "file",
    "id": "student/2/test1.jpg",
    "last-modified": "2015/03/01"
  }, {
    "type": "file",
    "id": "student/2/test2.jpg",
    "last-modified": "2015/03/02"
  }]
}
```

As you can see I changed the id of the file. And what to do when there is no "id" attribute present on the embedded record?

**Comment by bintoro** [comment]
There are two general approaches:
- Turn the embedded elements into separate, normalized resources (which is what you have done here).
- If the embedded elements are only accessed as part of the parent resource, you can just continue to embed them. See [Complex Attributes](http://jsonapi.org/format/#document-structure-resource-object-complex-attributes).

> It is important to notice that a File can be in more models than just a Student.

If by this you mean that the exact same underlying file can appear under several parent resources, then the slash-separated ID scheme obviously won't yield a unique ID for each file.

**Comment by willemdewit** [comment]
@bintoro Thank you for your quick reply.
To clearify, with complex attributes I'm allowed to do this?

``` json
{
  "type": "student",
  "id": "2",
  "files": [{
    "type": "file",
    "the-properties": "..."
  }]
}
```

> If by this you mean that the exact same underlying file can appear under several parent resources, then the slash-separated ID scheme obviously won't yield a unique ID for each file.

I meant that not an instance can be appear under several parent resources, but other instances of the same type.

**Comment by bintoro** [comment]
> To clearify, with complex attributes I'm allowed to do this?

Yes. Just remember not to use `id` and friends in any JSON objects within the `files` data structure.

**Comment by willemdewit** [comment]
Is `id` reserved because it should be a globally unique identifier for that type of object?

**Comment by bintoro** [comment]
Initially there was a need to reserve `links` so that outbound links from complex attributes could be added to the spec later. Then it was decided, admittedly without much deliberation, that let's just reserve all the special members that may appear in resource objects.

I think it would be fine to allow the use of `id` as long as it obeys the same rules as in resource objects. It's just that, more often than not, you simply don't have a globally unique ID for a subresource that's wholly dependent on its parent. That's exactly the problem complex attributes are intended to solve.

**Comment by dgeb** [comment]
I think @bintoro has thoroughly answered this. 

@willemdewit - please comment if you have remaining questions.

**Comment by tisto** [comment]
This is actually a plone.rest issue. Moved it to plone.rest: https://github.com/plone/plone.rest/issues/50
