### ISSUE TITLE
Using POST on related collection URLs

### ISSUE THREAD

**Issue by timabdulla** [json-api/json-api#496]
just to clarify, as this is not stated explicitly in the spec: is it ok to use POST on related collection URLs (e.g. /posts/1/comments) to create a new resource of the collection's type that is automatically linked to the related resource?

**Comment by bintoro** [comment]
Absolutely.

> A resource can be created by sending a POST request to a URL that represents a collection of resources. 

A server may choose not to support resource creation at all, but if it does, I would certainly expect related collections to accept POST requests. AFAIK this is not a requirement, however.

**Comment by timabdulla** [comment]
thanks, that clarifies that!
