### ISSUE TITLE
Terminology: relationship tuples

### ISSUE THREAD

**Issue by hhware** [json-api/json-api#499]
I would like to suggest to add the following definition to the spec: 

> A "relationship tuple" is a member object of a relationship linkage, which contains "type" and "id" members.

This would allow to simplify other definitions, for instance, to replace

> an array of objects each containing "type" and "id" members for non-empty to-many relationships.

with

> an array of relationship tuples for non-empty to-many relationships.

If I am not mistaken, there are 10 places in the current spec where this would apply.

**Comment by tkellen** [comment]
:+1: could you please submit a PR for this?

**Comment by hhware** [comment]
@tkellen Sure, with pleasure

**Comment by bintoro** [comment]
Note that all these mentions of "objects with `type` and `id` members" are going away, as they will be converted to use the concept of _linkage_. This is happening in PR #480.

I'm not convinced we need a new term that's only going to be used once (in the definition of "linkage").

**Comment by dgeb** [comment]
I'm in favor of the term "linkage object", which seems consistent with "link object" and "resource object". So "linkage" can be described with `null` or a single linkage object (for a to-one relationship), or an empty array or array of linkage objects (for a to-many relationship).

**Comment by ethanresnick** [comment]
I'm also in favor of "linkage object" over "relationship tuple"—that just sounds more direct. I'll update #480 accordingly.

**Comment by tkellen** [comment]
I'm going to close. @hhware if you feel this isn't addressed by #480 can you do some lobbying there?
