### ISSUE TITLE
Sideloading?

### ISSUE THREAD

**Issue by steveklabnik** [json-api/json-api#5]
Do we need something like this in the spec directly?

**Comment by wycats** [comment]
The "compound document" stuff is what people mean by "sideloading". It's already in there :)

**Comment by rcs** [comment]
The compound document section of the spec doesn't say anything about the client-side control I'd love to see defined (even as a SHOULD or MAY) for how a client can request specific sets of compound documents.

As an example, how I can request a person with their posts and comments? Or only the person when the API defaults to offering up  their posts as well?

Use cases: The API is backed by something that's slow to retrieve the posts. When I retrieve a person to show them in a contact list, or abbreviated profile,  I don't want to take the time hit of asking the server to retrieve the posts as well.

Until I'm writing an app that's backed by a mobile network with a big latency hit for at least the first request and I've got a robust client-side cache I'm using.

And when I'm on that high-latency mobile connection, it's nice to be able to request even further down the relationship chain. Person -> post -> top 10 comments on that post.

**Comment by GavinJoyce** [comment]
I'd like to be able to conditionally side-load:

GET `/albums.json?include=artists,songs`

which would return a collection of albums, all related artists and (possibly a page of) related songs. I'm building support for this into https://github.com/RestPack/restpack-serializer. I'll put together a demonstration and share soon.

The Zendesk REST API supports side-loading in this way:

http://developer.zendesk.com/documentation/rest_api/introduction.html#side-loading-(beta)

**Comment by GavinJoyce** [comment]
@wycats @steveklabnik 

Here's some examples of how I plan to use conditional side-loading with [restpack-serializer](https://github.com/RestPack/restpack-serializer). These examples model `Artists -> Albums -> Songs` [rails app source](https://github.com/GavinJoyce/restpack-serializer-sample).

Here is a collection of artists:

http://restpack-serializer-sample.herokuapp.com/artists.json

And here are just two:

http://restpack-serializer-sample.herokuapp.com/artists.json?ids=1,2

Let's side-load their albums:

http://restpack-serializer-sample.herokuapp.com/artists.json?ids=1,2&includes=albums

Now we'll side-load albums and songs:

http://restpack-serializer-sample.herokuapp.com/artists.json?ids=1,2&includes=albums,songs

Notice that as there may be a large number of songs (there are 31 in this case), we're only returning the first page here. I plan to add links to additional pages in the meta data, the URLs will take the following form:

http://restpack-serializer-sample.herokuapp.com/songs.json?artist_ids=1,2&page=2

or if we want to include side-loads:

http://restpack-serializer-sample.herokuapp.com/songs.json?artist_ids=1,2&page=2&includes=artists,albums

I plan to implement some of the json-api draft in the coming days so expect the JSON output to become more familiar soon.
