### ISSUE TITLE
Why not build on top of...

### ISSUE THREAD

**Issue by nathanhammond** [json-api/json-api#50]
There are lots of these that make sense for an FAQ. A few pieces I'd like to include in that list.
## JSON Schema (and Hyper-Schema)

"Describes your existing data format in clear, human- and machine-readable documentation which allows for complete structural validation to enable automated testing and validating client-submitted data."
- http://json-schema.org/
- https://github.com/kriszyp/json-schema
- http://tools.ietf.org/html/draft-zyp-json-schema-04
### JSON Ref
- http://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03
### JSON Pointer
- http://tools.ietf.org/html/rfc6901
## Swagger
- https://developers.helloreverb.com/swagger/
- http://petstore.swagger.wordnik.com/

**Comment by steveklabnik** [comment]
This is part of #1. Thanks for listing it out.
