### ISSUE TITLE
Organizational: submission of issues for consideration for a specific version

### ISSUE THREAD

**Issue by hhware** [json-api/json-api#507]
Unless I am mistaken, there is no way for authors of issues/PRs to lobby their inclusion into a specific version of the spec without posting annoying comments in the issues being lobbied. 

Example: #476 is a conflict/omission, seemingly in need of resolution before 1.0, but it is not scheduled for 1.0. Does it mean that editors of the spec believe it is not important, or just nobody had time for it yet, or something else?

Suggestion: set up a separate issue (per stable version) to track such requests and responses. Anyone not interested in this chatter could unsubscribe from that issue.

**Comment by dgeb** [comment]
This is why we're maintaining milestones. If we don't mark something for a milestone, please comment on it and we'll either milestone it or explain why we didn't.

I'll milestone #476 now, since you mentioned it - and we'll be sure to review it before 1.0.

**Comment by hhware** [comment]
@dgeb, thanks for the clarification on the process!
