### ISSUE TITLE
Pagination of to-many relationships is underspecified

### ISSUE THREAD

**Issue by jes5199** [json-api/json-api#509]
There's no clarification or example for this line:

> A link object that represents a to-many relationship MAY also contain pagination links, as described below.

I _think_ that means something like this: 

``` json
// ...
{
  "type": "articles",
  "id": "1",
  "title": "Rails is Omakase",
  "links": {
    "self": "http://example.com/articles/1",
      "comments": {
        "self": "http://example.com/articles/1/links/comments",
        "resource": "http://example.com/articles/1/comments",
        "linkage": [{"type": "comments", "id": "5"}, {"type": "comments", "id": "12"}],
        "next": "http://example.com/articles/1/comments?page[cursor]=XYZCAFE"
      }
  }
}
// ...
```

but I'm not completely sure that's correct. Is that `next` link what the spec intended?

Also: should that `next` link be more like a `self` or a `resource` link for the relationship? I'm actually not completely sure I even know the difference between the two kinds of links in the case of a To-Many relationship :-/

**Comment by dgeb** [comment]
Yes, this needs further clarification.

The pagination links must be for the relationship itself, rather than the related resources (and I have a foggy notion of mis-stating this recently in another issue, so apologies if I did).

Therefore, in your example, the `next` link might point to:  `""http://example.com/articles/1/links/comments?page[cursor]=XYZCAFE"` and return the next set of linkage data.

Related resources MUST be referenced through a `related` link (not `resource`). See the definition of "related resource URL" here: http://jsonapi.org/format/#document-structure-resource-relationships

Related resources can be fetched by following the related resource URL to get to the first "page", and then subsequent pagination links can be retrieved from the top-level `links` object in the response.

So to clarify your example would be:

```
// ...
{
  "type": "articles",
  "id": "1",
  "title": "Rails is Omakase",
  "links": {
    "self": "http://example.com/articles/1",
      "comments": {
        "self": "http://example.com/articles/1/links/comments",
        "related": "http://example.com/articles/1/comments",
        "linkage": [{"type": "comments", "id": "5"}, {"type": "comments", "id": "12"}],
        "next": "http://example.com/articles/1/links/comments?page[cursor]=XYZCAFE"
      }
  }
}
// ...
```

**Comment by jes5199** [comment]
Sorry about the `resource`/`related` confusion in my initial question, I had recently been referring to RC2.

What I'm hoping to do is provide a link where a client can actually download the next page of comments in one step - is it possible to do that with this pagination scheme? I think I can if I am allowed to put the actual comment data in `included` on the GET response for a relationship url, but from the spec I can't tell if I'm allowed to return anything other than linkages

**Comment by dgeb** [comment]
If the original request specifies `include=comments` then the server could append that query param to the `next` link: `"http://example.com/articles/1/links/comments?page[cursor]=XYZCAFE&include=comments"`

This should return the next page of linkage data as primary data together with the included comments in a compound document.

**Comment by jes5199** [comment]
Thanks, this is enough to set me in the right direction.

**Comment by ethanresnick** [comment]
@dgeb Wait, _what_? An `/articles/1/links/*` style request can have an `include` parameter? Even though the primary data returned isn't a resource object(s) and doesn't have a `links` bag? Now I'm beyond confused about `include`'s semantics. We really need to figure this and #497 out before 1.0.

**Comment by dgeb** [comment]
> We really need to figure this and #497 out before 1.0.

I agree that the spec should be explicit about the usage of `include` with relationship data, so I'm fine milestoning it. I'm not sure it's a blocker, but we can certainly discuss and clarify it.

**Comment by jes5199** [comment]
Does this statement:

> An endpoint MAY return resources related to the primary data by default

also apply to relationship data requests?

**Comment by ethanresnick** [comment]
@dgeb Cool. But the confusion isn't just for relationship data...in #497, there seems to be confusion (or, at least I'm confused) about `include`s fundamental semantics in the typical compound document case. Please do weigh in when you have a sec!

**Comment by dgeb** [comment]
Removing milestone now that #641 clarifies the usage of include with relationship endpoints.

**Comment by tkellen** [comment]
Closing as resolved in #641. @jes5199 If you feel this warrants further discussion, please feel free to continue the discussion.

**Comment by ethanresnick** [comment]
Reopening this. It got marked as closed after we resolved an issue with `?include`, even though we never added @dgeb's [clarification](https://github.com/json-api/json-api/issues/509#issuecomment-86795865) about the target of the pagination links to the base spec, which is still very vague on this point. I'll try to open a PR soon, unless someone else wants to tackle it.

**Comment by maryokhin** [comment]
Stumbled upon this issue when trying to implement nested pagination for [django-json-api](https://github.com/django-json-api/django-rest-framework-json-api/issues/178). Also noticed that the spec is very vague regarding the pagination links. 

For example, when I paginate the nested relationship by 3 resources at a time:

``` json
"relationships": {
    "comments": {
        "meta": {
            "count": 21,
            "pagination": {
                "page": 1,
                "pages": 1,
                "count": 21
             }
        },
        "data": [
             {
                 "type": "comments",
                  "id": "874"
             },
             {
                  "type": "comments",
                   "id": "877"
              },
              {
                  "type": "comments",
                  "id": "2273"
              }
       ],
       "links": {
           "self": "http://127.0.0.1:9000/drf/users/1/relationships/comments/",
           "related": "http://127.0.0.1:9000/drf/users/1/comments/",
           "first": "http://127.0.0.1:9000/drf/users/1/comments/?page=1",
            "last": "http://127.0.0.1:9000/drf/users/1/comments/?page=1",
            "next": null,
            "prev": null
       }
},
```

It is very confusing what the `next`. `prev`, etc. links should be, and what the pagination meta should represent. The pagination of the target `http://127.0.0.1:9000/drf/users/1/comments/` (which can be paginated differently btw, i.e. by 20 at a time), or the pagination of the nested structure (3 at a time)? 

Is the meta supposed to be there or not for the pagination? 

Not paginating the nested structure is not an option, as I can have hundreds of relations.

**Comment by maryokhin** [comment]
@dgeb @ethanresnick are there any updates/thoughts/guidance regarding nested pagination of relationships? Because to me this feels like the primary blocker to trying this API format on a live system.

**Comment by oligriffiths** [comment]
@dgeb I notice this issue is still open and doesn't appear to have been solved. This appears to be a blocking issue in Ember Data that implements JSON API. Just wondering if there is any update to this, been over a year since the last comment. Thanks

**Comment by Exelord** [comment]
another year later ;)

**Comment by dgeb** [comment]
Hmmm .... sorry, didn't realize this was still open. 

The [above comment](https://github.com/json-api/json-api/issues/509#issuecomment-86795865) remains correct. In reviewing, @ethanresnick is correct that this needs to be clarified further in the spec. Probably in http://jsonapi.org/format/#fetching-pagination or http://jsonapi.org/format/#document-resource-object-relationships (or both).

The key point is that pagination links always paginate the collection referenced by the sibling `self` link. Thus, any pagination links in a relationship are for paginating the relationship data (NOT the related resources). Any pagination links for a primary data collection are for the primary data.

@oligriffiths what is the blocking issue in Ember Data? Is it still open?

**Comment by oligriffiths** [comment]
@dgeb as of now, there is no way to paginate relationships in ED due to lack of support in the spec, unless I’ve missed something and this has been changed. The spec really does need first class support for relationship pagination, and until it does I’d consider this blocking on any ED implementation. Rn, all implementations are hacks.

**Comment by dgeb** [comment]
@oligriffiths Thanks for clarifying. I believe that the spec _does_ provide complete support for relationship pagination, and am hopeful that #1251 clarifies this. To sum up:

* To paginate relationship data, pagination links (`next`, `prev`, etc.)  can be included in `links` in the relationship object.

* To paginate related resources only, follow the `related` link from `links` in the relationship object. Then pagination links (`next`, `prev`, etc.) can be included in the top-level `links` object of the response. 

Please let me know if you think anything is missing.

**Comment by oligriffiths** [comment]
Thanks @dgeb 
Having read over the docs, I don't think it's clear as there are no examples under the pagination section for either the main resource or relationships. 
http://jsonapi.org/format/#fetching-pagination
http://jsonapi.org/format/#document-compound-documents

I think it'd be prudent to add some examples so it's clear what this looks like.

**Comment by LukasTsunami** [comment]
3 years that the last update was made and I'm don't find a way to paginate related resources. Do you know some way to do something like this?
