### ISSUE TITLE
Name of the Spec Will Ensure Confusion

### ISSUE THREAD

**Issue by kenmazaika** [json-api/json-api#51]
I feel like this is going to get a lot of hate; but I'm going to post it anyway.

If this specification is to take off and become the defacto-standard I think it's name will cause a lot of confusion when communicating about API's as it will not be clear what is actually meant by "This is a json-api".  Does the documentation mean it follows this spec, or just a confused developer talking about a regular json api and they actually have no idea what they're talking about.  Was the hyphen just a typo?  Who knows?

I think we assume that people will be on our level whose API's we consume, but I've worked with API's (out of necessity not choice), from developers who kind of get stuff but are seriously missing some key aspects.

Two examples of people sort of getting it that I can pull of the top of my head.

> > API 1: XML Based API
> > 
> > The developer built an API with the server built in dot net.  I was consuming the API in Ruby or Java, or something without the native auto-wiring abilities.  Dot-net hooked up the web service with XML in a certain format automatically: which exposed it with xml headers, and xml response body in separate fields in the xml.
> > 
> > The developer read up on how the API's were built, and knew that the request was supposed to follow that convention, so in the "response" xml bit, they rebuilt a new response, wrapped in the containing xml.  It resulted in an XML request, embedded as a string inside a separate xml request.
> > 
> > I convinced myself when integrating with this API it was built by xzibit.  Yo dawg, I heard you like xml, so I put some xml in your xml so you can parse while you parse.  I'm excited about the opportunity to reuse that joke.
> > 
> > API 2: Proper use of HTTP Codes
> > 
> > The developer knew that using the proper HTTP codes in responses was important.  So the response code was embedded in the json response.  Some examples:
> > 
> > HTTP: 200 OK
> > Response:
> > {
> >  "status":200,
> >  "body": "omg"
> > }
> > 
> > HTTP: 200 OK
> > Response:
> > {
> >  "status": 404,
> >  "body": "not found"
> > }

Calling this the "json-api" schema will ensure that confusion about whether or not the json follows this spec, or just is an api that returns json with many developers.

I also find it a little misleading, as there are other completely reasonable JSON API formats.    See #50.  Technically most of those are "json api" specs as well.

To draw a comparison of a similar topic, take REST.  If someone says their API is a RESTful one it is immediately clear that when it comes to "REST" they get it.

But what if it was named a little differently.  REST is basically just "let's use HTTP requests the way that the HTTP spec was defined".  Following the same convention REST could've been called "HTTP".  "Yeah bro, I'm integrating with this HTTP-api".  Would that dude mean a REST api, or just an API that goes over HTTP, like API example number 2.  Who knows?

Just my 2 cents.

**Comment by steveklabnik** [comment]
> Calling this the "json-api" schema will ensure that confusion about whether or not the json follows this spec, or just is an api that returns json with many developers.

It will not cause confusion, because it (after the paperwork clears) be a registered media type. If your app serves `application/vnd.api+json`, then it follows this spec. If it doesn't, it doesn't.

>  REST is basically just "let's use HTTP requests the way that the HTTP spec was defined".

No, it's not. REST is an architectural style defined by Roy Fielding in his doctoral work.

**Comment by kenmazaika** [comment]
Just saying, the confusion won't exist in the actual implementation of the API, but rather conversations and documentation about the API.  Get ready to argue with developers saying "no this is not a 'json api'".

Also in this case I was using REST as an analogy, and a over-simplification, but still generally pretty close to reality.
