### ISSUE TITLE
Example doesn't seem to be json-api

### ISSUE THREAD

**Issue by platy** [json-api/json-api#512]
The implementations page links to an example at https://restpack-serializer-sample.herokuapp.com/ 
On a quick observation the responses don't provide the main data in an entry named "data" and resource objects don't include types. Maybe it conformed to an earlier version of the spec.

This should be removed to avoid confusion - It would be good to have another example.

**Comment by ColtonProvias** [comment]
It did conform to an earlier version of the spec. Yet it should be noted that the spec is still in active development, so implementations are almost always going to be behind until it reaches 1.0 final.

**Comment by platy** [comment]
Thanks, I'm looking forward to the final version.
