### ISSUE TITLE
Plural names of resources

### ISSUE THREAD

**Issue by e-oz** [json-api/json-api#517]
Plural names of resources is not a best practice.  
Please read answers here: http://stackoverflow.com/questions/338156/table-naming-dilemma-singular-vs-plural-names

**Comment by tkellen** [comment]
Plural names are not required by this specification, they are a recommendation. Please feel free to structure your URLs as you see fit.

**Comment by e-oz** [comment]
But it's a harmful recommendation. Closing issue in first response killing any hopes about discussion. So it will remain "standard" for small bunch of "inventors". And for Ember.JS users.

**Comment by tkellen** [comment]
I truly hope that we can reach consensus in your other issues, that the discussions around your questions and objections will ultimately improve this specification, and that when we are through there will be shared understanding between us.

With regards to this particular issue--we need to move past this kind of hair splitting and focus on more important matters.
