### ISSUE TITLE
GET Ok response

### ISSUE THREAD

**Issue by e-oz** [json-api/json-api#519]
> A server MUST respond to a successful request to fetch an individual resource or resource collection with a 200 OK response

Status code of successfull response  **MUST** be in range 200-299, any other restrictions are pointless. Status codes can be used as additional information from API.

**Comment by tkellen** [comment]
I'm not opposed to relaxing this requirement. @dgeb?

**Comment by e-oz** [comment]
I'm not going to implement this proposal of standard because of your position about "PATCH" verb and "id" field in responses, so I don't see reasons to argue and closing all my issues.
