### ISSUE TITLE
No need to couple REST and Entity Concerns

### ISSUE THREAD

**Issue by kenmazaika** [json-api/json-api#52]
This issue will also probably get a lot of hate.  Enjoy.

Seems like this spec is doing two things, when in practice it would be better if it did one thing well.  This is defining how to use REST (response codes, urls, etc); plus how json entities for the objects should be defined.

REST has already been defined (and if it hasn't been clearly spec'ed out, which I'd be surprised, maybe we should make a clear spec for that as well).  By coupling the two ideas it becomes a little less flexible.

Say we want to store a json-api format entity (meta, etc) in memcache.  Saying it was a "json-api" json object wouldn't really make sense, because the post data wouldn't be there.  Also I don't see a reason why someone couldn't use entity format across a non-RESTful API; could be useful in a binary protocol api or something.

Just my 2 cents.  Feedback welcome, haters.

**Comment by steveklabnik** [comment]
There is tons of precedent for a media type defining both the format and how it interacts with HTTP (not REST). See, for example, ATOMpub.

Not a hater, but this has nothing to do with REST.
