### ISSUE TITLE
Fetching Relationships

### ISSUE THREAD

**Issue by e-oz** [json-api/json-api#520]
> For example, the following request fetches data about an article's comments:
> 
> ```
> GET /articles/1/links/comments
> ```

It's difficult to implement on the server side, why not use just plain endpoints? Why should endpoint care about nested structures? This limitation will significantly reduce chances of this document to be used as a working standard.

**Comment by tkellen** [comment]
I'm not sure I understand what you mean by "plain endpoints". Can you clarify?

Also, if this section doesn't illustrate what these documents are for, can you please explain more clearly what the confusion is?
http://jsonapi.org/format/#crud-updating-relationships

**Comment by e-oz** [comment]
Under "plain" I mean endpoint, returning 1 kind of resource always. And responsible for 1 kind of resource, what is more important.
In URL "/articles/1/links/comments" we have 3 names of resources, so endpoint "articles" should:
1. Know about existence of `links` and `comments`
2. Implement CRUD actions for links and comments
3. Be rewritten when new kind of sub-resource will appear.

It leads to violation of Single Responsibility principle, code duplication and, therefore, increases amount of bugs or missing parts in implementation.

Much better when we can fetch comments with this URL:
`/comment?article_id=1`

**Comment by tkellen** [comment]
I think you are misunderstanding what relationship documents are for.

The URI `/articles/1/links/comments` does not provide the comments themselves, it refers to the **relationship** of comments to a given article. This provides a resource which can be augmented to link or unlink other comments to a given article.

What you've described would be accessed via `/articles/1/comments`. This could easily be de-structured internally to `/comments?article_id=1` if you wish. My implementation has no duplication of code for this functionality.

Personally, I would recommend against exposing the foreign keys of your database to end users, the URI `/articles/1/comments` is much more tolerant to internal changes than `/comments?article_id=1`.

All of that being said, you're welcome to structure your URLs as you see fit!

**Comment by e-oz** [comment]
At least this issue isn't closed yet, lol.

> The URI /articles/1/links/comments does not provide the comments themselves, it refers to the relationship of comments to a given article.

Why should client or server care about their relationship? Comments are comments, and doesn't matter if their parent resource in tree being called "links" or "blogs". 

> This could easily be de-structured internally to /comments?article_id=1 if you wish. My implementation has no duplication of code for this functionality.

Your implementation at least have to parse words "links, comments, article" just to transform that request. But "comments" endpoint don't have to know about existence of links and articles at all.

> Personally, I would recommend against exposing the foreign keys of your database to end users

Me too. I never said you should. This issue is about absolutely different thing. You can set id of article in billions ways in that URL.

> All of that being said, you're welcome to structure your URLs as you see fit!

No, I don't think so:

> A server MUST support fetching relationship data for every relationship URL

So if this standard will be accepted, each system, which want to implement it, will be **MUST** to implement this part too.

**Comment by e-oz** [comment]
I'm not going to implement this proposal of standard because of your position about "PATCH" verb and "id" field in responses, so I don't see reasons to argue and closing all my issues.
