### ISSUE TITLE
'type' field

### ISSUE THREAD

**Issue by e-oz** [json-api/json-api#521]
What is the reason of existing of the `type` field? We already have name of the resource in the URL.

**Comment by tkellen** [comment]
Imagine you requested: `/author/1?include=books,papers`. The response would contain multiple resources of differing types. Using the `type` field, the client can differentiate between them.

At first, it may seem to make sense to simply place each type of resource under a top-level key of the same name (this is how a much earlier version of the spec worked). This pattern breaks down for polymorphic relations.

Imagine you requested `/author/1?include=publications` where publications could be either of the type `books` or `papers`. In this scenario, the unique identifier for each publication would be a combination of the `id` and `type` field.

The current version of the specification (likely to become 1.0 soon) puts this style of relation on a level playing field with non-polymorphic ones. It also makes it possible to stream results to the client with less intermediate buffering.

I'm going to close this issue but please feel free to continue the discussion if this has not sufficiently clarified the usage of `type`.

**Comment by e-oz** [comment]
No, response will contain list of resources of one kind: `author` because we requested this resource. All additional resources can be returned as nested fields or in additional fields.

> include=publications where publications could be either of the type books or papers

publications can be only of the type "publication", otherwise there is no sane way to predict what will be returned by API, when we request resource of one name, and it returns few another types.

**Comment by tkellen** [comment]
There is no need to predict what will be returned by the API. The related documents appear under the top level `data` and `included` key as an array regardless of what is in your query params.

**Comment by tkellen** [comment]
That said, I agree in principal that polymorphic relations are a bad idea. I won't personally use them in my APIs but I have no issue with presenting my data in a format that is interoperable with those who do.

**Comment by e-oz** [comment]
> There is no need to predict what will be returned by the API

I absolutely disagree. It sounds ridiculous for me when you send request to API, it returns "something" and client side should do "something" with that "something". When client requests list of users and API returns list of comments, conflict will happen.

**Comment by tkellen** [comment]
This will never happen. Each item in the `included` or `data` key must include a `type` field indicating what type it is. There will be no ambiguity for the client.

**Comment by AlexParamonov** [comment]
@jamm I already tried to stop this "data" madness here: https://github.com/json-api/json-api/issues/365
But it seems that polymorphic objects as one big mess are better than a clean spec.
