### ISSUE TITLE
POST response

### ISSUE THREAD

**Issue by e-oz** [json-api/json-api#522]
> The response MUST also include a document that contains the primary resource created.

It's pointless waste of traffic and bad for security - for example, if we create "user" object, we should never return "password" field, containing password hash. In other words, not all fields should be revealed by API and when client send request to create object, client knows all necessary fields already, so no reason to return them back.

**Comment by tkellen** [comment]
There are many instances where a newly created resource contains information the client has not provided. For example, unless an implementation supports client-generated uuids, the server is likely responsible for assigning an ID to the resource. Additionally, the representation of a resource is not a one-to-one mapping of what is stored on the server. There is no conflict with omitting fields for security purposes.

**Comment by e-oz** [comment]
There is no word in "standard" about omitting fields.

**Comment by e-oz** [comment]
But explicitly required to return a resource, not 1 or more fields.

**Comment by milap-neupane** [comment]
##### A resource object MUST contain at least the following top-level members
- "id"
- "type"

Which means others are optional. Is not that valid here ? @tkellen  @jamm

**Comment by e-oz** [comment]
no, @milap-neupane, id field not always can be revealed too.

**Comment by milap-neupane** [comment]
If the client cannot access the resource created what's the point. Can you illustrate the condition when id cannot be revealed.

**Comment by e-oz** [comment]
@milap-neupane client not always should have access to created resource. API will decide it, not client. 
ID can't be revealed when it should stay secret or when resource doesn't have such field as ID (and it's common for logging systems).

**Comment by tkellen** [comment]
In order for a resource to exist in a json-api compliant api, it must have both an `id` and a `type`. For a logging system without an internal id field, you could use the timestamp as the `id` for a compliant representation.

I still don't understand what real world scenario would have a resource created by a client become secret at the time of creation.

**Comment by e-oz** [comment]
Timestamp is not a unique thing, a lot of events can happen simultaneously.  
I gave you example but you don't want to understand it - what can I do else? 

Main misunderstanding here: **we don't need ID to make this request**, and to complete it, so there is **NO** reasons to require `id` field be returned. Making this a requirement without any reasons except "we like it", makes this proposal too opinionated and restrictive to be accepted. So if this requirement will remain, then feel free to close all my issues here.

**Comment by e-oz** [comment]
I'm not going to implement this proposal of standard because of your position about "PATCH" verb and "id" field in responses, so I don't see reasons to argue and closing all my issues.
