### ISSUE TITLE
PATCH verb

### ISSUE THREAD

**Issue by e-oz** [json-api/json-api#523]
Why not use much more widely implemented PUT verb? As illustration, nginx doesn't have PATCH in the list of supported verbs by default.

**Comment by tkellen** [comment]
Please see #291.

**Comment by e-oz** [comment]
Thanks, but that thread doesn't contain answer rather than "we like PUTCH more". It's not the responsibility  of this standard (proposal) to make people use PATCH because it's more idiomatic.

**Comment by tkellen** [comment]
You're welcome to implement PUT if you wish, but the semantics of it will almost undoubtedly remain undefined for JSON-API.

**Comment by e-oz** [comment]
@tkellen that's the reason why I created that issue. So what is your answer? You will insist on implementing PATCH method by each API?

**Comment by tkellen** [comment]
At the present moment, yes. That said, json-api is structured specifically to allow additive changes over time. If we can arrive at a consensus for the semantics of PUT, nothing is stopping us from adding it. I would encourage you to read the issues surrounding our attempts to do so and open a PR with your suggestion for resolution.

**Comment by e-oz** [comment]
Then you are going too far. I will not implement PATCH, reconfiguring servers, just because you like it more than "PUT" - I don't care about your personal preferences, really. And I think [GAE will not care too](https://code.google.com/p/httplib2/issues/detail?id=219).

**Comment by tkellen** [comment]
It's a bit unrealistic to expect that every disagreement you have with a project will be resolved in a single sitting with no effort on your part save for a few complaints about how things don't align with your personal preferences.

If you actually have a desire to participate in this process, please consider re-opening the issues that are serious deal-breakers and give the other maintainers and collaborators on this project a chance to chime in.

**Comment by e-oz** [comment]
It's not personal preferences, I explained all my motivations, not just "I
like it because I like it". I spent few hours on it (4 hours to be
precise), so I wouldn't call it "single sitting with no efforts". You don't
want to change parts which are critical for me so I don't see reasons to
waste my and your time to pointless arguing.
You have my feedback, hope it will be useful at least a bit :)

**Comment by bintoro** [comment]
@jamm If you look at the HTTP specification, you will find that PUT is intended for full resource replacements, while PATCH is intended for partial updates.

In JSON API, updates are partial by default. That is, you can specify a subset of the attributes, and the rest will be left intact. PATCH is therefore the correct verb, not just a "preference".

**Comment by e-oz** [comment]
@bintoro world of people is not as perfect as we want. It would be awesome if all servers and middleware tools support PATCH verb, but as it's not our reality, it's strange to see this requirement. It just will decrease adoption rate, nothing more. Because no real reasons behind, only perfectionism.
