### ISSUE TITLE
DELETE response

### ISSUE THREAD

**Issue by e-oz** [json-api/json-api#524]
> A server MUST return a 204 No Content status code if a delete request is successful.

Again, server should be able to return any code in 2xx range and it will be valid response.

**Comment by tkellen** [comment]
I'm not opposed to relaxing this requirement @dgeb?

**Comment by e-oz** [comment]
I'm not going to implement this proposal of standard because of your position about "PATCH" verb and "id" field in responses, so I don't see reasons to argue and closing all my issues.
