### ISSUE TITLE
Dasherized names

### ISSUE THREAD

**Issue by e-oz** [json-api/json-api#525]
It's just recommendation, but just for curiosity, please let me know how such names supposed to use in JS? `obj['dash-name']` instead of `obj.camelCase` or `obj.underlined_name`? And do you really use "dasherized" names for objects fields on the server side?

**Comment by tkellen** [comment]
You are correct, dasherized properties in javascript can be accessed as you've shown (e.g. `obj['dashed-name']`) Yes, some (but not all) implementations use dasherized names on the server side.

**Comment by notslang** [comment]
I found this to be pretty strange... since JSON is derived from JS, I would expect it to follow the same camelCase naming that JS uses.

**Comment by notslang** [comment]
Oh, and this is a duplicate of #323
