### ISSUE TITLE
New visual design including document outline navigation

### ISSUE THREAD

**Issue by wvteijlingen** [json-api/json-api#527]
I found the spec hard to read because everything is one page without any document outline or other navigation. When trying to add a sidebar I got the idea to refresh the whole design. Now I am by no means a great designer, but this is what I quickly whipped up.

I've added a (fixed) sidebar that contains a document outline for some pages. This is generated with JavaScript, which is the only way to do it using Github pages afaik.

The design is still pretty bland, but if you guys think this is an improvement, I'll make a pull request for it. The HTML and CSS is already done. I think for the 1.0 release this will be a nice refresh.

![json-api home](https://cloud.githubusercontent.com/assets/1460535/6886278/4bbc7a20-d637-11e4-9483-bbc877d48e81.png)
![json-api format](https://cloud.githubusercontent.com/assets/1460535/6886279/4e07cb18-d637-11e4-834d-618f69d2312a.png)
![json-api format scrolled](https://cloud.githubusercontent.com/assets/1460535/6886284/a2ea78ce-d637-11e4-994f-24c92ab9d2b9.png)

**Comment by bintoro** [comment]
> I've added a (fixed) sidebar that contains a document outline for some pages.

Thank you! This alone is a massive improvement.

**Comment by gr0uch** [comment]
:+1: looks good, and the sidebar looks super useful.

**Comment by ethanresnick** [comment]
As others have said, this looks great! Thanks for all your hard work, @wvteijlingen! The sidebar looks incredibly useful. 

The only (small) thing I might do is makes a measure of the text a little narrower on the homepage. Also, where does the "Documentation" button on the homepage link to? If it goes to the same page that's called "Format" in the navigation, that might be a little bit confusing.

**Comment by dgeb** [comment]
Well done @wvteijlingen! I really appreciate the layout improvements, especially the sidebar.

I do think there's something to be said for a small logo at the top left of every page, similar to the current design.

Anyway, a PR that we could tweak and launch with 1.0 would be awesome. Thanks for your work!

**Comment by steveklabnik** [comment]
Yes, this is wonderful. Thank you so much! :heart:

**Comment by wvteijlingen** [comment]
Thanks for the feedback! I'll make a pull request soon, just need to sprinkle in some more responsiveness.

> Also, where does the "Documentation" button on the homepage link to? If it goes to the same page that's called "Format" in the navigation, that might be a little bit confusing.

Good point. I now have the captions "Read the specification", and "Contribute on Github". But that implies that we need to rename "format" to "specification". Don't know how you guys feel about that. Technically the other pages belong to the specification as well of course.

**Comment by steveklabnik** [comment]
We had already thought 'format' was a bad name, 'specification' is a good one
