### ISSUE TITLE
Adding a summary or similar in the presentation of http://jsonapi.org/

### ISSUE THREAD

**Issue by xcombelle** [json-api/json-api#528]
Being aware of this project in twitter, I couldn't understand what was the purpose of this project. It looked very complicated in particular the example

after asking on twitter
https://twitter.com/Xavier_Combelle/status/581765642669395969
I had got the following answer (in french)

in a REST response context
a formal proposal for URL of reference to the current resource and related resources and key names

that's all

after reading this answer I had got an ah ah moment and eventually understood the example

I don't know either if the answer given to me is correct or complete but I think at least something similar would be needed in the presentation (I mean this page: http://jsonapi.org/ ) under a title like Summary or  In short  or  Intent or similar

**Comment by tkellen** [comment]
I would love a PR for this if you have the time/inclination to make one!
