### ISSUE TITLE
Media type in resource relationships

### ISSUE THREAD

**Issue by dmtrs** [json-api/json-api#532]
I did a draft search in the issues but was not able to find something relevant.

Would it be considered valid to have media-type inside the `type` attribute. Example:

```
{ 
"data":  {
    "type": "application/vnd.api.articles+json",
    "id": "1",
    "title": "Rails is Omakase",
    "links": {
       "self": "http://example.com/articles/1",
       "author": {
           "self": "http://example.com/articles/1/links/author",
           "related": "http://example.com/articles/1/author",
           "linkage": { "type": "application/vnd.api.people+json", "id": "9" }
       },
       "thumbnail": { "type": "image/png" },
       "comments": "http://example.com/articles/1/comments"
   }
}}
```

On the above example I have included `thumbnail` without a uri "meaning" a fallback to `self` ("http://example.com/articles/1").
My main goal is the client could know the content-type of a resource we link on. Thanks and sorry if late to the party.

**Comment by dgeb** [comment]
The value of `type` is completely opaque to the spec - any string is acceptable.

It does bump against the [recommendations for URL design](http://jsonapi.org/recommendations/#urls), but those are just recommendations of course.
