### ISSUE TITLE
Updating a resource via a nested URL 

### ISSUE THREAD

**Issue by timabdulla** [json-api/json-api#537]
The spec's current wording leaves some ambiguity about the possibility of updating a resource via a nested URL in the case of a belongs-to or a has-one relationship. For instance, if an account holder has a credit card and I want to modify a property of the credit, is it possible to `PATCH` the URL at `/account_holders/1/credit_card`?

The spec currently says, "A resource's attributes and relationships can be updated by sending a PATCH request to the URL that represents the resource." The source of the confusion is that this wording implies that there exists only a singular URL for any resource to which all `PATCH` requests should be forwarded. If it is possible to modify a resource in the manner discussed above, I would recommend the wording be modified to, "A resource's attributes and relationships can be updated by sending a PATCH request to _a_ URL that represents the resource."

**Comment by timabdulla** [comment]
any thoughts on this?

**Comment by tkellen** [comment]
Sorry for the slow reply @timabdulla! JSON-API does not take a stance on URL forms. You're welcome to use nested URLs if you like! In the future, questions like this would be better served over at http://discuss.jsonapi.org
