### ISSUE TITLE
Short linkage object when relation is obvious

### ISSUE THREAD

**Issue by ksimka** [json-api/json-api#538]
Say we have `/posts/:id` for fetching one post, so according to current jsonapi when using `/posts/1?include=comments` we'll get

``` js
{
  "data": {
    "type": "posts",
    "id": "1",
    "title": "Woohoo!",
    "links": {
      "self": "http://example.com/posts/1",
      "comments": {
        "self": "http://example.com/posts/1/links/comments",
        "related": "http://example.com/posts/1/comments",
        "linkage": [
          { "type": "comments", "id": "5" },
          { "type": "comments", "id": "12" }
        ]
      }
    }
  },
  "included": [{
    "type": "comments",
    "id": "5",
    "body": "First!",
    "links": {
      "self": "http://example.com/comments/5"
    }
  }, {
    "type": "comments",
    "id": "12",
    "body": "I like XML better",
    "links": {
      "self": "http://example.com/comments/12"
    }
  }]
}
```

> A "linkage object" is an object that identifies an individual related resource. It **MUST** contain type and **id** members.

But there is only one "post" object, so it's obvious all the comments are belong to it. Therefore ids in "linkage" are redundant here. One short linkage object with "type" is enough, like saying "all the objects of the type 'comments' are related to post"

``` js
// ...
"comments": {
    "self": "http://example.com/posts/1/links/comments",
    "related": "http://example.com/posts/1/comments",
    "linkage":  { "type": "comments" }
}
// ...
```

Or am I missing something?

**Comment by dgeb** [comment]
There will always be inferences that we as humans can easily make based on particular content. And indeed, we could program clients to understand these inferences. However, all of the logic we use to make these inferences gets complicated to codify and implement, and this complexity leads to less robust implementations. Therefore, the spec favors verbosity in most cases like this.

**Comment by ethanresnick** [comment]
This can be closed!
