### ISSUE TITLE
Namespace of attributes/relationships and custom endpoints

### ISSUE THREAD

**Issue by hhware** [json-api/json-api#542]
Does JSON API have any position/recommendation on custom endpoints, i.e. on methods which do not fit GET/POST/PATCH, because, for example, they need to perform multiple actions, perform actions on multiple associated resources, accept non-standard input, etc? Specifically, it is widely assumed that slash-separated paths refer to resource attributes or relationships, as in `http://example.com/articles/1/author`. If an API needs to provide a custom method `POST http://example.com/articles/1/custom`, would it be enough that `articles` has no attributes/relationships called `custom`, or is there more to it?

**Comment by tkellen** [comment]
JSON-API has no requirements about uri structure, implementations are free to use whatever form they wish. Perhaps this should be a non-normative note somewhere--this question or variations thereof have come up several times.
