### ISSUE TITLE
Filter recommendation may be incompatible with URI Template spec

### ISSUE THREAD

**Issue by maetl** [json-api/json-api#544]
It looks as if using `filter[name]=value` directly is incompatible with the URI Template specification documented in RFC6570, but `filter%5Bname%5D=value` works. Unsure if that’s expected or not.

The practical consequences of this are as follows:
- URI templates cannot be used to specify precise filter patterns in URLs that follow the JSON API recommendation. eg: `expand("{?filter[name]}", name="val")` will not expand to the expected string `"?filter[name]=val"` using popular URI template libraries.
- URI templates like `{?filter*}` _can_ be expanded to valid URLs with the `%5B`-`%5D` encoding (see [example here](https://gist.github.com/maetl/3d6330093aaf3bc175bf#file-template_builder-rb)), but this means that the template cannot specify an expansion of exact parameter names, nor can it expand to a non-urlencoded key names with the `[]` characters appearing.
- For newcomers to JSON API who want to leverage existing libraries for URI generation, there’s additional overhead in having to look up RFC documents and interpret the ambiguity of whether `[]` and `%5B%5D` mean the same thing or not. These generated URLs are less readable and don’t follow the examples on the JSON API website.

It would be good to confirm whether or not an incompatibility exists, and document this somewhere/somehow to clarify what the expectations are. URI Templates are a powerful and standardised way of generating URLs and seem like a good complement to JSON API itself.

**Comment by tkellen** [comment]
@maetl Sorry for the terribly delayed reply. I just tested this on express (node) and rack (ruby). Both treat percent encoded and literal values the same. I'm not sure what server you're using, but I suspect you'll see similar behavior anywhere else. I'll update the specification to include a note about this.

**Comment by tkellen** [comment]
Resolved in #756
