### ISSUE TITLE
Not specified what happens when server doesn't support include request parameter

### ISSUE THREAD

**Issue by jaspervz** [json-api/json-api#552]
The specification mentions that an endpoint MAY support custom inclusion, but doesn't specify what happens when a client issues a request with an include request parameter and the server doesn't support it. Proposal: server MUST return a 400 Bad Request, the same as for the sorting.

**Comment by ethanresnick** [comment]
@dgeb Are you in favor of this proposal? If so, I'd be happy to submit a PR before 1.0. It makes support for the `include` parameter much more visible than requiring the client to look for `"included"` in the payload.

**Comment by dgeb** [comment]
@ethanresnick yes, a PR would be appreciated. Thanks!

**Comment by ethanresnick** [comment]
@dgeb This can be closed now :)
