### ISSUE TITLE
Server must now support sparse fieldsets, proposal may

### ISSUE THREAD

**Issue by jaspervz** [json-api/json-api#553]
According to the specification, the server must support sparse fieldsets. Proposal: the server MAY support sparse fieldsets. If the client issues a request with the fields parameter and the server doesn't support them, the server MUST issue a 400 Bad Request.

**Comment by gr0uch** [comment]
There is already too much ambiguity over what is a MAY or a MUST in the main specification. I would prefer MUST over MAY.

**Comment by lgebhardt** [comment]
I agree. I also prefer MUST over MAY. The more optional concepts we can remove the better. In this case it seems simple, but it implies every client will need to account for servers that may or may not support sparse fieldsets.

**Comment by tkellen** [comment]
:+1: to to MUST.

**Comment by dgeb** [comment]
@wycats and I agreed that MUST was not too onerous to support for server implementations, and specifically chose MUST over MAY to simplify client implementations.
