### ISSUE TITLE
Please don't abuse HTTP PATCH.

### ISSUE THREAD

**Issue by ben-crowhurst** [json-api/json-api#556]
**Implement a PATCH document with a different Media-Type**

[RFC 5789](http://tools.ietf.org/html/rfc5789)

>  The PATCH method requests that a set of changes described in the
>   request entity be applied to the resource identified by the Request-
>   URI.  **The set of changes is represented in a format called a "patch
>   document" identified by a media type.**  If the Request-URI does not
>   point to an existing resource, the server MAY create a new resource,
>   depending on the patch document type (whether it can logically modify
>   a null resource) and permissions, etc.

**Implement a PATCH document**

[RFC 5789](http://tools.ietf.org/html/rfc5789)

>  The difference between the PUT and PATCH requests is reflected in the
>   way the server processes the enclosed entity to modify the resource
>  identified by the Request-URI.  In a PUT request, the enclosed entity
>   is considered to be a modified version of the resource stored on the
>   origin server, and the client is requesting that the stored version
>   be replaced.  **With PATCH, however, the enclosed entity contains a set
>   of instructions describing how a resource currently residing on the
>   origin server should be modified to produce a new version.**  The PATCH
>   method affects the resource identified by the Request-URI, and it
>   also MAY have side effects on other resources; i.e., new resources
>   may be created, or existing ones modified, by the application of a
>   PATCH.

[Please, don't PATCH like an idiot](http://williamdurand.fr/2014/02/14/please-do-not-patch-like-an-idiot/)

**Comment by bintoro** [comment]
I don't think there's any abuse going on. A partial resource representation can most definitely act as a "set of instructions" for modifying the resource. Most of the comments to that blog post seem to agree.

The author of the post makes a poor case. He specifically points out that

> You can use whatever format you want as [description of changes], as far as its semantics is well-defined.

but insists that partial representations are not OK as such descriptions — without providing any justification at all. I don't see anything in the relevant RFCs that would support this interpretation.

**Comment by ethanresnick** [comment]
Likewise, while I understand that the PATCH document needs to be identified by a media type to be interpretable, I don't see why that media type couldn't be the same as the one used for GET, POST, etc. requests, assuming the media type definition itself defines its semantics when used with different HTTP methods, as the json - api media type does. So I also don't see any abuse here.

**Comment by ethanresnick** [comment]
Or, the patch document's media type does have to be different (since I guess it is representing a different kind of data...though this still feels too pedantic to me), we could always add a simple media type parameter

**Comment by bintoro** [comment]
> Or, the patch document's media type does have to be different (since I guess it is representing a different kind of data [...])

It's the same kind of data: a JSON API document. The HTTP method dictates what the server should do with the data; no need to bring the media type into it.

**Comment by wwwdata** [comment]
I agree with you guys. The current usage of PATCH is absolutely fine and not abusive.

@ben-crowhurst: What exactly is wrong with the way jsonapi does PATCH requests?

**Comment by ethanresnick** [comment]
@bintoro Right. But the same json-api document has different semantics when its `POST`ed vs. `PATCH`ed, and someone could argue that the meaning of the same document shouldn't vary in meaning depending on the method it's used with. If you accept that argument, then it might lead to coining a different media type. But, digging into this more, I think it's fine for the same representation to have different processing semantics with different methods. 

From [RFC 7231](https://tools.ietf.org/html/rfc7231#section-3.1.1.1):

> Media types define both a data format and various processing models: how to process that data in accordance with each context in which it is received.

That seems pretty explicit. So, yeah, I think the spec is fine here.

**Comment by dgeb** [comment]
I agree that PATCH is not being abused here.

Closing because the discussion seems to have played out.
