### ISSUE TITLE
TOC for format page

### ISSUE THREAD

**Issue by sharpner** [json-api/json-api#557]
Hi there, It would be awesome if you could add an toc to the format.md file. 

It's really hard to focus on specific problems when scrolling all the time =)

thx!

**Comment by steveklabnik** [comment]
Hey @sharpner ! We agree, we just haven't merged https://github.com/json-api/json-api/pull/531 yet

**Comment by sharpner** [comment]
ah sorry. A search for "table" and "contents" did not show any open issues ;)

**Comment by steveklabnik** [comment]
Yeah no worries :)

**Comment by dgeb** [comment]
Closed via #629.
