### ISSUE TITLE
Official extensions: responses not well defined

### ISSUE THREAD

**Issue by gr0uch** [json-api/json-api#561]
In the official spec there is a `Location` header in the response for creating a singular resource. This is not defined in the official bulk extension. When multiple resources are created and responded with, it makes it necessary to define routes to fetch multiple IDs:

```
Location: http://example.com/foo/1,2,3,4,5
```

In the patch extension, multiple resources may be created, but the response status is 200 (?) and not 201, and also the location header is missing here too.

**Comment by tkellen** [comment]
For APIs using UUIDs (or even large integer ids) this sort of response could easily hit header and url length limitations.

**Comment by gr0uch** [comment]
Renamed and updated original issue.

**Comment by dgeb** [comment]
Removing 1.0 milestone. Prefer to mark official extensions as preliminary in advance of 1.0. See #643.

**Comment by ethanresnick** [comment]
Closing, as the extensions in question are deprecated. @dgeb Feel free to reopen if you see any need.
