### ISSUE TITLE
Some questions after trying to implement the format

### ISSUE THREAD

**Issue by cziegenberg** [json-api/json-api#563]
Hi,

I'm currently working on a reader/writer/request handler for JSON API in PHP and had the following questions while implementing the format:

1) IMHO it doesn't make sense to include "errors" in the request document, so "A document MUST contain either primary data or an array of error objects" isn't valid for request documents.

2) I read that "A compound document MUST NOT include more than one resource object for each type and id pair", but shouldn't this rule be extended for linkage arrays that could also contain objects with the same type and id?

3) How to handle trailing slashes in URLs (when creating documents/handling requests)? This could result in different URLs for the same resource (duplicate content), which should be allowed.
Suggestion: No trailing slashes in documents. A request with a trailing slash in the URL, should be redirected (status 301) to the URL without the trailing slash. 

4) Is there a format for (top-level) members? Which characters are allowed (at special positions)? Are member names case sensitive? Can I use integers as members?
Suggestion:
- Periods (U+002E FULL-STOP, ".") aren't allowed, because it's used as the relationship path separator.
- Commas (U+002C COMMA, ",") aren't allowed, because it's used in the include parameter as a separator for multiple relationship paths.
- Members should not start with a digit ("0-9"), as this could be a problem when mapping API to the code, e.g. in PHP and C# object members of this type aren't allowed.
- Members should not contain a minus (U+002D HYPHEN MINUS, "-"), as this could be a problem when mapping API to the code, e.g. in PHP and C# object members of this type aren't allowed.
- Members should not contain a colon (U+003A COLON, ":"), as this could be a problem when mapping API to the code, e.g. in PHP and C# object members of this type aren't allowed. Also they could be reserved for later use in the include parameter?!
- When checking for duplicate members, members should be handled case insensitive, because they name a resource, which has special semantics, and this is independent from the spelling. When using member names in a request (e.g. with the include parameter), they should be handled case sensitive, because this would allow duplicate content for different spellings.
- Theoretically it isn't important if lower- or upper-case characters are used for the member names, but I'd suggest to always use lower-case, as this is the current format of the standard members and it would simplify the use by API clients.
- Underscores (U+005F LOW LINE, "_") should be allowed, as I don't know problems with underscores in member variables of any language.
- Resulting format: ^[a-z]+[a-z0-9_]*$

Awaiting your comments.
Thanks.

**Comment by dgeb** [comment]
Thanks for raising these concerns. Could you please open four separate issues for discussion and close this one?

**Comment by cziegenberg** [comment]
Okay. I also found another point that hasn't defined yet.

**Comment by cziegenberg** [comment]
Issues separated.
