### ISSUE TITLE
Structure of request documents

### ISSUE THREAD

**Issue by cziegenberg** [json-api/json-api#564]
The standard doesn't contain detailed information about request documents:
- IMHO it doesn't make sense to include "errors" in the request document, so "A document MUST contain either primary data or an array of error objects" isn't valid for request documents.
- Also meta information, included resources and links don't make sense for me (but perhaps there are special cases?).

**Comment by tkellen** [comment]
Thanks for taking the time to submit these issues Christoph.

Unfortunately, this feedback is not actionable. It would be very helpful if you could open specific/focused issues with concrete suggestions (such as you did in #567).

That being said, in response to your two notes:

Including errors in a document is very important for human users--status codes may be verbose enough for machines, but they are not for humans.

I'm not sure what you mean with your second bullet point?

**Comment by cziegenberg** [comment]
This is a specific issue. I want to know, which elements are allowed in request documents and need to be processed by the server. I will try to explain it...

Data:
Of course we need data from the client. :)

Errors:
Why should the server process error information sent form the client in the request document? The server sends errors (in the response document), and only for this direction your argument regarding the status codes doesn't makes sense to me.

Meta:
The same applies to meta information. Why should the server process this information? Meta information that shouldn't have any effect on the server-side.

Included resources:
Theoretically it would be possible to create/update/delete multiple (linked) resources at once (when Client-Generated IDs are supported), but MUST a server support it?

Links:
This is okay, if clients need to create/update/delete links to already existing (!) resources - the problem I had was with links to non-existent resources, as described in the previous point.

**Comment by tkellen** [comment]
Ah, I'm tracking now. Sorry about that.

Errors: Perhaps we should special case the definition of the error object in the Document Structure section. JSON-API does not define any semantics for servers to _receive_ an error document.

Meta: This member is available for servers and clients to use as they wish. A generic server does not need to process this, but we should not normatively restrict its usage for all implementations.

Included resources: This is not presently supported by the base specification, but can be achieved by using the [JSON PATCH](http://jsonapi.org/extensions/jsonpatch/) and [Bulk](http://jsonapi.org/extensions/bulk/) extensions.

Links: JSON-API makes a distinction between relationships and resources. Links will never include resources, they only include relationship data. This shouldn't be an issue.

**Comment by tkellen** [comment]
Whoops, accidentally posted that before I was done. Edited and updated.

**Comment by tkellen** [comment]
@ziege Please feel free to open a focused PR if you feel this is still unclear.
