### ISSUE TITLE
Trailing slashes in URLs

### ISSUE THREAD

**Issue by cziegenberg** [json-api/json-api#566]
How to handle trailing slashes in URLs (when creating documents/handling requests)? This could result in different URLs for the same resource (duplicate content), which should not be allowed.

Suggestions: 
- No trailing slashes in documents. 
- A request with a trailing slash in the URL, should be redirected (status 301) to the URL without the trailing slash.

**Comment by bintoro** [comment]
Why does this matter? A given resource may be exposed at any number of URLs anyway.

**Comment by cziegenberg** [comment]
A resource is identified by the URL, so I think it should be unique.

REST API Design Rulebook:
https://books.google.de/books?id=4lZcsRwXo6MC&pg=PA12&lpg=PA12&source=bl&ots=F4CtaBkuaP&sig=zPd3g8wd-1DTixB4WaXdrN1IQVA&hl=de&sa=X&ei=eU82VfvwHYitswHph4LQBg&ved=0CDEQ6AEwBg

**Comment by bintoro** [comment]
JSON API resources are not resources in the REST/HTTP sense. They are identified by their `type` + `id` combination, not by a unique URI.

To see why, consider that a response document from a single URI (a REST resource) may contain any number of JSON API resources.

**Comment by steveklabnik** [comment]
The specification makes no requirements on URL representation, so this isn't part of the spec per-se.

In theory, we could add something like this as a Recommendation, but I'm not sure it's worth it right now.

**Comment by cziegenberg** [comment]
It's true that different URLs can result in the same content being returned, also without trailing slahes. 

And when following the spec it's allowed to use an empty string as id (it's set - present and not null - and it's a string), so this case can only be represented with a trailing slash:

http://example.com/resource/{id}
would result in 
http://example.com/resource/ (id = empty string)
which is different from
http://example.com/resource (no id set)

Will close it... but perhaps empty strings should not be allowed as id, as this could be confusing.
