### ISSUE TITLE
Reserved attribute member names

### ISSUE THREAD

**Issue by cziegenberg** [json-api/json-api#568]
In the current version of the standard I read about the values of attributes that "a complex attribute MUST reserve the id, type, links, and meta members" - okay, but there's nothing about reserved member names of the attributes. 

Suggestion:
- The reserved members id, type, links, and meta are not allowed as attributes members.

**Comment by hhware** [comment]
Section [Resource Objects](http://jsonapi.org/format/#document-structure-resource-objects) defines members `id`, `type`, `links`, `meta`. Its subsection Attributes states that

> A resource object MAY contain additional top-level members. These members represent "attributes" 

To me, it means that `id`, `type`, `links`, `meta` are not attributes. Wouldn't you agree?

**Comment by cziegenberg** [comment]
Yes, I agree, but they share the same namespace, so the reserved resource level members are also reserved attribute members. It was just a suggestion to clearly say what is allowed and what not, although it's already mentioned somewhere else in the spec. 

In my opinion it helps to understand the spec if things are clearly defined, and not derived from other rules that are spread over the whole spec... Element -> allowed, not allowed.

**Comment by cziegenberg** [comment]
Closed as the new "attributes" member changed the situation.
