### ISSUE TITLE
Running examples

### ISSUE THREAD

**Issue by harry-wood** [json-api/json-api#572]
There's currently a list of examples here : http://jsonapi.org/implementations/#examples  featuring just one example: http://restpack-serializer-sample.herokuapp.com ...which is a toy example, and not following the spec https://github.com/RestPack/restpack_serializer/issues/123

Are there any other (running) examples we can look at? Is that what this is?: https://github.com/json-api/json-api-demo  Is it running somewhere?

Any others? maybe even a _real world_ example?

**Comment by tkellen** [comment]
http://github.com/endpoints/example is a pretty-close-to-spec-compliant implementation. I really need to add endpoints to the implementation examples!

**Comment by steveklabnik** [comment]
> maybe even a real world example?

https://www.balancedpayments.com/ was using us to process over a million dollars of credit card charges per day. Unfortunately, startup life is hard, as you can see from their page.

**Comment by ethanresnick** [comment]
@harry-wood My organization runs our real-world api off the json-api spec (using [this library](http://github.com/ethanresnick/json-api)). Unfortunately, that APIs not public right now.

As a substitute, it might help to heck out http://github.com/ethanresnick/json-api-example! It is a bit of a toy implementation, as you say, but it's spec compliant and useful to play around with.

**Comment by tkellen** [comment]
Endpoints has an example app and it's linked on our example pages now.
