### ISSUE TITLE
proposal to reserve "attributes" member at top level of resource objects

### ISSUE THREAD

**Issue by tkellen** [json-api/json-api#573]
At the moment, we reserve `id`, `type`, `links`, and `meta` members in resource objects. We feel pretty dang sure these are the only ones we will ever need. However, the possibility remains that at some point in the future, we may wish to reserve another. Doing so would be additive/backwards-compatible with the spec, but it would not be backwards compatible with implementations if they are currently using that member as an attribute in their data.

There has been quite a bit of discussion around the prefixing or not-prefixing of reserved members since the inception of the spec (e.g. #313, #362, #558, #569) and we've always landed on not prefixing. I personally agree with this approach, but I'd like to propose an alternate representation for resource objects that should completely eliminate these concerns by walling off implementation-specific attributes under their own namespace.

``` json
{
  "id": "1",
  "type": "book",
  "attributes": {
    "name": "J. R. R. Tolkien",
    "date_of_birth": "1892-01-03",
    "date_of_death": "1973-09-02"
  },
  "links": {
    "chapters": {
      "self": "/books/1/links/chapters",
      "related": "/books/1/chapters"
    }
  }
}
```

Not only does this form prevent future conflicts, it would serve to simplify the normative language of the specification--terms like `members` and `attributes` would be reflected in the data structure itself.

Pending positive feedback from people currently implementing servers and clients I would like to make a PR for this change.

**Comment by cziegenberg** [comment]
I like your idea to wrap the attributes!

I also thought about this way to handle the problem, but decided against suggesting it, because of the additional wrapping elements... but when I see your example, it's much more readable than my suggestion (#569), but offers the same new flexibility: 

The reserved member names don't need to be reserved anymore (for attributes). One could discuss if it is a good practice or not, but I think many API designers would love to get the "type" back. :)

```
{
  "id": "1",
  "type": "book",
  "attributes": {
    "name": "J. R. R. Tolkien",
    "type": "hardcover",
    "date_of_birth": "1892-01-03",
    "date_of_death": "1973-09-02",
    "links": {
      "amazon": "http://www.amazon.com/dp/B0079KT81G/"
    }
  },
  "links": {
    "chapters": {
      "self": "/books/1/links/chapters",
      "related": "/books/1/chapters"
    }
  }
}
```

What I have to add to this suggestion is an additional (optional) top level member "extensions", which enables extensions to add additional data without creating conflicts (as described in #569).

One example:

I thought about an extension to sign requests and responses, therefore I would have to add signature information to the document. To avoid conflicts (with attributes, other top level members and other extensions), every extension needs its own namespace. 

So I would suggest to wrap them like in the following example (example name of the extension is "signature"):

```
{
  "id": "1",
  "type": "book",
  "attributes": {
    "name": "J. R. R. Tolkien",
    "type": "hardcover",
    "date_of_birth": "1892-01-03",
    "date_of_death": "1973-09-02",
    "links": {
      "amazon": "http://www.amazon.com/dp/B0079KT81G/"
    }
  },
  "links": {
    "chapters": {
      "self": "/books/1/links/chapters",
      "related": "/books/1/chapters"
    }
  }
  "extensions": {
    "signature": {
      "value": "...",
      "algorithm" : "...",
      "canonicalization": "...",
      "key": "..."
    }
  }
}
```

What do you think?

**Comment by tkellen** [comment]
I think the notion of an extension member seems interesting, but that discussion around it should happen in a separate thread. Would you mind opening another issue? Also, if you feel comfortable that this would resolve #569, could you please close that issue?

**Comment by cziegenberg** [comment]
Closed the old one and opened a new one for the "extensions" member.

**Comment by ethanresnick** [comment]
@tkellen I'm definitely +1 on this, but I'm guessing that this change will be pretty hard to sell so close to 1.0. If it can happen though, let's make it happen :)

**Comment by jakubrohleder** [comment]
+1. This is quite an importatant and valuable idea. Especially having in mind, that by default Ruby on Rails (and others?) uses 'type' column for [Single Table Inheritance](http://en.wikipedia.org/wiki/Single_Table_Inheritance).

**Comment by lgebhardt** [comment]
:+1: from me as well. It brings a nice consistency to the spec, in addition to removing the restrictions on attribute names.

**Comment by hhware** [comment]
I agree with others that this proposal makes object format cleaner. It will make more sense when (I bet it is "when" and not "if") more resource-level attributes are added (https://github.com/json-api/json-api/issues/575#issuecomment-96447358, perhaps?)

Interestingly, the proposed approach would help to resolve the issue which I unsuccessfully tried to raise in #361. It places JSON API resource ID to a different level than attributes, hence it would allow to map ID to different attributes. E.g., in the examples below, JSON API resource ID is mapped to something omitted (possibly `id`) for comments and to `username` for users:

```
{
  "data": {
    "id": "123",
    "type": "comments",
    "attributes": {
      "text": "abc"
    }
  }
}
```

```
{
  "data": {
    "id": "jsmith",
    "type": "users",
    "attributes": {
      "username": "jsmith",
      "first_name": "john",
      "last_name": "smith"
    }
  }
}
```

Would it make sense for the spec to elaborate on possibility of such mapping, perhaps in non-normative notes? 

Further, would it make sense to explicitly state spec's position towards `attributes.id` (I assume, indifferent)? In the example above, even if `id` is present in the DB table containing users, the purpose of using `username` as ID at API level is to completely hide surrogate key on API level in favor of meaningful but still unique natural key.

Also, would not it make sense to shorten the key name to `attrs`, `atrs`, something else short? Full English words are nice, but, e.g., `id` is an abbreviation, so it will not be a precedent. Given that paths will have to include it (e.g., `fields[TYPE]=attributes.name`), it would slightly decrease level of verbosity.

**Comment by tkellen** [comment]
@hhware I'm pretty indifferent on the naming. It wouldn't actually be required to prefix the container for fields--it's already stated normatively in the spec that fields controls the visibility of attributes (which will now be much easier to follow).

Given the positive response to this, I'm going to open a PR for this tomorrow. We can bikeshed the property name a bit there, if need be!

**Comment by hhware** [comment]
> It wouldn't actually be required to prefix the container for fields

Right!

**Comment by ethanresnick** [comment]
@maxdumas curious to get your take on this too, seeing as you'd have to update our client implementations (and the BC break is the most obvious downside)

**Comment by maxdumas** [comment]
@ethanresnick I am all for this as it would definitely give us some more freedom in how we define our data, and any changes to parsing on my end would be pretty trivial. My one concern is that 'attributes' is definitely a bit verbose. 'attrs' is a pretty standard abbreviation of that which I would prefer.

**Comment by ethanresnick** [comment]
@maxdumas Good to hear! Yay for more consensus.

Re the property name: personally, I'm in favor of `"attributes"` because it aligns better with the text of the specification. That makes understanding the spec easier, which is a win for adoption. Plus, a good client will only have to write this key in one or two places anyway, and gzipping will make the data size difference largely irrelevant. That said, from a broader perspective, I agree with @tkellen that the key really doesn't matter much and we shouldn't spend too much time bikeshedding it.

**Comment by ksimka** [comment]
:+1: cause we're doing that nasty thing with underscore prefixing for "system" fields in order to avoid conflicts. This proposal looks native like it's supposed to be here since the very beginning :)
