### ISSUE TITLE
409 error response doesn't fully comply with RFC 7231

### ISSUE THREAD

**Issue by cziegenberg** [json-api/json-api#576]
Following RFC 7231 for the HTTP/1.1 protocol the server "SHOULD generate a payload that includes enough information for a user to recognize the source of the conflict" when sending a 409 status code:
https://tools.ietf.org/html/rfc7231#section-6.5.8

The spec instead says that error details only "MAY" be returned (and only for "Other Responses"). 

So I suggest to add the following sentence to the 409 errors (appears two times):

_"A server SHOULD include error details and provide enough information to recognize the source of the conflict."_

**Comment by hhware** [comment]
Totally makes sense to me!

**Comment by cziegenberg** [comment]
Created PR  #596.
