### ISSUE TITLE
sort[data]

### ISSUE THREAD

**Issue by hhware** [json-api/json-api#577]
I would like to suggest to replace `sort` keyword with `sort[data]`. It will 
- explicitly indicate what the client expects to be sorted (same approach as with `fields[TYPE]`),
- clean the road for implementations/extensions, which want to return something else in sorted form (e.g., [linkage object arrays](https://github.com/hhware/json-api/commit/7aca0007af619786b95993175e236e6b525c9a9a#diff-26e38355b69056b0db1c2b1c612241b2R923)).

I would like to ask to consider this for 1.0.

**Comment by dgeb** [comment]
I understand the intent, but find `sort[data]` to be awkward. It is just similar enough to `fields[TYPE]` to be misleading in that `data` could be confused with a type.

An alternative would be for an extension to use a different query param for different types of sorting.

**Comment by dgeb** [comment]
I'm still :-1: on this. If anyone wants to speak in support, now is the time.

**Comment by tkellen** [comment]
I agree that we may someday wish to sort things other than resource collections, but I also agree with @dgeb that we shouldn't complicate the most common case to support something we don't yet have a need for. I'm going to close this in favor of considering another query param in the future.
