### ISSUE TITLE
Resource identification by combination of its type and id members - in what scope?

### ISSUE THREAD

**Issue by mBread** [json-api/json-api#578]
The section [Resource Identification](http://jsonapi.org/format/#document-structure-resource-identification) says "Every JSON API resource object is uniquely identified by a combination of its type and id members." but doesn't say what scope this applies to. Obviously, that cannot be true globally unless there is a registry of "type" values.

I expect the common inference is that it is "per API", but that is not said explicitly, and that concept is not present in the spec (at least not up to this point). Also, there do not appear to be any restrictions preventing one API (one implementation) from including links to another API (another implementation) - so just by following links you may find another resource with the same type and ID.

Later on [Compound Documents](http://jsonapi.org/format/#document-structure-compound-documents) says : "Note: In a single document, you can think of the type and id as a composite key that uniquely references resource objects in another part of the document." Is that what was meant in "Resource Identification" or not?

**Comment by bintoro** [comment]
> I expect the common inference is that it is "per API"

Yes, this is the intent.

> there do not appear to be any restrictions preventing one API (one implementation) from including links to another API (another implementation)

As I understand it, this is not supposed to happen — at least not via the standard linkage mechanism.

**Comment by tkellen** [comment]
Resolved in #676
