### ISSUE TITLE
Better job of tracking changes

### ISSUE THREAD

**Issue by immunda** [json-api/json-api#581]
First of all, I'm really happy with the direction the project is going, recent changes have addressed a bunch of quandaries I've had.

That said, these changes are somewhat contrary to the status page (http://jsonapi.org/status/) which implies that the spec is largely unlikely to change. This means from late last year I now have endpoints which don't match the current documentation, and there's no way to retrieve a historic documentation easily, as there doesn't seem to be any versioning in place.

Now that the project seems to be picking up pace again, it'd be great to start to see versioned releases, with a changelog, and versioned, hosted, documentation to match.

Thank you and keep up the great work!

**Comment by steveklabnik** [comment]
We're putting out a 1.0 on May 21, which is when we'll be doing such things, since we start actually having guarantees.

**Comment by immunda** [comment]
Boom, look forward to it.
