### ISSUE TITLE
Add naming recommendations to format

### ISSUE THREAD

**Issue by jonkoops** [json-api/json-api#583]
The naming recommendations for resource types, attribute names, and association names to be dashterized isn't part of the format. I think the specification should have a clear opinion on how to format these attributes in order to [prevent confusion](https://github.com/eneuhauser/ember-json-api/issues/8) and possible frustration amongst implementors.

This is what the recommendations page has to say:

> ## Recommendations for Naming
> 
> It is recommended that resource types, attribute names, and association names be "dasherized"; i.e. consist of only lower case alphanumeric characters and dashes (U+002D HYPHEN-MINUS, "-").
> 
> It is also recommended that resource types be pluralized. Dasherized and pluralized resource types can be used as URL segments without translation, as discussed below.

Source: http://jsonapi.org/recommendations/#naming

**Comment by cziegenberg** [comment]
#567 is an open issue about the allowed characters (ASCII, UNICODE, upper/lower case and special ASCII characters). There you'll find some new rules and recommendations to avoid problems with clients.

The current result of the discussion is, that members are case-sensitive and that it's the decision of the API if upper-/lower-case characters or which separator characters are used.

**Comment by jonkoops** [comment]
I see no good reason not to specify a separator character in the specification, it will only complicate implementations if we're not specific about it. A client now needs to be configured per API to know how to serialize & deserialize entities. I personally think enforcing a pre-defined separator is the way to go to give the user convention over configuration.

**Comment by cziegenberg** [comment]
There are different views on that point... Would you close this issue in favor of taking part in the existing discussion?

**Comment by jonkoops** [comment]
@ziege Will do.
