### ISSUE TITLE
POST array when creating?

### ISSUE THREAD

**Issue by chrishunt** [json-api/json-api#59]
When we GET a resource, we always want an array. Should we do the same for POST?

Take the first example from `write.md`:

``` text
POST /photos
Content-Type: application/json
Accept: application/json

{
  "photos": {
    "title": "Ember Hamster",
    "src": "http://example.com/images/productivity.png"
  }
}
```

The plural key `photos` doesn't make sense here unless we pass an array. It would make sense to either change the key to `photo`, or even better and easier, just require that we POST an array:

``` text
POST /photos
Content-Type: application/json
Accept: application/json

{
  "photos": [{
    "title": "Ember Hamster",
    "src": "http://example.com/images/productivity.png"
  }]
}
```

This also allows us to create multiple photos in one request if we wanted to:

``` text
POST /photos
Content-Type: application/json
Accept: application/json

{
  "photos": [{
    "title": "Ember Hamster",
    "src": "http://example.com/images/productivity.png"
  },{
    "title": "Angular A Badge",
    "src": "http://example.com/images/boring.png"
  }]
}
```

What are your thoughts?

**Comment by steveklabnik** [comment]
WDYT @wycats?

**Comment by lukfugl** [comment]
I think this makes sense. Both on the `POST` side and `PUT`. With a `POST` it makes sense to be able to submit a batch of documents to create (though allowing such will require some modifications to the **MUST** language around the `Location` header in PR https://github.com/json-api/json-api/pull/62). With a `PUT`, it's desirable that the representation sent match the expected representation returned from a `GET`, so having it use arrays symmetrically seems sound.
