### ISSUE TITLE
202 Accepted

### ISSUE THREAD

**Issue by adamesque** [json-api/json-api#595]
This may be beyond the scope of JSON API 1.0, but has anyone discussed relaxing some of the MUSTs for responses to successful CRUD requests to allow `202 Accepted`?

This would allow an API with an inherently asynchronous or time-consuming endpoint to respond with a 202 and a Location header pointing to an intermediate resource that could then be polled for status updates.

**Comment by tkellen** [comment]
Yup! It's here: https://github.com/json-api/json-api/issues/534. I'm going to close this as a duplicate, but if you'd be willing to open a PR for the specific area you want to address, that'd be fantastic!

**Comment by adamesque** [comment]
Ah! Serves me right for only searching "202" without the "Accepted". Sounds like the general desire is not to special-case statuses that are already HTTP-compliant, so I'll be happy with whatever resolution is reached in #534.

That said, if we end up building out this async pattern with any success, we might be able extract some recommendations that could go into an extension.

Thanks!
