### ISSUE TITLE
dot-separated relationship paths could conflict with handlebars

### ISSUE THREAD

**Issue by tkellen** [json-api/json-api#599]
There is nothing normative in the spec stating that nested relationships **MUST** be represented by a dot separated path, so I could resolve this issue within endpoints by using `__` (precedent from ruby sequel and django). That being said, with handlebars and ember-data slated to be big consumers of JSON-API, perhaps these examples should change?

**Comment by ethanresnick** [comment]
Can you explain this a bit more? Where are the paths causing a conflict? And how, if at all, does this tie in to the spec saying that:

> A relationship path is a dot-separated (U+002E FULL-STOP, ".") list of relationship names.

(Maybe this all goes back to #497?)

**Comment by tkellen** [comment]
Closing. We're going to be revisiting this next week in another issue (you're right that it drives back to #497).
