### ISSUE TITLE
Update to mention the correct content-type

### ISSUE THREAD

**Issue by steveklabnik** [json-api/json-api#6]
The IANA is currently reviewing my application for `application/vnd.api+json`. After this has been registered, we will need to update the docs.

**Comment by wycats** [comment]
I think we should explicitly allow `application/json` as well, because of the prevalence of libraries that support that format, but I realize I may be stepping on a land-mine here. @steveklabnik?

**Comment by steveklabnik** [comment]
It's a FAQ question. Because of the `+`, the type name means 'anything which can parse `application/json` can also parse this.'

**Comment by paddycarver** [comment]
Possibly a crazy question, but is it worthwhile to examine API versioning through Accept headers, and how this would interact with that? I know it's a popular way to version APIs.

**Comment by steveklabnik** [comment]
Versioning through accept headers is an anti-pattern. We won't be supporting it.

**Comment by paddycarver** [comment]
Well, that was an easy discussion. :+1:

**Comment by steveklabnik** [comment]
:)

(technically, it can probably be backdoored anyway, since I doubt (when this becomes an RFC) that I will want to restrict parameters to the type, and so someone could introduce a 'version' parameter. But that's outside of this spec anyway.)

**Comment by paddycarver** [comment]
SGTM.

**Comment by steveklabnik** [comment]
This has been added. It's not fully registered yet, but says that.
