### ISSUE TITLE
Defining Future Query Parameters

### ISSUE THREAD

**Issue by ethanresnick** [json-api/json-api#602]
If the spec wants to assign special semantics to additional query parameters down the line, that will be impossible if JSON-API APIs are already using these parameters in different ways. Therefore, I propose either:
1. Adding a list of query parameters to the spec that compliant APIs can’t use in their urls. Off the top of my head, that list—which I figure we should make pretty greedy—might include: `embed`, `match`, `version`, `search`, `action`, `links`, `signature`, `access`, `docs`,`profile`, `profiles` … anything else?
2. <a name="prefix-option"></a> Or, an alternate solution would be to have the user prefix any of _their_ query parameters (i.e. any they’re using that aren’t defined by the spec). This has a couple things going for it:
   1. We can add any query parameter we want down the line, as long as it doesn’t start with the prefix character (which is fine, since we want to avoid prefixing spec keywords anyway)
   2. It makes visible in the url which query parameters are standard and which are non-standard.
   
   But maybe a downside is it makes the URLs of compliant APIs somewhat uglier (since the user parameters are prefixed)?

Thoughts?

(As an aside: Extensibility questions like the above are what I was trying to raise, with @hhware, in #588. But I think our discussion was somewhat off topic there and perhaps unappreciated, so I apologize. Hopefully now we can discuss extensibility in proper, separate issues. I think this question of how to prepare the spec for the future is important, and while it’s something that the spec authors (@dgeb, @tkellen, @steveklabnik et al) may have discussed in private, it hasn’t basn’t been discussed explicitly on github much.)

**Comment by ethanresnick** [comment]
@tkellen @dgeb @steveklabnik no thoughts on this?

**Comment by tkellen** [comment]
Just a heads up: I flagged this for review before Thursday.

**Comment by dgeb** [comment]
Well, I'm certainly opposed to reserving an arbitrary list of params. We're sure to frustrate many API implementers by reserving params that they want to use. Furthermore, we'll misjudge future requirements and everything will be for naught.

**Comment by csantero** [comment]
Would a third possible solution be to flip point 2 around and prefix all JSON API query parameters?Anything else could then safely belong to the user.

**Comment by dgeb** [comment]
I suggest that we require that all custom query parameters contain a dash in their name, similar to custom element naming in the web components spec.

**Comment by tkellen** [comment]
I'm :+1: to custom query params having a dash.

**Comment by ethanresnick** [comment]
Ok, so the reserved words idea's gone. 

I want to think about this issue more in the context of #614 and #603 to see if we can't unify them all, but, tentatively, I'd prefer a prefix character for user parameter names over a dash because:
1. I think it's actually a real _virtue_ if parameters custom-defined by an API are visually delineated from base-spec-defined ones. That clearly communicates to users of the API which things they should look up in the API's documentation and which things they should look up in the JSON-API spec. And I think a prefix character is a stronger visual indicator than a dash.
2. The primary advantage of a dash, I suppose, is that it's more aesthetically pleasing. But that advantage only holds if the user's used dasherized names. If they've used camel case names, then our forcing them to dasherize their parameter names looks really weird. So, with this dash rule we'd be encroaching a bit more onto the ability of users to adopt their preferred naming style; before we were just recommending dasherized names, but now we're requiring it in these limited cases. Maybe that doesn't matter, but I don't know...people are pretty touchy about these things.

**Comment by ethanresnick** [comment]
To make my comment more specific above, I'm now in favor of a prefixing approach not only because it offers stronger visual delineation than dashes and a weaker intrusion on the user's naming scheme, but also because, if we merge a version of #650 eventually, using prefixes here would let us have a unified approach to delineating user- and spec-defined names throughout. This is because #650 requires prefixed parameters for "profile extensions", in order to allow JSON-LD to be defined as a profile extension. 

More particularly, I'm in favor of requiring that the parameters be prefixed by either an at-sign or an underscore. The "@" was chosen to allow compatibility with JSON-LD; the underscore because it's a de-facto standard for private properties and is URI safe. (Edit: also, "@" is url safe _in query strings_, which is nice.) And I suggest only allowing two characters as prefixes so we can continue to reserve as many characters as possible from @ziege's member names "reserved characters" list.

(In case people are interested, the text for the approach outlined above is already written, as part of my PR for #650.)

**Comment by ethanresnick** [comment]
Hey all, I just wanted to share a [bit of history](http://tools.ietf.org/html/rfc6648) that could inform our decisions here. I haven't digested that document fully yet, but it's worth taking into consideration and might change my view on prefixing.

**Comment by cziegenberg** [comment]
Intersting document... In the recommendations part there is a note, that parameters could still be prefixed with e.g. a company name (or extension name here) for namespacing.

Related to this I thought about extension attributes and came to result that prefixing is better than wrapping them in a special extension container, because of other suggestions like the immutable/read-only which shoulb be able to extend ALL attributes (including attributes by other extensions) with additional information.

Back to the query parameters:

I think that prefixing all extension information (query params, attributes,...) with the extension name (and separated by a hyphen minus) would generally a good way to handle this.
