### ISSUE TITLE
Error Object Extensibility

### ISSUE THREAD

**Issue by ethanresnick** [json-api/json-api#604]
Right now, every spec-defined object is declared as not allowing extra members (unless an extension is in use), except for errors objects, which say that the user MAY add extra members. Is there a reason for this exception? It seems like the rationale for preventing users from adding members to other objects (namely, to preserve base spec extensibility), applies just as much to errors, no? We’ve already seen [one instance](https://github.com/json-api/json-api/issues/584) of someone wanting to add another property to the errors object, so our wanting to extend this object in the future doesn’t seem impossible…

My suggestion would be to keep error objects non-extensible, just like everything else.

(For reference, btw, when I say that all other spec-defined objects are declared as inextensible, I’m referencing this clause: “Unless otherwise noted, objects defined by this specification MUST NOT contain any additional members. Client and server implementations MUST ignore object members not recognized by this specification.”)

**Comment by ethanresnick** [comment]
@dgeb @tkellen thoughts on this?

**Comment by tkellen** [comment]
Agreed! Would you mind opening a PR to make this change?

**Comment by ethanresnick** [comment]
@tkellen [Done](https://github.com/json-api/json-api/pull/610)!

**Comment by tkellen** [comment]
Cool! I will review this with @dgeb in the AM.

**Comment by ethanresnick** [comment]
This can be closed now too! :)
