### ISSUE TITLE
Proposal: Attributes and "Protected" Attributes

### ISSUE THREAD

**Issue by pixelhandler** [json-api/json-api#611]
One thing I often deal with is… attributes of a resource that are protected; consideration must be made whether or not to include the attribute of the resource for a given user. The use case below is super simple but illustrates the options of whom to show a protected attribute to.

_Resource: A Comment with attributes: body:string & approved:boolean (default: false)_
- Visitor: only sees Comments that are approved but never sees the 'approved' attribute in the resource
- Commenter: only sees the 'approved' attribute for Comments owned by the Commenter (never sees the 'approved' attribute for Comments owned by other Commenters
- Moderator: Sees the approved attribute for any Comment in the system

Now that the JSON representation of a resource has the optional **"attributes"** node (which includes the attrs of the resource) I started thinking about an (optional) "protected-attributes" node (sibling to "attributes") This "protected-attributes" object may contain any attributes that are not guaranteed to be included in the resource; however if the scenario is fitting for the response to include any protected attribute(s), then the resource may include those attribute(s) in the **"protected-attributes"** object.

In the following resource example the "approved" attribute may or may not be presented, depending on the scenario of the request…

``` javascript
{
  "data": {
    "id": "1",
    "type": "comments",
    "attributes": {
      "body": "Ah this is sweet"
      "protected": {
        "approved": false
      }
    }
  }
}
```

``` javascript
{
  "data": {
    "id": "1",
    "type": "comments",
    "attributes": {
      "body": "Ah this is sweet"
    }
  }
}
```

``` javascript
{
  "data": {
    "id": "1",
    "type": "comments",
    "attributes": {
      "body": "Ah this is sweet"
      "approved": false
    }
  }
}
```

However this seems like a better (more standard) representation for "Protected" attributes:

``` javascript
{
  "data": {
    "id": "1",
    "type": "comments",
    "attributes": {
      "body": "Ah this is sweet"
    },
    "protected-attributes": {
      "approved": false
    }
  }
}
```

**For example, consider a blog comment that needs moderation:**

A Commenter may see a JSON response which includes a comment the Commenter owns. A Moderator would see the same response:

``` javascript
{
  "data": {
    "id": "1",
    "type": "comments",
    "attributes": {
      "body": "Ah this is sweet"
    },
    "protected-attributes": {
      "approved": false
    },
    "links": {
      "self": "http://localhost:3000/api/v1/comments/1",
      "commenter": {
        "self": "http://localhost:3000/api/v1/comments/1/links/commenter",
        "related": "http://localhost:3000/api/v1/comments/1/commenter",
        "linkage": {
          "type": "commenters",
          "id": "1"
        }
      },
      "post": {
        "self": "http://localhost:3000/api/v1/comments/1/links/post",
        "related": "http://localhost:3000/api/v1/comments/1/post",
        "linkage": {
          "type": "posts",
          "id": "1"
        }
      }
    }
  },
  "included": [
    {
      "id": "1",
      "type": "commenters",
      "attributes": {
        "name": "Bill Heaton"
      },
      "links": {
        "self": "http://localhost:3000/api/v1/commenters/1",
        "comments": {
          "self": "http://localhost:3000/api/v1/commenters/1/links/comments",
          "related": "http://localhost:3000/api/v1/commenters/1/comments"
        }
      }
    }
  ]
}
```

Another Commenter viewing a Comment owned by someone else:

``` javascript
{
  "data": {
    "id": "2",
    "type": "comments",
    "attributes": {
      "body": "Well now, how about that!",
    },
    "protected-attributes": {},
    "links": {
      "self": "http://localhost:3000/api/v1/comments/2",
      "commenter": {
        "self": "http://localhost:3000/api/v1/comments/2/links/commenter",
        "related": "http://localhost:3000/api/v1/comments/2/commenter",
        "linkage": {
          "type": "commenters",
          "id": "2"
        }
      },
      "post": {
        "self": "http://localhost:3000/api/v1/comments/1/links/post",
        "related": "http://localhost:3000/api/v1/comments/1/post",
        "linkage": {
          "type": "posts",
          "id": "1"
        }
      }
    }
  },
  "included": [
    {
      "id": "2",
      "type": "commenters",
      "attributes": {
        "name": "Nobody Special"
      },
      "links": {
        "self": "http://localhost:3000/api/v1/commenters/2",
        "comments": {
          "self": "http://localhost:3000/api/v1/commenters/2/links/comments",
          "related": "http://localhost:3000/api/v1/commenters/2/comments"
        }
      }
    }
  ]
}
```

And a Visitor may not even be aware of any protected attributes

``` javascript
{
  "data": {
    "id": "5",
    "type": "comments",
    "attributes": {
      "body": "yeah another one, I know"
    },
    "links": {
      "self": "http://localhost:3000/api/v1/comments/5",
      "commenter": {
        "self": "http://localhost:3000/api/v1/comments/5/links/commenter",
        "related": "http://localhost:3000/api/v1/comments/5/commenter",
        "linkage": {
          "type": "commenters",
          "id": "2"
        }
      },
      "post": {
        "self": "http://localhost:3000/api/v1/comments/5/links/post",
        "related": "http://localhost:3000/api/v1/comments/5/post",
        "linkage": {
          "type": "posts",
          "id": "2"
        }
      }
    }
  }
}
```

**Comment by pixelhandler** [comment]
@dgeb here is an example implementation of the protected attributes hash in a resource (using jsonapi-resources gem) https://github.com/pixelhandler/blog-api/commit/471e2a6c1df96a70db9c8e6db23b037ab405780a

**Comment by ethanresnick** [comment]
Is there any reason this is better than simply not including the attributes in responses to users that don't have the rights to see them?

**Comment by pixelhandler** [comment]
@ethanresnick simply not including the attributes in responses that users don't have rights to, in my opinion results in different representations of a resource for different people. It bothers me to present the attribute of a resource to a user and not let them know that there are some attributes that are not guaranteed to be presented, nor to provide a sense that the attributes that they see include some attributes that are protected and will not be seen by other users. By using a "protected-attribute" object in the response, the resource that is represented within the **"attributes" object is common, known and expected**. API developers can send null for empty attrs; and there is no question of… is the attribute missing because the user does not have the rights? Or, is the attribute simply empty, so its not included. Also, by presenting "protected-attributes" in a separate section of the payload the response communicates that the **"protected-attributes" are not common, nor guaranteed to be included in the resource**. I also think that it may be a good idea for privileged attributes to be represented as so, it's self documenting. Both groups of attributes and protected-attributes can be combined, if the client application chooses to (or not).

**Comment by cziegenberg** [comment]
@pixelhandler Perhaps this could be solved with a combination of NULL values and `readonly`, discussed in #575 and PR #589.

**Comment by pixelhandler** [comment]
@ziege @ethanresnick @dgeb I think the "meta" section of the response would be sufficient for naming the types of attributes that are "read-only" or "protected". For example:

``` javascript
{
  "id": "1",
  "type": "person",
  "attributes": {
    "firstname": "Justin",
    "lastname": "Timberlake",
    "signature": "http://commons.wikimedia.org/wiki/File:Justin_Timberlake_signature.svg",
    "date-of-birth": "1981-01-31",
    "age": 34,
    "fullname": "Justin Timberlake"
  },
  "meta": {
    "attributes": {
      "read-only": ["age", "fullname"],
      "protected": ["date-of-birth"]
    }
  }
}
```

**Comment by ethanresnick** [comment]
@pixelhandler Yup, that's exactly what I was going to say!

Because relationships can be protected too, which leads you down the route of having a list of protected paths (rather than a container object), and then that list can probably live under `"meta"`, since the base spec can't address every case.

**Comment by pixelhandler** [comment]
@ziege @ethanresnick @dgeb I'm closing this issue (proposal), I think this helped me to decided how I'd like to represent meta info about attributes, such as 'read-only' or 'protected'.

``` javascript
{
  "data": {
    "id": "1",
    "type": "comments",
    "attributes": {
      "body": "Ah this is sweet"
      "protected": {
        "approved": false
      }
    }
  },
  "meta": {
    "attributes": {
      "protected": {
        "approved": false
      }
    }
  }
}
```

``` javascript
{
  "data": [
    {
      "id": "1",
      "type": "comments",
      "attributes": {
        "body": "Ah this is sweet…",
        "approved": true
      },
      "links": {
        "self": "http://example.com/comments/1",
        "commenter": {
          "self": "http://example.com/comments/1/links/commenter",
          "related": "http://example.com/comments/1/commenter",
          "linkage": {
            "type": "commenters",
            "id": "9"
          }
        }
      }
    },
    {
      "id": "2",
      "type": "comments",
      "attributes": {
        "body": "Well, on second thought…",
        "approved": false
      },
      "links": {
        "self": "http://example.com/comments/2",
        "commenter": {
          "self": "http://example.com/comments/2/links/commenter",
          "related": "http://example.com/comments/2/commenter",
          "linkage": {
            "type": "commenters",
            "id": "9"
          }
        }
      }
    }
  ],
  "included": [
    {
      "type": "commenters",
      "id": "9",
      "attributes": {
        "name": "Bill Heaton"
      },
      "links": {
        "self": "http://example.com/commenters/9"
      }
    }
  ],
  "meta": {
    "comments": {
      "attributes": {
        "protected": [
          "approved"
        ]
      }
    }
  }
}
```
