### ISSUE TITLE
Attributes Object Requirement 

### ISSUE THREAD

**Issue by bobholt** [json-api/json-api#612]
I can't find any normative reference that says all resource attributes **MUST** be within the attributes object or that resource attributes **MUST NOT** be present in the top-level data object, but it seems,  based on a brief email exchange with @tkellen that this should be the case. 

Based on my reading of the current spec, I might implicitly interpret that the `attributes` object is an optional suggestion and continue to put my attributes in the top-level data object.

**Comment by hhware** [comment]
The spec defines only 5 members of resource objects and then says:

> Unless otherwise noted, objects defined by this specification MUST NOT contain any additional members.

Is there a weak point in this logic?

**Comment by tkellen** [comment]
I'm gonna close this as resolved for now. @bobholt I'd love a PR with further clarification where you think it belongs, if you have the bandwidth to offer one.
