### ISSUE TITLE
Extended operations

### ISSUE THREAD

**Issue by willemdewit** [json-api/json-api#615]
We are using JSONAPI for a number of use cases, and in general things work great.
We are using it for a "survey"-like application to conduct questionaires.

We have a use case where we want to use JSONAPI to pull “next question” from a complex questionnaire. The app talking to our server through JSONAPI would like a single operation to get next question, but in the same operation, also save the answer for the previous question.
This in order for them to have one less roundtrip.

I'm working on another REST API in parallel based on [FHIR](http://hl7.org/fhir/2015May/), which added a concept of [Extended Operations](http://hl7.org/fhir/2015May/operations.html) to do something like this.

What is the preferred way of solving the "extra roundtrip" issue. And should JSON API specify Extended Operations also?

**Comment by hhware** [comment]
@willemdewit, IMHO, nothing prevents the server from adding the next question into `included` of the response of the operation which saves the previous question. Would that solve the problem?

**Comment by tkellen** [comment]
I agree with @hhware's assessment of how to resolve this issue. If you're still having trouble, http://discuss.jsonapi.org would be a great place to talk this out!
