### ISSUE TITLE
Consider compatibility with http-api-design from heroku?

### ISSUE THREAD

**Issue by ms-ati** [json-api/json-api#617]
Hi jsonapi folks,
1.  To what extent will JSON API 1.0 be compatible with [Heroku's HTTP API Design Guide](https://github.com/interagent/http-api-design)?
2.  To what extent can these two projects be made to be compatible or complementary in the future?

**Comment by dgeb** [comment]
JSON API 1.0 is coming in a few days. After this point, changes will only be additive in nature. If you'd like us to consider any particular aspect of Heroku's design guide, please open a very targeted issue for discussion ASAP.
