### ISSUE TITLE
Recommendations for filtering on partial value matches

### ISSUE THREAD

**Issue by scottgonzalez** [json-api/json-api#620]
The [recommendations for filtering](http://jsonapi.org/recommendations/#filtering) section should include a recommendation for partial value matching. For example a request to `/foo?filter[bar]=baz` which uses a database query similar to `SELECT * FROM foo WHERE bar LIKE "%baz%"`.

**Comment by tkellen** [comment]
We've intentionally left the filtering section unspecified. It is our (current) feeling that there are far too many possible filtering scenarios to be prescriptive about how servers implement them.

**Comment by tkellen** [comment]
If @dgeb, @ethanresnick or @steveklabnik feel this is needed, I'd be happy to field a PR with a recommendation for this. Can ya'll chime in here please?

**Comment by steveklabnik** [comment]
I will be doing a JSONAPI based API that does this, so I'm certainly interested in a sense. Hrm.

**Comment by ethanresnick** [comment]
I'm not opposed per se to having a rec about this.  I'm a little worried that it'll take a disproportionate amount of time to get the rec right for the value it offers...but the nice thing about a recommendation is that we can always change it as we learn more. So if we can aggregate even a bit of data on what's worked well for people thus far, I don't think there's much harm in publishing that as a tentative recommendation

**Comment by tkellen** [comment]
FWIW, I am not being opinionated about this with endpoints--implementors can do whatever they want with a filter param, e.g:
https://github.com/endpoints/endpoints-example/blob/master/src/modules/books/model.js#L39-L44

I think this is the tip of a very large iceberg. If we have a recommended convention for partial string matching does it match from the head of the string? The tail? Any substring? Fuzzy? Why not also provide a recommendation for greater than and less than? How about greater than or equal to and less than or equal to? How about a recommendation for ranges? Did you mean inclusive ranges or exclusive ranges? What about arrays of param values? Add all the previous questions to multi-element filters and compound it with more questions like, is a match valid if only one element fits the criteria, or do they all need to match?

I hope that I'm not seeming overly negative, I'm just very hesitant to take responsibility for the multitude of filtering use cases out there. I'm open to the possibility that this is exactly what JSON-API is meant to do, but I think we need to take all of the questions I just raised into account if we do.

I know that nobody on the core team has time to dedicate to this issue at present. @scottgonzalez, are you willing to open a PR and champion this through the inevitable bike-shedding that will result? If yes, we can land this any time during our release cycle. If no, would you mind closing this?
