### ISSUE TITLE
Standard Incompatible with IE8

### ISSUE THREAD

**Issue by ben-crowhurst** [json-api/json-api#621]
HTTP PATCH Method not supported :(

http://bugs.jquery.com/ticket/13240

**Comment by tanmayambre** [comment]
+1

**Comment by steveklabnik** [comment]
While I'm sympathetic to browser support, our primary audience isn't browsers, it's other API clients.

We can't _not_ use PATCH here, as it's the correct HTTP verb.

**Comment by ben-crowhurst** [comment]
May the standard host a section stating HTTP PUT is ok as long as its a complete resource document?

**Comment by ziyualexanderwang** [comment]
+1

**Comment by gogs2020** [comment]
+1

**Comment by juniorhamish** [comment]
+1

**Comment by gr0uch** [comment]
Seems like a popular request. For browsers that don't support PATCH, they should be able to send custom headers, such as `X-Request-Method` to bypass the method problem.

I disagree that the primary audience isn't browsers, considering that Ember Data is a major consumer. I agree that it should use PATCH though.

**Comment by shotsyjr** [comment]
+1

**Comment by steveklabnik** [comment]
I certainly don't want to talk down the Ember Data case, it _is_ very important! I just mean correctness comes first, then possible hacks for compatibility.

**Comment by hhware** [comment]
> May the standard host a section stating HTTP PUT is ok as long as its a complete resource document?

@ben-crowhurst, `PUT` is OK for anything, see http://jsonapi.org/faq/#wheres-put

**Comment by ChrisDavison** [comment]
+1

**Comment by dgeb** [comment]
I don't think we need anything normative in the spec to allow for this. This seems like a perfect candidate for an extension, which would allow servers to eventually phase out support.

**Comment by ethanresnick** [comment]
I'm +1 on @dgeb's and @steveklabnik's sentiment that we shouldn't spend too much effort worrying about this, as we're doing the correct thing and the problem will solve itself as IE8 fades out over time. That said, a recommendation for how to solve this (if there's a simple way) could be a really big win for the spec adoption at relatively little cost. 

For example, what if we recommended that clients wanting to do updates over PUT use the [`X-HTTP-Method`](https://msdn.microsoft.com/en-us/library/dd541471.aspx) header with their requests to instruct the server to treat the PUT as a PATCH, and we could recommend that server's support this header on PUT endpoints. Again, it'd just be a recommendation (no base spec changes) but could help adoption considerably.

**Comment by mandalae** [comment]
+1
