### ISSUE TITLE
More `include`-related vaguery

### ISSUE THREAD

**Issue by ethanresnick** [json-api/json-api#624]
This issue may be dependent on the resolution to #497, but is distinct from it. The issue is the following line:

> If a link object refers to resource objects included in the same compound document, it **MUST** include resource linkage to those resource objects.

Imagine that the resource at `/companies/abc` has two relationships: `"owner"` and "`ceo"`, and that these relationships point to the same person resource. I'm concerned that, as written, the line above would require that, on a request for `/companies/abc?include=owner` would require that the link object for the _`"ceo"` relationship_ include linkage, not just a `"related"` or `"self"` url. That seems like an unintended consequence that the language should be clarified to remove.

**Comment by tkellen** [comment]
I see what you mean. This seems like a bit of a reach, but you're technically correct. If there is a way to alleviate this concern without making this clause unnecessarily complex, I'd be +1 to a PR.

**Comment by dgeb** [comment]
Yeah, this has bothered me as well. This definitely needs rewording or removal.

**Comment by dgeb** [comment]
Closed via #637.
