### ISSUE TITLE
Example responses for other requests

### ISSUE THREAD

**Issue by lode** [json-api/json-api#630]
The homepage currently features an example for a collection request. When building other kind of requests I bump into things that are unclear for me. I would love to have some examples on other kinds of requests. They can be simple to start with, but a head start would be lovely.

Main points that are unclear to me right now are:
- resource (i.e. `GET /articles/1`): does it contain a `links.self` and a `data.links.self` which are the same?
- relationships resource (i.e. `GET /articles/1/relationships`): how is it structured? are the relationships given as `links`, `data`, `included` even?

**Comment by dgeb** [comment]
> does it contain a links.self and a data.links.self which are the same?

Neither is required. Both would have the same value in this case.

> relationships resource (i.e. GET /articles/1/relationships): how is it structured?

See http://jsonapi.org/format/#fetching-relationships-responses

**Comment by lode** [comment]
> Neither is required. Both would have the same value in this case.

Ok. And there is no preferred / recommended / best-practice one?

> See http://jsonapi.org/format/#fetching-relationships-responses

As far as I can see that only shows requests like `GET /articles/1/relationships/author`, not the list of relationships from a `GET /articles/1/relationships`.

**Comment by dgeb** [comment]
> Ok. And there is no preferred / recommended / best-practice one?

For simplicity and full hypermedia support, include both. Sometimes they will be identical, such as when targeting a single resource.

> As far as I can see that only shows requests like GET /articles/1/relationships/author, not the list of relationships from a GET /articles/1/relationships.

Sorry - I didn't focus on that URL. There is no concept of a _relationships URL_ in the spec, just individual _relationship URLs_. If you were to implement that endpoint, it would be beyond the scope of the spec. While possible, we don't provide guidance and make no guarantees about compatibility.

**Comment by lode** [comment]
I see. Thanks for the answers.

I think an example single resource response could help others getting started. Do you want to leave this open for that? Or shall I close as my personal questions are resolved?

**Comment by tkellen** [comment]
I sympathize with your concerns @lode. I've been considering a possible solution to this for some time and this issue has prompted me to write it up. I'm going to close this in favor of #639.

Thanks!
