### ISSUE TITLE
Fix typo. Missed a couple of links->relationships

### ISSUE THREAD

**Issue by ndrochak** [json-api/json-api#633]
Completely new to github and can't figure out how to make a pull request for this (I forked and made changes in my fork, but not sure if that is even the right thing...), so just going to post it as an issue...

I think this is a typo when "links" was renamed to "relationships". The change was missed in two places.

-If a relationship is provided in the `links` section of the resource object, its
+If a relationship is provided in the `relationships` section of the resource object, its

This occurs twice in the spec, btw.

HTH,
Nick D

**Comment by steveklabnik** [comment]
@ndrochak let's help you make a pr! If you go on this page: https://github.com/ndrochak/json-api/tree/ndrochak-fix-links

and click the little green button that looks like this:

![2015-05-20-122048_143x132_scrot](https://cloud.githubusercontent.com/assets/27786/7730848/a6966650-feea-11e4-939d-be5f61adcc8b.png)

you'll see 
![2015-05-20-122135_995x351_scrot](https://cloud.githubusercontent.com/assets/27786/7730862/c1c7aa74-feea-11e4-9f77-e808ce05bd30.png)

I'm not sure why it says it can't merge, but maybe do that, click the button to send the PR anyway, and we can go from there?

**Comment by ndrochak** [comment]
OK!  Got it.  Thanks.

**Comment by dgeb** [comment]
As mentioned in #636, this has indeed been fixed in both places where it appeared. Thanks again for reporting this @ndrochak. :+1:
