### ISSUE TITLE
Meta alone as a valid top level member

### ISSUE THREAD

**Issue by lgebhardt** [json-api/json-api#652]
I'd like to allow `meta` to be a valid top level member for all responses. This will allow responses, by way of the top level `meta` member, to return debug, server metrics, and other information for all requests. Currently this is prohibited for deletes and updating relationships (and maybe a few others).

In the cases where 204 No Content is returned I'd propose we allow a 200 OK response as well.

I'd also suggest we change the description of `meta` from "non-standard meta-information about the primary data" to "non-standard meta-information about the primary data or request"

**Comment by tkellen** [comment]
:+1: to a PR implementing this.

**Comment by bintoro** [comment]
Top-level meta items can pertain to anything: primary data, included data, or the response as a whole. So how about just "non-standard meta-information"?

**Comment by lgebhardt** [comment]
:+1: on "non-standard meta-information"

I'll put a PR together.

**Comment by dgeb** [comment]
Closed via #657
