### ISSUE TITLE
Sub navigation requires JavaScript

### ISSUE THREAD

**Issue by cziegenberg** [json-api/json-api#664]
I like the new layout, but I wondered why there isn't a sub navigation on the format page anymore. Also the other pages didn't have a sub navigation. Then I realized that it requires JavaScript, which is disabled in my browser by default and only activated for selected domains.

It would be good to provide a sub navigation that doesn't depend on JavaScript (and scrolls with the page) or at least to show a message, that JavaScript is required.

**Comment by tkellen** [comment]
I'd like to see this too @ziege. Would you please open a PR?
