### ISSUE TITLE
Resolve linkage inconsistencies and concerns

### ISSUE THREAD

**Issue by dgeb** [json-api/json-api#666]
This is a follow up to concerns about inconsistencies in linkage raised in #548, #579, and #637.

The solution that has landed in the spec (via #637) is to require full linkage within compound documents.

This solution removed the ability to exclude intermediate linkage. The previous method of exclusion was to allow multiple paths with the `include` parameter and only include the leaf node. This was fraught with complications to specify and implement because full linkage was not the default in compound documents. Now that this is no longer true, I believe we can restore the ability to exclude intermediate linkage by making exclusion explicit rather than implicit.

At the same time, I'd like to resolve the inconsistency that remains in the spec in which fields MAY be excluded. This prevents full linkage but is not mentioned as an exception anywhere.

A solution to the intermediate linkage issue that @tkellen and I arrived at is to allow a special case of `include` parameters that specify omitted intermediate linkages. By placing a reserved character, such as `-`, before a segment of a linkage path, the client can request exclusion of that intermediate linkage.

For instance, the following request would return an article along with authors of comments (but not the comments themselves): 

```
GET /articles/1?include=-comments.authors
```

Some finer points to this proposal:
- In the case of included paths but missing fields, linkage MUST be excluded.
- In the case of one path that includes linkage and another that doesn't (for example, `include=articles.author,-articles.notes`) the intermediate linkage MUST be included as needed to fulfill the requested linkage.

I believe this approach will work well because it still guarantees full linkage _by default_, which I think is very important.

Unless I'm missing something, it also removes all inconsistencies from the spec in this regard.

The only known limitation is that it still doesn't provide linkage from a primary resource to a leaf node without intermediate linkage. In other words, there is no facility to "roll up" a leaf node's linkage on a primary resource without the server explicitly declaring an aliased relationship (for example, the alias `comment-authors` instead of the path `comments.author`). I find this to be an acceptable limitation.

**Comment by ksimka** [comment]
> By placing a reserved character, such as -, before a segment of a linkage path, the client can request exclusion of that intermediate linkage.

So if a path consists of 3 parts, it'll look like 

```
GET /users/1?include=photos.-comments.authors
(fetching photos and authors of comments to photos, but not comments)

GET /users/1?include=-photos.-comments.authors
(fetching only authors of comments to photos)
```

Right?

> In the case of one path that includes linkage and another that doesn't (for example, include=articles.author,-articles.notes) the intermediate linkage MUST be included as needed to fulfill the requested linkage.

For me it looks like a bad request, conflict. Can we be more strict here? I can imagine why one client will build that kind of request (conditional query builder), but hey, just validate it and fix before run. 

> At the same time, I'd like to resolve the inconsistency that remains in the spec in which fields MAY be excluded. This prevents full linkage but is not mentioned as an exception anywhere.

Can you please explain what do you mean? I'm watching the spec evolution, but not sure about that inconsistency.

**Comment by dgeb** [comment]
> Right?

Yes, that's what I had in mind. Thanks for the clarifying examples.

> For me it looks like a bad request, conflict. Can we be more strict here?

Maybe `409 Conflict` is the right answer here. It would certainly be easier to implement.

> Can you please explain what do you mean?

Compound documents currently require full linkage. However, `fields` can be used to exclude fields, which could prevent full linkage from being present in a compound document.

**Comment by ksimka** [comment]
> However, fields can be used to exclude fields, which could prevent full linkage

But how? `fields` param controls objects' fields, not relationships. Or do you mean empty value: `fields[TYPE]=`? Does that mean "exclude all the TYPE resources"? (couldn't find anything about empty `fields` value) For me it's more like "attributes will be empty, but id, type and others will not".

**Comment by tkellen** [comment]
From the spec:

> A resource object's attributes and its relationships are collectively called its "fields".

**Comment by tkellen** [comment]
I believe that there **MUST** be a way to directly link to included records from the parent when intermediates are excluded.

For example given this resource object...

``` js
{
  "data": {
    "type": "articles",
    "id": "1",
    "attributes": {
      "title": "JSON API paints my bikeshed!"
    },
    "relationships": {
      "comments": {
        "links": {
          "self": "http://example.com/articles/1/relationships/comments",
          "related": "http://example.com/articles/1/comments"
        }
      }
    }
  }
}
```

... if you do `?include=-comments.author`, the authors will be populated under `included` but there will be no way to link them back to the primary data ("roll them up"). This seems like an abuse of `include` as a hacky query language that keys off the primary data to throw whatever you want into the included bucket.

Allowing partial representation means you could do something like `?include=-comments.-author.-articles.comments` and now `included` is populated with all comments on articles created by the authors of the comments on the primary document. Is this behavior really what we're trying to encourage?

I would argue that the included data has nothing whatsoever to do with the primary data unless the article's resource object in the aforementioned crazy request winds up being something like this:

``` js
{
  "data": {
    "type": "articles",
    "id": "1",
    "attributes": {
      "title": "JSON API paints my bikeshed!"
    },
    "relationships": {
      "comments": {
        "links": {
          "self": "http://example.com/articles/1/relationships/comments",
          "related": "http://example.com/articles/1/comments"
        }
      },
      "comments.author.articles.comments": {
        "data": [
          { "type": "comment", "id": "1" }
          // ...
        ]
      }
    }
  }
}
```

We could possibly require linkage "rollup" wherever there is a break in the representation, but our naming constraints prevent the representation I've shown above. Also  there are concerns about that relation being read only, because it would be fully insane to support POST/PATCH/DELETE etc to something like `/articles/1/relationships/comments.author.articles.comments`.

Honestly, partial representation/excluding intermediate records feels like something entirely different than include to me. It's like we're scratching at the surface of graphql in the most naive way possible.

It is so apt that this issue is #666.

**Comment by tkellen** [comment]
To be clear, I **want** to be able to exclude intermediate records but I think it makes no sense whatsoever without "rollup" to the primary data (or some entirely new construct in the spec).

**Comment by ksimka** [comment]
Thanks, @tkellen . 

But now, since we have mandatory full linkage, it looks a bit outdated. `include` is for controlling relationships, `fields` is for controlling attributes. 

Otherwise, according to the current spec, for the following request

```
GET /articles?include=author&fields[articles]=title,body&fields[people]=name
```

I **must** return the `author` object, because of `include`, and **must not** return the `author` object, because `fields[articles]` does not contain `author`. Right? It's a nonsense.

**Comment by dgeb** [comment]
I'm going to suggest that we only deal with the `fields` / full linkage inconsistency in the spec (special case an allowance for not providing full linkage when relationship fields are excluded).

I'm willing to shelve the rest of this and consider alternatives post 1.0. We've been down the "rollup" path before and it becomes very difficult to specify and implement.

Please comment here if you're willing to PR a fix for the inconsistency.

**Comment by tkellen** [comment]
You're right @ksimka, we need to deal with this. That's why we have this on the status page for the site.

> This release candidate exists solely to provide time for the specification to be carefully reviewed for inconsistencies and defects.

**Comment by bintoro** [comment]
What's the primary use case for excluding intermediate resources? Is it payload size, efficiency on the server, or something else?

**Comment by ksimka** [comment]
@tkellen 

> To be clear, I want to be able to exclude intermediate records but I think it makes no sense whatsoever without "rollup" to the primary data.

What if we say we can't totally exclude relationship from the response? Let's make `-` mean "I don't want data for that resource", but the other part of the object must be there.

``` http
GET /posts/1?include=-comments.author
```

``` js
{
  "data": {
    "type": "post",
    "id": "1",
    "attributes": {
      "title": "JSON API paints my bikeshed!"
    },
    "relationships": {
      "comments": [
        {"type": "comment", "id": 12}
      ]
    }
  },
  "included": [
    {
      "type": "comment",
      "id": 12,
      "relationships": {
        "author": {
          "type": "people",
          "id": 42
        }
      }
    },
    {
      "type": "people",
      "id": 42,
      "attributes": {
        "name": "Sam",
        "age": 90,
        // ...
      }
    }
  ]
}
```

What do you think?

@dgeb 

> Please comment here if you're willing to PR a fix for the inconsistency.
> 
> `include` is for controlling relationships, `fields` is for controlling attributes.

And that's all.

**Comment by dgeb** [comment]
> What's the primary use case for excluding intermediate resources?

@bintoro Probably payload size for most implementations. Could be server efficiency for others.

Anyway, I don't think it's worth introducing any complexity to the spec at this point. I'm going to close this once we fix the inconsistency.

> GET /articles?include=author&fields[articles]=title,body&fields[people]=name

@ksimka For your request, the `author` object should be returned as a person, but the author relationship would not appear in each `article`.

**Comment by dgeb** [comment]
Let's no longer discuss using `include` to exclude intermediate linkages. Let's leave that "as is".

> `include` is for controlling relationships, `fields` is for controlling attributes.

This is not correct.

**Comment by tkellen** [comment]
> What's the primary use case for excluding intermediate resources?

@bintoro Most probably payload size, but efficiency could matter too. In the insane query I mentioned above `?include=comments.author.articles.comments`, you could traverse to the target comments with a single SQL query, but if intermediate linkage is required, the entire graph has to be processed.

Per @dgeb's previous, I'm done talking about this for now. If I had one wish for what we would take away from this issue (besides fixing the internal inconsistency around fields) it would be that we realize excluding intermediate relationships = something other than include--perhaps with an entirely different response body style.

**Comment by dgeb** [comment]
And sorry - I submitted my comment earlier than intended.

To be clear:
- `include` is used to control inclusion of resources related to the primary resource.
- `fields` is used to control which fields appear in resources of each type.

I don't want to change this. I only want to carve out an exclusion in the full linkage requirement when `fields` excludes a particular relationship that would otherwise contain linkage.

**Comment by bintoro** [comment]
@tkellen I'm just wondering, must the "extra" linkage necessarily reside under primary data? When payload size is a concern, you could just put the excluded records in `included` anyway but transmit linkage data only, i.e. drop attributes if they're huge. Of course this doesn't help if query simplification on the server is the goal.

**Comment by ksimka** [comment]
@dgeb 

> @ksimka For your request, the author object should be returned as a person, but the author relationship would not appear in each article.

BTW, it's a request from the current docs.

> I don't want to change this. I only want to carve out an exclusion in the full linkage requirement when fields excludes a particular relationship that would otherwise contain linkage.

Maybe give `include` a higher priority? So `/articles/1?include=comments.author&fields[article]=body&fields[comment]=text` will be equal to `/articles/1?include=comments.author&fields[article]=body,comments&fields[comment]=text,author` .

**Comment by dgeb** [comment]
> BTW, it's a request from the current docs.

We should probably make it seem more realistic. And explain it better non-normatively. Sorry to say "your request" - don't mean to pin the blame on you :)

**Comment by tkellen** [comment]
@ksimka I think you're misunderstanding the problem (this one is tricky and I just left a note that we need to clarify it in the spec).

When you use `include` you are including things by relationship name. The result might be to drop resource objects into `included` that have multiple types (we support heterogenous collections). Imagine `/photos?include=usedBy` where `included` is populated by resource objects of the type `people`, `place`, `animal` etc.

It is not always the case that a relationship name matches the type you're trying to limit fields for.

**Comment by dgeb** [comment]
Closing in favor of #670

**Comment by ksimka** [comment]
@tkellen, ouch, my bad, thanks for clarifying )

**Comment by ethanresnick** [comment]
One idea, that I'm just documenting here for future reference (we don't need to act on it before 1.0) would be to have a `"linkage"` object at the resource object's top level. The keys of `"linkage"` would be populated with paths from the `include` param and wouldn't be subject to `fields` restrictions. This key could contain composite relationship paths (e.g. `comments.author`) without implying the existence of an endpoint at `/relationships/comments.author`, and it would be a more sensible serialization of the `include` param then having it affect the keys in the `relationships` bag.
