### ISSUE TITLE
Media type parameter namespace

### ISSUE THREAD

**Issue by bintoro** [json-api/json-api#669]
It's unclear whether (extended) APIs will be free to modify the JSON API media type with proprietary parameters.

If this is not going to be allowed, then the newly created _Media Type Negotiation_ section could just as well prescribe a blanket ban on any parameters instead of singling out `ext`.

But if proprietary parameters will be allowed, then it means JSON API itself won't be able to introduce new parameters in the future without theoretically risking conflict.

Any option between these two extremes seems to require some kind of namespacing scheme, similar to those currently being discussed in #602.

**Comment by ethanresnick** [comment]
@bintoro Media types must be registered with their allowed parameters at the IANA, so we couldn't (in a compliant manner) allow users to add their own parameters even if we wanted to. I'm working on some cleanup for the Media Type Negotiation section that takes this into account. But, other than that, I don't think we have to make any mention of media type parameter names in the base spec (except perhaps for clarity), because any user-defined ones would be non-compliant at a lower level.

**EDIT**: Technically, since we're in the vendor tree, we _could_ use unregistered parameters, but it'd be a bad idea. Specifically, the media type registration spec [says](https://tools.ietf.org/html/rfc6838#section-4.3):

> the names, values, and meanings of any parameters MUST be fully specified when a media type is registered in the standards tree, and SHOULD be  specified as completely as possible when media types are registered in the vendor or personal trees.

**Comment by dgeb** [comment]
It seems that we really should reserve the right to define any and all media type parameters, and not allow implementations to define custom ones. There are plenty of alternatives for implementations to do API versioning, etc.

**Comment by bintoro** [comment]
@dgeb I tend to agree and had already typed up a PR to disallow custom parameters when I decided to open this issue instead.

If a custom versioning scheme is communicated in a separate header, then a provider may not be able to easily use the server platform's media type matching services that are generally based on the `Accept` header. I figured this might annoy some people.

Also, versioning is a pretty basic part of any serious API, so it would be nice to have a standard way of negotiating over it.

On the other hand, there can potentially be many things to negotiate about: extensions, JSON API versions, and proprietary API versions. Stuffing all of these facets in a single header can give rise to a large number of parameter combinations, which may not be ideal. Using a separate header such as `Accept-Version` would allow a server to decide on the appropriate version first and then move on to JSON API -specific stuff.

I'm wondering if there are any notable frameworks around that make it difficult to deal with custom HTTP headers. If not, then I would also favor reserving all media type parameters.

**Comment by ethanresnick** [comment]
I'm far from an expert on API versioning, but I know that it's a really hard problem, and I doubt that we're going to come up with a good, standard solution in the next few days. Even if we reserved something like `api-version` for private use in the `Accept` header (which is a questionable use of content negotiation in some cases), I think defining the precise role of that parameter would be a pain. So I'm pretty inclined to just reserve all media type parameters for now (as #673 does), and then we can always add `api-version` or similar later.

**Comment by tkellen** [comment]
The resolution to this is #703.
