### ISSUE TITLE
Select a mascot

### ISSUE THREAD

**Issue by brixen** [json-api/json-api#67]
To best promote JSON API as a universal standard across the universe, a mascot is vital.

To submit a candidate for the JSON API mascot, please comment with a link to visual artifact suitable for high quality print or display. By submitting, you assert that you own the copyright to the material (or it is in the public domain) and you release all rights to it with respect to its use by JSON API.

Submissions will be accepted until the standard is finalized for version 1.0, then a vote will be held.

**Comment by brixen** [comment]
[Gavin Johnson](http://twitter.com/snow6oy) submitted http://pic.twitter.com/CYVChK761Z via [Twitter](https://twitter.com/snow6oy/status/333664131305582592). It is inspired by the UML symbol for an interface.

**Comment by GavinJoyce** [comment]
![jsonapi](https://f.cloud.github.com/assets/2526/493450/7090394a-bb45-11e2-9d3d-a710c1238233.png) 
![json-api3](https://f.cloud.github.com/assets/2526/493469/ab9a8e80-bb47-11e2-93fb-878aa8475593.png)
![json-api2](https://f.cloud.github.com/assets/2526/493471/b2429d22-bb47-11e2-8bd6-22a2c5b021a3.png) 
![json-api4](https://f.cloud.github.com/assets/2526/493472/b75718e2-bb47-11e2-89a0-3d49d64d684b.png)

**Comment by steveklabnik** [comment]
Adding to 1.0. ;)

**Comment by dgeb** [comment]
I think we can close this now that we have a [logo](http://jsonapi.org/images/jsonapi@1.3x.png)
