### ISSUE TITLE
Versioning of the APIs

### ISSUE THREAD

**Issue by ramkumarkb** [json-api/json-api#68]
How to version the JSON APIs so that changes can made w/o affecting the exisiting clients:

Here are some URIs using version identifiers:

http://www.example.org/v1/customer/1234
http://www.example.org/v2/customer/1234
http://www.example.org/customer/1234?version=v3
http://v4.example.org/customer/1234

**Comment by steveklabnik** [comment]
Thanks, we'll be putting something in the FAQ about this.

**Comment by drgomesp** [comment]
I didn't find any info about the API versioning issue. How is this going?

**Comment by steveklabnik** [comment]
It's outside of the scope of JSON API proper.

**Comment by drgomesp** [comment]
@steveklabnik can you please elaborate on that?

**Comment by steveklabnik** [comment]
How you version your API is completely orthogonal to JSON API itself, which is concerned about HTTP semantics and the arrangement of your JSON.

At Balanced, we've versioned through the Accept header. If I were making a new project, I'd not version at all. Someone else may version through URLs. It doesn't really matter.

**Comment by drgomesp** [comment]
Right, @steveklabnik.

But doesn't Accept header and URL versioning affect HTTP semantics?

**Comment by steveklabnik** [comment]
URL versioning has nothing to do with HTTP. Accept may. It doesn't affect anything in JSON API directly.

It's very similar to how we don't specify an authentication method: you can use whichever you'd like, that doesn't matter.
