### ISSUE TITLE
Identify Errors by URI

### ISSUE THREAD

**Issue by ethanresnick** [json-api/json-api#683]
Before I write up a PR for this, I want to see if there's interest. The idea is to identify particular error cases described by the spec with a URI, which would live at the `href` property in the returned error object. This would have a few advantages, as I see it: 
1. It would allow clients to distinguish between multiple errors that return the same status code. For example, a 403 Forbidden can occur on a request to replace a to-many relationship either because full replacement isn't allowed, in which case the client might be able to reformat its request successfully, or because the client simply isn't authorized to patch the resource, in which case it should give up. The same ambiguity can occur for a POST with a client-generated id, that is: the 403 could be coming because of a general authorization error, which the client can't do anything about, or because client-generated ids are unsupported, which it may be able to adjust to. As I alluded to in #673, there will also likely be different-but-same-status-code errors around extension negotiation that it would be valuable for clients to be able to distinguish as well. For example, the difference between extension negotiation not being supported at all vs. a particular combination of extensions not being supported.
2. It would be a usability win, in that each error uri could actually be dereferenceable to a page at jsonapi.org that has a human-readable description of the error and suggestions for fixing it. Angular does this for its errors and its incredibly helpful.

To get the full benefits of (1) for clients, I think this would ideally be a **MUST** for 1.0 (at least for certain errors), since it doesn't impose any real implementation burden on servers. That said, these URIs could be added as a SHOULD post 1.0, with almost the same value.

**Comment by dgeb** [comment]
I think that we're going to have to accept SHOULDs post-1.0 as the most stringent possible requirements, given the lack of time available and experience with real world implementations in this regard. It would probably be best to start with recommendations and then work from there.

**Comment by ethanresnick** [comment]
@dgeb Sounds good! I'll let this sit until after the 28th and we'll revisit it then.

**Comment by hhware** [comment]
@ethanresnick, going one step further, could `links` in error objects be considered for this purpose?

**Comment by ethanresnick** [comment]
@hhware Yes, it would be reasonable and more consistent to say `"links": {"describedby": "..."}` from within the error object in place of `"href": "..."`. But that would be a (small) breaking change. @dgeb @tkellen Would you be in favor of such an adjustment?

**Comment by hhware** [comment]
@ethanresnick, indeed, I somehow missed that the spec already has `href` in `errors`! In this case, I believe it should be converted to `links`. Submitted #690 for that.

**Comment by ethanresnick** [comment]
@dgeb Do you agree with the basic idea of identifying error types by URI rather than, or in addition to, an application-specific code? The benefits I imagine are, again, that: 1) the spec can provide unique identifiers that clients can use to identify certain error cases and adjust their behavior accordingly; and 2) these URIs can serve as documentation for how to resolve the error, offering a better developer experience.

Re the first goal/benefit, I think the number of errors that clients will want to distinguish between is systematically increasing as we add more, optional features post 1.0, and status code is not enough for distinguishing many of these cases.

If you're on board with the general idea here, I'd like to get a PR into the 1.1 draft as part of/as a prerequisite for the sideposting PR, as I believe that PR would benefit from (if not require) being able to mint URIs for the new error cases it opens up.

**Comment by dgeb** [comment]
@ethanresnick I would prefer not to remove any fields, especially considering that they are optional. Currently we only have one `about` link recommendation in the `links` object within an `errors` object. The `about` link "leads to further details about this particular occurrence of the problem." 

I think there's a place for an additional link recommendation - maybe `type` - that could serve the role you're looking for. What do you think?

**Comment by ethanresnick** [comment]
@dgeb The key thing I wanted to check was if you're open to a member with this purpose, and it sounds like like you are, which is great. As far as the details go:

- I'm ok with keeping `code` for now. I do think it'll be redundant once `type` is in place, but whether to deprecate it can be a separate conversation.

- I'm also ok with `type` being a `link` for now, and I'll work up a PR to that effect. Above all, I just want us to have something in the 1.1 draft for now that the extensions and sideposting proposals can reference. However, I'm very worried about shipping this as a link in 1.1 unless we've figured out our hypermedia plans in more depth. My (indirect) reasoning for that is basically:

  1. For certain **new** errors related to extensions/sideposting, I want to require that servers send this URI in their error objects

  2. But, there's currently nowhere in the spec that we require a link and, once we start requiring servers to send `links`, that would actually make impossible some ideas I've had for how to improve JSON:API's hypermedia support that rely on `links` being optional. 

I don't want to go too far down the hypermedia rabbit hole here; I'm just flagging this as something to resolve pre 1.1, even after we have it as a link in the 1.1 draft.

Perhaps after we have our 10k feet extensions conversation—which may well touch on hypermedia, since forms and link templates are a very powerful way for APIs to communicate their capabilities—we can have a dedicated conversation about JSON:API and hypermedia?

**Comment by ethanresnick** [comment]
Closing as solved by #1199.
