### ISSUE TITLE
Implementations out of date or not being maintained

### ISSUE THREAD

**Issue by joananeves** [json-api/json-api#686]
[Examples](http://jsonapi.org/implementations/#examples) has a very nice reference to http://restpack-serializer-sample.herokuapp.com/ but examples are out of date...
It seems that it's not only examples, it seems that [RestPack::Serializer](https://github.com/RestPack/restpack_serializer) is not being mantained also...
Being JSON API almost being release as 1.0, shouldn't [implementations](http://jsonapi.org/implementations) listed be at least 'still alive' ?

**Comment by tkellen** [comment]
Great point @joananeves. We should definitely review this list before marking 1.0 officially. Long term, I have plans to implement a test suite for the specification using http://github.com/endpoints/fantasy-database, and the integration suite from http://github.com/endpoints/endpoints. Eventually we'll be able to use those things collectively to verify compliance with much more accuracy.

**Comment by neomerx** [comment]
Moreover on [implementations list](http://jsonapi.org/implementations/) there are 'libraries' that do not even exist. They declare it would be nice to have an implementation.
