### ISSUE TITLE
CSS for code tags doesn't let them stand out inside lists

### ISSUE THREAD

**Issue by csantero** [json-api/json-api#704]
When code tags appear in paragraphs, they get the shaded background. This CSS doesn't apply inside lists. Currently, the word "about" in the second item of the before screenshot doesn't really stand out. Applying the paragraph `code` CSS to all `code` tags makes "about" stand out, but now the subject of each list item is also shaded, which may or may not be the desired effect. What do people think?
### Before:

![jsonapi code blocks](https://cloud.githubusercontent.com/assets/828286/7849069/6c8bae2e-049f-11e5-9a4f-cd13fe4ef11f.PNG)

**Comment by tkellen** [comment]
Thanks for pointing this out @csantero, I've just submitted a PR to fix.
