### ISSUE TITLE
Exemplar implementations

### ISSUE THREAD

**Issue by heartsentwined** [json-api/json-api#73]
It was mentioned, in the [examples](http://jsonapi.org/examples/) section, that [ember](http://emberjs.com/guides/models/the-rest-adapter/) is an exemplar implementation of `json-api`. However, as I have detailed in emberjs/data#983, this is far from the case. Perhaps we should remove this from the docs?

**Comment by steveklabnik** [comment]
I think it's more motivation to make it compliant soon ;)

**Comment by heartsentwined** [comment]
By the way, [active_model_serializers](https://github.com/rails-api/active_model_serializers) doesn't churn out `links`-style response either.

**Comment by steveklabnik** [comment]
Yup. Working on patches now.

More seriously, later today I'm going to do some re-organization, ill make this more clear.

I want to add the RABL wiki pale with compliance as well.

**Comment by steveklabnik** [comment]
Between @brixen and I's work recently, this is done.
