### ISSUE TITLE
Question: How to infer "to-one" vs "to-many" relationship if no "resource linkage" is present?

### ISSUE THREAD

**Issue by scott-mcdonald** [json-api/json-api#736]
Currently the majority of examples for relationships in the specification include the resource linkage elements which a client could then infer if the relationship is "to-one" or "to-many" by examining the value of the "data" property. If the "data" property is an "object" or is null then "to-one", else if is an "array" empty or not then "to-many".

But if the resource linkage is not included in the response then a client could not infer if the relationship is a "to-one" or a "to-many" relationship. A client would want to know if it did a GET on the "related" resource URL for example should it expect 0 to 1 resource for a "to-one" relationship versus a 0 to many resources for a "to-many" relationship. This would apply to a GET/PUT/POST/PATCH on the "self" relationship URL as well.

Personally I don't think the client should have to infer anything, this should be explicit. The question is how should this be specified? Any suggestions?

I suppose some will say put this type of information in the "meta" object in the relationship "links" but this feels more like a hack/workaround IMHO - personally I think it should be part of the json-api specification? I came across this because in my C#/.NET modeling of JSON-API I have an abstract relationship class and concrete "to-one" and "to-many" relationship classes and on JSON deserialization without the resource linkage "data" element I hit an "uh-oh" moment.

As an example, taking your root example from the home page and removing the "resource linkage" elements you can not tell if the author or comments relationships are "to-one" or "to-many":

``` javascript

{
  "links": {
    "self": "http://example.com/posts",
    "next": "http://example.com/posts?page[offset]=2",
    "last": "http://example.com/posts?page[offset]=10"
  },
  "data": [
    {
      "type": "posts",
      "id": "1",
      "attributes": {
        "title": "JSON API paints my bikeshed!"
      },
      "relationships": {
        "author": {
          "links": {
            "self": "http://example.com/posts/1/relationships/author",
            "related": "http://example.com/posts/1/author"
          }
        },
        "comments": {
          "links": {
            "self": "http://example.com/posts/1/relationships/comments",
            "related": "http://example.com/posts/1/comments"
          }
        }
      },
      "links": {
        "self": "http://example.com/posts/1"
      }
    }
  ]
}

```

**Comment by ksimka** [comment]
And how do you know if it's "to-one" or "to-many" when linkage is there? The same way — it's either object (to-one) or array (to-many).

**Comment by scott-mcdonald** [comment]
@ksimka That wasn't the question, I already know if linkage is present if it is "to-one" or "to-many" based on an object versus an array like I stated in the original post, the question is if _data (resource linkage) is not present at all_ which is a possibility if the service doesn't want to include resource linkage at all and just provide links only as is possible based on the specification (unless I missed something when reading it).

By just the links alone a _generic client_ would not know if the relationship is "to-one" or "to-many". The generic client would have to do a GET on the self or related link an examine if the primary data is an object or an array - but doing a GET to determine the _cardinality_ of the relationship does not feel correct and I feel this should be explicit in the relationship specification...

Am I wrong? What are others opinions?

If the goal of json-api is the ability to create generic clients/tools then knowing the difference between a "to-one" versus a "to-many" relationship is important due to semantic reasons. A contrived example, does a generic client allow a single selection via a "combo box" (to-one) versus a "list box" (to-many).

**Comment by ksimka** [comment]
I just can't get why you need to know this. My point was that you can just get those resources and see what's there, object or array, and then make a desicion.

But if you really need this for some reason, I'm afraid in the current version of the spec there is no any flag that can help.

**Comment by ethanresnick** [comment]
@scott-mcdonald I mentioned this briefly way, way [back](https://github.com/json-api/json-api/issues/276#issuecomment-61030060). I agree that this type of information is useful, and I suspect JSON API will add more, optional support for this kind of stuff over time; we've already seen other machine-readable documentation-related proposals with [schemas](https://github.com/json-api/json-api/issues/310), which might extend to your case, and an [immutables](https://github.com/json-api/json-api/pull/589) list. 

I think we need to figure out a coherent position on how to support this kind of documentation, though, which might or might not be schemas (and it might just be unofficial support through extensions). But we probably shouldn't add bits and pieces ad-hoc (e.g. putting a flag in the relationship object). So, for now, I'm afraid you're stuck with a `meta` based solution.

**Comment by scott-mcdonald** [comment]
@ksimka My point was I did not necessarily want to do a GET on the related resource(s) to determine the "types" of relationships and was thinking it should be part of the specification, something along the lines of:

``` javascript
"relationships": {
        "author": {
          "type": "to-one",
          "links": {
            "self": "http://example.com/posts/1/relationships/author",
            "related": "http://example.com/posts/1/author"
          }
        },
        "comments": {
          "type": "to-many",
          "links": {
            "self": "http://example.com/posts/1/relationships/comments",
            "related": "http://example.com/posts/1/comments"
          }
        }
      }
```

The reason I was thinking about this area is I have sold "business" (the bean counters) that we should adopt _json-api_ as our standard for our Level 3 REST API and deprecate our current proprietary JSON responses with my biggest selling point being the "compound document" feature among other reasons...

So in our C#/.NET/Web API strongly typed world I modeled a resource relationship as an abstract class with concrete "to-one" and "to-many" relationship classes. When deserializing a _json-api_ resource it was impossible to know what concrete relationship class to create based on links alone, hence the reason for this post. This type of problem is not a problem in loosely-typed languages which is probably where you are coming from...

I suppose the proper modeling is to **not** make a resource relationship abstract so it can be instantiated, therefore if no _data (resource linkage)_ is present in the relationship then create a relationship object, if data is present create a "to-one" or "to-many" relationship object based on if the data was an object or array respectively.

That aside and for the sake of completeness, overall I do feel the "relationship object" needs further specification in this "to-one" versus "to-many" semantic divide to give me that "warm fuzzy feeling" instead of relying on inference...

**Comment by tkellen** [comment]
I concur with @ethanresnick on needing to use `meta` for now. We may progress to supporting schema information like this in the future (via extensions or possibly even additions to the base spec). That being said, we'd like to give the community and implementors some time to get up to speed before adding more features. We marked 1.0 last Friday and have only just begun to discuss what kind of release cycle we want to have for additions.

**Comment by ksimka** [comment]
> When deserializing a json-api resource it was impossible to know what concrete relationship class to create based on links alone, hence the reason for this post. This type of problem is not a problem in loosely-typed languages which is probably where you are coming from...

@scott-mcdonald, no, our consumers are strongly typed too. But when API is about business and money I prefer a good documentation instead of machine-readable API. That's why it's hard for me to understand your needings :) We're using json-api as an amazing format for getting compound documents.

BTW, you'll have the same problem with many other things like pagination, filtering and sorting: now you don't know if resource supports pagination and what parameters do you need for filtering something out and so on. Json-api will not tell you. I don't believe that honest fully machine-readable API is a good thing. But it's just my opinion :)

**Comment by scott-mcdonald** [comment]
@tkellen Understood about 1.0 and meta is fine for the interim but do feel it will add _completeness_ to an already great specification down the road. Please keep it on your radar.

I just want to add the splitting out of _relationships_ from the previous _links_ was a stroke of genius, it did feel _links_ was overloaded with "multiple purposes", now _relationships_ models semantic relationships between resources and _links_ is more for structural navigation which seems correct and made the C#/Web API implementation much simpler then before _relationships_ was introduced. So shout out to @ethanresnick for a great proposal.

**Comment by MrTrick** [comment]
@scott-mcdonald I'd say the best approach would be that the client has a relationship class without such `to-one` or `to-many` features, and just have 'count', 'iterator', and 'first' methods regardless.

All clients could program defensively and not make assumptions about "A only has-one B".  
Consider LDAP clients that put all attribute values in arrays, regardless of whether MULTIPLE or not.

**Comment by scott-mcdonald** [comment]
@MrTrick

I already solved this awhile back by the following:
- I have 3 types of relationships where any of these 3 types can be instantiated:
  - Relationship has Links and Meta
  - ToOneRelationship inherits from Relationship and adds Data as a ResourceIdentifier object
  - ToManyRelationship inherits from Relationship and adds Data as a ResourceIdentifier array
- Upon JSON deserialization I use the following algorithm:
  - If Data is not present in the JSON, then create a Relationship object
  - If Data is present in the JSON, then
    - If Data is an object or null create a ToOneRelationship object
    - If Data is an array create a ToManyRelationship object.

**Comment by MrTrick** [comment]
@scott-mcdonald fair enough. I suppose something like a factory pattern could convert your Relationship object into a ToOne or ToMany object.

However, what I'm saying is "why bother?". 
- Your business rules might change over time. 
- An assumption that's correct now (eg "a person only has one current supervisor") might not be correct in the future. 

Having the framework treat everything as potentially "to-many" makes for a more future-proof solution.

**Comment by scott-mcdonald** [comment]
Closing this issue, based on my previous comment on 1/20/2016.

**Comment by kael-shipman** [comment]
@MrTrick, this is more just a thought for JSON API authors, but I figured I'd put it here since it's relevant.

I've been thinking about it, and I do like the idea of looking at all relationships as "to-many" (although it does present some frustrating usability issues, like always having to do things like `post.author[0].name` intead of `post.author.name`).

The only thing is, if we're going to do this, it seems necessary to make the spec honor that by only allowing collections in data objects for relationships, and disallowing `Resources` or `ResourceIdentifiers`. Doing this would give `null` and `[]` semantically clear meanings: A value of `null` would always mean _"not yet retrieved"_, regardless of relationship type, whereas a value of `[]` (empty collection) would always mean "none/not set", regardless of relationship type. (Currently `null` is potentially ambiguous, since in the case of to-one relationships it means "not set" and in the case of to-many relationships, it's somewhat undefined, but can be taken to mean "not yet retrieved".)
