### ISSUE TITLE
Include related resources for CREATE/UPDATE

### ISSUE THREAD

**Issue by old-grrt** [json-api/json-api#737]
So, I have this API. To use it, you need to 'login' first. Such login is actually a POST to /tokens 

Successful authentication returns a valid token along with an expiration date. It would be nice if
I could optionally include the token owner along the response. 
The question is: 
Including related resources for create/update request is something that JSON API should allow/prohibit explicitly? If so, what would be the case, good or bad idea?

It may look something like this

```
{
    "data" : {
        ...
    },
    "include" : "relationship"
}
```

Or maybe 

```
POST /resources?include=relationship
Content-Type: "application/vnd.api+json"
{ "data" : ... }
```

Thanks

**Comment by tkellen** [comment]
JSON API supports this behavior.

Here is a note from the bottom of the [inclusion of related resources](http://jsonapi.org/format/#fetching-includes) section:

> Note: This section applies to any endpoint that responds with primary data, regardless of the request type. For instance, a server could support the inclusion of related resources along with a POST request to create a resource or relationship.

I'm going to close this as a resolved, but please feel free to continue the discussion if need be!
