### ISSUE TITLE
Requesting resource that includes self-referential compound documents

### ISSUE THREAD

**Issue by tammersaleh** [json-api/json-api#74]
Say each person has friends that are also other people.  If I `GET /person/1`, and I'm returned a compound document, I'll get something like this:

``` json
{
  "people": [
    {
      "id": "1",
      "name": "Tammer",
      "links": { "friends": ["9"] }
    }, 
    {
      "id": "9",
      "name": "DHH"
    }
  ]
}
```

I can no longer assume that the first document in the "people" array is the one I want.  I must instead loop through them comparing `id` values to get the root document I originally requested.  Two solutions come to mind:
1. Require an order, so that it's assumed that requesting a singular resource will return an array where the _first_ document is that resource.  I don't care much for this solution.
2. Nest all related resources in another array.  Fairly heavy handed:

``` json
{
  "people": [{
    "id": "1",
    "name": "Tammer",
    "links": { "friends": ["9"] }
  }],
  "linked": [
    "people": [{
      "id": "9",
      "name": "DHH"
    }]
  ]
}
```

This affects all responses, of course:

``` json
{
  "posts": [{
    "id": "1",
    "title": "Rails is Omakase",
    "links": {
      "author": "9"
    }
  }],
  "linked": [
    "people": [{
      "id": "9",
      "name": "@d2h"
    }]
  ]
}
```

...and begs the question of what to return if I am my own friend.

So:  Thoughts?

**Comment by barelyknown** [comment]
Really good question. I like option 2 (nest all related resources in another array) because it makes parsing responses more straight forward and eliminates ambiguity.

**Comment by dgeb** [comment]
This came up in another issue in which [I suggested the separation of the primary document from its related documents](https://github.com/json-api/json-api/issues/8#issuecomment-17459267) just as you've done in option 2. Although that issue drifted away from this discussion without providing a resolution, both of the options you presented were discussed there.

I still favor option 2, and I like your suggested name (`linked`) better than the old `rels` keyword that's no longer being used in this spec. Placing significance on the order of items in an array to identify a primary document seems less clear, and also prevents requests to order the returned results (e.g. by name or date).

**Comment by barelyknown** [comment]
+1 for `linked`. It feels right.

**Comment by kjwierenga** [comment]
Isn't there a way to let the top-level `links` attribute handle this case too in some way?

**Comment by tammersaleh** [comment]
@kjwierenga how do you mean?

@wycats / @steveklabnik Any thoughts from you ends?

**Comment by kjwierenga** [comment]
In the URL-Based JSON API there is a top-level `links` section for URL Template Shorthands. My thinking was to use that for nested related resources too. On second thought maybe that's not such a good idea given the totally different goal of `links` and your proposed `linked` top-level attributes.

**Comment by Xiot** [comment]
+1 for `linked` as well.
I've started to implement client & server side handlers for api+json in c# (which I'll make public once its a little more complete). 
With both the id style and the url style, the parsing gets a little ambiguous, especially with dynamic data models like I have in my case.  One thing that I've had to do is to determine whether or not an items link was a url or an id in an unknown linked item.

In the following example `posts.links.author` has no clear meaning.  Is the `9` a relative uri, or is it an id.  And if it's an id, which collection does it point to.

``` javascript
{
  "posts": [{
    "id": "1",
    "title": "Rails is Omakase",
    "links": {
      "author": "9"
    }
  }],
  "linked": [
    "people": [{
      "id": "9",
      "name": "@d2h"
    }]
  ]
}
```

I realize that with a little bit of client side logic this is known ahead of time, however in my case I don't always have that luxury.  One of the ideas that I was thinking about was to come up with a intra-document uri.  So in this case it would look something like this

``` javascript
{
  "posts": [{
    "id": "1",
    "title": "Rails is Omakase",
    "links": {
      "author": "linked://people/9"
    }
  }],
  "linked": [
    "people": [{
      "id": "9",
      "name": "@d2h"
    }]
  ]
}
```

`posts.links.author` would be something like `linked://people/9` instead of just `9`.  Easy enough to parse and tells you exactly where the resource is located.  I'm not quite sold on the fake `linked://` scheme, it was just my first thought.

I welcome thoughts / comments / feedback.

EDIT:
I realize that the top level `links` item can tell you the name of the collection ie 

``` javascript
{
  "links": {
    "posts.author": {
      "href": "http://example.com/people/{posts.author}",
      "type": "people"
    },
}
```

However it seems like a lot of jumping around

**Comment by andrewsardone** [comment]
Please forgive me if I'm missing something, but it seems like there is a third option.

So, a `person` can have many `friends`, each of which is also a person. `GET /people/1` could return a compound document like so:

``` json
{
  "links": {
    "people.friends": {
      "href": "http://example.com/people/{people.friends}",
      "type": "friends"
    }
  },
  "people": [
    {
      "id": "1",
      "name": "Tammer",
      "links": { "friends": ["9"] }
    }
  ],
  "friends": [
    {
      "id": "9",
      "name": "DHH"
    }
  ]
}
```

It's clear that the primary document is `people/0` – it's the singular document identified by the name of the requested resource (`GET /people/1`). One can link to all related friends via the normal embedded `people/0/links/friends` path and expanding the top-level `links.people.friends` URL template. On top of that, one can key off of the `people/0/links/friends` resource name for looking up included compound documents.

Clearly this breaks the (tacit?) assumption that the resource name reflects some deeper absolute type of the collection's elements and not merely an identifier within the scope of the JSON response. This could be a deal breaker, but at first glance it's unclear to me that it is problematic. Could someone help clarify any issues with this third option?

**Comment by dgeb** [comment]
I still think `linked` is the right answer here, but I favor `linked: { }` over `linked: [ ]`. It allows for easier access to each resource type on both sides of the API.

**Comment by samwgoldman** [comment]
I'm not sure I see any issue here.
1. consumer requests person from the store, e.g. store.get("person", 1)
2. store requests the person resource (assuming the resource is not already in the store)
3. store pushes all documents in the response, which includes person 1 and all sideloaded documents, indexed by modelName/ID
4. store queries its internal state for the person with ID=1, which is returned

This is effectively your "option 1" but that seems like intended behavior. Am I missing something?

[Edit: Sorry, this isn't your "option 1." This is the un-numbered option, "loop through them comparing id values"]

**Comment by samwgoldman** [comment]
Ah, now I see where I was mistaken. Client's who are creating a resource with server-side IDs wouldn't know which one was the primary. I was only considering a GET request where the type and ID would be known. Thanks!
