### ISSUE TITLE
What does this section mean exactly?

### ISSUE THREAD

**Issue by benhartney** [json-api/json-api#741]
> Complex data structures involving JSON objects and arrays are allowed as attribute values. However, any object that constitutes or is contained in an attribute MUST reserve the relationships and links members for future use.
> https://github.com/json-api/json-api/blob/84ad5cdba292a90f3aa72a9fd57065607ba92263/format/index.md#attributes-

What exactly does `reserve the relationships and links members for future use` mean?

**Comment by tkellen** [comment]
It means this:

``` js
{
  "attributes": {
    "name": "tyler",
    "skills": {
      "programmer": true,
      "spec author": true,
      "links": "anything", // illegal, we may support links in nested attributes at a later date
      "relationships": "anything" // illegal, we may support relationships in nested attributes at a later date
    }
  }
}
```
