### ISSUE TITLE
Add CSS print style sheet for improved print reading experience

### ISSUE THREAD

**Issue by jayeff** [json-api/json-api#744]
Hi,
currently there is no optimization for the website when a page is printed. With CSS it's quite simple to improve printed output. I would be willing to write a CSS style sheet but before I start working on this I wanted to ask a) if such a pull request is welcome and b) if you have any thoughts on this topic?

**Comment by tkellen** [comment]
:+1: Please do!

**Comment by jayeff** [comment]
I opened a PR #757 - still needs some work and testing but probably is a good first step.

**Comment by tkellen** [comment]
Thanks @jayeff! Will review soon.

**Comment by jayeff** [comment]
Thanks, I'm a little swamped with work ATM. Will do some tests with different browsers within the next few days.
