### ISSUE TITLE
Are resource names out-of-band?

### ISSUE THREAD

**Issue by kjwierenga** [json-api/json-api#75]
Page 61, chapter 21 "How can I tell if I’m using out-of-band information?" of http://designinghypermediaapis.com shows an example JSON representation containing a top-level 'post' key, and states that using 'post' in the client code is considered using out-of-band information.

Given the following example from http://jsonapi.org/reading

```
{
  "posts": [{
    "id": "1",  
    "title": "Rails is Omakase"
  }]
}
```

I would envision having a 'posts' method on an API client object. Something like this:

```
API.new(root_url).posts
```

Would this be considered use of out-of-band data? Or is this allowed by the use of the application/vnd.api+json media-type?

Because of this coupling we can't change the name "posts" to "pages" without changing the client. Don't get me wrong; I think this is a sensible constraint. An API conveys concepts/resources to the API client. This name coupling is unavoidable.

Question: when is the use of the resource names in the client code not considered out-of-band.

**Comment by steveklabnik** [comment]
This is what profiles are for. The type is about protocol semantics, and the profile would flavor it with your application semantics.

**Comment by kjwierenga** [comment]
Thanks. Reading about profiles now. 

Verstuurd vanaf mijn iPhone

Op 17 mei 2013 om 17:39 heeft Steve Klabnik notifications@github.com het volgende geschreven:

**Comment by steveklabnik** [comment]
Any time. Related: http://www.designinghypermediaapis.com/blog/the-profile-link-relation-and-you.html

**Comment by kjwierenga** [comment]
Read your article "The profile link relation and you". How does this relate to the following excerpt from Roy Fieldings [blog post](http://roy.gbiv.com/untangled/2008/rest-apis-must-be-hypertext-driven)?

> A REST API must not define fixed resource names or hierarchies (an obvious coupling of client and server). Servers must have the freedom to control their own namespace. Instead, allow servers to instruct clients on how to construct appropriate URIs, such as is done in HTML forms and URI templates, by defining those instructions within media types and link relations.

Is "posts" a fixed resource name? From what I understand this name is "fixed" as soon as I document it in the corresponding 'profile' right?

Edit: is this the right place for these questions?

**Comment by steveklabnik** [comment]
It's not fixed, it's described in-band. If the profile changes, the name can change.

This section is against saying "a user is always /users/123", which would not allow the server to control its namespace. Here, the profile says "you'll be able to find out where a user is, it may appear in responses" and the server is free to include or not include it as appropriate.

Hence the second sentence: you don't construct URIs, you let the media type and link relations tell you how.

**Comment by renato-zannon** [comment]
Sorry for reviving this, but I have a related question:

> It's not fixed, it's described in-band. If the profile changes, the name can change.

Should a client then test whether the profile has changed? If the name suddenly changes in the profile, how would an automated client continue to work?

**Comment by steveklabnik** [comment]
Once you publish a particular profile it's up to you to be additive only, to not break clients.
