### ISSUE TITLE
What does the related link of a resource fetch?

### ISSUE THREAD

**Issue by bryanburgers** [json-api/json-api#752]
Using the example in the [Document Structure > Compound Documents section](http://jsonapi.org/format/#document-compound-documents), what should fetching `/articles/1/author` return?

The [Fetching Data > Fetching Resources section](http://jsonapi.org/format/#fetching-resources) states:

> [`/articles/1/author`] fetches an article's author.

Is that:
1. A document that is effectively identical to fetching `/people/9` except with a different "self" link?
2. A 302 redirect to `/people/9`?
3. A unique document that provides some small bit of data that effectively tells the client that it should fetch `/people/9`?

I can see the value when a relationship is to-many. But I'm not sure what I should be implementing when the relationship is to-one.

**Comment by dgeb** [comment]
This question is answered in the description of [related resource links](http://jsonapi.org/format/#document-resource-object-related-resource-links).

In brief, it should fetch the _current_ related resource object as primary data. For a has-one relationship, `null` must be returned if the relationship is empty.

The top-level `self` link in the response document must match the request URL (e.g. `/articles/1/author`). The resource-level `self` link (if a resource object is returned) must point to the canonical URL for the related resource (e.g. `/people/9`).

**Comment by bryanburgers** [comment]
@dgeb As an example, that would look something like this?

```
{
  "links": {
    "self": "http://example.com/articles/1/author",
  },
  "data": {
    "type": "people",
    "id": "9",
    "attributes": {
      "first-name": "Dan",
      "last-name": "Gebhardt",
      "twitter": "dgeb"
    },
    "links": {
      "self": "http://example.com/people/9"
    }
  }
}
```

Which would be unique from `/people/9`, which would be:

```
{
  "links": {
    "self": "http://example.com/people/9",
  },
  "data": {
    "type": "people",
    "id": "9",
    "attributes": {
      "first-name": "Dan",
      "last-name": "Gebhardt",
      "twitter": "dgeb"
      // Full definition of a person is here, so could include more attributes,
      // whereas /articles/1/author is more of a summary
    },
    "links": {
      // Is it recommended to include this for the data, even if it's included
      // for the document?
      "self": "http://example.com/people/9"
    }
  }
}
```

**Comment by dgeb** [comment]
@bryanburgers yes, both those examples look good.

As for the inline comments: 
- There's nothing normative disallowing different representations of resources at different endpoints, so a summary at the related resource URL seems ok. However, I'd recommend against it to allow for more standard processing and let your clients request their own "summary views" via sparse fieldsets.
- If you're including `self` links, I'd recommend including them everywhere to allow for more standard processing (even if resource-level and top-level links happen to match).

**Comment by bryanburgers** [comment]
@dgeb Thanks for your help!

**Comment by dgeb** [comment]
Glad I could help, @bryanburgers!
