### ISSUE TITLE
question: about object creation with related objects

### ISSUE THREAD

**Issue by senid231** [json-api/json-api#753]
I read [#480](https://github.com/json-api/json-api/pull/480) and [#482](https://github.com/json-api/json-api/issues/482) but still have some questions.

According to this
[format/index.md#creating-updating-and-deleting-resources](https://github.com/json-api/json-api/blob/gh-pages/format/index.md#creating-updating-and-deleting-resources-)
we can create main object and his related objects using request like:

``` json
POST /photos HTTP/1.1
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "data": {
    "type": "contact",
    "attributes": {
      "name_first": "John",
      "name_last": "Doe"
    },
    "relationships": {
      "phone_number": {
        "data": [
                      { "type": "phone_number", "number":"123-456" },
                      { "type": "phone_number", "number":"123-457" }
                   ]
      }
    }
  }
}
```

And I expect that this request creates three objects:
one Contact with attrs `{ id: 1,  name_first: "John", name_last: "Doe" }`
two PhoneNumber with atrrs `{ id: 1, number: "123-456" }` and `{ id: 2, number: "123-457" }`

Am I right?

**Comment by Fivell** [comment]
+1 related #205

**Comment by senid231** [comment]
#205 has pretty nice solution of related objects creation but @dgeb dislike it (with understandable explanation).
There is #536 where @dgeb propose to create extension for embedding resource creation, but i think that @ethanresnick propose better solution. 
My opinion: it should be included into basic JSON-API with word **MAY**

Any updates related to this feature?

**Comment by neoneo** [comment]
Just posted a question about this on Stackoverflow before I found this and other discussions here. http://stackoverflow.com/questions/30704498/jsonapi-how-to-create-compound-documents

So it's officially not supported.
It has become clear to me now that in the general case, it's indeed pretty hard to solve this. Which is what the spec tries to do. It has no domain knowledge. But the API developer has that knowledge, so why not give some freedom in that regard?

For instance, if we have a person with bank accounts, we can be sure that the bank accounts belong to the person, so those can be inserted, updated and even deleted as specified in the sent data.
In a general one-to-many relationship, you cannot do this. For example a person with hobbies. Each hobby is possibly shared by many persons, so you can't just update a hobby if some person sends data where the hobby is renamed. In this case it might be more logical if non-existing hobbies are created, and others only linked but not updated.

So I agree with @senid231, I think it should be up to the API implementation what to do when embedded objects are sent along:
- it MAY insert non-existing ones
- it MAY update existing ones
  Whether an object exists can be decided based on it being a resource identifier object, or it containing a candidate key. The implementation decides what that key is, or if it exists at all (and what to do in that case, return a 403 for instance).

In general, the client cannot be sure that the state of the server is actually what was sent. Maybe that's a problem, but this could just be documented by the API publisher.

As a last remark, there will be more people wanting to embed objects and if the spec is not going to provide a definition for how to do this, people are going to come up with different approaches. This would be bad for the standard.

**Comment by tkellen** [comment]
[This feature is milestoned for 1.1](http://discuss.jsonapi.org/t/json-api-weekly-meeting-june-22nd-2015/23)

/ref #795
