### ISSUE TITLE
NON-HTTP Transports?

### ISSUE THREAD

**Issue by clavecoder** [json-api/json-api#755]
The documentation and specifications are all centered around HTTP. Has there been consideration of how JSON API would work within, say, WebSockets, or private protocol? For example, the format of URLs don't seem to be specified. Example, can they be relative, or do they have to be absolute? If relative, can they be protocol relative?

**Comment by dgeb** [comment]
Any valid URLs are compatible with JSON API - the base spec has no normative rules about them. However, there are some non-normative [recommendations](http://jsonapi.org/recommendations/#urls) for designing URLs across an API.

> Has there been consideration of how JSON API would work within, say, WebSockets, or private protocol?

The media type, described in the [Document Structure section](http://jsonapi.org/format/#document-structure), can be used to format JSON sent with other protocols besides HTTP.

**Comment by clavecoder** [comment]
Thanks!
