### ISSUE TITLE
Empty sparse fieldsets

### ISSUE THREAD

**Issue by PhilippMi** [json-api/json-api#759]
I have a resource (e.g. posts) which has a to-many relationship to other resources (e.g. comments). I do not need any fields of the related resource but their self-links (to fetch them asynchronously on demand). The response should look something like this:

``` javascript
{
  "links": {
    "self": "http://example.com/posts/1?xxx",
  },
  "data": [{
    "type": "posts",
    "id": "1",
    "attributes": {
      "title": "JSON API paints my bikeshed!"
    },
    "relationships": {
      "comments": {
        "links": {
          "self": "http://example.com/posts/1/relationships/comments",
          "related": "http://example.com/posts/1/comments"
        },
        "data": [
          { "type": "comments", "id": "5" },
          { "type": "comments", "id": "12" }
        ]
      }
    },
    "links": {
      "self": "http://example.com/posts/1"
    }
  }],
  "included": [{
    "type": "comments",
    "id": "5",
    "links": {
      "self": "http://example.com/comments/5"
    }
  }, {
    "type": "comments",
    "id": "12",
    "links": {
      "self": "http://example.com/comments/12"
    }
  }]
}
```

My question is how should the URL for the request look like?

My idea would be to include the comments and then use an empty sparse fieldset to avoid getting any comment fields but just the self link (+id, type).
Hence, it should look something like `http://example.com/posts/1?include=comments&fields[comments]=[]`.

The specification is not very detailed about sparse fieldsets or their relation to links.

**Comment by ethanresnick** [comment]
I think it would just be `http://example.com/posts/1?include=comments&fields[comments]=`, since that would make `fields[comments]` have an empty string as its value which, when comma-split, forms an empty list. It looks a little awkward, certainly, but I think that'd be the way to do it.

**Comment by dgeb** [comment]
Yep - I agree with @ethanresnick. I suppose a non-normative note to this effect could be helpful.

**Comment by ethanresnick** [comment]
P.S. @PhilippMi The long-term fix for this would probably be [optional links in resource identifier objects](https://github.com/json-api/json-api/issues/477#issuecomment-105958836), as has been discussed before. But one thing at a time :)

**Comment by PhilippMi** [comment]
@ethanresnick I thought about such a solution too and would really appreciate it.

Anyway, thanks for your help.
