### ISSUE TITLE
Possible Extension: Idempotent POST

### ISSUE THREAD

**Issue by ethanresnick** [json-api/json-api#764]
I have no clue how this would work yet, but I just want to throw out the idea, as having this use case on the table could affect our extension system's design. Making an idempotent POST isn't a new concept, but it can be quite useful in practice for recovering from network issues (see, e.g., [stripe's use](https://stripe.com/docs/api/node#idempotent_requests)), and I think it'd make a good extension.

Here's a good background article on the topic: https://www.subbu.org/blog/2008/10/double-post-and-poe

**Comment by steveklabnik** [comment]
What advantage does "idempotent POST" have over just using a PUT?

**Comment by ethanresnick** [comment]
Basically, that the client doesn't know the URI to PUT to yet, because the resource (and its URI) that would result from the POST may not have been created yet. So, if a client want to add an "article" resource, it can't PUT to the URI for that article before it exists. So these POE ideas route around that, offering a POST and redirect alternative to  PATCH + client-generated id.

**Comment by dgeb** [comment]
We'd like to move discussion of specific extensions over to http://discuss.jsonapi.org/

We're closing all extension proposals here, but tracking them over in #794 so none slip through the cracks. We'll be revisiting extension proposals after 1.1 once we land support, in accordance with [our roadmap](http://discuss.jsonapi.org/t/json-api-weekly-meeting-june-22nd-2015/23).
