### ISSUE TITLE
Should the url shorthand nest the links under the resource name when there's a top level links object?

### ISSUE THREAD

**Issue by barelyknown** [json-api/json-api#77]
The docs currently give this example:

```
{
  "links": {
    "posts.comments": "http://example.com/posts/{posts.id}/comments"
  },
  "posts": [...]
}
```

It seems like it would be easier to parse and more obvious if the templates were nested under the relevant resource name.

```
{
  "links": {
    "posts": {
      "comments": "http://example.com/posts/{posts.id}/comments"
    }
  },
  "posts": [...]
}
```

Is there a reason to use the {resource_name.association_name} format as the key instead?

**Comment by kwakwaversal** [comment]
I had the same thought when reading through the json API documentation. The thing that made me realise that "posts.comments" was just as good as "posts->comments" is you still need to write something to parse and replace "posts.id" in the URL shortcut anyway.

**Comment by steveklabnik** [comment]
Agreed. This hasn't been an issue in practice.

**Comment by wycats** [comment]
The reason I originally included the templates at the top level is caching: you can cache the individual resources without details that will be the same across all resources of a type, and just add in the necessary templates when you build the entire payload.
