### ISSUE TITLE
Callbacks Extension/Support

### ISSUE THREAD

**Issue by badosu** [json-api/json-api#774]
Hello, I am implementing jsonapi for my application and there's one part where I want to know if there's a convention/extension/set of ideas:

This application has a type which has many states, let's call it `articles` just for the sake of clarity. The starting point is when the client `POST /articles`  to create a new one (like specified on jsonapi).

Now, there will be a state machine in which the article can pass through many states, e.g.: `drafted`. `published`, `closed`, etc... And for each of these transitions I want to notify the client, sending additional data.

Is there a use case or any discussion about this related to jsonapi?

Possibly related: https://github.com/json-api/json-api/issues/247

Thanks!

**Comment by ethanresnick** [comment]
> And for each of these transitions I want to notify the client, sending additional data.

Do you want the client to receive state changes on all articles, or only ones it specifically requests to listen to?

**Comment by badosu** [comment]
@ethanresnick That's a good question. I have multiple clients in which the majority will not need this feature.

Maybe a solution for this would be to have an (optional) indication of the callback URL on the resource creation?

This would be per resource (article).

**Comment by ethanresnick** [comment]
Ok, here's what I'd do:

Create a collection/resource type called `"listeners"` and have the client POST to that to register its callback. Something like:

```
POST /listeners

{
  "data": {
    "type": "listeners",
    "attributes": {
      "url": "http://uri-that-client-wants-called.com/...",
    },
    "relationships": {
      "subject": {
        "data": {
          "type": "articles", 
          "id": "id-of-the-article-the-client-is-listening-about"
        }
      }
    }
  }
}
```

By defining each listener as its own resource, the client can remove a listener with a standard DELETE request, edit it with a PATCH, etc. It's then your choice how to connect the listener to the resource it's about. (Here, I've created a `"subject"` relationship on `"listeners"`—which could be renamed `"subjects"` if each listener can be used for more than one resource—but you could just as easily do the reverse and create a `"listener"` relationship on `"articles"`.)

You'll note that adding a listener does take a separate request (i.e. it can't be created from scratch with the article POST), but this may be solved down the line by #536. And, for now, I don't think it's that big a burden.

**Comment by badosu** [comment]
I like this idea, is there any restriction on why I can't just use the `relationships` field of the resource POST?

Also, although this is an elegant solution for when all resources share the same callback url, it fails if the client wants to receive a token or a specific url per resource.

**Comment by ethanresnick** [comment]
> I like this idea, is there any restriction on why I can't just use the relationships field of the resource POST?

You can, if the listener's already been created, but that initial creation is still another request. See #536.

> Also, although this is an elegant solution for when all resources share the same callback url, it fails if the client wants to receive a token or a specific url per resource.

Just create one listener resource for each callback url :)

**Comment by badosu** [comment]
So, the problem is that it's very important for me that I can use just one request. It has been already difficult to establish the use of jsonapi with my client, and I don't know if I'll be able to push the need for another request.

In this case I could circumvent this issue by simply associating an attribute for each resource and receiving this attribute on the resource creation. It's not like I disagree with the `listeners` model, but it's simply not feasible for me to have 2 requests for a single successful resource creation.

**Comment by gr0uch** [comment]
Why not use the `meta` key for this use case?

**Comment by ethanresnick** [comment]
Yes, you could definitely put the contents of the proposed `listeners` resource as an attribute of the article instead (though this has some limitations around adding multiple listeners to the same article). You could also use `meta` as @daliwali suggests--that might be the best answer if multiple requests are out of the question.

**Comment by badosu** [comment]
Hmm. I'll consider using `meta`, it pretty much solves my problem. And I'll have just one listener.

I'll still ponder whether I'll use this as a resource attribute or as a `meta` object, since I'll probably have to write this attribute to the model anyway.

Thanks for the help!

Also, regarding the callback requests themselves, I guess they'll be pretty much like jsonapi but in the reverse?

E.G.: Each article status transition will be a PATCH sending the attributes in `vnd.api+json`?

**Comment by ethanresnick** [comment]
I'm gonna give this a close, as the existing options have already been outlined. As I mentioned earlier, we're discussing extensions now in #795 to make this even easier. Here's how it would work with my proposal from #795:

```
POST /articles

{
  "data": {
    "type": "articles",
    "relationships": {
       "listeners": { "data": [{ "pointer": "/embedded/0" }] }
    }
  },
  "embedded": [{
    "type": "listeners",
    "attributes": { "callback-uri": "http://example.com/" }
   }]
}
```

This is, of course, also easily doable with the operations proposal in #795.

**Comment by badosu** [comment]
ok, thanks!
