### ISSUE TITLE
question: using factories to create jsonapi style json

### ISSUE THREAD

**Issue by danielspaniel** [json-api/json-api#775]
I have a project that is used to create json from factories for making testing ember-data/ember applications easier  .. ( ember-data-factory-guy )  but I have been thinking that it could expand to be used for orbit/ember apps or other jsonapi compliant front end applications. 
 Do you think that would be useful? Would it be used? Is there something else out there doing the same thing that orbit/jsonapi front end users are using?

**Comment by tkellen** [comment]
I think this sounds great @danielspaniel! If you build something like this, please feel free to open a PR adding a link to our implementations page (under a new heading called "testing" or something similar).
