### ISSUE TITLE
Organizational: expectations for future releases

### ISSUE THREAD

**Issue by hhware** [json-api/json-api#780]
Inspired by https://github.com/json-api/json-api/issues/684#issuecomment-110431886: it would be great to have a bit more visibility into the plans/expectations/schedule/whatever for future releases of JSON API. It is a very practical question for those of us who are involved in development of commercial applications using JSON API and therefore might need to coordinate development schedules of those applications with availability of new features in JSON API.

**Comment by beauby** [comment]
+1

**Comment by ethanresnick** [comment]
A very rough roadmap is [here](http://discuss.jsonapi.org/t/json-api-weekly-meeting-june-22nd-2015/23). Basically, the plan for 1.1 is to introduce an extension system and a mechanism form creating multiple related resources at once. That'll hopefully be done by September 30. Then hypermedia stuff (e.g. entry point design, RFC 5988 links, custom actions) will be the goal for 1.2.

@tkellen @dgeb Any preference for whether/where we should put the roadmap on jsonapi.org? Maybe on the homepage above the update history, or on the about page somewhere?

**Comment by tkellen** [comment]
@ethanresnick I'm game to have the major features for the next two planned versions on the home page. Would you be up for adding it?

**Comment by ethanresnick** [comment]
@tkellen sure. Although now that we have the roadmap on the about page, putting it on the homepage too seems a bit redundant. I'll submit a PR to add a bit more to it on the about page though

**Comment by lode** [comment]
Is there an up-to-date roadmap, or mainly expectations of that. Is the spec dying because it's hard to keep BC with new features? Or because the core team is having other priorities in life? No hard feelings btw, just that it would be nice to know if this is a standard I can build upon for the future.

**Comment by philsturgeon** [comment]
Hey there, it seems like all roads point here. 

I'm interested in links being expanded from beyond href+meta to being actually useful. Method, fields, etc support is important for making Hypermedia actions available beyond forcing people to OPTIONS on a string and see which method is possible. That's not enough.

Be it like Siren, or be it RFC 5988, or whatever, can we work out a plan?

We're certainly a long way past September 30th 2015, and v1.1 isn't done. Is links still on the roadmap for v1.2? Where do I sign up to help. :)
