### ISSUE TITLE
Long running jobs or asynchronous processing

### ISSUE THREAD

**Issue by benoittgt** [json-api/json-api#781]
Hello

I was wondering if it's plan to write specs when doing [asynchronous processing](http://farazdagi.com/blog/2014/rest-long-running-jobs/).  Maybe it's completely irrelevant..

If not, will love to discuss about it : 
- Posting return :

``` json
HTTP/1.1 202 Accepted
Location: http://example.com/photos/queue/5234
Content-Type: application/vnd.api+json
```

Does response need a body with more informations ? Seems enough for me.
- Get status

``` json
HTTP/1.1 200 Ok
Content-Type: application/vnd.api+json

{
  "links": {
    "self": "/photos/queue/5234"
  },
    "data": {
      "type": "queue job",
      "id": "5234",
      "status": "Process failed, see errors",
      "errors": [
      {
        "code": "too_long",
        "field": "/photos/title"
      },
      {
        "code": "invalid_format",
        "field": "/photos/file01"
      }
      ]
    }
}
```
- If success 

``` json
HTTP/1.1 303 See other
Location: http://example.com/photos/4577
Content-Type: application/vnd.api+json
```

Thanks in advance. 

PS: This post is now on [discourse](http://discuss.jsonapi.org/t/long-running-jobs-or-asynchronous-processing/26).

**Comment by steveklabnik** [comment]
> PS: This post is now on discourse.

Yup, that's more appropriate, so closing.
