### ISSUE TITLE
How I can implement really big query to fetch a collection?

### ISSUE THREAD

**Issue by DenisIzmaylov** [json-api/json-api#784]
Hi,
I would like to fetch a collection of big resources (over 50+ attributes). It's clean that I could not apply full filter (i.e 30 pairs of key-value) in query. How we can solve this issue?
1. Place the query to GET-request body?
2. Use POST method (which isn't correct according RESTful semantic)?

P.S. We can't to reduce and re-align attributes of this resource or change its structure.

**Comment by ksimka** [comment]
>  It's clean that I could not apply full filter (i.e 30 pairs of key-value) in query

Why? And what's wrong with simple GET request?

**Comment by DenisIzmaylov** [comment]
30 pairs which look like:

```
"something-big-group": {
  "first-something-big-attribute": "some-big-value",
  "second-something-big-attribute": "some-big-value",
// ..
},
// ...
```

If we place it at HTTP Query it will be hard to read, debug, etc.

**Comment by ksimka** [comment]
Do you really need names that big? "I" in "API" stands for "interface", you can do it like you want. You doesn't have to use the same names as in your code, it's not RPC.

And BTW

```
"something-big-group": {
  "first-something-big-attribute": "some-big-value",
  "second-something-big-attribute": "some-big-value",
```

Is it attributes (response) or query parameters (request)? (to be sure I got it right)

**Comment by gr0uch** [comment]
Are all of the parameters arbitrary? You could probably implement some custom logic on the server that responds to the `filter` query since that is very underspecified.

**Comment by DenisIzmaylov** [comment]
That's all is attributes. It's collection of resources which could look:

``` javascript
{
  "data": [{
    "type": "monthly-analytics-reports",
    "id": 1,
    "attributes": {
      "something-big-group": {
        "first-something-big-attribute": "some-big-value",
        "second-something-big-attribute": "some-big-value",
        // ... and more than 20 attributes 
      },
      // ... and more than 3 same groups
    }
  }]
}
```

**Comment by DenisIzmaylov** [comment]
So and imagine, we have to filter collection by one, or some, or all of those attributes. How we can implement it?

**Comment by ksimka** [comment]
By "filtering" do you mean http://jsonapi.org/format/#fetching-filtering or maybe http://jsonapi.org/format/#fetching-sparse-fieldsets ?

If the first one, then

```
Note: JSON API is agnostic about the strategies supported by a server. The filter query parameter can be used as the basis for any number of filtering strategies.
```

so do it as you see it. I.e., create a number of presets, one preset = bunch of attributes to filter.

If you mean "sparse fieldsets", and you want to minimize request weight, then you have to analyze, what's bigger: request with loooong query string or full response without.

**Comment by DenisIzmaylov** [comment]
According [this discussion](http://dret.typepad.com/dretblog/2007/10/http-get-with-m.html) we can send JSON body in GET requests.
If we look at [Elasticsearch API](https://www.elastic.co/guide/en/elasticsearch/reference/1.3/search-request-body.html) we can found more reasons to do it.

**Comment by DenisIzmaylov** [comment]
Anybody here?

**Comment by tkellen** [comment]
JSON-API does not specify support for filtering from data in the request body. I concur with @ksimka's suggestions for how to deal with this problem. Additionally, it would be very easy to transform the data structure you're describing into a valid query string--I don't see where the conflict is here.

I'm going to give this a close for now--if you'd like to propose a new feature for JSON-API, please open a focused PR that describes the feature and suggests new requirements for the specification. If you have more general questions, please consider creating a thread at http://discuss.jsonapi.org

Thanks and good luck!

**Comment by ethanresnick** [comment]
I agree with @tkellen. I'd just add that if you really can't use a query string, you could, as a JSON API compliant workaround, POST a query to a `/queries` resource and have it redirect (303) to a short URI representing just those results, and then you could `GET` that URI, with all the proper semantics/cacheability that GET affords. (You would have to do more work on the server, though, to keep track of what query each URI maps to.)

Imagining that your resources are of type "abcs", this would look something like:

```
POST /queries-for-abcs
Content-Type: application/vnd.api+json

{
  "data": {
     "attributes": {
        "equals": {
          "first-something-big-attribute": "some-big-value",
          "second-something-big-attribute": "some-big-value"
        }
     }
  }
}
```

Then the server responds

```
HTTP 1.1
303 See Other 
Location: http://example.com/abcs/from-query-1897jrnshkxinjdbs
```

And then a `GET /abcs/from-query-1897jrnshkxinjdbs` would return just the resources you're looking for.

**Comment by DenisIzmaylov** [comment]
Nice advice @ethanresnick! I already think in this way. But your idea of redirect (303) looks really great! Thank you very much.
