### ISSUE TITLE
Where's the test suite being assembled?

### ISSUE THREAD

**Issue by kevmoo** [json-api/json-api#789]
`...but a test suite is now being assembled to vet them.` - http://jsonapi.org/implementations/

**Comment by tkellen** [comment]
https://github.com/endpoints/endpoints/pull/125

**Comment by tkellen** [comment]
Please feel free to open issues over @ endpoints for this!

**Comment by gr0uch** [comment]
There's [tests here as well](https://github.com/fortunejs/fortune/blob/master/test/integration/serializers/json_api.js).

**Comment by kevmoo** [comment]
@tkellen @0x8890 Will https://github.com/endpoints/endpoints be the **canonical** local for tests?

That should be documented as part of `json-api`. Having a model for interop testing is as important – arguably more important – than the spec.

**Comment by tkellen** [comment]
We're currently developing the integration suite against endpoints using https://github.com/json-api/json-api/blob/gh-pages/normative-statements.json. Once this is complete, we'll move it out to json-api and figure out how we can generalize it far enough to be pointed at any API. One hitch is that implementors will need to use http://github.com/endpoints/fantasy-database for their API. We don't support hypermedia quite well enough for the integration suite to be entirely generic.

**Comment by kevmoo** [comment]
@tkellen Great news.

I don't mind having to run tests with nodejs against my own impl.

**Comment by kevmoo** [comment]
@tkellen Could we make this bug – or another – a tracking issue for tests? Call it an "enhancement request".

**Comment by gr0uch** [comment]
It would not be too difficult to generalize testing, the implementation would just need to be aware of what types will be used for testing. 

This is how I implemented tests:
1. Create all resources by posting to the API.
2. Run test.
3. Delete all resources by making delete requests. Repeat.

Note: not all tests need to run/pass, depending on the implementation.
