### ISSUE TITLE
Usecase of type on the primary resource?

### ISSUE THREAD

**Issue by mkroeders** [json-api/json-api#790]
What is the use case for the `type` on the primary resource?
1. A simple check you hit the right endpoint;
   ie. You create a resource on `/areas` while you submit the type `account` so you get a `409` wrong type.
2. An usefull tool to make "subtypes";
   ie. You have the endpoint `/areas` you get multiple resources back, and the first one is a type country, and the second a type state.
   No I already say subtype so it should probably be a `attributes.subtype`. But then I have every where the type `areas`.

So what is the usefulness of adding to all the primary resources a type, if it should be all the same?

**Comment by bintoro** [comment]
The name of the endpoint doesn't necessarily match the type of the resources it exposes.

**Comment by mkroeders** [comment]
Is the case I used in 2 a valid one, `/areas` which returns the type `country` & `state` for example. Or do you mean something else?

**Comment by bintoro** [comment]
@mkroeders Yeah, exactly. Collections are allowed to be heterogeneous, i.e., composed of resources of various types.

**Comment by tkellen** [comment]
Closing this as resolved, thanks @bintoro!
