### ISSUE TITLE
Allow "type" and "id" attributes

### ISSUE THREAD

**Issue by janko** [json-api/json-api#799]
The [Fields](https://github.com/json-api/json-api/blob/625c32dd60634a818d5a7e257a8799478a4d29b8/format/index.md#fields-) subsection says the following:

> Fields for a resource object **MUST** share a common namespace with each
> other and with `type` and `id`. In other words, a resource can not have an
> attribute and relationship with the same name, **nor can it have an attribute
> or relationship named `type` or `id`**.

The last part for me feels contradictory to the reason why the `attributes` key was brought in in the first place. I thought that now resources _can_ have an attribute called "type", because attributes are now separated in their own JSON object.

I think it's safe for us to allow both "type" and "id" to be in `attributes`, and this would be very useful especially because "type" is a very common database column name. It would be unfortunate to have to change the column name because of serialization technicalities (or not change the column, but then serialization becomes more complicated because you have to specially handle that field not being named the same as the corresponding column).

**Comment by dgeb** [comment]
Because fields share a common namespace with each other and with `type` and `id`, there can't be any overlap. Reusing `type` or `id` within attributes would cause confusion in situations where fields are referenced outside of their structure. For instance, the following request to sort by `type` would be ambiguous:

```
GET /things?sort=type,name
```

This is the same reason that attributes and relationships can't share names.

The primary benefit offered by nesting `attributes` is that it allows for extensibility, since the spec fully defines all the members at the root-level of a resource.

**Comment by ksimka** [comment]
> I think it's safe for us to allow both "type" and "id" to be in attributes

@janko-m, I agree about 'type', but why 'id'? If you have 'id' in attributes, then you must just extract it to the root-level 'id'. It's weird to have 'id' here and there with the different meanings. 

@dgeb, I think your example with 'sort' and 'type' is not good enough as of

> Note: Although recommended, sort fields do not necessarily need to correspond to resource attribute and association names.

And besides, isn't it strange to sort by 'class name' or 'model name'?

Anyway, I think 'type' could be used as attribute. But for consistency it's better not to.

**Comment by dgeb** [comment]
> I think your example with 'sort' and 'type' is not good enough

Now that the spec is at 1.0 and not changing, this will have to remain a difference of opinion.

> And besides, isn't it strange to sort by 'class name' or 'model name'?

It seems reasonable to me to want to sort a heterogeneous collection by `type`.

> I think 'type' could be used as attribute.

This would not be compliant.

**Comment by janko** [comment]
@ksimka Yeah, I also don't really think "id" should be treated the same, I just included it for consistency.

@dgeb Thank you for the answer. Yeah, it makes sense to sort by "type". I also don't have to strictly follow JSON API in my application, if diverging would have benefits, which in my case does.

**Comment by gr0uch** [comment]
> I also don't have to strictly follow JSON API in my application, if diverging would have benefits, which in my case does.

I'm curious if people take JSON API as a starting point for an ad-hoc implementation, as most of its value is in strictly following the spec. If implementations differ greatly then the spec is not that useful.

**Comment by janko** [comment]
@0x8890 I completely agree with you, I would only diverge a bit; @dgeb said that `GET /things?sort=type` would be ambiguous, so in my application I can just remove the ambiguity by stating that in this case `type` will be a database column, and not the type of the resource. Also, I don't support sorting in my app (in the spec the feature of sorting is a **MAY**, so it's good), and I don't see where else it would cause problems. Anyway, just my special case :)

**Comment by ksimka** [comment]
@janko-m, not only your special case ;)

**Comment by janko** [comment]
@ksimka @0x8890 I actually realized now that in my tests it becomes a problem when I have a `type` attribute (I'm writing some testing helpers for more easily asserting JSON responses, and it's a problem when I want to flatten out JSON objects), I really see now why it's better to not have that field, so I will switch to `kind` or `category` after all.

**Comment by mfn** [comment]
We were hit with that issue too today; quite a bummer IMHO.

Especially when connection a perfectly valid existing Schema to the API, this needs workarounds/hacks to overcome so that the spec isn't violated.
