### ISSUE TITLE
When is data required in relationships?

### ISSUE THREAD

**Issue by krzkrzkrz** [json-api/json-api#803]
At the doc at http://jsonapi.org/format 

Sometimes, you will see `data` in the `relationships` and sometimes not. Is `data` required? If so, all the time or situational?

Take for example:

```
    "relationships": {
      "author": {
        "links": {
          "self": "http://example.com/articles/1/relationships/author",
          "related": "http://example.com/articles/1/author"
        },
        "data": { "type": "people", "id": "9" }
      },
```

And:

```
    "relationships": {
      "author": {
        "links": {
          "related": "http://example.com/articles/1/author"
        }
      }
    }
```

**Comment by jamesplease** [comment]
@krzkrzkrz based on [this part of the spec](http://jsonapi.org/format/#document-resource-object-relationships) it seems optional.

> A "relationship object" MUST contain at least one of the following: `links`, `data`, `meta`.

(slightly paraphrased). So if I'm interpreting it correctly then only one of them is necessary.

**Comment by krzkrzkrz** [comment]
@jmeas what would `data` be used for in the `relationship` context?

**Comment by jamesplease** [comment]
I didn't know, so I followed the link under `data` in the link I sent above, and [it sent me here](http://jsonapi.org/format/#document-resource-object-linkage). Have you read that section?

**Comment by tkellen** [comment]
Data is not required. For to-one relationships like the author of an article, you'd see it always, but for to-many relations like comments, you would not see it unless you explicitly included them. (e.g. `GET /article/1?include=comments`). In this case, you can "dereference" the data in the comments relationship by matching it up with entries under the top level `included`.

**Comment by tkellen** [comment]
Our issue tracker is for website changes, discussing internal inconsistencies with the specification, or discussing features on our roadmap. In the future, could you please open issues like this on http://discuss.jsonapi.org/?

I'm going to give this a close but I'd be happy to discuss this further here if needed.
