### ISSUE TITLE
ID Alias

### ISSUE THREAD

**Issue by IsaiahJTurner** [json-api/json-api#810]
What is the best way to handle multiple IDs that reference the same object? For example, usernames may be case insensitive and ignore dots and dashes but that user should also be queryable by their ID. For example, Twitter allows case-insensive queries for a user ID or a username. How could I accomplish this with JSON API?

**Comment by jamesplease** [comment]
Maybe [the `filter` query param](http://jsonapi.org/format/#fetching-filtering) could be used as the foundation for adding somethin' like this to your API?

**Comment by steveklabnik** [comment]
Would you mind posting this on http://discuss.jsonapi.org/ please? it's better for these kinds of 'how do I use' questions. Thank you!
