### ISSUE TITLE
JsonSchema doubts!!

### ISSUE THREAD

**Issue by fearzendron** [json-api/json-api#811]
Hello guys, just for curiosity, what are the differences between this json-api pattern and JsonSchema? I'm asking this because I'm using a backend dolution called Anypoint that validates all models with JsonSchema and for the front-end I'm using Ember that follows the Json-api. 

thanks!

**Comment by steveklabnik** [comment]
Discussion questions are best asked over at http://discuss.jsonapi.org/, please post this there, thank you!
