### ISSUE TITLE
Padding between menu and content

### ISSUE THREAD

**Issue by DaleGardner** [json-api/json-api#816]
There should be some padding between the menu and the main content. :shirt: 

![jsonapi-padding-1](https://cloud.githubusercontent.com/assets/3970939/8890450/769579a0-32cf-11e5-881a-6886bbf636be.PNG)

![jsonapi-padding-2](https://cloud.githubusercontent.com/assets/3970939/8890451/79afc190-32cf-11e5-8d41-0610282542c2.PNG)

**Comment by jamesplease** [comment]
What browser are you viewing the site in? I see this:

<img width="997" alt="screen shot 2015-07-25 at 2 49 56 pm" src="https://cloud.githubusercontent.com/assets/2322305/8890817/7a255f6a-32dc-11e5-8b0f-8b628d3db203.png">

**Comment by DaleGardner** [comment]
Google Chrome Version 44.0.2403.107 m (64-bit)

Also the same for: Mozilla Firefox Developer Edition 41.0a2 (64-bit)

This is on Windows 7. The font is probably slightly different for you, which causes it to hit the next line (as you can see from my screenshots, it is right on the absolute edge). I've run into similar font issues recently on a few different projects, with Mac and Windows being slightly different.

In any case, I can assure that there is no padding at all between the menu and the content. Which means, depending on where the words break, it can butt up right against the content.

**Comment by jamesplease** [comment]
> In any case, I can assure that there is no padding at all between the menu and the content.

Yup, you're def. right. This should be changed!

:+1:

**Comment by tkellen** [comment]
Thanks Dale!
