### ISSUE TITLE
Singular resources as array are not a good fit for ActiveResources's find()

### ISSUE THREAD

**Issue by hoetmaaiers** [json-api/json-api#82]
When following the JSON API document, I return my singular resources in an array as described:

```
{
  "designs": [
    {
      // individual design
    }
  ]
}
```

My app talking to the API uses ActiveResource. When I do a find in ActiveRescource

```
Api::Design.find(10)
```

I get the following error:

```
ArgumentError: expected an attributes Hash, got [{"id"=>10, "title"=>" ...
```

ActiveResource seems to have trouble with return singular resources as an array.
Any thoughts or help on this?

**Comment by steveklabnik** [comment]
ActiveResource does not work with JSON API.

**Comment by hoetmaaiers** [comment]
No need to worry about JSON API while working on ActiveResource then?

Is there an important thing I'm missing? Iis ActiveResource made with other principles in mind? Do you have knowledge what direction ActiveResource is about to go? (I realize it's more a question for the AR project).

**Comment by steveklabnik** [comment]
> Is there an important thing I'm missing? 

I feel the same, to be honest. ActiveResource has its own format, it has nothing to do with JSON API. They could support it, if they wanted to, but I'm not aware of any efforts to do so at this time. You should ask them over on their tracker, they'd know better than I do.
