### ISSUE TITLE
File uploading

### ISSUE THREAD

**Issue by ShogunPanda** [json-api/json-api#821]
Hi all.
In the specification I read (and implemented) that the `Content-Type` header for both client and server **MUST** be `application/vnd.api+json`.

Now, here's my question. When I'm uploading a file along with a JSON document, the only content-type I can foresee to use is the `multipart/form-data`, which seems to be conflicting with the specs.

Am I thinking it wrong? How can I fix this problem?
Bye!
  Shogun

**Comment by tkellen** [comment]
Can you please open this issue @ http://discuss.jsonapi.org? Our issue tracker can always be used to address internal inconsistencies within the current specification, or updates to the website. Beyond this, we try to limit discussions to those which focus on problems that will be dealt with in the next version of JSON API.

As a quick answer, you might consider base64 encoding your binary data and sending it with the rest of your payload.

**Comment by ShogunPanda** [comment]
Done: http://discuss.jsonapi.org/t/file-uploading-with-multipart/71 :)
