### ISSUE TITLE
Missing examples for filters

### ISSUE THREAD

**Issue by bpinney** [json-api/json-api#822]
The **Recommendations** section on filtering (http://jsonapi.org/recommendations/#filtering) has sentences that allude to examples, but there are no examples listed in the section.  Please add some examples.

**Comment by bf4** [comment]
Would you help me understand what sorts of examples you're looking for? :)

**Comment by ethanresnick** [comment]
ref https://github.com/json-api/json-api/issues/389, since, if we're going to clean up these examples, we should probably deal with the missing type too

**Comment by bpinney** [comment]
Looks like examples are now given.  Thanks.
