### ISSUE TITLE
Missing examples / guides for non-resource data

### ISSUE THREAD

**Issue by lukasoppermann** [json-api/json-api#823]
For e.g. I want to return the oauth access token and I am puzzled how to do it correctly. Treating it as a resource seems wrong, I don't want to return an Id for the token. Is it correct, to ignore the jsonapi format for this? How would I format it otherwise?

**Comment by tkellen** [comment]
Our issue tracker is for addressing inconsistencies and enhancements to the specification. Can you please open this discussion @ http://discuss.jsonapi.org?

Thanks!

**Comment by lukasoppermann** [comment]
Sure, thanks for the tip.
