### ISSUE TITLE
Who is using JSON-API?

### ISSUE THREAD

**Issue by tkellen** [json-api/json-api#825]
We would like to gather a list of projects/companies using this specification for the website.

Please post here and let us know if your project/company uses json-api and wouldn't mind being mentioned. A logo with a link to the project and a short description of how you are using json-api / how it has helped would be awesome. If the code is open source, please link to that too!

**Comment by scott-mcdonald** [comment]
@tkellen 

Tyler. I am the solution architect/lead here at movietickets.com and I pitched the idea of adopting json:api as our hypermedia JSON based response standard for our greenfield "Level 3 REST API" which was accepted by the company. We are using it to power our new JSON based hypermedia API to deprecate our older WCF SOAP based services. We do not have a "developer" portal yet and might not for awhile so it is **not** accessible from the outside. 

I believe we would not have any problem in the website mentioning us. Let me know what you need, logo, my pitch to the suits, etc.

Scott McDonald

**Comment by tkellen** [comment]
Hey @scott-mcdonald! Thanks so much for responding :smile:. As much as you'd be willing to share would be valuable. Posting links to logos or just embedding them right in the thread would be awesome.

**Comment by scott-mcdonald** [comment]
@tkellen Tyler, I talked to our CEO and he has given approval to use our movietickets.com logo for companies using json-api but there are some legalese restrictions he wants in place which is standard fare for this type of stuff. I am going to email you directly and give you his email address as our CEO wants to know for himself how you are going to use the logo etc before he signs off on it. Can you simply send an email to him on exactly how you intend to use the logo so he can approve and sign off on it...

Scott McDonald

**Comment by jeremiahivan** [comment]
@tkellen Rent the Runway is beginning to roll out JSON-API in our production site. The first items are live now. Our goal is to standardize on this specification for our client facing API. We'd be happy to share promotional material and happier still for our developers to work openly with you to improve. Please reach out for any questions and collaboration.

**Comment by kfriedman** [comment]
@tkellen 

I'm a developer at the New York Public Library and we're using JSON API for most of our apps going forward (http://www.nypl.org/blog/2015/07/14/unit-testing-angular-js) and to power the website redesign currently underway (http://www.nypl.org/blog/2015/06/15/transformation-nypl-website). 

Our devs have also written two JSON API parsers:

Node:
https://github.com/EdwinGuzman/parserinator

Ruby:
https://github.com/seanredmond/subjoin

**Comment by dylnslck** [comment]
@tkellen 

I'm leading the development of a few early-stage startups (www.truprice.healthcare, www.getladdr.com, and www.amplebiometrics.com). We love Ember, so I've been working on a JSON API Node driver https://github.com/dcslack/restle to knock all these out at once.

**Comment by Majstore** [comment]
Hi, we are starting implementation of JSON API based .NET Web API 2 implementation in company I am working for (www.soprex.com) and will use it in some of our projects. We are using Sencha's ExtJS platform as frontend , and soon we will set git project for ExtJS implementation which will serialize/deserialize messages and dynamically creating models. 

We are waiting for some updates of JSON API which will give us support for resource behaviors (actions) and resource descriptions (profiles).

**Comment by Jeehut** [comment]
Hi, I am using the [jsonapi-resources](https://github.com/cerebris/jsonapi-resources) gem for my open-source **movie discovery app** that will be available under movie-assistor.com (preview under [develop.movie-assistor.com](http://develop.movie-assistor.com)) – here's the [GitHub project](https://github.com/Flinesoft/MovieAssistor) of the backend. Love to inform you once it's live!

**Comment by tsteuwer** [comment]
The company I work for is using it for a reporting project.

**Comment by SimonKaluza** [comment]
We're using it at inboxhealth.com for both our internal and external APIs.  We consume it via Ember Data.  We're still halfway done with some of the error handling the standard recommends (we don't use the pointers correctly at the moment) and have some of our own customized pagination implemented, but JSON API provided a great formal starting point for us.

**Comment by gr2m** [comment]
[Hoodie](http://hood.ie/) will use JSON API in its Account Module in the upcoming version:
- http://docs.accountjsonapi.apiary.io
- https://github.com/hoodiehq/hoodie-server-account
- https://github.com/hoodiehq/hoodie-client-account

**Comment by AlexParamonov** [comment]
@tkellen does pre stable json api versions count? We use older specification of json api.

**Comment by tkellen** [comment]
Sure do!

**Comment by AlexParamonov** [comment]
We are using pre-stable json api here: https://www.malimar.tv/
It was a great boost to us while developing: stick to standardized document helped to avoid doubts on api format.

**Comment by toobulkeh** [comment]
still under consideration at https://github.com/thoughtbot/guides/pull/365

We are trying out json-api at [Vaporware](http://vaporwa.re/) for a currently unannounced client. So far, so good. Thank the Ember guides (and by extension, community) for bringing us to your efforts.

We're also documenting the API using [APIary](https://apiary.io/) and by extension are limited to the [APIblueprint](https://apiblueprint.org/) documentation specification.

Finally, we found this issue via a [good discourse post on current efforts by Hoodie](http://discuss.jsonapi.org/t/example-json-api-for-accounts/234/7).

Thanks everyone for their contributions thus far!

**Comment by ctolsen** [comment]
@tkellen we at [Lystable](http://www.lystable.com) are using json-api for, well, everything. We have a Flask backend and a React.js frontend and tooling on both ends to support the standard, and it's also used to communicate between backend resources. json-api has definitely succeeded in its primary mission of anti-bikeshedding for us and is helping resolve bigger architectural considerations as well.

Nothing is open source as of yet, as most of our implementation is basically wrappers around existing stuff. But my hope is that we will do so when we have a more stable framework.

**Comment by AlexParamonov** [comment]
@ctolsen what do you use on front end together with React? Do you use open source library?

**Comment by chrisui** [comment]
@AlexParamonov We have some home-grown utilities for interacting with our json-api layer and storing data within redux-powered state. Nothing open source yet but would love to in the future :)

Edit: Should clarify I'm from Lystable!

**Comment by 21echoes** [comment]
[Patreon](patreon.com) is using JSON-API and loving it so far! Top benefits would probably be:
- easy answers for on-boarding
- easy answers for new feature development (every API question's first answer is "well what does jsonapi.org say?)
- pretty extensive use case coverage is nice, as well -- already having related resource, sparse fieldset, sorting, and pagination specifications and/or recommendations makes everything so easy to keep clean & consistent.
- lots of open source tools and snippets that leverage the standard, so less time writing serializing/deserializing libraries, more time actually developing :D

Logos can be found here: https://www.patreon.com/toolbox/media

Majority of usage is internal & closed-source, but our alpha clients for public API usage can be found here: 
- https://github.com/Patreon/patreon-python
- https://github.com/Patreon/patreon-ruby
- https://github.com/Patreon/patreon-js
- https://github.com/Patreon/patreon-php
- https://github.com/Patreon/patreon-java

We'll probably be open-sourcing our pretty extensive Flask-JSONAPI integration libraries in a few months (flask.request extensions for pagination, sorting, includes, and sparse fieldset parsing, serializers & deserializers using schema declarations and per-attribute & per-relationship ACLs, etc.)

**Comment by zmeda** [comment]
@tkellen 

We are using it at [Zalando](http://zalando.github.io/). Trying to reach 3. Level in [Richardson Maturity Model](http://martinfowler.com/articles/richardsonMaturityModel.html). 

Content negotiation is "easy". 

HATEOAS is funny. :smile: Therefore we developed the [scala-jsonapi](https://github.com/zalando/scala-jsonapi). Now we are rolling out our RESTful (finally we can proudly use RESTful) APIs. It looks like it is well accepted across our API users.

**Comment by 21echoes** [comment]
Update: We've just open sourced our [python server-side JSON:API library](https://github.com/Patreon/cartographer) (with a few extra optional [Flask](http://flask.pocoo.org/) tools), which makes it really easy to serialize to and parse from JSON:API documents. It's served a few billion requests since we started writing it back during ~JSON:API RC2, so we think you'll enjoy all the battle-tested optimizations and features we've baked in. Of course we're super excited to continue improving it as well, like the upcoming [automatic Flask routing](https://github.com/Patreon/cartographer/pull/16). We'll have a full-on blog post for it soon, but wanted to post a quick note here first!

We've also open-sourced our [iOS JSON:API library](https://github.com/Patreon/Realm-JSONAPI), designed for use with [Realm](https://realm.io/). Blog post also coming soon 😀 

We hope to have our `redux.js` middleware open sourced within the month, and some Android tools as well. Ping me (or those linked repos) with any thoughts! And keep up the awesome work on JSON:API 👍 ❤️

**Comment by cyril-sf** [comment]
Anyone using it for a public API?

**Comment by 21echoes** [comment]
@cyril-sf We are! Well, you need a Patreon account to get an API key, but anyone can set up a Patreon account! And then we have a few open-source libraries that you can use to talk to it (https://github.com/Patreon/patreon-python, https://github.com/Patreon/patreon-ruby, https://github.com/Patreon/patreon-php, https://github.com/Patreon/patreon-js, https://github.com/Patreon/patreon-java, and a wordpress plugin that uses the php plugin under the hood https://github.com/Patreon/patreon-wordpress).

Do you have any specific questions about using it for a public API vs only using it to talk to your own clients? For instance, one more urgent need for public API's is great documentation, which we've been trying to build a good automated JSON:API <=> [Swagger](http://swagger.io/) tool for. What else is on your mind?

**Comment by cyril-sf** [comment]
@21echoes I pinged you on Twitter. Would love to meet you to discuss more about this. I'm in SF too. (how many users of that API, did you get feedback from them about the choice of jsonapi, ..)

**Comment by arteymix** [comment]
I do! http://mirbooking.major.iric.ca/

It even does [MessagePack](http://msgpack.org/) serialization :)

**Comment by adnanoner** [comment]
@zmeda I see that Zalando's guideline's use a subset of hal, could you explain what the thought process was around that, and where you are using the json-api?

**Comment by sirtobey** [comment]
@Majstore Is there any news on your ExtJS implementation?

**Comment by galiat** [comment]
My group at Autodesk does. We wont have a public API (yet) but when we do I'll update with links

**Comment by jrrevy** [comment]
Instagram API also is inspired by JSON API but doesn't seem to be fully compliant (pagination, etc.)

**Comment by vsoroka** [comment]
The [ORO Platform](https://www.orocrm.com/oro-platform) uses JSON API as well.

**Comment by cordovapolymer** [comment]
Hi, we use JSON-API at [Wanna Taxi](https://wanna.taxi), please add our [logo](https://wanna.taxi/images/logo.svg)!

**Comment by postmechanical** [comment]
Is anyone actually actively consuming JSONAPI on iOS clients here?

**Comment by 21echoes** [comment]
Hey @postmechanical! We are at [Patreon](https://www.patreon.com), and we have an open source library that helps us do so here: https://github.com/Patreon/Realm-JSONAPI. It integrates with [Realm](https://www.realm.io), but should have plenty of useful bits you can use even if you don't use Realm.

**Comment by postmechanical** [comment]
Thanks @21echoes but I'm moving away from Objective-C and not using Realm. Not much in that library that's useful to me.

**Comment by wimleers** [comment]
I think it's time to close this issue?

**Comment by postmechanical** [comment]
Went with GraphQL on top of JSON-API and am much much happier with the client side code.

**Comment by alexsabdev** [comment]
These folks 100% use fully compliant JSON:API - https://mobstery.com.

**Comment by DominusKelvin** [comment]
Quru Tech will be implementing JSON:API on all her webservices both open source and for clients as well.

**Comment by radj** [comment]
[Autodesk Forge Data Management API](https://forge.autodesk.com/en/docs/data/v2/reference/http/) is implementing JSON:API.

**Comment by janwerkhoven** [comment]
100% into JSON API

https://interflux.com
https://interflux.group
https://lmpa-q.com
https://jetfluxer.com

⛵
