### ISSUE TITLE
Machine-readable service/resource description link convention

### ISSUE THREAD

**Issue by SphtKr** [json-api/json-api#83]
(This may be a v1.1+ concern, but I think it may be needed.)

At present, it doesn't seem that one of the goals of JSONAPI is for resource representations to be self-describing. That is probably good for simplicity and compactness. But some use-cases would benefit from having a computer-readable service description, including available resources and fields in each resource.

For example, while I'm not a big believer in computer-generated application code, it would be valuable for automatic test generation or for API validation (e.g. if one wanted to specify a common resource model for multiple vendors to implement). Likewise, it might be interesting to be able to generate just the data model code initially from a service description.

Additionally, #20 raises the issue of partially populated records. Unless the data model is explicitly defined in the client, it isn't possible to know when a resource is omitting fields or when they just don't exist. Other use cases that come to mind include resource model versioning, and possibly some of the [polymorphism discussions](https://github.com/json-api/json-api/issues/8#issuecomment-17472105) that have come up (if we don't allow polymorphism specifically in the resources, it might be good to have a place to specify it optionally).

From what I'm reading so far, it seems that the "profiles" capability is primarily intended to be human readable. Or is the intention to have a computer readable form as well? Perhaps different responses to profile URLs based on `Accept-encoding`?

**Comment by steveklabnik** [comment]
> it doesn't seem that one of the goals of JSONAPI is for resource representations to be self-describing. 

I'd like to hear more about this: as far as I know, it is self-describing, and that constraint is important to me.

There's no plans to implement things like JSON-Schema, but there's no reason you couldn't include such things in the meta section if you wanted.

Historically, things with human-readable schemas win over things that are machine-readable. See XHTML vs. HTML for a recent example of this fight.

> From what I'm reading so far, it seems that the "profiles" capability is primarily intended to be human readable.

Yup, profiles are best human-readable in my opinion, but they can be machine-readable as well:

>   Note that, at the same
>   time, it is possible for profile target URIs to use dereferencable
>   URIs and to use a representation (which is outside the scope of this
>   specification) that represents the information about the profile in a
>   human- or machine-readable way.

That'd be how I'd recommend doing it, if you'd like.

**Comment by SphtKr** [comment]
> I'd like to hear more about this: as far as I know, it is self-describing, and that constraint is important to me.

Sure, what I meant by not self-describing stemmed from four things:

First, field/relationship data types. For instance, if a field is null in a resource, it's not apparent whether it is normally a number, string, array, hash/object type, particular class type, or a variant, I suppose. For that matter, whether it should be/is allowed to be null (with the exception of `id`) is not apparent. 

Second is what I mentioned with regards to partial resources (#20): if fields are omitted/excluded from the resource, they likely will be omitted entirely from the serialized object (rather than, say, being included as null, which would be misleading). Therefore, the existence of the field is not apparent to a client.

Third is the polymorphism discussions that have cropped up in a couple of other issues (#28, #8). I can see the argument that trying to communicate polymorphic object types in the resource is not conducive to simplicity and compactness of the resource representation. However, [as I said before](https://github.com/json-api/json-api/issues/28#issuecomment-17657685), the resource representations in one's service _do_ necessarily imply some class model to the client (though _not_ necessarily the same one as is internal to the server). Having a machine-readable "profile" standard would provide a place to express class relationships--_and to specify explicitly when a given resource URL-referenced association could contain multiple object types_ (see the first item, data types).

Fourth is the existence of resources themselves. It would be handy to have a way to make your resource endpoints discoverable. For instance, this might relate well to #13. I'll lump resource versioning in with this item, because my list is already long.

(sorry, that started with two points and ended up as four.)

You may say, "well, this should all go in the `meta` of the resource". Maybe, but that means that you'd be sending a whole lot of information _every time you send a resource_, and possibly many many multiple times if the meta is in the object itself instead of the top level (incidentally, if I read [the writeup on profiles](http://www.mnot.net/blog/2012/04/17/profiles) correctly, you could link a profile from individual objects rather than/in addition to at the top level--so that would potentially address some of the polymorphism concerns as well). On the other hand, if there was a definition available for each resource type, a client would only need pull that information once. Another problem with exclusively using `meta` is the mild paradox it creates: in order to know the meta for the resource/class you want to pull, you have to pull a resource instance first--and you may not know an ID for a record at the time you want to know the structure, among other problems.

And yes, a lot of this is done by manually declaring data structures in the client code. But this has disadvantages also...if I build clients in two languages/runtimes, I have to redefine my boilerplate model definitions in each client--something a client-side library could do for me.

I'm not trying to create WSDL-level support, but I can see use cases where this kind of information would be useful.

**Comment by steveklabnik** [comment]
Yeah, I think all of this comes on a continuum, very similar from static to dynamically typed.

When I hear 'self-described messages' I think of Fielding, which is apparently very different from what you meant. Makes more sense now, thanks for elaborating.

**Comment by SphtKr** [comment]
No problem. Been looking briefly into [JSON Schema](http://json-schema.org), and it might actually be a good fit, rather than inventing something. Will research further.

**Comment by steveklabnik** [comment]
Yup! If you want schemas, that's the standard, for sure.
