### ISSUE TITLE
/format sidebar overflow is not accessible

### ISSUE THREAD

**Issue by ashleygwilliams** [json-api/json-api#831]
http://jsonapi.org/format/ accessed by Chrome Version 44.0.2403.130 (64-bit)

the information in the sidebar on the Format page extends below the window and is not accessbile via scroll. it seems like a result of fixed positioning.

might investigate later and make a PR but s'cool if someone wants to take over before i get to it.

**Comment by wvteijlingen** [comment]
This is a known bug, with one open PR at the moment: https://github.com/json-api/json-api/pull/785. A better solution is always welkome though! :)
