### ISSUE TITLE
Firefox auto-appends media type parameter 'charset=UTF-8'

### ISSUE THREAD

**Issue by jason21000000** [json-api/json-api#837]
The specification states:

> "Clients MUST send all JSON API data in request documents with the header Content-Type: application/vnd.api+json without any media type parameters."

However, I noticed Firefox (I'm using 36.0.4) automatically appends charset-UTF-8 to the request header content-type, even when you explicitly set it to just "application/vnd.api+json"

**Comment by steveklabnik** [comment]
that's not cool :/

**Comment by mvdstam** [comment]
This is a known bug in Firefox:

https://bugzilla.mozilla.org/show_bug.cgi?id=416178

We ran into this issue as well and decided to just relax this specific requirement, since Firefox essentially didn't work with the JSON API for anything other than GET requests.

**Comment by ethanresnick** [comment]
Yeah; I'm not sure what the official JSON API resolution to this will ultimately be, but I agree that just relaxing the requirement (for just the charset parameter) is a good strategy for now.

**Comment by ethanresnick** [comment]
This bug has since been fixed in Firefox, though that fix didn't make it into the main/user-facing build until of FF 43.

**Comment by ethanresnick** [comment]
Closing. This is long fixed in FF, so we don't need to worry about it.
