### ISSUE TITLE
DELETE should delete the thing the URL refers to

### ISSUE THREAD

**Issue by MattSANU** [json-api/json-api#838]
There's an example in this specification that doesn't seem right:

Relationship members are specified in the same way as in the POST request.

In the following example, comments with IDs of 12 and 13 are removed from the list of comments for the article with ID 1:

DELETE /articles/1/relationships/comments HTTP/1.1
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "data": [
    { "type": "comments", "id": "12" },
    { "type": "comments", "id": "13" }
  ]
}

Given the URL supplied, this should be deleting the relationship comments collection from article 1, not deleting two comments.

The spec notes that RFC 7231 permits inclusion of a request body in an HTTP DELETE request, which it does. However, 'resources' are supposed to be identified/located solely by URLs, and DELETE deletes the identified resource, ie what the URL alone identifies.

A similar example request would be correct HTTP if sent to a different URL and if it used method POST not DELETE, eg:
POST /posts/1/comments/actions/delete
id=123

I'm looking forward to using JSON-API, but it's my understanding this makes it not-fully-RESTful. So I'll wait until someone comments on this issue before proceeding.

**Comment by gr0uch** [comment]
I'm not sure if compliance with REST is a goal of JSON API. There are other parts of the spec which are seemingly not RESTful such as optional hyperlinks, which may imply that traversing between resources is based on out-of-band information.

Anyways I think it's too late to make a breaking change such as this.

**Comment by bintoro** [comment]
JSON API and HTTP have different ideas about what "resource" means. An HTTP resource may map to multiple JSON API resources. It's just a terminology issue.

**Comment by steveklabnik** [comment]
REST also says nothing about URLs, HTTP verbs, or anything else like that.

**Comment by gr0uch** [comment]
> REST also says nothing about URLs, HTTP verbs, or anything else like that.

@steveklabnik not sure about that, there is an [entire chapter](https://www.ics.uci.edu/~fielding/pubs/dissertation/evaluation.htm) on how REST relates to the web, ~~but you're right that HTTP verbs are not explicitly mentioned~~ there's also HTTP verbs. The architectural style may not cover implementation details, but it's still an important consideration here.

**Comment by steveklabnik** [comment]
REST itself is chapter 5. Chapter six is evaluating how the web platform stacks up against REST.

(and yeah, I'm not saying it's not important, I'm saying "REST says that this URL should do this with a DELETE" is a category error)

**Comment by ethanresnick** [comment]
I'm gonna give this a close, since we've discussed it in the past (#445) and there wasn't enough resistance to the current approach for us to change it at the time. Maybe in the future we'll add a different alternative and deprecate the current approach, but there's no way to just remove it now that the spec's reached 1.0.

**Comment by MattSANU** [comment]
I understand your reluctance to change this after spec 1.0, but since (as I understand it) this makes JSON-API both non-compliant with RFC 7231 and non-RESTful, it sure would be good to see this not forgotten about. Maybe a possibility for spec 2.0, then?

**Comment by ethanresnick** [comment]
@MattSANU Ok, I'm open to reopening this and leaving it milestoned for a future release. (This has always bugged me a bit too.) What say @dgeb and @tkellen?

**Comment by bintoro** [comment]
HTTP only calls for disassociating the endpoint from its "current functionality" upon DELETE, which arguably is happening when the corresponding resource linkage is modified, no?

**Comment by ethanresnick** [comment]
@bintoro I think it depends how you define "current functionality", but my reading is that the "current functionality" is that of returning the collection of related linkage—and that functionality still remains, even though the members of that collection are different. If we read "current functionality" as you suggest, then any PATCH operation would be ok to do as a DELETE, because it would change the entity (the "current functionality") even though it leaves the conceptual resource intact. That's a reading that's just a bit too lose for me...

**Comment by MattSANU** [comment]
The problem (as I see it) is that the entity that's being modified isn't being identified solely by the URI/URL - it's being identified by a combination of the URI and the request body. Which means that that Uniform Resource Identifier doesn't actually identify the Resource that is the topic of the DELETE request.

**Comment by bintoro** [comment]
@MattSANU, you're conflating HTTP resources and JSON API resources. What HTTP calls "resources" are called "endpoints" in JSON API.

Just consider compound documents. They consist of multiple JSON API resources delivered from a single URI (the HTTP resource). Equating JSON API resources and HTTP resources would make such collections impossible, as there would have to be a one-to-one correspondence between URIs and resources. Therefore, they are not intended to be the same thing. The choice of terminology is unfortunate but pretty much set by now.

**Comment by bintoro** [comment]
> If we read "current functionality" as you suggest, then any PATCH operation would be ok to do as a DELETE

@ethanresnick True, but it's the only way to have DELETE do anything useful.

**Comment by ethanresnick** [comment]
@bintoro There are other solutions, though. Maybe it's coming up with a URI convention for picking out the linkage to DELETE (which could easily work well for up to 20 links). More likely, it's defining a `PATCH` or `POST` alternative for this use case. But, either way, all I'm suggesting for now is leaving this open to discuss more later.

**Comment by dgeb** [comment]
As others have pointed out, in [RFC 7231](https://tools.ietf.org/html/rfc7231) "target resource" means _HTTP resource_. What we're really doing here is identifying _multiple JSON API resources_ within a _single target HTTP resource_ that represents a _collection of JSON API resources_.

RFC 7231 provides a fair bit of wiggle room for server implementations to interpret the effects of DELETE:

> If the target resource has one or more current representations, they
>    might or might not be destroyed by the origin server, and the
>    associated storage might or might not be reclaimed, depending
>    entirely on the nature of the resource and its implementation by the
>    origin server (which are beyond the scope of this specification).
>    Likewise, other implementation aspects of a resource might need to be
>    deactivated or archived as a result of a DELETE, such as database or
>    gateway connections.  In general, it is assumed that the origin
>    server will only allow DELETE on resources for which it has a
>    prescribed mechanism for accomplishing the deletion.

And there is explicit wiggle room left for defining the meaning of the payload:

> A payload within a DELETE request message has no defined semantics; sending a payload body on a DELETE request might cause some existing implementations to reject the request.

@wycats and I felt that we could operate within the wiggle room provided by 7231 to more explicitly and specifically define DELETE for the JSON API spec.

**Comment by ethanresnick** [comment]
P.S. I think one ultimate solution for those concerned about this will be to use whatever format we come up with for PATCH [operations](https://github.com/json-api/json-api/issues/795#issuecomment-132559958). I.e., 

```
DELETE /articles/1/relationships/tags

{
  "data": [{
    "type": "tags", "id": "1"
  }]
}
```

will be rewriteable as something like:

```
PATCH /articles/1/relationships/tags

{
  "operations": [{
    "op": "remove",
    "data": { "type": "tags", "id": "1" }
  }]
}
```

which seems much more compliant to me.

**Comment by MattSANU** [comment]
@ethanresnick Yes, I think that would be much more compliant. I'd consider that a solution to all of the points I raised. I get what you're saying about the different types of 'resource'.

**Comment by MattSANU** [comment]
You could (if you wanted) also have a URL that referred directly to the JSON API resource (not to the collection), in this example to a comment rather than to the collection of comments. At that point, the JSON API resource and the HTTP resource would be one and the same, so use of method DELETE would be perfectly appropriate, and you probably wouldn't need a request body any longer.
