### ISSUE TITLE
Is nesting partial related resources within attributes allowed?

### ISSUE THREAD

**Issue by joostfarla** [json-api/json-api#839]
Say I have a resource URL for retrieving an article. Would it be allowed to include a subset of the related author's attributes in the attributes of the primary data? 

The reason why I would want to do this:
- For the most use cases when retrieving an article resource, the fields `name` and `photo` are all that are needed. However, the author resource contains a lot more properties, but I do not want to include all these properties in the article response.
- I don't want to introduce the "complexity" of matching the right related resource (partial or not) in the 'included' object.

Is this response allowed? Or is there a better way of doing this?

``` json
{
  "type": "articles",
  "id": "1",
  "links": {
    "self": "http://example.com/articles/1"
  },
  "attributes": {
    "title": "Rails is Omakase",
    "author": {
      "name": "John Doe",
      "photo": "http://some-url/to/the/photo"
    }
  },
  "relationships": {
    "author": {
      "links": {
        "related": "http://example.com/authors/12"
      }
    }
  }
}
```

This is related to https://github.com/json-api/json-api/issues/160.

**Comment by ksimka** [comment]
> For the most use cases when retrieving an article resource, the fields name and photo are all that are needed

Use `fields` (http://jsonapi.org/format/#fetching-sparse-fieldsets)

> I don't want to introduce the "complexity" of matching the right related resource (partial or not) in the 'included' object.

Why 'complexity'? You implement json-api only once, then you always can convert json-api format to a plain js object of your choice. Creating additional formats — that's the complexity.

**Comment by joostfarla** [comment]
> Use fields (http://jsonapi.org/format/#fetching-sparse-fieldsets)

In my case, I don't want the client to determine which fields are returned and which are not. These 2 fields should be the default. If they want more, they should follow the related URL to retrieve all attributes.

> Why 'complexity'? You implement json-api only once, then you always can convert json-api format to a plain js object of your choice. Creating additional formats — that's the complexity.

I mean complexity for the client. For a rookie developer, getting `attributes.author.name` is way simpler than iterating through an array of included resources and finding a match by `id` and `type`, which they have to extract from resource identifier objects. Of course a client library could simplify these tasks, but at this moment not every platform has a mature client library available.

What do you mean by converting JSON-API to a plain JS object of my choice? In the sense of supporting multiple media types? 

What I'm trying to achieve is making the API design as simple as possible for most use cases, but also facilitate hypermedia links for relations, operations and more advanced use cases.

**Comment by ksimka** [comment]
> What do you mean by converting JSON-API to a plain JS object of my choice?

We have one function that converts this

``` json
{
  "type": "articles",
  "id": "1",
  "links": {
    "self": "http://example.com/articles/1"
  },
  "attributes": {
    "title": "Rails is Omakase",
  },
  "relationships": {
    "author": {
      "data": {"type": "people", "id": 1}
    }
  },
  "included": [
    {
      "type": "people",
      "id": 1,
      "name": "John Doe",
      "photo": "http://some-url/to/the/photo"
    }
  ]
}
```

to this

``` json
{
  "id": 1,
  "title": "Rails is Omakase",
  "author": {
      "id": 1,
      "name": "John Doe",
      "photo": "http://some-url/to/the/photo"
  }
}
```

So when we need raw data, we don't bother what's in response. You can do a similar one corresponding to your needs.

**Comment by joostfarla** [comment]
That's a good solution if you are writing the client code yourself, but that's not the case here. I would rather not bother the client with (platform-specific) conversion functions. I want to provide maximum flexibility, but also make it dead simple for the most common use cases. That's why I wanted to include a minimal subset of the related attributes somewhere. 

I'm still wondering if that would be valid?

**Comment by ksimka** [comment]
> I'm still wondering if that would be valid?

Technically — no, since attributes and relationships together are fields, so you will get a conflict. You either have an attribute "author" or relationship "author", not both. (But it's better not to trust me and ask one of maintainers :) )

**Comment by ethanresnick** [comment]
I agree with @ksimka that what you're proposing isn't technically valid. I think the best way to go would be to put the `name` and `photo` fields in the `meta` member for the author relationship, like this:

```
{
  "data": [{
     "type": "articles", 
     "id": "1",
     "attributes": { //... },
     "relationships": {
       "author": {
         "type": "authors",
         "id": "12",
         "links": {
           "related": "http://example.com/authors/12"
         },
         "meta": {
           "name": "John Doe",
           "photo": "http://some-url/to/the/photo"
         }
       }
     }
  }]
}
```

This is compliant because resource identifier objects are allowed to have a `meta` member. Meanwhile, any generic JSON API client can still correctly identify the relationship and fetch the full author data.

Using fields would also be a fine way to go. Yes, it would increase client complexity, but it would also give generic clients more information about your resources (since a generic client can't assume anything about the meaning of `meta` when it's used as described above). Using that approach, you'd construct a URI like `http://example.com/articles?include=author&fields[people]=name,photo`.

**Comment by joostfarla** [comment]
@ethanresnick @ksimka thanks for your thoughts!
