### ISSUE TITLE
Uniquely identify resources with URL-based APIs

### ISSUE THREAD

**Issue by oriolgual** [json-api/json-api#84]
Maybe I'm missing something, but as stated [here](https://github.com/json-api/json-api/blob/gh-pages/format/index.md#singular-resources-1) a resource MAY include an `id`.

If the response doesn't return an `id` how can the client uniquely identify a resource from another? Is the `href` a MUST? Or it's up to the API implementation?

**Comment by steveklabnik** [comment]
I believe that MAY should be at least a SHOULD, and possibly a MUST. I haven't been reading a whole lot of the ID-based style, because @wycats and I have a plan to unify them that we're working on.

@wycats? Why did you write this as MAY?

**Comment by SphtKr** [comment]
One use case for not requiring this would be where objects have composite keys--though that seems to be frowned upon these days (but one I've had to deal with, especially with legacy systems). However, while in theory a client could be built to support this, I'm betting most will require a single key field anyway. So it probably might as well be MUST.

**Comment by oriolgual** [comment]
I agree that not all resources might have a single key field, that's why I also asked if `href` (or a link to self) is a MUST or not.

**Comment by rkh** [comment]
Strongly identifying a resource by href in requiring that to be included does not work for resources that do not have an endpoint returning just that document. Other documents in from the same URI it came from would have the same href (unless omitted) and would thus mess with the client.

**Comment by rkh** [comment]
An example endpoint that would not be mappable to json-api if including href becomes a MUST is the /repos/:id/caches endpoint in the Travis CI API.

**Comment by dgeb** [comment]
#182 clarifies `id` as a SHOULD requirement after a fair bit of discussion in #181
