### ISSUE TITLE
Specify the relationship between self links and base URIs

### ISSUE THREAD

**Issue by ethanresnick** [json-api/json-api#840]
Details [here](https://github.com/json-api/json-api/pull/834#issuecomment-131192713). I'm opening this as a reminder until we can work up a PR.

**Comment by ethanresnick** [comment]
I'm closing this, since base URIs actually aren't necessary, as none of the values in `links` can be "relative references"; they must be full URIs. See https://github.com/json-api/json-api/pull/834#issuecomment-141631788

However, an extension could support relative URIs and, to that end, I'm reffing #794, so that it can take this use case for the extension system into account.

**Comment by ethanresnick** [comment]
cc @0x8890 in case you're still interested in this

**Comment by gr0uch** [comment]
this breaks a few existing implementations (including mine).

**Comment by gr0uch** [comment]
Refs https://github.com/fortunejs/fortune-json-api/commit/cf703304a97f389765b926d8e914a3c879c9e2bd.

**Comment by ethanresnick** [comment]
@0x8890 I don't want to break any implementations, but I'm not sure how to avoid that here (since the other option, allowing partial URLs, would also break some clients, namely those that expect a full URI). If you have any ideas, though, for how to resolve this better, let me know!

**Comment by gr0uch** [comment]
Solution is simple: just allow relative paths.

**Comment by ethanresnick** [comment]
But then that breaks existing clients...
