### ISSUE TITLE
`additionalProperties: false` in JSON Schema

### ISSUE THREAD

**Issue by ethanresnick** [json-api/json-api#851]
The JSON Schema we host now at jsonapi.org currently says that additional properties are not allowed in any spec-defined objects, which is correct:

> "Unless otherwise noted, objects defined by this specification MUST NOT contain any additional members."

However, the spec also says that, if clients and servers _do_ encounter any additional properties, they must ignore them, which allows us to extend the base objects in the future.

I'm worried that some server devs will use the current schema to validate incoming request documents, and then (inadvertently) their servers will inadvertently reject documents by future clients (i.e. with extra properties) that they should accept.

So, I see a few options:
1. We could change the schema to say `additionalProperties: true`. This removes the risk of servers/clients rejecting valid documents because they check them against our schema, but it also makes the schema slightly less useful for clients/servers to use in their test suites to check that they're always producing valid documents.
2. We could add a prominent note (which some will nevertheless overlook) saying that, while it's fine to use this schema to validate documents your code is producing, you shouldn't use it to validate incoming documents.
3. We could create two schema versions, one for the test suite case and one for incoming document validation...but that seems like a lot to maintain.

**Comment by bf4** [comment]
All good points.  Maybe the can be addressed by naming, having 'the schema' aka spec validation version and a 'production' version (I hesitate to say strict and transitional).

I don't know json_schema well enough if such a thing is supported within it and lazy me not looking right now :)

Some erb-type doc generator could allow two versions from one source for sure.

**Comment by ethanresnick** [comment]
Closing in favor of #867
