### ISSUE TITLE
Plans to update jsonapi.org/schema from draft-04 to 1.0?

### ISSUE THREAD

**Issue by bf4** [json-api/json-api#852]
Re: 
- https://github.com/json-api/json-api/pull/440
- http://jsonschemalint.com/draft4/#
- https://github.com/json-api/json-api/blob/6a410c0068dcce1813ac4c0b5a875adbef759729/faq/index.md#is-there-a-json-schema-describing-json-api-

If so, how would one help going about that? What's the source of truth to validate it against?

**Comment by ethanresnick** [comment]
I'm confused...I don't think there is a JSON Schema 1.0; draft 4 appears to be the [latest version](http://tools.ietf.org/html/draft-zyp-json-schema-04).

**Comment by bf4** [comment]
oh, brain fart, you're right. I was thinking that referred to JSON API 1.0.
