### ISSUE TITLE
json-api should support json-ld

### ISSUE THREAD

**Issue by danja** [json-api/json-api#854]
JSON-LD is a transparent addition to JSON data that makes it first-class Linked Data, desirable for any Web-oriented systems, according to Tim Berners-Lee, inventor of the Web.

see: 

https://en.wikipedia.org/wiki/Linked_data  

http://codyburleson.com/2015/07/28/the-amazing-power-of-the-link-in-linked-data/

http://json-ld.org/

**Comment by ethanresnick** [comment]
This is in the works. See https://github.com/json-api/json-api/issues/587 (that issue's closed until the extension system is finished, but it's definitely on the radar).

**Comment by danja** [comment]
Hmm, I'm a little confused by the closing of issues that are still effectively open... But still, glad this is on your radar. Hopefully the links above will give it a bigger bleep :)
