### ISSUE TITLE
the format page can be difficult to navigate

### ISSUE THREAD

**Issue by fivetanley** [json-api/json-api#855]
Hi JSONAPI team!

I'm reading throughs some of the spec for some Ember Data implementation details. I'm using Chrome, and the menu can be kind of difficult to navigate because I have to scroll down to the bottom of the page in order to see the last few menu items, instead of the menu being scrolled separately.

Here's a video demonstrating the issue: ![video demonstrating issue](https://dl.dropboxusercontent.com/s/0h29u2bq2vlk5el/2015-08-23%20at%2010.58%20AM.gif)

(sorry for the quality, the tool i used wasn't that good)

And a screenshot of what happens when you do visit the bottom of the page. ![screenshot demonstrating scroll issue](https://dl.dropboxusercontent.com/s/jrfkfe8fleq5lq4/2015-08-23%20at%2010.56%20AM.png)

**Comment by ethanresnick** [comment]
Thanks for submitting! We already have a couple issues for this, though your report inspired me to take another crack at a solution, so I'm closing this in favor of those tickets. See https://github.com/json-api/json-api/pull/856 and #831
