### ISSUE TITLE
formatting is really messed up on Firefox/Linux

### ISSUE THREAD

**Issue by steveklabnik** [json-api/json-api#858]
![2015-08-23-200848_604x511_scrot](https://cloud.githubusercontent.com/assets/27786/9430913/c3dbb638-49d2-11e5-9498-beceda08c50b.png)

O_O

**Comment by jamesplease** [comment]
![](http://www.countryhealthsa.sa.gov.au/Portals/0/Graphics/IE%20Best%20viewed-paint7.png)

**Comment by ethanresnick** [comment]
Should be fixed by #860.
