### ISSUE TITLE
archive of old release

### ISSUE THREAD

**Issue by equivalent** [json-api/json-api#873]
Hi, is there a url somewhere to the older page version (before 1.0, from around dec 2014 ? ) 

the reason is that I've used that version to create application, and I've need to stick url to the app Documentation for the reference.

**Comment by tkellen** [comment]
We're going to maintain a history of versions for everything post 1.0 on the website. If you want to link to something leading up to 1.0, you'll (unfortunately) need to mine through the git history and link directly to the markdown file.

**Comment by equivalent** [comment]
ok there is one now http://jsonapi-rc3.herokuapp.com/
