### ISSUE TITLE
Angular-jsonapi

### ISSUE THREAD

**Issue by jakubrohleder** [json-api/json-api#880]
For past few months I've been implementing JSON API client for angular.js users. Currently it is in the 1.0.0-alpha state, but I'm planning stable 1.0.0 to be released in the near future. It is accessible at [jakubrohleder/angular-jsonapi](https://github.com/jakubrohleder/angular-jsonapi).

Documentation is only partially ready, so everyone who is interested in using/collaborating - feel free to post issues.

Please also add the link to the Implementations section on the website.

**Comment by ethanresnick** [comment]
@jakubrohleder Awesome! I'll get it added to the implementations page momentarily.

cc @TechAtNYU/infrastructure-team

**Comment by jakubrohleder** [comment]
Great, Thanks mate!

**Comment by ethanresnick** [comment]
Added.
