### ISSUE TITLE
PATCH is misused in the specification for Many-TO-Many Relationships

### ISSUE THREAD

**Issue by buckmaxwell** [json-api/json-api#885]
As you can see in the photo, the PATCH method is being misused.  Rather than having its usual additive behavior, it suddenly is doing a full replace as if it was a PUT! I suggest that PATCH have its normal behavior so that we don't punish good HTTP conforming front-end developers by deleting all their relationships when all they wanted to do was add one.  I suggest that if a developer wants to do a 'remove all' on tags (for example) they just call delete on /articles/1/relationships/tags.

<img width="769" alt="screen shot 2015-09-17 at 12 39 50 pm" src="https://cloud.githubusercontent.com/assets/6210452/9940230/8643be2e-5d3c-11e5-8bdb-38c45dba742a.png">

**Comment by buckmaxwell** [comment]
And you know what.  The To-One relationships shouldn't be a PATCH either! These should both be PUT.  You can't just use PATCH because you use it everywhere else.

**Comment by ethanresnick** [comment]
> Rather than having its usual additive behavior, it suddenly is doing a full replace as if it was a PUT!

I can see how the behavior you cite might be a bit unexpected, since a request like:

```
PATCH /articles/1

{ 
  "data": {
    "attributes": {}
  }
}
```

wouldn't change anything about the resource, while your the request you cite does overwrite the  resource's value.

However, this isn't a _prohibited_ use of PATCH; PATCH is allowed to do full replacement just like PUT. PUT might be marginally better (in that it offers a guarantee of idempotence that PATCH doesn't), and maybe we'll add support for PUT, but PATCH is certainly allowed.

> I suggest that PATCH have its normal behavior so that we don't punish good HTTP conforming front-end developers by deleting all their relationships when all they wanted to do was add one.

If a dev wants to add to a to many relationship, they can `POST` to the relationship URI, which is both a convenient and compliant way to do an addition.

**Comment by ethanresnick** [comment]
> I suggest that if a developer wants to do a 'remove all' on tags (for example) they just call delete on /articles/1/relationships/tags.

That would make sense if we weren't already using DELETE, with a body, to DELETE only certain members of the relationship. We may [phase out](https://github.com/json-api/json-api/issues/838#issuecomment-133088670) that use of DELETE though, in which case we could introduce this new one. (We also could allow both uses of DELETE, i.e. with and without a body, simultaneously, but that's probably a bad idea, because some HTTP intermediaries might mistakenly strip out a DELETE body and, in that case, it's much better for the request to fail than for the full relationship to be accidentally deleted.)

**EDIT**: actually, the use of DELETE you're proposing might not make sense anyway, because the relationship still exists after the DELETE goes through (it's just empty).

**Comment by dgeb** [comment]
I agree with @ethanresnick. Also see http://jsonapi.org/faq/#wheres-put for more details re: PATCH vs. PUT usage.

Note that your server could _also_ implement PUT for full replacement of relationships, but that would be outside the scope of this spec.

**Comment by ethanresnick** [comment]
> Note that your server could also implement PUT for full replacement of relationships, but that would be outside the scope of this spec.

Yup. The only thing I'd add to that, @buckmaxwell, is: if you do implement PUT, make sure the content you're receiving/sending from that endpoint doesn't use the JSON API media type. That way, if we do add PUT support into the spec for this case, there's no risk of our addition conflicting with your server.

**Comment by buckmaxwell** [comment]
@ethanresnick and @dgeb   I see where you are coming from but I think your assertion that PATCH can be used to do a full replace is oversimplified. 

According to the RFC, in a PUT request, the enclosed entity is considered to be a modified version of the resource stored on the origin server, and the client is requesting that the stored version be replaced. With PATCH, however, the enclosed entity contains a set of instructions describing how a resource currently residing on the origin server should be modified to produce a new version.

The "set of instructions", in all other cases of this spec is a partial representation of the object.  I would argue that this case is a bit of a gotcha.  

I appreciate that I am fully licensed to support PUT in my own servers, but I like this spec quite a bit and am currently implementing some tools that can create instant JSON APIs based on sqlalchemy data models.  Because I'll release this tool open source, I want to make sure it complies to this standard without a lot of added personal choices.  That said, I'd feel really weird about implementing it this way without completely understanding how it complies with the RFC standard.  I really don't see how it is RFC compliant yet, but I have appreciated you guys taking the time to explain your choice.

**Comment by buckmaxwell** [comment]
@ethanresnick , @dgeb I mean usually a "set of instructions" is more like, 

Original:

``` json
{
  "baz": "qux",
  "foo": "bar"
}
```

Patch:

``` json
[
  { "op": "replace", "path": "/baz", "value": "boo" },
  { "op": "add", "path": "/hello", "value": ["world"] },
  { "op": "remove", "path": "/foo"}
]
```

Result:

``` json
{
   "baz": "boo",
   "hello": ["world"]
}
```

I admit, I like the simplistic [jsonapi](http://jsonapi.org) approach much better.  But usage of the jsonapi spec makes people infer that patch does a partial replace if an option is not specified.  This means that if the path exists it will be updated and if not it will be created.  There would be  no reason to assume the JSON API spec would ever infer a delete except for if they had done the thorough multiday reading that I did.

**Comment by buckmaxwell** [comment]
@ethanresnick , @dgeb Well guys, I think I've decided you're right.  Thanks for letting me talk through this...my hope is maybe someone else who is confused will later stumble upon this issue.

Usually it goes something like:

``` json
{
"data":{"attributes":{}, "rels":{} }
}
```

or 

``` json
{
"data":[{"attributes":{}, "rels":{}}]
}
```

In most PATCH reqs we change the update the contents of attributes or relationships.  In this one we update data itself.  Setting data to null or an empty set in a PATCH totally does what you want.

Good call.

Best,
@buckmaxwell

**Comment by ethanresnick** [comment]
@buckmaxwell I'm glad you're convinced :) And yes, I agree that it still is a bit of a gotcha, even if it's permitted by the PATCH rfc. Also, I'm glad to hear that you like the specification overall and I'm excited to see the tools you come up with! I retweeted the mention of your library and, if you're ok with it, would love to add it to the [implementations page](http://jsonapi.org/implementations/) too.

**Comment by buckmaxwell** [comment]
@ethanresnick yea please do! Thanks for the retweet.  It's still a work in progress, but we're now using it at one of the companies I work for and it does a pretty good job.  It should be getting a bit more functional every day.  Thanks for the work you guys did with this.
