### ISSUE TITLE
Proposal for type namespaces

### ISSUE THREAD

**Issue by youroff** [json-api/json-api#896]
I'm working on PR for `active_model_serializers` gem:
https://github.com/rails-api/active_model_serializers/pull/1216

Right now standard doesn't say anything about namespace declaration in `type` field, and current behavior of ams is just to glue namespace segments by the same separator that is used for class name processing. So `Namespaced::SuperModel` becomes `namespaced_super_model`, which doesn't allow for distinguishing between this one and `NamespacedSuperModel`.

Current proposal from ams team is to use double dash for this purpose and formally it complies standard, however I think something like `/` or `:` or `.` would serve better. So here are variants of proposals:

1) Can we let member names contain any of these symbols to reflect namespace of the model? Probably a period as it's url-safe?

2) Or can we create namespace attribute next to type and pass the namespace there?

3) Or can we recommend passing namespace in meta?

**Comment by steveklabnik** [comment]
Is this a dup of https://github.com/json-api/json-api/issues/850 ?

**Comment by youroff** [comment]
Seems like. Sorry. ;) Should I just close this one?

**Comment by steveklabnik** [comment]
Yeah, let's consolidate discussion over there :+1:
