### ISSUE TITLE
How to represent nested errors?

### ISSUE THREAD

**Issue by myoung8** [json-api/json-api#899]
Currently, the spec gives an example of attributes for one top-level resource:

```
{pointer: 'data/attributes/first_name'}
```

What if an API accepts nested attributes and returns nested errors? (e.g. creating an Organization and a User at the same time--very common in signup flows)

A possible solution could be:

```
{pointer: /data/<nested-resource-name>/attributes/<attribute>}
```

So if you had errors on an Organization and User (with Organization being the top-level model in this case):

```
{pointer: 'data/attributes/name'} # an error on the Organization
{pointer: 'data/users/attributes/email'} # an error on the User
```

**Comment by ethanresnick** [comment]
> What if an API accepts nested attributes and returns nested errors?

First, let me clear up a misconception: JSON API doesn't allow nested resource objects; instead, it always returns/accepts separate resource objects as siblings, that are then linked together through a relationship. This approach prevents duplication and other problems that can arise when the same nested resource would need to be returned multiple times or needs to be linked to multiple resources. (See the Compound Documents section of the spec for how this works in responses; in requests, like to create an Organization with a User, an analogous approach will apply, though the details haven't been finalized yet (see #795)).

Still, some nesting is allowed, in that a field of a resource can hold an object/array, which can then contain more nested values, like this:

```
POST /people
{
  "type": "people",
  "attributes": {
    "name": {
      "first": "",
      "last": "Resnick"
    }
  }
}
```

Then, the error in the response would just use `"pointer"` to indicate that the nested `"first"` field is the source of the problem, like this:

```
{
  "errors": [{
    "title": "Invalid first name", 
    "details": "The first name cannot be empty",
    "source": {
      "pointer": "/data/attributes/name/first"
    }
  }]
}
```

JSON Pointer is it's [own spec](https://tools.ietf.org/html/rfc6901) that describes how to point to any value in a JSON document. Therefore, for any error—even if the document is malformed under JSON API—you can provide a pointer to the source of the error. We don't currently allow the nesting your original question was about, but even if we did, the solution would still be to use the real pointer to place in the request document where the problematic nested attribute was provided.
