### ISSUE TITLE
Representing embedded resources?

### ISSUE THREAD

**Issue by jimsynz** [json-api/json-api#9]
Is the following example valid?

``` json
{
  "rels": {
    "authors.photo": "http://example.com/people/{photos.author}/photos/{photo.id}"
  },
  "authors": {
    "id": 1,
    "href": "http://example.com/people/1",
    "title": "Tom Dale",
    "rels": {
      "photos": [1]
    }
  },
  "photos": {
    "id": 1,
    "href": "http://example.com/people/1/photos/1",
    "title": "Hamster",
    "src": "images/hamster.png",
    "rels": {
      "comments": [ 1, 5, 12, 17 ],
      "authors": 1
    }
  }
}
```

I'm specifically worried about embedded documents that can only be accessed via their parent document (eg [Mongoid's embedded relationships](http://mongoid.org/en/mongoid/docs/relations.html#embeds_many)) but this would seem relevant to Rails' embedded resources also.

**Comment by wycats** [comment]
I'm not sure I understand why the example shouldn't be valid. What am I missing?

**Comment by jimsynz** [comment]
I guess I'm just wondering about how we can represent that one record not only relates to another, but that it is required. In this context, you can't create a photo unless you know the author's id and how to construct a URL for it.

**Comment by steveklabnik** [comment]
This is an application-level concern, your profile should discuss it.
