### ISSUE TITLE
Multiple Different Error HTTP Response Codes == 400 for the whole response?

### ISSUE THREAD

**Issue by ghost** [json-api/json-api#901]
In the [multiple errors example](http://jsonapi.org/examples/#error-objects-multiple-errors), a error response with multiple errors with multiple error codes results in a 400 error code for the whole response. Should we always return a 400 if we have disparate error codes?

I apologize if this is documented somewhere (couldn't find it).

**Comment by ethanresnick** [comment]
It'll usually be 400, but not always. Here's the relevant text from the spec:

> When a server encounters multiple problems for a single request, the most generally applicable HTTP error code SHOULD be used in the response. For instance, 400 Bad Request might be appropriate for multiple 4xx errors or 500 Internal Server Error might be appropriate for multiple 5xx errors.

But things other than 400 or 500 could be appropriate too. For example, if the user tries to PATCH two fields on a resource, both of which they don't have access to, each of those errors might independently be a 403, so a 403 could be used for the whole response as well.

Ultimately, covering every case is impossible, so the spec doesn't try. Just follow HTTP and use your best judgement
