### ISSUE TITLE
Usage of relationships objects and data within them

### ISSUE THREAD

**Issue by groyoh** [json-api/json-api#902]
First of all, thanks for this great spec. My team uses JSONAPI and we are pretty excited about it. Unfortunately, we have stumbled upon issues and questions concerning the usage of _relationships objects_ and _data_ within _relationships objects_. We did not manage to find out exactly in which case the _relationships objects_ should be present and what they should contain. Here are the different cases that we found out and couldn't sort out when reading the spec (we assume that we only use _data_ and don't use _links_ or _meta_).
- Relationships are present only when including them (whether they are null/empty or not).

``` json
// GET http://api.example.com/articles/123
{
  "data": {
    "id": "123",
    "type": "articles"
  }
}

// GET http://api.example.com/articles/123?include=author,comments
{
  "data": {
    "id": "123",
    "type": "articles",
    "relationships": {
      "author": {
        "data":{
          "id": "2",
          "type": "people"
        }
      },
      "comments":{
        "data": []
      }
    }
  },
  "included": [{
    "id":"2",
    "type": "people",
    "attributes":{
      "age": 30
    }
  }]
}
```
- Relationships are present when non null/empty or when including them.

``` json
// GET http://api.example.com/articles/123
{
  "data": {
    "id": "123",
    "type": "articles",
    "relationships": {
      "author": {
        "data":{
          "id": "2",
          "type": "people"
        }
      }
    }
  }
}

// GET http://api.example.com/articles/123?include=author,comments
{
  "data": {
    "id": "123",
    "type": "articles",
    "relationships": {
      "author": {
        "data":{
          "id": "2",
          "type": "people"
        }
      },
      "comments":{
        "data": []
      }
    }
  },
  "included": [{
    "id":"2",
    "type": "people",
    "attributes":{
      "age": 30
    }
  }]
}
```
- Relationships are always present for to-one relationships (whether they are null or not) but present for to-many relationships only when we include them (as stated at https://github.com/json-api/json-api/issues/803#issuecomment-118870497). This does not feel consistent for us as a client might think that a relationship is empty whereas it is just not included. It is also impossible for a client to get the ids of the to-many relationship without including the relationships.

``` json
// GET http://api.example.com/articles/123
{
  "data": {
    "id": "123",
    "type": "articles",
    "relationships": {
      "author": {
        "data": null
      }
    }
  }
}

// GET http://api.example.com/articles/123?include=author,comments
{
  "data": {
    "id": "123",
    "type": "articles",
    "relationships": {
      "author": {
        "data":null
      },
      "comments":{
        "data": [{ "id": "2", "type": "comment" }]
      }
    }
  },
  "included": [{
    "id": "2",
    "type": "comment",
    "attributes": {
      "content": "Awesome spec!"
    }
  }]
}
```
- Relationships are always present (whether they are null/empty or not). This may lead to some additionnal overhead for fetching the relationships id(s) (when using join tables for example).

``` json
// GET http://api.example.com/articles/123
{
  "data": {
    "id": "123",
    "type": "articles",
    "relationships": {
      "author": {
        "data":{
          "id": "2",
          "type": "people"
        }
      },
      "comments":{
        "data": []
      }
    }
  }
}

// GET http://api.example.com/articles/123?include=author,comments
{
  "data": {
    "id": "123",
    "type": "articles",
    "relationships": {
      "author": {
        "data":{
          "id": "2",
          "type": "people"
        }
      },
      "comments":{
        "data": []
      }
    }
  },
  "included": [{
    "id":"2",
    "type": "people",
    "attributes":{
      "age": 30
    }
  }]
}
```

Could you please tell me which one of these previous cases is correct? Or describe the proper usage if it is not among these cases.

It would also be great to have more examples or a deeper explanation within the spec itself.

**Comment by ethanresnick** [comment]
@groyoh Glad your team is enjoying the spec!

The case that is most correct is the last one (i.e. relationships are always present). The only time when a relationship shouldn't be present is if it's been filtered out with the `?fields` parameter. In this sense, relationships are just like attributes.

To your point about the possible overhead of including the relationship ids in to-many relationships: this is exactly why `"links"` can be used as a substitute for `"data"`!

So, if, in your example, the `"comments"` relationship that might contain a lot of ids or would otherwise be  expensive to return with `"data"`, you can return it like so:

``` js
{
  "data": {
    "id": "123",
    "type": "articles",
    "relationships": {
      "author": { /* author data here */ },

      "comments":{
        // omit data, but include a link that the client can request to get all the related ids. If 
        // it would be more convenient for it to get the related resources directly (rather than
        // just their ids), you could make the link below a "related" link instead of a "self" link.
        "links": {
          "self": "http://example.com/articles/123/relationships/comments" 
        }
      }
    }
  }
}
```

Does that answer your question?

As for clarifying this in the spec, I'm not sure I could write one without knowing more about exactly which parts were confusing. But I'd be very open to a PR that clarifies this if you're up for writing one—the other editors and I are always trying to make things easier to understand!

**Comment by groyoh** [comment]
@ethanresnick thanks a lot for your answer. This is exactly the explanation we were looking for.
As for clarifying the specs, I will try to point out the confusing points in an upcoming comment and if possible create a PR for it.
