### ISSUE TITLE
Updating To-One Relationships with primary data

### ISSUE THREAD

**Issue by smcclstocks** [json-api/json-api#903]
The spec doesn't seem to be explicitly clear on how to break the relationship or I could be overlooking it.

I see http://jsonapi.org/format/#crud-updating-to-one-relationships:

```
PATCH /articles/1/relationships/author HTTP/1.1
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "data": null
}
```

but that is for breaking the relationship when using the relationship link not when saving with primary data. @wecc in the ember-data slack room said ember-data would set "data" to null when saving with the primary data but also noted the spec wasn't totally clear on it. Could we make the spec totally clear or could you reference the part of the spec where it is? Thanks!

**Comment by tkellen** [comment]
Hey @smcclstocks! Just a quick heads up from our [contribution guidelines](https://github.com/json-api/json-api/blob/gh-pages/CONTRIBUTING.md):

> Our issue tracker can always be used to address internal inconsistencies within the current specification, or updates to the website. Beyond this, we try to limit discussions to those which focus on problems that will be dealt with in the next version of JSON API. A roadmap can be found on the about section of our website.

Can you please direct questions like this to our [discussion forum](http://discuss.jsonapi.org/) in the future? Thanks!

## 

All of that said, the specification is very clear about this. From http://jsonapi.org/format/#crud-updating-to-one-relationships:

> A server **MUST** respond to `PATCH` requests to a URL from a to-one relationship link as described below.
> 
> The PATCH request **MUST** include a top-level member named data containing one of:
> - a resource identifier object corresponding to the new related resource.
> - `null`, to remove the relationship.

**Comment by tkellen** [comment]
Whoops, I mis-read your issue. Looks like we could use another example here. I'd gladly land a PR for one!

**Comment by tkellen** [comment]
Additionally, this is the correct request:

```
PATCH /articles/1 HTTP/1.1
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "data": {
    "type": "articles",
    "id": "1",
    "relationships": {
      "author": {
        "data": null
      }
    }
  }
}
```

**Comment by smcclstocks** [comment]
The example you show is how wecc described ember-data would behave as well. Thanks for following up.. i'll try to put a PR together.

**Comment by ethanresnick** [comment]
Great @smcclstocks! More examples are always appreciated.

For reference, the passage in the spec that covers this case (at least by my reading) is:

> If a relationship is provided in the `relationships` member of a resource object in a `PATCH` request, its value MUST be a relationship object with a `data` member. The relationship's value will be replaced with the value specified in this member.
