### ISSUE TITLE
Cloud we change the name of markdown files from index.md to README.md? 

### ISSUE THREAD

**Issue by bobintornado** [json-api/json-api#905]
So that Github will automatically render them. :smile:

**Comment by ethanresnick** [comment]
Changing their names would break the URLs (since this is a Jekyll site), and Github will already automatically render the file if you [open it directly](https://github.com/json-api/json-api/blob/gh-pages/_format/1.0/index.md). So I think it's best to just leave things as is.

**Comment by bobintornado** [comment]
Ic Ic.
