### ISSUE TITLE
Naming of this standard makes it extremely hard to discover/search/query it

### ISSUE THREAD

**Issue by tolgaek** [json-api/json-api#906]
I'm sure it was brought up before but couldn't find anything in closed issues.

It's very hard to find information on the json:api and google for it. Most people who hear about it want to compare it to something they know. So googling something like 'odata vs json:api' will not yield any useful resources.

I think naming of this standard has to be updated to make it searchable.

**Comment by steveklabnik** [comment]
I understand the concern, but there's already a media type registration with the name, and we've been using it for years. The name isn't going to change.
