### ISSUE TITLE
how JSON:API relates to swagger/RAML/API Blueprint

### ISSUE THREAD

**Issue by ducin** [json-api/json-api#909]
Hello All,

Just came accross the JSON:API specification, reading about it. I can't find information how does it relate to API-definition specifications: Swagger, RAML, API Blueprint. At first sight, JSON:API and these 3 solve similar purpose: they define API contract to be conformed to by both Frontend and Backend. This enables auto-tools such as docs generators, stub server generators, API-test generators, etc. And these 3 are proud of their stack tools, e.g. see _Tooling_ in https://apiblueprint.org/.

So, mainly, my question is: is JSON:API another alternative to {swagger, RAML, API Blueprint}? If not really, what is its purpose? What is its advantage over these 3? I know it's a specification for defining APIs. But so are above 3 mentioned.

No hate here, not at all. Just asking. Maybe JSON:API has something interesting I don't know about.

**Comment by steveklabnik** [comment]
Could you post this on http://discuss.jsonapi.org/ please? We try to keep this kind of discussion over there. :smile:

**Comment by ducin** [comment]
@steveklabnik I know this is your project :) but it is not really convenient to force people to register in a custom system in order to discuss anything. Especially that I just wanted to ask one question and, might be, nothing more ever - and now I received a 3-4 page email with a brand new interface and lots of colours. What for? This is discouraging somehow. If you want to categorize topics, you may use tighub issues.

If all open source systems required that, there'd be a global mess...

However, I did a copy-paste into http://discuss.jsonapi.org/ as you wanted.

**Comment by steveklabnik** [comment]
I can understand your frustration, however, GitHub issues aren't well suited towards discussion and help. Having a clear separation between "questions and help about use" vs "working on the project itself" is something that virtually all projects I've ever worked on have, and to good effect.
