### ISSUE TITLE
Consider an alternative phrasing to "anti-bikeshedding *weapon*"

### ISSUE THREAD

**Issue by dgeb** [json-api/json-api#918]
See https://twitter.com/gr2m/status/665622128230797312

I think I like @FrancescoK's suggestion best re: "cure". Something along the lines of "JSON API is the cure for bikeshedding".

**Comment by gr2m** [comment]
Thanks for putting it to a discussion. I know this is trivial to many, but it makes a difference to some, including me. And I'm sure we can come up with a good alternative to weapon that everyone would like. I like @FrancescoK’s suggestion "cure", too

**Comment by steveklabnik** [comment]
I'm :+1: on cure

**Comment by varjmes** [comment]
I quite like 'tool'. Just because I'm not sure if bikeshedding is really a sickness. I wouldn't hate the use of 'cure' though. :)

**Comment by tkellen** [comment]
:+1: from me. I opened #919 to resolve.

**Comment by ethanresnick** [comment]
:+1: on cure or tool, though I'd stick with "JSON API is..." rather than "JSON API can be", since the former seems stronger.
