### ISSUE TITLE
Ignore charset parameter for the Content-Type

### ISSUE THREAD

**Issue by cziegenberg** [json-api/json-api#924]
I'm currently implementing the spec and while testing the server, I recognized a problem regarding the encoding. The problem I had was that the Firefox browser (and also all add-ons for Firefox) always added a `charset` parameter to the `Content-Type` header, which violates the JSON API 1.0 spec (this will be fixed with Firefox 44, currently alpha). Also other clients could add this parameter.

Would it be possible to just ignore the `charset` parameter, so that such request doesn't have to result in an error, like it's defined for [JSON](http://www.iana.org/assignments/media-types/application/json) (see note at the end)?

**Comment by ethanresnick** [comment]
Closing this in favor of #837 and #874.

Given that extensions are dragging on, and that I'm thinking more and more that we'll _likely want to add significant media type parameters over time even after we finish extensions_, I'd be fine with merging #874 now. But I know @dgeb had some reservations about that, so I'm happy to defer to him. Either way, though, that's a conversation we can pick up in #874.

**Comment by cziegenberg** [comment]
Great. #874 sounds good to me.
