### ISSUE TITLE
Redefine 204 Status Code conditions for POST requests

### ISSUE THREAD

**Issue by cziegenberg** [json-api/json-api#945]
For POST request the 204 status code depends on if a client-generated ID has been used or not, because in this case the ID isn't generated by the server and so - theoretically - the resulting resource is the same as the resource in the request.

**Problem 1:**
For PUTs and DELETEs, this also depends on added meta data. This can be also added to POST requests, but isn't handled there. So meta data seems to be treated as important data for the client in some cases, in others not.

**Problem 2:**
The server could use default values or calculate values (the derived fields topic) when creating resources, so the client doesn't have to (or is not allowed to) set all fields in the request. So when the client generated the ID and a 204 response was returned, the client would not have the up-to-date/complete resource data.

**Solution:**
To cover all cases, the text should be changed similar to the one in the update section:
"A server MUST return a 204 No Content status code if the creation is successful and the representation of the resource in the request matches the result."

**Comment by tkellen** [comment]
Can you open this as a PR for discussion please? I think I disagree with your framing here but it would be easier to examine in the context of the document itself.

**Comment by cziegenberg** [comment]
Done. I left the "include a Client-Generated ID" part - it's no more neccessary, but perhaps makes it clearer.
