### ISSUE TITLE
Clarify exactly which query parameters are reserved

### ISSUE THREAD

**Issue by ethanresnick** [json-api/json-api#951]
The spec says things like:

> The `filter` query parameter is reserved for filtering data. 

and

> The `page` query parameter is reserved for pagination. 

But it's pretty clear that we don't (only) mean the literal parameters named `page` and `filter`... we also mean parameters like `page[offset]`. (Moreover, the concept of a named query parameter isn't even in RFC 3986, so we should probably mention that it's actually an idea we're getting from—I think—HTML forms.)

We could fix this issue by just specifying the `[...]` form, but I wonder if there's an opportunity here to clean up the design a bit (as reserving too many query parameters is a [bad idea](http://tools.ietf.org/html/rfc7320) anyway, and the notion of a query parameter being "reserved but not specified" has never made much sense to me). 

For now, though, I just wanted to document the issue. Ref: http://stackoverflow.com/questions/33838358/jsonapi-org-correct-way-to-use-pagination-using-the-page-query-string

**Comment by ethanresnick** [comment]
Will be addressed by #1308.

**Comment by jelhan** [comment]
This has been clarified in v1.1 by introducing that the term _query parameter family_ and stating that the entire family is reserved:

> The page query parameter family is reserved for pagination. Servers and clients SHOULD use these parameters for pagination operations.

> The filter [query parameter family](https://jsonapi.org/format/1.1/#query-parameters-families) is reserved for filtering data. Servers and clients SHOULD use these parameters for filtering operations.

> A “query parameter family” is the set of all query parameters whose name starts with a “base name”, followed by zero or more instances of empty square brackets (i.e. []) or square-bracketed legal member names. The family is referred to by its base name.

I'm going to close this issue. Please speak up if you see the need for further clarification.
