### ISSUE TITLE
Conflict between the single exception for full linkage and /articles/1/relationships/comments?include=comments.author

### ISSUE THREAD

**Issue by mcasperson** [json-api/json-api#952]
```
Compound documents require "full linkage", meaning that every included resource
MUST be identified by at least one resource identifier object in the same document. 
These resource identifier objects could either be primary data or represent resource
linkage contained within primary or included resources.

The only exception to the full linkage requirement is when relationship fields that would
otherwise contain linkage data are excluded via sparse fieldsets.
```

My interpretation of this statement is that every entity in the included{} block must have a corresponding resource identifier, unless the included entity is from a field that was excluded via  sparse fieldsets. For example, we might call 

```
/articles?include=articles.author,articles.comments&fields[articles]=author
```

which includes the author and comments for all articles, but only includes the author in the sparse fieldset, resulting in the comments being listed in the included{} block, and not having any other reference:

```
{
  "data": [{
    "type": "articles",
    "id": "1",
    "attributes": {
      "title": "JSON API paints my bikeshed!"
    },
    "links": {
      "self": "http://example.com/articles/1"
    },
    "relationships": {
      "author": {
        "links": {
          "self": "http://example.com/articles/1/relationships/author",
          "related": "http://example.com/articles/1/author"
        },
        "data": { "type": "people", "id": "9" }
      }
    }
  }],
  "included": [{
    "type": "people",
    "id": "9",
    "attributes": {
      "first-name": "Dan",
      "last-name": "Gebhardt",
      "twitter": "dgeb"
    },
    "links": {
      "self": "http://example.com/people/9"
    }
  }, {
    "type": "comments",
    "id": "5",
    "attributes": {
      "body": "First!"
    },
    "relationships": {
      "author": {
        "data": { "type": "people", "id": "2" }
      }
    },
    "links": {
      "self": "http://example.com/comments/5"
    }
  }, {
    "type": "comments",
    "id": "12",
    "attributes": {
      "body": "I like XML better"
    },
    "relationships": {
      "author": {
        "data": { "type": "people", "id": "9" }
      }
    },
    "links": {
      "self": "http://example.com/comments/12"
    }
  }]
}
```

Then we have the statement 

```
GET /articles/1/relationships/comments?include=comments.author HTTP/1.1
Accept: application/vnd.api+json

In this case, the primary data would be a collection of resource identifier objects 
that represent linkage to comments for an article, while the full comments and 
comment authors would be returned as included data.
```

This would seem to indicate the the result should be something like this, where we have a list of resource identifiers returned in the data{} block, and a list of resource objects returned in the included{} block.

```
{
  "data": [{
    "type": "comments",
    "id": "5"
  }],
  "included": [{
    "type": "articles",
    "id": "1",
    "attributes": {
      "title": "JSON API paints my bikeshed!"
    },
    "relationships": {
      "comments": {
        "data": { "type": "comments", "id": "5" }
      }
    },
    "links": {
      "self": "http://example.com/articles/1"
    }
  }]
}
```

If I am reading the JSON API spec correctly, this second result is actually a second case where full resource linkage is not required, because the entities in the included{} block have no other references in the document.

So, am I correct in thinking that there are two exclusions to the full linking requirement, or have in interpreted the spec incorrectly?

**Comment by bintoro** [comment]
The second example request calls for the inclusion of comments and the authors of those comments. The payload you posted has neither; instead, it includes the article, which wasn't requested.

This is how I believe the response should look like:

```
{
  "data": [{
    "type": "comments",
    "id": "5"
  }],
  "included": [{
    "type": "comments",
    "id": "5",
    "attributes": {...},
    "relationships": {
      "author": {
        "data": { "type": "people", "id": "2" }
      }
    }
  }, {
    "type": "people",
    "id": "2",
    "attributes": {...},
    "links": {
      "self": "http://example.com/people/9"
    }
  }]
}
```

So, there is no conflict with the full linkage requirement.

Using `include` at a relationship URL seems fairly pointless to me. Since the first segment of any include path must necessarily be the relationship itself, you get the same result as from the corresponding related resource URL, except that everything is now under the `included` array.

One scenario I can think of where it accomplishes something is when you want to add several items to a relationship, some of which already exist and some need to be created on the fly:

```
POST /articles/1/relationships/tags?include=tags HTTP/1.1

{
  "data": [
    { "type": "tags", "id": <existing ID> },
    { "type": "tags", "id": <new ID> }
  ],
  "included": [{
    "type": "tags",
    "id": <new ID>,
    "attributes": {
      "label": "Python"
    }
  }]
}
```

**Comment by ethanresnick** [comment]
I agree with @bintoro that there's no conflict here, so I'm gonna close this. Feel free to reopen if I've missed something.
