### ISSUE TITLE
Links section improvements

### ISSUE THREAD

**Issue by bintoro** [json-api/json-api#958]
The _Links_ section could use a passage explaining that
- the section itself only aims to define global rules for representing links;
- individual links are context-dependent; and therefore
- the allowed links within a links object as well as their semantics are defined elsewhere.

I already posted a brief line note about this in #957, but a spin-off issue seems more appropriate.

Right now, there's no mention of where link names come from or how they are supposed to be used. The section lists the possible members of a _link object_ yet immediately goes on to talk about `profile` (#957) and `related` without explaining what these things are. It's quite confusing.

This isn't an immediate priority but should be resolved once `links` starts seeing new uses due to extensions and relation links.

**Comment by bf4** [comment]
@bintoro any thoughts on relevance of https://github.com/json-api/json-api/issues/898 to this?

**Comment by bintoro** [comment]
@bf4 Well, the Links section is certainly the right place to explain relative URLs once we agree on the details, but other than that, this issue is more about the links' keys than the URLs.

**Comment by ethanresnick** [comment]
@bintoro's line note in #957 and my response: https://github.com/json-api/json-api/pull/957#discussion_r48570311

**Comment by jelhan** [comment]
The latest version of upcoming v1.1 explicitly discusses the context of a link in the _Links_ section:

> A link’s context is the top-level object, resource object, or relationship object in which it appears.

It links to the sections, which specify allowed members depending of the context.

Do you see further need to clarify this?
