### ISSUE TITLE
Group Collection By

### ISSUE THREAD

**Issue by webpapaya** [json-api/json-api#960]
In the current specification of JSON API I couldn't find anything about grouping collections by a certain attribute, like the SQL Group By statement. Eg. I have users who belong into different groups. I now want to display all groups with all users in this particular group. Should the grouping of this collection be a client only concern? 

Even tough there are libraries out there which are doing those kinds of transformations on the client, I feel like reinventing the wheel in many cases.

**Comment by ethanresnick** [comment]
Currently, yes, JSON API thinks of this as a client concern. 

If your grouping logic is complex, though, and you don't want to duplicate all that logic on the client, you could always add a field in `meta` called `group` and let the server set that field for each resource; then the client would just have to partition based on reading that one field, which should be simple.
