### ISSUE TITLE
Content-type clarification and preflight requests

### ISSUE THREAD

**Issue by dwelle** [json-api/json-api#968]
You specify that the `Content-type: application/vnd.api+json` is **REQUIRED** in all requests, but then within your specification-page examples you don't include it -- instead you specify `Accept` header which I understand is **OPTIONAL**, e.g.

```
GET /articles HTTP/1.1
Accept: application/vnd.api+json
```

Also, is it really necessary to require `Content-Type` header? Doing that will effectively make even `GET`/`POST` requests issue preflight requests (for CORS), which will hurt page responsiveness (added latency). I think the `Accept` header alone would be fine, and it wouldn't produce preflights.

**Comment by bintoro** [comment]
> You specify that the Content-type: application/vnd.api+json is **REQUIRED** in all requests

No, only when there's "JSON API data", which is supposed to mean an HTTP message body. Thus, GET requests are exempt.

The spec should either formally define "JSON API data" or revert to the common HTTP terminology in the Content Negotiation section.

**Comment by dwelle** [comment]
Makes sense. Yea the wording is a bit confusing but mistake is on my part.

The `POST` will still make a preflight, though. I agree including the `Content-type` is semantic and correct, but just a tad annoying (which for some remote users might add up to more than a tad).

**Comment by mphasize** [comment]
I also think it should be mentioned that `GET` and `DELETE` requests **should not** send the `Content-Type` header and that the spec doesn't require them. When reading the spec, it's easy to miss that these requests do not contain JSON API data and therefore don't fall under this rule.

**Comment by jelhan** [comment]
I think this has been clarified in upcoming v1.1 of the specification:

> Clients and servers MUST send all JSON:API payloads using the JSON:API media type in the Content-Type header.

This clearly limits the `Content-Type` header to request and responses, which includes a JSON:API payload.

Do you see further need to clarify?
