### ISSUE TITLE
Categorising multiple relationships to a single resource type?

### ISSUE THREAD

**Issue by MrTrick** [json-api/json-api#970]
I'm wondering how best to represent this case, and not sure how best to structure the JSONAPI response. 
1. A `person` has a `contract` object. 
2. The `contract` object can have multiple `supervisor` (`person`) objects.
3. There are different **kinds** of supervision ('principal', 'alternate', 'co', 'external', 'joint') where there might be more than one of each kind, or none.

Within the `contract`, I could use;

``` javascript
    "relationships": {
        "supervisor": {
            "links": { "self": "/contract/123456/supervisor", "related": "/contract/123456" },
            "data": [
                { "id":"654321", "type": "person"}, 
                { "id":"543210", "type": "person"}, 
                { "id":"432109", "type": "person"}
            ]
        },
        ...
    }
```

But then how to determine which is which?  

I could place each in eg "supervisor_principal", "supervisor_alternate", etc sections, but then how does a consumer who just wants all supervisors know which keys to look at?
(and adding both options seems extremely verbose)

Alternately, is storing a map of (type) to (supervisor id) inside the attributes a 'jsonapi-compliant' way to go?

**Comment by ethanresnick** [comment]
I believe this question was discussed [here](http://discuss.jsonapi.org/t/metadata-about-relationships/86). Please take a look at that link. If it doesn't help, feel free to open a new thread on http://discuss.jsonapi.org/, our discussion forum! For now, I'm going to close this issue here, as we prefer to have these discussions on discuss.

**Comment by MrTrick** [comment]
Thank you @ethanresnick for clarifying. I'm afraid I take @hhware 's side in this too.
In the last API we designed foreign keys were just represented as attributes, lists of attributes or maps of attributes. (depending on multiplicity etc) 
The first-class treatment that 'relationships' get is great, but one loses brevity and flexibility in doing so. (and I'm already struggling to deal with the signal-to-boilerplate ratio)

The suggested solution for promoting foreign keys to being their own object only sounds like a workaround for a technical limitation, not a solution.

Thank you for pointing me towards discuss.jsonapi.org - I hadn't seen links to it anywhere or had it show up in search results! (and IRC is so dead...)
Two suggestions while I've got your attention;  
- Giving the `discuss` greater weight and visibility on the main site?
- The spec is great and detailed, but it doesn't negate the need for lots of examples. How about some recipes for common use cases? Cross-referencing with the spec, even.

**Comment by ethanresnick** [comment]
> I'm afraid I take @hhware 's side in this too.

That's fair. Hopefully the (forthcoming) extension system will address this for you! See #957 for the current version of that proposal.

> - Giving the discuss greater weight and visibility on the main site?
> - The spec is great and detailed, but it doesn't negate the need for lots of examples. How about some recipes for common use cases? Cross-referencing with the spec, even.

I agree with both of those things. It's just been an issue of time & bandwidth. If you're able to submit PRs to address either of those, though, I'd happily accept them!

**Comment by MrTrick** [comment]
>  If you're able to submit PRs to address either of those, though,

Hah! A list of "what not to do", given my current level of expertise...
