### ISSUE TITLE
Enable HTTPS for the page

### ISSUE THREAD

**Issue by Turbo87** [json-api/json-api#974]
http://jsonapi.org/ doesn't seem to support HTTPS at the moment, since I can't get a connection using https://jsonapi.org/. It looks like https://json-api.github.io/json-api/ works quite fine though, apart from the broken resource paths. Is there any reason for not using HTTPS here?

**Comment by Turbo87** [comment]
nevermind, you obviously would need a different HTTPS cert for that domain and GitHub doesn't seem to support that yet...

**Comment by steveklabnik** [comment]
Yes, that's the problem :/
