### ISSUE TITLE
Creating nested resources

### ISSUE THREAD

**Issue by scottgonzalez** [json-api/json-api#979]
The spec talks about fetching resources via nested routes. For example:

> And the following request fetches an article's author:
> 
> ``` http
> GET /articles/1/author HTTP/1.1
> Accept: application/vnd.api+json
> ```

It also talks about linking resources after they've been created:

> In the following example, the comment with ID `123` is added to the list of comments for the article with ID `1`:
> 
> ``` http
> POST /articles/1/relationships/comments HTTP/1.1
> Content-Type: application/vnd.api+json
> Accept: application/vnd.api+json
> 
> {
>   "data": [
>     { "type": "comments", "id": "123" }
>   ]
> }
> ```

However, it does not talk about creating a resource via nested routes. So my question is can the comment be created via a `POST` to the nested resource without specifying any relationship information in the data (since it's implicit from the URL)?

``` http
POST /articles/1/comments HTTP/1.1
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "data": {
    "type": "comments",
    "attributes": {
      "body": "First!"
    }
  }
}
```

_Note: I realize the actual data structure used in the spec is more complicated and the comment needs to be linked to an author. Let's assume that's not the case for the sake of this discussion._

**Comment by dgeb** [comment]
> So my question is can the comment be created via a POST to the nested resource without specifying any relationship information in the data (since it's implicit from the URL)?

The base spec treats URLs as opaque and therefore doesn't have a concept of "nested resources". URL design only shows up as a recommendation, so there's nothing binding.

To answer your question: yes, it's absolutely fine for relationships or attributes to be implicitly set on the server. A server might choose to do so based on who the user is, a segment in the URL, the current data/time, or any number of factors.

**Comment by scottgonzalez** [comment]
Thanks @dgeb. That was my impression, but I was involved in a discussion elsewhere with people who thought this was discouraged, so I figured I'd get a definitive answer.

**Comment by scottgonzalez** [comment]
BTW, your response resolved my issue, so this can be closed unless you wanted to leave it open for others to respond.

**Comment by dgeb** [comment]
Ok, great @scottgonzalez. 

> I was involved in a discussion elsewhere with people who thought this was discouraged

Well, I would say that it's only discouraged in so far as a flat URL structure is _recommended_ but by no means required.

Anyway, I'll close this now but will be glad to reopen if more discussion arises.
