### ISSUE TITLE
Specification Clarity

### ISSUE THREAD

**Issue by hackling** [json-api/json-api#983]
I've been asked to implement JSONAPI on a project that I'm working on. Reading of the specification has raised a few questions for me.
1. What am I supposed to do with unknown parameters?
   I asked around the office and the interpretation varies. If I send a request with correct `page[number] params`, but throw in another one `foo=true`, should I be 400-ing?
2. Pagination - Requesting Pages out of Range
   Say I have 1000 records. I request `page[number]=1002, page[size]=100`, what should I be doing here?
   Should I 400? Should I send back an empty `data: []` section? If I return an empty data array, how should I format the links section.
3. Pagination - Requesting the First and Last Page
   What should the links section look like?
   If I request the first page, should I just omit the `prev` section from `links`, or should I include it, and leave it empty?

**Comment by bf4** [comment]
> What am I supposed to do with unknown parameters? If I send a request with correct page[number] params, but throw in another one foo=true, should I be 400-ing?

interp is up to you. It could be a parameter error or not http://jsonapi.org/examples/#error-objects-invalid-query-parameters

> Should I send back an empty data: [] section? If I return an empty data array, how should I format the links section.

empty data would be correct semantics, in my opinion. links should probably be the same, no? `first, last` and anything else that is useful

> If I request the first page, should I just omit the prev section from links, or should I include it, and leave it empty?

I believe that is up to you. None of the links are required. It's just a spec for their format

**Comment by ethanresnick** [comment]
:+1: to everything @bf4 said. 

Re: 

> If I request the first page, should I just omit the prev section from links, or should I include it, and leave it empty?

I would omit the prev link altogether.
