### ISSUE TITLE
Returning included resources in response to create request

### ISSUE THREAD

**Issue by scottgonzalez** [json-api/json-api#986]
The spec isn't clear on whether related resources may be included in response to a create request. Let's say users may have many profiles and creating a user automatically creates their first profile. Can the profile be returned as a related resource in the `included` member as part of the response? If so, may the client control this behavior using the `include` query parameter?

**Comment by dgeb** [comment]
Yes to both questions. There is a note at the end of the [Inclusion of Related Resources](http://jsonapi.org/format/#fetching-includes) section that makes this explicit:

> Note: This section applies to any endpoint that responds with primary data, regardless of the request type. For instance, a server could support the inclusion of related resources along with a POST request to create a resource or relationship.
