### ISSUE TITLE
Redcarpet -> Kramdown

### ISSUE THREAD

**Issue by steveklabnik** [json-api/json-api#990]
We need to move to Kramdown by May 5. We're currently using redcarpet's tables extension, hopefully kramdown supports it.

**Comment by ethanresnick** [comment]
I'm working on this in the gh-pages-compliance branch.

Tables haven't been a problem (kramdown actually has support built-in) and, with a bit of configuration, I've was able to make most of the other behavior match redcarpets.

The big exception to the above is syntax highlighting, where we were relying on redcarpets to pass the language of each code block through to HTML as a class attribute, which kramdown doesn't seem to do.

**Comment by steveklabnik** [comment]
:+1:

**Comment by ethanresnick** [comment]
It may be a rouge issue too, rather than a kramdown one. Ref https://github.com/jneen/rouge/issues/361 https://github.com/jneen/rouge/issues/379

**Comment by steveklabnik** [comment]
Rouge is very much not-maintained (for good reason, I might add (at leas this is the impression I got from the author on twitter, it looks like it does get a few commits every few months)), so hopefully if it is we can work around it.

**Comment by jamesplease** [comment]
Is this issue closeable since #1039 was merged? :)

**Comment by ethanresnick** [comment]
Yup, thanks!
