### ISSUE TITLE
Optional resource id in PATCH

### ISSUE THREAD

**Issue by scottgonzalez** [json-api/json-api#991]
The spec currently says:

> A resource object MUST contain at least the following top-level members:
> -  `id`
> - `type`
> 
> Exception: The `id` member is not required when the resource object originates at the client and represents a new resource to be created on the server.

I know that `type` and `id` are currently required everywhere for consistency. In some scenarios, the client may not care about the `id` of an existing resource though. For example, an e-commerce site might have a cart for each user, which can be accessed at `/cart`. Because there is only ever one cart available, updating the cart via a PATCH request doesn't require knowing the cart's `id`. Would it be possible to allow such requests to not include the `id` member?

**Comment by beauby** [comment]
As there would be only one logical cart per user-context, I think it would be fine to consider that a cart is uniquely identified by an arbitrary id. Hence, you could provide `"id": "cart"` in your payload and it should remain compliant with the spec.

**Comment by ethanresnick** [comment]
Closing this, as I don't think the spec could change here without it being a BC break, and I'm not sure a change is needed.
