### ISSUE TITLE
Question: Where should relationship errors point to?

### ISSUE THREAD

**Issue by cmanallen** [json-api/json-api#993]
Say I have some relationship named `friend` that has raised an error.  What should the pointer value be?

``` js
{
    "pointer": "/data/relationships/friend", // to the field itself
    "pointer": "/data/relationships/friend/data", // to the data envelope within the friend relationship object
    "pointer": "/data/relationships/friend/data/id" // to the id field that is actually in error
}
```

Is this left to the implementer's discretion or is there an agreed upon pattern?  The specification is unclear on relationship errors.

**Comment by ethanresnick** [comment]
I think there's a bit of discretion here, but generally it makes sense for the pointer to refer to the most specific value possible responsible for the error. So, if you know for sure that the id value caused the error, I'd point to that.

I'm gonna close this, but lmk if that didn't answer your question and we can keep discussing!
